import SPELLS from 'common/SPELLS';
import TALENTS from 'common/TALENTS/priest';

export const HOLY_ABILITIES_AFFECTED_BY_HEALING_INCREASES = [
  SPELLS.DIVINE_HYMN_HEAL.id,
  SPELLS.GREATER_HEAL.id,
  SPELLS.FLASH_HEAL.id,
  SPELLS.PRAYER_OF_MENDING_HEAL.id,
  TALENTS.PRAYER_OF_HEALING_TALENT.id,
  TALENTS.RENEW_TALENT.id,
  TALENTS.HOLY_WORD_SERENITY_TALENT.id,
  TALENTS.HOLY_WORD_SANCTIFY_TALENT.id,
  TALENTS.HOLY_WORD_SALVATION_TALENT.id,
  SPELLS.DESPERATE_PRAYER.id,
  TALENTS.COSMIC_RIPPLE_TALENT.id,
  SPELLS.BINDING_HEALS_TALENT_HEAL.id,
  TALENTS.CIRCLE_OF_HEALING_TALENT.id,
  SPELLS.HALO_HEAL.id,
  SPELLS.DIVINE_STAR_HEAL.id,
  SPELLS.TRAIL_OF_LIGHT_TALENT_HEAL.id,
  TALENTS.POWER_WORD_LIFE_TALENT.id,
];

// better off making things that -dont- proc it perhaps?
export const ABILITIES_THAT_TRIGGER_MASTERY = [
  SPELLS.DIVINE_HYMN_HEAL.id,
  SPELLS.GREATER_HEAL.id,
  SPELLS.FLASH_HEAL.id,
  SPELLS.PRAYER_OF_MENDING_HEAL.id,
  TALENTS.PRAYER_OF_HEALING_TALENT.id,
  TALENTS.HOLY_WORD_SERENITY_TALENT.id,
  TALENTS.HOLY_WORD_SANCTIFY_TALENT.id,
  TALENTS.HOLY_WORD_SALVATION_TALENT.id,
  SPELLS.DESPERATE_PRAYER.id,
  SPELLS.COSMIC_RIPPLE_HEAL.id,
  SPELLS.BINDING_HEALS_TALENT_HEAL.id,
  TALENTS.CIRCLE_OF_HEALING_TALENT.id,
  SPELLS.HALO_HEAL.id,
  SPELLS.DIVINE_STAR_HEAL.id,
  TALENTS.RENEW_TALENT.id, // this is reduced in calculations, due to the initial tick proccing EoL but not the periodic ticks
  SPELLS.TRAIL_OF_LIGHT_TALENT_HEAL.id,
  SPELLS.HOLY_NOVA_HEAL.id,
  SPELLS.GUARDIAN_SPIRIT_HEAL.id,
  TALENTS.POWER_WORD_LIFE_TALENT.id,
  // Trinkets
];

export const ABILITIES_AFFECTED_BY_APOTHEOSIS_TALENT = [
  TALENTS.HOLY_WORD_SERENITY_TALENT.id,
  TALENTS.HOLY_WORD_SANCTIFY_TALENT.id,
  TALENTS.HOLY_WORD_CHASTISE_TALENT.id,
];

export const HOLY_PRIEST_HEALING_INCREASE_AURA = 0.4;
