import SPELLS from 'common/SPELLS';
import TALENTS from 'common/TALENTS/mage';

export const MS_BUFFER_1000 = 1000;

//Frost
export const COMET_STORM_AOE_MIN_TARGETS = 2;
export const SHATTER_DEBUFFS = [
  SPELLS.WINTERS_CHILL,
  SPELLS.FROST_NOVA,
  TALENTS.ICE_NOVA_TALENT,
  SPELLS.GLACIAL_SPIKE_DAMAGE,
  SPELLS.RING_OF_FROST_DAMAGE,
  SPELLS.FREEZE,
];

//Fire
export const FEEL_THE_BURN_MAX_STACKS = 3;
export const IMPROVED_SCORCH_MAX_STACKS = 2;
export const FIRESTARTER_THRESHOLD = 0.9;
export const SEARING_TOUCH_THRESHOLD = 0.3;
export const COMBUSTION_END_BUFFER = 3000;
export const COMBUSTION_DURATION = 12000;
export const SKB_COMBUST_DURATION = 6000;
export const FIRE_DIRECT_DAMAGE_SPELLS = [
  SPELLS.FIREBALL,
  TALENTS.PYROBLAST_TALENT,
  SPELLS.FIRE_BLAST,
  SPELLS.SCORCH,
];

//Arcane
export const ARCANE_CHARGE_MAX_STACKS = 4;
export const ARCANE_TEMPO_MAX_STACKS = 5;
export const ARCANE_TEMPO_HASTE_PER_STACK = 0.02;
export const UNERRING_PROFICIENCY_MAX_STACKS = 30;
export const ARCANE_MISSILES_MAX_TICKS = 8;
export const CLEARCASTING_MAX_STACKS = 3;
export const ARCANE_BLAST_BASE_MANA_COST = 1375;
export const ARCANE_EXPLOSION_BASE_MANA_COST = 5000;
export const TOUCH_OF_MAGI_DURATION = 12000;
export const ARCANE_TEMPO_DURATION = 12000;
