import type { RetailSpell } from 'wow-dbc';
const SPELLS = {
  JAB: {
    id: 100780,
    type: 'baseline',
    passive: false,
    name: 'Jab',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  BLACKOUT_KICK: {
    id: 100784,
    type: 'baseline',
    passive: false,
    name: 'Blackout Kick',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  TIGER_PALM: {
    id: 100787,
    type: 'baseline',
    passive: false,
    name: 'Tiger Palm',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  FLYING_SERPENT_KICK_FLYING_SERPENT_KICK: {
    id: 115057,
    grantedBy: 101545,
    type: 'temporary',
    passive: false,
    name: 'Flying Serpent Kick',
  },
  FLYING_SERPENT_KICK: {
    id: 101545,
    type: 'baseline',
    passive: false,
    name: 'Flying Serpent Kick',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 25000,
      hasted: false,
    },
  },
  SPINNING_CRANE_KICK: {
    id: 101546,
    type: 'baseline',
    passive: false,
    name: 'Spinning Crane Kick',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    channel: {
      duration: 2250,
      hasted: true,
      buffIsLogged: true,
      triggeredSpells: [
        {
          spell: 107270,
          period: 750,
          hasted: true,
        },
      ],
    },
  },
  TRANSCENDENCE: {
    id: 101643,
    type: 'baseline',
    passive: false,
    name: 'Transcendence',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
    },
    castTime: {
      duration: 500,
    },
  },
  STANCE_OF_THE_FIERCE_TIGER: {
    id: 103985,
    type: 'baseline',
    passive: false,
    name: 'Stance of the Fierce Tiger',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  SPINNING_CRANE_KICK_HIDDEN_1: {
    id: 107270,
    type: 'baseline',
    passive: false,
    hidden: 'always',
    name: 'Spinning Crane Kick',
  },
  SPINNING_CRANE_KICK_HIDDEN_2: {
    id: 117640,
    type: 'baseline',
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Spinning Crane Kick',
  },
  RISING_SUN_KICK: {
    id: 107428,
    type: 'baseline',
    passive: false,
    name: 'Rising Sun Kick',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 8000,
      hasted: false,
    },
  },
  DND_MONK_ENERGY_DRIVER_HIDDEN: {
    id: 107500,
    type: 'baseline',
    passive: true,
    hidden: 'always',
    name: '<DND> Monk Energy Driver',
  },
  MONK_WEAPON_OVERRIDE_DRIVER_HIDDEN: {
    id: 108562,
    type: 'baseline',
    passive: true,
    hidden: 'always',
    name: 'Monk Weapon Override Driver',
  },
  WAY_OF_THE_MONK_HIDDEN_1: {
    id: 108977,
    type: 'baseline',
    passive: true,
    hidden: 'always',
    name: 'Way of the Monk',
  },
  WAY_OF_THE_MONK_HIDDEN_2: {
    id: 120275,
    type: 'baseline',
    passive: true,
    hidden: 'always',
    name: 'Way of the Monk',
  },
  ROLL_CELERITY_TALENT: {
    id: 121827,
    grantedBy: 115173,
    type: 'temporary',
    passive: false,
    name: 'Roll',
    charges: {
      max: 3,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
  },
  ROLL: {
    id: 109132,
    type: 'baseline',
    passive: false,
    name: 'Roll',
    charges: {
      max: 2,
    },
    cooldown: {
      duration: 20000,
      hasted: false,
    },
  },
  SYMBIOSIS: {
    id: 110500,
    type: 'baseline',
    passive: false,
    name: 'Symbiosis',
  },
  FISTS_OF_FURY: {
    id: 113656,
    type: 'baseline',
    passive: false,
    name: 'Fists of Fury',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 25000,
      hasted: false,
    },
    channel: {
      duration: 4000,
      hasted: true,
      buffIsLogged: true,
      triggeredSpells: [
        {
          spell: 120086,
          period: 1000,
          hasted: true,
        },
      ],
    },
  },
  CHI_TORPEDO_TALENT: {
    id: 115008,
    overrides: 109132,
    type: 'mists-talent',
    row: 5,
    column: 3,
    passive: false,
    name: 'Chi Torpedo',
    charges: {
      max: 2,
    },
    cooldown: {
      duration: 20000,
      hasted: false,
    },
  },
  EXPEL_HARM: {
    id: 115072,
    type: 'baseline',
    passive: false,
    name: 'Expel Harm',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
  },
  SPINNING_FIRE_BLOSSOM: {
    id: 115073,
    type: 'baseline',
    passive: false,
    name: 'Spinning Fire Blossom',
    gcd: {
      duration: 1000,
      hasted: true,
    },
  },
  FIGHTING_STYLE_PASSIVE: {
    id: 115074,
    type: 'baseline',
    passive: true,
    name: 'Fighting Style',
  },
  PARALYSIS: {
    id: 115078,
    type: 'baseline',
    passive: false,
    name: 'Paralysis',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
  },
  TOUCH_OF_DEATH: {
    id: 115080,
    type: 'baseline',
    passive: false,
    name: 'Touch of Death',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 90000,
      hasted: false,
    },
  },
  CHI_WAVE_TALENT: {
    id: 115098,
    type: 'mists-talent',
    row: 1,
    column: 1,
    passive: false,
    name: 'Chi Wave',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
  },
  EXPEL_HARM_HIDDEN: {
    id: 115129,
    type: 'baseline',
    passive: false,
    hidden: 'always',
    name: 'Expel Harm',
    gcd: {
      duration: 1500,
      hasted: true,
    },
  },
  CELERITY_TALENT: {
    id: 115173,
    type: 'mists-talent',
    row: 0,
    column: 1,
    passive: true,
    name: 'Celerity',
  },
  MOMENTUM_TALENT: {
    id: 115174,
    type: 'mists-talent',
    row: 0,
    column: 3,
    passive: true,
    name: 'Momentum',
  },
  ZEN_MEDITATION: {
    id: 115176,
    type: 'baseline',
    passive: false,
    name: 'Zen Meditation',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
    channel: {
      duration: 8000,
      hasted: false,
      buffIsLogged: true,
      triggeredSpells: [],
    },
  },
  RESUSCITATE: {
    id: 115178,
    type: 'baseline',
    passive: false,
    name: 'Resuscitate',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 10000,
    },
  },
  FORTIFYING_BREW: {
    id: 115203,
    type: 'baseline',
    passive: false,
    name: 'Fortifying Brew',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
  },
  ENERGIZING_BREW: {
    id: 115288,
    type: 'baseline',
    passive: false,
    name: 'Energizing Brew',
    cooldown: {
      duration: 60000,
      hasted: false,
    },
  },
  ASCENSION_TALENT: {
    id: 115396,
    type: 'mists-talent',
    row: 2,
    column: 2,
    passive: true,
    name: 'Ascension',
  },
  CHI_BREW_TALENT: {
    id: 115399,
    type: 'mists-talent',
    row: 2,
    column: 3,
    passive: false,
    name: 'Chi Brew',
    charges: {
      max: 2,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
    },
  },
  DETOX_1: {
    id: 115450,
    type: 'baseline',
    passive: false,
    name: 'Detox',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 8000,
      hasted: false,
    },
  },
  DETOX_2: {
    id: 125170,
    type: 'baseline',
    passive: false,
    name: 'Detox',
  },
  HEALING_SPHERE: {
    id: 115460,
    type: 'baseline',
    passive: false,
    name: 'Healing Sphere',
    gcd: {
      duration: 500,
      hasted: true,
    },
    cooldown: {
      duration: 500,
      hasted: false,
    },
  },
  HEALING_SPHERE_HIDDEN_1: {
    id: 115464,
    type: 'baseline',
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Healing Sphere',
  },
  HEALING_SPHERE_HIDDEN_2: {
    id: 125355,
    type: 'baseline',
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Healing Sphere',
  },
  HEALING_SPHERE_HIDDEN_3: {
    id: 135914,
    type: 'baseline',
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Healing Sphere',
  },
  LEER_OF_THE_OX: {
    id: 115543,
    type: 'baseline',
    passive: false,
    hidden: 'unless-learned',
    name: 'Leer of the Ox',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 20000,
      hasted: false,
    },
  },
  PROVOKE: {
    id: 115546,
    type: 'baseline',
    passive: false,
    name: 'Provoke',
    cooldown: {
      duration: 8000,
      hasted: false,
    },
  },
  EXPEL_HARM_DRIVER_HIDDEN: {
    id: 115612,
    type: 'baseline',
    passive: true,
    hidden: 'always',
    name: 'Expel Harm Driver',
  },
  MASTERY_BOTTLED_FURY_PASSIVE: {
    id: 115636,
    type: 'baseline',
    passive: true,
    name: 'Mastery: Bottled Fury',
  },
  LEGACY_OF_THE_EMPEROR: {
    id: 115921,
    type: 'baseline',
    passive: false,
    name: 'Legacy of the Emperor',
    gcd: {
      duration: 1000,
      hasted: true,
    },
  },
  SPARRING_PASSIVE: {
    id: 116023,
    type: 'baseline',
    passive: true,
    name: 'Sparring',
    channel: {
      duration: -1,
      hasted: false,
      buffIsLogged: true,
      triggeredSpells: [],
    },
  },
  AFTERLIFE_PASSIVE: {
    id: 116092,
    type: 'baseline',
    passive: true,
    name: 'Afterlife',
  },
  DISABLE: {
    id: 116095,
    type: 'baseline',
    passive: false,
    name: 'Disable',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  SPEAR_HAND_STRIKE: {
    id: 116705,
    type: 'baseline',
    passive: false,
    name: 'Spear Hand Strike',
    cooldown: {
      duration: 15000,
      hasted: false,
    },
  },
  TIGEREYE_BREW_1: {
    id: 116740,
    type: 'baseline',
    passive: false,
    name: 'Tigereye Brew',
    cooldown: {
      duration: 5000,
      hasted: false,
    },
  },
  TIGEREYE_BREW_2: {
    id: 1247275,
    grantedBy: 137025,
    type: 'temporary',
    passive: false,
    name: 'Tigereye Brew',
    cooldown: {
      duration: 1000,
      hasted: false,
    },
  },
  TIGEREYE_BREW_3: {
    id: 1247279,
    grantedBy: 137025,
    type: 'temporary',
    passive: false,
    name: 'Tigereye Brew',
  },
  LEGACY_OF_THE_WHITE_TIGER: {
    id: 116781,
    type: 'baseline',
    passive: false,
    name: 'Legacy of the White Tiger',
    gcd: {
      duration: 1000,
      hasted: true,
    },
  },
  PARRY_PASSIVE: {
    id: 116812,
    type: 'baseline',
    passive: true,
    name: 'Parry',
  },
  TIGERS_LUST_TALENT: {
    id: 116841,
    type: 'mists-talent',
    row: 0,
    column: 2,
    passive: false,
    name: "Tiger's Lust",
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
  },
  RING_OF_PEACE_TALENT: {
    id: 116844,
    type: 'mists-talent',
    row: 3,
    column: 1,
    passive: false,
    name: 'Ring of Peace',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
    },
  },
  RUSHING_JADE_WIND_TALENT: {
    id: 116847,
    overrides: 101546,
    type: 'mists-talent',
    row: 5,
    column: 1,
    passive: false,
    name: 'Rushing Jade Wind',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 6000,
      hasted: true,
    },
  },
  SURGING_MIST_HIDDEN: {
    id: 116995,
    type: 'baseline',
    passive: false,
    hidden: 'always',
    name: 'Surging Mist',
    gcd: {
      duration: 1500,
      hasted: true,
    },
  },
  GRAPPLE_WEAPON: {
    id: 117368,
    type: 'baseline',
    passive: false,
    name: 'Grapple Weapon',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
  },
  FISTS_OF_FURY_HIDDEN: {
    id: 117418,
    type: 'baseline',
    passive: false,
    hidden: 'always',
    name: 'Fists of Fury',
  },
  EMINENCE_STATUE: {
    id: 117895,
    type: 'baseline',
    castableWhileCasting: true,
    passive: false,
    hidden: 'unless-learned',
    name: 'Eminence (Statue)',
  },
  CRACKLING_JADE_LIGHTNING: {
    id: 117952,
    type: 'baseline',
    passive: false,
    name: 'Crackling Jade Lightning',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    channel: {
      duration: 6000,
      hasted: true,
      buffIsLogged: true,
      triggeredSpells: [],
    },
  },
  CRACKLING_JADE_LIGHTNING_HIDDEN: {
    id: 117959,
    type: 'baseline',
    passive: true,
    hidden: 'always',
    name: 'Crackling Jade Lightning',
  },
  CHI_TORPEDO_HIDDEN_1: {
    id: 117993,
    type: 'baseline',
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Torpedo',
  },
  CHI_TORPEDO_HIDDEN_2: {
    id: 124040,
    type: 'baseline',
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Torpedo',
  },
  DIZZYING_HAZE: {
    id: 118022,
    type: 'baseline',
    passive: false,
    hidden: 'unless-learned',
    name: 'Dizzying Haze',
    gcd: {
      duration: 1500,
      hasted: false,
    },
  },
  LEG_SWEEP_TALENT: {
    id: 119381,
    type: 'mists-talent',
    row: 3,
    column: 3,
    passive: false,
    name: 'Leg Sweep',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
    },
  },
  CHARGING_OX_WAVE_TALENT: {
    id: 119392,
    type: 'mists-talent',
    row: 3,
    column: 2,
    passive: false,
    name: 'Charging Ox Wave',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
  },
  RENEWING_MIST_HIDDEN: {
    id: 119611,
    type: 'baseline',
    passive: false,
    hidden: 'always',
    name: 'Renewing Mist',
  },
  ENERGY_USAGE_HIDDEN: {
    id: 119650,
    type: 'baseline',
    passive: false,
    hidden: 'always',
    name: 'Energy Usage',
  },
  TRANSCENDENCE_TRANSFER: {
    id: 119996,
    type: 'baseline',
    passive: false,
    name: 'Transcendence: Transfer',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 25000,
      hasted: false,
    },
    castTime: {
      duration: 500,
    },
  },
  LEATHER_SPECIALIZATION_PASSIVE: {
    id: 120227,
    type: 'baseline',
    passive: true,
    hidden: 'unless-learned',
    name: 'Leather Specialization',
  },
  TIGER_STRIKES_PASSIVE: {
    id: 120272,
    type: 'baseline',
    passive: true,
    name: 'Tiger Strikes',
  },
  TIGER_STRIKES_HIDDEN_1: {
    id: 120274,
    type: 'baseline',
    passive: false,
    hidden: 'always',
    name: 'Tiger Strikes',
  },
  TIGER_STRIKES_HIDDEN_2: {
    id: 120278,
    type: 'baseline',
    passive: false,
    hidden: 'always',
    name: 'Tiger Strikes',
  },
  WAY_OF_THE_MONK_PASSIVE: {
    id: 120277,
    type: 'baseline',
    passive: true,
    name: 'Way of the Monk',
  },
  TOUCH_OF_DEATHEXPEL_HARM_NOTIFICATION_DRIVER_HIDDEN: {
    id: 121128,
    type: 'baseline',
    passive: true,
    hidden: 'always',
    name: 'Touch of Death/Expel Harm Notification Driver',
  },
  POWER_STRIKES_TALENT: {
    id: 121817,
    type: 'mists-talent',
    row: 2,
    column: 1,
    passive: true,
    name: 'Power Strikes',
  },
  CHI_TORPEDO: {
    id: 121828,
    grantedBy: 115173,
    type: 'temporary',
    passive: false,
    name: 'Chi Torpedo',
    charges: {
      max: 3,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
  },
  DAMPEN_HARM_TALENT: {
    id: 122278,
    type: 'mists-talent',
    row: 4,
    column: 2,
    passive: false,
    name: 'Dampen Harm',
    cooldown: {
      duration: 90000,
      hasted: false,
    },
  },
  HEALING_ELIXIRS_TALENT: {
    id: 122280,
    type: 'mists-talent',
    row: 4,
    column: 1,
    passive: true,
    name: 'Healing Elixirs',
  },
  HEALING_ELIXIRS_HIDDEN: {
    id: 122281,
    type: 'baseline',
    passive: false,
    hidden: 'always',
    name: 'Healing Elixirs',
  },
  TOUCH_OF_KARMA: {
    id: 122470,
    type: 'baseline',
    passive: false,
    name: 'Touch of Karma',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 90000,
      hasted: false,
    },
  },
  DIFFUSE_MAGIC_TALENT: {
    id: 122783,
    type: 'mists-talent',
    row: 4,
    column: 3,
    passive: false,
    name: 'Diffuse Magic',
    cooldown: {
      duration: 90000,
      hasted: false,
    },
  },
  SURGING_MIST: {
    id: 123273,
    type: 'baseline',
    passive: false,
    hidden: 'unless-learned',
    name: 'Surging Mist',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    castTime: {
      duration: 1500,
    },
  },
  CRACKLING_JADE_LIGHTNING_CHI_PROC_DRIVER_HIDDEN: {
    id: 123332,
    type: 'baseline',
    passive: true,
    hidden: 'always',
    name: 'Crackling Jade Lightning Chi Proc Driver',
  },
  FLYING_SERPENT_KICK_HIDDEN: {
    id: 123586,
    type: 'baseline',
    passive: false,
    hidden: 'always',
    name: 'Flying Serpent Kick',
  },
  BREATH_OF_FIRE_HIDDEN: {
    id: 123725,
    type: 'baseline',
    passive: false,
    hidden: 'always',
    name: 'Breath of Fire',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  INVOKE_XUEN_THE_WHITE_TIGER_TALENT: {
    id: 123904,
    type: 'mists-talent',
    row: 5,
    column: 2,
    passive: false,
    name: 'Invoke Xuen, the White Tiger',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
  },
  BREWING_TIGEREYE_BREW_PASSIVE: {
    id: 123980,
    type: 'baseline',
    passive: true,
    name: 'Brewing: Tigereye Brew',
  },
  CHI_BURST_TALENT: {
    id: 123986,
    type: 'mists-talent',
    row: 1,
    column: 3,
    passive: false,
    name: 'Chi Burst',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    castTime: {
      duration: 1000,
    },
  },
  GIFT_OF_THE_SERPENT_HIDDEN_1: {
    id: 124041,
    type: 'baseline',
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Gift of the Serpent',
  },
  GIFT_OF_THE_SERPENT_HIDDEN_2: {
    id: 135920,
    type: 'baseline',
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Gift of the Serpent',
  },
  ZEN_SPHERE_TALENT: {
    id: 124081,
    type: 'mists-talent',
    row: 1,
    column: 2,
    passive: false,
    name: 'Zen Sphere',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 10000,
      hasted: false,
    },
  },
  ZEN_SPHERE: {
    id: 124098,
    type: 'baseline',
    passive: false,
    hidden: 'unless-learned',
    name: 'Zen Sphere',
    gcd: {
      duration: 1500,
      hasted: true,
    },
  },
  ZEN_SPHERE_DETONATE_1: {
    id: 124101,
    type: 'baseline',
    passive: false,
    hidden: 'unless-learned',
    name: 'Zen Sphere: Detonate',
    gcd: {
      duration: 1500,
      hasted: true,
    },
  },
  ZEN_SPHERE_DETONATE_2: {
    id: 125033,
    type: 'baseline',
    passive: false,
    hidden: 'unless-learned',
    name: 'Zen Sphere: Detonate',
    gcd: {
      duration: 1500,
      hasted: true,
    },
  },
  DUAL_WIELD_PASSIVE: {
    id: 124146,
    type: 'baseline',
    passive: true,
    name: 'Dual Wield',
  },
  TOUCH_OF_KARMA_HIDDEN: {
    id: 124280,
    type: 'baseline',
    passive: false,
    hidden: 'always',
    name: 'Touch of Karma',
    gcd: {
      duration: 1500,
      hasted: true,
    },
  },
  SWIFT_REFLEXES_PASSIVE: {
    id: 124334,
    type: 'baseline',
    passive: true,
    name: 'Swift Reflexes',
  },
  SWIFT_REFLEXES_HIDDEN: {
    id: 124335,
    type: 'baseline',
    passive: false,
    hidden: 'always',
    name: 'Swift Reflexes',
  },
  GIFT_OF_THE_OX_HIDDEN: {
    id: 124507,
    type: 'baseline',
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Gift of the Ox',
  },
  SOOTHING_MIST: {
    id: 125953,
    type: 'baseline',
    passive: false,
    hidden: 'unless-learned',
    name: 'Soothing Mist',
    gcd: {
      duration: 1000,
      hasted: true,
    },
  },
  ADAPTATION_PASSIVE: {
    id: 126046,
    type: 'baseline',
    passive: true,
    name: 'Adaptation',
  },
  EMINENCE: {
    id: 126890,
    type: 'baseline',
    castableWhileCasting: true,
    passive: false,
    hidden: 'unless-learned',
    name: 'Eminence',
  },
  ZEN_PILGRIMAGE: {
    id: 126892,
    type: 'baseline',
    passive: false,
    name: 'Zen Pilgrimage',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 1800000,
      hasted: false,
    },
    castTime: {
      duration: 10000,
    },
  },
  ZEN_PILGRIMAGEDEATH_GATEMOONGLADE_STORAGE_AURA_I_HIDDEN: {
    id: 126893,
    type: 'baseline',
    passive: false,
    hidden: 'always',
    name: 'Zen Pilgrimage/Death Gate/Moonglade Storage Aura I',
  },
  ZEN_PILGRIMAGE_RETURN_HIDDEN: {
    id: 126895,
    type: 'baseline',
    passive: false,
    hidden: 'always',
    name: 'Zen Pilgrimage: Return',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    castTime: {
      duration: 10000,
    },
  },
  BLACKOUT_KICK_HIDDEN_1: {
    id: 128531,
    type: 'baseline',
    passive: false,
    hidden: 'always',
    name: 'Blackout Kick',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  BLACKOUT_KICK_HIDDEN_2: {
    id: 128591,
    type: 'baseline',
    passive: false,
    hidden: 'always',
    name: 'Blackout Kick',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  COMBAT_CONDITIONING_PASSIVE: {
    id: 128595,
    type: 'baseline',
    passive: true,
    name: 'Combat Conditioning',
  },
  MONK_JAB_OVERRIDE_FIST_LOGIN_HIDDEN: {
    id: 128678,
    type: 'baseline',
    passive: false,
    hidden: 'always',
    name: 'Monk Jab Override Fist Login',
  },
  YOU_ARE_A_LEVEL_90_MONK_HIDDEN: {
    id: 130610,
    type: 'baseline',
    passive: true,
    hidden: 'always',
    name: 'You Are A Level 90 Monk',
  },
  CHI_BURST_HIDDEN: {
    id: 130654,
    type: 'baseline',
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Burst',
  },
  ENVELOPING_MIST_HIDDEN: {
    id: 132120,
    type: 'baseline',
    passive: false,
    hidden: 'always',
    name: 'Enveloping Mist',
    gcd: {
      duration: 1000,
      hasted: true,
    },
  },
  CHI_WAVE_HIDDEN_1: {
    id: 132463,
    type: 'baseline',
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Wave',
  },
  CHI_WAVE_HIDDEN_2: {
    id: 132467,
    type: 'baseline',
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Wave',
  },
  STANCE_OF_THE_WISE_SERPENT_HIDDEN: {
    id: 136336,
    type: 'baseline',
    passive: false,
    hidden: 'always',
    name: 'Stance of the Wise Serpent',
  },
  HOTFIX_PASSIVE_HIDDEN_1: {
    id: 137022,
    type: 'baseline',
    passive: true,
    hidden: 'always',
    name: 'Hotfix Passive',
  },
  HOTFIX_PASSIVE_HIDDEN_2: {
    id: 137025,
    type: 'baseline',
    passive: true,
    hidden: 'always',
    name: 'Hotfix Passive',
  },
  COMBO_BREAKER_PASSIVE: {
    id: 137384,
    type: 'baseline',
    passive: true,
    name: 'Combo Breaker',
  },
  NIMBLE_BREW: {
    id: 137562,
    type: 'baseline',
    passive: false,
    name: 'Nimble Brew',
    cooldown: {
      duration: 120000,
      hasted: false,
    },
  },
  STORM_EARTH_AND_FIRE: {
    id: 137639,
    type: 'baseline',
    passive: false,
    name: 'Storm, Earth, and Fire',
    gcd: {
      duration: 1000,
      hasted: true,
    },
  },
  REAWAKEN: {
    id: 1245934,
    type: 'baseline',
    passive: false,
    name: 'Reawaken',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 10000,
    },
  },
  BREWING_TIGEREYE_BREW: {
    id: 1247267,
    grantedBy: 137025,
    type: 'temporary',
    passive: true,
    name: 'Brewing: Tigereye Brew',
  },
  MASTERY_BOTTLED_FURY: {
    id: 1247280,
    grantedBy: 137025,
    type: 'temporary',
    passive: true,
    name: 'Mastery: Bottled Fury',
  },
  YOU_ARE_A_LEVEL_85_MONK_HIDDEN: {
    id: 1251700,
    type: 'baseline',
    passive: true,
    hidden: 'always',
    name: 'You Are A Level 85 Monk',
  },
} as const satisfies Record<string, RetailSpell>;
export default SPELLS;
