import SPELLS from 'common/SPELLS';

export const DISPERSION_BASE_CD = 90;
export const DISPERSION_UPTIME_MS = 6000;
export const MINDBENDER_UPTIME_MS = 15000;
export const MS_BUFFER = 100;
export const SPIRIT_DAMAGE_MULTIPLIER = 1.3;
export const SPIRIT_INSANITY_GENERATION = 1;
export const TWIST_OF_FATE_INCREASE = 1.1;
export const VOID_TORRENT_MAX_TIME = 4000;

export const VOID_FORM_ACTIVATORS = [
  SPELLS.VOID_ERUPTION.id,
  SPELLS.SURRENDER_TO_MADNESS_TALENT.id,
];

