import type { RetailSpell } from 'wow-dbc';
const SPELLS = {
  JAB: {
    id: 100780,
    type: 'baseline',
    iconID: 574572,
    passive: false,
    name: 'Jab',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'ability_monk_jab.jpg',
  },
  BLACKOUT_KICK: {
    id: 100784,
    type: 'baseline',
    iconID: 574575,
    passive: false,
    name: 'Blackout Kick',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'ability_monk_roundhousekick.jpg',
  },
  TIGER_PALM: {
    id: 100787,
    type: 'baseline',
    iconID: 606551,
    passive: false,
    name: 'Tiger Palm',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'ability_monk_tigerpalm.jpg',
  },
  SPINNING_CRANE_KICK: {
    id: 101546,
    type: 'baseline',
    iconID: 606543,
    passive: false,
    name: 'Spinning Crane Kick',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    channel: {
      duration: 2250,
      hasted: true,
      buffIsLogged: true,
      triggeredSpells: [
        {
          spell: 107270,
          period: 750,
          hasted: true,
        },
      ],
    },
    icon: 'ability_monk_cranekick_new.jpg',
  },
  TRANSCENDENCE: {
    id: 101643,
    type: 'baseline',
    iconID: 627608,
    passive: false,
    name: 'Transcendence',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
    },
    castTime: {
      duration: 500,
    },
    icon: 'monk_ability_transcendence.jpg',
  },
  STANCE_OF_THE_FIERCE_TIGER: {
    id: 103985,
    type: 'baseline',
    iconID: 611420,
    passive: false,
    name: 'Stance of the Fierce Tiger',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'monk_stance_whitetiger.jpg',
  },
  SPINNING_CRANE_KICK_HIDDEN_1: {
    id: 107270,
    type: 'baseline',
    iconID: 606543,
    passive: false,
    hidden: 'always',
    name: 'Spinning Crane Kick',
    icon: 'ability_monk_cranekick_new.jpg',
  },
  SPINNING_CRANE_KICK_HIDDEN_2: {
    id: 117640,
    type: 'baseline',
    iconID: 606543,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Spinning Crane Kick',
    icon: 'ability_monk_cranekick_new.jpg',
  },
  DND_MONK_ENERGY_DRIVER_HIDDEN: {
    id: 107500,
    type: 'baseline',
    iconID: 236180,
    passive: true,
    hidden: 'always',
    name: '<DND> Monk Energy Driver',
    icon: 'ability_hunter_huntervswild.jpg',
  },
  MONK_WEAPON_OVERRIDE_DRIVER_HIDDEN: {
    id: 108562,
    type: 'baseline',
    iconID: 132528,
    passive: true,
    hidden: 'always',
    name: 'Monk Weapon Override Driver',
    icon: 'inv_bijou_gold.jpg',
  },
  WAY_OF_THE_MONK_HIDDEN_1: {
    id: 108977,
    type: 'baseline',
    iconID: 574570,
    passive: true,
    hidden: 'always',
    name: 'Way of the Monk',
    icon: 'ability_monk_dpsstance.jpg',
  },
  WAY_OF_THE_MONK_HIDDEN_2: {
    id: 120275,
    type: 'baseline',
    iconID: 574570,
    passive: true,
    hidden: 'always',
    name: 'Way of the Monk',
    icon: 'ability_monk_dpsstance.jpg',
  },
  ROLL_CELERITY_TALENT: {
    id: 121827,
    grantedBy: 115173,
    type: 'temporary',
    iconID: 574574,
    passive: false,
    name: 'Roll',
    charges: {
      max: 3,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
    icon: 'ability_monk_roll.jpg',
  },
  ROLL: {
    id: 109132,
    type: 'baseline',
    iconID: 574574,
    passive: false,
    name: 'Roll',
    charges: {
      max: 2,
    },
    cooldown: {
      duration: 20000,
      hasted: false,
    },
    icon: 'ability_monk_roll.jpg',
  },
  SYMBIOSIS: {
    id: 110500,
    type: 'baseline',
    iconID: 571587,
    passive: false,
    name: 'Symbiosis',
    icon: 'spell_druid_symbiosis.jpg',
  },
  CHI_TORPEDO_TALENT: {
    id: 115008,
    overrides: 109132,
    type: 'mists-talent',
    row: 5,
    column: 3,
    iconID: 607849,
    passive: false,
    name: 'Chi Torpedo',
    charges: {
      max: 2,
    },
    cooldown: {
      duration: 20000,
      hasted: false,
    },
    icon: 'ability_monk_quitornado.jpg',
  },
  STANCE_OF_THE_STURDY_OX: {
    id: 115069,
    type: 'baseline',
    iconID: 611419,
    passive: false,
    name: 'Stance of the Sturdy Ox',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'monk_stance_drunkenox.jpg',
  },
  EXPEL_HARM: {
    id: 115072,
    type: 'baseline',
    iconID: 627486,
    passive: false,
    name: 'Expel Harm',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
    icon: 'ability_monk_expelharm.jpg',
  },
  FIGHTING_STYLE_PASSIVE: {
    id: 115074,
    type: 'baseline',
    iconID: 574577,
    passive: true,
    name: 'Fighting Style',
    icon: 'ability_monk_standingkick.jpg',
  },
  PARALYSIS: {
    id: 115078,
    type: 'baseline',
    iconID: 629534,
    passive: false,
    name: 'Paralysis',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
    icon: 'ability_monk_paralysis.jpg',
  },
  TOUCH_OF_DEATH: {
    id: 115080,
    type: 'baseline',
    iconID: 606552,
    passive: false,
    name: 'Touch of Death',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 90000,
      hasted: false,
    },
    icon: 'ability_monk_touchofdeath.jpg',
  },
  CHI_WAVE_TALENT: {
    id: 115098,
    type: 'mists-talent',
    row: 1,
    column: 1,
    iconID: 606541,
    passive: false,
    name: 'Chi Wave',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
    icon: 'ability_monk_chiwave.jpg',
  },
  EXPEL_HARM_HIDDEN: {
    id: 115129,
    type: 'baseline',
    iconID: 627486,
    passive: false,
    hidden: 'always',
    name: 'Expel Harm',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'ability_monk_expelharm.jpg',
  },
  CELERITY_TALENT: {
    id: 115173,
    type: 'mists-talent',
    row: 0,
    column: 1,
    iconID: 607848,
    passive: true,
    name: 'Celerity',
    icon: 'ability_monk_quipunch.jpg',
  },
  MOMENTUM_TALENT: {
    id: 115174,
    type: 'mists-talent',
    row: 0,
    column: 3,
    iconID: 574577,
    passive: true,
    name: 'Momentum',
    icon: 'ability_monk_standingkick.jpg',
  },
  ZEN_MEDITATION: {
    id: 115176,
    type: 'baseline',
    iconID: 642417,
    passive: false,
    name: 'Zen Meditation',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
    channel: {
      duration: 8000,
      hasted: false,
      buffIsLogged: true,
      triggeredSpells: [],
    },
    icon: 'ability_monk_zenmeditation.jpg',
  },
  RESUSCITATE: {
    id: 115178,
    type: 'baseline',
    iconID: 132132,
    passive: false,
    name: 'Resuscitate',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 10000,
    },
    icon: 'ability_druid_lunarguidance.jpg',
  },
  DIZZYING_HAZE_1: {
    id: 115180,
    type: 'baseline',
    iconID: 606544,
    passive: false,
    name: 'Dizzying Haze',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'ability_monk_drunkenhaze.jpg',
  },
  DIZZYING_HAZE_2: {
    id: 118022,
    type: 'baseline',
    iconID: 606544,
    passive: false,
    hidden: 'unless-learned',
    name: 'Dizzying Haze',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    icon: 'ability_monk_drunkenhaze.jpg',
  },
  BREATH_OF_FIRE: {
    id: 115181,
    type: 'baseline',
    iconID: 615339,
    passive: false,
    name: 'Breath of Fire',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'ability_monk_breathoffire.jpg',
  },
  FORTIFYING_BREW: {
    id: 115203,
    type: 'baseline',
    iconID: 615341,
    passive: false,
    name: 'Fortifying Brew',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
    icon: 'ability_monk_fortifyingale_new.jpg',
  },
  AVERT_HARM: {
    id: 115213,
    type: 'baseline',
    iconID: 627605,
    passive: false,
    name: 'Avert Harm',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
    icon: 'monk_ability_avertharm.jpg',
  },
  GUARD: {
    id: 115295,
    type: 'baseline',
    iconID: 611417,
    passive: false,
    name: 'Guard',
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 'ability_monk_guard.jpg',
  },
  ELUSIVE_BREW: {
    id: 115308,
    type: 'baseline',
    iconID: 613396,
    passive: false,
    name: 'Elusive Brew',
    cooldown: {
      duration: 6000,
      hasted: false,
    },
    icon: 'ability_monk_elusiveale.jpg',
  },
  SUMMON_BLACK_OX_STATUE: {
    id: 115315,
    type: 'baseline',
    iconID: 627607,
    passive: false,
    name: 'Summon Black Ox Statue',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 'monk_ability_summonoxstatue.jpg',
  },
  ASCENSION_TALENT: {
    id: 115396,
    type: 'mists-talent',
    row: 2,
    column: 2,
    iconID: 629482,
    passive: true,
    name: 'Ascension',
    icon: 'ability_monk_ascension.jpg',
  },
  CHI_BREW_TALENT: {
    id: 115399,
    type: 'mists-talent',
    row: 2,
    column: 3,
    iconID: 629483,
    passive: false,
    name: 'Chi Brew',
    charges: {
      max: 2,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
    },
    icon: 'ability_monk_chibrew.jpg',
  },
  DETOX_1: {
    id: 115450,
    type: 'baseline',
    iconID: 135894,
    passive: false,
    name: 'Detox',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 8000,
      hasted: false,
    },
    icon: 'spell_holy_dispelmagic.jpg',
  },
  DETOX_2: {
    id: 125170,
    type: 'baseline',
    iconID: 237171,
    passive: false,
    name: 'Detox',
    icon: 'inv_inscription_tradeskill01.jpg',
  },
  HEALING_SPHERE: {
    id: 115460,
    type: 'baseline',
    iconID: 606546,
    passive: false,
    name: 'Healing Sphere',
    gcd: {
      duration: 500,
      hasted: true,
    },
    cooldown: {
      duration: 500,
      hasted: false,
    },
    icon: 'ability_monk_healthsphere.jpg',
  },
  HEALING_SPHERE_HIDDEN_1: {
    id: 115464,
    type: 'baseline',
    iconID: 606546,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Healing Sphere',
    icon: 'ability_monk_healthsphere.jpg',
  },
  HEALING_SPHERE_HIDDEN_2: {
    id: 125355,
    type: 'baseline',
    iconID: 606546,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Healing Sphere',
    icon: 'ability_monk_healthsphere.jpg',
  },
  HEALING_SPHERE_HIDDEN_3: {
    id: 135914,
    type: 'baseline',
    iconID: 606546,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Healing Sphere',
    icon: 'ability_monk_healthsphere.jpg',
  },
  LEER_OF_THE_OX: {
    id: 115543,
    type: 'baseline',
    iconID: 620829,
    passive: false,
    hidden: 'unless-learned',
    name: 'Leer of the Ox',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 20000,
      hasted: false,
    },
    icon: 'ability_monk_leeroftheox.jpg',
  },
  PROVOKE: {
    id: 115546,
    type: 'baseline',
    iconID: 620830,
    passive: false,
    name: 'Provoke',
    cooldown: {
      duration: 8000,
      hasted: false,
    },
    icon: 'ability_monk_provoke.jpg',
  },
  EXPEL_HARM_DRIVER_HIDDEN: {
    id: 115612,
    type: 'baseline',
    iconID: 236218,
    passive: true,
    hidden: 'always',
    name: 'Expel Harm Driver',
    icon: 'ability_mage_hotstreak.jpg',
  },
  LEGACY_OF_THE_EMPEROR: {
    id: 115921,
    type: 'baseline',
    iconID: 606547,
    passive: false,
    name: 'Legacy of the Emperor',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    icon: 'ability_monk_legacyoftheemperor.jpg',
  },
  DISABLE: {
    id: 116095,
    type: 'baseline',
    iconID: 132316,
    passive: false,
    name: 'Disable',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'ability_shockwave.jpg',
  },
  SPEAR_HAND_STRIKE: {
    id: 116705,
    type: 'baseline',
    iconID: 608940,
    passive: false,
    name: 'Spear Hand Strike',
    cooldown: {
      duration: 15000,
      hasted: false,
    },
    icon: 'ability_monk_spearhand.jpg',
  },
  PARRY_PASSIVE: {
    id: 116812,
    type: 'baseline',
    iconID: 132269,
    passive: true,
    name: 'Parry',
    icon: 'ability_parry.jpg',
  },
  TIGERS_LUST_TALENT: {
    id: 116841,
    type: 'mists-talent',
    row: 0,
    column: 2,
    iconID: 651727,
    passive: false,
    name: "Tiger's Lust",
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 'ability_monk_tigerslust.jpg',
  },
  RING_OF_PEACE_TALENT: {
    id: 116844,
    type: 'mists-talent',
    row: 3,
    column: 1,
    iconID: 839107,
    passive: false,
    name: 'Ring of Peace',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
    },
    icon: 'spell_monk_ringofpeace.jpg',
  },
  RUSHING_JADE_WIND_TALENT: {
    id: 116847,
    overrides: 101546,
    type: 'mists-talent',
    row: 5,
    column: 1,
    iconID: 606549,
    passive: false,
    name: 'Rushing Jade Wind',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 6000,
      hasted: true,
    },
    icon: 'ability_monk_rushingjadewind.jpg',
  },
  SURGING_MIST_HIDDEN: {
    id: 116995,
    type: 'baseline',
    iconID: 628135,
    passive: false,
    hidden: 'always',
    name: 'Surging Mist',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'ability_monk_surgingmist.jpg',
  },
  GRAPPLE_WEAPON: {
    id: 117368,
    type: 'baseline',
    iconID: 132343,
    passive: false,
    name: 'Grapple Weapon',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: 'ability_warrior_disarm.jpg',
  },
  FISTS_OF_FURY_HIDDEN: {
    id: 117418,
    type: 'baseline',
    iconID: 627606,
    passive: false,
    hidden: 'always',
    name: 'Fists of Fury',
    icon: 'monk_ability_fistoffury.jpg',
  },
  EMINENCE_STATUE: {
    id: 117895,
    type: 'baseline',
    iconID: 237237,
    castableWhileCasting: true,
    passive: false,
    hidden: 'unless-learned',
    name: 'Eminence (Statue)',
    icon: 'inv_jewelcrafting_jadeserpent.jpg',
  },
  MASTERY_ELUSIVE_BRAWLER_PASSIVE: {
    id: 117906,
    type: 'baseline',
    iconID: 132792,
    passive: true,
    name: 'Mastery: Elusive Brawler',
    icon: 'inv_drink_05.jpg',
  },
  CRACKLING_JADE_LIGHTNING: {
    id: 117952,
    type: 'baseline',
    iconID: 606542,
    passive: false,
    name: 'Crackling Jade Lightning',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    channel: {
      duration: 6000,
      hasted: true,
      buffIsLogged: true,
      triggeredSpells: [],
    },
    icon: 'ability_monk_cracklingjadelightning.jpg',
  },
  CRACKLING_JADE_LIGHTNING_HIDDEN: {
    id: 117959,
    type: 'baseline',
    iconID: 132269,
    passive: true,
    hidden: 'always',
    name: 'Crackling Jade Lightning',
    icon: 'ability_parry.jpg',
  },
  BREWMASTER_TRAINING_PASSIVE: {
    id: 117967,
    type: 'baseline',
    iconID: 608950,
    passive: true,
    name: 'Brewmaster Training',
    icon: 'spell_monk_brewmastertraining.jpg',
  },
  CHI_TORPEDO_HIDDEN_1: {
    id: 117993,
    type: 'baseline',
    iconID: 607849,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Torpedo',
    icon: 'ability_monk_quitornado.jpg',
  },
  CHI_TORPEDO_HIDDEN_2: {
    id: 124040,
    type: 'baseline',
    iconID: 607849,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Torpedo',
    icon: 'ability_monk_quitornado.jpg',
  },
  LEG_SWEEP_TALENT: {
    id: 119381,
    type: 'mists-talent',
    row: 3,
    column: 3,
    iconID: 642414,
    passive: false,
    name: 'Leg Sweep',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
    },
    icon: 'ability_monk_legsweep.jpg',
  },
  CHARGING_OX_WAVE_TALENT: {
    id: 119392,
    type: 'mists-talent',
    row: 3,
    column: 2,
    iconID: 615340,
    passive: false,
    name: 'Charging Ox Wave',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 'ability_monk_chargingoxwave.jpg',
  },
  PURIFYING_BREW: {
    id: 119582,
    type: 'baseline',
    iconID: 133701,
    passive: false,
    name: 'Purifying Brew',
    cooldown: {
      duration: 1000,
      hasted: false,
    },
    icon: 'inv_misc_beer_06.jpg',
  },
  RENEWING_MIST_HIDDEN: {
    id: 119611,
    type: 'baseline',
    iconID: 627487,
    passive: false,
    hidden: 'always',
    name: 'Renewing Mist',
    icon: 'ability_monk_renewingmists.jpg',
  },
  ENERGY_USAGE_HIDDEN: {
    id: 119650,
    type: 'baseline',
    iconID: 135724,
    passive: false,
    hidden: 'always',
    name: 'Energy Usage',
    icon: 'mail_gmicon.jpg',
  },
  TRANSCENDENCE_TRANSFER: {
    id: 119996,
    type: 'baseline',
    iconID: 237585,
    passive: false,
    name: 'Transcendence: Transfer',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 25000,
      hasted: false,
    },
    castTime: {
      duration: 500,
    },
    icon: 'spell_shaman_spectraltransformation.jpg',
  },
  LEATHER_SPECIALIZATION_PASSIVE: {
    id: 120225,
    type: 'baseline',
    iconID: 132721,
    passive: true,
    hidden: 'unless-learned',
    name: 'Leather Specialization',
    icon: 'inv_chest_leather_06.jpg',
  },
  VENGEANCE_PASSIVE: {
    id: 120267,
    type: 'baseline',
    iconID: 136129,
    passive: true,
    name: 'Vengeance',
    icon: 'spell_shadow_charm.jpg',
  },
  TIGER_STRIKES_HIDDEN_1: {
    id: 120274,
    type: 'baseline',
    iconID: 136018,
    passive: false,
    hidden: 'always',
    name: 'Tiger Strikes',
    icon: 'spell_nature_cyclone.jpg',
  },
  TIGER_STRIKES_HIDDEN_2: {
    id: 120278,
    type: 'baseline',
    iconID: 136018,
    passive: false,
    hidden: 'always',
    name: 'Tiger Strikes',
    icon: 'spell_nature_cyclone.jpg',
  },
  WAY_OF_THE_MONK_PASSIVE: {
    id: 120277,
    type: 'baseline',
    iconID: 574570,
    passive: true,
    name: 'Way of the Monk',
    icon: 'ability_monk_dpsstance.jpg',
  },
  TOUCH_OF_DEATHEXPEL_HARM_NOTIFICATION_DRIVER_HIDDEN: {
    id: 121128,
    type: 'baseline',
    iconID: 135895,
    passive: true,
    hidden: 'always',
    name: 'Touch of Death/Expel Harm Notification Driver',
    icon: 'spell_holy_divineillumination.jpg',
  },
  KEG_SMASH: {
    id: 121253,
    type: 'baseline',
    iconID: 594274,
    passive: false,
    name: 'Keg Smash',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 8000,
      hasted: false,
    },
    icon: 'achievement_brewery_2.jpg',
  },
  POWER_STRIKES_TALENT: {
    id: 121817,
    type: 'mists-talent',
    row: 2,
    column: 1,
    iconID: 629484,
    passive: true,
    name: 'Power Strikes',
    icon: 'ability_monk_powerstrikes.jpg',
  },
  CHI_TORPEDO: {
    id: 121828,
    grantedBy: 115173,
    type: 'temporary',
    iconID: 607849,
    passive: false,
    name: 'Chi Torpedo',
    charges: {
      max: 3,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
    icon: 'ability_monk_quitornado.jpg',
  },
  CLASH: {
    id: 122057,
    type: 'baseline',
    iconID: 628134,
    passive: false,
    name: 'Clash',
    cooldown: {
      duration: 35000,
      hasted: false,
    },
    icon: 'ability_monk_clashingoxcharge.jpg',
  },
  DAMPEN_HARM_TALENT: {
    id: 122278,
    type: 'mists-talent',
    row: 4,
    column: 2,
    iconID: 620827,
    passive: false,
    name: 'Dampen Harm',
    cooldown: {
      duration: 90000,
      hasted: false,
    },
    icon: 'ability_monk_dampenharm.jpg',
  },
  HEALING_ELIXIRS_TALENT: {
    id: 122280,
    type: 'mists-talent',
    row: 4,
    column: 1,
    iconID: 608939,
    passive: true,
    name: 'Healing Elixirs',
    icon: 'ability_monk_jasmineforcetea.jpg',
  },
  HEALING_ELIXIRS_HIDDEN: {
    id: 122281,
    type: 'baseline',
    iconID: 608939,
    passive: false,
    hidden: 'always',
    name: 'Healing Elixirs',
    icon: 'ability_monk_jasmineforcetea.jpg',
  },
  DIFFUSE_MAGIC_TALENT: {
    id: 122783,
    type: 'mists-talent',
    row: 4,
    column: 3,
    iconID: 775460,
    passive: false,
    name: 'Diffuse Magic',
    cooldown: {
      duration: 90000,
      hasted: false,
    },
    icon: 'spell_monk_diffusemagic.jpg',
  },
  KEG_SMASH_HIDDEN: {
    id: 123192,
    type: 'baseline',
    iconID: 460686,
    passive: true,
    hidden: 'always',
    name: 'Keg Smash',
    icon: 'ability_deathknight_brittlebones.jpg',
  },
  SURGING_MIST: {
    id: 123273,
    type: 'baseline',
    iconID: 628135,
    passive: false,
    hidden: 'unless-learned',
    name: 'Surging Mist',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    castTime: {
      duration: 1500,
    },
    icon: 'ability_monk_surgingmist.jpg',
  },
  CRACKLING_JADE_LIGHTNING_CHI_PROC_DRIVER_HIDDEN: {
    id: 123332,
    type: 'baseline',
    iconID: 132269,
    passive: true,
    hidden: 'always',
    name: 'Crackling Jade Lightning Chi Proc Driver',
    icon: 'ability_parry.jpg',
  },
  FLYING_SERPENT_KICK_HIDDEN: {
    id: 123586,
    type: 'baseline',
    iconID: 463281,
    passive: false,
    hidden: 'always',
    name: 'Flying Serpent Kick',
    icon: 'priest_icon_chakra_green.jpg',
  },
  BREATH_OF_FIRE_HIDDEN: {
    id: 123725,
    type: 'baseline',
    iconID: 615339,
    passive: false,
    hidden: 'always',
    name: 'Breath of Fire',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'ability_monk_breathoffire.jpg',
  },
  INVOKE_XUEN_THE_WHITE_TIGER_TALENT: {
    id: 123904,
    type: 'mists-talent',
    row: 5,
    column: 2,
    iconID: 620832,
    passive: false,
    name: 'Invoke Xuen, the White Tiger',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
    icon: 'ability_monk_summontigerstatue.jpg',
  },
  CHI_BURST_TALENT: {
    id: 123986,
    type: 'mists-talent',
    row: 1,
    column: 3,
    iconID: 135734,
    passive: false,
    name: 'Chi Burst',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    castTime: {
      duration: 1000,
    },
    icon: 'spell_arcane_arcanetorrent.jpg',
  },
  GIFT_OF_THE_SERPENT_HIDDEN_1: {
    id: 124041,
    type: 'baseline',
    iconID: 606546,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Gift of the Serpent',
    icon: 'ability_monk_healthsphere.jpg',
  },
  GIFT_OF_THE_SERPENT_HIDDEN_2: {
    id: 135920,
    type: 'baseline',
    iconID: 606546,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Gift of the Serpent',
    icon: 'ability_monk_healthsphere.jpg',
  },
  ZEN_SPHERE_TALENT: {
    id: 124081,
    type: 'mists-talent',
    row: 1,
    column: 2,
    iconID: 613397,
    passive: false,
    name: 'Zen Sphere',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 10000,
      hasted: false,
    },
    icon: 'ability_monk_forcesphere.jpg',
  },
  ZEN_SPHERE: {
    id: 124098,
    type: 'baseline',
    iconID: 613397,
    passive: false,
    hidden: 'unless-learned',
    name: 'Zen Sphere',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'ability_monk_forcesphere.jpg',
  },
  ZEN_SPHERE_DETONATE_1: {
    id: 124101,
    type: 'baseline',
    iconID: 613397,
    passive: false,
    hidden: 'unless-learned',
    name: 'Zen Sphere: Detonate',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'ability_monk_forcesphere.jpg',
  },
  ZEN_SPHERE_DETONATE_2: {
    id: 125033,
    type: 'baseline',
    iconID: 613397,
    passive: false,
    hidden: 'unless-learned',
    name: 'Zen Sphere: Detonate',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'ability_monk_forcesphere.jpg',
  },
  DUAL_WIELD_PASSIVE: {
    id: 124146,
    type: 'baseline',
    iconID: 132147,
    passive: true,
    name: 'Dual Wield',
    icon: 'ability_dualwield.jpg',
  },
  TOUCH_OF_KARMA_HIDDEN: {
    id: 124280,
    type: 'baseline',
    iconID: 651728,
    passive: false,
    hidden: 'always',
    name: 'Touch of Karma',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'ability_monk_touchofkarma.jpg',
  },
  SWIFT_REFLEXES_PASSIVE: {
    id: 124334,
    type: 'baseline',
    iconID: 132171,
    passive: true,
    name: 'Swift Reflexes',
    icon: 'ability_hunter_displacement.jpg',
  },
  SWIFT_REFLEXES_HIDDEN: {
    id: 124335,
    type: 'baseline',
    iconID: 132171,
    passive: false,
    hidden: 'always',
    name: 'Swift Reflexes',
    icon: 'ability_hunter_displacement.jpg',
  },
  GIFT_OF_THE_OX_PASSIVE: {
    id: 124502,
    type: 'baseline',
    iconID: 236155,
    passive: true,
    name: 'Gift of the Ox',
    icon: 'ability_druid_giftoftheearthmother.jpg',
  },
  GIFT_OF_THE_OX_HIDDEN: {
    id: 124507,
    type: 'baseline',
    iconID: 606546,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Gift of the Ox',
    icon: 'ability_monk_healthsphere.jpg',
  },
  SOOTHING_MIST: {
    id: 125953,
    type: 'baseline',
    iconID: 606550,
    passive: false,
    hidden: 'unless-learned',
    name: 'Soothing Mist',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    icon: 'ability_monk_soothingmists.jpg',
  },
  DESPERATE_MEASURES_PASSIVE: {
    id: 126060,
    type: 'baseline',
    iconID: 136088,
    passive: true,
    name: 'Desperate Measures',
    icon: 'spell_nature_shamanrage.jpg',
  },
  DESPERATE_MEASURES_HIDDEN: {
    id: 126086,
    type: 'baseline',
    iconID: 136088,
    passive: true,
    hidden: 'always',
    name: 'Desperate Measures',
    icon: 'spell_nature_shamanrage.jpg',
  },
  EMINENCE: {
    id: 126890,
    type: 'baseline',
    iconID: 237237,
    castableWhileCasting: true,
    passive: false,
    hidden: 'unless-learned',
    name: 'Eminence',
    icon: 'inv_jewelcrafting_jadeserpent.jpg',
  },
  ZEN_PILGRIMAGE: {
    id: 126892,
    type: 'baseline',
    iconID: 775462,
    passive: false,
    name: 'Zen Pilgrimage',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 1800000,
      hasted: false,
    },
    castTime: {
      duration: 10000,
    },
    icon: 'spell_monk_zenpilgrimage.jpg',
  },
  ZEN_PILGRIMAGEDEATH_GATEMOONGLADE_STORAGE_AURA_I_HIDDEN: {
    id: 126893,
    type: 'baseline',
    iconID: 132181,
    passive: false,
    hidden: 'always',
    name: 'Zen Pilgrimage/Death Gate/Moonglade Storage Aura I',
    icon: 'ability_hunter_pathfinding.jpg',
  },
  ZEN_PILGRIMAGE_RETURN_HIDDEN: {
    id: 126895,
    type: 'baseline',
    iconID: 775462,
    passive: false,
    hidden: 'always',
    name: 'Zen Pilgrimage: Return',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    castTime: {
      duration: 10000,
    },
    icon: 'spell_monk_zenpilgrimage.jpg',
  },
  BLACKOUT_KICK_HIDDEN_1: {
    id: 128531,
    type: 'baseline',
    iconID: 574575,
    passive: false,
    hidden: 'always',
    name: 'Blackout Kick',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'ability_monk_roundhousekick.jpg',
  },
  BLACKOUT_KICK_HIDDEN_2: {
    id: 128591,
    type: 'baseline',
    iconID: 574575,
    passive: false,
    hidden: 'always',
    name: 'Blackout Kick',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'ability_monk_roundhousekick.jpg',
  },
  MONK_JAB_OVERRIDE_FIST_LOGIN_HIDDEN: {
    id: 128678,
    type: 'baseline',
    iconID: 132528,
    passive: false,
    hidden: 'always',
    name: 'Monk Jab Override Fist Login',
    icon: 'inv_bijou_gold.jpg',
  },
  BREWING_ELUSIVE_BREW_PASSIVE: {
    id: 128938,
    type: 'baseline',
    iconID: 613396,
    passive: true,
    name: 'Brewing: Elusive Brew',
    icon: 'ability_monk_elusiveale.jpg',
  },
  YOU_ARE_A_LEVEL_90_MONK_HIDDEN: {
    id: 130610,
    type: 'baseline',
    iconID: 572033,
    passive: true,
    hidden: 'always',
    name: 'You Are A Level 90 Monk',
    icon: 'pandarenracial_bouncy.jpg',
  },
  CHI_BURST_HIDDEN: {
    id: 130654,
    type: 'baseline',
    iconID: 135734,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Burst',
    icon: 'spell_arcane_arcanetorrent.jpg',
  },
  ENVELOPING_MIST_HIDDEN: {
    id: 132120,
    type: 'baseline',
    iconID: 775461,
    passive: false,
    hidden: 'always',
    name: 'Enveloping Mist',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    icon: 'spell_monk_envelopingmist.jpg',
  },
  CHI_WAVE_HIDDEN_1: {
    id: 132463,
    type: 'baseline',
    iconID: 606541,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Wave',
    icon: 'ability_monk_chiwave.jpg',
  },
  CHI_WAVE_HIDDEN_2: {
    id: 132467,
    type: 'baseline',
    iconID: 606541,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Wave',
    icon: 'ability_monk_chiwave.jpg',
  },
  STANCE_OF_THE_WISE_SERPENT_HIDDEN: {
    id: 136336,
    type: 'baseline',
    iconID: 611421,
    passive: false,
    hidden: 'always',
    name: 'Stance of the Wise Serpent',
    icon: 'monk_stance_wiseserpent.jpg',
  },
  HOTFIX_PASSIVE_HIDDEN_1: {
    id: 137022,
    type: 'baseline',
    iconID: 236216,
    passive: true,
    hidden: 'always',
    name: 'Hotfix Passive',
    icon: 'ability_mage_firestarter.jpg',
  },
  HOTFIX_PASSIVE_HIDDEN_2: {
    id: 137023,
    type: 'baseline',
    iconID: 236216,
    passive: true,
    hidden: 'always',
    name: 'Hotfix Passive',
    icon: 'ability_mage_firestarter.jpg',
  },
  NIMBLE_BREW: {
    id: 137562,
    type: 'baseline',
    iconID: 839394,
    passive: false,
    name: 'Nimble Brew',
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'spell_monk_nimblebrew.jpg',
  },
  REAWAKEN: {
    id: 1245934,
    type: 'baseline',
    iconID: 608952,
    passive: false,
    name: 'Reawaken',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 10000,
    },
    icon: 'spell_monk_mistweaver_spec.jpg',
  },
  YOU_ARE_A_LEVEL_85_MONK_HIDDEN: {
    id: 1251700,
    type: 'baseline',
    iconID: 572033,
    passive: true,
    hidden: 'always',
    name: 'You Are A Level 85 Monk',
    icon: 'pandarenracial_bouncy.jpg',
  },
} as const satisfies Record<string, RetailSpell & { icon: string }>;
export default SPELLS;
