import type { RetailSpell } from 'wow-dbc';
const SPELLS = {
  JAB: {
    id: 100780,
    type: 'baseline',
    iconID: 574572,
    passive: false,
    name: 'Jab',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'f',
  },
  BLACKOUT_KICK: {
    id: 100784,
    type: 'baseline',
    iconID: 574575,
    passive: false,
    name: 'Blackout Kick',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'm',
  },
  TIGER_PALM: {
    id: 100787,
    type: 'baseline',
    iconID: 606551,
    passive: false,
    name: 'Tiger Palm',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: '2',
  },
  SPINNING_CRANE_KICK: {
    id: 101546,
    type: 'baseline',
    iconID: 606543,
    passive: false,
    name: 'Spinning Crane Kick',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    channel: {
      duration: 2250,
      hasted: true,
      buffIsLogged: true,
      triggeredSpells: [
        {
          spell: 107270,
          period: 750,
          hasted: true,
        },
      ],
    },
    icon: 'o',
  },
  TRANSCENDENCE: {
    id: 101643,
    type: 'baseline',
    iconID: 627608,
    passive: false,
    name: 'Transcendence',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
    },
    castTime: {
      duration: 500,
    },
    icon: '',
  },
  STANCE_OF_THE_FIERCE_TIGER: {
    id: 103985,
    type: 'baseline',
    iconID: 611420,
    passive: false,
    name: 'Stance of the Fierce Tiger',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: '1',
  },
  SPINNING_CRANE_KICK_HIDDEN_1: {
    id: 107270,
    type: 'baseline',
    iconID: 606543,
    passive: false,
    hidden: 'always',
    name: 'Spinning Crane Kick',
    icon: 'o',
  },
  SPINNING_CRANE_KICK_HIDDEN_2: {
    id: 117640,
    type: 'baseline',
    iconID: 606543,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Spinning Crane Kick',
    icon: 'o',
  },
  DND_MONK_ENERGY_DRIVER_HIDDEN: {
    id: 107500,
    type: 'baseline',
    iconID: 236180,
    passive: true,
    hidden: 'always',
    name: '<DND> Monk Energy Driver',
    icon: '_',
  },
  MONK_WEAPON_OVERRIDE_DRIVER_HIDDEN: {
    id: 108562,
    type: 'baseline',
    iconID: 132528,
    passive: true,
    hidden: 'always',
    name: 'Monk Weapon Override Driver',
    icon: 'g',
  },
  WAY_OF_THE_MONK_HIDDEN_1: {
    id: 108977,
    type: 'baseline',
    iconID: 574570,
    passive: true,
    hidden: 'always',
    name: 'Way of the Monk',
    icon: 'e',
  },
  WAY_OF_THE_MONK_HIDDEN_2: {
    id: 120275,
    type: 'baseline',
    iconID: 574570,
    passive: true,
    hidden: 'always',
    name: 'Way of the Monk',
    icon: 'e',
  },
  ROLL_CELERITY_TALENT: {
    id: 121827,
    grantedBy: 115173,
    type: 'temporary',
    iconID: 574574,
    passive: false,
    name: 'Roll',
    charges: {
      max: 3,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
    icon: 's',
  },
  ROLL: {
    id: 109132,
    type: 'baseline',
    iconID: 574574,
    passive: false,
    name: 'Roll',
    charges: {
      max: 2,
    },
    cooldown: {
      duration: 20000,
      hasted: false,
    },
    icon: 's',
  },
  SYMBIOSIS: {
    id: 110500,
    type: 'baseline',
    iconID: 571587,
    passive: false,
    name: 'Symbiosis',
    icon: '',
  },
  CHI_TORPEDO_TALENT: {
    id: 115008,
    overrides: 109132,
    type: 'mists-talent',
    row: 5,
    column: 3,
    iconID: 607849,
    passive: false,
    name: 'Chi Torpedo',
    charges: {
      max: 2,
    },
    cooldown: {
      duration: 20000,
      hasted: false,
    },
    icon: 'n',
  },
  STANCE_OF_THE_STURDY_OX: {
    id: 115069,
    type: 'baseline',
    iconID: 611419,
    passive: false,
    name: 'Stance of the Sturdy Ox',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: '1',
  },
  EXPEL_HARM: {
    id: 115072,
    type: 'baseline',
    iconID: 627486,
    passive: false,
    name: 'Expel Harm',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
    icon: 'r',
  },
  FIGHTING_STYLE_PASSIVE: {
    id: 115074,
    type: 'baseline',
    iconID: 574577,
    passive: true,
    name: 'Fighting Style',
    icon: 'l',
  },
  PARALYSIS: {
    id: 115078,
    type: 'baseline',
    iconID: 629534,
    passive: false,
    name: 'Paralysis',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
    icon: '5',
  },
  TOUCH_OF_DEATH: {
    id: 115080,
    type: 'baseline',
    iconID: 606552,
    passive: false,
    name: 'Touch of Death',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 90000,
      hasted: false,
    },
    icon: '9',
  },
  CHI_WAVE_TALENT: {
    id: 115098,
    type: 'mists-talent',
    row: 1,
    column: 1,
    iconID: 606541,
    passive: false,
    name: 'Chi Wave',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
    icon: 'w',
  },
  EXPEL_HARM_HIDDEN: {
    id: 115129,
    type: 'baseline',
    iconID: 627486,
    passive: false,
    hidden: 'always',
    name: 'Expel Harm',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'r',
  },
  CELERITY_TALENT: {
    id: 115173,
    type: 'mists-talent',
    row: 0,
    column: 1,
    iconID: 607848,
    passive: true,
    name: 'Celerity',
    icon: 'o',
  },
  MOMENTUM_TALENT: {
    id: 115174,
    type: 'mists-talent',
    row: 0,
    column: 3,
    iconID: 574577,
    passive: true,
    name: 'Momentum',
    icon: 'l',
  },
  ZEN_MEDITATION: {
    id: 115176,
    type: 'baseline',
    iconID: 642417,
    passive: false,
    name: 'Zen Meditation',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
    channel: {
      duration: 8000,
      hasted: false,
      buffIsLogged: true,
      triggeredSpells: [],
    },
    icon: 't',
  },
  RESUSCITATE: {
    id: 115178,
    type: 'baseline',
    iconID: 132132,
    passive: false,
    name: 'Resuscitate',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 10000,
    },
    icon: 'n',
  },
  DIZZYING_HAZE_1: {
    id: 115180,
    type: 'baseline',
    iconID: 606544,
    passive: false,
    name: 'Dizzying Haze',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: '"',
  },
  DIZZYING_HAZE_2: {
    id: 118022,
    type: 'baseline',
    iconID: 606544,
    passive: false,
    hidden: 'unless-learned',
    name: 'Dizzying Haze',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    icon: '"',
  },
  BREATH_OF_FIRE: {
    id: 115181,
    type: 'baseline',
    iconID: 615339,
    passive: false,
    name: 'Breath of Fire',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'i',
  },
  FORTIFYING_BREW: {
    id: 115203,
    type: 'baseline',
    iconID: 615341,
    passive: false,
    name: 'Fortifying Brew',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
    icon: 'y',
  },
  AVERT_HARM: {
    id: 115213,
    type: 'baseline',
    iconID: 627605,
    passive: false,
    name: 'Avert Harm',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
    icon: 'r',
  },
  GUARD: {
    id: 115295,
    type: 'baseline',
    iconID: 611417,
    passive: false,
    name: 'Guard',
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: ',',
  },
  ELUSIVE_BREW: {
    id: 115308,
    type: 'baseline',
    iconID: 613396,
    passive: false,
    name: 'Elusive Brew',
    cooldown: {
      duration: 6000,
      hasted: false,
    },
    icon: '7',
  },
  SUMMON_BLACK_OX_STATUE: {
    id: 115315,
    type: 'baseline',
    iconID: 627607,
    passive: false,
    name: 'Summon Black Ox Statue',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 'd',
  },
  ASCENSION_TALENT: {
    id: 115396,
    type: 'mists-talent',
    row: 2,
    column: 2,
    iconID: 629482,
    passive: true,
    name: 'Ascension',
    icon: 'n',
  },
  CHI_BREW_TALENT: {
    id: 115399,
    type: 'mists-talent',
    row: 2,
    column: 3,
    iconID: 629483,
    passive: false,
    name: 'Chi Brew',
    charges: {
      max: 2,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
    },
    icon: 'd',
  },
  DETOX_1: {
    id: 115450,
    type: 'baseline',
    iconID: 135894,
    passive: false,
    name: 'Detox',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 8000,
      hasted: false,
    },
    icon: 'u',
  },
  DETOX_2: {
    id: 125170,
    type: 'baseline',
    iconID: 237171,
    passive: false,
    name: 'Detox',
    icon: '0',
  },
  HEALING_SPHERE: {
    id: 115460,
    type: 'baseline',
    iconID: 606546,
    passive: false,
    name: 'Healing Sphere',
    gcd: {
      duration: 500,
      hasted: true,
    },
    cooldown: {
      duration: 500,
      hasted: false,
    },
    icon: '"',
  },
  HEALING_SPHERE_HIDDEN_1: {
    id: 115464,
    type: 'baseline',
    iconID: 606546,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Healing Sphere',
    icon: '"',
  },
  HEALING_SPHERE_HIDDEN_2: {
    id: 125355,
    type: 'baseline',
    iconID: 606546,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Healing Sphere',
    icon: '"',
  },
  HEALING_SPHERE_HIDDEN_3: {
    id: 135914,
    type: 'baseline',
    iconID: 606546,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Healing Sphere',
    icon: '"',
  },
  LEER_OF_THE_OX: {
    id: 115543,
    type: 'baseline',
    iconID: 620829,
    passive: false,
    hidden: 'unless-learned',
    name: 'Leer of the Ox',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 20000,
      hasted: false,
    },
    icon: 'n',
  },
  PROVOKE: {
    id: 115546,
    type: 'baseline',
    iconID: 620830,
    passive: false,
    name: 'Provoke',
    cooldown: {
      duration: 8000,
      hasted: false,
    },
    icon: 'g',
  },
  EXPEL_HARM_DRIVER_HIDDEN: {
    id: 115612,
    type: 'baseline',
    iconID: 236218,
    passive: true,
    hidden: 'always',
    name: 'Expel Harm Driver',
    icon: 'k',
  },
  LEGACY_OF_THE_EMPEROR: {
    id: 115921,
    type: 'baseline',
    iconID: 606547,
    passive: false,
    name: 'Legacy of the Emperor',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    icon: '1',
  },
  DISABLE: {
    id: 116095,
    type: 'baseline',
    iconID: 132316,
    passive: false,
    name: 'Disable',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: '',
  },
  SPEAR_HAND_STRIKE: {
    id: 116705,
    type: 'baseline',
    iconID: 608940,
    passive: false,
    name: 'Spear Hand Strike',
    cooldown: {
      duration: 15000,
      hasted: false,
    },
    icon: 'w',
  },
  PARRY_PASSIVE: {
    id: 116812,
    type: 'baseline',
    iconID: 132269,
    passive: true,
    name: 'Parry',
    icon: 'l',
  },
  TIGERS_LUST_TALENT: {
    id: 116841,
    type: 'mists-talent',
    row: 0,
    column: 2,
    iconID: 651727,
    passive: false,
    name: "Tiger's Lust",
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: '',
  },
  RING_OF_PEACE_TALENT: {
    id: 116844,
    type: 'mists-talent',
    row: 3,
    column: 1,
    iconID: 839107,
    passive: false,
    name: 'Ring of Peace',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
    },
    icon: '"',
  },
  RUSHING_JADE_WIND_TALENT: {
    id: 116847,
    overrides: 101546,
    type: 'mists-talent',
    row: 5,
    column: 1,
    iconID: 606549,
    passive: false,
    name: 'Rushing Jade Wind',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 6000,
      hasted: true,
    },
    icon: '4',
  },
  SURGING_MIST_HIDDEN: {
    id: 116995,
    type: 'baseline',
    iconID: 628135,
    passive: false,
    hidden: 'always',
    name: 'Surging Mist',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'e',
  },
  GRAPPLE_WEAPON: {
    id: 117368,
    type: 'baseline',
    iconID: 132343,
    passive: false,
    name: 'Grapple Weapon',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: ':',
  },
  FISTS_OF_FURY_HIDDEN: {
    id: 117418,
    type: 'baseline',
    iconID: 627606,
    passive: false,
    hidden: 'always',
    name: 'Fists of Fury',
    icon: 'l',
  },
  EMINENCE_STATUE: {
    id: 117895,
    type: 'baseline',
    iconID: 237237,
    castableWhileCasting: true,
    passive: false,
    hidden: 'unless-learned',
    name: 'Eminence (Statue)',
    icon: 'w',
  },
  MASTERY_ELUSIVE_BRAWLER_PASSIVE: {
    id: 117906,
    type: 'baseline',
    iconID: 132792,
    passive: true,
    name: 'Mastery: Elusive Brawler',
    icon: 'o',
  },
  CRACKLING_JADE_LIGHTNING: {
    id: 117952,
    type: 'baseline',
    iconID: 606542,
    passive: false,
    name: 'Crackling Jade Lightning',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    channel: {
      duration: 6000,
      hasted: true,
      buffIsLogged: true,
      triggeredSpells: [],
    },
    icon: 'm',
  },
  CRACKLING_JADE_LIGHTNING_HIDDEN: {
    id: 117959,
    type: 'baseline',
    iconID: 132269,
    passive: true,
    hidden: 'always',
    name: 'Crackling Jade Lightning',
    icon: 'l',
  },
  BREWMASTER_TRAINING_PASSIVE: {
    id: 117967,
    type: 'baseline',
    iconID: 608950,
    passive: true,
    name: 'Brewmaster Training',
    icon: 'o',
  },
  CHI_TORPEDO_HIDDEN_1: {
    id: 117993,
    type: 'baseline',
    iconID: 607849,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Torpedo',
    icon: 'n',
  },
  CHI_TORPEDO_HIDDEN_2: {
    id: 124040,
    type: 'baseline',
    iconID: 607849,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Torpedo',
    icon: 'n',
  },
  LEG_SWEEP_TALENT: {
    id: 119381,
    type: 'mists-talent',
    row: 3,
    column: 3,
    iconID: 642414,
    passive: false,
    name: 'Leg Sweep',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
    },
    icon: 'n',
  },
  CHARGING_OX_WAVE_TALENT: {
    id: 119392,
    type: 'mists-talent',
    row: 3,
    column: 2,
    iconID: 615340,
    passive: false,
    name: 'Charging Ox Wave',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 't',
  },
  PURIFYING_BREW: {
    id: 119582,
    type: 'baseline',
    iconID: 133701,
    passive: false,
    name: 'Purifying Brew',
    cooldown: {
      duration: 1000,
      hasted: false,
    },
    icon: 'h',
  },
  RENEWING_MIST_HIDDEN: {
    id: 119611,
    type: 'baseline',
    iconID: 627487,
    passive: false,
    hidden: 'always',
    name: 'Renewing Mist',
    icon: 't',
  },
  ENERGY_USAGE_HIDDEN: {
    id: 119650,
    type: 'baseline',
    iconID: 135724,
    passive: false,
    hidden: 'always',
    name: 'Energy Usage',
    icon: 'a',
  },
  TRANSCENDENCE_TRANSFER: {
    id: 119996,
    type: 'baseline',
    iconID: 237585,
    passive: false,
    name: 'Transcendence: Transfer',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 25000,
      hasted: false,
    },
    castTime: {
      duration: 500,
    },
    icon: '3',
  },
  LEATHER_SPECIALIZATION_PASSIVE: {
    id: 120225,
    type: 'baseline',
    iconID: 132721,
    passive: true,
    hidden: 'unless-learned',
    name: 'Leather Specialization',
    icon: '0',
  },
  VENGEANCE_PASSIVE: {
    id: 120267,
    type: 'baseline',
    iconID: 136129,
    passive: true,
    name: 'Vengeance',
    icon: 'u',
  },
  TIGER_STRIKES_HIDDEN_1: {
    id: 120274,
    type: 'baseline',
    iconID: 136018,
    passive: false,
    hidden: 'always',
    name: 'Tiger Strikes',
    icon: '7',
  },
  TIGER_STRIKES_HIDDEN_2: {
    id: 120278,
    type: 'baseline',
    iconID: 136018,
    passive: false,
    hidden: 'always',
    name: 'Tiger Strikes',
    icon: '7',
  },
  WAY_OF_THE_MONK_PASSIVE: {
    id: 120277,
    type: 'baseline',
    iconID: 574570,
    passive: true,
    name: 'Way of the Monk',
    icon: 'e',
  },
  TOUCH_OF_DEATHEXPEL_HARM_NOTIFICATION_DRIVER_HIDDEN: {
    id: 121128,
    type: 'baseline',
    iconID: 135895,
    passive: true,
    hidden: 'always',
    name: 'Touch of Death/Expel Harm Notification Driver',
    icon: 'i',
  },
  KEG_SMASH: {
    id: 121253,
    type: 'baseline',
    iconID: 594274,
    passive: false,
    name: 'Keg Smash',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 8000,
      hasted: false,
    },
    icon: 'u',
  },
  POWER_STRIKES_TALENT: {
    id: 121817,
    type: 'mists-talent',
    row: 2,
    column: 1,
    iconID: 629484,
    passive: true,
    name: 'Power Strikes',
    icon: '_',
  },
  CHI_TORPEDO: {
    id: 121828,
    grantedBy: 115173,
    type: 'temporary',
    iconID: 607849,
    passive: false,
    name: 'Chi Torpedo',
    charges: {
      max: 3,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
    icon: 'n',
  },
  CLASH: {
    id: 122057,
    type: 'baseline',
    iconID: 628134,
    passive: false,
    name: 'Clash',
    cooldown: {
      duration: 35000,
      hasted: false,
    },
    icon: 'r',
  },
  DAMPEN_HARM_TALENT: {
    id: 122278,
    type: 'mists-talent',
    row: 4,
    column: 2,
    iconID: 620827,
    passive: false,
    name: 'Dampen Harm',
    cooldown: {
      duration: 90000,
      hasted: false,
    },
    icon: 'd',
  },
  HEALING_ELIXIRS_TALENT: {
    id: 122280,
    type: 'mists-talent',
    row: 4,
    column: 1,
    iconID: 608939,
    passive: true,
    name: 'Healing Elixirs',
    icon: '',
  },
  HEALING_ELIXIRS_HIDDEN: {
    id: 122281,
    type: 'baseline',
    iconID: 608939,
    passive: false,
    hidden: 'always',
    name: 'Healing Elixirs',
    icon: '',
  },
  DIFFUSE_MAGIC_TALENT: {
    id: 122783,
    type: 'mists-talent',
    row: 4,
    column: 3,
    iconID: 775460,
    passive: false,
    name: 'Diffuse Magic',
    cooldown: {
      duration: 90000,
      hasted: false,
    },
    icon: 'd',
  },
  KEG_SMASH_HIDDEN: {
    id: 123192,
    type: 'baseline',
    iconID: 460686,
    passive: true,
    hidden: 'always',
    name: 'Keg Smash',
    icon: '',
  },
  SURGING_MIST: {
    id: 123273,
    type: 'baseline',
    iconID: 628135,
    passive: false,
    hidden: 'unless-learned',
    name: 'Surging Mist',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    castTime: {
      duration: 1500,
    },
    icon: 'e',
  },
  CRACKLING_JADE_LIGHTNING_CHI_PROC_DRIVER_HIDDEN: {
    id: 123332,
    type: 'baseline',
    iconID: 132269,
    passive: true,
    hidden: 'always',
    name: 'Crackling Jade Lightning Chi Proc Driver',
    icon: 'l',
  },
  FLYING_SERPENT_KICK_HIDDEN: {
    id: 123586,
    type: 'baseline',
    iconID: 463281,
    passive: false,
    hidden: 'always',
    name: 'Flying Serpent Kick',
    icon: 'l',
  },
  BREATH_OF_FIRE_HIDDEN: {
    id: 123725,
    type: 'baseline',
    iconID: 615339,
    passive: false,
    hidden: 'always',
    name: 'Breath of Fire',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'i',
  },
  INVOKE_XUEN_THE_WHITE_TIGER_TALENT: {
    id: 123904,
    type: 'mists-talent',
    row: 5,
    column: 2,
    iconID: 620832,
    passive: false,
    name: 'Invoke Xuen, the White Tiger',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
    icon: '',
  },
  CHI_BURST_TALENT: {
    id: 123986,
    type: 'mists-talent',
    row: 1,
    column: 3,
    iconID: 135734,
    passive: false,
    name: 'Chi Burst',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    castTime: {
      duration: 1000,
    },
    icon: '_',
  },
  GIFT_OF_THE_SERPENT_HIDDEN_1: {
    id: 124041,
    type: 'baseline',
    iconID: 606546,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Gift of the Serpent',
    icon: '"',
  },
  GIFT_OF_THE_SERPENT_HIDDEN_2: {
    id: 135920,
    type: 'baseline',
    iconID: 606546,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Gift of the Serpent',
    icon: '"',
  },
  ZEN_SPHERE_TALENT: {
    id: 124081,
    type: 'mists-talent',
    row: 1,
    column: 2,
    iconID: 613397,
    passive: false,
    name: 'Zen Sphere',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 10000,
      hasted: false,
    },
    icon: '"',
  },
  ZEN_SPHERE: {
    id: 124098,
    type: 'baseline',
    iconID: 613397,
    passive: false,
    hidden: 'unless-learned',
    name: 'Zen Sphere',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: '"',
  },
  ZEN_SPHERE_DETONATE_1: {
    id: 124101,
    type: 'baseline',
    iconID: 613397,
    passive: false,
    hidden: 'unless-learned',
    name: 'Zen Sphere: Detonate',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: '"',
  },
  ZEN_SPHERE_DETONATE_2: {
    id: 125033,
    type: 'baseline',
    iconID: 613397,
    passive: false,
    hidden: 'unless-learned',
    name: 'Zen Sphere: Detonate',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: '"',
  },
  DUAL_WIELD_PASSIVE: {
    id: 124146,
    type: 'baseline',
    iconID: 132147,
    passive: true,
    name: 'Dual Wield',
    icon: 'r',
  },
  TOUCH_OF_KARMA_HIDDEN: {
    id: 124280,
    type: 'baseline',
    iconID: 651728,
    passive: false,
    hidden: 'always',
    name: 'Touch of Karma',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'w',
  },
  SWIFT_REFLEXES_PASSIVE: {
    id: 124334,
    type: 'baseline',
    iconID: 132171,
    passive: true,
    name: 'Swift Reflexes',
    icon: '.',
  },
  SWIFT_REFLEXES_HIDDEN: {
    id: 124335,
    type: 'baseline',
    iconID: 132171,
    passive: false,
    hidden: 'always',
    name: 'Swift Reflexes',
    icon: '.',
  },
  GIFT_OF_THE_OX_PASSIVE: {
    id: 124502,
    type: 'baseline',
    iconID: 236155,
    passive: true,
    name: 'Gift of the Ox',
    icon: 'n',
  },
  GIFT_OF_THE_OX_HIDDEN: {
    id: 124507,
    type: 'baseline',
    iconID: 606546,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Gift of the Ox',
    icon: '"',
  },
  SOOTHING_MIST: {
    id: 125953,
    type: 'baseline',
    iconID: 606550,
    passive: false,
    hidden: 'unless-learned',
    name: 'Soothing Mist',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    icon: '6',
  },
  DESPERATE_MEASURES_PASSIVE: {
    id: 126060,
    type: 'baseline',
    iconID: 136088,
    passive: true,
    name: 'Desperate Measures',
    icon: 'u',
  },
  DESPERATE_MEASURES_HIDDEN: {
    id: 126086,
    type: 'baseline',
    iconID: 136088,
    passive: true,
    hidden: 'always',
    name: 'Desperate Measures',
    icon: 'u',
  },
  EMINENCE: {
    id: 126890,
    type: 'baseline',
    iconID: 237237,
    castableWhileCasting: true,
    passive: false,
    hidden: 'unless-learned',
    name: 'Eminence',
    icon: 'w',
  },
  ZEN_PILGRIMAGE: {
    id: 126892,
    type: 'baseline',
    iconID: 775462,
    passive: false,
    name: 'Zen Pilgrimage',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 1800000,
      hasted: false,
    },
    castTime: {
      duration: 10000,
    },
    icon: 'a',
  },
  ZEN_PILGRIMAGEDEATH_GATEMOONGLADE_STORAGE_AURA_I_HIDDEN: {
    id: 126893,
    type: 'baseline',
    iconID: 132181,
    passive: false,
    hidden: 'always',
    name: 'Zen Pilgrimage/Death Gate/Moonglade Storage Aura I',
    icon: '8',
  },
  ZEN_PILGRIMAGE_RETURN_HIDDEN: {
    id: 126895,
    type: 'baseline',
    iconID: 775462,
    passive: false,
    hidden: 'always',
    name: 'Zen Pilgrimage: Return',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    castTime: {
      duration: 10000,
    },
    icon: 'a',
  },
  BLACKOUT_KICK_HIDDEN_1: {
    id: 128531,
    type: 'baseline',
    iconID: 574575,
    passive: false,
    hidden: 'always',
    name: 'Blackout Kick',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'm',
  },
  BLACKOUT_KICK_HIDDEN_2: {
    id: 128591,
    type: 'baseline',
    iconID: 574575,
    passive: false,
    hidden: 'always',
    name: 'Blackout Kick',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'm',
  },
  MONK_JAB_OVERRIDE_FIST_LOGIN_HIDDEN: {
    id: 128678,
    type: 'baseline',
    iconID: 132528,
    passive: false,
    hidden: 'always',
    name: 'Monk Jab Override Fist Login',
    icon: 'g',
  },
  BREWING_ELUSIVE_BREW_PASSIVE: {
    id: 128938,
    type: 'baseline',
    iconID: 613396,
    passive: true,
    name: 'Brewing: Elusive Brew',
    icon: '7',
  },
  YOU_ARE_A_LEVEL_90_MONK_HIDDEN: {
    id: 130610,
    type: 'baseline',
    iconID: 572033,
    passive: true,
    hidden: 'always',
    name: 'You Are A Level 90 Monk',
    icon: 'u',
  },
  CHI_BURST_HIDDEN: {
    id: 130654,
    type: 'baseline',
    iconID: 135734,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Burst',
    icon: '_',
  },
  ENVELOPING_MIST_HIDDEN: {
    id: 132120,
    type: 'baseline',
    iconID: 775461,
    passive: false,
    hidden: 'always',
    name: 'Enveloping Mist',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    icon: 'r',
  },
  CHI_WAVE_HIDDEN_1: {
    id: 132463,
    type: 'baseline',
    iconID: 606541,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Wave',
    icon: 'w',
  },
  CHI_WAVE_HIDDEN_2: {
    id: 132467,
    type: 'baseline',
    iconID: 606541,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Wave',
    icon: 'w',
  },
  STANCE_OF_THE_WISE_SERPENT_HIDDEN: {
    id: 136336,
    type: 'baseline',
    iconID: 611421,
    passive: false,
    hidden: 'always',
    name: 'Stance of the Wise Serpent',
    icon: '4',
  },
  HOTFIX_PASSIVE_HIDDEN_1: {
    id: 137022,
    type: 'baseline',
    iconID: 236216,
    passive: true,
    hidden: 'always',
    name: 'Hotfix Passive',
    icon: 'n',
  },
  HOTFIX_PASSIVE_HIDDEN_2: {
    id: 137023,
    type: 'baseline',
    iconID: 236216,
    passive: true,
    hidden: 'always',
    name: 'Hotfix Passive',
    icon: 'n',
  },
  NIMBLE_BREW: {
    id: 137562,
    type: 'baseline',
    iconID: 839394,
    passive: false,
    name: 'Nimble Brew',
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'u',
  },
  REAWAKEN: {
    id: 1245934,
    type: 'baseline',
    iconID: 608952,
    passive: false,
    name: 'Reawaken',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 10000,
    },
    icon: '',
  },
  YOU_ARE_A_LEVEL_85_MONK_HIDDEN: {
    id: 1251700,
    type: 'baseline',
    iconID: 572033,
    passive: true,
    hidden: 'always',
    name: 'You Are A Level 85 Monk',
    icon: 'u',
  },
} as const satisfies Record<string, RetailSpell & { icon: string }>;
export default SPELLS;
