const SPELLS = {
  JAB: {
    id: 100780,
    type: 'baseline',
    label: [22, 16],
    classMask: [4, 0, 0, 0],
    effects: [
      {
        sourceSpellId: 103985,
        aura: 107,
        basePoints: 1,
        misc0: 12,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Jab',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  BLACKOUT_KICK: {
    id: 100784,
    type: 'baseline',
    label: [22, 16],
    classMask: [16, 0, 0, 0],
    effects: [
      {
        sourceSpellId: 137023,
        aura: 108,
        basePoints: 25,
        misc0: 0,
        misc1: 0,
        pointModifiers: [],
      },
    ],
    passive: false,
    name: 'Blackout Kick',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  TIGER_PALM: {
    id: 100787,
    type: 'baseline',
    label: [22, 16],
    classMask: [1024, 0, 0, 0],
    effects: [
      {
        sourceSpellId: 117967,
        aura: 108,
        basePoints: -100,
        misc0: 14,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Tiger Palm',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  SPINNING_CRANE_KICK: {
    id: 101546,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, -2147483648, 0, 0],
    effects: [],
    passive: false,
    name: 'Spinning Crane Kick',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    channel: {
      duration: 2250,
      hasted: true,
      buffIsLogged: true,
      triggeredSpells: [
        {
          spell: 107270,
          period: 750,
          hasted: true,
        },
      ],
    },
  },
  TRANSCENDENCE: {
    id: 101643,
    type: 'baseline',
    label: [22, 16],
    classMask: [512, 0, 0, 0],
    effects: [],
    passive: false,
    name: 'Transcendence',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
    },
    castTime: {
      duration: 500,
    },
  },
  STANCE_OF_THE_FIERCE_TIGER: {
    id: 103985,
    type: 'baseline',
    label: [22, 16],
    classMask: [8192, 0, 0, 0],
    effects: [],
    passive: false,
    name: 'Stance of the Fierce Tiger',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  SPINNING_CRANE_KICK_HIDDEN_1: {
    id: 107270,
    type: 'baseline',
    label: [22, 16],
    classMask: [256, 0, 0, 0],
    effects: [],
    passive: false,
    hidden: 'always',
    name: 'Spinning Crane Kick',
  },
  SPINNING_CRANE_KICK_HIDDEN_2: {
    id: 117640,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 2097152, 0],
    effects: [
      {
        sourceSpellId: 130610,
        aura: 4,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 1251700,
        aura: 4,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 124502,
        aura: 4,
        basePoints: 1,
        misc0: 15,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Spinning Crane Kick',
  },
  DND_MONK_ENERGY_DRIVER_HIDDEN: {
    id: 107500,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    hidden: 'always',
    name: '<DND> Monk Energy Driver',
  },
  MONK_WEAPON_OVERRIDE_DRIVER_HIDDEN: {
    id: 108562,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    hidden: 'always',
    name: 'Monk Weapon Override Driver',
  },
  WAY_OF_THE_MONK_HIDDEN_1: {
    id: 108977,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 524288, 0],
    effects: [],
    passive: true,
    hidden: 'always',
    name: 'Way of the Monk',
  },
  WAY_OF_THE_MONK_HIDDEN_2: {
    id: 120275,
    type: 'baseline',
    label: [22, 16],
    effects: [],
    passive: true,
    hidden: 'always',
    name: 'Way of the Monk',
  },
  ROLL_CELERITY_TALENT: {
    id: 121827,
    grantedBy: 115173,
    type: 'temporary',
    label: [22, 16],
    classMask: [128, 262144, 0, 0],
    effects: [
      {
        sourceSpellId: 121128,
        aura: 4,
        basePoints: 5,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 115173,
        aura: 332,
        basePoints: 121827,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Roll',
    charges: {
      max: 3,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
  },
  ROLL: {
    id: 109132,
    type: 'baseline',
    label: [22, 16],
    classMask: [128, 262144, 0, 0],
    effects: [
      {
        sourceSpellId: 121128,
        aura: 4,
        basePoints: 5,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 115173,
        aura: 332,
        basePoints: 121827,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Roll',
    charges: {
      max: 2,
    },
    cooldown: {
      duration: 20000,
      hasted: false,
    },
  },
  SYMBIOSIS: {
    id: 110500,
    type: 'baseline',
    label: [22, 16],
    classMask: [16384, 0, 0, 0],
    effects: [],
    passive: false,
    name: 'Symbiosis',
  },
  CHI_TORPEDO_TALENT: {
    id: 115008,
    overrides: 109132,
    type: 'mists-talent',
    row: 5,
    column: 3,
    label: [22, 16],
    classMask: [128, 2, 0, 0],
    effects: [
      {
        sourceSpellId: 121128,
        aura: 4,
        basePoints: 5,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 115173,
        aura: 332,
        basePoints: 121828,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Chi Torpedo',
    charges: {
      max: 2,
    },
    cooldown: {
      duration: 20000,
      hasted: false,
    },
  },
  STANCE_OF_THE_STURDY_OX: {
    id: 115069,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 4, 0, 0],
    effects: [],
    passive: false,
    name: 'Stance of the Sturdy Ox',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  EXPEL_HARM: {
    id: 115072,
    type: 'baseline',
    label: [22, 16],
    classMask: [131072, 0, -2147483648, 0],
    effects: [
      {
        sourceSpellId: 103985,
        aura: 107,
        basePoints: 1,
        misc0: 12,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 115295,
        aura: 283,
        basePoints: 30,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 126060,
        aura: 108,
        basePoints: -100,
        misc0: 11,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Expel Harm',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
  },
  FIGHTING_STYLE_PASSIVE: {
    id: 115074,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    name: 'Fighting Style',
  },
  PARALYSIS: {
    id: 115078,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 8, 8388608, 0],
    effects: [
      {
        sourceSpellId: 115612,
        aura: 4,
        basePoints: 50,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Paralysis',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
  },
  TOUCH_OF_DEATH: {
    id: 115080,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 256, 8, 0],
    effects: [],
    passive: false,
    name: 'Touch of Death',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 90000,
      hasted: false,
    },
  },
  CHI_WAVE_TALENT: {
    id: 115098,
    type: 'mists-talent',
    row: 1,
    column: 1,
    label: [22, 16],
    classMask: [2, 0, 0, 0],
    effects: [],
    passive: false,
    name: 'Chi Wave',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
  },
  EXPEL_HARM_HIDDEN: {
    id: 115129,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 1024, 0],
    effects: [],
    passive: false,
    hidden: 'always',
    name: 'Expel Harm',
    gcd: {
      duration: 1500,
      hasted: true,
    },
  },
  CELERITY_TALENT: {
    id: 115173,
    type: 'mists-talent',
    row: 0,
    column: 1,
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    name: 'Celerity',
  },
  MOMENTUM_TALENT: {
    id: 115174,
    type: 'mists-talent',
    row: 0,
    column: 3,
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    name: 'Momentum',
  },
  ZEN_MEDITATION: {
    id: 115176,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 8192, 0, 0],
    effects: [],
    passive: false,
    name: 'Zen Meditation',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
    channel: {
      duration: 8000,
      hasted: false,
      buffIsLogged: true,
      triggeredSpells: [],
    },
  },
  RESUSCITATE: {
    id: 115178,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 16384, 0, 0],
    effects: [],
    passive: false,
    name: 'Resuscitate',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 10000,
    },
  },
  DIZZYING_HAZE_1: {
    id: 115180,
    type: 'baseline',
    label: [22, 16],
    classMask: [128, 0, 0, 0],
    effects: [
      {
        sourceSpellId: 121128,
        aura: 4,
        basePoints: 5,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Dizzying Haze',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  DIZZYING_HAZE_2: {
    id: 118022,
    type: 'baseline',
    label: [22, 16],
    classMask: [128, 0, 0, 0],
    effects: [
      {
        sourceSpellId: 121128,
        aura: 4,
        basePoints: 5,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    hidden: 'unless-learned',
    name: 'Dizzying Haze',
    gcd: {
      duration: 1500,
      hasted: false,
    },
  },
  BREATH_OF_FIRE: {
    id: 115181,
    type: 'baseline',
    label: [22, 16],
    classMask: [524288, 0, 8, 0],
    effects: [],
    passive: false,
    name: 'Breath of Fire',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  FORTIFYING_BREW: {
    id: 115203,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 3145728, 0, 0],
    effects: [],
    passive: false,
    name: 'Fortifying Brew',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
  },
  AVERT_HARM: {
    id: 115213,
    type: 'baseline',
    label: [22, 16],
    classMask: [2097152, 0, 0, 0],
    effects: [],
    passive: false,
    name: 'Avert Harm',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
  },
  GUARD: {
    id: 115295,
    type: 'baseline',
    label: [22, 16],
    classMask: [268435456, 0, 8, 0],
    effects: [],
    passive: false,
    name: 'Guard',
    cooldown: {
      duration: 30000,
      hasted: false,
    },
  },
  ELUSIVE_BREW: {
    id: 115308,
    type: 'baseline',
    label: [22, 16],
    classMask: [4096, 2097152, 0, 0],
    effects: [
      {
        sourceSpellId: 130610,
        aura: 4,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 1251700,
        aura: 4,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 124502,
        aura: 4,
        basePoints: 1,
        misc0: 15,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Elusive Brew',
    cooldown: {
      duration: 6000,
      hasted: false,
    },
  },
  SUMMON_BLACK_OX_STATUE: {
    id: 115315,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: false,
    name: 'Summon Black Ox Statue',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
  },
  ASCENSION_TALENT: {
    id: 115396,
    type: 'mists-talent',
    row: 2,
    column: 2,
    label: [22, 16],
    effects: [],
    passive: true,
    name: 'Ascension',
  },
  CHI_BREW_TALENT: {
    id: 115399,
    type: 'mists-talent',
    row: 2,
    column: 3,
    label: [22, 16],
    classMask: [0, 2097152, 268435456, 0],
    effects: [],
    passive: false,
    name: 'Chi Brew',
    charges: {
      max: 2,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
    },
  },
  DETOX_1: {
    id: 115450,
    type: 'baseline',
    label: [22, 16],
    classMask: [4194304, 0, 0, 0],
    effects: [],
    passive: false,
    name: 'Detox',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 8000,
      hasted: false,
    },
  },
  DETOX_2: {
    id: 125170,
    type: 'baseline',
    label: [22, 16],
    effects: [],
    passive: false,
    name: 'Detox',
  },
  HEALING_SPHERE: {
    id: 115460,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 1024, 131072, 0],
    effects: [
      {
        sourceSpellId: 115295,
        aura: 283,
        basePoints: 30,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Healing Sphere',
    gcd: {
      duration: 500,
      hasted: true,
    },
    cooldown: {
      duration: 500,
      hasted: false,
    },
  },
  HEALING_SPHERE_HIDDEN_1: {
    id: 115464,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 1024, 0, 0],
    effects: [
      {
        sourceSpellId: 115295,
        aura: 283,
        basePoints: 30,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Healing Sphere',
  },
  HEALING_SPHERE_HIDDEN_2: {
    id: 125355,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Healing Sphere',
  },
  HEALING_SPHERE_HIDDEN_3: {
    id: 135914,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 1024, 0, 0],
    effects: [
      {
        sourceSpellId: 115295,
        aura: 283,
        basePoints: 30,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Healing Sphere',
  },
  LEER_OF_THE_OX: {
    id: 115543,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: false,
    hidden: 'unless-learned',
    name: 'Leer of the Ox',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 20000,
      hasted: false,
    },
  },
  PROVOKE: {
    id: 115546,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: false,
    name: 'Provoke',
    cooldown: {
      duration: 8000,
      hasted: false,
    },
  },
  EXPEL_HARM_DRIVER_HIDDEN: {
    id: 115612,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    hidden: 'always',
    name: 'Expel Harm Driver',
  },
  LEGACY_OF_THE_EMPEROR: {
    id: 115921,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 134217728, 0],
    effects: [],
    passive: false,
    name: 'Legacy of the Emperor',
    gcd: {
      duration: 1000,
      hasted: true,
    },
  },
  DISABLE: {
    id: 116095,
    type: 'baseline',
    label: [22, 16],
    classMask: [536870912, 0, 0, 0],
    effects: [],
    passive: false,
    name: 'Disable',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  SPEAR_HAND_STRIKE: {
    id: 116705,
    type: 'baseline',
    label: [22, 16],
    classMask: [1073741824, 0, 0, 0],
    effects: [],
    passive: false,
    name: 'Spear Hand Strike',
    cooldown: {
      duration: 15000,
      hasted: false,
    },
  },
  PARRY_PASSIVE: {
    id: 116812,
    type: 'baseline',
    label: [22, 16],
    effects: [],
    passive: true,
    name: 'Parry',
  },
  TIGERS_LUST_TALENT: {
    id: 116841,
    type: 'mists-talent',
    row: 0,
    column: 2,
    label: [22, 16],
    classMask: [0, 32768, 0, 0],
    effects: [
      {
        sourceSpellId: 121128,
        aura: 4,
        basePoints: 5,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: "Tiger's Lust",
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
  },
  RING_OF_PEACE_TALENT: {
    id: 116844,
    type: 'mists-talent',
    row: 3,
    column: 1,
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: false,
    name: 'Ring of Peace',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
    },
  },
  RUSHING_JADE_WIND_TALENT: {
    id: 116847,
    overrides: 101546,
    type: 'mists-talent',
    row: 5,
    column: 1,
    label: [22, 16],
    classMask: [32, 0, 0, 0],
    effects: [
      {
        sourceSpellId: 115074,
        aura: 416,
        basePoints: 100,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Rushing Jade Wind',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 6000,
      hasted: true,
    },
  },
  SURGING_MIST_HIDDEN: {
    id: 116995,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 2048, 0, 0],
    effects: [],
    passive: false,
    hidden: 'always',
    name: 'Surging Mist',
    gcd: {
      duration: 1500,
      hasted: true,
    },
  },
  GRAPPLE_WEAPON: {
    id: 117368,
    type: 'baseline',
    label: [22, 16],
    classMask: [512, 0, 0, 0],
    effects: [],
    passive: false,
    name: 'Grapple Weapon',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
  },
  FISTS_OF_FURY_HIDDEN: {
    id: 117418,
    type: 'baseline',
    label: [22, 16],
    classMask: [1048576, 0, 0, 0],
    effects: [],
    passive: false,
    hidden: 'always',
    name: 'Fists of Fury',
  },
  EMINENCE_STATUE: {
    id: 117895,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 262144, 0],
    effects: [],
    castableWhileCasting: true,
    passive: false,
    hidden: 'unless-learned',
    name: 'Eminence (Statue)',
  },
  MASTERY_ELUSIVE_BRAWLER_PASSIVE: {
    id: 117906,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    name: 'Mastery: Elusive Brawler',
  },
  CRACKLING_JADE_LIGHTNING: {
    id: 117952,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 1, 64, 0],
    effects: [],
    passive: false,
    name: 'Crackling Jade Lightning',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    channel: {
      duration: 6000,
      hasted: true,
      buffIsLogged: true,
      triggeredSpells: [],
    },
  },
  CRACKLING_JADE_LIGHTNING_HIDDEN: {
    id: 117959,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    hidden: 'always',
    name: 'Crackling Jade Lightning',
  },
  BREWMASTER_TRAINING_PASSIVE: {
    id: 117967,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    name: 'Brewmaster Training',
  },
  CHI_TORPEDO_HIDDEN_1: {
    id: 117993,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 65536, 0],
    effects: [],
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Torpedo',
  },
  CHI_TORPEDO_HIDDEN_2: {
    id: 124040,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 1056768, 0],
    effects: [
      {
        sourceSpellId: 115295,
        aura: 283,
        basePoints: 30,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Torpedo',
  },
  LEG_SWEEP_TALENT: {
    id: 119381,
    type: 'mists-talent',
    row: 3,
    column: 3,
    label: [22, 16],
    classMask: [0, 512, 0, 0],
    effects: [],
    passive: false,
    name: 'Leg Sweep',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
    },
  },
  CHARGING_OX_WAVE_TALENT: {
    id: 119392,
    type: 'mists-talent',
    row: 3,
    column: 2,
    label: [22, 16],
    classMask: [0, 65536, 0, 0],
    effects: [
      {
        sourceSpellId: 121128,
        aura: 4,
        basePoints: 5,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Charging Ox Wave',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
  },
  PURIFYING_BREW: {
    id: 119582,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 2097152, 12, 0],
    effects: [],
    passive: false,
    name: 'Purifying Brew',
    cooldown: {
      duration: 1000,
      hasted: false,
    },
  },
  RENEWING_MIST_HIDDEN: {
    id: 119611,
    type: 'baseline',
    label: [22, 16],
    classMask: [8388608, 0, 0, 0],
    effects: [],
    passive: false,
    hidden: 'always',
    name: 'Renewing Mist',
  },
  ENERGY_USAGE_HIDDEN: {
    id: 119650,
    type: 'baseline',
    label: [22, 16],
    effects: [],
    passive: false,
    hidden: 'always',
    name: 'Energy Usage',
  },
  TRANSCENDENCE_TRANSFER: {
    id: 119996,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 4194304, 0, 0],
    effects: [],
    passive: false,
    name: 'Transcendence: Transfer',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 25000,
      hasted: false,
    },
    castTime: {
      duration: 500,
    },
  },
  LEATHER_SPECIALIZATION_PASSIVE: {
    id: 120225,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    hidden: 'unless-learned',
    name: 'Leather Specialization',
  },
  VENGEANCE_PASSIVE: {
    id: 120267,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    name: 'Vengeance',
  },
  TIGER_STRIKES_HIDDEN_1: {
    id: 120274,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 4096, 0, 0],
    effects: [
      {
        sourceSpellId: 108977,
        aura: 108,
        basePoints: 40,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    hidden: 'always',
    name: 'Tiger Strikes',
  },
  TIGER_STRIKES_HIDDEN_2: {
    id: 120278,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 4096, 0, 0],
    effects: [
      {
        sourceSpellId: 108977,
        aura: 108,
        basePoints: 40,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    hidden: 'always',
    name: 'Tiger Strikes',
  },
  WAY_OF_THE_MONK_PASSIVE: {
    id: 120277,
    type: 'baseline',
    label: [22, 16],
    effects: [],
    passive: true,
    name: 'Way of the Monk',
  },
  TOUCH_OF_DEATHEXPEL_HARM_NOTIFICATION_DRIVER_HIDDEN: {
    id: 121128,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    hidden: 'always',
    name: 'Touch of Death/Expel Harm Notification Driver',
  },
  KEG_SMASH: {
    id: 121253,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 33554432, 0, 0],
    effects: [
      {
        sourceSpellId: 123192,
        aura: 109,
        basePoints: 100,
        misc0: 1,
        misc1: 0,
        pointModifiers: {},
        triggeredSpell: 115798,
      },
    ],
    passive: false,
    name: 'Keg Smash',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 8000,
      hasted: false,
    },
  },
  POWER_STRIKES_TALENT: {
    id: 121817,
    type: 'mists-talent',
    row: 2,
    column: 1,
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    name: 'Power Strikes',
  },
  CHI_TORPEDO: {
    id: 121828,
    grantedBy: 115173,
    type: 'temporary',
    label: [22, 16],
    classMask: [128, 2, 0, 0],
    effects: [
      {
        sourceSpellId: 121128,
        aura: 4,
        basePoints: 5,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 115173,
        aura: 332,
        basePoints: 121828,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Chi Torpedo',
    charges: {
      max: 3,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
  },
  CLASH: {
    id: 122057,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 4096, 0],
    effects: [],
    passive: false,
    name: 'Clash',
    cooldown: {
      duration: 35000,
      hasted: false,
    },
  },
  DAMPEN_HARM_TALENT: {
    id: 122278,
    type: 'mists-talent',
    row: 4,
    column: 2,
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: false,
    name: 'Dampen Harm',
    cooldown: {
      duration: 90000,
      hasted: false,
    },
  },
  HEALING_ELIXIRS_TALENT: {
    id: 122280,
    type: 'mists-talent',
    row: 4,
    column: 1,
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    name: 'Healing Elixirs',
  },
  HEALING_ELIXIRS_HIDDEN: {
    id: 122281,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 8192, 0],
    effects: [
      {
        sourceSpellId: 115295,
        aura: 283,
        basePoints: 30,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    hidden: 'always',
    name: 'Healing Elixirs',
  },
  DIFFUSE_MAGIC_TALENT: {
    id: 122783,
    type: 'mists-talent',
    row: 4,
    column: 3,
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: false,
    name: 'Diffuse Magic',
    cooldown: {
      duration: 90000,
      hasted: false,
    },
  },
  KEG_SMASH_HIDDEN: {
    id: 123192,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    hidden: 'always',
    name: 'Keg Smash',
  },
  SURGING_MIST: {
    id: 123273,
    type: 'baseline',
    label: [22, 16],
    classMask: [33554432, 0, 0, 0],
    effects: [],
    passive: false,
    hidden: 'unless-learned',
    name: 'Surging Mist',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    castTime: {
      duration: 1500,
    },
  },
  CRACKLING_JADE_LIGHTNING_CHI_PROC_DRIVER_HIDDEN: {
    id: 123332,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    hidden: 'always',
    name: 'Crackling Jade Lightning Chi Proc Driver',
  },
  FLYING_SERPENT_KICK_HIDDEN: {
    id: 123586,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 32, 0],
    effects: [],
    passive: false,
    hidden: 'always',
    name: 'Flying Serpent Kick',
  },
  BREATH_OF_FIRE_HIDDEN: {
    id: 123725,
    type: 'baseline',
    label: [22, 16],
    classMask: [524288, 0, 0, 0],
    effects: [],
    passive: false,
    hidden: 'always',
    name: 'Breath of Fire',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  INVOKE_XUEN_THE_WHITE_TIGER_TALENT: {
    id: 123904,
    type: 'mists-talent',
    row: 5,
    column: 2,
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: false,
    name: 'Invoke Xuen, the White Tiger',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
  },
  CHI_BURST_TALENT: {
    id: 123986,
    type: 'mists-talent',
    row: 1,
    column: 3,
    label: [22, 16],
    classMask: [0, 64, 0, 0],
    effects: [],
    passive: false,
    name: 'Chi Burst',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    castTime: {
      duration: 1000,
    },
  },
  GIFT_OF_THE_SERPENT_HIDDEN_1: {
    id: 124041,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 1024, 1073741824, 0],
    effects: [
      {
        sourceSpellId: 115295,
        aura: 283,
        basePoints: 30,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Gift of the Serpent',
  },
  GIFT_OF_THE_SERPENT_HIDDEN_2: {
    id: 135920,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 1024, 1073741824, 0],
    effects: [
      {
        sourceSpellId: 115295,
        aura: 283,
        basePoints: 30,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Gift of the Serpent',
  },
  ZEN_SPHERE_TALENT: {
    id: 124081,
    type: 'mists-talent',
    row: 1,
    column: 2,
    label: [22, 16],
    classMask: [262144, 0, 67117056, 0],
    effects: [
      {
        sourceSpellId: 115295,
        aura: 283,
        basePoints: 30,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Zen Sphere',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 10000,
      hasted: false,
    },
  },
  ZEN_SPHERE: {
    id: 124098,
    type: 'baseline',
    label: [22, 16],
    classMask: [262144, 0, 0, 0],
    effects: [],
    passive: false,
    hidden: 'unless-learned',
    name: 'Zen Sphere',
    gcd: {
      duration: 1500,
      hasted: true,
    },
  },
  ZEN_SPHERE_DETONATE_1: {
    id: 124101,
    type: 'baseline',
    label: [22, 16],
    classMask: [262144, 0, 67117056, 0],
    effects: [
      {
        sourceSpellId: 115295,
        aura: 283,
        basePoints: 30,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    hidden: 'unless-learned',
    name: 'Zen Sphere: Detonate',
    gcd: {
      duration: 1500,
      hasted: true,
    },
  },
  ZEN_SPHERE_DETONATE_2: {
    id: 125033,
    type: 'baseline',
    label: [22, 16],
    classMask: [262144, 0, 0, 0],
    effects: [],
    passive: false,
    hidden: 'unless-learned',
    name: 'Zen Sphere: Detonate',
    gcd: {
      duration: 1500,
      hasted: true,
    },
  },
  DUAL_WIELD_PASSIVE: {
    id: 124146,
    type: 'baseline',
    label: [22, 16],
    effects: [],
    passive: true,
    name: 'Dual Wield',
  },
  TOUCH_OF_KARMA_HIDDEN: {
    id: 124280,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: false,
    hidden: 'always',
    name: 'Touch of Karma',
    gcd: {
      duration: 1500,
      hasted: true,
    },
  },
  SWIFT_REFLEXES_PASSIVE: {
    id: 124334,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    name: 'Swift Reflexes',
  },
  SWIFT_REFLEXES_HIDDEN: {
    id: 124335,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: false,
    hidden: 'always',
    name: 'Swift Reflexes',
  },
  GIFT_OF_THE_OX_PASSIVE: {
    id: 124502,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    name: 'Gift of the Ox',
  },
  GIFT_OF_THE_OX_HIDDEN: {
    id: 124507,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 8192, 0],
    effects: [
      {
        sourceSpellId: 115295,
        aura: 283,
        basePoints: 30,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Gift of the Ox',
  },
  SOOTHING_MIST: {
    id: 125953,
    type: 'baseline',
    label: [22, 16],
    classMask: [16777216, 0, 0, 0],
    effects: [
      {
        sourceSpellId: 132120,
        aura: 283,
        basePoints: 30,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    hidden: 'unless-learned',
    name: 'Soothing Mist',
    gcd: {
      duration: 1000,
      hasted: true,
    },
  },
  DESPERATE_MEASURES_PASSIVE: {
    id: 126060,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    name: 'Desperate Measures',
  },
  DESPERATE_MEASURES_HIDDEN: {
    id: 126086,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    hidden: 'always',
    name: 'Desperate Measures',
  },
  EMINENCE: {
    id: 126890,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 262144, 0],
    effects: [],
    castableWhileCasting: true,
    passive: false,
    hidden: 'unless-learned',
    name: 'Eminence',
  },
  ZEN_PILGRIMAGE: {
    id: 126892,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, -2147483648],
    effects: [],
    passive: false,
    name: 'Zen Pilgrimage',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 1800000,
      hasted: false,
    },
    castTime: {
      duration: 10000,
    },
  },
  ZEN_PILGRIMAGEDEATH_GATEMOONGLADE_STORAGE_AURA_I_HIDDEN: {
    id: 126893,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: false,
    hidden: 'always',
    name: 'Zen Pilgrimage/Death Gate/Moonglade Storage Aura I',
  },
  ZEN_PILGRIMAGE_RETURN_HIDDEN: {
    id: 126895,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: false,
    hidden: 'always',
    name: 'Zen Pilgrimage: Return',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    castTime: {
      duration: 10000,
    },
  },
  BLACKOUT_KICK_HIDDEN_1: {
    id: 128531,
    type: 'baseline',
    label: [22, 16],
    classMask: [16, 0, 0, 0],
    effects: [
      {
        sourceSpellId: 137023,
        aura: 108,
        basePoints: 25,
        misc0: 0,
        misc1: 0,
        pointModifiers: [],
      },
    ],
    passive: false,
    hidden: 'always',
    name: 'Blackout Kick',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  BLACKOUT_KICK_HIDDEN_2: {
    id: 128591,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: false,
    hidden: 'always',
    name: 'Blackout Kick',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  MONK_JAB_OVERRIDE_FIST_LOGIN_HIDDEN: {
    id: 128678,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: false,
    hidden: 'always',
    name: 'Monk Jab Override Fist Login',
  },
  BREWING_ELUSIVE_BREW_PASSIVE: {
    id: 128938,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    name: 'Brewing: Elusive Brew',
  },
  YOU_ARE_A_LEVEL_90_MONK_HIDDEN: {
    id: 130610,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    hidden: 'always',
    name: 'You Are A Level 90 Monk',
  },
  CHI_BURST_HIDDEN: {
    id: 130654,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 64, 33562624, 0],
    effects: [
      {
        sourceSpellId: 115295,
        aura: 283,
        basePoints: 30,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Burst',
  },
  ENVELOPING_MIST_HIDDEN: {
    id: 132120,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 32768, 0],
    effects: [],
    passive: false,
    hidden: 'always',
    name: 'Enveloping Mist',
    gcd: {
      duration: 1000,
      hasted: true,
    },
  },
  CHI_WAVE_HIDDEN_1: {
    id: 132463,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 67108864, 8192, 0],
    effects: [
      {
        sourceSpellId: 115295,
        aura: 283,
        basePoints: 30,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Wave',
  },
  CHI_WAVE_HIDDEN_2: {
    id: 132467,
    type: 'baseline',
    label: [22, 16],
    classMask: [134217728, 0, 0, 0],
    effects: [],
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Wave',
  },
  STANCE_OF_THE_WISE_SERPENT_HIDDEN: {
    id: 136336,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: false,
    hidden: 'always',
    name: 'Stance of the Wise Serpent',
  },
  HOTFIX_PASSIVE_HIDDEN_1: {
    id: 137022,
    type: 'baseline',
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    hidden: 'always',
    name: 'Hotfix Passive',
  },
  HOTFIX_PASSIVE_HIDDEN_2: {
    id: 137023,
    type: 'baseline',
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    hidden: 'always',
    name: 'Hotfix Passive',
  },
  NIMBLE_BREW: {
    id: 137562,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 2097152, 0, 0],
    effects: [],
    passive: false,
    name: 'Nimble Brew',
    cooldown: {
      duration: 120000,
      hasted: false,
    },
  },
  REAWAKEN: {
    id: 1245934,
    type: 'baseline',
    effects: [],
    passive: false,
    name: 'Reawaken',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 10000,
    },
  },
  YOU_ARE_A_LEVEL_85_MONK_HIDDEN: {
    id: 1251700,
    type: 'baseline',
    label: [22, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    hidden: 'always',
    name: 'You Are A Level 85 Monk',
  },
} as const;
export default SPELLS;
