export const SCINTILLATION_PROC_CHANCE = 0.15;

export const VOLATILITY_PROC_CHANCE = 0.15;

export const BLAZING_SHARDS_DURATION = 5;

export const ARCANE_INTENSITY_MULTIPLIER = 0.08;

export const HEAT_WAVE_MULTIPLIER = 0.2;

export const SPELLWEAVERS_DOMINANCE_CRIT_MULTIPLIER = 0.15;

export const HONED_AGGRESSION_MULTIPLIER = 0.05;

export const TITANIC_WRATH_MULTIPLIER = 0.075;

export const EYE_OF_INFINITY_MULTIPLIER = 0.15;

export const ENGULFING_BLAZE_MULTIPLIER = 0.25;

export const LAY_WASTE_MULTIPLIER = 0.2;

export const IRIDESCENCE_MULTIPLIER = 0.2;

export const DISINTEGRATE_TICKS = 4;
export const DISINTEGRATE_CHAINED_TICKS = 5;

export const CAUSALITY_DISINTEGRATE_CDR_MS = 500;
export const CAUSALITY_PYRE_CDR_MS = 400;

export const DEVA_T31_2PC_MULTIPLER = 0.05;
export const DENSE_ENERGY_ESSENCE_REDUCTION = 1;
