import SPELLS from 'common/SPELLS';

export const ARCANE_POWER_MANA_THRESHOLD = 0.40;
export const TIME_ANOMALY_MANA_THRESHOLD = 0.70;

export const ARCANE_POWER_SPELL_BLACKLIST = [
  SPELLS.ARCANE_BARRAGE,
  SPELLS.ARCANE_FAMILIAR_TALENT,
  SPELLS.ARCANE_INTELLECT,
  SPELLS.EVOCATION,
  SPELLS.SUPERNOVA_TALENT,
  SPELLS.MIRROR_IMAGE_TALENT,
  SPELLS.NETHER_TEMPEST_TALENT,
  SPELLS.ARCANE_ORB_TALENT,
  SPELLS.RUNE_OF_POWER_TALENT,
];

export const ARCANE_CHARGE_SPELLS = [
  SPELLS.ARCANE_BLAST,
  SPELLS.ARCANE_EXPLOSION,
  SPELLS.CHARGED_UP_TALENT,
];