import type { RetailSpell } from 'wow-dbc';
const SPELLS = {
  PATH_OF_FROST: {
    id: 3714,
    type: 'baseline',
    iconID: 237528,
    passive: false,
    name: 'Path of Frost',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'spell_deathknight_pathoffrost.jpg',
  },
  ARMY_OF_THE_DEAD: {
    id: 42650,
    type: 'baseline',
    iconID: 237511,
    passive: false,
    name: 'Army of the Dead',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 600000,
      hasted: false,
    },
    channel: {
      duration: 4000,
      hasted: false,
      buffIsLogged: true,
      triggeredSpells: [
        {
          spell: 42651,
          period: 500,
          hasted: false,
        },
      ],
    },
    icon: 'spell_deathknight_armyofthedead.jpg',
  },
  DEATH_AND_DECAY_1: {
    id: 43265,
    type: 'baseline',
    iconID: 136144,
    passive: false,
    name: 'Death and Decay',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 'spell_shadow_deathanddecay.jpg',
  },
  DEATH_AND_DECAY_2: {
    id: 52212,
    type: 'baseline',
    iconID: 136144,
    castableWhileCasting: true,
    passive: false,
    hidden: 'unless-learned',
    name: 'Death and Decay',
    icon: 'spell_shadow_deathanddecay.jpg',
  },
  PLAGUE_STRIKE: {
    id: 45462,
    type: 'baseline',
    iconID: 237519,
    passive: false,
    name: 'Plague Strike',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'spell_deathknight_empowerruneblade.jpg',
  },
  ICY_TOUCH: {
    id: 45477,
    type: 'baseline',
    iconID: 237526,
    passive: false,
    name: 'Icy Touch',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    icon: 'spell_deathknight_icetouch.jpg',
  },
  CHAINS_OF_ICE: {
    id: 45524,
    type: 'baseline',
    iconID: 135834,
    passive: false,
    name: 'Chains of Ice',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    icon: 'spell_frost_chainsofice.jpg',
  },
  BLOOD_TAP_TALENT: {
    id: 45529,
    type: 'mists-talent',
    row: 4,
    column: 1,
    iconID: 237515,
    passive: false,
    name: 'Blood Tap',
    icon: 'spell_deathknight_bloodtap.jpg',
  },
  BLOOD_STRIKE: {
    id: 45902,
    type: 'baseline',
    iconID: 135772,
    passive: false,
    name: 'Blood Strike',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'spell_deathknight_deathstrike.jpg',
  },
  RAISE_DEAD: {
    id: 46584,
    type: 'baseline',
    iconID: 136119,
    passive: false,
    name: 'Raise Dead',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'spell_shadow_animatedead.jpg',
  },
  STRANGULATE: {
    id: 47476,
    type: 'baseline',
    iconID: 136214,
    passive: false,
    name: 'Strangulate',
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: 'spell_shadow_soulleech_3.jpg',
  },
  MIND_FREEZE: {
    id: 47528,
    type: 'baseline',
    iconID: 237527,
    passive: false,
    name: 'Mind Freeze',
    cooldown: {
      duration: 15000,
      hasted: false,
    },
    icon: 'spell_deathknight_mindfreeze.jpg',
  },
  DEATH_COIL: {
    id: 47541,
    type: 'baseline',
    iconID: 136145,
    passive: false,
    name: 'Death Coil',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    icon: 'spell_shadow_deathcoil.jpg',
  },
  EMPOWER_RUNE_WEAPON: {
    id: 47568,
    type: 'baseline',
    iconID: 135372,
    passive: false,
    name: 'Empower Rune Weapon',
    cooldown: {
      duration: 300000,
      hasted: false,
    },
    icon: 'inv_sword_62.jpg',
  },
  BLOOD_PRESENCE: {
    id: 48263,
    type: 'baseline',
    iconID: 135770,
    passive: false,
    name: 'Blood Presence',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'spell_deathknight_bloodpresence.jpg',
  },
  UNHOLY_PRESENCE: {
    id: 48265,
    type: 'baseline',
    iconID: 135775,
    passive: false,
    name: 'Unholy Presence',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'spell_deathknight_unholypresence.jpg',
  },
  FROST_PRESENCE: {
    id: 48266,
    type: 'baseline',
    iconID: 135773,
    passive: false,
    name: 'Frost Presence',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'spell_deathknight_frostpresence.jpg',
  },
  ANTI_MAGIC_SHELL: {
    id: 48707,
    type: 'baseline',
    iconID: 136120,
    passive: false,
    name: 'Anti-Magic Shell',
    cooldown: {
      duration: 45000,
      hasted: false,
    },
    icon: 'spell_shadow_antimagicshell.jpg',
  },
  BLOOD_BOIL: {
    id: 48721,
    type: 'baseline',
    iconID: 237513,
    passive: false,
    name: 'Blood Boil',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    icon: 'spell_deathknight_bloodboil.jpg',
  },
  DEATH_PACT_TALENT: {
    id: 48743,
    type: 'mists-talent',
    row: 3,
    column: 1,
    iconID: 136146,
    passive: false,
    name: 'Death Pact',
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'spell_shadow_deathpact.jpg',
  },
  ICEBOUND_FORTITUDE: {
    id: 48792,
    type: 'baseline',
    iconID: 237525,
    passive: false,
    name: 'Icebound Fortitude',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
    icon: 'spell_deathknight_iceboundfortitude.jpg',
  },
  RUNE_TAP: {
    id: 48982,
    type: 'baseline',
    iconID: 237529,
    passive: false,
    name: 'Rune Tap',
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 'spell_deathknight_runetap.jpg',
  },
  DANCING_RUNE_WEAPON: {
    id: 49028,
    type: 'baseline',
    iconID: 135277,
    passive: false,
    name: 'Dancing Rune Weapon',
    cooldown: {
      duration: 90000,
      hasted: false,
    },
    icon: 'inv_sword_07.jpg',
  },
  LICHBORNE_TALENT: {
    id: 49039,
    type: 'mists-talent',
    row: 1,
    column: 1,
    iconID: 136187,
    passive: false,
    hidden: 'unless-learned',
    name: 'Lichborne',
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'spell_shadow_raisedead.jpg',
  },
  BONE_SHIELD: {
    id: 49222,
    type: 'baseline',
    iconID: 458717,
    passive: false,
    name: 'Bone Shield',
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: 'ability_deathknight_boneshield.jpg',
  },
  SCENT_OF_BLOOD_PASSIVE: {
    id: 49509,
    type: 'baseline',
    iconID: 132284,
    passive: true,
    name: 'Scent of Blood',
    icon: 'ability_rogue_bloodyeye.jpg',
  },
  BLOOD_PARASITE_PASSIVE: {
    id: 49542,
    type: 'baseline',
    iconID: 136211,
    passive: true,
    name: 'Blood Parasite',
    icon: 'spell_shadow_soulleech.jpg',
  },
  DEATH_GRIP: {
    id: 49576,
    type: 'baseline',
    iconID: 237532,
    passive: false,
    name: 'Death Grip',
    cooldown: {
      duration: 25000,
      hasted: false,
    },
    icon: 'spell_deathknight_strangulate.jpg',
  },
  DEATH_STRIKE: {
    id: 49998,
    type: 'baseline',
    iconID: 237517,
    passive: false,
    name: 'Death Strike',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'spell_deathknight_butcher2.jpg',
  },
  VETERAN_OF_THE_THIRD_WAR_PASSIVE: {
    id: 50029,
    type: 'baseline',
    iconID: 136005,
    passive: true,
    name: 'Veteran of the Third War',
    icon: 'spell_misc_warsongfocus.jpg',
  },
  BLOOD_RITES_PASSIVE: {
    id: 50034,
    type: 'baseline',
    iconID: 237515,
    passive: true,
    name: 'Blood Rites',
    icon: 'spell_deathknight_bloodtap.jpg',
  },
  CHILBLAINS_TALENT: {
    id: 50041,
    type: 'mists-talent',
    row: 2,
    column: 2,
    iconID: 135864,
    passive: true,
    name: 'Chilblains',
    icon: 'spell_frost_wisp.jpg',
  },
  IMPROVED_BLOOD_PRESENCE_PASSIVE: {
    id: 50371,
    type: 'baseline',
    iconID: 135770,
    passive: true,
    name: 'Improved Blood Presence',
    icon: 'spell_deathknight_bloodpresence.jpg',
  },
  PESTILENCE: {
    id: 50842,
    type: 'baseline',
    iconID: 136182,
    passive: false,
    name: 'Pestilence',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    icon: 'spell_shadow_plaguecloud.jpg',
  },
  DEATH_GATE: {
    id: 50977,
    type: 'baseline',
    iconID: 135766,
    passive: false,
    hidden: 'unless-learned',
    name: 'Death Gate',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    castTime: {
      duration: 10000,
    },
    icon: 'spell_arcane_teleportundercity.jpg',
  },
  ANTI_MAGIC_ZONE_TALENT: {
    id: 51052,
    type: 'mists-talent',
    row: 1,
    column: 2,
    iconID: 237510,
    passive: false,
    hidden: 'unless-learned',
    name: 'Anti-Magic Zone',
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'spell_deathknight_antimagiczone.jpg',
  },
  RUNIC_CORRUPTION_TALENT: {
    id: 51462,
    type: 'mists-talent',
    row: 4,
    column: 3,
    iconID: 252272,
    passive: true,
    name: 'Runic Corruption',
    icon: 'spell_shadow_rune.jpg',
  },
  ON_A_PALE_HORSE_PASSIVE: {
    id: 51986,
    type: 'baseline',
    iconID: 132264,
    passive: true,
    name: 'On a Pale Horse',
    icon: 'ability_mount_undeadhorse.jpg',
  },
  HEART_STRIKE: {
    id: 55050,
    type: 'baseline',
    overrides: 45902,
    iconID: 135675,
    passive: false,
    name: 'Heart Strike',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'inv_weapon_shortblade_40.jpg',
  },
  BLOOD_PLAGUE_HIDDEN: {
    id: 55078,
    type: 'baseline',
    iconID: 237514,
    passive: false,
    hidden: 'always',
    name: 'Blood Plague',
    icon: 'spell_deathknight_bloodplague.jpg',
  },
  FROST_FEVER_HIDDEN: {
    id: 55095,
    type: 'baseline',
    iconID: 237522,
    passive: false,
    hidden: 'always',
    name: 'Frost Fever',
    icon: 'spell_deathknight_frostfever.jpg',
  },
  VAMPIRIC_BLOOD: {
    id: 55233,
    type: 'baseline',
    iconID: 136168,
    passive: false,
    name: 'Vampiric Blood',
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: 'spell_shadow_lifedrain.jpg',
  },
  DARK_COMMAND: {
    id: 56222,
    type: 'baseline',
    iconID: 136088,
    passive: false,
    name: 'Dark Command',
    cooldown: {
      duration: 8000,
      hasted: false,
    },
    icon: 'spell_nature_shamanrage.jpg',
  },
  RUNE_STRIKE: {
    id: 56815,
    type: 'baseline',
    iconID: 237518,
    passive: false,
    name: 'Rune Strike',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'spell_deathknight_darkconviction.jpg',
  },
  HORN_OF_WINTER: {
    id: 57330,
    type: 'baseline',
    iconID: 134228,
    passive: false,
    name: 'Horn of Winter',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 20000,
      hasted: false,
    },
    icon: 'inv_misc_horn_02.jpg',
  },
  BLOOD_PLAGUE_PASSIVE: {
    id: 59879,
    type: 'baseline',
    iconID: 237514,
    passive: true,
    name: 'Blood Plague',
    icon: 'spell_deathknight_bloodplague.jpg',
  },
  FROST_FEVER_PASSIVE: {
    id: 59921,
    type: 'baseline',
    iconID: 237522,
    passive: true,
    name: 'Frost Fever',
    icon: 'spell_deathknight_frostfever.jpg',
  },
  RAISE_ALLY: {
    id: 61999,
    type: 'baseline',
    iconID: 136143,
    passive: false,
    name: 'Raise Ally',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 600000,
      hasted: false,
    },
    icon: 'spell_shadow_deadofnight.jpg',
  },
  NECROTIC_STRIKE: {
    id: 73975,
    type: 'baseline',
    iconID: 132481,
    passive: false,
    name: 'Necrotic Strike',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'inv_axe_96.jpg',
  },
  MASTERY_BLOOD_SHIELD_PASSIVE: {
    id: 77513,
    type: 'baseline',
    iconID: 135772,
    passive: true,
    name: 'Mastery: Blood Shield',
    icon: 'spell_deathknight_deathstrike.jpg',
  },
  OUTBREAK: {
    id: 77575,
    type: 'baseline',
    iconID: 348565,
    passive: false,
    name: 'Outbreak',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 'spell_deathvortex.jpg',
  },
  DARK_SIMULACRUM: {
    id: 77606,
    type: 'baseline',
    iconID: 135888,
    passive: false,
    name: 'Dark Simulacrum',
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: 'spell_holy_consumemagic.jpg',
  },
  SANGUINE_FORTITUDE_PASSIVE: {
    id: 81127,
    type: 'baseline',
    iconID: 458719,
    passive: true,
    name: 'Sanguine Fortitude',
    icon: 'ability_deathknight_sanguinfortitude.jpg',
  },
  SCARLET_FEVER_PASSIVE: {
    id: 81132,
    type: 'baseline',
    iconID: 458735,
    passive: true,
    name: 'Scarlet Fever',
    icon: 'ability_rogue_vendetta.jpg',
  },
  CRIMSON_SCOURGE_PASSIVE: {
    id: 81136,
    type: 'baseline',
    iconID: 237513,
    passive: true,
    name: 'Crimson Scourge',
    icon: 'spell_deathknight_bloodboil.jpg',
  },
  WILL_OF_THE_NECROPOLIS_PASSIVE: {
    id: 81164,
    type: 'baseline',
    iconID: 132094,
    passive: true,
    name: 'Will of the Necropolis',
    icon: 'ability_creature_cursed_02.jpg',
  },
  RUNIC_EMPOWERMENT_TALENT: {
    id: 81229,
    type: 'mists-talent',
    row: 4,
    column: 2,
    iconID: 134423,
    passive: true,
    hidden: 'unless-learned',
    name: 'Runic Empowerment',
    icon: 'inv_misc_rune_10.jpg',
  },
  PARRY_PASSIVE: {
    id: 82246,
    type: 'baseline',
    iconID: 132269,
    passive: true,
    name: 'Parry',
    icon: 'ability_parry.jpg',
  },
  PLATE_SPECIALIZATION_PASSIVE: {
    id: 86524,
    type: 'baseline',
    iconID: 132747,
    passive: true,
    name: 'Plate Specialization',
    icon: 'inv_chest_plate12.jpg',
  },
  PLATE_SPECIALIZATION_HIDDEN: {
    id: 86537,
    type: 'baseline',
    iconID: 132750,
    passive: true,
    hidden: 'always',
    name: 'Plate Specialization',
    icon: 'inv_chest_plate15.jpg',
  },
  DEATH_STRIKE_ENABLER_HIDDEN: {
    id: 89832,
    type: 'baseline',
    iconID: 136243,
    passive: true,
    hidden: 'always',
    name: 'Death Strike Enabler',
    icon: 'trade_engineering.jpg',
  },
  VENGEANCE_PASSIVE: {
    id: 93099,
    type: 'baseline',
    iconID: 136129,
    passive: true,
    name: 'Vengeance',
    icon: 'spell_shadow_charm.jpg',
  },
  DEATHS_ADVANCE_TALENT: {
    id: 96268,
    type: 'mists-talent',
    row: 2,
    column: 1,
    iconID: 237561,
    passive: false,
    name: "Death's Advance",
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 'spell_shadow_demonicempathy.jpg',
  },
  ROILING_BLOOD_TALENT: {
    id: 108170,
    type: 'mists-talent',
    row: 0,
    column: 1,
    iconID: 538561,
    passive: true,
    name: 'Roiling Blood',
    icon: 'ability_deathknight_roilingblood.jpg',
  },
  ASPHYXIATE_TALENT: {
    id: 108194,
    overrides: 47476,
    type: 'mists-talent',
    row: 2,
    column: 3,
    iconID: 538558,
    passive: false,
    name: 'Asphyxiate',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 'ability_deathknight_asphixiate.jpg',
  },
  DEATH_SIPHON_TALENT: {
    id: 108196,
    type: 'mists-talent',
    row: 3,
    column: 2,
    iconID: 538559,
    passive: false,
    name: 'Death Siphon',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    icon: 'ability_deathknight_deathsiphon.jpg',
  },
  GOREFIENDS_GRASP_TALENT: {
    id: 108199,
    type: 'mists-talent',
    row: 5,
    column: 1,
    iconID: 538767,
    passive: false,
    name: "Gorefiend's Grasp",
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: 'ability_deathknight_aoedeathgrip.jpg',
  },
  REMORSELESS_WINTER_TALENT: {
    id: 108200,
    type: 'mists-talent',
    row: 5,
    column: 2,
    iconID: 538770,
    passive: false,
    name: 'Remorseless Winter',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: 'ability_deathknight_remorselesswinters2.jpg',
  },
  DESECRATED_GROUND_TALENT: {
    id: 108201,
    type: 'mists-talent',
    row: 5,
    column: 3,
    iconID: 538768,
    passive: false,
    name: 'Desecrated Ground',
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'ability_deathknight_desecratedground.jpg',
  },
  SYMBIOSIS: {
    id: 110498,
    type: 'baseline',
    iconID: 571587,
    passive: false,
    name: 'Symbiosis',
    icon: 'spell_druid_symbiosis.jpg',
  },
  CONTROL_UNDEAD: {
    id: 111673,
    type: 'baseline',
    iconID: 237273,
    passive: false,
    name: 'Control Undead',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    castTime: {
      duration: 1500,
    },
    icon: 'inv_misc_bone_skull_01.jpg',
  },
  PURGATORY_TALENT: {
    id: 114556,
    type: 'mists-talent',
    row: 1,
    column: 3,
    iconID: 134430,
    passive: true,
    name: 'Purgatory',
    icon: 'inv_misc_shadowegg.jpg',
  },
  SOUL_REAPER: {
    id: 114866,
    type: 'baseline',
    iconID: 636333,
    passive: false,
    name: 'Soul Reaper',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 6000,
      hasted: false,
    },
    icon: 'ability_deathknight_soulreaper.jpg',
  },
  UNHOLY_BLIGHT_TALENT: {
    id: 115989,
    type: 'mists-talent',
    row: 0,
    column: 3,
    iconID: 136132,
    passive: false,
    name: 'Unholy Blight',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 90000,
      hasted: false,
    },
    icon: 'spell_shadow_contagion.jpg',
  },
  CONVERSION_TALENT: {
    id: 119975,
    type: 'mists-talent',
    row: 3,
    column: 3,
    iconID: 538560,
    passive: false,
    name: 'Conversion',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    icon: 'ability_deathknight_deathsiphon2.jpg',
  },
  PLAGUE_LEECH_TALENT: {
    id: 123693,
    type: 'mists-talent',
    row: 0,
    column: 2,
    iconID: 132099,
    passive: false,
    name: 'Plague Leech',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 25000,
      hasted: false,
    },
    icon: 'ability_creature_disease_02.jpg',
  },
  DEATHS_ADVANCE_HIDDEN: {
    id: 124285,
    type: 'learned',
    taughtBy: 96268,
    iconID: 237561,
    passive: true,
    hidden: 'always',
    name: "Death's Advance",
    icon: 'spell_shadow_demonicempathy.jpg',
  },
  HOTFIX_PASSIVE_HIDDEN_1: {
    id: 137005,
    type: 'baseline',
    iconID: 236216,
    passive: true,
    hidden: 'always',
    name: 'Hotfix Passive',
    icon: 'ability_mage_firestarter.jpg',
  },
  HOTFIX_PASSIVE_HIDDEN_2: {
    id: 137008,
    type: 'baseline',
    iconID: 236216,
    passive: true,
    hidden: 'always',
    name: 'Hotfix Passive',
    icon: 'ability_mage_firestarter.jpg',
  },
  RIPOSTE_PASSIVE: {
    id: 145676,
    type: 'baseline',
    iconID: 132354,
    passive: true,
    name: 'Riposte',
    icon: 'ability_warrior_riposte.jpg',
  },
  SCENT_OF_BLOOD_HIDDEN: {
    id: 148211,
    type: 'baseline',
    iconID: 132284,
    passive: true,
    hidden: 'always',
    name: 'Scent of Blood',
    icon: 'ability_rogue_bloodyeye.jpg',
  },
} as const satisfies Record<string, RetailSpell & { icon: string }>;
export default SPELLS;
