import type { RetailSpell } from 'wow-dbc';
const SPELLS = {
  PATH_OF_FROST: {
    id: 3714,
    type: 'baseline',
    passive: false,
    name: 'Path of Frost',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  ARMY_OF_THE_DEAD: {
    id: 42650,
    type: 'baseline',
    passive: false,
    name: 'Army of the Dead',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 600000,
      hasted: false,
    },
    channel: {
      duration: 4000,
      hasted: false,
      buffIsLogged: true,
      triggeredSpells: [
        {
          spell: 42651,
          period: 500,
          hasted: false,
        },
      ],
    },
  },
  DEATH_AND_DECAY_1: {
    id: 43265,
    type: 'baseline',
    passive: false,
    name: 'Death and Decay',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
  },
  DEATH_AND_DECAY_2: {
    id: 52212,
    type: 'baseline',
    castableWhileCasting: true,
    passive: false,
    hidden: 'unless-learned',
    name: 'Death and Decay',
  },
  PLAGUE_STRIKE: {
    id: 45462,
    type: 'baseline',
    passive: false,
    name: 'Plague Strike',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  ICY_TOUCH: {
    id: 45477,
    type: 'baseline',
    passive: false,
    name: 'Icy Touch',
    gcd: {
      duration: 1000,
      hasted: true,
    },
  },
  CHAINS_OF_ICE: {
    id: 45524,
    type: 'baseline',
    passive: false,
    name: 'Chains of Ice',
    gcd: {
      duration: 1000,
      hasted: true,
    },
  },
  BLOOD_TAP_TALENT: {
    id: 45529,
    type: 'mists-talent',
    row: 4,
    column: 1,
    passive: false,
    name: 'Blood Tap',
  },
  BLOOD_STRIKE: {
    id: 45902,
    type: 'baseline',
    passive: false,
    name: 'Blood Strike',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  RAISE_DEAD: {
    id: 46584,
    type: 'baseline',
    passive: false,
    name: 'Raise Dead',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 120000,
      hasted: false,
    },
  },
  STRANGULATE: {
    id: 47476,
    type: 'baseline',
    passive: false,
    name: 'Strangulate',
    cooldown: {
      duration: 60000,
      hasted: false,
    },
  },
  MIND_FREEZE: {
    id: 47528,
    type: 'baseline',
    passive: false,
    name: 'Mind Freeze',
    cooldown: {
      duration: 15000,
      hasted: false,
    },
  },
  DEATH_COIL: {
    id: 47541,
    type: 'baseline',
    passive: false,
    name: 'Death Coil',
    gcd: {
      duration: 1000,
      hasted: true,
    },
  },
  EMPOWER_RUNE_WEAPON: {
    id: 47568,
    type: 'baseline',
    passive: false,
    name: 'Empower Rune Weapon',
    cooldown: {
      duration: 300000,
      hasted: false,
    },
  },
  BLOOD_PRESENCE: {
    id: 48263,
    type: 'baseline',
    passive: false,
    name: 'Blood Presence',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  UNHOLY_PRESENCE: {
    id: 48265,
    type: 'baseline',
    passive: false,
    name: 'Unholy Presence',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  FROST_PRESENCE: {
    id: 48266,
    type: 'baseline',
    passive: false,
    name: 'Frost Presence',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  ANTI_MAGIC_SHELL: {
    id: 48707,
    type: 'baseline',
    passive: false,
    name: 'Anti-Magic Shell',
    cooldown: {
      duration: 45000,
      hasted: false,
    },
  },
  BLOOD_BOIL: {
    id: 48721,
    type: 'baseline',
    passive: false,
    name: 'Blood Boil',
    gcd: {
      duration: 1000,
      hasted: true,
    },
  },
  DEATH_PACT_TALENT: {
    id: 48743,
    type: 'mists-talent',
    row: 3,
    column: 1,
    passive: false,
    name: 'Death Pact',
    cooldown: {
      duration: 120000,
      hasted: false,
    },
  },
  ICEBOUND_FORTITUDE: {
    id: 48792,
    type: 'baseline',
    passive: false,
    name: 'Icebound Fortitude',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
  },
  RUNE_TAP: {
    id: 48982,
    type: 'baseline',
    passive: false,
    name: 'Rune Tap',
    cooldown: {
      duration: 30000,
      hasted: false,
    },
  },
  DANCING_RUNE_WEAPON: {
    id: 49028,
    type: 'baseline',
    passive: false,
    name: 'Dancing Rune Weapon',
    cooldown: {
      duration: 90000,
      hasted: false,
    },
  },
  LICHBORNE_TALENT: {
    id: 49039,
    type: 'mists-talent',
    row: 1,
    column: 1,
    passive: false,
    hidden: 'unless-learned',
    name: 'Lichborne',
    cooldown: {
      duration: 120000,
      hasted: false,
    },
  },
  BONE_SHIELD: {
    id: 49222,
    type: 'baseline',
    passive: false,
    name: 'Bone Shield',
    cooldown: {
      duration: 60000,
      hasted: false,
    },
  },
  SCENT_OF_BLOOD_PASSIVE: {
    id: 49509,
    type: 'baseline',
    passive: true,
    name: 'Scent of Blood',
  },
  BLOOD_PARASITE_PASSIVE: {
    id: 49542,
    type: 'baseline',
    passive: true,
    name: 'Blood Parasite',
  },
  DEATH_GRIP: {
    id: 49576,
    type: 'baseline',
    passive: false,
    name: 'Death Grip',
    cooldown: {
      duration: 25000,
      hasted: false,
    },
  },
  DEATH_STRIKE: {
    id: 49998,
    type: 'baseline',
    passive: false,
    name: 'Death Strike',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  VETERAN_OF_THE_THIRD_WAR_PASSIVE: {
    id: 50029,
    type: 'baseline',
    passive: true,
    name: 'Veteran of the Third War',
  },
  BLOOD_RITES_PASSIVE: {
    id: 50034,
    type: 'baseline',
    passive: true,
    name: 'Blood Rites',
  },
  CHILBLAINS_TALENT: {
    id: 50041,
    type: 'mists-talent',
    row: 2,
    column: 2,
    passive: true,
    name: 'Chilblains',
  },
  IMPROVED_BLOOD_PRESENCE_PASSIVE: {
    id: 50371,
    type: 'baseline',
    passive: true,
    name: 'Improved Blood Presence',
  },
  PESTILENCE: {
    id: 50842,
    type: 'baseline',
    passive: false,
    name: 'Pestilence',
    gcd: {
      duration: 1000,
      hasted: true,
    },
  },
  DEATH_GATE: {
    id: 50977,
    type: 'baseline',
    passive: false,
    hidden: 'unless-learned',
    name: 'Death Gate',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    castTime: {
      duration: 10000,
    },
  },
  ANTI_MAGIC_ZONE_TALENT: {
    id: 51052,
    type: 'mists-talent',
    row: 1,
    column: 2,
    passive: false,
    hidden: 'unless-learned',
    name: 'Anti-Magic Zone',
    cooldown: {
      duration: 120000,
      hasted: false,
    },
  },
  RUNIC_CORRUPTION_TALENT: {
    id: 51462,
    type: 'mists-talent',
    row: 4,
    column: 3,
    passive: true,
    name: 'Runic Corruption',
  },
  ON_A_PALE_HORSE_PASSIVE: {
    id: 51986,
    type: 'baseline',
    passive: true,
    name: 'On a Pale Horse',
  },
  HEART_STRIKE: {
    id: 55050,
    type: 'baseline',
    overrides: 45902,
    passive: false,
    name: 'Heart Strike',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  BLOOD_PLAGUE_HIDDEN: {
    id: 55078,
    type: 'baseline',
    passive: false,
    hidden: 'always',
    name: 'Blood Plague',
  },
  FROST_FEVER_HIDDEN: {
    id: 55095,
    type: 'baseline',
    passive: false,
    hidden: 'always',
    name: 'Frost Fever',
  },
  VAMPIRIC_BLOOD: {
    id: 55233,
    type: 'baseline',
    passive: false,
    name: 'Vampiric Blood',
    cooldown: {
      duration: 60000,
      hasted: false,
    },
  },
  DARK_COMMAND: {
    id: 56222,
    type: 'baseline',
    passive: false,
    name: 'Dark Command',
    cooldown: {
      duration: 8000,
      hasted: false,
    },
  },
  RUNE_STRIKE: {
    id: 56815,
    type: 'baseline',
    passive: false,
    name: 'Rune Strike',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  HORN_OF_WINTER: {
    id: 57330,
    type: 'baseline',
    passive: false,
    name: 'Horn of Winter',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 20000,
      hasted: false,
    },
  },
  BLOOD_PLAGUE_PASSIVE: {
    id: 59879,
    type: 'baseline',
    passive: true,
    name: 'Blood Plague',
  },
  FROST_FEVER_PASSIVE: {
    id: 59921,
    type: 'baseline',
    passive: true,
    name: 'Frost Fever',
  },
  RAISE_ALLY: {
    id: 61999,
    type: 'baseline',
    passive: false,
    name: 'Raise Ally',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 600000,
      hasted: false,
    },
  },
  NECROTIC_STRIKE: {
    id: 73975,
    type: 'baseline',
    passive: false,
    name: 'Necrotic Strike',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  MASTERY_BLOOD_SHIELD_PASSIVE: {
    id: 77513,
    type: 'baseline',
    passive: true,
    name: 'Mastery: Blood Shield',
  },
  OUTBREAK: {
    id: 77575,
    type: 'baseline',
    passive: false,
    name: 'Outbreak',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
  },
  DARK_SIMULACRUM: {
    id: 77606,
    type: 'baseline',
    passive: false,
    name: 'Dark Simulacrum',
    cooldown: {
      duration: 60000,
      hasted: false,
    },
  },
  SANGUINE_FORTITUDE_PASSIVE: {
    id: 81127,
    type: 'baseline',
    passive: true,
    name: 'Sanguine Fortitude',
  },
  SCARLET_FEVER_PASSIVE: {
    id: 81132,
    type: 'baseline',
    passive: true,
    name: 'Scarlet Fever',
  },
  CRIMSON_SCOURGE_PASSIVE: {
    id: 81136,
    type: 'baseline',
    passive: true,
    name: 'Crimson Scourge',
  },
  WILL_OF_THE_NECROPOLIS_PASSIVE: {
    id: 81164,
    type: 'baseline',
    passive: true,
    name: 'Will of the Necropolis',
  },
  RUNIC_EMPOWERMENT_TALENT: {
    id: 81229,
    type: 'mists-talent',
    row: 4,
    column: 2,
    passive: true,
    hidden: 'unless-learned',
    name: 'Runic Empowerment',
  },
  PARRY_PASSIVE: {
    id: 82246,
    type: 'baseline',
    passive: true,
    name: 'Parry',
  },
  PLATE_SPECIALIZATION_PASSIVE: {
    id: 86524,
    type: 'baseline',
    passive: true,
    name: 'Plate Specialization',
  },
  PLATE_SPECIALIZATION_HIDDEN: {
    id: 86537,
    type: 'baseline',
    passive: true,
    hidden: 'always',
    name: 'Plate Specialization',
  },
  DEATH_STRIKE_ENABLER_HIDDEN: {
    id: 89832,
    type: 'baseline',
    passive: true,
    hidden: 'always',
    name: 'Death Strike Enabler',
  },
  VENGEANCE_PASSIVE: {
    id: 93099,
    type: 'baseline',
    passive: true,
    name: 'Vengeance',
  },
  DEATHS_ADVANCE_TALENT: {
    id: 96268,
    type: 'mists-talent',
    row: 2,
    column: 1,
    passive: false,
    name: "Death's Advance",
    cooldown: {
      duration: 30000,
      hasted: false,
    },
  },
  ROILING_BLOOD_TALENT: {
    id: 108170,
    type: 'mists-talent',
    row: 0,
    column: 1,
    passive: true,
    name: 'Roiling Blood',
  },
  ASPHYXIATE_TALENT: {
    id: 108194,
    overrides: 47476,
    type: 'mists-talent',
    row: 2,
    column: 3,
    passive: false,
    name: 'Asphyxiate',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
  },
  DEATH_SIPHON_TALENT: {
    id: 108196,
    type: 'mists-talent',
    row: 3,
    column: 2,
    passive: false,
    name: 'Death Siphon',
    gcd: {
      duration: 1000,
      hasted: true,
    },
  },
  GOREFIENDS_GRASP_TALENT: {
    id: 108199,
    type: 'mists-talent',
    row: 5,
    column: 1,
    passive: false,
    name: "Gorefiend's Grasp",
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
  },
  REMORSELESS_WINTER_TALENT: {
    id: 108200,
    type: 'mists-talent',
    row: 5,
    column: 2,
    passive: false,
    name: 'Remorseless Winter',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
  },
  DESECRATED_GROUND_TALENT: {
    id: 108201,
    type: 'mists-talent',
    row: 5,
    column: 3,
    passive: false,
    name: 'Desecrated Ground',
    cooldown: {
      duration: 120000,
      hasted: false,
    },
  },
  SYMBIOSIS: {
    id: 110498,
    type: 'baseline',
    passive: false,
    name: 'Symbiosis',
  },
  CONTROL_UNDEAD: {
    id: 111673,
    type: 'baseline',
    passive: false,
    name: 'Control Undead',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    castTime: {
      duration: 1500,
    },
  },
  PURGATORY_TALENT: {
    id: 114556,
    type: 'mists-talent',
    row: 1,
    column: 3,
    passive: true,
    name: 'Purgatory',
  },
  SOUL_REAPER: {
    id: 114866,
    type: 'baseline',
    passive: false,
    name: 'Soul Reaper',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 6000,
      hasted: false,
    },
  },
  UNHOLY_BLIGHT_TALENT: {
    id: 115989,
    type: 'mists-talent',
    row: 0,
    column: 3,
    passive: false,
    name: 'Unholy Blight',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 90000,
      hasted: false,
    },
  },
  CONVERSION_TALENT: {
    id: 119975,
    type: 'mists-talent',
    row: 3,
    column: 3,
    passive: false,
    name: 'Conversion',
    gcd: {
      duration: 1000,
      hasted: true,
    },
  },
  PLAGUE_LEECH_TALENT: {
    id: 123693,
    type: 'mists-talent',
    row: 0,
    column: 2,
    passive: false,
    name: 'Plague Leech',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 25000,
      hasted: false,
    },
  },
  DEATHS_ADVANCE_HIDDEN: {
    id: 124285,
    type: 'learned',
    taughtBy: 96268,
    passive: true,
    hidden: 'always',
    name: "Death's Advance",
  },
  HOTFIX_PASSIVE_HIDDEN_1: {
    id: 137005,
    type: 'baseline',
    passive: true,
    hidden: 'always',
    name: 'Hotfix Passive',
  },
  HOTFIX_PASSIVE_HIDDEN_2: {
    id: 137008,
    type: 'baseline',
    passive: true,
    hidden: 'always',
    name: 'Hotfix Passive',
  },
  RIPOSTE_PASSIVE: {
    id: 145676,
    type: 'baseline',
    passive: true,
    name: 'Riposte',
  },
  SCENT_OF_BLOOD_HIDDEN: {
    id: 148211,
    type: 'baseline',
    passive: true,
    hidden: 'always',
    name: 'Scent of Blood',
  },
} as const satisfies Record<string, RetailSpell>;
export default SPELLS;
