FROM node:8.2.1-alpine

# To get the latest version this requires having run `npm install`, `npm run build` and another `npm install` in the server directory prior to building the container

COPY server /usr/src/wowanalyzer/server/
COPY build /usr/src/wowanalyzer/build/
WORKDIR /usr/src/wowanalyzer/server/
EXPOSE 3000
USER node
CMD ["npm", "start"]
