FROM node:8.2.1-alpine

# App
WORKDIR /usr/src/wowanalyzer

# By doing this separate we allow Docker to cache this
COPY package.json package-lock.json /usr/src/wowanalyzer/
RUN npm install

COPY . /usr/src/wowanalyzer
RUN npm run build

# Server
WORKDIR ./server
RUN npm install
USER node

CMD ["npm", "start"]
