FROM node:9.2.0-alpine

# To get the latest version this requires having run `npm install`, `npm run build` and another `npm install` and `npm run build` in the server directory prior to building the container

COPY server /usr/src/wowanalyzer/server/
COPY build /usr/src/wowanalyzer/build/
WORKDIR /usr/src/wowanalyzer/server/
ENV NODE_ENV=production
EXPOSE 3000
USER node
CMD ["npm", "run", "serve"]
