FROM node:8.2.1-alpine

WORKDIR /usr/src/wowanalyzer/server/

# By doing this separate we allow Docker to cache this
COPY server/package.json server/package-lock.json /usr/src/wowanalyzer/server/
RUN npm install

COPY server /usr/src/wowanalyzer/server/
COPY build /usr/src/wowanalyzer/build/

EXPOSE 3000

CMD ["npm", "start"]
