FROM node:10.4-alpine

WORKDIR /usr/src/wowanalyzer/server/

# By doing this separate we allow Docker to cache this
COPY server/package.json server/package-lock.json /usr/src/wowanalyzer/server/
RUN npm install

COPY server /usr/src/wowanalyzer/server/
COPY build /usr/src/wowanalyzer/build/

EXPOSE 3000
# Webpack dev server has to poll because https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-start-doesnt-detect-changes
ENV CHOKIDAR_USEPOLLING=true
ENV NODE_ENV=development

CMD ["npm", "start"]
