FROM node:8.2.1-alpine

COPY . /usr/src/wowanalyzer/
WORKDIR /usr/src/wowanalyzer/

# Run in one line to prevent creating additional layers which allows us to keep the image small
RUN npm install --production \
  && npm run build \
  && cd server \
  && npm install --production \
  && npm cache clean --force \
  && cd .. \
  && rm -rf node_modules server/node_modules config public scripts src

# Start the server
WORKDIR ./server/
USER node
CMD ["npm", "start"]
