// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
  RequiredParams,
} from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales = 'de' | 'en' | 'es' | 'fr' | 'it' | 'ko' | 'pl' | 'pt' | 'ru' | 'zh';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  demonhunter: {
    havoc: {
      wastedFury: {
        statistic: {
          /**
           * {​a​m​o​u​n​t​}​%​ ​w​a​s​t​e​d
           * @param {string} amount
           */
          tooltip: RequiredParams<'amount'>;
          /**
           * F​u​r​y​ ​W​a​s​t​e​d
           */
          subtitle: string;
        };
        suggestion: {
          /**
           * Y​o​u​ ​w​a​s​t​e​d​ ​{​a​m​o​u​n​t​}​ ​F​u​r​y​.
           * @param {string} amount
           */
          base: RequiredParams<'amount'>;
          /**
           * {​a​m​o​u​n​t​}​%​ ​F​u​r​y​ ​w​a​s​t​e​d
           * @param {string} amount
           */
          actual: RequiredParams<'amount'>;
          /**
           * <​{​a​m​o​u​n​t​}​%​ ​i​s​ ​r​e​c​o​m​m​e​n​d​e​d
           * @param {string} amount
           */
          recommend: RequiredParams<'amount'>;
        };
      };
    };
  };
};

export type TranslationFunctions = {
  demonhunter: {
    havoc: {
      wastedFury: {
        statistic: {
          /**
           * {amount}% wasted
           */
          tooltip: (arg: { amount: string }) => LocalizedString;
          /**
           * Fury Wasted
           */
          subtitle: () => LocalizedString;
        };
        suggestion: {
          /**
           * You wasted {amount} Fury.
           */
          base: (arg: { amount: string }) => LocalizedString;
          /**
           * {amount}% Fury wasted
           */
          actual: (arg: { amount: string }) => LocalizedString;
          /**
           * <{amount}% is recommended
           */
          recommend: (arg: { amount: string }) => LocalizedString;
        };
      };
    };
  };
};

export type Formatters = {};
