// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters';
import type { Locales, Translations } from './i18n-types';
import { loadedFormatters, loadedLocales, locales } from './i18n-util';

import de from './de';
import en from './en';
import es from './es';
import fr from './fr';
import it from './it';
import ko from './ko';
import pl from './pl';
import pt from './pt';
import ru from './ru';
import zh from './zh';

const localeTranslations = {
  de,
  en,
  es,
  fr,
  it,
  ko,
  pl,
  pt,
  ru,
  zh,
};

export const loadLocale = (locale: Locales): void => {
  if (loadedLocales[locale]) return;

  loadedLocales[locale] = (localeTranslations[locale] as unknown) as Translations;
  loadFormatters(locale);
};

export const loadAllLocales = (): void => locales.forEach(loadLocale);

export const loadFormatters = (locale: Locales): void =>
  void (loadedFormatters[locale] = initFormatters(locale));
