// Generated file, changes will be overwritten!

export default {
  // Shared

  // Frost
  SHATTERING_STRIKES_TALENT: { id: 207057, name: "Shattering Strikes", icon: "ability_warrior_shatteringthrow" },
  ICY_TALONS_TALENT: { id: 194878, name: "Icy Talons", icon: "spell_deathknight_icytalons" },
  RUNIC_ATTENUATION_TALENT: { id: 207104, name: "Runic Attenuation", icon: "boss_odunrunes_blue" },
  FREEZING_FOG_TALENT: { id: 207060, name: "Freezing Fog", icon: "spell_frost_arcticwinds" },
  MURDEROUS_EFFICIENCY_TALENT: { id: 207061, name: "Murderous Efficiency", icon: "spell_frost_frostarmor" },
  HORN_OF_WINTER_TALENT: { id: 57330, name: "Horn of Winter", icon: "inv_misc_horn_02" },
  ICECAP_TALENT: { id: 207126, name: "Icecap", icon: "inv_misc_herb_icecap" },
  GLACIAL_ADVANCE_TALENT: { id: 194913, name: "Glacial Advance", icon: "ability_hunter_glacialtrap" },
  AVALANCHE_TALENT: { id: 207142, name: "Avalanche", icon: "spell_frost_icestorm" },
  ABOMINATIONS_MIGHT_TALENT: { id: 207161, name: "Abomination's Might", icon: "spell_deathknight_icetouch" },
  BLINDING_SLEET_TALENT: { id: 207167, name: "Blinding Sleet", icon: "spell_frost_chillingblast" },
  WINTER_IS_COMING_TALENT: { id: 207170, name: "Winter is Coming", icon: "inv_wolfdraenormountfrost" },
  VOLATILE_SHIELDING_TALENT: { id: 207188, name: "Volatile Shielding", icon: "ability_mage_shattershield" },
  PERMAFROST_TALENT: { id: 207200, name: "Permafrost", icon: "achievement_zone_frostfire" },
  INEXORABLE_ASSAULT_TALENT: { id: 253593, name: "Inexorable Assault", icon: "achievement_dungeon_icecrown_frostmourne" },
  FROSTSCYTHE_TALENT: { id: 207230, name: "Frostscythe", icon: "inv_misc_2h_farmscythe_a_01" },
  FROZEN_PULSE_TALENT: { id: 194909, name: "Frozen Pulse", icon: "inv_misc_permafrostshard" },
  GATHERING_STORM_TALENT: { id: 194912, name: "Gathering Storm", icon: "spell_frost_iceshards" },
  OBLITERATION_TALENT: { id: 207256, name: "Obliteration", icon: "inv_axe_114" },
  BREATH_OF_SINDRAGOSA_TALENT: { id: 152279, name: "Breath of Sindragosa", icon: "spell_deathknight_breathofsindragosa" },
  HUNGERING_RUNE_WEAPON_TALENT: { id: 207127, name: "Hungering Rune Weapon", icon: "ability_deathknight_hungeringruneblade" },
  // Blood
  HEARTBREAKER_TALENT: { id: 221536, name: "Heartbreaker", icon: "spell_deathknight_deathstrike" },
  BLOODDRINKER_TALENT: { id: 206931, name: "Blooddrinker", icon: "ability_animusdraw" },
  RUNE_STRIKE_TALENT: { id: 210764, name: "Rune Strike", icon: "spell_deathknight_darkconviction" },
  RAPID_DECOMPOSITION_TALENT: { id: 194662, name: "Rapid Decomposition", icon: "ability_deathknight_deathsiphon2" },
  HEMOSTASIS_TALENT: { id: 273946, name: "Hemostasis", icon: "ability_deathwing_bloodcorruption_earth" },
  CONSUMPTION_TALENT: { id: 274156, name: 'Consumption', icon: 'inv_axe_2h_artifactmaw_d_01' },
  WILL_OF_THE_NECROPOLIS_TALENT: { id: 206967, name: "Will of the Necropolis", icon: "achievement_boss_kelthuzad_01" },
  ANTIMAGIC_BARRIER_TALENT: { id: 205727, name: "Anti-Magic Barrier", icon: "spell_shadow_antimagicshell" },
  RUNE_TAP_TALENT: { id: 194679, name: "Rune Tap", icon: "spell_deathknight_runetap" },
  TIGHTENING_GRASP_TALENT: { id: 206970, name: "Tightening Grasp", icon: "spell_shadow_chilltouch" },
  GRIP_OF_THE_DEAD_TALENT: { id: 273952, name: "Grip of the Dead", icon: "warlock_curse_shadow" },
  MARCH_OF_THE_DAMNED_TALENT: { id: 219779, name: "March of the Damned", icon: "spell_shadow_demonicempathy" },
  FOUL_BULWARK_TALENT: { id: 206974, name: "Foul Bulwark", icon: "inv_armor_shield_naxxramas_d_02" },
  OSSUARY_TALENT: { id: 219786, name: "Ossuary", icon: "ability_deathknight_brittlebones" },
  TOMBSTONE_TALENT: { id: 219809, name: "Tombstone", icon: "ability_fiegndead" },
  VORACIOUS_TALENT: { id: 273953, name: "Voracious", icon: "ability_ironmaidens_whirlofblood" },
  BLOODWORMS_TALENT: { id: 195679, name: "Bloodworms", icon: "spell_shadow_soulleech" },
  MARK_OF_BLOOD_TALENT: { id: 206940, name: "Mark of Blood", icon: "ability_hunter_rapidkilling" },
  PURGATORY_TALENT: { id: 114556, name: "Purgatory", icon: "inv_misc_shadowegg" },
  RED_THIRST_TALENT: { id: 205723, name: "Red Thirst", icon: "spell_deathknight_bloodpresence" },
  BONESTORM_TALENT: { id: 194844, name: "Bonestorm", icon: "achievement_boss_lordmarrowgar", runicPowerCost: 20 },

  HEART_OF_ICE_TALENT: { id: 246426, name: "Heart of Ice", icon: "spell_frost_coldhearted" },
  SPECTRAL_DEFLECTION_TALENT: { id: 211078, name: "Spectral Deflection", icon: "spell_deathknight_spelldeflection" },
  BLOOD_TAP_TALENT: { id: 221699, name: "Blood Tap", icon: "spell_deathknight_bloodtap" },
  TREMBLE_BEFORE_ME_TALENT: { id: 206960, name: "Tremble Before Me", icon: "spell_shadow_auraofdarkness" },
  BLOOD_MIRROR_TALENT: { id: 206977, name: "Blood Mirror", icon: "inv_misc_gem_bloodstone_01" },
  // Unholy
  ALL_WILL_SERVE_TALENT: { id: 194916, name: "All Will Serve", icon: "ability_fiegndead" },
  BURSTING_SORES_TALENT: { id: 207264, name: "Bursting Sores", icon: "ability_druid_infectedwound" },
  EBON_FEVER_TALENT: { id: 207269, name: "Ebon Fever", icon: "spell_shadow_creepingplague" },
  EPIDEMIC_TALENT: { id: 207317, name: "Epidemic", icon: "spell_deathknight_unholypresence" },
  PESTILENT_PUSTULES_TALENT: { id: 194917, name: "Pestilent Pustules", icon: "spell_yorsahj_bloodboil_purpleoil" },
  BLIGHTED_RUNE_WEAPON_TALENT: { id: 194918, name: "Blighted Rune Weapon", icon: "spell_deathknight_plaguestrike" },
  UNHOLY_FRENZY_TALENT: { id: 207289, name: "Unholy Frenzy", icon: "spell_shadow_unholyfrenzy" },
  CASTIGATOR_TALENT: { id: 207305, name: "Castigator", icon: "spell_shadow_fumble" },
  CLAWING_SHADOWS_TALENT: { id: 207311, name: "Clawing Shadows", icon: "warlock_curse_shadow" },
  SLUDGE_BELCHER_TALENT: { id: 207313, name: "Sludge Belcher", icon: "achievement_boss_patchwerk" },
  ASPHYXIATE_TALENT: { id: 108194, name: "Asphyxiate", icon: "ability_deathknight_asphixiate" },
  DEBILITATING_INFESTATION_TALENT: { id: 207316, name: "Debilitating Infestation", icon: "spell_deathknight_necroticplague" },
  SPELL_EATER_TALENT: { id: 207321, name: "Spell Eater", icon: "ability_creature_cursed_03" },
  CORPSE_SHIELD_TALENT: { id: 207319, name: "Corpse Shield", icon: "inv_pet_ghoul" },
  LINGERING_APPARITION_TALENT: { id: 212763, name: "Lingering Apparition", icon: "spell_holy_senseundead" },
  SHADOW_INFUSION_TALENT: { id: 198943, name: "Shadow Infusion", icon: "spell_shadow_requiem" },
  NECROSIS_TALENT: { id: 207346, name: "Necrosis", icon: "inv_weapon_shortblade_60" },
  INFECTED_CLAWS_TALENT: { id: 207272, name: "Infected Claws", icon: "spell_deathknight_thrash_ghoul" },
  DARK_ARBITER_TALENT: { id: 207349, name: "Dark Arbiter", icon: "achievement_boss_svalasorrowgrave" },
  DEFILE_TALENT: { id: 152280, name: "Defile", icon: "spell_deathknight_defile" },
  SOUL_REAPER_TALENT: { id: 130736, name: "Soul Reaper", icon: "ability_deathknight_soulreaper" },
};
