// Generated file, changes will be overwritten!

export default {
  // Shared
  DEATHS_REACH_TALENT: { id: 276079, name: "Death's Reach", icon: "spell_deathknight_strangulate" },
  ASPHYXIATE_TALENT: { id: 108194, name: "Asphyxiate", icon: "ability_deathknight_asphixiate" },
  GRIP_OF_THE_DEAD_TALENT: { id: 273952, name: "Grip of the Dead", icon: "ability_creature_disease_05" },
  WRAITH_WALK_TALENT: { id: 212552, name: "Wraith Walk", icon: "inv_helm_plate_raiddeathknight_p_01" },
  DEATH_PACT_TALENT: { id: 48743, name: "Death Pact", icon: "spell_shadow_deathpact" },
  // Blood
  HEARTBREAKER_TALENT: { id: 221536, name: "Heartbreaker", icon: "spell_deathknight_deathstrike" },
  BLOODDRINKER_TALENT: { id: 206931, name: "Blooddrinker", icon: "ability_animusdraw" },
  RUNE_STRIKE_TALENT: { id: 210764, name: "Rune Strike", icon: "spell_deathknight_darkconviction" },
  RAPID_DECOMPOSITION_TALENT: { id: 194662, name: "Rapid Decomposition", icon: "ability_deathknight_deathsiphon2" },
  HEMOSTASIS_TALENT: { id: 273946, name: "Hemostasis", icon: "ability_deathwing_bloodcorruption_earth" },
  CONSUMPTION_TALENT: { id: 274156, name: "Consumption", icon: "inv_axe_2h_artifactmaw_d_01" },
  FOUL_BULWARK_TALENT: { id: 206974, name: "Foul Bulwark", icon: "inv_armor_shield_naxxramas_d_02" },
  OSSUARY_TALENT: { id: 219786, name: "Ossuary", icon: "ability_deathknight_brittlebones" },
  TOMBSTONE_TALENT: { id: 219809, name: "Tombstone", icon: "ability_fiegndead" },
  WILL_OF_THE_NECROPOLIS_TALENT: { id: 206967, name: "Will of the Necropolis", icon: "achievement_boss_kelthuzad_01" },
  ANTIMAGIC_BARRIER_TALENT: { id: 205727, name: "Anti-Magic Barrier", icon: "spell_shadow_antimagicshell" },
  RUNE_TAP_TALENT: { id: 194679, name: "Rune Tap", icon: "spell_deathknight_runetap", runicPowerCost: 60 },
  TIGHTENING_GRASP_TALENT: { id: 206970, name: "Tightening Grasp", icon: "ability_deathknight_aoedeathgrip" },
  VORACIOUS_TALENT: { id: 273953, name: "Voracious", icon: "ability_ironmaidens_whirlofblood" },
  BLOODWORMS_TALENT: { id: 195679, name: "Bloodworms", icon: "spell_shadow_soulleech" },
  MARK_OF_BLOOD_TALENT: { id: 206940, name: "Mark of Blood", icon: "ability_hunter_rapidkilling" },
  PURGATORY_TALENT: { id: 114556, name: "Purgatory", icon: "inv_misc_shadowegg" },
  RED_THIRST_TALENT: { id: 205723, name: "Red Thirst", icon: "spell_deathknight_bloodpresence" },
  BONESTORM_TALENT: { id: 194844, name: "Bonestorm", icon: "achievement_boss_lordmarrowgar", runicPowerCost: 20 },
  // Unholy
  INFECTED_CLAWS_TALENT: { id: 207272, name: "Infected Claws", icon: "spell_deathknight_thrash_ghoul" },
  ALL_WILL_SERVE_TALENT: { id: 194916, name: "All Will Serve", icon: "ability_fiegndead" },
  CLAWING_SHADOWS_TALENT: { id: 207311, name: "Clawing Shadows", icon: "warlock_curse_shadow" },
  BURSTING_SORES_TALENT: { id: 207264, name: "Bursting Sores", icon: "ability_druid_infectedwound" },
  EBON_FEVER_TALENT: { id: 207269, name: "Ebon Fever", icon: "spell_shadow_creepingplague" },
  UNHOLY_BLIGHT_TALENT: { id: 115989, name: "Unholy Blight", icon: "spell_shadow_contagion" },
  PESTILENT_PUSTULES_TALENT: { id: 194917, name: "Pestilent Pustules", icon: "spell_yorsahj_bloodboil_purpleoil" },
  HARBINGER_OF_DOOM_TALENT: { id: 276023, name: "Harbinger of Doom", icon: "spell_shadow_painspike" },
  SOUL_REAPER_TALENT: { id: 130736, name: "Soul Reaper", icon: "ability_deathknight_soulreaper" },
  SPELL_EATER_TALENT: { id: 207321, name: "Spell Eater", icon: "ability_creature_cursed_03" },
  PESTILENCE_TALENT: { id: 277234, name: "Pestilence", icon: "spell_deathknight_necroticplague" },
  DEFILE_TALENT: { id: 152280, name: "Defile", icon: "spell_deathknight_defile", runicPowerCost: 10 },
  EPIDEMIC_TALENT: { id: 207317, name: "Epidemic", icon: "spell_nature_nullifydisease" },
  ARMY_OF_THE_DAMNED_TALENT: { id: 276837, name: "Army of the Damned", icon: "artifactability_unholydeathknight_deathsembrace" },
  UNHOLY_FRENZY_TALENT: { id: 207289, name: "Unholy Frenzy", icon: "spell_shadow_unholyfrenzy" },
  SUMMON_GARGOYLE_TALENT: { id: 49206, name: "Summon Gargoyle", icon: "ability_deathknight_summongargoyle" },
  // Frost
  INEXORABLE_ASSAULT_TALENT: { id: 253593, name: "Inexorable Assault", icon: "achievement_dungeon_icecrown_frostmourne" },
  ICY_TALONS_TALENT: { id: 194878, name: "Icy Talons", icon: "spell_deathknight_icytalons" },
  COLD_HEART_TALENT: { id: 281208, name: "Cold Heart", icon: "spell_frost_frozencore" },
  RUNIC_ATTENUATION_TALENT: { id: 207104, name: "Runic Attenuation", icon: "boss_odunrunes_blue" },
  MURDEROUS_EFFICIENCY_TALENT: { id: 207061, name: "Murderous Efficiency", icon: "spell_frost_frostarmor" },
  HORN_OF_WINTER_TALENT: { id: 57330, name: "Horn of Winter", icon: "inv_misc_horn_02" },
  BLINDING_SLEET_TALENT: { id: 207167, name: "Blinding Sleet", icon: "spell_frost_chillingblast" },
  AVALANCHE_TALENT: { id: 207142, name: "Avalanche", icon: "spell_frost_icestorm" },
  FROZEN_PULSE_TALENT: { id: 194909, name: "Frozen Pulse", icon: "inv_misc_permafrostshard" },
  FROSTSCYTHE_TALENT: { id: 207230, name: "Frostscythe", icon: "inv_misc_2h_farmscythe_a_01" },
  PERMAFROST_TALENT: { id: 207200, name: "Permafrost", icon: "achievement_zone_frostfire" },
  GATHERING_STORM_TALENT: { id: 194912, name: "Gathering Storm", icon: "spell_frost_iceshards" },
  GLACIAL_ADVANCE_TALENT: { id: 194913, name: "Glacial Advance", icon: "ability_hunter_glacialtrap" },
  FROSTWYRMS_FURY_TALENT: { id: 279302, name: "Frostwyrm's Fury", icon: "achievement_boss_sindragosa" },
  ICECAP_TALENT: { id: 207126, name: "Icecap", icon: "inv_misc_herb_icecap" },
  OBLITERATION_TALENT: { id: 281238, name: "Obliteration", icon: "inv_axe_114" },
  BREATH_OF_SINDRAGOSA_TALENT: { id: 152279, name: "Breath of Sindragosa", icon: "spell_deathknight_breathofsindragosa" },
};
