// Generated file, changes will be overwritten!

export default {
  // Shared
  RENEWAL_TALENT: { id: 108238, name: "Renewal", icon: "spell_nature_natureblessing" },
  DISPLACER_BEAST_TALENT: { id: 102280, name: "Displacer Beast", icon: "spell_druid_displacement" },
  WILD_CHARGE_TALENT: { id: 102401, name: "Wild Charge", icon: "spell_druid_wildcharge" },
  RESTORATION_AFFINITY_TALENT: { id: 197492, name: "Restoration Affinity", icon: "ability_druid_improvedtreeform" },
  MIGHTY_BASH_TALENT: { id: 5211, name: "Mighty Bash", icon: "ability_druid_bash" },
  MASS_ENTANGLEMENT_TALENT: { id: 102359, name: "Mass Entanglement", icon: "spell_druid_massentanglement" },
  TYPHOON_TALENT: { id: 132469, name: "Typhoon", icon: "ability_druid_typhoon" },
  INCARNATION_CHOSEN_OF_ELUNE_TALENT: { id: 102560, name: "Incarnation: Chosen of Elune", icon: "spell_druid_incarnation" },
  BALANCE_AFFINITY_TALENT_SHARED: { id: 197488, name: "Balance Affinity", icon: "ability_druid_improvedmoonkinform" },
  GUARDIAN_AFFINITY_TALENT_SHARED: { id: 197491, name: "Guardian Affinity", icon: "talentspec_druid_feral_bear" },
  // Restoration
  PROSPERITY_TALENT: { id: 200383, name: "Prosperity", icon: "spell_druid_rampantgrowth" },
  CENARION_WARD_TALENT: { id: 102351, name: "Cenarion Ward", icon: "ability_druid_naturalperfection", manaCost: 20218 },
  ABUNDANCE_TALENT: { id: 207383, name: "Abundance", icon: "ability_druid_empoweredrejuvination" },
  INCARNATION_TREE_OF_LIFE_TALENT: { id: 33891, name: "Incarnation: Tree of Life", icon: "ability_druid_improvedtreeform" },
  CULTIVATION_TALENT: { id: 200390, name: "Cultivation", icon: "ability_druid_nourish" },
  SPRING_BLOSSOMS_TALENT: { id: 207385, name: "Spring Blossoms", icon: "inv_misc_trailofflowers" },
  INNER_PEACE_TALENT: { id: 197073, name: "Inner Peace", icon: "ability_druid_dreamstate" },
  GERMINATION_TALENT: { id: 155675, name: "Germination", icon: "spell_druid_germination" },
  STONEBARK_TALENT: { id: 197061, name: "Stonebark", icon: "ability_druid_replenish" },
  FLOURISH_TALENT: { id: 197721, name: "Flourish", icon: "spell_druid_wildburst" },
  BALANCE_AFFINITY_TALENT_RESTORATION: { id: 197632, name: "Balance Affinity", icon: "ability_druid_improvedmoonkinform" },
  FERAL_AFFINITY_TALENT_RESTORATION: { id: 197490, name: "Feral Affinity", icon: "talentspec_druid_feral_cat" },
  SOUL_OF_THE_FOREST_TALENT_RESTORATION: { id: 158478, name: "Soul of the Forest", icon: "ability_druid_manatree" },
  MOMENT_OF_CLARITY_TALENT_RESTORATION: { id: 155577, name: "Moment of Clarity", icon: "spell_druid_momentofclarity" },
  // Feral
  PREDATOR_TALENT: { id: 202021, name: "Predator", icon: "ability_hunter_catlikereflexes" },
  BLOOD_SCENT_TALENT: { id: 202022, name: "Blood Scent", icon: "ability_mount_pinktiger" },
  LUNAR_INSPIRATION_TALENT: { id: 155580, name: "Lunar Inspiration", icon: "spell_druid_lunarinspiration" },
  INCARNATION_KING_OF_THE_JUNGLE_TALENT: { id: 102543, name: "Incarnation: King of the Jungle", icon: "spell_druid_incarnation" },
  JAGGED_WOUNDS_TALENT: { id: 202032, name: "Jagged Wounds", icon: "ability_druid_disembowel" },
  SABERTOOTH_TALENT: { id: 202031, name: "Sabertooth", icon: "inv_misc_monsterfang_01" },
  BRUTAL_SLASH_TALENT: { id: 202028, name: "Brutal Slash", icon: "ability_druid_ravage", energyCost: 20 },
  SAVAGE_ROAR_TALENT: { id: 52610, name: "Savage Roar", icon: "ability_druid_skinteeth", energyCost: 40 },
  BLOODTALONS_TALENT: { id: 155672, name: "Bloodtalons", icon: "spell_druid_bloodythrash" },
  ELUNES_GUIDANCE_TALENT: { id: 202060, name: "Elune's Guidance", icon: "spell_holy_elunesgrace" },
  GUARDIAN_AFFINITY_TALENT_FERAL: { id: 217615, name: "Guardian Affinity", icon: "talentspec_druid_feral_bear" },
  SOUL_OF_THE_FOREST_TALENT_FERAL: { id: 158476, name: "Soul of the Forest", icon: "ability_druid_manatree" },
  MOMENT_OF_CLARITY_TALENT_FERAL: { id: 236068, name: "Moment of Clarity", icon: "spell_druid_momentofclarity" },
  // Balance
  FORCE_OF_NATURE_TALENT: { id: 205636, name: "Force of Nature", icon: "ability_druid_forceofnature" },
  WARRIOR_OF_ELUNE_TALENT: { id: 202425, name: "Warrior of Elune", icon: "spell_holy_elunesgrace" },
  STARLORD_TALENT: { id: 202345, name: "Starlord", icon: "spell_shaman_measuredinsight" },
  STELLAR_FLARE_TALENT: { id: 202347, name: "Stellar Flare", icon: "ability_druid_stellarflare" },
  SHOOTING_STARS_TALENT: { id: 202342, name: "Shooting Stars", icon: "spell_priest_divinestar_shadow2" },
  ASTRAL_COMMUNION_TALENT: { id: 202359, name: "Astral Communion", icon: "talentspec_druid_balance" },
  BLESSING_OF_THE_ANCIENTS_TALENT: { id: 202360, name: "Blessing of the Ancients", icon: "inv_pet_ancientprotector" },
  FURY_OF_ELUNE_TALENT: { id: 202770, name: "Fury of Elune", icon: "ability_druid_dreamstate" },
  STELLAR_DRIFT_TALENT: { id: 202354, name: "Stellar Drift", icon: "spell_nature_starfall" },
  NATURES_BALANCE_TALENT: { id: 202430, name: "Nature's Balance", icon: "ability_druid_balanceofpower" },
  FERAL_AFFINITY_TALENT_BALANCE: { id: 202157, name: "Feral Affinity", icon: "talentspec_druid_feral_cat" },
  SOUL_OF_THE_FOREST_TALENT_BALANCE: { id: 114107, name: "Soul of the Forest", icon: "ability_druid_manatree" },
  // Guardian
  BRAMBLES_TALENT: { id: 203953, name: "Brambles", icon: "inv_misc_thornnecklace" },
  BRISTLING_FUR_TALENT: { id: 155835, name: "Bristling Fur", icon: "spell_druid_bristlingfur" },
  BLOOD_FRENZY_TALENT: { id: 203962, name: "Blood Frenzy", icon: "ability_druid_primaltenacity" },
  GUTTURAL_ROARS_TALENT: { id: 204012, name: "Guttural Roars", icon: "ability_druid_enrage" },
  INTIMIDATING_ROAR_TALENT: { id: 236748, name: "Intimidating Roar", icon: "ability_druid_challangingroar" },
  INCARNATION_GUARDIAN_OF_URSOC_TALENT: { id: 102558, name: "Incarnation: Guardian of Ursoc", icon: "spell_druid_incarnation" },
  GALACTIC_GUARDIAN_TALENT: { id: 203964, name: "Galactic Guardian", icon: "spell_frost_iceclaw" },
  EARTHWARDEN_TALENT: { id: 203974, name: "Earthwarden", icon: "spell_shaman_blessingofeternals" },
  GUARDIAN_OF_ELUNE_TALENT: { id: 155578, name: "Guardian of Elune", icon: "spell_druid_guardianofelune" },
  SURVIVAL_OF_THE_FITTEST_TALENT: { id: 203965, name: "Survival of the Fittest", icon: "ability_druid_enrage" },
  REND_AND_TEAR_TALENT: { id: 204053, name: "Rend and Tear", icon: "ability_druid_swipe" },
  LUNAR_BEAM_TALENT: { id: 204066, name: "Lunar Beam", icon: "spell_nature_moonglow" },
  PULVERIZE_TALENT: { id: 80313, name: "Pulverize", icon: "spell_druid_malfurionstenacity" },
  FERAL_AFFINITY_TALENT_GUARDIAN: { id: 202155, name: "Feral Affinity", icon: "talentspec_druid_feral_cat" },
  SOUL_OF_THE_FOREST_TALENT_GUARDIAN: { id: 158477, name: "Soul of the Forest", icon: "ability_druid_manatree" },
};
