// Generated file, changes will be overwritten!

export default {
  // Shared
  REPENTANCE_TALENT: { id: 20066, name: "Repentance", icon: "spell_holy_prayerofhealing", manaCost: 2000 },
  BLINDING_LIGHT_TALENT: { id: 115750, name: "Blinding Light", icon: "ability_paladin_blindinglight", manaCost: 1600 },
  CAVALIER_TALENT: { id: 230332, name: "Cavalier", icon: "ability_paladin_divinesteed" },
  UNBREAKABLE_SPIRIT_TALENT: { id: 114154, name: "Unbreakable Spirit", icon: "spell_holy_holyguidance" },
  JUDGMENT_OF_LIGHT_TALENT: { id: 183778, name: "Judgment of Light", icon: "spell_holy_divineprovidence" },
  FIST_OF_JUSTICE_TALENT_SHARED: { id: 198054, name: "Fist of Justice", icon: "spell_holy_fistofjustice" },
  // Retribution
  ZEAL_TALENT: { id: 269569, name: "Zeal", icon: "spell_holy_sealofblood" },
  RIGHTEOUS_VERDICT_TALENT: { id: 267610, name: "Righteous Verdict", icon: "spell_paladin_templarsverdict" },
  EXECUTION_SENTENCE_TALENT: { id: 267798, name: "Execution Sentence", icon: "spell_paladin_executionsentence", maelstromCost: 3 },
  FIRES_OF_JUSTICE_TALENT: { id: 203316, name: "Fires of Justice", icon: "spell_holy_crusaderstrike" },
  BLADE_OF_WRATH_TALENT: { id: 231832, name: "Blade of Wrath", icon: "ability_paladin_bladeofjustice" },
  HAMMER_OF_WRATH_TALENT: { id: 24275, name: "Hammer of Wrath", icon: "spell_paladin_hammerofwrath" },
  DIVINE_JUDGMENT_TALENT: { id: 271580, name: "Divine Judgment", icon: "ability_paladin_righteousvengeance" },
  CONSECRATION_TALENT: { id: 205228, name: "Consecration", icon: "spell_holy_innerfire" },
  WAKE_OF_ASHES_TALENT: { id: 255937, name: "Wake of Ashes", icon: "inv_sword_2h_artifactashbringerfire_d_03" },
  EYE_FOR_AN_EYE_TALENT: { id: 205191, name: "Eye for an Eye", icon: "spell_holy_weaponmastery" },
  SELFLESS_HEALER_TALENT: { id: 85804, name: "Selfless Healer", icon: "ability_paladin_gaurdedbythelight" },
  JUSTICARS_VENGEANCE_TALENT: { id: 215661, name: "Justicar's Vengeance", icon: "spell_holy_retributionaura", maelstromCost: 5 },
  WORD_OF_GLORY_TALENT: { id: 210191, name: "Word of Glory", icon: "inv_helmet_96", maelstromCost: 3 },
  CRUSADE_TALENT: { id: 231895, name: "Crusade", icon: "ability_paladin_sanctifiedwrath" },
  INQUISITION_TALENT: { id: 84963, name: "Inquisition", icon: "spell_paladin_inquisition", maelstromCost: 1 },
  FIST_OF_JUSTICE_TALENT_RETRIBUTION: { id: 234299, name: "Fist of Justice", icon: "spell_holy_fistofjustice" },
  DIVINE_PURPOSE_TALENT_RETRIBUTION: { id: 223817, name: "Divine Purpose", icon: "spell_holy_divinepurpose" },
  // Protection
  HOLY_SHIELD_TALENT: { id: 152261, name: "Holy Shield", icon: "inv_shield_1h_hyrja_d_01" },
  REDOUBT_TALENT: { id: 280373, name: "Redoubt", icon: "ability_warrior_shieldguard" },
  BLESSED_HAMMER_TALENT: { id: 204019, name: "Blessed Hammer", icon: "paladin_retribution" },
  FIRST_AVENGER_TALENT: { id: 203776, name: "First Avenger", icon: "ability_skyreach_shielded" },
  CRUSADERS_JUDGMENT_TALENT: { id: 204023, name: "Crusader's Judgment", icon: "ability_paladin_enlightenedjudgements" },
  BASTION_OF_LIGHT_TALENT: { id: 204035, name: "Bastion of Light", icon: "paladin_protection" },
  RETRIBUTION_AURA_TALENT: { id: 203797, name: "Retribution Aura", icon: "spell_holy_auraoflight" },
  BLESSING_OF_SPELLWARDING_TALENT: { id: 204018, name: "Blessing of Spellwarding", icon: "spell_holy_blessingofprotection", manaCost: 3000 },
  FINAL_STAND_TALENT: { id: 204077, name: "Final Stand", icon: "spell_holy_crusade" },
  HAND_OF_THE_PROTECTOR_TALENT: { id: 213652, name: "Hand of the Protector", icon: "ability_paladin_blessedhands" },
  CONSECRATED_GROUND_TALENT: { id: 204054, name: "Consecrated Ground", icon: "ability_paladin_righteousvengeance" },
  AEGIS_OF_LIGHT_TALENT: { id: 204150, name: "Aegis of Light", icon: "spell_holy_greaterblessingoflight" },
  LAST_DEFENDER_TALENT: { id: 203791, name: "Last Defender", icon: "spell_holy_divinepurpose" },
  RIGHTEOUS_PROTECTOR_TALENT: { id: 204074, name: "Righteous Protector", icon: "ability_paladin_shieldofthetemplar" },
  SERAPHIM_TALENT: { id: 152262, name: "Seraphim", icon: "ability_paladin_seraphim" },
  // Holy
  CRUSADERS_MIGHT_TALENT: { id: 196926, name: "Crusader's Might", icon: "ability_paladin_swiftretribution" },
  BESTOW_FAITH_TALENT: { id: 223306, name: "Bestow Faith", icon: "ability_paladin_blessedmending", manaCost: 1200 },
  LIGHTS_HAMMER_TALENT: { id: 114158, name: "Light's Hammer", icon: "spell_paladin_lightshammer", manaCost: 5600 },
  RULE_OF_LAW_TALENT: { id: 214202, name: "Rule of Law", icon: "ability_paladin_longarmofthelaw" },
  DEVOTION_AURA_TALENT: { id: 183425, name: "Devotion Aura", icon: "spell_holy_devotionaura" },
  AURA_OF_SACRIFICE_TALENT: { id: 183416, name: "Aura of Sacrifice", icon: "ability_deathwing_bloodcorruption_earth" },
  AURA_OF_MERCY_TALENT: { id: 183415, name: "Aura of Mercy", icon: "spell_holy_blessedlife" },
  HOLY_PRISM_TALENT: { id: 114165, name: "Holy Prism", icon: "spell_paladin_holyprism", manaCost: 3400 },
  HOLY_AVENGER_TALENT: { id: 105809, name: "Holy Avenger", icon: "ability_paladin_holyavenger" },
  SANCTIFIED_WRATH_TALENT: { id: 53376, name: "Sanctified Wrath", icon: "ability_paladin_sanctifiedwrath" },
  AVENGING_CRUSADER_TALENT: { id: 216331, name: "Avenging Crusader", icon: "ability_paladin_veneration", manaCost: 10000 },
  AWAKENING_TALENT: { id: 248033, name: "Awakening", icon: "inv_helm_plate_raidpaladin_n_01" },
  BEACON_OF_FAITH_TALENT: { id: 156910, name: "Beacon of Faith", icon: "ability_paladin_beaconsoflight", manaCost: 624 },
  BEACON_OF_VIRTUE_TALENT: { id: 200025, name: "Beacon of Virtue", icon: "ability_paladin_beaconofinsight", manaCost: 2000 },
  DIVINE_PURPOSE_TALENT_HOLY: { id: 197646, name: "Divine Purpose", icon: "spell_holy_divinepurpose" },
};
