// Generated file, changes will be overwritten!

export default {
  // Shared
  GUST_OF_WIND_TALENT: { id: 192063, name: "Gust of Wind", icon: "ability_skyreach_four_wind" },
  WIND_RUSH_TOTEM_TALENT: { id: 192077, name: "Wind Rush Totem", icon: "ability_shaman_windwalktotem" },
  LIGHTNING_SURGE_TOTEM_TALENT: { id: 192058, name: "Lightning Surge Totem", icon: "spell_nature_brilliance", manaCost: 22000 },
  EARTHGRAB_TOTEM_TALENT: { id: 51485, name: "Earthgrab Totem", icon: "spell_nature_stranglevines", manaCost: 22000 },
  VOODOO_TOTEM_TALENT: { id: 196932, name: "Voodoo Totem", icon: "spell_totem_wardofdraining", manaCost: 22000 },
  ANCESTRAL_GUIDANCE_TALENT: { id: 108281, name: "Ancestral Guidance", icon: "ability_shaman_ancestralguidance" },
  ANCESTRAL_SWIFTNESS_TALENT: { id: 192087, name: "Ancestral Swiftness", icon: "spell_shaman_elementaloath" },
  ELEMENTAL_MASTERY_TALENT: { id: 16166, name: "Elemental Mastery", icon: "spell_nature_wispheal" },
  ECHO_OF_THE_ELEMENTS_TALENT: { id: 108283, name: "Echo of the Elements", icon: "ability_shaman_echooftheelements" },
  // Enhancement
  WINDSONG_TALENT: { id: 201898, name: "Windsong", icon: "ability_skyreach_wind_wall" },
  HOT_HAND_TALENT: { id: 201900, name: "Hot Hand", icon: "spell_fire_playingwithfire" },
  LANDSLIDE_TALENT: { id: 197992, name: "Landslide", icon: "inv_ore_blackrock_nugget" },
  RAINFALL_TALENT: { id: 215864, name: "Rainfall", icon: "spell_nature_giftofthewaterspirit" },
  FERAL_LUNGE_TALENT: { id: 196884, name: "Feral Lunge", icon: "spell_beastmaster_wolf" },
  LIGHTNING_SHIELD_TALENT: { id: 192106, name: "Lightning Shield", icon: "spell_nature_lightningshield" },
  HAILSTORM_TALENT: { id: 210853, name: "Hailstorm", icon: "spell_frost_frostbrand" },
  TEMPEST_TALENT: { id: 192234, name: "Tempest", icon: "inv_misc_herb_stormvine" },
  OVERCHARGE_TALENT: { id: 210727, name: "Overcharge", icon: "spell_nature_callstorm" },
  EMPOWERED_STORMLASH_TALENT: { id: 210731, name: "Empowered Stormlash", icon: "spell_lightning_lightningbolt01" },
  CRASHING_STORM_TALENT: { id: 192246, name: "Crashing Storm", icon: "spell_nature_unrelentingstorm" },
  FURY_OF_AIR_TALENT: { id: 197211, name: "Fury of Air", icon: "ability_ironmaidens_swirlingvortex", maelstromCost: 3 },
  SUNDERING_TALENT: { id: 197214, name: "Sundering", icon: "ability_rhyolith_lavapool", maelstromCost: 20 },
  BOULDERFIST_TALENT: { id: 246035, name: "Boulderfist", icon: "ability_earthenfury_giftofearth" },
  EARTHEN_SPIKE_TALENT: { id: 188089, name: "Earthen Spike", icon: "ability_earthen_pillar", maelstromCost: 20 },
  ASCENDANCE_TALENT_ENHANCEMENT: { id: 114051, name: "Ascendance", icon: "spell_fire_elementaldevastation" },
  // Elemental
  PATH_OF_FLAME_TALENT: { id: 201909, name: "Path of Flame", icon: "spell_mage_flameorb" },
  EARTHEN_RAGE_TALENT: { id: 170374, name: "Earthen Rage", icon: "ability_earthen_pillar" },
  TOTEM_MASTERY_TALENT: { id: 210643, name: "Totem Mastery", icon: "spell_nature_wrathofair_totem" },
  AFTERSHOCK_TALENT: { id: 210707, name: "Aftershock", icon: "spell_nature_stormreach" },
  ELEMENTAL_FUSION_TALENT: { id: 192235, name: "Elemental Fusion", icon: "spell_shaman_shockinglava" },
  PRIMAL_ELEMENTALIST_TALENT: { id: 117013, name: "Primal Elementalist", icon: "shaman_talent_primalelementalist" },
  ELEMENTAL_BLAST_TALENT: { id: 117014, name: "Elemental Blast", icon: "shaman_talent_elementalblast" },
  LIQUID_MAGMA_TOTEM_TALENT: { id: 192222, name: "Liquid Magma Totem", icon: "spell_shaman_spewlava" },
  STORM_ELEMENTAL_TALENT: { id: 192249, name: "Storm Elemental", icon: "spell_shaman_measuredinsight" },
  LIGHTNING_ROD_TALENT: { id: 210689, name: "Lightning Rod", icon: "inv_rod_enchantedcobalt" },
  ICEFURY_TALENT: { id: 210714, name: "Icefury", icon: "spell_frost_iceshard" },
  ASCENDANCE_TALENT_ELEMENTAL: { id: 114050, name: "Ascendance", icon: "spell_fire_elementaldevastation" },
  // Restoration
  UNDULATION_TALENT: { id: 200071, name: "Undulation", icon: "spell_nature_healingwavelesser" },
  UNLEASH_LIFE_TALENT: { id: 73685, name: "Unleash Life", icon: "spell_shaman_unleashweapon_life", manaCost: 11000 },
  TORRENT_TALENT: { id: 200072, name: "Torrent", icon: "spell_nature_riptide" },
  GRACEFUL_SPIRIT_TALENT: { id: 192088, name: "Graceful Spirit", icon: "spell_shaman_spectraltransformation" },
  CRASHING_WAVES_TALENT: { id: 197464, name: "Crashing Waves", icon: "spell_frost_summonwaterelemental" },
  DELUGE_TALENT: { id: 200076, name: "Deluge", icon: "ability_shawaterelemental_reform" },
  ANCESTRAL_PROTECTION_TOTEM_TALENT: { id: 207399, name: "Ancestral Protection Totem", icon: "spell_nature_reincarnation", manaCost: 24200 },
  EARTHEN_SHIELD_TOTEM_TALENT: { id: 198838, name: "Earthen Shield Totem", icon: "spell_nature_stoneskintotem", manaCost: 24200 },
  ANCESTRAL_VIGOR_TALENT: { id: 207401, name: "Ancestral Vigor", icon: "spell_shaman_blessingoftheeternals" },
  BOTTOMLESS_DEPTHS_TALENT: { id: 197467, name: "Bottomless Depths", icon: "ability_shawaterelemental_swirl" },
  CLOUDBURST_TOTEM_TALENT: { id: 157153, name: "Cloudburst Totem", icon: "ability_shaman_condensationtotem", manaCost: 18920 },
  WELLSPRING_TALENT: { id: 197995, name: "Wellspring", icon: "ability_shawaterelemental_split", manaCost: 44000 },
  HIGH_TIDE_TALENT: { id: 157154, name: "High Tide", icon: "spell_shaman_hightide" },
  ASCENDANCE_TALENT_RESTORATION: { id: 114052, name: "Ascendance", icon: "spell_fire_elementaldevastation" },
};
