import SPELLS from 'common/SPELLS';

const SHAMAN_BASE_ABILITIES = [
  SPELLS.HEALING_WAVE.id,
  SPELLS.CHAIN_HEAL.id,
  SPELLS.HEALING_SURGE_RESTORATION.id,
  SPELLS.HEALING_STREAM_TOTEM_HEAL.id,
  SPELLS.HEALING_TIDE_TOTEM_HEAL.id,
  SPELLS.RIPTIDE.id,
  SPELLS.HEALING_RAIN_HEAL.id,
  SPELLS.WELLSPRING_HEAL.id,
  SPELLS.UNLEASH_LIFE_TALENT.id,
  SPELLS.EARTH_SHIELD_HEAL.id,
  SPELLS.DOWNPOUR_TALENT.id,
  SPELLS.ASCENDANCE_INITIAL_HEAL.id,
];

const SHAMAN_AZERITE = [
  SPELLS.OVERFLOWING_SHORES_HEAL.id,
  SPELLS.SWELLING_STREAM_HEAL.id,
  SPELLS.SPOUTING_SPIRITS_HEAL.id,
  SPELLS.SERENE_SPIRIT_HEAL.id,
  SPELLS.PACK_SPIRIT_HEAL.id,
];

export const ABILITIES_AFFECTED_BY_HEALING_INCREASES = [
  ...SHAMAN_BASE_ABILITIES,

  // Azerite Traits
  ...SHAMAN_AZERITE,
  SPELLS.IMPASSIVE_VISAGE_HEAL.id,
  SPELLS.VAMPIRIC_SPEED_HEAL.id,

  // Items
  SPELLS.REJUVENATING_TIDES.id,
  SPELLS.TOUCH_OF_THE_VOODOO.id,

  // While the following spells don't double dip in healing increases, they gain the same percentual bonus from the transfer
  SPELLS.CLOUDBURST_TOTEM_HEAL.id,
  SPELLS.ASCENDANCE_HEAL.id,
  SPELLS.LEECH.id,
];

export const BASE_ABILITIES_AFFECTED_BY_MASTERY = [
  ...SHAMAN_BASE_ABILITIES,
  ...SHAMAN_AZERITE,
];

export const ABILITIES_AFFECTED_BY_MASTERY = [
  ...BASE_ABILITIES_AFFECTED_BY_MASTERY,
  // While the following spells don't double dip in healing increases, they gain the same percentual bonus from the transfer
  SPELLS.CLOUDBURST_TOTEM_HEAL.id,
  SPELLS.ASCENDANCE_HEAL.id,
  SPELLS.LEECH.id,
];

export const ABILITIES_FEEDING_INTO_CBT = [
  ...SHAMAN_BASE_ABILITIES,
  SPELLS.ASCENDANCE_HEAL.id,
  SPELLS.NATURES_GUARDIAN_HEAL.id,
];

export const ABILITIES_NOT_FEEDING_INTO_ASCENDANCE = [
  SPELLS.HEALING_TIDE_TOTEM_HEAL.id,
  SPELLS.HEALING_STREAM_TOTEM_HEAL.id,
  SPELLS.SPIRIT_LINK_TOTEM_REDISTRIBUTE.id,
  SPELLS.LEECH.id,
  SPELLS.ASCENDANCE_HEAL.id,
  SPELLS.CLOUDBURST_TOTEM_HEAL.id,
  SPELLS.ASCENDANCE_INITIAL_HEAL.id,
  SPELLS.SPOUTING_SPIRITS_HEAL.id,
];
