import type { RetailSpell } from 'wow-dbc';
const SPELLS = {
  AUTO_SHOT: {
    id: 75,
    type: 'baseline',
    iconID: 132369,
    passive: false,
    name: 'Auto Shot',
    icon: 'n',
  },
  MEND_PET: {
    id: 136,
    type: 'baseline',
    iconID: 132179,
    passive: false,
    name: 'Mend Pet',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    icon: '0',
  },
  DISENGAGE: {
    id: 781,
    type: 'baseline',
    iconID: 132294,
    passive: false,
    name: 'Disengage',
    cooldown: {
      duration: 20000,
      hasted: false,
      modifiers: [
        {
          duration: -10000,
          hasted: false,
          requiredSpells: [118675],
        },
      ],
    },
    icon: 's',
  },
  CALL_PET_1: {
    id: 883,
    type: 'baseline',
    iconID: 132161,
    passive: false,
    name: 'Call Pet 1',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    icon: 'o',
  },
  REVIVE_PET: {
    id: 982,
    type: 'baseline',
    iconID: 132163,
    passive: false,
    name: 'Revive Pet',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 4000,
    },
    icon: 'y',
  },
  HUNTERS_MARK: {
    id: 1130,
    type: 'baseline',
    iconID: 132212,
    passive: false,
    name: "Hunter's Mark",
    gcd: {
      duration: 1000,
      hasted: true,
    },
    icon: 'g',
  },
  BEAST_LORE: {
    id: 1462,
    type: 'baseline',
    iconID: 132270,
    passive: false,
    name: 'Beast Lore',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    icon: 'd',
  },
  TRACK_BEASTS_HIDDEN: {
    id: 1494,
    type: 'baseline',
    iconID: 132328,
    passive: false,
    hidden: 'always',
    name: 'Track Beasts',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    icon: '3',
  },
  FREEZING_TRAP_TRAP_LAUNCHER: {
    id: 60192,
    grantedBy: 77769,
    type: 'temporary',
    iconID: 135834,
    passive: false,
    hidden: 'always',
    name: 'Freezing Trap',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 24000,
      hasted: false,
    },
    icon: '3',
  },
  FREEZING_TRAP: {
    id: 1499,
    type: 'baseline',
    iconID: 135834,
    passive: false,
    name: 'Freezing Trap',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 24000,
      hasted: false,
    },
    icon: '3',
  },
  SCARE_BEAST: {
    id: 1513,
    type: 'baseline',
    iconID: 132118,
    passive: false,
    name: 'Scare Beast',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 1500,
    },
    icon: 'a',
  },
  TAME_BEAST: {
    id: 1515,
    type: 'baseline',
    iconID: 132164,
    passive: false,
    name: 'Tame Beast',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    channel: {
      duration: 10000,
      hasted: true,
      buffIsLogged: true,
      triggeredSpells: [
        {
          spell: 13481,
          period: 10000,
          hasted: true,
        },
      ],
    },
    icon: 'b',
  },
  FLARE: {
    id: 1543,
    type: 'baseline',
    iconID: 135815,
    passive: false,
    name: 'Flare',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 20000,
      hasted: false,
    },
    icon: 'g',
  },
  SERPENT_STING: {
    id: 1978,
    type: 'baseline',
    iconID: 132204,
    passive: false,
    name: 'Serpent Sting',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: '',
  },
  DISMISS_PET: {
    id: 2641,
    type: 'baseline',
    iconID: 136095,
    passive: false,
    name: 'Dismiss Pet',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    castTime: {
      duration: 3000,
    },
    icon: 'w',
  },
  MULTI_SHOT: {
    id: 2643,
    type: 'baseline',
    iconID: 132330,
    passive: false,
    name: 'Multi-Shot',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'w',
  },
  ARCANE_SHOT: {
    id: 3044,
    type: 'baseline',
    iconID: 132218,
    passive: false,
    name: 'Arcane Shot',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'a',
  },
  RAPID_FIRE: {
    id: 3045,
    type: 'baseline',
    iconID: 132208,
    passive: false,
    name: 'Rapid Fire',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
    icon: 'l',
  },
  BLACK_ARROW: {
    id: 3674,
    type: 'baseline',
    iconID: 136181,
    passive: false,
    name: 'Black Arrow',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 24000,
      hasted: false,
    },
    icon: '0',
  },
  CONCUSSIVE_SHOT: {
    id: 5116,
    type: 'baseline',
    iconID: 135860,
    passive: false,
    name: 'Concussive Shot',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 5000,
      hasted: false,
    },
    icon: '',
  },
  ASPECT_OF_THE_CHEETAH: {
    id: 5118,
    type: 'baseline',
    iconID: 132242,
    passive: false,
    name: 'Aspect of the Cheetah',
    cooldown: {
      duration: 1000,
      hasted: false,
    },
    icon: 'y',
  },
  FEIGN_DEATH: {
    id: 5384,
    type: 'baseline',
    iconID: 132293,
    passive: false,
    name: 'Feign Death',
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: '',
  },
  EAGLE_EYE: {
    id: 6197,
    type: 'baseline',
    iconID: 132172,
    passive: false,
    name: 'Eagle Eye',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    channel: {
      duration: 60000,
      hasted: false,
      buffIsLogged: true,
      triggeredSpells: [],
    },
    icon: 'w',
  },
  FEED_PET: {
    id: 6991,
    type: 'baseline',
    iconID: 132165,
    passive: false,
    name: 'Feed Pet',
    cooldown: {
      duration: 10000,
      hasted: false,
    },
    icon: 'a',
  },
  MAIL_HIDDEN: {
    id: 8737,
    type: 'baseline',
    iconID: 132627,
    passive: true,
    hidden: 'always',
    name: 'Mail',
    icon: 't',
  },
  ASPECT_OF_THE_PACK: {
    id: 13159,
    type: 'baseline',
    iconID: 132267,
    passive: false,
    name: 'Aspect of the Pack',
    cooldown: {
      duration: 1000,
      hasted: false,
    },
    icon: 'o',
  },
  ASPECT_OF_THE_HAWK: {
    id: 13165,
    type: 'baseline',
    iconID: 136076,
    passive: false,
    name: 'Aspect of the Hawk',
    cooldown: {
      duration: 1000,
      hasted: false,
    },
    icon: 'a',
  },
  ICE_TRAP_TRAP_LAUNCHER: {
    id: 82941,
    grantedBy: 77769,
    type: 'temporary',
    iconID: 612394,
    passive: false,
    hidden: 'always',
    name: 'Ice Trap',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 24000,
      hasted: false,
    },
    icon: '_',
  },
  ICE_TRAP: {
    id: 13809,
    type: 'baseline',
    iconID: 612394,
    passive: false,
    name: 'Ice Trap',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 24000,
      hasted: false,
    },
    icon: '_',
  },
  EXPLOSIVE_TRAP_TRAP_LAUNCHER: {
    id: 82939,
    grantedBy: 77769,
    type: 'temporary',
    iconID: 135826,
    passive: false,
    hidden: 'always',
    name: 'Explosive Trap',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 24000,
      hasted: false,
    },
    icon: 'i',
  },
  EXPLOSIVE_TRAP: {
    id: 13813,
    type: 'baseline',
    iconID: 135826,
    passive: false,
    name: 'Explosive Trap',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 24000,
      hasted: false,
    },
    icon: 'i',
  },
  DETERRENCE_CROUCHING_TIGER_HIDDEN_CHIMERA_TALENT: {
    id: 148467,
    grantedBy: 118675,
    type: 'temporary',
    iconID: 132369,
    passive: false,
    name: 'Deterrence',
    charges: {
      max: 2,
    },
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'n',
  },
  DETERRENCE: {
    id: 19263,
    type: 'baseline',
    iconID: 132369,
    passive: false,
    name: 'Deterrence',
    charges: {
      max: 2,
    },
    cooldown: {
      duration: 180000,
      hasted: false,
    },
    icon: 'n',
  },
  WYVERN_STING_TALENT: {
    id: 19386,
    type: 'mists-talent',
    row: 1,
    column: 2,
    iconID: 135125,
    passive: false,
    hidden: 'unless-learned',
    name: 'Wyvern Sting',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
    },
    icon: 't',
  },
  ENTRAPMENT_PASSIVE: {
    id: 19387,
    type: 'baseline',
    iconID: 136100,
    passive: true,
    name: 'Entrapment',
    icon: '"',
  },
  SCATTER_SHOT: {
    id: 19503,
    type: 'baseline',
    iconID: 132153,
    passive: false,
    name: 'Scatter Shot',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 't',
  },
  TRUESHOT_AURA_PASSIVE: {
    id: 19506,
    type: 'baseline',
    iconID: 132329,
    passive: true,
    name: 'Trueshot Aura',
    icon: '.',
  },
  INTIMIDATION_TALENT: {
    id: 19577,
    type: 'mists-talent',
    row: 1,
    column: 3,
    iconID: 132111,
    passive: false,
    hidden: 'unless-learned',
    name: 'Intimidation',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: 'l',
  },
  TRANQUILIZING_SHOT: {
    id: 19801,
    type: 'baseline',
    iconID: 136020,
    passive: false,
    name: 'Tranquilizing Shot',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: '3',
  },
  TRACK_DEMONS_HIDDEN: {
    id: 19878,
    type: 'baseline',
    iconID: 136217,
    passive: false,
    hidden: 'always',
    name: 'Track Demons',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    icon: 'b',
  },
  TRACK_DRAGONKIN_HIDDEN: {
    id: 19879,
    type: 'baseline',
    iconID: 134153,
    passive: false,
    hidden: 'always',
    name: 'Track Dragonkin',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    icon: 'd',
  },
  TRACK_ELEMENTALS_HIDDEN: {
    id: 19880,
    type: 'baseline',
    iconID: 135861,
    passive: false,
    hidden: 'always',
    name: 'Track Elementals',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    icon: 'a',
  },
  TRACK_GIANTS_HIDDEN: {
    id: 19882,
    type: 'baseline',
    iconID: 132275,
    passive: false,
    hidden: 'always',
    name: 'Track Giants',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    icon: '',
  },
  TRACK_HUMANOIDS_HIDDEN: {
    id: 19883,
    type: 'baseline',
    iconID: 135942,
    passive: false,
    hidden: 'always',
    name: 'Track Humanoids',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    icon: 'w',
  },
  TRACK_UNDEAD_HIDDEN: {
    id: 19884,
    type: 'baseline',
    iconID: 136142,
    passive: false,
    hidden: 'always',
    name: 'Track Undead',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    icon: 'n',
  },
  TRACK_HIDDEN_HIDDEN: {
    id: 19885,
    type: 'baseline',
    iconID: 132320,
    passive: false,
    hidden: 'always',
    name: 'Track Hidden',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    icon: 't',
  },
  DISTRACTING_SHOT: {
    id: 20736,
    type: 'baseline',
    iconID: 135736,
    passive: false,
    name: 'Distracting Shot',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 8000,
      hasted: false,
    },
    icon: 'u',
  },
  MISDIRECTION: {
    id: 34477,
    type: 'baseline',
    iconID: 132180,
    passive: false,
    name: 'Misdirection',
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: '7',
  },
  SNAKE_TRAP_TRAP_LAUNCHER: {
    id: 82948,
    grantedBy: 77769,
    type: 'temporary',
    iconID: 132211,
    passive: false,
    hidden: 'always',
    name: 'Snake Trap',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 24000,
      hasted: false,
    },
    icon: 'n',
  },
  SNAKE_TRAP: {
    id: 34600,
    type: 'baseline',
    iconID: 132211,
    passive: false,
    name: 'Snake Trap',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 24000,
      hasted: false,
    },
    icon: 'n',
  },
  CAMOUFLAGE: {
    id: 51753,
    type: 'baseline',
    iconID: 132171,
    passive: false,
    name: 'Camouflage',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: '.',
  },
  MASTERS_CALL: {
    id: 53271,
    type: 'baseline',
    iconID: 236189,
    passive: false,
    name: "Master's Call",
    cooldown: {
      duration: 45000,
      hasted: false,
    },
    icon: ',',
  },
  EXPLOSIVE_SHOT: {
    id: 53301,
    type: 'baseline',
    iconID: 236178,
    passive: false,
    name: 'Explosive Shot',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 6000,
      hasted: false,
    },
    icon: 'o',
  },
  KILL_SHOT: {
    id: 53351,
    type: 'baseline',
    iconID: 236174,
    passive: false,
    name: 'Kill Shot',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 10000,
      hasted: false,
    },
    icon: 'r',
  },
  LOCK_AND_LOAD_PASSIVE: {
    id: 56343,
    type: 'baseline',
    iconID: 236185,
    passive: true,
    name: 'Lock and Load',
    icon: 'w',
  },
  STEADY_SHOT: {
    id: 56641,
    type: 'baseline',
    iconID: 132213,
    passive: false,
    name: 'Steady Shot',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    castTime: {
      duration: 2000,
    },
    icon: 's',
  },
  TRAP_MASTERY_PASSIVE: {
    id: 63458,
    type: 'baseline',
    iconID: 132149,
    passive: true,
    name: 'Trap Mastery',
    icon: '_',
  },
  MASTERY_ESSENCE_OF_THE_VIPER_PASSIVE: {
    id: 76658,
    type: 'baseline',
    iconID: 135833,
    passive: true,
    name: 'Mastery: Essence of the Viper',
    icon: '0',
  },
  FOCUS_HIDDEN: {
    id: 77442,
    type: 'baseline',
    iconID: 236180,
    passive: false,
    hidden: 'always',
    name: 'Focus',
    icon: '_',
  },
  COBRA_SHOT: {
    id: 77767,
    type: 'baseline',
    overrides: 56641,
    iconID: 461114,
    passive: false,
    name: 'Cobra Shot',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    castTime: {
      duration: 2000,
    },
    icon: 'g',
  },
  TRAP_LAUNCHER: {
    id: 77769,
    type: 'baseline',
    iconID: 461122,
    passive: false,
    name: 'Trap Launcher',
    cooldown: {
      duration: 1500,
      hasted: false,
    },
    icon: 'i',
  },
  WIDOW_VENOM: {
    id: 82654,
    type: 'baseline',
    iconID: 236200,
    passive: false,
    name: 'Widow Venom',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'w',
  },
  FERVOR_TALENT: {
    id: 82726,
    type: 'mists-talent',
    row: 3,
    column: 1,
    iconID: 132160,
    passive: false,
    name: 'Fervor',
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 'o',
  },
  IMPROVED_SERPENT_STING_PASSIVE: {
    id: 82834,
    type: 'baseline',
    iconID: 132204,
    passive: true,
    name: 'Improved Serpent Sting',
    icon: '',
  },
  CALL_PET_2: {
    id: 83242,
    type: 'baseline',
    iconID: 132161,
    passive: false,
    name: 'Call Pet 2',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    icon: 'o',
  },
  CALL_PET_3: {
    id: 83243,
    type: 'baseline',
    iconID: 132161,
    passive: false,
    name: 'Call Pet 3',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    icon: 'o',
  },
  CALL_PET_4: {
    id: 83244,
    type: 'baseline',
    iconID: 132161,
    passive: false,
    name: 'Call Pet 4',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    icon: 'o',
  },
  CALL_PET_5: {
    id: 83245,
    type: 'baseline',
    iconID: 132161,
    passive: false,
    name: 'Call Pet 5',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    icon: 'o',
  },
  MAIL_SPECIALIZATION_PASSIVE: {
    id: 86538,
    type: 'baseline',
    iconID: 132629,
    passive: true,
    name: 'Mail Specialization',
    icon: 'b',
  },
  FOCUSED_AIM_PASSIVE: {
    id: 87324,
    type: 'baseline',
    iconID: 236179,
    passive: true,
    name: 'Focused Aim',
    icon: 'n',
  },
  SERPENT_SPREAD_PASSIVE: {
    id: 87935,
    type: 'baseline',
    iconID: 132209,
    passive: true,
    name: 'Serpent Spread',
    icon: 'd',
  },
  CONTROL_PET_PASSIVE: {
    id: 93321,
    type: 'baseline',
    iconID: 132162,
    passive: true,
    name: 'Control Pet',
    icon: 't',
  },
  CONTROL_PET_HIDDEN: {
    id: 93322,
    type: 'baseline',
    iconID: 132162,
    passive: false,
    hidden: 'always',
    name: 'Control Pet',
    icon: 't',
  },
  SPIRIT_BOND_TALENT: {
    id: 109212,
    type: 'mists-talent',
    row: 2,
    column: 3,
    iconID: 132121,
    passive: true,
    name: 'Spirit Bond',
    icon: 'r',
  },
  POSTHASTE_TALENT: {
    id: 109215,
    type: 'mists-talent',
    row: 0,
    column: 1,
    iconID: 461119,
    passive: true,
    name: 'Posthaste',
    icon: 'a',
  },
  BINDING_SHOT_TALENT: {
    id: 109248,
    type: 'mists-talent',
    row: 1,
    column: 1,
    iconID: 462650,
    passive: false,
    name: 'Binding Shot',
    cooldown: {
      duration: 45000,
      hasted: false,
    },
    icon: 'r',
  },
  POWERSHOT_TALENT: {
    id: 109259,
    type: 'mists-talent',
    row: 5,
    column: 2,
    iconID: 461120,
    passive: false,
    name: 'Powershot',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
    },
    castTime: {
      duration: 2250,
    },
    icon: 's',
  },
  ASPECT_OF_THE_IRON_HAWK_TALENT: {
    id: 109260,
    overrides: 13165,
    type: 'mists-talent',
    row: 2,
    column: 2,
    iconID: 612363,
    passive: false,
    name: 'Aspect of the Iron Hawk',
    cooldown: {
      duration: 1000,
      hasted: false,
    },
    icon: 'm',
  },
  NARROW_ESCAPE_TALENT: {
    id: 109298,
    type: 'mists-talent',
    row: 0,
    column: 2,
    iconID: 237430,
    passive: true,
    name: 'Narrow Escape',
    icon: 'd',
  },
  EXHILARATION_TALENT: {
    id: 109304,
    type: 'mists-talent',
    row: 2,
    column: 1,
    iconID: 461117,
    passive: false,
    name: 'Exhilaration',
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'c',
  },
  THRILL_OF_THE_HUNT_TALENT: {
    id: 109306,
    type: 'mists-talent',
    row: 3,
    column: 3,
    iconID: 132216,
    passive: true,
    name: 'Thrill of the Hunt',
    icon: 't',
  },
  SYMBIOSIS: {
    id: 110497,
    type: 'baseline',
    iconID: 571587,
    passive: false,
    name: 'Symbiosis',
    icon: '',
  },
  GLAIVE_TOSS_TALENT: {
    id: 117050,
    type: 'mists-talent',
    row: 5,
    column: 1,
    iconID: 648707,
    passive: false,
    name: 'Glaive Toss',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
    icon: 'r',
  },
  TRACKING_PASSIVE: {
    id: 118424,
    type: 'baseline',
    iconID: 132328,
    passive: true,
    name: 'Tracking',
    icon: '3',
  },
  CROUCHING_TIGER_HIDDEN_CHIMERA_TALENT: {
    id: 118675,
    type: 'mists-talent',
    row: 0,
    column: 3,
    iconID: 236190,
    passive: true,
    name: 'Crouching Tiger, Hidden Chimera',
    icon: '"',
  },
  VIPER_VENOM_PASSIVE: {
    id: 118976,
    type: 'baseline',
    iconID: 236166,
    passive: true,
    name: 'Viper Venom',
    icon: 'o',
  },
  BARRAGE_TALENT: {
    id: 120360,
    type: 'mists-talent',
    row: 5,
    column: 3,
    iconID: 236201,
    passive: false,
    name: 'Barrage',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    channel: {
      duration: 3000,
      hasted: true,
      buffIsLogged: true,
      triggeredSpells: [
        {
          spell: 120361,
          period: 200,
          hasted: false,
        },
      ],
    },
    icon: 'o',
  },
  DIRE_BEAST_TALENT: {
    id: 120679,
    type: 'mists-talent',
    row: 3,
    column: 2,
    iconID: 461121,
    passive: false,
    name: 'Dire Beast',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 's',
  },
  LYNX_RUSH_TALENT: {
    id: 120697,
    type: 'mists-talent',
    row: 4,
    column: 3,
    iconID: 132167,
    passive: false,
    name: 'Lynx Rush',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 90000,
      hasted: false,
    },
    icon: '_',
  },
  GLAIVE_TOSS_HIDDEN_1: {
    id: 120761,
    type: 'baseline',
    iconID: 132330,
    passive: false,
    hidden: 'always',
    name: 'Glaive Toss',
    icon: 'w',
  },
  GLAIVE_TOSS_HIDDEN_2: {
    id: 121414,
    type: 'baseline',
    iconID: 132330,
    passive: false,
    hidden: 'always',
    name: 'Glaive Toss',
    icon: 'w',
  },
  STAMPEDE: {
    id: 121818,
    type: 'baseline',
    iconID: 461112,
    passive: false,
    name: 'Stampede',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 300000,
      hasted: false,
    },
    icon: 'i',
  },
  BLINK_STRIKES_TALENT: {
    id: 130392,
    type: 'mists-talent',
    row: 4,
    column: 2,
    iconID: 135731,
    passive: true,
    name: 'Blink Strikes',
    icon: 'o',
  },
  A_MURDER_OF_CROWS_TALENT: {
    id: 131894,
    type: 'mists-talent',
    row: 4,
    column: 1,
    iconID: 645217,
    passive: false,
    name: 'A Murder of Crows',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'n',
  },
  HOTFIX_PASSIVE_HIDDEN_1: {
    id: 137014,
    type: 'baseline',
    iconID: 236216,
    passive: true,
    hidden: 'always',
    name: 'Hotfix Passive',
    icon: 'n',
  },
  HOTFIX_PASSIVE_HIDDEN_2: {
    id: 137017,
    type: 'baseline',
    iconID: 236216,
    passive: true,
    hidden: 'always',
    name: 'Hotfix Passive',
    icon: 'n',
  },
  ANCIENT_ZANDALARI_KNOWLEDGE_HIDDEN: {
    id: 138430,
    type: 'baseline',
    iconID: 791593,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Ancient Zandalari Knowledge',
    icon: 'i',
  },
  COUNTER_SHOT: {
    id: 147362,
    type: 'baseline',
    iconID: 249170,
    passive: false,
    name: 'Counter Shot',
    cooldown: {
      duration: 24000,
      hasted: false,
    },
    icon: ',',
  },
} as const satisfies Record<string, RetailSpell & { icon: string }>;
export default SPELLS;
