import type { RetailSpell } from 'wow-dbc';
const SPELLS = {
  EYE_OF_KILROGG: {
    id: 126,
    type: 'baseline',
    iconID: 136155,
    passive: false,
    name: 'Eye of Kilrogg',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    channel: {
      duration: 45000,
      hasted: false,
      buffIsLogged: true,
      triggeredSpells: [],
    },
    castTime: {
      duration: 2000,
    },
    icon: 'spell_shadow_evileye.jpg',
  },
  CORRUPTION_CORRUPTION: {
    id: 146739,
    grantedBy: 172,
    type: 'temporary',
    iconID: 136118,
    passive: false,
    hidden: 'always',
    name: 'Corruption',
    icon: 'spell_shadow_abominationexplosion.jpg',
  },
  CORRUPTION_1: {
    id: 172,
    type: 'baseline',
    iconID: 136118,
    passive: false,
    name: 'Corruption',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'spell_shadow_abominationexplosion.jpg',
  },
  CORRUPTION_2: {
    id: 131740,
    type: 'baseline',
    iconID: 136118,
    castableWhileCasting: true,
    passive: false,
    hidden: 'unless-learned',
    name: 'Corruption',
    icon: 'spell_shadow_abominationexplosion.jpg',
  },
  SHADOW_BOLT_GLYPH: {
    id: 112092,
    grantedBy: 56240,
    type: 'temporary',
    overrides: 686,
    iconID: 136197,
    passive: false,
    name: 'Shadow Bolt',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 1700,
    },
    icon: 'spell_shadow_shadowbolt.jpg',
  },
  SHADOW_BOLT: {
    id: 686,
    type: 'baseline',
    iconID: 136197,
    passive: false,
    name: 'Shadow Bolt',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 1700,
    },
    icon: 'spell_shadow_shadowbolt.jpg',
  },
  SHADOW_BOLT_1: {
    id: 114328,
    grantedBy: 112092,
    type: 'temporary',
    iconID: 136197,
    passive: false,
    name: 'Shadow Bolt',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'spell_shadow_shadowbolt.jpg',
  },
  SHADOW_BOLT_2: {
    id: 114329,
    grantedBy: 112092,
    type: 'temporary',
    iconID: 136197,
    passive: false,
    name: 'Shadow Bolt',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'spell_shadow_shadowbolt.jpg',
  },
  SUMMON_IMP: {
    id: 688,
    type: 'baseline',
    iconID: 136218,
    passive: false,
    name: 'Summon Imp',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 5000,
    },
    icon: 'spell_shadow_summonimp.jpg',
  },
  DRAIN_LIFE: {
    id: 689,
    type: 'baseline',
    iconID: 136169,
    passive: false,
    name: 'Drain Life',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    channel: {
      duration: 6000,
      hasted: true,
      buffIsLogged: true,
      triggeredSpells: [],
    },
    icon: 'spell_shadow_lifedrain02.jpg',
  },
  SUMMON_FELHUNTER: {
    id: 691,
    type: 'baseline',
    iconID: 136217,
    passive: false,
    name: 'Summon Felhunter',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 5000,
    },
    icon: 'spell_shadow_summonfelhunter.jpg',
  },
  SUMMON_VOIDWALKER: {
    id: 697,
    type: 'baseline',
    iconID: 136221,
    passive: false,
    name: 'Summon Voidwalker',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 5000,
    },
    icon: 'spell_shadow_summonvoidwalker.jpg',
  },
  RITUAL_OF_SUMMONING: {
    id: 698,
    type: 'baseline',
    iconID: 136223,
    passive: false,
    name: 'Ritual of Summoning',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    channel: {
      duration: 120000,
      hasted: false,
      buffIsLogged: true,
      triggeredSpells: [],
    },
    icon: 'spell_shadow_twilight.jpg',
  },
  BANISH: {
    id: 710,
    type: 'baseline',
    iconID: 136135,
    passive: false,
    name: 'Banish',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 1500,
    },
    icon: 'spell_shadow_cripple.jpg',
  },
  SUMMON_SUCCUBUS: {
    id: 712,
    type: 'baseline',
    iconID: 136220,
    passive: false,
    name: 'Summon Succubus',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 5000,
    },
    icon: 'spell_shadow_summonsuccubus.jpg',
  },
  HEALTH_FUNNEL_GLYPH: {
    id: 114189,
    grantedBy: 56238,
    type: 'temporary',
    overrides: 755,
    iconID: 136168,
    passive: false,
    name: 'Health Funnel',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 10000,
      hasted: false,
    },
    icon: 'spell_shadow_lifedrain.jpg',
  },
  HEALTH_FUNNEL: {
    id: 755,
    type: 'baseline',
    iconID: 136168,
    passive: false,
    name: 'Health Funnel',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    channel: {
      duration: 6000,
      hasted: true,
      buffIsLogged: true,
      triggeredSpells: [],
    },
    icon: 'spell_shadow_lifedrain.jpg',
  },
  SUBJUGATE_DEMON: {
    id: 1098,
    type: 'baseline',
    iconID: 136154,
    passive: false,
    name: 'Subjugate Demon',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 3000,
    },
    icon: 'spell_shadow_enslavedemon.jpg',
  },
  SUMMON_INFERNAL: {
    id: 1122,
    type: 'baseline',
    iconID: 136219,
    passive: false,
    name: 'Summon Infernal',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 600000,
      hasted: false,
    },
    icon: 'spell_shadow_summoninfernal.jpg',
  },
  LIFE_TAP: {
    id: 1454,
    type: 'baseline',
    iconID: 136126,
    passive: false,
    name: 'Life Tap',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'spell_shadow_burningspirit.jpg',
  },
  CURSE_OF_THE_ELEMENTS: {
    id: 1490,
    type: 'baseline',
    iconID: 615099,
    passive: false,
    name: 'Curse of the Elements',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 0,
      hasted: false,
      modifiers: [
        {
          duration: 10000,
          hasted: false,
          requiredSpells: [103958],
        },
      ],
    },
    icon: 'warlock_curse_shadow.jpg',
  },
  HELLFIRE: {
    id: 1949,
    type: 'baseline',
    iconID: 135818,
    passive: false,
    name: 'Hellfire',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    channel: {
      duration: 14000,
      hasted: true,
      buffIsLogged: true,
      triggeredSpells: [],
    },
    icon: 'spell_fire_incinerate.jpg',
  },
  HOWL_OF_TERROR: {
    id: 5484,
    type: 'baseline',
    iconID: 607852,
    passive: false,
    name: 'Howl of Terror',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 40000,
      hasted: false,
    },
    icon: 'ability_warlock_howlofterror.jpg',
  },
  UNENDING_BREATH: {
    id: 5697,
    type: 'baseline',
    iconID: 136148,
    passive: false,
    name: 'Unending Breath',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'spell_shadow_demonbreath.jpg',
  },
  FEAR: {
    id: 5782,
    type: 'baseline',
    iconID: 136183,
    passive: false,
    name: 'Fear',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 1700,
    },
    icon: 'spell_shadow_possession.jpg',
  },
  FELSTEED_THE_CODEX_OF_XERRATH_PASSIVE: {
    id: 148970,
    grantedBy: 101508,
    type: 'temporary',
    overrides: 5784,
    iconID: 136103,
    passive: false,
    name: 'Felsteed',
    castTime: {
      duration: 1500,
    },
    icon: 'spell_nature_swiftness.jpg',
  },
  FELSTEED: {
    id: 5784,
    type: 'baseline',
    iconID: 136103,
    passive: false,
    name: 'Felsteed',
    castTime: {
      duration: 1500,
    },
    icon: 'spell_nature_swiftness.jpg',
  },
  CREATE_HEALTHSTONE: {
    id: 6201,
    type: 'baseline',
    iconID: 538745,
    passive: false,
    name: 'Create Healthstone',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 3000,
    },
    icon: 'warlock_-healthstone.jpg',
  },
  SOULSTONE_SOULSTONE: {
    id: 6203,
    grantedBy: 20707,
    type: 'temporary',
    iconID: 136210,
    passive: false,
    name: 'Soulstone',
    icon: 'spell_shadow_soulgem.jpg',
  },
  SOULSTONE: {
    id: 20707,
    type: 'baseline',
    iconID: 136210,
    passive: false,
    name: 'Soulstone',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 600000,
      hasted: false,
    },
    castTime: {
      duration: 3000,
    },
    icon: 'spell_shadow_soulgem.jpg',
  },
  TWILIGHT_WARD: {
    id: 6229,
    type: 'baseline',
    iconID: 425952,
    passive: false,
    name: 'Twilight Ward',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 'spell_fire_twilightfireward.jpg',
  },
  SOUL_FIRE: {
    id: 6353,
    type: 'baseline',
    iconID: 135808,
    passive: false,
    name: 'Soul Fire',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 4000,
    },
    icon: 'spell_fire_fireball02.jpg',
  },
  MORTAL_COIL_TALENT: {
    id: 6789,
    type: 'mists-talent',
    row: 1,
    column: 2,
    iconID: 607853,
    passive: false,
    hidden: 'unless-learned',
    name: 'Mortal Coil',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
    },
    icon: 'ability_warlock_mortalcoil.jpg',
  },
  SUMMON_DOOMGUARD_SUMMON_DOOMGUARD: {
    id: 60478,
    grantedBy: 18540,
    type: 'temporary',
    iconID: 615103,
    passive: false,
    name: 'Summon Doomguard',
    icon: 'warlock_summon_doomguard.jpg',
  },
  SUMMON_DOOMGUARD: {
    id: 18540,
    type: 'baseline',
    iconID: 615103,
    passive: false,
    name: 'Summon Doomguard',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 600000,
      hasted: false,
    },
    icon: 'warlock_summon_doomguard.jpg',
  },
  DREADSTEED_THE_CODEX_OF_XERRATH_HIDDEN: {
    id: 148972,
    grantedBy: 137206,
    type: 'temporary',
    overrides: 23161,
    iconID: 132238,
    passive: false,
    name: 'Dreadsteed',
    castTime: {
      duration: 1500,
    },
    icon: 'ability_mount_dreadsteed.jpg',
  },
  DREADSTEED: {
    id: 23161,
    type: 'baseline',
    iconID: 132238,
    passive: false,
    name: 'Dreadsteed',
    castTime: {
      duration: 1500,
    },
    icon: 'ability_mount_dreadsteed.jpg',
  },
  SEED_OF_CORRUPTION_HIDDEN_1: {
    id: 27285,
    type: 'baseline',
    iconID: 136193,
    passive: false,
    hidden: 'always',
    name: 'Seed of Corruption',
    icon: 'spell_shadow_seedofdestruction.jpg',
  },
  SEED_OF_CORRUPTION_HIDDEN_2: {
    id: 87385,
    type: 'baseline',
    iconID: 136193,
    passive: false,
    hidden: 'always',
    name: 'Seed of Corruption',
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: 'spell_shadow_seedofdestruction.jpg',
  },
  SOULSHATTER: {
    id: 29858,
    type: 'baseline',
    iconID: 135728,
    passive: false,
    name: 'Soulshatter',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'spell_arcane_arcane01.jpg',
  },
  CREATE_SOULWELL: {
    id: 29893,
    type: 'baseline',
    iconID: 136194,
    passive: false,
    name: 'Create Soulwell',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    castTime: {
      duration: 3000,
    },
    icon: 'spell_shadow_shadesofdarkness.jpg',
  },
  SUMMON_FELGUARD: {
    id: 30146,
    type: 'baseline',
    iconID: 136216,
    passive: false,
    name: 'Summon Felguard',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 5000,
    },
    icon: 'spell_shadow_summonfelguard.jpg',
  },
  SHADOWFURY_TALENT: {
    id: 30283,
    type: 'mists-talent',
    row: 1,
    column: 3,
    iconID: 607865,
    passive: false,
    hidden: 'unless-learned',
    name: 'Shadowfury',
    gcd: {
      duration: 500,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 'ability_warlock_shadowfurytga.jpg',
  },
  RAIN_OF_FIRE_HIDDEN_1: {
    id: 42223,
    type: 'baseline',
    iconID: 136186,
    passive: false,
    hidden: 'always',
    name: 'Rain of Fire',
    icon: 'spell_shadow_rainoffire.jpg',
  },
  RAIN_OF_FIRE_HIDDEN_2: {
    id: 104233,
    type: 'baseline',
    iconID: 136186,
    passive: false,
    hidden: 'always',
    name: 'Rain of Fire',
    icon: 'spell_shadow_rainoffire.jpg',
  },
  DEMONIC_BREATH_TALENT: {
    id: 47897,
    type: 'mists-talent',
    row: 1,
    column: 1,
    iconID: 236302,
    passive: false,
    hidden: 'unless-learned',
    name: 'Demonic Breath',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 20000,
      hasted: false,
    },
    icon: 'ability_warlock_shadowflame.jpg',
  },
  DEMONIC_CIRCLE_SUMMON: {
    id: 48018,
    type: 'baseline',
    iconID: 237559,
    passive: false,
    name: 'Demonic Circle: Summon',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 500,
    },
    icon: 'spell_shadow_demoniccirclesummon.jpg',
  },
  DEMONIC_CIRCLE_TELEPORT: {
    id: 48020,
    type: 'baseline',
    iconID: 237560,
    passive: false,
    name: 'Demonic Circle: Teleport',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
      modifiers: [
        {
          duration: -4000,
          hasted: false,
          requiredSpells: [63309],
        },
      ],
    },
    icon: 'spell_shadow_demoniccircleteleport.jpg',
  },
  GLYPH_OF_SUBTLETY: {
    type: 'glyph',
    id: 56217,
    glyphId: 282,
    glyphItemId: 42463,
    iconID: 132299,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Subtlety',
    icon: 'ability_rogue_masterofsubtlety.jpg',
  },
  GLYPH_OF_SIPHON_LIFE: {
    type: 'glyph',
    id: 56218,
    glyphId: 274,
    glyphItemId: 42455,
    iconID: 136188,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Siphon Life',
    icon: 'spell_shadow_requiem.jpg',
  },
  GLYPH_OF_HEALTHSTONE: {
    type: 'glyph',
    id: 56224,
    glyphId: 281,
    glyphItemId: 42462,
    iconID: 135230,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Healthstone',
    icon: 'inv_stone_04.jpg',
  },
  GLYPH_OF_SOULSTONE: {
    type: 'glyph',
    id: 56231,
    glyphId: 289,
    glyphItemId: 42470,
    iconID: 134336,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Soulstone',
    icon: 'inv_misc_orb_04.jpg',
  },
  GLYPH_OF_NIGHTMARES: {
    type: 'glyph',
    id: 56232,
    glyphId: 276,
    glyphItemId: 42457,
    iconID: 132251,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Nightmares',
    icon: 'ability_mount_nightmarehorse.jpg',
  },
  GLYPH_OF_UNSTABLE_AFFLICTION: {
    type: 'glyph',
    id: 56233,
    glyphId: 291,
    glyphItemId: 42472,
    iconID: 136228,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Unstable Affliction',
    icon: 'spell_shadow_unstableaffliction_3.jpg',
  },
  GLYPH_OF_CONFLAGRATE: {
    type: 'glyph',
    id: 56235,
    glyphId: 273,
    glyphItemId: 42454,
    iconID: 135807,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Conflagrate',
    icon: 'spell_fire_fireball.jpg',
  },
  GLYPH_OF_HEALTH_FUNNEL: {
    type: 'glyph',
    id: 56238,
    glyphId: 280,
    glyphItemId: 42461,
    iconID: 136168,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Health Funnel',
    icon: 'spell_shadow_lifedrain.jpg',
  },
  GLYPH_OF_SHADOW_BOLT: {
    type: 'glyph',
    id: 56240,
    glyphId: 286,
    glyphItemId: 42467,
    iconID: 136197,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Shadow Bolt',
    icon: 'spell_shadow_shadowbolt.jpg',
  },
  GLYPH_OF_VERDANT_SPHERES: {
    type: 'glyph',
    id: 56241,
    glyphId: 275,
    glyphItemId: 42456,
    iconID: 463854,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Verdant Spheres',
    icon: 'inv_misc_enchantedpearlb.jpg',
  },
  GLYPH_OF_IMP_SWARM: {
    type: 'glyph',
    id: 56242,
    glyphId: 284,
    glyphItemId: 42465,
    iconID: 460856,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Imp Swarm',
    icon: 'ability_warlock_impoweredimp.jpg',
  },
  GLYPH_OF_FEAR: {
    type: 'glyph',
    id: 56244,
    glyphId: 277,
    glyphItemId: 42458,
    iconID: 136183,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Fear',
    icon: 'spell_shadow_possession.jpg',
  },
  GLYPH_OF_FELGUARD: {
    type: 'glyph',
    id: 56246,
    glyphId: 278,
    glyphItemId: 42459,
    iconID: 136216,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Felguard',
    icon: 'spell_shadow_summonfelguard.jpg',
  },
  GLYPH_OF_FALLING_METEOR: {
    type: 'glyph',
    id: 56247,
    glyphId: 292,
    glyphItemId: 42473,
    iconID: 135821,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Falling Meteor',
    icon: 'spell_fire_meteorstorm.jpg',
  },
  GLYPH_OF_HAND_OF_GULDAN: {
    type: 'glyph',
    id: 56248,
    glyphId: 272,
    glyphItemId: 42453,
    iconID: 535592,
    passive: true,
    hidden: 'always',
    name: "Glyph of Hand of Gul'dan",
    icon: 'ability_warlock_handofguldan.jpg',
  },
  GLYPH_OF_DEMON_TRAINING: {
    type: 'glyph',
    id: 56249,
    glyphId: 279,
    glyphItemId: 42460,
    iconID: 136217,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Demon Training',
    icon: 'spell_shadow_summonfelhunter.jpg',
  },
  GLYPH_OF_CARRION_SWARM: {
    type: 'glyph',
    id: 56250,
    glyphId: 290,
    glyphItemId: 42471,
    iconID: 236293,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Carrion Swarm',
    icon: 'ability_warlock_demonicpower.jpg',
  },
  GLYPH_OF_SOUL_CONSUMPTION: {
    type: 'glyph',
    id: 58070,
    glyphId: 478,
    glyphItemId: 43390,
    iconID: 460700,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Soul Consumption',
    icon: 'ability_warlock_soulsiphon.jpg',
  },
  GLYPH_OF_UNENDING_BREATH: {
    type: 'glyph',
    id: 58079,
    glyphId: 477,
    glyphItemId: 43389,
    iconID: 136148,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Unending Breath',
    icon: 'spell_shadow_demonbreath.jpg',
  },
  GLYPH_OF_CURSE_OF_EXHAUSTION: {
    type: 'glyph',
    id: 58080,
    glyphId: 480,
    glyphItemId: 43392,
    iconID: 136162,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Curse of Exhaustion',
    icon: 'spell_shadow_grimward.jpg',
  },
  GLYPH_OF_EYE_OF_KILROGG: {
    type: 'glyph',
    id: 58081,
    glyphId: 479,
    glyphItemId: 43391,
    iconID: 136155,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Eye of Kilrogg',
    icon: 'spell_shadow_evileye.jpg',
  },
  GLYPH_OF_SOULWELL: {
    type: 'glyph',
    id: 58094,
    glyphId: 482,
    glyphItemId: 43394,
    iconID: 136194,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Soulwell',
    icon: 'spell_shadow_shadesofdarkness.jpg',
  },
  GLYPH_OF_SUBJUGATE_DEMON: {
    type: 'glyph',
    id: 58107,
    glyphId: 481,
    glyphItemId: 43393,
    iconID: 136154,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Subjugate Demon',
    icon: 'spell_shadow_enslavedemon.jpg',
  },
  SIPHON_LIFE: {
    id: 63106,
    type: 'baseline',
    iconID: 136188,
    passive: false,
    hidden: 'unless-learned',
    name: 'Siphon Life',
    icon: 'spell_shadow_requiem.jpg',
  },
  GLYPH_OF_DRAIN_LIFE: {
    type: 'glyph',
    id: 63302,
    glyphId: 755,
    glyphItemId: 45779,
    iconID: 136169,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Drain Life',
    icon: 'spell_shadow_lifedrain02.jpg',
  },
  GLYPH_OF_DEMON_HUNTING: {
    type: 'glyph',
    id: 63303,
    glyphId: 756,
    glyphItemId: 45780,
    iconID: 136172,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Demon Hunting',
    icon: 'spell_shadow_metamorphosis.jpg',
  },
  GLYPH_OF_EMBER_TAP: {
    type: 'glyph',
    id: 63304,
    glyphId: 757,
    glyphItemId: 45781,
    iconID: 514016,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Ember Tap',
    icon: 'inv_ember.jpg',
  },
  GLYPH_OF_DEMONIC_CIRCLE: {
    type: 'glyph',
    id: 63309,
    glyphId: 758,
    glyphItemId: 45782,
    iconID: 237560,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Demonic Circle',
    icon: 'spell_shadow_demoniccircleteleport.jpg',
  },
  GLYPH_OF_CRIMSON_BANISH: {
    type: 'glyph',
    id: 63312,
    glyphId: 761,
    glyphItemId: 45789,
    iconID: 136135,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Crimson Banish',
    icon: 'spell_shadow_cripple.jpg',
  },
  GLYPH_OF_LIFE_TAP: {
    type: 'glyph',
    id: 63320,
    glyphId: 760,
    glyphItemId: 45785,
    iconID: 136126,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Life Tap',
    icon: 'spell_shadow_burningspirit.jpg',
  },
  MASTERY_MASTER_DEMONOLOGIST_PASSIVE: {
    id: 77219,
    type: 'baseline',
    iconID: 136203,
    passive: true,
    name: 'Mastery: Master Demonologist',
    icon: 'spell_shadow_shadowpact.jpg',
  },
  FEL_FLAME: {
    id: 77799,
    type: 'baseline',
    iconID: 135795,
    passive: false,
    name: 'Fel Flame',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'spell_fire_felfirenova.jpg',
  },
  DARK_SOUL: {
    id: 77801,
    type: 'baseline',
    iconID: 463284,
    passive: false,
    hidden: 'unless-learned',
    name: 'Dark Soul',
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'spell_warlock_demonsoul.jpg',
  },
  NETHERMANCY_PASSIVE: {
    id: 86091,
    type: 'baseline',
    iconID: 132870,
    passive: true,
    name: 'Nethermancy',
    icon: 'inv_enchant_essencenetherlarge.jpg',
  },
  SUPPRESSION_HIDDEN: {
    id: 87330,
    type: 'baseline',
    iconID: 136154,
    passive: true,
    hidden: 'always',
    name: 'Suppression',
    icon: 'spell_shadow_enslavedemon.jpg',
  },
  CONTROL_DEMON_PASSIVE: {
    id: 93375,
    type: 'baseline',
    iconID: 136154,
    passive: true,
    name: 'Control Demon',
    icon: 'spell_shadow_enslavedemon.jpg',
  },
  CONTROL_DEMON_HIDDEN: {
    id: 93376,
    type: 'learned',
    taughtBy: 93375,
    iconID: 136154,
    passive: false,
    hidden: 'always',
    name: 'Control Demon',
    icon: 'spell_shadow_enslavedemon.jpg',
  },
  THE_CODEX_OF_XERRATH_PASSIVE: {
    id: 101508,
    type: 'baseline',
    iconID: 666475,
    passive: true,
    name: 'The Codex of Xerrath',
    icon: 'inv_misc_codexofxerrath_nochains.jpg',
  },
  SOUL_HARVEST_PASSIVE: {
    id: 101976,
    type: 'baseline',
    iconID: 236223,
    passive: true,
    name: 'Soul Harvest',
    icon: 'ability_mage_potentspirit.jpg',
  },
  VOIDWALKER_SUFFERING_PASSIVE: {
    id: 103128,
    type: 'baseline',
    iconID: 136123,
    passive: true,
    name: 'Voidwalker: Suffering',
    icon: 'spell_shadow_blackplague.jpg',
  },
  FELGUARD_PURSUIT_PASSIVE: {
    id: 103129,
    type: 'baseline',
    iconID: 132307,
    passive: true,
    name: 'Felguard: Pursuit',
    icon: 'ability_rogue_sprint.jpg',
  },
  VOIDWALKER_SHADOW_SHIELD_PASSIVE: {
    id: 103130,
    type: 'baseline',
    iconID: 132851,
    passive: true,
    name: 'Voidwalker: Shadow Shield',
    icon: 'inv_elemental_primal_shadow.jpg',
  },
  FELGUARD_AXE_TOSS_PASSIVE: {
    id: 103131,
    type: 'baseline',
    iconID: 236316,
    passive: true,
    name: 'Felguard: Axe Toss',
    icon: 'ability_warrior_titansgrip.jpg',
  },
  IMP_FLEE_PASSIVE: {
    id: 103133,
    type: 'baseline',
    iconID: 236171,
    passive: true,
    name: 'Imp: Flee',
    icon: 'ability_heroicleap.jpg',
  },
  FELGUARD_FELSTORM_PASSIVE: {
    id: 103134,
    type: 'baseline',
    iconID: 236303,
    passive: true,
    name: 'Felguard: Felstorm',
    icon: 'ability_warrior_bladestorm.jpg',
  },
  FELHUNTER_SPELL_LOCK_PASSIVE: {
    id: 103135,
    type: 'baseline',
    iconID: 136174,
    passive: true,
    name: 'Felhunter: Spell Lock',
    icon: 'spell_shadow_mindrot.jpg',
  },
  FELHUNTER_DEVOUR_MAGIC_PASSIVE: {
    id: 103136,
    type: 'baseline',
    iconID: 135894,
    passive: true,
    name: 'Felhunter: Devour Magic',
    icon: 'spell_holy_dispelmagic.jpg',
  },
  SUCCUBUS_SEDUCTION_PASSIVE: {
    id: 103139,
    type: 'baseline',
    iconID: 136175,
    passive: true,
    name: 'Succubus: Seduction',
    icon: 'spell_shadow_mindsteal.jpg',
  },
  SUCCUBUS_LESSER_INVISIBILITY_PASSIVE: {
    id: 103140,
    type: 'baseline',
    iconID: 135994,
    passive: true,
    name: 'Succubus: Lesser Invisibility',
    icon: 'spell_magic_lesserinvisibilty.jpg',
  },
  SUCCUBUS_WHIPLASH_PASSIVE: {
    id: 103141,
    type: 'baseline',
    iconID: 460858,
    passive: true,
    name: 'Succubus: Whiplash',
    icon: 'ability_warlock_whiplash.jpg',
  },
  VOIDWALKER_SHADOW_BULWARK_PASSIVE: {
    id: 103142,
    type: 'baseline',
    iconID: 136121,
    passive: true,
    name: 'Voidwalker: Shadow Bulwark',
    icon: 'spell_shadow_antishadow.jpg',
  },
  IMP_SINGE_MAGIC_PASSIVE: {
    id: 103150,
    type: 'baseline',
    iconID: 135791,
    passive: true,
    name: 'Imp: Singe Magic',
    icon: 'spell_fire_elementaldevastation.jpg',
  },
  METAMORPHOSIS: {
    id: 103958,
    type: 'baseline',
    iconID: 237558,
    passive: false,
    name: 'Metamorphosis',
    cooldown: {
      duration: 10000,
      hasted: false,
    },
    icon: 'spell_shadow_demonform.jpg',
  },
  CARRION_SWARM: {
    id: 103967,
    type: 'baseline',
    iconID: 236293,
    passive: false,
    name: 'Carrion Swarm',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 12000,
      hasted: false,
    },
    icon: 'ability_warlock_demonicpower.jpg',
  },
  DEMONIC_FURY_PASSIVE: {
    id: 104315,
    type: 'baseline',
    iconID: 236295,
    castableWhileCasting: true,
    passive: true,
    name: 'Demonic Fury',
    icon: 'ability_warlock_eradication.jpg',
  },
  IMP_SWARM: {
    id: 104316,
    type: 'learned',
    taughtBy: 56242,
    iconID: 460856,
    passive: false,
    hidden: 'unless-learned',
    name: 'Imp Swarm',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'ability_warlock_impoweredimp.jpg',
  },
  UNENDING_RESOLVE_GLYPH: {
    id: 148688,
    grantedBy: 148683,
    type: 'temporary',
    overrides: 104773,
    iconID: 136150,
    passive: true,
    name: 'Unending Resolve',
    icon: 'spell_shadow_demonictactics.jpg',
  },
  UNENDING_RESOLVE: {
    id: 104773,
    type: 'baseline',
    iconID: 136150,
    passive: false,
    name: 'Unending Resolve',
    cooldown: {
      duration: 180000,
      hasted: false,
      modifiers: [
        {
          duration: -60000,
          hasted: false,
          requiredSpells: [146964],
        },
      ],
    },
    icon: 'spell_shadow_demonictactics.jpg',
  },
  FEL_ARMOR_PASSIVE: {
    id: 104938,
    type: 'baseline',
    iconID: 136156,
    passive: true,
    name: 'Fel Armor',
    icon: 'spell_shadow_felarmour.jpg',
  },
  HAND_OF_GULDAN: {
    id: 105174,
    type: 'baseline',
    iconID: 535592,
    passive: false,
    name: "Hand of Gul'dan",
    gcd: {
      duration: 1500,
      hasted: true,
    },
    charges: {
      max: 2,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
    icon: 'ability_warlock_handofguldan.jpg',
  },
  DARK_REGENERATION_TALENT: {
    id: 108359,
    type: 'mists-talent',
    row: 0,
    column: 1,
    iconID: 537516,
    passive: false,
    hidden: 'unless-learned',
    name: 'Dark Regeneration',
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'spell_warlock_darkregeneration.jpg',
  },
  SOUL_LEECH: {
    id: 108366,
    type: 'baseline',
    iconID: 571320,
    passive: false,
    hidden: 'unless-learned',
    name: 'Soul Leech',
    icon: 'warlock_siphonlife.jpg',
  },
  SOUL_LEECH_TALENT: {
    id: 108370,
    type: 'mists-talent',
    row: 0,
    column: 2,
    iconID: 571320,
    passive: true,
    hidden: 'unless-learned',
    name: 'Soul Leech',
    icon: 'warlock_siphonlife.jpg',
  },
  HARVEST_LIFE_TALENT: {
    id: 108371,
    type: 'mists-talent',
    row: 0,
    column: 3,
    iconID: 537517,
    passive: true,
    hidden: 'unless-learned',
    name: 'Harvest Life',
    icon: 'spell_warlock_harvestoflife.jpg',
  },
  MORTAL_COIL: {
    id: 108396,
    type: 'baseline',
    iconID: 607853,
    passive: false,
    hidden: 'unless-learned',
    name: 'Mortal Coil',
    icon: 'ability_warlock_mortalcoil.jpg',
  },
  SOUL_LINK_TALENT: {
    id: 108415,
    type: 'mists-talent',
    row: 2,
    column: 1,
    iconID: 607854,
    passive: true,
    hidden: 'unless-learned',
    name: 'Soul Link',
    icon: 'ability_warlock_soullink.jpg',
  },
  SACRIFICIAL_PACT_TALENT: {
    id: 108416,
    type: 'mists-talent',
    row: 2,
    column: 2,
    iconID: 538538,
    passive: false,
    hidden: 'unless-learned',
    name: 'Sacrificial Pact',
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: 'warlock_sacrificial_pact.jpg',
  },
  UNBOUND_WILL_TALENT: {
    id: 108482,
    type: 'mists-talent',
    row: 3,
    column: 3,
    iconID: 571321,
    castableWhileCasting: true,
    passive: false,
    hidden: 'unless-learned',
    name: 'Unbound Will',
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: 'warlock_spelldrain.jpg',
  },
  GRIMOIRE_OF_SUPREMACY_TALENT: {
    id: 108499,
    type: 'mists-talent',
    row: 4,
    column: 1,
    iconID: 538442,
    passive: true,
    hidden: 'unless-learned',
    name: 'Grimoire of Supremacy',
    icon: 'warlock_grimoireofcommand.jpg',
  },
  GRIMOIRE_OF_SERVICE_TALENT: {
    id: 108501,
    type: 'mists-talent',
    row: 4,
    column: 2,
    iconID: 538444,
    passive: false,
    hidden: 'always',
    name: 'Grimoire of Service',
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'warlock_grimoireofservice.jpg',
  },
  GRIMOIRE_OF_SACRIFICE_TALENT: {
    id: 108503,
    type: 'mists-talent',
    row: 4,
    column: 3,
    iconID: 538443,
    passive: false,
    hidden: 'unless-learned',
    name: 'Grimoire of Sacrifice',
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 'warlock_grimoireofsacrifice.jpg',
  },
  ARCHIMONDES_DARKNESS_TALENT: {
    id: 108505,
    type: 'mists-talent',
    row: 5,
    column: 1,
    iconID: 236402,
    passive: true,
    name: "Archimonde's Darkness",
    icon: 'achievement_boss_archimonde-.jpg',
  },
  MANNOROTHS_FURY_TALENT: {
    id: 108508,
    type: 'mists-talent',
    row: 5,
    column: 3,
    iconID: 236423,
    castableWhileCasting: true,
    passive: false,
    hidden: 'unless-learned',
    name: "Mannoroth's Fury",
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: 'achievement_boss_magtheridon.jpg',
  },
  DEMONIC_REBIRTH_PASSIVE: {
    id: 108559,
    type: 'baseline',
    iconID: 136150,
    passive: true,
    name: 'Demonic Rebirth',
    icon: 'spell_shadow_demonictactics.jpg',
  },
  DECIMATION_PASSIVE: {
    id: 108869,
    type: 'baseline',
    iconID: 469753,
    passive: true,
    name: 'Decimation',
    icon: 'inv_wand_1h_firelandsraid_d_02.jpg',
  },
  DEMONIC_FURY_HIDDEN: {
    id: 109145,
    type: 'baseline',
    iconID: 236295,
    castableWhileCasting: true,
    passive: true,
    hidden: 'always',
    name: 'Demonic Fury',
    icon: 'ability_warlock_eradication.jpg',
  },
  DEMONIC_LEAP: {
    id: 109151,
    type: 'baseline',
    iconID: 132368,
    passive: false,
    name: 'Demonic Leap',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 10000,
      hasted: false,
    },
    icon: 'ability_warstomp.jpg',
  },
  CURSE_OF_ENFEEBLEMENT: {
    id: 109466,
    type: 'baseline',
    iconID: 615101,
    passive: false,
    name: 'Curse of Enfeeblement',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 0,
      hasted: false,
      modifiers: [
        {
          duration: 10000,
          hasted: false,
          requiredSpells: [103958],
        },
      ],
    },
    icon: 'warlock_curse_weakness.jpg',
  },
  DARK_INTENT: {
    id: 109773,
    type: 'baseline',
    iconID: 463285,
    passive: false,
    name: 'Dark Intent',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'spell_warlock_focusshadow.jpg',
  },
  METAMORPHOSIS_IMMOLATION_AURA_PASSIVE: {
    id: 109797,
    type: 'baseline',
    iconID: 460698,
    passive: true,
    name: 'Metamorphosis: Immolation Aura',
    icon: 'ability_warlock_inferno.jpg',
  },
  SYMBIOSIS: {
    id: 110505,
    type: 'baseline',
    iconID: 571587,
    passive: false,
    name: 'Symbiosis',
    icon: 'spell_druid_symbiosis.jpg',
  },
  DARK_BARGAIN_TALENT: {
    id: 110913,
    type: 'mists-talent',
    row: 2,
    column: 3,
    iconID: 538039,
    passive: false,
    hidden: 'unless-learned',
    name: 'Dark Bargain',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
    icon: 'ability_deathwing_bloodcorruption_death.jpg',
  },
  BLOOD_HORROR_TALENT: {
    id: 111397,
    type: 'mists-talent',
    row: 3,
    column: 1,
    iconID: 538040,
    passive: false,
    name: 'Blood Horror',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 'ability_deathwing_bloodcorruption_earth.jpg',
  },
  BURNING_RUSH_TALENT: {
    id: 111400,
    type: 'mists-talent',
    row: 3,
    column: 2,
    iconID: 538043,
    passive: false,
    name: 'Burning Rush',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'ability_deathwing_sealarmorbreachtga.jpg',
  },
  DEMONIC_GATEWAY_DEMONIC_GATEWAY: {
    id: 113890,
    grantedBy: 111771,
    type: 'temporary',
    iconID: 607513,
    castableWhileCasting: true,
    passive: false,
    name: 'Demonic Gateway',
    cooldown: {
      duration: 10000,
      hasted: false,
    },
    icon: 'spell_warlock_demonicportal_purple.jpg',
  },
  DEMONIC_GATEWAY: {
    id: 111771,
    type: 'baseline',
    iconID: 607512,
    passive: false,
    name: 'Demonic Gateway',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 10000,
      hasted: false,
    },
    castTime: {
      duration: 3000,
    },
    icon: 'spell_warlock_demonicportal_green.jpg',
  },
  GRIMOIRE_IMP: {
    id: 111859,
    type: 'learned',
    taughtBy: 108501,
    iconID: 136218,
    passive: false,
    name: 'Grimoire: Imp',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'spell_shadow_summonimp.jpg',
  },
  GRIMOIRE_VOIDWALKER: {
    id: 111895,
    type: 'learned',
    taughtBy: 108501,
    iconID: 136221,
    passive: false,
    name: 'Grimoire: Voidwalker',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'spell_shadow_summonvoidwalker.jpg',
  },
  GRIMOIRE_SUCCUBUS: {
    id: 111896,
    type: 'learned',
    taughtBy: 108501,
    iconID: 136220,
    passive: false,
    name: 'Grimoire: Succubus',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'spell_shadow_summonsuccubus.jpg',
  },
  GRIMOIRE_FELHUNTER: {
    id: 111897,
    type: 'learned',
    taughtBy: 108501,
    iconID: 136217,
    passive: false,
    name: 'Grimoire: Felhunter',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'spell_shadow_summonfelhunter.jpg',
  },
  GRIMOIRE_FELGUARD: {
    id: 111898,
    type: 'learned',
    taughtBy: 108501,
    iconID: 136216,
    passive: false,
    name: 'Grimoire: Felguard',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'spell_shadow_summonfelguard.jpg',
  },
  METAMORPHOSIS_TOUCH_OF_CHAOS_PASSIVE: {
    id: 112089,
    type: 'baseline',
    iconID: 237244,
    passive: true,
    name: 'Metamorphosis: Touch of Chaos',
    icon: 'inv_jewelcrafting_shadowspirit_02.jpg',
  },
  SUMMON_FEL_IMP: {
    id: 112866,
    grantedBy: 108499,
    type: 'temporary',
    overrides: 688,
    iconID: 615097,
    passive: false,
    name: 'Summon Fel Imp',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 5000,
    },
    icon: 'spell_warlock_summonimpoutland.jpg',
  },
  SUMMON_VOIDLORD: {
    id: 112867,
    grantedBy: 108499,
    type: 'temporary',
    overrides: 697,
    iconID: 538447,
    passive: false,
    name: 'Summon Voidlord',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 5000,
    },
    icon: 'warlock_summon_-voidlord.jpg',
  },
  SUMMON_SHIVARRA: {
    id: 112868,
    grantedBy: 108499,
    type: 'temporary',
    overrides: 712,
    iconID: 615148,
    passive: false,
    name: 'Summon Shivarra',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 5000,
    },
    icon: 'warlock_summon_-shivan.jpg',
  },
  SUMMON_OBSERVER: {
    id: 112869,
    grantedBy: 108499,
    type: 'temporary',
    overrides: 691,
    iconID: 538445,
    passive: false,
    name: 'Summon Observer',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 5000,
    },
    icon: 'warlock_summon_-beholder.jpg',
  },
  SUMMON_WRATHGUARD: {
    id: 112870,
    grantedBy: 108499,
    type: 'temporary',
    overrides: 30146,
    iconID: 615025,
    passive: false,
    hidden: 'unless-learned',
    name: 'Summon Wrathguard',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 5000,
    },
    icon: 'spell_warlock_summonwrathguard.jpg',
  },
  UNKNOWN: {
    id: 112891,
    grantedBy: 5484,
    type: 'temporary',
    passive: false,
    name: 'Unknown',
    icon: 'inv_axe_02.jpg',
  },
  SUMMON_ABYSSAL_GRIMOIRE_OF_SUPREMACY_TALENT: {
    id: 112921,
    grantedBy: 108499,
    type: 'temporary',
    overrides: 1122,
    iconID: 524350,
    passive: false,
    name: 'Summon Abyssal',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 600000,
      hasted: false,
    },
    icon: 'achievement_boss_lordanthricyst.jpg',
  },
  SUMMON_ABYSSAL_THE_CODEX_OF_XERRATH_PASSIVE: {
    id: 140763,
    grantedBy: 101508,
    type: 'temporary',
    overrides: 112921,
    iconID: 840189,
    passive: false,
    name: 'Summon Abyssal',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 600000,
      hasted: false,
    },
    icon: 'ability_boss_lordanthricystgreen.jpg',
  },
  SUMMON_TERRORGUARD_SUMMON_TERRORGUARD: {
    id: 112926,
    grantedBy: 112927,
    type: 'temporary',
    iconID: 615098,
    passive: false,
    name: 'Summon Terrorguard',
    icon: 'spell_warlock_summonterrorguard.jpg',
  },
  SUMMON_TERRORGUARD_GRIMOIRE_OF_SUPREMACY_TALENT: {
    id: 112927,
    grantedBy: 108499,
    type: 'temporary',
    overrides: 18540,
    iconID: 615098,
    passive: false,
    name: 'Summon Terrorguard',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 600000,
      hasted: false,
    },
    icon: 'spell_warlock_summonterrorguard.jpg',
  },
  DARK_SOUL_KNOWLEDGE: {
    id: 113861,
    type: 'baseline',
    overrides: 77801,
    iconID: 463284,
    passive: false,
    name: 'Dark Soul: Knowledge',
    charges: {
      max: 0,
      modifiers: [
        {
          max: 2,
          requiredSpells: [108505],
        },
      ],
    },
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'spell_warlock_demonsoul.jpg',
  },
  NETHER_PLATING_PASSIVE: {
    id: 114129,
    type: 'baseline',
    iconID: 443382,
    passive: true,
    name: 'Nether Plating',
    icon: 'inv_misc_deepseascales.jpg',
  },
  DARK_APOTHEOSIS: {
    id: 114168,
    type: 'learned',
    taughtBy: 63303,
    iconID: 136172,
    passive: false,
    hidden: 'unless-learned',
    name: 'Dark Apotheosis',
    cooldown: {
      duration: 10000,
      hasted: false,
    },
    icon: 'spell_shadow_metamorphosis.jpg',
  },
  WILD_IMPS_PASSIVE: {
    id: 114592,
    type: 'baseline',
    iconID: 460856,
    castableWhileCasting: true,
    passive: true,
    name: 'Wild Imps',
    icon: 'ability_warlock_impoweredimp.jpg',
  },
  DISRUPTED_NETHER: {
    id: 114736,
    grantedBy: 104316,
    type: 'temporary',
    iconID: 236300,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Disrupted Nether',
    icon: 'ability_warlock_improvedsoulleech.jpg',
  },
  SEED_OF_CORRUPTION_1: {
    id: 114790,
    type: 'baseline',
    iconID: 136193,
    passive: false,
    hidden: 'unless-learned',
    name: 'Seed of Corruption',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 2000,
    },
    icon: 'spell_shadow_seedofdestruction.jpg',
  },
  SEED_OF_CORRUPTION_2: {
    id: 132566,
    type: 'baseline',
    iconID: 136193,
    passive: false,
    hidden: 'unless-learned',
    name: 'Seed of Corruption',
    icon: 'spell_shadow_seedofdestruction.jpg',
  },
  METAMORPHOSIS_CURSED_AURAS_PASSIVE: {
    id: 116208,
    type: 'baseline',
    iconID: 136192,
    passive: true,
    name: 'Metamorphosis: Cursed Auras',
    icon: 'spell_shadow_sealofkings.jpg',
  },
  SOUL_SWAP: {
    id: 119678,
    type: 'baseline',
    iconID: 460857,
    passive: false,
    hidden: 'unless-learned',
    name: 'Soul Swap',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'ability_warlock_soulswap.jpg',
  },
  FURY_WARD: {
    id: 119839,
    grantedBy: 114168,
    type: 'temporary',
    overrides: 6229,
    iconID: 463829,
    passive: false,
    name: 'Fury Ward',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    charges: {
      max: 2,
    },
    cooldown: {
      duration: 10000,
      hasted: false,
    },
    icon: 'ability_toughness.jpg',
  },
  COMMAND_DEMON: {
    id: 119898,
    type: 'baseline',
    iconID: 236292,
    castableWhileCasting: true,
    passive: false,
    name: 'Command Demon',
    icon: 'ability_warlock_demonicempowerment.jpg',
  },
  MOLTEN_CORE_PASSIVE: {
    id: 122351,
    type: 'baseline',
    iconID: 236301,
    passive: true,
    name: 'Molten Core',
    icon: 'ability_warlock_moltencore.jpg',
  },
  IMP_CAUTERIZE_MASTER_PASSIVE: {
    id: 124538,
    type: 'baseline',
    iconID: 463567,
    passive: true,
    name: 'Imp: Cauterize Master',
    icon: 'inv_misc_volatilefire.jpg',
  },
  VOIDWALKER_DISARM_PASSIVE: {
    id: 124539,
    type: 'baseline',
    iconID: 132343,
    passive: true,
    name: 'Voidwalker: Disarm',
    icon: 'ability_warrior_disarm.jpg',
  },
  METAMORPHOSIS_DOOM_PASSIVE: {
    id: 124913,
    type: 'baseline',
    iconID: 136122,
    passive: true,
    name: 'Metamorphosis: Doom',
    icon: 'spell_shadow_auraofdarkness.jpg',
  },
  METAMORPHOSIS_CHAOS_WAVE_PASSIVE: {
    id: 124917,
    type: 'baseline',
    iconID: 607850,
    passive: true,
    name: 'Metamorphosis: Chaos Wave',
    icon: 'ability_warlock_coil2.jpg',
  },
  METAMORPHOSIS_VOID_RAY_PASSIVE: {
    id: 129343,
    type: 'baseline',
    iconID: 425958,
    passive: true,
    name: 'Metamorphosis: Void Ray',
    icon: 'spell_fire_twilightnova.jpg',
  },
  UNSTABLE_AFFLICTION: {
    id: 131736,
    type: 'baseline',
    iconID: 136228,
    castableWhileCasting: true,
    passive: false,
    hidden: 'unless-learned',
    name: 'Unstable Affliction',
    castTime: {
      duration: 1500,
    },
    icon: 'spell_shadow_unstableaffliction_3.jpg',
  },
  AGONY: {
    id: 131737,
    type: 'baseline',
    iconID: 136139,
    castableWhileCasting: true,
    passive: false,
    hidden: 'unless-learned',
    name: 'Agony',
    icon: 'spell_shadow_curseofsargeras.jpg',
  },
  PANDEMIC_PASSIVE: {
    id: 131973,
    type: 'baseline',
    iconID: 136180,
    passive: true,
    name: 'Pandemic',
    icon: 'spell_shadow_painfulafflictions.jpg',
  },
  GLYPH_OF_SUPERNOVA: {
    type: 'glyph',
    id: 135032,
    glyphId: 1057,
    glyphItemId: 93197,
    iconID: 525026,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Supernova',
    icon: 'spell_fire_ragnaros_supernova.jpg',
  },
  GLYPH_OF_GATEWAY_ATTUNEMENT: {
    type: 'glyph',
    id: 135557,
    glyphId: 1058,
    glyphItemId: 93202,
    iconID: 607512,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Gateway Attunement',
    icon: 'spell_warlock_demonicportal_green.jpg',
  },
  HOTFIX_PASSIVE_HIDDEN_1: {
    id: 137042,
    type: 'baseline',
    iconID: 236216,
    passive: true,
    hidden: 'always',
    name: 'Hotfix Passive',
    icon: 'ability_mage_firestarter.jpg',
  },
  HOTFIX_PASSIVE_HIDDEN_2: {
    id: 137044,
    type: 'baseline',
    iconID: 236216,
    passive: true,
    hidden: 'always',
    name: 'Hotfix Passive',
    icon: 'ability_mage_firestarter.jpg',
  },
  THE_CODEX_OF_XERRATH_HIDDEN: {
    id: 137206,
    type: 'baseline',
    iconID: 666475,
    passive: true,
    hidden: 'always',
    name: 'The Codex of Xerrath',
    icon: 'inv_misc_codexofxerrath_nochains.jpg',
  },
  KILJAEDENS_CUNNING_TALENT: {
    id: 137587,
    type: 'mists-talent',
    row: 5,
    column: 2,
    iconID: 236418,
    passive: true,
    hidden: 'unless-learned',
    name: "Kil'jaeden's Cunning",
    icon: 'achievement_boss_kiljaedan.jpg',
  },
  GLYPH_OF_HAVOC: {
    type: 'glyph',
    id: 146962,
    glyphId: 1071,
    glyphItemId: 104054,
    iconID: 460695,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Havoc',
    icon: 'ability_warlock_baneofhavoc.jpg',
  },
  GLYPH_OF_CURSE_OF_THE_ELEMENTS: {
    type: 'glyph',
    id: 146963,
    glyphId: 283,
    glyphItemId: 42464,
    iconID: 615099,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Curse of the Elements',
    icon: 'warlock_curse_shadow.jpg',
  },
  GLYPH_OF_UNENDING_RESOLVE: {
    type: 'glyph',
    id: 146964,
    glyphId: 759,
    glyphItemId: 45783,
    iconID: 136150,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Unending Resolve',
    icon: 'spell_shadow_demonictactics.jpg',
  },
  GLYPH_OF_ETERNAL_RESOLVE: {
    type: 'glyph',
    id: 148683,
    glyphId: 911,
    glyphItemId: 50077,
    iconID: 136150,
    passive: true,
    hidden: 'always',
    name: 'Glyph of Eternal Resolve',
    icon: 'spell_shadow_demonictactics.jpg',
  },
} as const satisfies Record<string, RetailSpell & { icon: string }>;
export default SPELLS;
