import SPELLS from 'common/SPELLS';
import TALENTS from 'common/TALENTS/shaman';
import CoreAlwaysBeCastingHealing from 'parser/shared/modules/AlwaysBeCastingHealing';

class AlwaysBeCasting extends CoreAlwaysBeCastingHealing {
  HEALING_ABILITIES_ON_GCD = [
    SPELLS.HEALING_WAVE.id,
    TALENTS.CHAIN_HEAL_TALENT.id,
    SPELLS.HEALING_SURGE.id,
    TALENTS.RIPTIDE_TALENT.id,
    TALENTS.HEALING_RAIN_TALENT.id,
    TALENTS.HEALING_STREAM_TOTEM_SHARED_TALENT.id,
    TALENTS.HEALING_TIDE_TOTEM_TALENT.id,
    TALENTS.SPIRIT_LINK_TOTEM_TALENT.id,
    TALENTS.WELLSPRING_TALENT.id,
    TALENTS.CLOUDBURST_TOTEM_TALENT.id,
    TALENTS.EARTHEN_WALL_TOTEM_TALENT.id,
    TALENTS.UNLEASH_LIFE_TALENT.id,
    TALENTS.EARTH_SHIELD_TALENT.id,
    TALENTS.DOWNPOUR_TALENT.id,
  ];
}

export default AlwaysBeCasting;
