//hots
export const ECHO_BASE_DURATION = 15000;
export const REVERSION_BASE_DURATION = 12000;
export const DREAM_BREATH_MIN_DURATION = 4000;
export const DREAM_BREATH_MAX_DURATION = 16000;

//talents
export const TIMELESS_MAGIC = 0.15;
export const EMPATH_REGEN_FACTOR = 1;
export const FLOW_STATE_FACTOR = 0.1;
export const GRACE_PERIOD_INCREASE = 0.05;
export const CALL_OF_YSERA_DREAM_BREATH_INCREASE = 0.4;
export const CALL_OF_YSERA_DREAM_LIVING_FLAME_INCREASE = 1;
