import type { RetailSpell } from 'wow-dbc';
const SPELLS = {
  UNKNOWN_TALENT: {
    id: 0,
    granted: false,
    requiresTalentEntry: [112820],
    type: 'talent',
    passive: false,
    name: 'Unknown',
    icon: 'inv_axe_02.jpg',
  },
  GLIDE: {
    id: 131347,
    type: 'baseline',
    iconID: 1305157,
    passive: false,
    name: 'Glide',
    cooldown: {
      duration: 1000,
      hasted: false,
    },
    icon: 'ability_demonhunter_glide.jpg',
  },
  DEMONS_BITE_DEMONS_BITE: {
    id: 162243,
    grantedBy: 344859,
    type: 'temporary',
    iconID: 135561,
    passive: false,
    hidden: 'unless-learned',
    name: "Demon's Bite",
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'inv_weapon_glave_01.jpg',
  },
  DEMONS_BITE: {
    id: 344859,
    type: 'baseline',
    iconID: 135561,
    passive: false,
    name: "Demon's Bite",
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'inv_weapon_glave_01.jpg',
  },
  METAMORPHOSIS_METAMORPHOSIS: {
    id: 162264,
    grantedBy: 191427,
    type: 'temporary',
    iconID: 1247262,
    passive: false,
    name: 'Metamorphosis',
    icon: 'ability_demonhunter_metamorphasisdps.jpg',
  },
  METAMORPHOSIS_VOID_METAMORPHOSIS: {
    id: 201453,
    grantedBy: 1217605,
    type: 'temporary',
    iconID: 135561,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Metamorphosis',
    icon: 'inv_weapon_glave_01.jpg',
  },
  METAMORPHOSIS: {
    id: 191427,
    type: 'baseline',
    iconID: 1247262,
    passive: false,
    name: 'Metamorphosis',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'ability_demonhunter_metamorphasisdps.jpg',
  },
  STAT_NEGATION_AURA_INTELLECT_DPS_HIDDEN: {
    id: 162699,
    type: 'baseline',
    iconID: 136243,
    passive: true,
    hidden: 'always',
    name: 'Stat Negation Aura - Intellect DPS',
    icon: 'trade_engineering.jpg',
  },
  DISRUPT: {
    id: 183752,
    type: 'baseline',
    iconID: 1305153,
    passive: false,
    name: 'Disrupt',
    cooldown: {
      duration: 15000,
      hasted: false,
    },
    icon: 'ability_demonhunter_consumemagic.jpg',
  },
  DISRUPTING_FURY_TALENT: {
    id: 183782,
    granted: false,
    requiresTalentEntry: [112848],
    type: 'talent',
    iconID: 1305153,
    passive: true,
    hidden: 'always',
    name: 'Disrupting Fury',
    icon: 'ability_demonhunter_consumemagic.jpg',
  },
  THROW_GLAIVE_THROW_GLAIVE: {
    id: 337819,
    grantedBy: 185123,
    type: 'temporary',
    iconID: 1305159,
    castableWhileCasting: true,
    passive: false,
    name: 'Throw Glaive',
    icon: 'ability_demonhunter_throwglaive.jpg',
  },
  THROW_GLAIVE: {
    id: 185123,
    type: 'baseline',
    iconID: 1305159,
    passive: false,
    name: 'Throw Glaive',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    charges: {
      max: 1,
      modifiers: [
        {
          max: 1,
          requiredSpells: [389763],
        },
        {
          max: 1,
          requiredSpells: [429211],
        },
      ],
    },
    cooldown: {
      duration: 9000,
      hasted: true,
    },
    icon: 'ability_demonhunter_throwglaive.jpg',
  },
  TORMENT: {
    id: 185245,
    type: 'baseline',
    iconID: 1344654,
    passive: false,
    name: 'Torment',
    charges: {
      max: 1,
      modifiers: [
        {
          max: 1,
          requiredSpells: [1253402],
        },
      ],
    },
    cooldown: {
      duration: 8000,
      hasted: false,
    },
    icon: 'ability_demonhunter_torment.jpg',
  },
  ENERGY_REGEN_HIDDEN: {
    id: 186452,
    type: 'baseline',
    iconID: 136183,
    passive: true,
    hidden: 'always',
    name: 'Energy Regen',
    icon: 'spell_shadow_possession.jpg',
  },
  SPECTRAL_SIGHT_BASELINE: {
    id: 188501,
    type: 'baseline',
    iconID: 1247266,
    passive: false,
    name: 'Spectral Sight',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 0,
      hasted: false,
      modifiers: [
        {
          duration: -5000,
          hasted: false,
          requiredSpells: [389849],
        },
      ],
    },
    icon: 'ability_demonhunter_spectralsight.jpg',
  },
  SPECTRAL_SIGHT: {
    id: 1251417,
    type: 'baseline',
    overrides: 188501,
    iconID: 1247266,
    passive: false,
    name: 'Spectral Sight',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 0,
      hasted: false,
      modifiers: [
        {
          duration: -5000,
          hasted: false,
          requiredSpells: [389849],
        },
      ],
    },
    icon: 'ability_demonhunter_spectralsight.jpg',
  },
  SPECTRAL_SIGHT_1: {
    id: 202688,
    grantedBy: 1251417,
    type: 'temporary',
    iconID: 1247266,
    passive: false,
    name: 'Spectral Sight',
    icon: 'ability_demonhunter_spectralsight.jpg',
  },
  SPECTRAL_SIGHT_2: {
    id: 215725,
    grantedBy: 1251417,
    type: 'temporary',
    iconID: 1247266,
    passive: false,
    name: 'Spectral Sight',
    icon: 'ability_demonhunter_spectralsight.jpg',
  },
  SPECTRAL_SIGHT_3: {
    id: 1251707,
    grantedBy: 1251417,
    type: 'temporary',
    iconID: 136194,
    passive: false,
    hidden: 'always',
    name: 'Spectral Sight',
    icon: 'spell_shadow_shadesofdarkness.jpg',
  },
  FEL_RUSH_FEL_RUSH: {
    id: 195072,
    grantedBy: 344865,
    type: 'temporary',
    iconID: 1247261,
    passive: false,
    name: 'Fel Rush',
    gcd: {
      duration: 500,
      hasted: false,
    },
    charges: {
      max: 1,
      modifiers: [
        {
          max: 1,
          requiredSpells: [320416],
        },
      ],
    },
    cooldown: {
      duration: 10000,
      hasted: false,
    },
    icon: 'ability_demonhunter_felrush.jpg',
  },
  FEL_RUSH: {
    id: 344865,
    type: 'baseline',
    iconID: 1247261,
    passive: false,
    name: 'Fel Rush',
    gcd: {
      duration: 250,
      hasted: false,
    },
    charges: {
      max: 1,
      modifiers: [
        {
          max: 1,
          requiredSpells: [320416],
        },
      ],
    },
    cooldown: {
      duration: 10000,
      hasted: false,
    },
    icon: 'ability_demonhunter_felrush.jpg',
  },
  DOUBLE_JUMP_PASSIVE: {
    id: 196055,
    type: 'baseline',
    iconID: 132296,
    passive: true,
    name: 'Double Jump',
    icon: 'ability_rogue_fleetfooted.jpg',
  },
  DARKNESS_TALENT: {
    id: 196718,
    granted: false,
    requiresTalentEntry: [112921],
    type: 'talent',
    iconID: 1305154,
    passive: false,
    name: 'Darkness',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 300000,
      hasted: false,
      modifiers: [
        {
          duration: -120000,
          hasted: false,
          requiredSpells: [389783],
        },
      ],
    },
    icon: 'ability_demonhunter_darkness.jpg',
  },
  GLIDE_HIDDEN: {
    id: 197130,
    type: 'baseline',
    iconID: 136203,
    passive: true,
    hidden: 'always',
    name: 'Glide',
    icon: 'spell_shadow_shadowpact.jpg',
  },
  BLUR_BLUR: {
    id: 212800,
    grantedBy: 198589,
    type: 'temporary',
    iconID: 1305150,
    passive: false,
    name: 'Blur',
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: 'ability_demonhunter_blur.jpg',
  },
  BLUR: {
    id: 198589,
    type: 'baseline',
    iconID: 1305150,
    passive: false,
    hidden: 'unless-learned',
    name: 'Blur',
    charges: {
      max: 1,
      modifiers: [
        {
          max: 1,
          requiredSpells: [1266307],
        },
      ],
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: 'ability_demonhunter_blur.jpg',
  },
  ANNIHILATION: {
    id: 201427,
    grantedBy: 162264,
    type: 'temporary',
    iconID: 1303275,
    passive: false,
    name: 'Annihilation',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'inv_glaive_1h_npc_d_02.jpg',
  },
  FURY_OF_THE_ILLIDARI_1: {
    id: 201467,
    type: 'baseline',
    iconID: 1117778,
    passive: false,
    name: 'Fury of the Illidari',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: 'inv_glaive_1h_artifactazgalor_d_01.jpg',
  },
  FURY_OF_THE_ILLIDARI_2: {
    id: 201628,
    type: 'baseline',
    iconID: 135774,
    castableWhileCasting: true,
    passive: false,
    name: 'Fury of the Illidari',
    icon: 'spell_deathknight_plaguestrike.jpg',
  },
  FURY_OF_THE_ILLIDARI_3: {
    id: 201789,
    type: 'baseline',
    iconID: 135774,
    castableWhileCasting: true,
    passive: false,
    name: 'Fury of the Illidari',
    icon: 'spell_deathknight_plaguestrike.jpg',
  },
  FELBLADE_HIDDEN_1: {
    id: 203557,
    type: 'learned',
    taughtBy: 1245412,
    iconID: 1344646,
    passive: true,
    hidden: 'always',
    name: 'Felblade',
    icon: 'ability_demonhunter_felblade.jpg',
  },
  FELBLADE_HIDDEN_2: {
    id: 236167,
    type: 'learned',
    taughtBy: 1245412,
    iconID: 1344646,
    passive: true,
    hidden: 'always',
    name: 'Felblade',
    icon: 'ability_demonhunter_felblade.jpg',
  },
  PARRY_HIDDEN: {
    id: 203724,
    type: 'baseline',
    iconID: 132269,
    passive: true,
    hidden: 'always',
    name: 'Parry',
    icon: 'ability_parry.jpg',
  },
  SIGIL_OF_FLAME: {
    id: 204596,
    type: 'baseline',
    iconID: 1344652,
    passive: false,
    name: 'Sigil of Flame',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    charges: {
      max: 1,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 'ability_demonhunter_sigilofinquisition.jpg',
  },
  SOUL_RENDING_TALENT: {
    id: 204909,
    granted: false,
    requiresTalentEntry: [112847],
    type: 'talent',
    iconID: 1354410,
    passive: true,
    hidden: 'always',
    name: 'Soul Rending',
    icon: 'ability_demonhunter_soulcleave2.jpg',
  },
  AURA_OF_PAIN_TALENT: {
    id: 207347,
    granted: false,
    requiresTalentEntry: [112844],
    type: 'talent',
    iconID: 135802,
    passive: true,
    hidden: 'always',
    name: 'Aura of Pain',
    icon: 'spell_fire_felimmolation.jpg',
  },
  SOUL_CARVER_SOUL_CARVER: {
    id: 214743,
    grantedBy: 207407,
    type: 'temporary',
    iconID: 1309072,
    passive: false,
    name: 'Soul Carver',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: 'inv_glaive_1h_artifactaldrochi_d_01.jpg',
  },
  SOUL_CARVER: {
    id: 207407,
    type: 'baseline',
    iconID: 1309072,
    passive: false,
    name: 'Soul Carver',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: 'inv_glaive_1h_artifactaldrochi_d_01.jpg',
  },
  DEATH_SWEEP: {
    id: 210152,
    grantedBy: 162264,
    type: 'temporary',
    iconID: 1309099,
    passive: false,
    name: 'Death Sweep',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 9000,
      hasted: true,
    },
    icon: 'inv_glaive_1h_artifactaldrochi_d_02dual.jpg',
  },
  DEMON_HUNTER_HIDDEN_1: {
    id: 212611,
    type: 'baseline',
    iconID: 1363130,
    passive: true,
    hidden: 'always',
    name: 'Demon Hunter',
    icon: 'crest_demonhunter.jpg',
  },
  DEMON_HUNTER_HIDDEN_2: {
    id: 462065,
    type: 'baseline',
    iconID: 136243,
    passive: true,
    hidden: 'always',
    name: 'Demon Hunter',
    icon: 'trade_engineering.jpg',
  },
  CHARRED_WARBLADES_TALENT: {
    id: 213010,
    granted: false,
    requiresTalentEntry: [112861],
    type: 'talent',
    iconID: 135818,
    passive: true,
    hidden: 'always',
    name: 'Charred Warblades',
    icon: 'spell_fire_incinerate.jpg',
  },
  IMPRISON_TALENT: {
    id: 217832,
    granted: false,
    requiresTalentEntry: [112927],
    type: 'talent',
    iconID: 1380368,
    passive: false,
    name: 'Imprison',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
    },
    icon: 'ability_demonhunter_imprison.jpg',
  },
  CHAOS_BRAND_PASSIVE: {
    id: 255260,
    type: 'baseline',
    iconID: 1450142,
    passive: true,
    name: 'Chaos Brand',
    icon: 'ability_demonhunter_empowerwards.jpg',
  },
  IMMOLATION_AURA: {
    id: 258920,
    type: 'baseline',
    iconID: 1344649,
    passive: false,
    name: 'Immolation Aura',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    charges: {
      max: 1,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 'ability_demonhunter_immolation.jpg',
  },
  CONSUME_MAGIC_TALENT: {
    id: 278326,
    granted: false,
    requiresTalentEntry: [112926],
    type: 'talent',
    iconID: 828455,
    passive: false,
    name: 'Consume Magic',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 10000,
      hasted: false,
    },
    icon: 'spell_misc_zandalari_council_soulswap.jpg',
  },
  SWALLOWED_ANGER_TALENT: {
    id: 320313,
    granted: false,
    requiresTalentEntry: [112925],
    type: 'talent',
    iconID: 828455,
    passive: true,
    hidden: 'always',
    name: 'Swallowed Anger',
    icon: 'spell_misc_zandalari_council_soulswap.jpg',
  },
  INFERNAL_ARMOR_TALENT: {
    id: 320331,
    granted: false,
    requiresTalentEntry: [112924],
    type: 'talent',
    iconID: 1344649,
    passive: true,
    hidden: 'always',
    name: 'Infernal Armor',
    icon: 'ability_demonhunter_immolation.jpg',
  },
  IMPROVED_DISRUPT_TALENT: {
    id: 320361,
    granted: false,
    requiresTalentEntry: [112849],
    type: 'talent',
    iconID: 1305153,
    passive: true,
    hidden: 'always',
    name: 'Improved Disrupt',
    icon: 'ability_demonhunter_consumemagic.jpg',
  },
  IMMOLATION_AURA_PASSIVE: {
    id: 320364,
    type: 'baseline',
    iconID: 1344649,
    passive: true,
    name: 'Immolation Aura',
    icon: 'ability_demonhunter_immolation.jpg',
  },
  SPECTRAL_SIGHT_PASSIVE: {
    id: 320379,
    type: 'baseline',
    iconID: 1247266,
    passive: true,
    name: 'Spectral Sight',
    icon: 'ability_demonhunter_spectralsight.jpg',
  },
  BOUNCING_GLAIVES_TALENT: {
    id: 320386,
    granted: false,
    requiresTalentEntry: [112841],
    type: 'talent',
    iconID: 1305159,
    passive: true,
    hidden: 'always',
    name: 'Bouncing Glaives',
    icon: 'ability_demonhunter_throwglaive.jpg',
  },
  BLAZING_PATH_TALENT: {
    id: 320416,
    granted: false,
    requiresTalentEntry: [117759],
    type: 'talent',
    iconID: 1247261,
    passive: true,
    hidden: 'always',
    name: 'Blazing Path',
    icon: 'ability_demonhunter_felrush.jpg',
  },
  IMPROVED_SIGIL_OF_MISERY_TALENT: {
    id: 320418,
    granted: false,
    requiresTalentEntry: [112858],
    type: 'talent',
    iconID: 1418287,
    passive: true,
    hidden: 'always',
    name: 'Improved Sigil of Misery',
    icon: 'ability_demonhunter_sigilofmisery.jpg',
  },
  VENGEFUL_BONDS_TALENT: {
    id: 320635,
    granted: false,
    requiresTalentEntry: [112840],
    type: 'talent',
    iconID: 1348401,
    passive: true,
    hidden: 'always',
    name: 'Vengeful Bonds',
    icon: 'ability_demonhunter_vengefulretreat2.jpg',
  },
  PURSUIT_TALENT: {
    id: 320654,
    granted: false,
    requiresTalentEntry: [112851],
    type: 'talent',
    iconID: 1344651,
    passive: true,
    hidden: 'always',
    name: 'Pursuit',
    icon: 'ability_demonhunter_infernalstrike2.jpg',
  },
  UNRESTRAINED_FURY_TALENT: {
    id: 320770,
    granted: false,
    requiresTalentEntry: [112852],
    type: 'talent',
    iconID: 132346,
    passive: true,
    hidden: 'always',
    name: 'Unrestrained Fury',
    icon: 'ability_warrior_improveddisciplines.jpg',
  },
  CHAOS_STRIKE: {
    id: 344862,
    type: 'baseline',
    iconID: 1305152,
    passive: false,
    name: 'Chaos Strike',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'ability_demonhunter_chaosstrike.jpg',
  },
  FODDER_TO_THE_FLAME_PASSIVE: {
    id: 350570,
    type: 'baseline',
    iconID: 3591588,
    passive: true,
    hidden: 'unless-learned',
    name: 'Fodder to the Flame',
    icon: 'ability_maldraxxus_demonhunter.jpg',
  },
  THE_HUNT: {
    id: 370967,
    grantedBy: 1246167,
    type: 'temporary',
    iconID: 6035307,
    passive: false,
    hidden: 'always',
    name: 'The Hunt',
    icon: 'inv_ability_demonhunter_thehunt.jpg',
  },
  WILL_OF_THE_ILLIDARI_TALENT: {
    id: 389695,
    granted: false,
    requiresTalentEntry: [112918],
    type: 'talent',
    iconID: 1247265,
    passive: true,
    hidden: 'always',
    name: 'Will of the Illidari',
    icon: 'ability_demonhunter_spectank.jpg',
  },
  ILLIDARI_KNOWLEDGE_TALENT: {
    id: 389696,
    granted: false,
    requiresTalentEntry: [112846],
    type: 'talent',
    iconID: 1033914,
    passive: true,
    hidden: 'always',
    name: 'Illidari Knowledge',
    icon: 'spell_mage_overpowered.jpg',
  },
  MASTER_OF_THE_GLAIVE_TALENT: {
    id: 389763,
    granted: false,
    requiresTalentEntry: [112912],
    type: 'talent',
    iconID: 1278164,
    passive: true,
    hidden: 'always',
    name: 'Master of the Glaive',
    icon: 'inv_glaive_1h_demonhunter_a_01.jpg',
  },
  LONG_NIGHT_TALENT: {
    id: 389781,
    granted: false,
    requiresTalentEntry: [112920],
    type: 'talent',
    iconID: 425957,
    passive: true,
    hidden: 'always',
    name: 'Long Night',
    icon: 'spell_fire_twilightimmolation.jpg',
  },
  PITCH_BLACK_TALENT: {
    id: 389783,
    granted: false,
    requiresTalentEntry: [112919],
    type: 'talent',
    iconID: 895888,
    passive: true,
    hidden: 'always',
    name: 'Pitch Black',
    icon: 'sha_spell_warlock_demonsoul.jpg',
  },
  SHATTERED_RESTORATION_TALENT: {
    id: 389824,
    granted: false,
    requiresTalentEntry: [112863],
    type: 'talent',
    iconID: 460700,
    passive: true,
    hidden: 'always',
    name: 'Shattered Restoration',
    icon: 'ability_warlock_soulsiphon.jpg',
  },
  FELFIRE_HASTE_TALENT: {
    id: 389846,
    granted: false,
    requiresTalentEntry: [112850],
    type: 'talent',
    iconID: 446089,
    passive: true,
    hidden: 'always',
    name: 'Felfire Haste',
    icon: 'inv_boots_cloth_35v4.jpg',
  },
  LOST_IN_DARKNESS_TALENT: {
    id: 389849,
    granted: false,
    requiresTalentEntry: [112860],
    type: 'talent',
    iconID: 1387707,
    passive: true,
    hidden: 'always',
    name: 'Lost in Darkness',
    icon: 'inv_pet_inquisitoreye.jpg',
  },
  ERRATIC_FELHEART_TALENT: {
    id: 391397,
    granted: false,
    requiresTalentEntry: [112914],
    type: 'talent',
    iconID: 1379226,
    passive: true,
    hidden: 'always',
    name: 'Erratic Felheart',
    icon: 'inv_archaeology_70_crystallineeyeofundravius.jpg',
  },
  ALDRACHI_DESIGN_TALENT: {
    id: 391409,
    granted: false,
    requiresTalentEntry: [112917],
    type: 'talent',
    iconID: 1309100,
    passive: true,
    hidden: 'always',
    name: 'Aldrachi Design',
    icon: 'inv_glaive_1h_artifactaldrochi_d_01dual.jpg',
  },
  INTERNAL_STRUGGLE_TALENT: {
    id: 393822,
    granted: false,
    requiresTalentEntry: [112845],
    type: 'talent',
    iconID: 236293,
    passive: true,
    hidden: 'always',
    name: 'Internal Struggle',
    icon: 'ability_warlock_demonicpower.jpg',
  },
  LIVE_BY_THE_GLAIVE_TALENT: {
    id: 428607,
    granted: false,
    requiresTalentEntry: [117761],
    type: 'talent',
    iconID: 135289,
    passive: true,
    hidden: 'always',
    name: 'Live by the Glaive',
    icon: 'inv_sword_108.jpg',
  },
  CHAMPION_OF_THE_GLAIVE_TALENT: {
    id: 429211,
    granted: false,
    requiresTalentEntry: [117768],
    type: 'talent',
    iconID: 1970139,
    passive: true,
    hidden: 'always',
    name: 'Champion of the Glaive',
    icon: 'inv_glaive_1h_battledungeon_c_01.jpg',
  },
  DEMONSURGE_TALENT: {
    id: 452402,
    granted: false,
    requiresTalentEntry: [117514, 136613],
    type: 'talent',
    iconID: 5927628,
    passive: true,
    hidden: 'always',
    name: 'Demonsurge',
    icon: 'inv_ability_felscarreddemonhunter_demonsurge.jpg',
  },
  WAVE_OF_DEBILITATION_TALENT: {
    id: 452403,
    granted: false,
    requiresTalentEntry: [117510, 136621],
    type: 'talent',
    iconID: 135795,
    passive: true,
    hidden: 'always',
    name: 'Wave of Debilitation',
    icon: 'spell_fire_felfirenova.jpg',
  },
  PURSUIT_OF_ANGRINESS_TALENT: {
    id: 452404,
    granted: false,
    requiresTalentEntry: [124011, 136619],
    type: 'talent',
    iconID: 1117885,
    passive: true,
    hidden: 'always',
    name: 'Pursuit of Angriness',
    icon: 'ability_felarakkoa_focusedblast.jpg',
  },
  FOCUSED_HATRED_TALENT: {
    id: 452405,
    granted: false,
    requiresTalentEntry: [117515, 136612],
    type: 'talent',
    iconID: 1380367,
    passive: true,
    hidden: 'always',
    name: 'Focused Hatred',
    icon: 'ability_demonhunter_illidansgrasp.jpg',
  },
  SET_FIRE_TO_THE_PAIN_TALENT: {
    id: 452406,
    granted: false,
    requiresTalentEntry: [117496, 136620],
    type: 'talent',
    iconID: 1450142,
    passive: true,
    hidden: 'always',
    name: 'Set Fire to the Pain',
    icon: 'ability_demonhunter_empowerwards.jpg',
  },
  IMPROVED_SOUL_RENDING_TALENT: {
    id: 452407,
    granted: false,
    requiresTalentEntry: [124010, 136618],
    type: 'talent',
    iconID: 1354410,
    passive: true,
    hidden: 'always',
    name: 'Improved Soul Rending',
    icon: 'ability_demonhunter_soulcleave2.jpg',
  },
  BURNING_BLADES_TALENT: {
    id: 452408,
    granted: false,
    requiresTalentEntry: [117502, 136610],
    type: 'talent',
    iconID: 1273721,
    passive: true,
    hidden: 'always',
    name: 'Burning Blades',
    icon: 'inv_glaive_1h_artifactazgalor_d_02dual.jpg',
  },
  VIOLENT_TRANSFORMATION_TALENT: {
    id: 452409,
    granted: false,
    requiresTalentEntry: [117509, 136622],
    type: 'talent',
    iconID: 237559,
    passive: true,
    hidden: 'always',
    name: 'Violent Transformation',
    icon: 'spell_shadow_demoniccirclesummon.jpg',
  },
  ENDURING_TORMENT_TALENT: {
    id: 452410,
    granted: false,
    requiresTalentEntry: [117513, 136615],
    type: 'talent',
    iconID: 135802,
    passive: true,
    hidden: 'always',
    name: 'Enduring Torment',
    icon: 'spell_fire_felimmolation.jpg',
  },
  UNTETHERED_FURY_TALENT: {
    id: 452411,
    granted: false,
    requiresTalentEntry: [117501, 136606],
    type: 'talent',
    iconID: 2032602,
    passive: true,
    hidden: 'always',
    name: 'Untethered Fury',
    icon: 'inv__felbarrage.jpg',
  },
  STUDENT_OF_SUFFERING_TALENT: {
    id: 452412,
    granted: false,
    requiresTalentEntry: [117499, 136616],
    type: 'talent',
    iconID: 3601553,
    passive: true,
    hidden: 'always',
    name: 'Student of Suffering',
    icon: 'achievement_dungeon_theatreofpain_kultharok.jpg',
  },
  FLAMEBOUND_TALENT: {
    id: 452413,
    granted: false,
    requiresTalentEntry: [124009, 136614],
    type: 'talent',
    iconID: 135799,
    passive: true,
    hidden: 'always',
    name: 'Flamebound',
    icon: 'spell_fire_felflamering.jpg',
  },
  MONSTER_RISING_TALENT: {
    id: 452414,
    granted: false,
    requiresTalentEntry: [117506, 136608],
    type: 'talent',
    iconID: 236293,
    passive: true,
    hidden: 'always',
    name: 'Monster Rising',
    icon: 'ability_warlock_demonicpower.jpg',
  },
  DEMONIC_INTENSITY_TALENT: {
    id: 452415,
    granted: false,
    requiresTalentEntry: [117498, 136617],
    type: 'talent',
    iconID: 1378283,
    passive: true,
    hidden: 'always',
    name: 'Demonic Intensity',
    icon: 'spell_warlock_demonicempowerment.jpg',
  },
  VOID_METAMORPHOSIS_TALENT: {
    id: 471306,
    granted: false,
    requiresTalentEntry: [132282],
    type: 'talent',
    iconID: 7135881,
    passive: true,
    hidden: 'always',
    name: 'Void Metamorphosis',
    icon: 'inv_112_ability_demonhunter_metamorphasisvoid.jpg',
  },
  CONSUME: {
    id: 473662,
    type: 'baseline',
    overrides: 344859,
    iconID: 7554200,
    passive: false,
    name: 'Consume',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 2000,
    },
    icon: 'inv_12_dh_void_ability_consume.jpg',
  },
  VOID_RAY_TALENT: {
    id: 473728,
    granted: false,
    requiresTalentEntry: [132278],
    type: 'talent',
    iconID: 7554220,
    passive: false,
    name: 'Void Ray',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 0,
      hasted: true,
      modifiers: [
        {
          duration: -2000,
          hasted: false,
          requiredSpells: [1244220],
        },
        {
          duration: 16000,
          hasted: false,
          requiredSpells: [1217607],
        },
      ],
    },
    channel: {
      duration: 3000,
      hasted: true,
      buffIsLogged: true,
      triggeredSpells: [],
    },
    icon: 'inv_12_dh_void_ability_voidray.jpg',
  },
  DEVOURER_DEMON_HUNTER_HIDDEN_1: {
    id: 1213636,
    type: 'baseline',
    iconID: 1247264,
    passive: true,
    hidden: 'always',
    name: 'Devourer Demon Hunter',
    icon: 'ability_demonhunter_specdps.jpg',
  },
  DEVOURER_DEMON_HUNTER_HIDDEN_2: {
    id: 1256964,
    type: 'baseline',
    iconID: 1247264,
    passive: true,
    hidden: 'always',
    name: 'Devourer Demon Hunter',
    icon: 'ability_demonhunter_specdps.jpg',
  },
  DEVOURER_DEMON_HUNTER_HIDDEN_3: {
    id: 1256968,
    type: 'baseline',
    iconID: 1247264,
    passive: true,
    hidden: 'always',
    name: 'Devourer Demon Hunter',
    icon: 'ability_demonhunter_specdps.jpg',
  },
  UNKNOWN_1: {
    id: 1215546,
    type: 'baseline',
    passive: false,
    name: 'Unknown',
    icon: 'inv_axe_02.jpg',
  },
  UNKNOWN_2: {
    id: 1227110,
    type: 'baseline',
    passive: false,
    name: 'Unknown',
    icon: 'inv_axe_02.jpg',
  },
  PREDATORS_THIRST_TALENT: {
    id: 1215617,
    granted: false,
    requiresTalentEntry: [133107],
    type: 'talent',
    iconID: 7554200,
    passive: true,
    hidden: 'always',
    name: "Predator's Thirst",
    icon: 'inv_12_dh_void_ability_consume.jpg',
  },
  VOID_METAMORPHOSIS_VOID_METAMORPHOSIS: {
    id: 1217607,
    grantedBy: 1217605,
    type: 'temporary',
    iconID: 7135881,
    passive: false,
    name: 'Void Metamorphosis',
    icon: 'inv_112_ability_demonhunter_metamorphasisvoid.jpg',
  },
  VOID_METAMORPHOSIS: {
    id: 1217605,
    type: 'baseline',
    overrides: 191427,
    iconID: 7135881,
    passive: false,
    name: 'Void Metamorphosis',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'inv_112_ability_demonhunter_metamorphasisvoid.jpg',
  },
  DEVOUR: {
    id: 1217610,
    grantedBy: 1217607,
    type: 'temporary',
    overrides: 473662,
    iconID: 7554204,
    passive: false,
    name: 'Devour',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 1500,
    },
    icon: 'inv_12_dh_void_ability_feast.jpg',
  },
  COLLAPSING_STAR_TALENT: {
    id: 1221167,
    granted: false,
    requiresTalentEntry: [132281],
    type: 'talent',
    iconID: 7554199,
    passive: true,
    hidden: 'always',
    name: 'Collapsing Star',
    icon: 'inv_12_dh_void_ability_collapsingstar.jpg',
  },
  GUILE_TALENT: {
    id: 1223171,
    granted: false,
    requiresTalentEntry: [132288],
    type: 'talent',
    iconID: 237558,
    passive: true,
    hidden: 'always',
    name: 'Guile',
    icon: 'spell_shadow_demonform.jpg',
  },
  WASTE_NOT_TALENT: {
    id: 1223918,
    granted: false,
    requiresTalentEntry: [133370],
    type: 'talent',
    iconID: 7554223,
    passive: true,
    hidden: 'always',
    name: 'Waste Not',
    icon: 'inv_12_dh_void_ability_wastenot.jpg',
  },
  REAP: {
    id: 1226019,
    type: 'baseline',
    overrides: 344862,
    iconID: 7554210,
    passive: false,
    name: 'Reap',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    charges: {
      max: 1,
      modifiers: [
        {
          max: 1,
          requiredSpells: [1239537],
        },
      ],
    },
    cooldown: {
      duration: 8000,
      hasted: false,
      modifiers: [
        {
          hasted: true,
          requiredSpells: [1272842],
        },
      ],
    },
    icon: 'inv_12_dh_void_ability_reap.jpg',
  },
  ERADICATE_TALENT: {
    id: 1226033,
    granted: false,
    requiresTalentEntry: [132287],
    type: 'talent',
    iconID: 7554203,
    passive: true,
    hidden: 'always',
    name: 'Eradicate',
    icon: 'inv_12_dh_void_ability_eradicate.jpg',
  },
  SHATTERED_SOULS_PASSIVE: {
    id: 1227619,
    type: 'baseline',
    iconID: 7554214,
    passive: true,
    name: 'Shattered Souls',
    icon: 'inv_12_dh_void_ability_soulfragments.jpg',
  },
  IMPENDING_APOCALYPSE_TALENT: {
    id: 1227707,
    granted: false,
    requiresTalentEntry: [132283],
    type: 'talent',
    iconID: 7554207,
    passive: true,
    hidden: 'always',
    name: 'Impending Apocalypse',
    icon: 'inv_12_dh_void_ability_impendingapocalypse.jpg',
  },
  SINGLE_BUTTON_ASSISTANT: {
    id: 1229376,
    type: 'baseline',
    iconID: 6718291,
    passive: false,
    name: 'Single-Button Assistant',
    castTime: {
      duration: 2000,
    },
    icon: 'ui_spellbook_onebutton.jpg',
  },
  VOID_NOVA_TALENT: {
    id: 1234195,
    granted: false,
    requiresTalentEntry: [132289],
    type: 'talent',
    iconID: 7554172,
    passive: false,
    name: 'Void Nova',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
    },
    icon: 'inv_12_voiddh_ability_voidnova.jpg',
  },
  SHIFT: {
    id: 1234796,
    type: 'baseline',
    overrides: 344865,
    iconID: 7554213,
    passive: false,
    name: 'Shift',
    charges: {
      max: 1,
      modifiers: [
        {
          max: 1,
          requiredSpells: [320416],
        },
        {
          max: 1,
          requiredSpells: [1253402],
        },
      ],
    },
    cooldown: {
      duration: 20000,
      hasted: false,
    },
    icon: 'inv_12_dh_void_ability_shift.jpg',
  },
  FEAST_OF_SOULS_TALENT: {
    id: 1237270,
    granted: false,
    requiresTalentEntry: [132285],
    type: 'talent',
    iconID: 7554205,
    passive: true,
    hidden: 'always',
    name: 'Feast of Souls',
    icon: 'inv_12_dh_void_ability_firstofsouls.jpg',
  },
  MOMENT_OF_CRAVING_TALENT: {
    id: 1238488,
    granted: false,
    requiresTalentEntry: [133106],
    type: 'talent',
    iconID: 7554208,
    passive: true,
    hidden: 'always',
    name: 'Moment of Craving',
    icon: 'inv_12_dh_void_ability_momentofcraving.jpg',
  },
  SOULSHAPER_TALENT: {
    id: 1238739,
    granted: false,
    requiresTalentEntry: [132284],
    type: 'talent',
    iconID: 7554217,
    passive: true,
    hidden: 'always',
    name: 'Soulshaper',
    icon: 'inv_12_dh_void_ability_sunder.jpg',
  },
  MASTERY_MONSTER_WITHIN_PASSIVE: {
    id: 1238855,
    type: 'baseline',
    iconID: 1380372,
    passive: true,
    name: 'Mastery: Monster Within',
    icon: 'ability_demonhunter_reversemagic.jpg',
  },
  HUNGERING_SLASH_TALENT: {
    id: 1239519,
    granted: false,
    requiresTalentEntry: [133531],
    type: 'talent',
    iconID: 7554211,
    passive: true,
    hidden: 'always',
    name: 'Hungering Slash',
    icon: 'inv_12_dh_void_ability_reapersslice.jpg',
  },
  SECOND_HELPING_TALENT: {
    id: 1239537,
    granted: false,
    requiresTalentEntry: [136499],
    type: 'talent',
    iconID: 7126991,
    passive: true,
    hidden: 'always',
    name: 'Second Helping',
    icon: 'inv_polearm_2h_voidscythe_d_01.jpg',
  },
  DEVOURERS_BITE_TALENT: {
    id: 1240201,
    granted: false,
    requiresTalentEntry: [136692],
    type: 'talent',
    iconID: 7554201,
    passive: true,
    hidden: 'always',
    name: "Devourer's Bite",
    icon: 'inv_12_dh_void_ability_devourerbite.jpg',
  },
  VOIDGLARE_BOON_TALENT: {
    id: 1240202,
    granted: false,
    requiresTalentEntry: [136694],
    type: 'talent',
    iconID: 5976933,
    passive: true,
    hidden: 'always',
    name: 'Voidglare Boon',
    icon: 'inv_nulllotus_cosmicvoid.jpg',
  },
  FOCUSED_RAY_TALENT: {
    id: 1240203,
    granted: false,
    requiresTalentEntry: [133110],
    type: 'talent',
    iconID: 4913233,
    passive: true,
    hidden: 'always',
    name: 'Focused Ray',
    icon: 'inv_cosmicvoid_beam.jpg',
  },
  STAR_FRAGMENTS_TALENT: {
    id: 1240204,
    granted: false,
    requiresTalentEntry: [136697],
    type: 'talent',
    iconID: 7554216,
    passive: true,
    hidden: 'always',
    name: 'Star Fragments',
    icon: 'inv_12_dh_void_ability_starfragments.jpg',
  },
  SOUL_IMMOLATION_TALENT: {
    id: 1241937,
    granted: false,
    requiresTalentEntry: [132286],
    overrides: 258920,
    type: 'talent',
    iconID: 7554219,
    passive: false,
    name: 'Soul Immolation',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    charges: {
      max: 1,
      modifiers: [
        {
          max: 1,
          requiredSpells: [1246555],
        },
      ],
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: 'inv_12_dh_void_ability_voidpurge.jpg',
  },
  MIDNIGHT_TALENT_1: {
    id: 1242486,
    granted: false,
    requiresTalentEntry: [137016],
    type: 'talent',
    iconID: 7514177,
    passive: true,
    hidden: 'always',
    name: 'Midnight',
    icon: 'inv12_apextalent_demonhunter_midnight.jpg',
  },
  MIDNIGHT_TALENT_2: {
    id: 1250088,
    granted: false,
    requiresTalentEntry: [137015],
    type: 'talent',
    iconID: 5927657,
    passive: true,
    hidden: 'always',
    name: 'Midnight',
    icon: 'inv_ability_voidweaverpriest_entropicrift.jpg',
  },
  MIDNIGHT_TALENT_3: {
    id: 1250094,
    granted: false,
    requiresTalentEntry: [137014],
    type: 'talent',
    iconID: 1778227,
    passive: true,
    hidden: 'always',
    name: 'Midnight',
    icon: 'ability_argus_edgeofobliteration.jpg',
  },
  EMPTINESS_TALENT: {
    id: 1242492,
    granted: false,
    requiresTalentEntry: [133512],
    type: 'talent',
    iconID: 4913234,
    passive: true,
    hidden: 'always',
    name: 'Emptiness',
    icon: 'inv_cosmicvoid_buff.jpg',
  },
  CALAMITOUS_TALENT: {
    id: 1242495,
    granted: false,
    requiresTalentEntry: [136691],
    type: 'talent',
    iconID: 1778229,
    passive: true,
    hidden: 'always',
    name: 'Calamitous',
    icon: 'ability_argus_soulbombdebuffsmall.jpg',
  },
  SWEET_RELEASE_TALENT: {
    id: 1242768,
    granted: false,
    requiresTalentEntry: [134149],
    type: 'talent',
    iconID: 828455,
    passive: true,
    hidden: 'always',
    name: 'Sweet Release',
    icon: 'spell_misc_zandalari_council_soulswap.jpg',
  },
  VOIDRAGE_TALENT: {
    id: 1242956,
    granted: false,
    requiresTalentEntry: [136131],
    type: 'talent',
    iconID: 7554215,
    passive: true,
    hidden: 'always',
    name: 'Voidrage',
    icon: 'inv_12_dh_void_ability_soulimmolation.jpg',
  },
  VOIDPURGE_TALENT: {
    id: 1244220,
    granted: false,
    requiresTalentEntry: [136699],
    type: 'talent',
    iconID: 7554220,
    passive: true,
    hidden: 'always',
    name: 'Voidpurge',
    icon: 'inv_12_dh_void_ability_voidray.jpg',
  },
  DEVOURERS_EDGE_TALENT: {
    id: 1244222,
    granted: false,
    requiresTalentEntry: [133538],
    type: 'talent',
    iconID: 7554202,
    passive: true,
    hidden: 'always',
    name: "Devourer's Edge",
    icon: 'inv_12_dh_void_ability_empoweredreap.jpg',
  },
  ROLLING_TORMENT_TALENT: {
    id: 1244237,
    granted: false,
    requiresTalentEntry: [136693],
    type: 'talent',
    iconID: 4914666,
    passive: true,
    hidden: 'always',
    name: 'Rolling Torment',
    icon: 'inv_cosmicvoid_debuff.jpg',
  },
  SWEET_SUFFERING_TALENT: {
    id: 1244295,
    granted: false,
    requiresTalentEntry: [132280],
    type: 'talent',
    iconID: 1305158,
    passive: true,
    hidden: 'always',
    name: 'Sweet Suffering',
    icon: 'ability_demonhunter_shatteredsouls.jpg',
  },
  VOIDBLADE_TALENT: {
    id: 1245412,
    granted: true,
    requiresTalentEntry: [134272],
    type: 'talent',
    iconID: 7554171,
    passive: false,
    name: 'Voidblade',
    gcd: {
      duration: 500,
      hasted: false,
    },
    charges: {
      max: 1,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 'inv_12_voiddh_ability_voidblade.jpg',
  },
  CULL: {
    id: 1245453,
    grantedBy: 1217607,
    type: 'temporary',
    overrides: 1226019,
    iconID: 7554202,
    passive: false,
    name: 'Cull',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    charges: {
      max: 1,
      modifiers: [
        {
          max: 1,
          requiredSpells: [1239537],
        },
      ],
    },
    cooldown: {
      duration: 8000,
      hasted: false,
      modifiers: [
        {
          hasted: true,
          requiredSpells: [1272842],
        },
      ],
    },
    icon: 'inv_12_dh_void_ability_empoweredreap.jpg',
  },
  THE_HUNT_TALENT: {
    id: 1246167,
    granted: false,
    requiresTalentEntry: [135736],
    type: 'talent',
    iconID: 7554167,
    passive: false,
    hidden: 'unless-learned',
    name: 'The Hunt',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 90000,
      hasted: false,
    },
    castTime: {
      duration: 1000,
    },
    icon: 'inv_12_voiddh_ability_thehunt.jpg',
  },
  TEMPERED_SOUL_TALENT: {
    id: 1246555,
    granted: false,
    requiresTalentEntry: [134280],
    type: 'talent',
    iconID: 7554219,
    passive: true,
    hidden: 'always',
    name: 'Tempered Soul',
    icon: 'inv_12_dh_void_ability_voidpurge.jpg',
  },
  SPONTANEOUS_IMMOLATION_TALENT: {
    id: 1246556,
    granted: false,
    requiresTalentEntry: [135730],
    overrides: 1241937,
    type: 'talent',
    iconID: 425957,
    passive: true,
    hidden: 'always',
    name: 'Spontaneous Immolation',
    icon: 'spell_fire_twilightimmolation.jpg',
  },
  SCYTHES_EMBRACE_TALENT: {
    id: 1246558,
    granted: false,
    requiresTalentEntry: [134279],
    type: 'talent',
    iconID: 7554221,
    passive: true,
    hidden: 'always',
    name: "Scythe's Embrace",
    icon: 'inv_12_dh_void_ability_voidreaper.jpg',
  },
  DUTY_ETERNAL_TALENT: {
    id: 1246562,
    granted: false,
    requiresTalentEntry: [134275],
    type: 'talent',
    iconID: 7554171,
    passive: true,
    hidden: 'always',
    name: 'Duty Eternal',
    icon: 'inv_12_voiddh_ability_voidblade.jpg',
  },
  SOUL_GLUTTON_TALENT: {
    id: 1247534,
    granted: false,
    requiresTalentEntry: [134331],
    type: 'talent',
    iconID: 1120184,
    passive: true,
    hidden: 'always',
    name: 'Soul Glutton',
    icon: 'ability_bossgorefiend_gorefiendscorruption.jpg',
  },
  DEMONIC_INSTINCT_TALENT: {
    id: 1247538,
    granted: false,
    requiresTalentEntry: [136690],
    type: 'talent',
    iconID: 7554209,
    passive: true,
    hidden: 'always',
    name: 'Demonic Instinct',
    icon: 'inv_12_dh_void_ability_predatorsthirst.jpg',
  },
  VOIDFALL_TALENT: {
    id: 1253304,
    granted: false,
    requiresTalentEntry: [135667],
    type: 'talent',
    iconID: 7554218,
    passive: true,
    hidden: 'always',
    name: 'Voidfall',
    icon: 'inv_12_dh_void_ability_voidfall.jpg',
  },
  METEORIC_RISE_TALENT: {
    id: 1253377,
    granted: false,
    requiresTalentEntry: [135673],
    type: 'talent',
    iconID: 1041231,
    passive: true,
    hidden: 'always',
    name: 'Meteoric Rise',
    icon: 'ability_socererking_arcanefortification.jpg',
  },
  METEORIC_FALL_TALENT: {
    id: 1253391,
    granted: false,
    requiresTalentEntry: [135664],
    type: 'talent',
    iconID: 1041233,
    passive: true,
    hidden: 'always',
    name: 'Meteoric Fall',
    icon: 'ability_socererking_arcanereplication.jpg',
  },
  PATH_TO_OBLIVION_TALENT: {
    id: 1253399,
    granted: false,
    requiresTalentEntry: [135666],
    type: 'talent',
    iconID: 1041230,
    passive: true,
    hidden: 'always',
    name: 'Path to Oblivion',
    icon: 'ability_socererking_arcaneacceleration.jpg',
  },
  STATE_OF_MATTER_TALENT: {
    id: 1253402,
    granted: false,
    requiresTalentEntry: [135659],
    type: 'talent',
    iconID: 6891021,
    passive: true,
    hidden: 'always',
    name: 'State of Matter',
    icon: 'inv_112_arcane_buff.jpg',
  },
  CELESTIAL_ECHOES_TALENT: {
    id: 1253415,
    granted: false,
    requiresTalentEntry: [135669],
    type: 'talent',
    iconID: 7126991,
    passive: true,
    hidden: 'always',
    name: 'Celestial Echoes',
    icon: 'inv_polearm_2h_voidscythe_d_01.jpg',
  },
  SWIFT_ERASURE_TALENT: {
    id: 1253668,
    granted: false,
    requiresTalentEntry: [135672],
    type: 'talent',
    iconID: 1445237,
    passive: true,
    hidden: 'always',
    name: 'Swift Erasure',
    icon: 'ability_priest_darkarchangel.jpg',
  },
  DOOMSAYER_TALENT: {
    id: 1253676,
    granted: false,
    requiresTalentEntry: [135668],
    type: 'talent',
    iconID: 4914674,
    passive: true,
    hidden: 'always',
    name: 'Doomsayer',
    icon: 'inv_shadowflame_buff.jpg',
  },
  CATASTROPHE_TALENT: {
    id: 1253769,
    granted: false,
    requiresTalentEntry: [135671],
    type: 'talent',
    iconID: 2065615,
    passive: true,
    hidden: 'always',
    name: 'Catastrophe',
    icon: 'inv_netherportal.jpg',
  },
  FINAL_HOUR_TALENT: {
    id: 1253805,
    granted: false,
    requiresTalentEntry: [135663],
    type: 'talent',
    iconID: 4632795,
    passive: true,
    hidden: 'always',
    name: 'Final Hour',
    icon: 'inv_10_worlddroplevelingoptionalreagent_relics_hourglass_color1.jpg',
  },
  OTHERWORLDLY_FOCUS_TALENT: {
    id: 1253817,
    granted: false,
    requiresTalentEntry: [135661],
    type: 'talent',
    iconID: 6992623,
    passive: true,
    hidden: 'always',
    name: 'Otherworldly Focus',
    icon: 'inv_babyvoidwalker_blue.jpg',
  },
  PHASE_SHIFT_TALENT: {
    id: 1256245,
    granted: false,
    requiresTalentEntry: [135670],
    type: 'talent',
    iconID: 1305150,
    passive: true,
    hidden: 'always',
    name: 'Phase Shift',
    icon: 'ability_demonhunter_blur.jpg',
  },
  MASS_ACCELERATION_TALENT: {
    id: 1256295,
    granted: false,
    requiresTalentEntry: [135665],
    type: 'talent',
    iconID: 5976939,
    passive: true,
    hidden: 'always',
    name: 'Mass Acceleration',
    icon: 'inv_nullstone_cosmicvoid.jpg',
  },
  DARK_MATTER_TALENT: {
    id: 1256307,
    granted: false,
    requiresTalentEntry: [135662],
    type: 'talent',
    iconID: 4914669,
    passive: true,
    hidden: 'always',
    name: 'Dark Matter',
    icon: 'inv_cosmicvoid_nova.jpg',
  },
  WORLD_KILLER_TALENT: {
    id: 1256353,
    granted: false,
    requiresTalentEntry: [135660],
    type: 'talent',
    iconID: 7127719,
    passive: true,
    hidden: 'always',
    name: 'World Killer',
    icon: 'inv_112_raiddimensius_brokenworld.jpg',
  },
  GRIM_FOCUS_PASSIVE: {
    id: 1260008,
    type: 'baseline',
    iconID: 1305156,
    passive: true,
    name: 'Grim Focus',
    icon: 'ability_demonhunter_eyebeam.jpg',
  },
  ENTROPY_TALENT: {
    id: 1261684,
    granted: false,
    requiresTalentEntry: [133511],
    type: 'talent',
    iconID: 7137586,
    passive: true,
    hidden: 'always',
    name: 'Entropy',
    icon: 'inv_112_raidtrinkets_voidprism.jpg',
  },
  FOCUSED_IRE_TALENT: {
    id: 1266296,
    granted: false,
    requiresTalentEntry: [117767],
    type: 'talent',
    iconID: 1118739,
    passive: true,
    hidden: 'always',
    name: 'Focused Ire',
    icon: 'ability_bossfellord_felspike.jpg',
  },
  DEMONIC_RESILIENCE_TALENT: {
    id: 1266307,
    granted: false,
    requiresTalentEntry: [117755],
    type: 'talent',
    iconID: 2065628,
    passive: true,
    hidden: 'always',
    name: 'Demonic Resilience',
    icon: 'inv_summondemonictyrant.jpg',
  },
  BURN_IT_OUT_TALENT: {
    id: 1266316,
    granted: false,
    requiresTalentEntry: [112837],
    type: 'talent',
    iconID: 841219,
    passive: true,
    hidden: 'always',
    name: 'Burn It Out',
    icon: 'spell_fel_elementaldevastation.jpg',
  },
  FURIOUS_TALENT: {
    id: 1266326,
    granted: false,
    requiresTalentEntry: [117762],
    type: 'talent',
    iconID: 607865,
    passive: true,
    hidden: 'always',
    name: 'Furious',
    icon: 'ability_warlock_shadowfurytga.jpg',
  },
  REMORSELESS_TALENT: {
    id: 1266328,
    granted: false,
    requiresTalentEntry: [112839],
    type: 'talent',
    iconID: 1303275,
    passive: true,
    hidden: 'always',
    name: 'Remorseless',
    icon: 'inv_glaive_1h_npc_d_02.jpg',
  },
  DEMON_MUZZLE_TALENT: {
    id: 1266329,
    granted: false,
    requiresTalentEntry: [112838],
    type: 'talent',
    iconID: 1032478,
    passive: true,
    hidden: 'always',
    name: 'Demon Muzzle',
    icon: 'spell_warlock_demonicservitude.jpg',
  },
  SOUL_SPLITTER_TALENT: {
    id: 1266330,
    granted: false,
    requiresTalentEntry: [112862],
    type: 'talent',
    iconID: 460857,
    passive: true,
    hidden: 'always',
    name: 'Soul Splitter',
    icon: 'ability_warlock_soulswap.jpg',
  },
  WINGS_OF_WRATH_TALENT: {
    id: 1266493,
    granted: false,
    requiresTalentEntry: [136500],
    type: 'talent',
    iconID: 1305157,
    passive: true,
    hidden: 'always',
    name: 'Wings of Wrath',
    icon: 'ability_demonhunter_glide.jpg',
  },
  SOUL_CLEANSE_TALENT: {
    id: 1266496,
    granted: false,
    requiresTalentEntry: [136502],
    type: 'talent',
    iconID: 136082,
    passive: true,
    hidden: 'always',
    name: 'Soul Cleanse',
    icon: 'spell_nature_removecurse.jpg',
  },
  FIRST_IN_LAST_OUT_TALENT: {
    id: 1266497,
    granted: false,
    requiresTalentEntry: [117758],
    type: 'talent',
    iconID: 1380365,
    passive: true,
    hidden: 'always',
    name: 'First In, Last Out',
    icon: 'ability_demonhunter_demonictrample.jpg',
  },
  FINAL_BREATH_TALENT: {
    id: 1266500,
    granted: false,
    requiresTalentEntry: [136501],
    type: 'talent',
    iconID: 135798,
    passive: true,
    hidden: 'always',
    name: 'Final Breath',
    icon: 'spell_fire_felflamebreath.jpg',
  },
  BLIND_FOCUS_TALENT: {
    id: 1272364,
    granted: false,
    requiresTalentEntry: [136031, 136607],
    type: 'talent',
    iconID: 1531487,
    passive: true,
    hidden: 'always',
    name: 'Blind Focus',
    icon: 'inv_belt_leather_raiddemonhunter_r_01.jpg',
  },
  UNDYING_EMBERS_TALENT: {
    id: 1272405,
    granted: false,
    requiresTalentEntry: [136032, 136609],
    type: 'talent',
    iconID: 840194,
    passive: true,
    hidden: 'always',
    name: 'Undying Embers',
    icon: 'ability_warlock_burningembersgreen.jpg',
  },
  VOIDRUSH_TALENT: {
    id: 1272422,
    granted: false,
    requiresTalentEntry: [136698],
    type: 'talent',
    iconID: 7554222,
    passive: true,
    hidden: 'always',
    name: 'Voidrush',
    icon: 'inv_12_dh_void_ability_voidstep.jpg',
  },
  SOULFORGED_BLADES_TALENT: {
    id: 1272432,
    granted: false,
    requiresTalentEntry: [136696],
    type: 'talent',
    iconID: 7439190,
    passive: true,
    hidden: 'always',
    name: 'Soulforged Blades',
    icon: 'inv12_ability_deathknight_frostscythe.jpg',
  },
  VOLATILE_INSTINCT_TALENT: {
    id: 1272453,
    granted: false,
    requiresTalentEntry: [136030, 136611],
    type: 'talent',
    iconID: 7501339,
    passive: true,
    hidden: 'always',
    name: 'Volatile Instinct',
    icon: 'inv_nature_nova.jpg',
  },
  SINGULAR_STRIKES_TALENT: {
    id: 1272770,
    granted: false,
    requiresTalentEntry: [136695],
    type: 'talent',
    iconID: 7554212,
    passive: true,
    hidden: 'always',
    name: 'Singular Strikes',
    icon: 'inv_12_dh_void_ability_scythethrow.jpg',
  },
  IMPROVED_CONSUME_TALENT: {
    id: 1272817,
    granted: false,
    requiresTalentEntry: [134330],
    type: 'talent',
    iconID: 7554204,
    passive: true,
    hidden: 'always',
    name: 'Improved Consume',
    icon: 'inv_12_dh_void_ability_feast.jpg',
  },
  SINGED_SPIRIT_TALENT: {
    id: 1272832,
    granted: false,
    requiresTalentEntry: [134148],
    type: 'talent',
    iconID: 6012046,
    passive: true,
    hidden: 'always',
    name: 'Singed Spirit',
    icon: 'inv_11_0_misc_candlekobold_color3.jpg',
  },
  UMBRAL_BLADE_TALENT: {
    id: 1272842,
    granted: false,
    requiresTalentEntry: [133368],
    type: 'talent',
    iconID: 7554210,
    passive: true,
    hidden: 'always',
    name: 'Umbral Blade',
    icon: 'inv_12_dh_void_ability_reap.jpg',
  },
  GIFT_OF_THE_VOID_TALENT: {
    id: 1272847,
    granted: false,
    requiresTalentEntry: [133111],
    type: 'talent',
    iconID: 1380372,
    passive: true,
    hidden: 'always',
    name: 'Gift of the Void',
    icon: 'ability_demonhunter_reversemagic.jpg',
  },
  LEATHER_SPECIALIZATION_HIDDEN: {
    id: 1277734,
    type: 'baseline',
    iconID: 132649,
    passive: true,
    hidden: 'always',
    name: 'Leather Specialization',
    icon: 'inv_chest_cloth_08.jpg',
  },
  DEMONIC_WARDS_PASSIVE: {
    id: 1277736,
    type: 'baseline',
    iconID: 1266395,
    passive: true,
    name: 'Demonic Wards',
    icon: 'inv_belt_leather_demonhunter_a_01.jpg',
  },
  HARNESS_THE_COSMOS_TALENT: {
    id: 1279247,
    granted: false,
    requiresTalentEntry: [136810],
    type: 'talent',
    iconID: 4914670,
    passive: true,
    hidden: 'always',
    name: 'Harness the Cosmos',
    icon: 'inv_cosmicvoid_orb.jpg',
  },
} as const satisfies Record<string, RetailSpell & { icon: string }>;
export default SPELLS;
