import SPELLS from 'common/SPELLS';

export const ABILITIES_AFFECTED_BY_HEALING_INCREASES = [
  SPELLS.DIVINE_HYMN_HEAL.id,
  SPELLS.GREATER_HEAL.id,
  SPELLS.FLASH_HEAL.id,
  SPELLS.PRAYER_OF_MENDING_HEAL.id,
  SPELLS.PRAYER_OF_HEALING.id,
  SPELLS.RENEW.id,
  SPELLS.HOLY_WORD_SERENITY.id,
  SPELLS.HOLY_WORD_SANCTIFY.id,
  SPELLS.HOLY_WORD_SALVATION_TALENT.id,
  SPELLS.DESPERATE_PRAYER.id,
  SPELLS.COSMIC_RIPPLE_TALENT.id,
  SPELLS.BINDING_HEAL_TALENT.id,
  SPELLS.CIRCLE_OF_HEALING_TALENT.id,
  SPELLS.HALO_HEAL.id,
  SPELLS.DIVINE_STAR_TALENT.id, // might have diff id for heal?
  SPELLS.GUILTY_CONSCIENCE.id,
  SPELLS.TRAIL_OF_LIGHT_TALENT.id,
];

// better off making things that -dont- proc it perhaps?
export const ABILITIES_THAT_TRIGGER_MASTERY = [
  SPELLS.DIVINE_HYMN_HEAL.id,
  SPELLS.GREATER_HEAL.id,
  SPELLS.FLASH_HEAL.id,
  SPELLS.PRAYER_OF_MENDING_HEAL.id,
  SPELLS.PRAYER_OF_HEALING.id,
  SPELLS.HOLY_WORD_SERENITY.id,
  SPELLS.HOLY_WORD_SANCTIFY.id,
  SPELLS.HOLY_WORD_SALVATION_TALENT.id,
  SPELLS.DESPERATE_PRAYER.id,
  SPELLS.COSMIC_RIPPLE_HEAL.id,
  SPELLS.BINDING_HEAL_TALENT.id,
  SPELLS.CIRCLE_OF_HEALING_TALENT.id,
  SPELLS.HALO_HEAL.id,
  SPELLS.DIVINE_STAR_HEAL.id, // might have diff id for heal?
  SPELLS.GUILTY_CONSCIENCE.id,
  SPELLS.RENEW.id, // this is reduced in calculations, due to the initial tick proccing EoL but not the periodic ticks
  SPELLS.TRAIL_OF_LIGHT_TALENT.id,
  SPELLS.HOLY_NOVA_HEAL.id,
  SPELLS.GUARDIAN_SPIRIT_HEAL.id,
];

export const ABILITIES_THAT_TRIGGER_ENDURING_RENEWAL = [
  SPELLS.GREATER_HEAL.id,
  SPELLS.FLASH_HEAL.id,
  SPELLS.HOLY_WORD_SERENITY.id,
  SPELLS.BINDING_HEAL_TALENT.id,
];

export const ABILITIES_AFFECTED_BY_APOTHEOSIS_TALENT = [
  SPELLS.HOLY_WORD_SERENITY.id,
  SPELLS.HOLY_WORD_SANCTIFY.id,
];
