import { CLASSES } from 'game/CLASSES';
import { TIERS } from 'game/TIERS';

export const DEATH_KNIGHT_TIER_T28_ID = 1500;
export const DEMON_HUNTER_TIER_T28_ID = 1501;
export const DRUID_TIER_T28_ID = 1502;
export const HUNTER_TIER_T28_ID = 1497;
export const MAGE_TIER_T28_ID = 1503;
export const MONK_TIER_T28_ID = 1504;
export const PALADIN_TIER_T28_ID = 1498;
export const PRIEST_TIER_T28_ID = 1505;
export const ROGUE_TIER_T28_ID = 1496;
export const SHAMAN_TIER_T28_ID = 1499;
export const WARLOCK_TIER_T28_ID = 1507;
export const WARRIOR_TIER_T28_ID = 1506;

export type T28_TIER_GEAR_IDS =
  | typeof DEATH_KNIGHT_TIER_T28_ID
  | typeof DEMON_HUNTER_TIER_T28_ID
  | typeof DRUID_TIER_T28_ID
  | typeof HUNTER_TIER_T28_ID
  | typeof MAGE_TIER_T28_ID
  | typeof MONK_TIER_T28_ID
  | typeof PALADIN_TIER_T28_ID
  | typeof PRIEST_TIER_T28_ID
  | typeof ROGUE_TIER_T28_ID
  | typeof SHAMAN_TIER_T28_ID
  | typeof WARLOCK_TIER_T28_ID
  | typeof WARRIOR_TIER_T28_ID;

export const DEATH_KNIGHT_T30_ID = 1526;
export const DEMON_HUNTER_T30_ID = 1527;
export const DRUID_T30_ID = 1528;
export const EVOKER_T30_ID = 1530;
export const HUNTER_T30_ID = 1529;
export const MAGE_T30_ID = 1531;
export const MONK_T30_ID = 1532;
export const PALADIN_T30_ID = 1533;
export const PRIEST_T30_ID = 1534;
export const ROGUE_T30_ID = 1535;
export const SHAMAN_T30_ID = 1536;
export const WARLOCK_T30_ID = 1537;
export const WARRIOR_T30_ID = 1538;

export type T30_TIER_GEAR_IDS =
  | typeof DEATH_KNIGHT_T30_ID
  | typeof DEMON_HUNTER_T30_ID
  | typeof DRUID_T30_ID
  | typeof EVOKER_T30_ID
  | typeof HUNTER_T30_ID
  | typeof MAGE_T30_ID
  | typeof MONK_T30_ID
  | typeof PALADIN_T30_ID
  | typeof PRIEST_T30_ID
  | typeof ROGUE_T30_ID
  | typeof SHAMAN_T30_ID
  | typeof WARLOCK_T30_ID
  | typeof WARRIOR_T30_ID;

export const T28_TIER_BY_CLASSES: Record<number, T28_TIER_GEAR_IDS> = {
  [CLASSES.DEATH_KNIGHT]: DEATH_KNIGHT_TIER_T28_ID,
  [CLASSES.DEMON_HUNTER]: DEMON_HUNTER_TIER_T28_ID,
  [CLASSES.DRUID]: DRUID_TIER_T28_ID,
  [CLASSES.HUNTER]: HUNTER_TIER_T28_ID,
  [CLASSES.MAGE]: MAGE_TIER_T28_ID,
  [CLASSES.MONK]: MONK_TIER_T28_ID,
  [CLASSES.PALADIN]: PALADIN_TIER_T28_ID,
  [CLASSES.PRIEST]: PRIEST_TIER_T28_ID,
  [CLASSES.ROGUE]: ROGUE_TIER_T28_ID,
  [CLASSES.SHAMAN]: SHAMAN_TIER_T28_ID,
  [CLASSES.WARLOCK]: WARLOCK_TIER_T28_ID,
  [CLASSES.WARRIOR]: WARRIOR_TIER_T28_ID,
};

export const T30_TIER_BY_CLASSES: Record<number, T30_TIER_GEAR_IDS> = {
  [CLASSES.DEATH_KNIGHT]: DEATH_KNIGHT_T30_ID,
  [CLASSES.DEMON_HUNTER]: DEMON_HUNTER_T30_ID,
  [CLASSES.DRUID]: DRUID_T30_ID,
  [CLASSES.EVOKER]: EVOKER_T30_ID,
  [CLASSES.HUNTER]: HUNTER_T30_ID,
  [CLASSES.MAGE]: MAGE_T30_ID,
  [CLASSES.MONK]: MONK_T30_ID,
  [CLASSES.PALADIN]: PALADIN_T30_ID,
  [CLASSES.PRIEST]: PRIEST_T30_ID,
  [CLASSES.ROGUE]: ROGUE_T30_ID,
  [CLASSES.SHAMAN]: SHAMAN_T30_ID,
  [CLASSES.WARLOCK]: WARLOCK_T30_ID,
  [CLASSES.WARRIOR]: WARRIOR_T30_ID,
};

export const TIER_BY_CLASSES: Record<number, Record<number, number>> = {
  [TIERS.T28]: T28_TIER_BY_CLASSES,
  [TIERS.T30]: T30_TIER_BY_CLASSES,
};
