import SPELLS from 'common/SPELLS';
import Spell from 'common/SPELLS/Spell';
import TALENTS from 'common/TALENTS/paladin';
import Combatant from 'parser/core/Combatant';

export const ABILITIES_AFFECTED_BY_HEALING_INCREASES = [
  SPELLS.HOLY_SHOCK_HEAL.id,
  SPELLS.LIGHT_OF_DAWN_HEAL.id,
  SPELLS.FLASH_OF_LIGHT.id,
  SPELLS.JUDGMENT_OF_LIGHT_HEAL.id,
  TALENTS.LIGHT_OF_THE_MARTYR_TALENT.id,
  SPELLS.HOLY_PRISM_HEAL.id,
  SPELLS.HOLY_PRISM_HEAL_DIRECT.id,
  SPELLS.AURA_OF_MERCY_HEAL.id,
  // While the following spells don't double dip in healing increases, they gain the same percentual bonus from the transfer
  SPELLS.BEACON_OF_LIGHT_HEAL.id,
  SPELLS.LEECH.id,

  // There trinkets are confirmed to also be increased:
  // Proof: https://www.warcraftlogs.com/reports/4AVZqJTgyhG2F368/#fight=46&source=4&view=events&pins=2%24Off%24%23244F4B%24auras-gained%24-1%240.0.0.Any%240.0.0.Any%24true%240.0.0.Any%24true%24216331%24true%24true see the events at 00:03:39.013 and 00:03:40.369.
  SPELLS.AVENGING_CRUSADER_HEAL_NORMAL.id,
  SPELLS.AVENGING_CRUSADER_HEAL_CRIT.id,
];

// TODO: Feed this with the SpellInfo config
export const ABILITIES_AFFECTED_BY_MASTERY = [
  SPELLS.HOLY_SHOCK_HEAL.id,
  SPELLS.LIGHT_OF_DAWN_HEAL.id,
  SPELLS.FLASH_OF_LIGHT.id,
  TALENTS.LIGHT_OF_THE_MARTYR_TALENT.id,
  SPELLS.HOLY_PRISM_HEAL.id,
  SPELLS.HOLY_PRISM_HEAL_DIRECT.id,
  SPELLS.JUDGMENT_OF_LIGHT_HEAL.id,
  SPELLS.WORD_OF_GLORY.id,
  TALENTS.ETERNAL_FLAME_TALENT.id,
  SPELLS.HOLY_LIGHT.id,
  SPELLS.GOLDEN_PATH_HEAL_TALENT.id,
  SPELLS.SEAL_OF_MERCY_HEAL_TALENT.id,
  SPELLS.TYRS_DELIVERANCE_HEALING_INCREASE.id,
];

// Talent Constants
export const BLESSING_OF_ANSHE_INCREASE = 2.0;
export const DIVINE_REVELATIONS_INCREASE = 0.2;
export const PROTECTION_OF_TYR_INCREASE = 0.1;
export const RECLAMATION_MAX_INCREASE = 0.5;
export const RISING_SUNLIGHT_MAX_INCREASE = 0.1;
export const UNENDING_LIGHT_INCREASE = 0.05; // per stack
export const GLEAMING_RAYS_INCREASE = 0.05;
export const BLESSING_OF_SEASONS_DURATION = 30;
export const BLESSING_OF_SPRING_INCREASE = 0.15;
export const BLESSING_OF_SPRING_TAKEN_INCREASE = 0.3;
export const BLESSING_OF_AUTUMN_REDUCTION = 0.3;
export const BLESSING_OF_WINTER_RESTORE = 0.01;
export const T33_DIVINE_TOLL_REDUCTION = 1000;
export const LAYING_DOWN_ARMS_REDUCTION = 15000;
export const VALIANCE_REDUCTION = 3000;
export const CRUSADERS_MIGHT_REDUCTION = 1500;
export const IMBUED_INFUSIONS_REDUCTION = 1000;
export const TIRIONS_DEVOTION_REDUCTION = 1500; // per holy power
export const LIGHTS_PROTECTION_DAMAGE_REDUCTION = 0.05;
export const JUDGMENT_OF_LIGHT_HEALS = 5;
export const SOLAR_GRACE_INCREASE = 0.02; // per stack
export const SECOND_SUNRISE_CHANCE = 0.15;

// Beacon Constants & Functions
export const BEACON_TRANSFERING_ABILITIES = {
  [SPELLS.HOLY_SHOCK_HEAL.id]: 1,
  [SPELLS.LIGHT_OF_DAWN_HEAL.id]: 0.5,
  [SPELLS.FLASH_OF_LIGHT.id]: 1,
  [SPELLS.HOLY_PRISM_HEAL.id]: 0.5,
  [SPELLS.HOLY_PRISM_HEAL_DIRECT.id]: 1,
  [SPELLS.AVENGING_CRUSADER_HEAL_NORMAL.id]: 1,
  [SPELLS.AVENGING_CRUSADER_HEAL_CRIT.id]: 1,
  [SPELLS.WORD_OF_GLORY.id]: 1,
  [SPELLS.HOLY_LIGHT.id]: 1,
  [SPELLS.GOLDEN_PATH_HEAL_TALENT.id]: 1,
  [SPELLS.TYRS_DELIVERANCE_HEALING_INCREASE.id]: 1,
  [SPELLS.RESPLENDENT_LIGHT_HEAL.id]: 1,
  [SPELLS.SEAL_OF_THE_CRUSADER_HEAL.id]: 1,
  [SPELLS.AURA_OF_MERCY_HEAL.id]: 1,
  [TALENTS.ETERNAL_FLAME_TALENT.id]: 1,
  [TALENTS.TRUTH_PREVAILS_TALENT.id]: 1,
  [SPELLS.TRUTH_PREVAILS_HEAL.id]: 1,
  [SPELLS.SUN_SEAR_HEAL.id]: 1,
  [SPELLS.HAMMER_AND_ANVIL_HEAL.id]: 1,
  [SPELLS.VENERATION_HEAL.id]: 1,
  [SPELLS.VENERATION_HEAL_CRIT.id]: 1,
  [SPELLS.LIGHTBEARER_HEAL.id]: 1,
  [SPELLS.RADIANT_AURA_HEAL.id]: 1,
  [SPELLS.SACRED_WORD_HEAL.id]: 1,
  [SPELLS.HOLY_RITUAL_HEAL.id]: 1,
  [SPELLS.LIGHTFORGED_BLESSING.id]: 1,

  // TODO: figure out beacon healing for new LotM
  // [TALENTS.LIGHT_OF_THE_MARTYR_TALENT.id]: (player: Combatant) =>
  //   player.hasBuff(SPELLS.MARAADS_DYING_BREATH_BUFF.id) ? 1 : undefined,
};

export function getBeaconSpellFactor(spellID: number, player: Combatant): number | undefined {
  const factor = BEACON_TRANSFERING_ABILITIES[spellID];
  if (!factor) {
    return undefined;
  }
  return factor;
}

export const enum BEACON_TYPE {
  BEACON_OF_LIGHT,
  BEACON_OF_FAITH,
  BEACON_OF_VIRTUE,
  BEACON_OF_THE_SAVIOR,
}

export const BEACON_SPELL_IDS: Record<BEACON_TYPE, readonly number[]> = {
  [BEACON_TYPE.BEACON_OF_LIGHT]: [SPELLS.BEACON_OF_LIGHT_CAST_AND_BUFF.id],
  [BEACON_TYPE.BEACON_OF_FAITH]: [
    SPELLS.BEACON_OF_LIGHT_CAST_AND_BUFF.id,
    TALENTS.BEACON_OF_FAITH_TALENT.id,
  ],
  [BEACON_TYPE.BEACON_OF_VIRTUE]: [TALENTS.BEACON_OF_VIRTUE_TALENT.id],
  [BEACON_TYPE.BEACON_OF_THE_SAVIOR]: [SPELLS.BEACON_OF_THE_SAVIOR_BUFF.id],
} as const;

// Holy Power Constants
export const HOLY_POWER_BUILDERS: Spell[] = [
  SPELLS.CRUSADER_STRIKE,
  SPELLS.JUDGMENT_CAST_HOLY,
  TALENTS.DIVINE_TOLL_TALENT,
  TALENTS.HAMMER_OF_WRATH_TALENT,
  TALENTS.HOLY_SHOCK_TALENT,
];

// Misc Constants
export const SPELL_COLORS = {
  HAMMER_OF_WRATH: '#70C1B3',
  HOLY_SHOCK: '#f4ecb1',
  JUDGMENT: '#F8b700',
  DIVINE_TOLL: '#3185fC',
  BEACON_OF_LIGHT: '#f890bd',
  CRUSADER_STRIKE: '#F9DC5C',
  FLASH_OF_LIGHT: '#FFFDE7',
  HOLY_LIGHT: '#F57C00',
  SECOND_SUNRISE: '#c5841d',
  BLESSED_ASSURANCE: '#fdfbce',
  DAWNLIGHT: '#f7ca69',
  DAWNLIGHT_AOE: '#dfb147',
  SUNS_AVATAR: '#fbf89e',
  SUNS_AVATAR_SELF: '#d9c381',
};

export const BLESSING_OF_SEASONS_BUFFS = [
  SPELLS.BLESSING_OF_AUTUMN_TALENT,
  SPELLS.BLESSING_OF_WINTER_TALENT,
  SPELLS.BLESSING_OF_SPRING_TALENT,
  SPELLS.BLESSING_OF_SUMMER_TALENT,
];
