import SPELLS from 'common/SPELLS';

export const DAMAGING_ABILITIES = [
  SPELLS.STARSURGE_MOONKIN.id,
  SPELLS.STARSURGE_AFFINITY.id,
  SPELLS.STARFIRE.id,
  SPELLS.WRATH_MOONKIN.id,
  SPELLS.WRATH.id,
  SPELLS.SUNFIRE_CAST.id,
  SPELLS.MOONFIRE.id,
  SPELLS.STARFALL_CAST.id,
  SPELLS.FULL_MOON.id,
  SPELLS.HALF_MOON.id,
];

export default DAMAGING_ABILITIES;
