import SPELLS from 'common/SPELLS';

// Based on spelldata for Avenging Wrath
// Avenging Wrath also increases melee damage by 20% - this is added in their modules.
export const ABILITIES_AFFECTED_BY_DAMAGE_INCREASES = [
  SPELLS.CRUSADER_STRIKE,
  SPELLS.JUDGMENT_CAST,
  SPELLS.TEMPLARS_VERDICT_DAMAGE,
  SPELLS.BLADE_OF_JUSTICE,
  SPELLS.DIVINE_STORM_DAMAGE,
  SPELLS.EXECUTION_SENTENCE_TALENT,
  SPELLS.CONSECRATION_CAST,
  SPELLS.ZEAL_DAMAGE,
  SPELLS.HAMMER_OF_WRATH,
  SPELLS.WAKE_OF_ASHES,
  SPELLS.JUSTICARS_VENGEANCE_TALENT,
  SPELLS.EYE_FOR_AN_EYE_TALENT,
  SPELLS.SANCTIFIED_WRATH_DAMAGE
];

// Stuff like Retribution mastery and Execution sentence increases damage done by these sources of holy damage
export const ABILITIES_AFFECTED_BY_HOLY_DAMAGE_INCREASES = [
  SPELLS.JUDGMENT_CAST,
  SPELLS.TEMPLARS_VERDICT_DAMAGE,
  SPELLS.DIVINE_STORM_DAMAGE,
  SPELLS.CONSECRATION_CAST,
  SPELLS.ZEAL_DAMAGE,
  SPELLS.HAMMER_OF_WRATH,
  SPELLS.WAKE_OF_ASHES,
  SPELLS.JUSTICARS_VENGEANCE_TALENT,
  SPELLS.SANCTIFIED_WRATH_DAMAGE,
];

export const EMPYREAN_POWER_CHANCE = .15;
