import SPELLS from 'common/SPELLS';

export const ABILITIES_AFFECTED_BY_MASTERY = [
  SPELLS.TIGER_PALM.id,
  SPELLS.BLACKOUT_KICK.id,
  SPELLS.FISTS_OF_FURY_CAST.id,
  SPELLS.RISING_SUN_KICK.id,
  SPELLS.CHI_WAVE_TALENT.id,
  SPELLS.STRIKE_OF_THE_WINDLORD.id,
  SPELLS.SPINNING_CRANE_KICK.id,
  SPELLS.FLYING_SERPENT_KICK.id,
];
