import type { RetailSpell } from 'wow-dbc';
const SPELLS = {
  DEVOTION_AURA: {
    id: 465,
    type: 'learned',
    taughtBy: 385633,
    iconID: 135893,
    passive: false,
    name: 'Devotion Aura',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'spell_holy_devotionaura.jpg',
  },
  LAY_ON_HANDS_TALENT: {
    id: 633,
    granted: true,
    requiresTalentEntry: [102583],
    type: 'talent',
    iconID: 135928,
    passive: false,
    name: 'Lay on Hands',
    cooldown: {
      duration: 600000,
      hasted: false,
    },
    icon: 'spell_holy_layonhands.jpg',
  },
  DIVINE_SHIELD: {
    id: 642,
    type: 'baseline',
    iconID: 524354,
    passive: false,
    name: 'Divine Shield',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 300000,
      hasted: false,
    },
    icon: 'spell_holy_divineshield.jpg',
  },
  HAMMER_OF_JUSTICE: {
    id: 853,
    type: 'baseline',
    iconID: 135963,
    passive: false,
    name: 'Hammer of Justice',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
      modifiers: [
        {
          duration: -15000,
          hasted: false,
          requiredSpells: [234299],
        },
      ],
    },
    icon: 'spell_holy_sealofmight.jpg',
  },
  BLESSING_OF_PROTECTION_TALENT: {
    id: 1022,
    granted: false,
    requiresTalentEntry: [102604],
    type: 'talent',
    iconID: 135964,
    passive: false,
    name: 'Blessing of Protection',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    charges: {
      max: 1,
    },
    cooldown: {
      duration: 300000,
      hasted: false,
      modifiers: [
        {
          duration: -45000,
          requiredSpells: [378425],
        },
        {
          duration: -60000,
          requiredSpells: [384909],
        },
      ],
    },
    icon: 'spell_holy_sealofprotection.jpg',
  },
  BLESSING_OF_FREEDOM_TALENT: {
    id: 1044,
    granted: false,
    requiresTalentEntry: [128251],
    type: 'talent',
    iconID: 135968,
    passive: false,
    name: 'Blessing of Freedom',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    charges: {
      max: 1,
    },
    cooldown: {
      duration: 25000,
      hasted: false,
    },
    icon: 'spell_holy_sealofvalor.jpg',
  },
  SENSE_UNDEAD: {
    id: 5502,
    type: 'baseline',
    iconID: 135974,
    passive: false,
    name: 'Sense Undead',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    icon: 'spell_holy_senseundead.jpg',
  },
  BLESSING_OF_SACRIFICE_TALENT: {
    id: 6940,
    granted: false,
    requiresTalentEntry: [102602],
    type: 'talent',
    iconID: 135966,
    passive: false,
    name: 'Blessing of Sacrifice',
    cooldown: {
      duration: 120000,
      hasted: false,
      modifiers: [
        {
          duration: -60000,
          hasted: false,
          requiredSpells: [384820],
        },
      ],
    },
    icon: 'spell_holy_sealofsacrifice.jpg',
  },
  REDEMPTION: {
    id: 7328,
    type: 'baseline',
    iconID: 135955,
    passive: false,
    name: 'Redemption',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 10000,
    },
    icon: 'spell_holy_resurrection.jpg',
  },
  TURN_EVIL_TALENT: {
    id: 10326,
    granted: false,
    requiresTalentEntry: [102623],
    type: 'talent',
    iconID: 571559,
    passive: false,
    name: 'Turn Evil',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
    castTime: {
      duration: 1500,
    },
    icon: 'ability_paladin_turnevil.jpg',
  },
  SUMMON_WARHORSE: {
    id: 13819,
    type: 'baseline',
    iconID: 136103,
    passive: false,
    name: 'Summon Warhorse',
    castTime: {
      duration: 1500,
    },
    icon: 'spell_nature_swiftness.jpg',
  },
  FLASH_OF_LIGHT: {
    id: 19750,
    type: 'baseline',
    iconID: 135907,
    passive: false,
    name: 'Flash of Light',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 1500,
    },
    icon: 'spell_holy_flashheal.jpg',
  },
  JUDGMENT_BASELINE: {
    id: 20271,
    type: 'baseline',
    iconID: 135959,
    passive: false,
    name: 'Judgment',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    charges: {
      max: 1,
      modifiers: [
        {
          max: 1,
          requiredSpells: [204023],
        },
      ],
    },
    cooldown: {
      duration: 4949.999999999999,
      hasted: true,
    },
    icon: 'spell_holy_righteousfury.jpg',
  },
  JUDGMENT: {
    id: 275779,
    type: 'baseline',
    overrides: 20271,
    iconID: 135959,
    passive: false,
    hidden: 'unless-learned',
    name: 'Judgment',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    charges: {
      max: 1,
      modifiers: [
        {
          max: 1,
          requiredSpells: [204023],
        },
      ],
    },
    cooldown: {
      duration: 4949.999999999999,
      hasted: true,
    },
    icon: 'spell_holy_righteousfury.jpg',
  },
  SUMMON_CHARGER: {
    id: 23214,
    type: 'baseline',
    iconID: 132226,
    passive: false,
    name: 'Summon Charger',
    castTime: {
      duration: 1500,
    },
    icon: 'ability_mount_charger.jpg',
  },
  HAMMER_OF_WRATH: {
    id: 24275,
    type: 'baseline',
    iconID: 7439209,
    passive: false,
    name: 'Hammer of Wrath',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    charges: {
      max: 1,
    },
    cooldown: {
      duration: 7500,
      hasted: true,
    },
    icon: 'inv12_ability_paladin_hammerofwrath.jpg',
  },
  RIGHTEOUS_FURY_HIDDEN: {
    id: 25780,
    type: 'baseline',
    iconID: 135962,
    passive: true,
    hidden: 'always',
    name: 'Righteous Fury',
    icon: 'spell_holy_sealoffury.jpg',
  },
  HOLY_SHOCK_HIDDEN_1: {
    id: 25912,
    type: 'baseline',
    iconID: 135972,
    passive: false,
    hidden: 'always',
    name: 'Holy Shock',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'spell_holy_searinglight.jpg',
  },
  HOLY_SHOCK_HIDDEN_2: {
    id: 25914,
    type: 'baseline',
    iconID: 135972,
    passive: false,
    hidden: 'always',
    name: 'Holy Shock',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'spell_holy_searinglight.jpg',
  },
  CONSECRATION_1: {
    id: 26573,
    type: 'baseline',
    iconID: 135926,
    passive: false,
    name: 'Consecration',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 9000,
      hasted: true,
    },
    icon: 'spell_holy_innerfire.jpg',
  },
  CONSECRATION_2: {
    id: 81297,
    type: 'baseline',
    iconID: 135926,
    castableWhileCasting: true,
    passive: false,
    hidden: 'unless-learned',
    name: 'Consecration',
    icon: 'spell_holy_innerfire.jpg',
  },
  ARDENT_DEFENDER_TALENT: {
    id: 31850,
    granted: false,
    requiresTalentEntry: [102445],
    type: 'talent',
    iconID: 135870,
    passive: false,
    name: 'Ardent Defender',
    cooldown: {
      duration: 90000,
      hasted: false,
    },
    icon: 'spell_holy_ardentdefender.jpg',
  },
  AVENGING_WRATH_TALENT: {
    id: 31884,
    granted: false,
    requiresTalentEntry: [102448],
    visibleSpellId: 31884,
    type: 'talent',
    iconID: 135875,
    passive: false,
    name: 'Avenging Wrath',
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: 'spell_holy_avenginewrath.jpg',
  },
  AVENGERS_SHIELD_TALENT: {
    id: 31935,
    granted: false,
    requiresTalentEntry: [102471],
    type: 'talent',
    iconID: 135874,
    passive: false,
    name: "Avenger's Shield",
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 15000,
      hasted: true,
    },
    icon: 'spell_holy_avengersshield.jpg',
  },
  CRUSADER_AURA: {
    id: 32223,
    type: 'learned',
    taughtBy: 385633,
    iconID: 135890,
    passive: false,
    name: 'Crusader Aura',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'spell_holy_crusaderaura.jpg',
  },
  SUMMON_THALASSIAN_CHARGER: {
    id: 34767,
    type: 'baseline',
    iconID: 132226,
    passive: false,
    name: 'Summon Thalassian Charger',
    castTime: {
      duration: 1500,
    },
    icon: 'ability_mount_charger.jpg',
  },
  SUMMON_THALASSIAN_WARHORSE: {
    id: 34769,
    type: 'baseline',
    iconID: 136103,
    passive: false,
    name: 'Summon Thalassian Warhorse',
    castTime: {
      duration: 1500,
    },
    icon: 'spell_nature_swiftness.jpg',
  },
  CRUSADER_STRIKE: {
    id: 35395,
    type: 'baseline',
    iconID: 135891,
    passive: false,
    name: 'Crusader Strike',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    charges: {
      max: 2,
    },
    cooldown: {
      duration: 6000,
      hasted: true,
    },
    icon: 'spell_holy_crusaderstrike.jpg',
  },
  SANCTIFIED_WRATH_TALENT: {
    id: 53376,
    granted: false,
    requiresTalentEntry: [128278],
    type: 'talent',
    iconID: 236259,
    passive: true,
    hidden: 'always',
    name: 'Sanctified Wrath',
    icon: 'ability_paladin_judgementsofthejust.jpg',
  },
  HAMMER_OF_THE_RIGHTEOUS_TALENT: {
    id: 53595,
    granted: false,
    requiresTalentEntry: [102431],
    overrides: 35395,
    type: 'talent',
    iconID: 236253,
    passive: false,
    name: 'Hammer of the Righteous',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    charges: {
      max: 2,
    },
    cooldown: {
      duration: 5000,
      hasted: true,
    },
    icon: 'ability_paladin_hammeroftherighteous.jpg',
  },
  SHIELD_OF_THE_RIGHTEOUS: {
    id: 53600,
    type: 'baseline',
    iconID: 236265,
    passive: false,
    name: 'Shield of the Righteous',
    cooldown: {
      duration: 1000,
      hasted: true,
    },
    icon: 'ability_paladin_shieldofvengeance.jpg',
  },
  BEACON_OF_LIGHT_HIDDEN: {
    id: 53652,
    type: 'baseline',
    iconID: 236247,
    passive: false,
    hidden: 'always',
    name: 'Beacon of Light',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'ability_paladin_beaconoflight.jpg',
  },
  HAND_OF_RECKONING: {
    id: 62124,
    type: 'baseline',
    iconID: 135984,
    passive: false,
    name: 'Hand of Reckoning',
    charges: {
      max: 1,
    },
    cooldown: {
      duration: 8000,
      hasted: false,
    },
    icon: 'spell_holy_unyieldingfaith.jpg',
  },
  ARDENT_DEFENDER: {
    id: 66235,
    type: 'baseline',
    iconID: 135920,
    passive: false,
    hidden: 'unless-learned',
    name: 'Ardent Defender',
    icon: 'spell_holy_holybolt.jpg',
  },
  SUMMON_SUNWALKER_KODO: {
    id: 69820,
    type: 'baseline',
    iconID: 132245,
    passive: false,
    name: 'Summon Sunwalker Kodo',
    castTime: {
      duration: 1500,
    },
    icon: 'ability_mount_kodo_03.jpg',
  },
  SUMMON_GREAT_SUNWALKER_KODO: {
    id: 69826,
    type: 'baseline',
    iconID: 329848,
    passive: false,
    name: 'Summon Great Sunwalker Kodo',
    castTime: {
      duration: 1500,
    },
    icon: 'ability_mount_kodosunwalkerelite.jpg',
  },
  SUMMON_EXARCHS_ELEKK: {
    id: 73629,
    type: 'baseline',
    iconID: 136103,
    passive: false,
    name: "Summon Exarch's Elekk",
    castTime: {
      duration: 1500,
    },
    icon: 'spell_nature_swiftness.jpg',
  },
  SUMMON_GREAT_EXARCHS_ELEKK: {
    id: 73630,
    type: 'baseline',
    iconID: 132226,
    passive: false,
    name: "Summon Great Exarch's Elekk",
    castTime: {
      duration: 1500,
    },
    icon: 'ability_mount_charger.jpg',
  },
  MASTERY_DIVINE_BULWARK_PASSIVE_1: {
    id: 76671,
    type: 'baseline',
    iconID: 135923,
    passive: true,
    name: 'Mastery: Divine Bulwark',
    icon: 'spell_holy_holyprotection.jpg',
  },
  MASTERY_DIVINE_BULWARK_PASSIVE_2: {
    id: 317907,
    type: 'baseline',
    iconID: 135923,
    passive: true,
    name: 'Mastery: Divine Bulwark',
    icon: 'spell_holy_holyprotection.jpg',
  },
  PARRY_HIDDEN: {
    id: 82242,
    type: 'baseline',
    iconID: 132269,
    passive: true,
    hidden: 'always',
    name: 'Parry',
    icon: 'ability_parry.jpg',
  },
  GRAND_CRUSADER_TALENT: {
    id: 85043,
    granted: false,
    requiresTalentEntry: [102453],
    type: 'talent',
    iconID: 133176,
    passive: true,
    hidden: 'always',
    name: 'Grand Crusader',
    icon: 'inv_helmet_74.jpg',
  },
  WORD_OF_GLORY: {
    id: 85673,
    type: 'baseline',
    iconID: 133192,
    passive: false,
    name: 'Word of Glory',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'inv_helmet_96.jpg',
  },
  PLATE_SPECIALIZATION_HIDDEN: {
    id: 86102,
    type: 'baseline',
    iconID: 132750,
    passive: true,
    hidden: 'always',
    name: 'Plate Specialization',
    icon: 'inv_chest_plate15.jpg',
  },
  GUARDIAN_OF_ANCIENT_KINGS_TALENT: {
    id: 86659,
    granted: false,
    requiresTalentEntry: [102456],
    type: 'talent',
    iconID: 135919,
    passive: false,
    name: 'Guardian of Ancient Kings',
    charges: {
      max: 1,
      modifiers: [
        {
          max: 1,
          requiredSpells: [1246481],
        },
      ],
    },
    cooldown: {
      duration: 180000,
      hasted: false,
    },
    icon: 'spell_holy_heroism.jpg',
  },
  LIGHT_OF_THE_ANCIENT_KINGS_HIDDEN: {
    id: 86678,
    type: 'baseline',
    iconID: 135920,
    passive: false,
    hidden: 'always',
    name: 'Light of the Ancient Kings',
    icon: 'spell_holy_holybolt.jpg',
  },
  ANCIENT_FURY: {
    id: 86704,
    type: 'baseline',
    iconID: 236262,
    passive: false,
    hidden: 'unless-learned',
    name: 'Ancient Fury',
    icon: 'ability_paladin_sanctifiedwrath.jpg',
  },
  PROTECTOR_OF_THE_INNOCENT_HIDDEN: {
    id: 94289,
    type: 'baseline',
    iconID: 460690,
    passive: false,
    hidden: 'always',
    name: 'Protector of the Innocent',
    icon: 'ability_paladin_protectoroftheinnocent.jpg',
  },
  REBUKE_TALENT: {
    id: 96231,
    granted: false,
    requiresTalentEntry: [102591],
    type: 'talent',
    iconID: 523893,
    passive: false,
    name: 'Rebuke',
    cooldown: {
      duration: 15000,
      hasted: false,
    },
    icon: 'spell_holy_rebuke.jpg',
  },
  SANCTUARY_HIDDEN: {
    id: 105805,
    type: 'baseline',
    iconID: 136051,
    passive: true,
    hidden: 'always',
    name: 'Sanctuary',
    icon: 'spell_nature_lightningshield.jpg',
  },
  UNBREAKABLE_SPIRIT_TALENT: {
    id: 114154,
    granted: false,
    requiresTalentEntry: [102603],
    type: 'talent',
    iconID: 135921,
    passive: true,
    hidden: 'always',
    name: 'Unbreakable Spirit',
    icon: 'spell_holy_holyguidance.jpg',
  },
  HOLY_PRISM_1: {
    id: 114852,
    type: 'baseline',
    iconID: 613408,
    passive: false,
    hidden: 'unless-learned',
    name: 'Holy Prism',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 20000,
      hasted: false,
      modifiers: [
        {
          duration: -15000,
          hasted: false,
          requiredSpells: [379391],
        },
      ],
    },
    icon: 'spell_paladin_holyprism.jpg',
  },
  HOLY_PRISM_2: {
    id: 114871,
    type: 'baseline',
    iconID: 613408,
    passive: false,
    hidden: 'unless-learned',
    name: 'Holy Prism',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 20000,
      hasted: false,
      modifiers: [
        {
          duration: -15000,
          hasted: false,
          requiredSpells: [379391],
        },
      ],
    },
    icon: 'spell_paladin_holyprism.jpg',
  },
  LIGHTS_HAMMER: {
    id: 114919,
    type: 'baseline',
    iconID: 613955,
    passive: false,
    name: "Light's Hammer",
    icon: 'spell_paladin_lightshammer.jpg',
  },
  BOUNDLESS_CONVICTION_HIDDEN: {
    id: 115675,
    type: 'baseline',
    iconID: 454051,
    passive: true,
    hidden: 'always',
    name: 'Boundless Conviction',
    icon: 'trade_archaeology_gemmeddrinkingcup.jpg',
  },
  BLINDING_LIGHT_TALENT: {
    id: 115750,
    granted: false,
    requiresTalentEntry: [102584],
    type: 'talent',
    iconID: 571553,
    passive: false,
    name: 'Blinding Light',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 90000,
      hasted: false,
      modifiers: [
        {
          duration: -15000,
          hasted: false,
          requiredSpells: [469325],
        },
      ],
    },
    icon: 'ability_paladin_blindinglight.jpg',
  },
  CONTEMPLATION: {
    id: 121183,
    type: 'baseline',
    iconID: 134916,
    passive: false,
    hidden: 'unless-learned',
    name: 'Contemplation',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 8000,
      hasted: false,
    },
    icon: 'inv_relics_libramofhope.jpg',
  },
  BLOCK_HIDDEN: {
    id: 123830,
    type: 'baseline',
    iconID: 134950,
    passive: true,
    hidden: 'always',
    name: 'Block',
    icon: 'inv_shield_04.jpg',
  },
  PALADIN_HIDDEN_1: {
    id: 137026,
    type: 'baseline',
    iconID: 236216,
    passive: true,
    hidden: 'always',
    name: 'Paladin',
    icon: 'ability_mage_firestarter.jpg',
  },
  PALADIN_HIDDEN_2: {
    id: 462092,
    type: 'baseline',
    iconID: 136243,
    passive: true,
    hidden: 'always',
    name: 'Paladin',
    icon: 'trade_engineering.jpg',
  },
  PROTECTION_PALADIN_HIDDEN_1: {
    id: 137028,
    type: 'baseline',
    iconID: 236216,
    passive: true,
    hidden: 'always',
    name: 'Protection Paladin',
    icon: 'ability_mage_firestarter.jpg',
  },
  PROTECTION_PALADIN_HIDDEN_2: {
    id: 462095,
    type: 'baseline',
    iconID: 136243,
    passive: true,
    hidden: 'always',
    name: 'Protection Paladin',
    icon: 'trade_engineering.jpg',
  },
  PROTECTION_PALADIN_HIDDEN_3: {
    id: 1256936,
    type: 'baseline',
    iconID: 236216,
    passive: true,
    hidden: 'always',
    name: 'Protection Paladin',
    icon: 'ability_mage_firestarter.jpg',
  },
  LIGHTS_REVOCATION_TALENT: {
    id: 146956,
    granted: false,
    requiresTalentEntry: [102596],
    type: 'talent',
    iconID: 524354,
    passive: true,
    hidden: 'always',
    name: "Light's Revocation",
    icon: 'spell_holy_divineshield.jpg',
  },
  RIPOSTE_PASSIVE: {
    id: 161800,
    type: 'baseline',
    iconID: 135340,
    passive: true,
    name: 'Riposte',
    icon: 'inv_sword_30.jpg',
  },
  JAILERS_JUDGMENT: {
    id: 162056,
    type: 'baseline',
    iconID: 133048,
    passive: false,
    hidden: 'unless-learned',
    name: "Jailer's Judgment",
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 180000,
      hasted: false,
    },
    icon: 'inv_hammer_11.jpg',
  },
  STAT_NEGATION_AURA_STRENGTH_TANK_HIDDEN: {
    id: 162702,
    type: 'baseline',
    iconID: 136243,
    passive: true,
    hidden: 'always',
    name: 'Stat Negation Aura - Strength Tank',
    icon: 'trade_engineering.jpg',
  },
  BLESSING_OF_DAWN_TALENT: {
    id: 183416,
    granted: false,
    requiresTalentEntry: [115673],
    type: 'talent',
    iconID: 618798,
    passive: true,
    hidden: 'always',
    name: 'Blessing of Dawn',
    icon: 'achievement_zone_valeofeternalblossoms.jpg',
  },
  RETRIBUTION_AURA: {
    id: 183435,
    type: 'baseline',
    iconID: 135889,
    passive: false,
    name: 'Retribution Aura',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'spell_holy_crusade.jpg',
  },
  DIVINE_STEED_TALENT: {
    id: 190784,
    granted: true,
    requiresTalentEntry: [102625],
    type: 'talent',
    iconID: 1360759,
    passive: false,
    name: 'Divine Steed',
    charges: {
      max: 1,
      modifiers: [
        {
          max: 1,
          requiredSpells: [230332],
        },
      ],
    },
    cooldown: {
      duration: 30000,
      hasted: false,
      modifiers: [
        {
          duration: -9000,
          requiredSpells: [469409],
        },
      ],
    },
    icon: 'ability_paladin_divinesteed.jpg',
  },
  HOLY_RITUAL_TALENT: {
    id: 199422,
    granted: false,
    requiresTalentEntry: [128262],
    type: 'talent',
    iconID: 134917,
    passive: true,
    hidden: 'always',
    name: 'Holy Ritual',
    icon: 'inv_relics_libramoftruth.jpg',
  },
  BLESSING_OF_SACRIFICE_PASSIVE: {
    id: 200327,
    type: 'baseline',
    iconID: 135966,
    passive: true,
    name: 'Blessing of Sacrifice',
    icon: 'spell_holy_sealofsacrifice.jpg',
  },
  TYRS_DELIVERANCE_1: {
    id: 200652,
    type: 'baseline',
    iconID: 1122562,
    passive: false,
    name: "Tyr's Deliverance",
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 90000,
      hasted: false,
    },
    castTime: {
      duration: 2000,
    },
    icon: 'inv_mace_2h_artifactsilverhand_d_01.jpg',
  },
  TYRS_DELIVERANCE_2: {
    id: 200654,
    type: 'baseline',
    iconID: 1122562,
    castableWhileCasting: true,
    passive: false,
    name: "Tyr's Deliverance",
    icon: 'inv_mace_2h_artifactsilverhand_d_01.jpg',
  },
  BLESSING_OF_SPELLWARDING_TALENT: {
    id: 204018,
    granted: false,
    requiresTalentEntry: [111886],
    type: 'talent',
    iconID: 135880,
    passive: false,
    name: 'Blessing of Spellwarding',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    charges: {
      max: 1,
    },
    cooldown: {
      duration: 300000,
      hasted: false,
      modifiers: [
        {
          duration: -45000,
          requiredSpells: [378425],
        },
        {
          duration: -60000,
          requiredSpells: [384909],
        },
      ],
    },
    icon: 'spell_holy_blessingofprotection.jpg',
  },
  BLESSED_HAMMER_TALENT: {
    id: 204019,
    granted: false,
    requiresTalentEntry: [102430],
    overrides: 35395,
    type: 'talent',
    iconID: 535595,
    passive: false,
    name: 'Blessed Hammer',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    charges: {
      max: 3,
    },
    cooldown: {
      duration: 5000,
      hasted: true,
    },
    icon: 'paladin_retribution.jpg',
  },
  CRUSADERS_JUDGMENT_TALENT: {
    id: 204023,
    granted: false,
    requiresTalentEntry: [102600],
    type: 'talent',
    iconID: 236251,
    passive: true,
    hidden: 'always',
    name: "Crusader's Judgment",
    icon: 'ability_paladin_enlightenedjudgements.jpg',
  },
  CONSECRATED_GROUND_TALENT: {
    id: 204054,
    granted: false,
    requiresTalentEntry: [102518],
    type: 'talent',
    iconID: 236260,
    passive: true,
    hidden: 'always',
    name: 'Consecrated Ground',
    icon: 'ability_paladin_righteousvengeance.jpg',
  },
  RIGHTEOUS_PROTECTOR_TALENT: {
    id: 204074,
    granted: false,
    requiresTalentEntry: [102440],
    type: 'talent',
    iconID: 236264,
    passive: true,
    hidden: 'always',
    name: 'Righteous Protector',
    icon: 'ability_paladin_shieldofthetemplar.jpg',
  },
  FINAL_STAND_TALENT: {
    id: 204077,
    granted: false,
    requiresTalentEntry: [102473],
    type: 'talent',
    iconID: 135889,
    passive: true,
    hidden: 'always',
    name: 'Final Stand',
    icon: 'spell_holy_crusade.jpg',
  },
  WAKE_OF_ASHES: {
    id: 205273,
    type: 'baseline',
    iconID: 1109508,
    passive: false,
    name: 'Wake of Ashes',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 'inv_sword_2h_artifactashbringer_d_01.jpg',
  },
  EYE_OF_TYR: {
    id: 209202,
    type: 'baseline',
    iconID: 1272527,
    passive: false,
    name: 'Eye of Tyr',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: 'inv_shield_1h_artifactnorgannon_d_01.jpg',
  },
  BULWARK_OF_ORDER_TALENT: {
    id: 209389,
    granted: false,
    requiresTalentEntry: [102468],
    type: 'talent',
    iconID: 135948,
    passive: true,
    hidden: 'always',
    name: 'Bulwark of Order',
    icon: 'spell_holy_pureofheart.jpg',
  },
  CLEANSE_TOXINS_TALENT: {
    id: 213644,
    granted: false,
    requiresTalentEntry: [102476],
    type: 'talent',
    iconID: 135953,
    passive: false,
    name: 'Cleanse Toxins',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    charges: {
      max: 1,
    },
    cooldown: {
      duration: 8000,
      hasted: false,
    },
    icon: 'spell_holy_renew.jpg',
  },
  DIVINE_PURPOSE_TALENT: {
    id: 223817,
    granted: false,
    requiresTalentEntry: [128244],
    type: 'talent',
    iconID: 135897,
    passive: true,
    hidden: 'always',
    name: 'Divine Purpose',
    icon: 'spell_holy_divinepurpose.jpg',
  },
  BLESSED_HAMMER_HIDDEN: {
    id: 229976,
    type: 'learned',
    taughtBy: 204019,
    iconID: 136051,
    passive: true,
    hidden: 'always',
    name: 'Blessed Hammer',
    icon: 'spell_nature_lightningshield.jpg',
  },
  CAVALIER_TALENT: {
    id: 230332,
    granted: false,
    requiresTalentEntry: [102592],
    type: 'talent',
    iconID: 1360759,
    passive: true,
    hidden: 'always',
    name: 'Cavalier',
    icon: 'ability_paladin_divinesteed.jpg',
  },
  GREATER_JUDGMENT_TALENT: {
    id: 231663,
    granted: false,
    requiresTalentEntry: [102590],
    type: 'talent',
    iconID: 135959,
    passive: true,
    hidden: 'always',
    name: 'Greater Judgment',
    icon: 'spell_holy_righteousfury.jpg',
  },
  FIST_OF_JUSTICE_TALENT: {
    id: 234299,
    granted: false,
    requiresTalentEntry: [136487],
    type: 'talent',
    iconID: 135906,
    passive: true,
    hidden: 'always',
    name: 'Fist of Justice',
    icon: 'spell_holy_fistofjustice.jpg',
  },
  SUMMON_DARKFORGE_RAM: {
    id: 270562,
    type: 'baseline',
    iconID: 1980723,
    passive: false,
    name: 'Summon Darkforge Ram',
    castTime: {
      duration: 1500,
    },
    icon: 'inv_dwarfpaladinram_red.jpg',
  },
  SUMMON_DAWNFORGE_RAM: {
    id: 270564,
    type: 'baseline',
    iconID: 1980722,
    passive: false,
    name: 'Summon Dawnforge Ram',
    castTime: {
      duration: 1500,
    },
    icon: 'inv_dwarfpaladinram_gold.jpg',
  },
  REDOUBT_TALENT: {
    id: 280373,
    granted: false,
    requiresTalentEntry: [102462],
    type: 'talent',
    iconID: 132359,
    passive: true,
    hidden: 'always',
    name: 'Redoubt',
    icon: 'ability_warrior_shieldguard.jpg',
  },
  CRUSADERS_DIREHORN: {
    id: 290608,
    type: 'baseline',
    iconID: 2564351,
    passive: false,
    name: "Crusader's Direhorn",
    castTime: {
      duration: 1500,
    },
    icon: 'inv_zandalaripaladinmount.jpg',
  },
  UNBOUND_FREEDOM_TALENT: {
    id: 305394,
    granted: false,
    requiresTalentEntry: [115479],
    type: 'talent',
    iconID: 135968,
    passive: true,
    hidden: 'always',
    name: 'Unbound Freedom',
    icon: 'spell_holy_sealofvalor.jpg',
  },
  JUDGMENT_PASSIVE_1: {
    id: 315867,
    type: 'baseline',
    iconID: 135959,
    passive: true,
    name: 'Judgment',
    icon: 'spell_holy_righteousfury.jpg',
  },
  JUDGMENT_PASSIVE_2: {
    id: 327977,
    type: 'baseline',
    iconID: 135959,
    passive: true,
    name: 'Judgment',
    icon: 'spell_holy_righteousfury.jpg',
  },
  WORD_OF_GLORY_PASSIVE: {
    id: 315921,
    type: 'baseline',
    iconID: 133192,
    passive: true,
    name: 'Word of Glory',
    icon: 'inv_helmet_96.jpg',
  },
  HAND_OF_THE_PROTECTOR_TALENT: {
    id: 315924,
    granted: false,
    requiresTalentEntry: [102438],
    type: 'talent',
    iconID: 236248,
    passive: true,
    hidden: 'always',
    name: 'Hand of the Protector',
    icon: 'ability_paladin_blessedhands.jpg',
  },
  AVENGING_WRATH_PASSIVE: {
    id: 317872,
    type: 'baseline',
    iconID: 135875,
    passive: true,
    name: 'Avenging Wrath',
    icon: 'spell_holy_avenginewrath.jpg',
  },
  RETRIBUTION_AURA_PASSIVE: {
    id: 317906,
    type: 'baseline',
    iconID: 135889,
    passive: true,
    name: 'Retribution Aura',
    icon: 'spell_holy_crusade.jpg',
  },
  DIVINE_STEED_PASSIVE: {
    id: 317911,
    type: 'baseline',
    iconID: 1360759,
    passive: true,
    name: 'Divine Steed',
    icon: 'ability_paladin_divinesteed.jpg',
  },
  CONCENTRATION_AURA: {
    id: 317920,
    type: 'learned',
    taughtBy: 385633,
    iconID: 135933,
    passive: false,
    name: 'Concentration Aura',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'spell_holy_mindsooth.jpg',
  },
  SHINING_LIGHT_TALENT: {
    id: 321136,
    granted: false,
    requiresTalentEntry: [102455],
    type: 'talent',
    iconID: 1360764,
    passive: true,
    hidden: 'always',
    name: 'Shining Light',
    icon: 'ability_paladin_toweroflight.jpg',
  },
  HAMMER_OF_WRATH_PASSIVE: {
    id: 326730,
    type: 'learned',
    taughtBy: 384376,
    iconID: 613533,
    passive: true,
    name: 'Hammer of Wrath',
    icon: 'spell_paladin_hammerofwrath.jpg',
  },
  CONSECRATION_PASSIVE: {
    id: 327980,
    type: 'baseline',
    iconID: 135926,
    passive: true,
    name: 'Consecration',
    icon: 'spell_holy_innerfire.jpg',
  },
  UNKNOWN_1: {
    id: 337287,
    type: 'baseline',
    passive: false,
    name: 'Unknown',
    icon: 'inv_axe_02.jpg',
  },
  UNKNOWN_2: {
    id: 344172,
    type: 'baseline',
    passive: false,
    name: 'Unknown',
    icon: 'inv_axe_02.jpg',
  },
  CRUSADER_STRIKE_PASSIVE: {
    id: 342348,
    type: 'baseline',
    iconID: 135891,
    passive: true,
    name: 'Crusader Strike',
    icon: 'spell_holy_crusaderstrike.jpg',
  },
  AEGIS_OF_LIGHT_PASSIVE_1: {
    id: 353367,
    type: 'baseline',
    iconID: 135909,
    passive: true,
    name: 'Aegis of Light',
    icon: 'spell_holy_greaterblessingoflight.jpg',
  },
  AEGIS_OF_LIGHT_PASSIVE_2: {
    id: 358934,
    type: 'baseline',
    iconID: 135909,
    passive: true,
    name: 'Aegis of Light',
    icon: 'spell_holy_greaterblessingoflight.jpg',
  },
  SUMMON_LIGHTFORGED_RUINSTRIDER: {
    id: 363613,
    type: 'baseline',
    iconID: 4070328,
    passive: false,
    name: 'Summon Lightforged Ruinstrider',
    castTime: {
      duration: 1500,
    },
    icon: 'inv_lightforgedtalbuk.jpg',
  },
  DIVINE_TOLL_TALENT: {
    id: 375576,
    granted: false,
    requiresTalentEntry: [136496],
    type: 'talent',
    iconID: 6035315,
    passive: false,
    hidden: 'unless-learned',
    name: 'Divine Toll',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
      modifiers: [
        {
          duration: -15000,
          hasted: false,
          requiredSpells: [379391],
        },
      ],
    },
    icon: 'inv_ability_paladin_divinetoll.jpg',
  },
  SEASONED_WARHORSE_HIDDEN: {
    id: 376996,
    type: 'baseline',
    iconID: 136103,
    passive: true,
    hidden: 'always',
    name: 'Seasoned Warhorse',
    icon: 'spell_nature_swiftness.jpg',
  },
  SEAL_OF_REPRISAL_TALENT: {
    id: 377053,
    granted: false,
    requiresTalentEntry: [102621],
    type: 'talent',
    iconID: 135962,
    passive: true,
    hidden: 'always',
    name: 'Seal of Reprisal',
    icon: 'spell_holy_sealoffury.jpg',
  },
  GOLDEN_PATH_TALENT: {
    id: 377128,
    granted: false,
    requiresTalentEntry: [128252],
    type: 'talent',
    iconID: 612098,
    passive: true,
    hidden: 'always',
    name: 'Golden Path',
    icon: 'ability_priest_cascade.jpg',
  },
  GIFT_OF_THE_GOLDEN_VALKYR_TALENT: {
    id: 378279,
    granted: false,
    requiresTalentEntry: [102449],
    type: 'talent',
    iconID: 1349535,
    passive: true,
    hidden: 'always',
    name: "Gift of the Golden Val'kyr",
    icon: 'inv_valkiergoldpet.jpg',
  },
  TYRS_ENFORCER_TALENT: {
    id: 378285,
    granted: false,
    requiresTalentEntry: [102437],
    type: 'talent',
    iconID: 237546,
    passive: true,
    hidden: 'always',
    name: "Tyr's Enforcer",
    icon: 'spell_holy_persecution.jpg',
  },
  LIGHT_OF_THE_TITANS_TALENT: {
    id: 378405,
    granted: false,
    requiresTalentEntry: [102472],
    type: 'talent',
    iconID: 461859,
    passive: true,
    hidden: 'always',
    name: 'Light of the Titans',
    icon: 'spell_paladin_lightofdawn.jpg',
  },
  UTHERS_COUNSEL_TALENT: {
    id: 378425,
    granted: false,
    requiresTalentEntry: [102469],
    type: 'talent',
    iconID: 135910,
    passive: true,
    hidden: 'always',
    name: "Uther's Counsel",
    icon: 'spell_holy_greaterblessingofsalvation.jpg',
  },
  SOARING_SHIELD_TALENT: {
    id: 378457,
    granted: false,
    requiresTalentEntry: [102434],
    type: 'talent',
    iconID: 1032476,
    passive: true,
    hidden: 'always',
    name: 'Soaring Shield',
    icon: 'spell_burningbladeshaman_lavaslash.jpg',
  },
  FERREN_MARCUSS_FERVOR_TALENT: {
    id: 378762,
    granted: false,
    requiresTalentEntry: [102446],
    type: 'talent',
    iconID: 135971,
    passive: true,
    hidden: 'always',
    name: "Ferren Marcus's Fervor",
    icon: 'spell_holy_sealofwrath.jpg',
  },
  FOCUSED_ENMITY_TALENT: {
    id: 378845,
    granted: false,
    requiresTalentEntry: [102435],
    type: 'talent',
    iconID: 612968,
    passive: true,
    hidden: 'always',
    name: 'Focused Enmity',
    icon: 'ability_priest_flashoflight.jpg',
  },
  SANCTUARY_TALENT: {
    id: 379021,
    granted: false,
    requiresTalentEntry: [102436],
    type: 'talent',
    iconID: 135926,
    passive: true,
    hidden: 'always',
    name: 'Sanctuary',
    icon: 'spell_holy_innerfire.jpg',
  },
  CONSECRATION_IN_FLAME_TALENT: {
    id: 379022,
    granted: false,
    requiresTalentEntry: [102450],
    type: 'talent',
    iconID: 135824,
    passive: true,
    hidden: 'always',
    name: 'Consecration in Flame',
    icon: 'spell_fire_sealoffire.jpg',
  },
  QUICKENED_INVOCATION_TALENT: {
    id: 379391,
    granted: false,
    requiresTalentEntry: [115168],
    type: 'talent',
    iconID: 135948,
    passive: true,
    hidden: 'always',
    name: 'Quickened Invocation',
    icon: 'spell_holy_pureofheart.jpg',
  },
  CRUSADERS_RESOLVE_TALENT: {
    id: 380188,
    granted: false,
    requiresTalentEntry: [102460],
    type: 'talent',
    iconID: 633042,
    passive: true,
    hidden: 'always',
    name: "Crusader's Resolve",
    icon: 'ability_priest_angelicbulwark.jpg',
  },
  RELENTLESS_INQUISITOR_TALENT: {
    id: 383388,
    granted: false,
    requiresTalentEntry: [102475],
    type: 'talent',
    iconID: 135934,
    passive: true,
    hidden: 'always',
    name: 'Relentless Inquisitor',
    icon: 'spell_holy_mindvision.jpg',
  },
  AVENGING_WRATH_HIDDEN: {
    id: 384376,
    type: 'baseline',
    iconID: 135875,
    passive: true,
    hidden: 'always',
    name: 'Avenging Wrath',
    icon: 'spell_holy_avenginewrath.jpg',
  },
  SEAL_OF_CHARITY_TALENT: {
    id: 384815,
    granted: false,
    requiresTalentEntry: [102467],
    type: 'talent',
    iconID: 1386546,
    passive: true,
    hidden: 'always',
    name: 'Seal of Charity',
    icon: 'spell_priest_power-word.jpg',
  },
  SACRIFICE_OF_THE_JUST_TALENT: {
    id: 384820,
    granted: false,
    requiresTalentEntry: [102595],
    type: 'talent',
    iconID: 135966,
    passive: true,
    hidden: 'always',
    name: 'Sacrifice of the Just',
    icon: 'spell_holy_sealofsacrifice.jpg',
  },
  IMPROVED_BLESSING_OF_PROTECTION_TALENT: {
    id: 384909,
    granted: false,
    requiresTalentEntry: [102606],
    type: 'talent',
    iconID: 135964,
    passive: true,
    hidden: 'always',
    name: 'Improved Blessing of Protection',
    icon: 'spell_holy_sealofprotection.jpg',
  },
  RECOMPENSE_TALENT: {
    id: 384914,
    granted: false,
    requiresTalentEntry: [102594],
    type: 'talent',
    iconID: 1786407,
    passive: true,
    hidden: 'always',
    name: 'Recompense',
    icon: 'ability_racial_foregedinflames.jpg',
  },
  AFTERIMAGE_TALENT: {
    id: 385414,
    granted: false,
    requiresTalentEntry: [115480],
    type: 'talent',
    iconID: 237537,
    passive: true,
    hidden: 'always',
    name: 'Afterimage',
    icon: 'spell_holy_aspiration.jpg',
  },
  OBDURACY_TALENT: {
    id: 385427,
    granted: false,
    requiresTalentEntry: [102622],
    type: 'talent',
    iconID: 571558,
    passive: true,
    hidden: 'always',
    name: 'Obduracy',
    icon: 'ability_paladin_speedoflight.jpg',
  },
  SEAL_OF_MIGHT_TALENT: {
    id: 385450,
    granted: false,
    requiresTalentEntry: [102612],
    type: 'talent',
    iconID: 135971,
    passive: true,
    hidden: 'always',
    name: 'Seal of Might',
    icon: 'spell_holy_sealofwrath.jpg',
  },
  HOLY_AEGIS_TALENT: {
    id: 385515,
    granted: false,
    requiresTalentEntry: [102597],
    type: 'talent',
    iconID: 236267,
    passive: true,
    hidden: 'always',
    name: 'Holy Aegis',
    icon: 'ability_paladin_touchedbylight.jpg',
  },
  AURAS_OF_THE_RESOLUTE_TALENT: {
    id: 385633,
    granted: true,
    requiresTalentEntry: [102587],
    type: 'talent',
    iconID: 135893,
    passive: true,
    hidden: 'always',
    name: 'Auras of the Resolute',
    icon: 'spell_holy_devotionaura.jpg',
  },
  BULWARK_OF_RIGHTEOUS_FURY_TALENT: {
    id: 386653,
    granted: false,
    requiresTalentEntry: [102457],
    type: 'talent',
    iconID: 135965,
    passive: true,
    hidden: 'always',
    name: 'Bulwark of Righteous Fury',
    icon: 'spell_holy_sealofrighteousness.jpg',
  },
  DIVINE_RESONANCE_TALENT: {
    id: 386738,
    granted: false,
    requiresTalentEntry: [102443],
    type: 'talent',
    iconID: 656322,
    passive: true,
    hidden: 'always',
    name: 'Divine Resonance',
    icon: 'ability_mount_goatmountwhite.jpg',
  },
  EMPYREAL_WARD_TALENT: {
    id: 387791,
    granted: false,
    requiresTalentEntry: [128255],
    type: 'talent',
    iconID: 135928,
    passive: true,
    hidden: 'always',
    name: 'Empyreal Ward',
    icon: 'spell_holy_layonhands.jpg',
  },
  SENTINEL_TALENT: {
    id: 389539,
    granted: false,
    requiresTalentEntry: [102447],
    visibleSpellId: 389539,
    type: 'talent',
    iconID: 135922,
    passive: false,
    name: 'Sentinel',
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'spell_holy_holynova.jpg',
  },
  INTERCESSION: {
    id: 391054,
    type: 'baseline',
    iconID: 4726195,
    passive: false,
    name: 'Intercession',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    cooldown: {
      duration: 600000,
      hasted: false,
    },
    castTime: {
      duration: 2000,
    },
    icon: 'ability_paladin_intercession.jpg',
  },
  ZEALOTS_PARAGON_TALENT: {
    id: 391142,
    granted: false,
    requiresTalentEntry: [102433],
    type: 'talent',
    iconID: 460689,
    passive: true,
    hidden: 'always',
    name: "Zealot's Paragon",
    icon: 'ability_paladin_conviction.jpg',
  },
  TIRIONS_DEVOTION_TALENT: {
    id: 392928,
    granted: false,
    requiresTalentEntry: [125873],
    type: 'talent',
    iconID: 135958,
    passive: true,
    hidden: 'always',
    name: "Tirion's Devotion",
    icon: 'spell_holy_revivechampion.jpg',
  },
  STRENGTH_IN_ADVERSITY_TALENT: {
    id: 393071,
    granted: false,
    requiresTalentEntry: [102461],
    type: 'talent',
    iconID: 135986,
    passive: true,
    hidden: 'always',
    name: 'Strength in Adversity',
    icon: 'spell_holy_weaponmastery.jpg',
  },
  IMPROVED_ARDENT_DEFENDER_TALENT: {
    id: 393114,
    granted: false,
    requiresTalentEntry: [111887],
    type: 'talent',
    iconID: 135870,
    passive: true,
    hidden: 'always',
    name: 'Improved Ardent Defender',
    icon: 'spell_holy_ardentdefender.jpg',
  },
  SANCTIFIED_PLATES_TALENT: {
    id: 402964,
    granted: false,
    requiresTalentEntry: [115034],
    type: 'talent',
    iconID: 1605807,
    passive: true,
    hidden: 'always',
    name: 'Sanctified Plates',
    icon: 'inv_chest_plate_raidpaladin_s_01.jpg',
  },
  PUNISHMENT_TALENT: {
    id: 403530,
    granted: false,
    requiresTalentEntry: [115444],
    type: 'talent',
    iconID: 523893,
    passive: true,
    hidden: 'always',
    name: 'Punishment',
    icon: 'spell_holy_rebuke.jpg',
  },
  GUIDED_PRAYER_TALENT: {
    id: 404357,
    granted: false,
    requiresTalentEntry: [136503],
    type: 'talent',
    iconID: 839106,
    passive: true,
    hidden: 'always',
    name: 'Guided Prayer',
    icon: 'ability_crown_of_the_heavens_icon.jpg',
  },
  FAITHS_ARMOR_TALENT: {
    id: 406101,
    granted: false,
    requiresTalentEntry: [102464],
    type: 'talent',
    iconID: 3736878,
    passive: true,
    hidden: 'always',
    name: "Faith's Armor",
    icon: 'inv_shield_1h_newplayer_a_01.jpg',
  },
  LIGHTFORGED_BLESSING_TALENT: {
    id: 406468,
    granted: false,
    requiresTalentEntry: [128240],
    type: 'talent',
    iconID: 135887,
    passive: true,
    hidden: 'always',
    name: 'Lightforged Blessing',
    icon: 'spell_holy_circleofrenewal.jpg',
  },
  LIGHTS_DELIVERANCE_TALENT: {
    id: 425518,
    granted: false,
    requiresTalentEntry: [117815],
    type: 'talent',
    iconID: 1316218,
    passive: true,
    hidden: 'always',
    name: "Light's Deliverance",
    icon: 'inv_glove_plate_raidpaladinmythic_q_01.jpg',
  },
  LIGHTS_GUIDANCE_TALENT: {
    id: 427445,
    granted: false,
    requiresTalentEntry: [117813],
    type: 'talent',
    iconID: 571556,
    passive: true,
    hidden: 'always',
    name: "Light's Guidance",
    icon: 'ability_paladin_longarmofthelaw.jpg',
  },
  ZEALOUS_VINDICATION_TALENT: {
    id: 431463,
    granted: false,
    requiresTalentEntry: [117816],
    type: 'talent',
    iconID: 135981,
    passive: true,
    hidden: 'always',
    name: 'Zealous Vindication',
    icon: 'spell_holy_surgeoflight.jpg',
  },
  SHAKE_THE_HEAVENS_TALENT: {
    id: 431533,
    granted: false,
    requiresTalentEntry: [117823],
    type: 'talent',
    iconID: 1022948,
    passive: true,
    hidden: 'always',
    name: 'Shake the Heavens',
    icon: 'ability_priest_holybolts01.jpg',
  },
  WRATHFUL_DESCENT_TALENT: {
    id: 431551,
    granted: false,
    requiresTalentEntry: [117810],
    type: 'talent',
    iconID: 4726195,
    passive: true,
    hidden: 'always',
    name: 'Wrathful Descent',
    icon: 'ability_paladin_intercession.jpg',
  },
  HIGHER_CALLING_TALENT: {
    id: 431687,
    granted: false,
    requiresTalentEntry: [117811],
    type: 'talent',
    iconID: 1360764,
    passive: true,
    hidden: 'always',
    name: 'Higher Calling',
    icon: 'ability_paladin_toweroflight.jpg',
  },
  SACROSANCT_CRUSADE_TALENT: {
    id: 431730,
    granted: false,
    requiresTalentEntry: [117812],
    type: 'talent',
    iconID: 4558042,
    passive: true,
    hidden: 'always',
    name: 'Sacrosanct Crusade',
    icon: 'inv_plate_raidpaladinprimalist_d_01_cape.jpg',
  },
  HOLY_BULWARK_TALENT: {
    id: 432459,
    granted: false,
    requiresTalentEntry: [117882],
    type: 'talent',
    iconID: 5927636,
    passive: false,
    name: 'Holy Bulwark',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    charges: {
      max: 2,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
      modifiers: [
        {
          duration: -15000,
          requiredSpells: [379391],
        },
        {
          duration: -12000,
          requiredSpells: [432804],
        },
      ],
    },
    icon: 'inv_ability_lightsmithpaladin_holybulwark.jpg',
  },
  HAMMERFALL_TALENT: {
    id: 432463,
    granted: false,
    requiresTalentEntry: [117818],
    type: 'talent',
    iconID: 236251,
    passive: true,
    hidden: 'always',
    name: 'Hammerfall',
    icon: 'ability_paladin_enlightenedjudgements.jpg',
  },
  ENDLESS_WRATH_TALENT: {
    id: 432615,
    granted: false,
    requiresTalentEntry: [117820],
    type: 'talent',
    iconID: 135897,
    passive: true,
    hidden: 'always',
    name: 'Endless Wrath',
    icon: 'spell_holy_divinepurpose.jpg',
  },
  UNDISPUTED_RULING_TALENT: {
    id: 432626,
    granted: false,
    requiresTalentEntry: [117822],
    type: 'talent',
    iconID: 135959,
    passive: true,
    hidden: 'always',
    name: 'Undisputed Ruling',
    icon: 'spell_holy_righteousfury.jpg',
  },
  SOLIDARITY_TALENT: {
    id: 432802,
    granted: false,
    requiresTalentEntry: [117873],
    type: 'talent',
    iconID: 135919,
    passive: true,
    hidden: 'always',
    name: 'Solidarity',
    icon: 'spell_holy_heroism.jpg',
  },
  FOREWARNING_TALENT: {
    id: 432804,
    granted: false,
    requiresTalentEntry: [117876],
    type: 'talent',
    iconID: 236252,
    passive: true,
    hidden: 'always',
    name: 'Forewarning',
    icon: 'ability_paladin_gaurdedbythelight.jpg',
  },
  SHARED_RESOLVE_TALENT: {
    id: 432821,
    granted: false,
    requiresTalentEntry: [117886],
    type: 'talent',
    iconID: 135893,
    passive: true,
    hidden: 'always',
    name: 'Shared Resolve',
    icon: 'spell_holy_devotionaura.jpg',
  },
  LAYING_DOWN_ARMS_TALENT: {
    id: 432866,
    granted: false,
    requiresTalentEntry: [117885],
    type: 'talent',
    iconID: 1360761,
    passive: true,
    hidden: 'always',
    name: 'Laying Down Arms',
    icon: 'ability_paladin_handoflight.jpg',
  },
  VALIANCE_TALENT: {
    id: 432919,
    granted: false,
    requiresTalentEntry: [117874],
    type: 'talent',
    iconID: 133527,
    passive: true,
    hidden: 'always',
    name: 'Valiance',
    icon: 'inv_mace_47.jpg',
  },
  DIVINE_HAMMER_TALENT: {
    id: 432929,
    granted: false,
    requiresTalentEntry: [136005],
    type: 'talent',
    iconID: 626003,
    passive: true,
    hidden: 'always',
    name: 'Divine Hammer',
    icon: 'classicon_paladin.jpg',
  },
  DIVINE_INSPIRATION_TALENT: {
    id: 432964,
    granted: false,
    requiresTalentEntry: [117877],
    type: 'talent',
    iconID: 612968,
    passive: true,
    hidden: 'always',
    name: 'Divine Inspiration',
    icon: 'ability_priest_flashoflight.jpg',
  },
  SANCTIFICATION_TALENT: {
    id: 432977,
    granted: false,
    requiresTalentEntry: [117819],
    type: 'talent',
    iconID: 236248,
    passive: true,
    hidden: 'always',
    name: 'Sanctification',
    icon: 'ability_paladin_blessedhands.jpg',
  },
  UNRELENTING_CHARGER_TALENT: {
    id: 432990,
    granted: false,
    requiresTalentEntry: [117858],
    type: 'talent',
    iconID: 3636572,
    passive: true,
    hidden: 'always',
    name: 'Unrelenting Charger',
    icon: 'ability_mount_mawhorsespikes_yellow.jpg',
  },
  BONDS_OF_FELLOWSHIP_TALENT: {
    id: 432992,
    granted: false,
    requiresTalentEntry: [117814],
    type: 'talent',
    iconID: 135889,
    passive: true,
    hidden: 'always',
    name: 'Bonds of Fellowship',
    icon: 'spell_holy_crusade.jpg',
  },
  BLESSING_OF_THE_FORGE_TALENT: {
    id: 433011,
    granted: false,
    requiresTalentEntry: [117875],
    type: 'talent',
    iconID: 5927637,
    passive: true,
    hidden: 'always',
    name: 'Blessing of the Forge',
    icon: 'inv_ability_lightsmithpaladin_sacredweapon.jpg',
  },
  BLESSED_ASSURANCE_TALENT: {
    id: 433015,
    granted: false,
    requiresTalentEntry: [117883],
    type: 'talent',
    iconID: 135876,
    passive: true,
    hidden: 'always',
    name: 'Blessed Assurance',
    icon: 'spell_holy_blessedlife.jpg',
  },
  DIVINE_GUIDANCE_TALENT: {
    id: 433106,
    granted: false,
    requiresTalentEntry: [117884],
    type: 'talent',
    iconID: 135931,
    passive: true,
    hidden: 'always',
    name: 'Divine Guidance',
    icon: 'spell_holy_lightsgrace.jpg',
  },
  RITE_OF_SANCTIFICATION_TALENT: {
    id: 433568,
    granted: false,
    requiresTalentEntry: [117881],
    type: 'talent',
    iconID: 237172,
    passive: false,
    name: 'Rite of Sanctification',
    castTime: {
      duration: 2000,
    },
    icon: 'inv_inscription_weaponscroll01.jpg',
  },
  RITE_OF_ADJURATION_TALENT: {
    id: 433583,
    granted: false,
    requiresTalentEntry: [117880],
    type: 'talent',
    iconID: 237051,
    passive: false,
    name: 'Rite of Adjuration',
    castTime: {
      duration: 2000,
    },
    icon: 'inv_inscription_armorscroll02.jpg',
  },
  HAMMER_AND_ANVIL_TALENT: {
    id: 433718,
    granted: false,
    requiresTalentEntry: [136001],
    type: 'talent',
    iconID: 4622272,
    passive: true,
    hidden: 'always',
    name: 'Hammer and Anvil',
    icon: 'inv_10_blacksmithing_consumable_repairhammer_color1.jpg',
  },
  EARTHEN_ORDINANTS_RAMOLITH: {
    id: 453785,
    type: 'baseline',
    iconID: 5350153,
    passive: false,
    name: "Earthen Ordinant's Ramolith",
    castTime: {
      duration: 1500,
    },
    icon: 'inv_earthenpaladinmount.jpg',
  },
  WRENCH_EVIL_TALENT: {
    id: 460720,
    granted: false,
    requiresTalentEntry: [128250],
    type: 'talent',
    iconID: 571559,
    passive: true,
    hidden: 'always',
    name: 'Wrench Evil',
    icon: 'ability_paladin_turnevil.jpg',
  },
  SACROSANCT_CRUSADE_HIDDEN: {
    id: 461926,
    type: 'learned',
    taughtBy: 431730,
    iconID: 4558042,
    passive: true,
    hidden: 'always',
    name: 'Sacrosanct Crusade',
    icon: 'inv_plate_raidpaladinprimalist_d_01_cape.jpg',
  },
  WORTHY_SACRIFICE_TALENT: {
    id: 469279,
    granted: false,
    requiresTalentEntry: [128261],
    type: 'talent',
    iconID: 1360761,
    passive: true,
    hidden: 'always',
    name: 'Worthy Sacrifice',
    icon: 'ability_paladin_handoflight.jpg',
  },
  STEED_OF_LIBERTY_TALENT: {
    id: 469304,
    granted: false,
    requiresTalentEntry: [102624],
    type: 'talent',
    iconID: 135890,
    passive: true,
    hidden: 'always',
    name: 'Steed of Liberty',
    icon: 'spell_holy_crusaderaura.jpg',
  },
  EYE_FOR_AN_EYE_TALENT: {
    id: 469309,
    granted: false,
    requiresTalentEntry: [102620],
    type: 'talent',
    iconID: 135904,
    passive: true,
    hidden: 'always',
    name: 'Eye for an Eye',
    icon: 'spell_holy_eyeforaneye.jpg',
  },
  STOICISM_TALENT: {
    id: 469316,
    granted: false,
    requiresTalentEntry: [128258],
    type: 'talent',
    iconID: 135995,
    passive: true,
    hidden: 'always',
    name: 'Stoicism',
    icon: 'spell_magic_magearmor.jpg',
  },
  STAND_AGAINST_EVIL_TALENT: {
    id: 469317,
    granted: false,
    requiresTalentEntry: [128249],
    type: 'talent',
    iconID: 135902,
    passive: true,
    hidden: 'always',
    name: 'Stand Against Evil',
    icon: 'spell_holy_excorcism.jpg',
  },
  RIGHTEOUS_PROTECTION_TALENT: {
    id: 469321,
    granted: false,
    requiresTalentEntry: [128248],
    type: 'talent',
    iconID: 135880,
    passive: true,
    hidden: 'always',
    name: 'Righteous Protection',
    icon: 'spell_holy_blessingofprotection.jpg',
  },
  LIGHTS_COUNTENANCE_TALENT: {
    id: 469325,
    granted: false,
    requiresTalentEntry: [128247],
    type: 'talent',
    iconID: 4869742,
    passive: true,
    hidden: 'always',
    name: "Light's Countenance",
    icon: 'inv_shoulder_raidpaladindragon_d_01.jpg',
  },
  SACRED_STRENGTH_TALENT: {
    id: 469337,
    granted: false,
    requiresTalentEntry: [115490],
    type: 'talent',
    iconID: 135960,
    passive: true,
    hidden: 'always',
    name: 'Sacred Strength',
    icon: 'spell_holy_righteousnessaura.jpg',
  },
  DIVINE_SPURS_TALENT: {
    id: 469409,
    granted: false,
    requiresTalentEntry: [128253],
    type: 'talent',
    iconID: 132226,
    passive: true,
    hidden: 'always',
    name: 'Divine Spurs',
    icon: 'ability_mount_charger.jpg',
  },
  A_JUST_REWARD_TALENT: {
    id: 469411,
    granted: false,
    requiresTalentEntry: [128254],
    type: 'talent',
    iconID: 135883,
    passive: true,
    hidden: 'always',
    name: 'A Just Reward',
    icon: 'spell_holy_blindingheal.jpg',
  },
  LIGHTBEARER_TALENT: {
    id: 469416,
    granted: false,
    requiresTalentEntry: [128257],
    type: 'talent',
    iconID: 461857,
    passive: true,
    hidden: 'always',
    name: 'Lightbearer',
    icon: 'spell_paladin_clarityofpurpose.jpg',
  },
  SELFLESS_HEALER_TALENT: {
    id: 469434,
    granted: false,
    requiresTalentEntry: [128309],
    type: 'talent',
    iconID: 236252,
    passive: true,
    hidden: 'always',
    name: 'Selfless Healer',
    icon: 'ability_paladin_gaurdedbythelight.jpg',
  },
  INSPIRED_GUARD_TALENT: {
    id: 469439,
    granted: false,
    requiresTalentEntry: [128260],
    type: 'talent',
    iconID: 524353,
    passive: true,
    hidden: 'always',
    name: 'Inspired Guard',
    icon: 'spell_holy_divineprotection.jpg',
  },
  HOLY_REPRIEVE_TALENT: {
    id: 469445,
    granted: false,
    requiresTalentEntry: [128256],
    type: 'talent',
    iconID: 135967,
    passive: true,
    hidden: 'always',
    name: 'Holy Reprieve',
    icon: 'spell_holy_sealofsalvation.jpg',
  },
  DIVINE_REACH_TALENT: {
    id: 469476,
    granted: false,
    requiresTalentEntry: [115447],
    type: 'talent',
    iconID: 135934,
    passive: true,
    hidden: 'always',
    name: 'Divine Reach',
    icon: 'spell_holy_mindvision.jpg',
  },
  TEMPERED_IN_BATTLE_TALENT: {
    id: 469701,
    granted: false,
    requiresTalentEntry: [117878],
    type: 'talent',
    iconID: 5931163,
    passive: true,
    hidden: 'always',
    name: 'Tempered in Battle',
    icon: 'inv_everburningforge_yellow.jpg',
  },
  BLESSED_CALLING_TALENT: {
    id: 469770,
    granted: false,
    requiresTalentEntry: [128264],
    type: 'talent',
    iconID: 236256,
    passive: true,
    hidden: 'always',
    name: 'Blessed Calling',
    icon: 'ability_paladin_judgementofthepure.jpg',
  },
  LEAD_THE_CHARGE_TALENT: {
    id: 469780,
    granted: false,
    requiresTalentEntry: [128263],
    type: 'talent',
    iconID: 1581161,
    passive: true,
    hidden: 'always',
    name: 'Lead the Charge',
    icon: 'inv_helm_plate_raidpaladin_r_01mythic.jpg',
  },
  REFINING_FIRE_TALENT: {
    id: 469883,
    granted: false,
    requiresTalentEntry: [102452],
    type: 'talent',
    iconID: 5931165,
    passive: true,
    hidden: 'always',
    name: 'Refining Fire',
    icon: 'inv_everburningignition_yellow.jpg',
  },
  AUTHORITATIVE_REBUKE_TALENT: {
    id: 469886,
    granted: false,
    requiresTalentEntry: [117879],
    type: 'talent',
    iconID: 134471,
    passive: true,
    hidden: 'always',
    name: 'Authoritative Rebuke',
    icon: 'inv_misc_symbolofkings_01.jpg',
  },
  LAY_ON_HANDS: {
    id: 471195,
    grantedBy: 387791,
    type: 'temporary',
    overrides: 633,
    iconID: 135928,
    passive: false,
    name: 'Lay on Hands',
    cooldown: {
      duration: 600000,
      hasted: false,
    },
    icon: 'spell_holy_layonhands.jpg',
  },
  HAMMERFALL_HIDDEN: {
    id: 1224051,
    type: 'learned',
    taughtBy: 432463,
    iconID: 236251,
    passive: true,
    hidden: 'always',
    name: 'Hammerfall',
    icon: 'ability_paladin_enlightenedjudgements.jpg',
  },
  SINGLE_BUTTON_ASSISTANT: {
    id: 1229376,
    type: 'baseline',
    iconID: 6718291,
    passive: false,
    name: 'Single-Button Assistant',
    castTime: {
      duration: 2000,
    },
    icon: 'ui_spellbook_onebutton.jpg',
  },
  BLESSING_OF_DUSK_TALENT: {
    id: 1241945,
    granted: false,
    requiresTalentEntry: [128259],
    type: 'talent',
    iconID: 1048304,
    passive: true,
    hidden: 'always',
    name: 'Blessing of Dusk',
    icon: 'achievement_zone_newshadowmoonvalley.jpg',
  },
  VENGEFUL_WRATH_TALENT: {
    id: 1241958,
    granted: false,
    requiresTalentEntry: [128241],
    type: 'talent',
    iconID: 613533,
    passive: true,
    hidden: 'always',
    name: 'Vengeful Wrath',
    icon: 'spell_paladin_hammerofwrath.jpg',
  },
  UNDYING_EMBERS_TALENT: {
    id: 1244019,
    granted: false,
    requiresTalentEntry: [102459],
    type: 'talent',
    iconID: 5899329,
    passive: true,
    hidden: 'always',
    name: 'Undying Embers',
    icon: 'inv_achievement_dungeon_darkflamecleft.jpg',
  },
  SEARING_SUNLIGHT_TALENT: {
    id: 1244070,
    granted: false,
    requiresTalentEntry: [102470],
    type: 'talent',
    iconID: 3193844,
    passive: true,
    hidden: 'always',
    name: 'Searing Sunlight',
    icon: 'ability_essence_reapingflames.jpg',
  },
  VISION_OF_SANCTITY_TALENT: {
    id: 1245354,
    granted: false,
    requiresTalentEntry: [102432],
    type: 'talent',
    iconID: 1724000,
    passive: true,
    hidden: 'always',
    name: 'Vision of Sanctity',
    icon: 'ability_racial_orbitalstrike.jpg',
  },
  SOLACE_TALENT: {
    id: 1245891,
    granted: false,
    requiresTalentEntry: [102451],
    type: 'talent',
    iconID: 135944,
    passive: true,
    hidden: 'always',
    name: 'Solace',
    icon: 'spell_holy_prayerofmendingtga.jpg',
  },
  VALIANT_CRUSADE_TALENT: {
    id: 1245979,
    granted: false,
    requiresTalentEntry: [102439],
    type: 'talent',
    iconID: 524049,
    passive: true,
    hidden: 'always',
    name: 'Valiant Crusade',
    icon: 'ability_mount_alliancepvpmount.jpg',
  },
  EMPYREAN_AUTHORITY_TALENT: {
    id: 1246481,
    granted: false,
    requiresTalentEntry: [102466],
    type: 'talent',
    iconID: 1030099,
    passive: true,
    hidden: 'always',
    name: 'Empyrean Authority',
    icon: 'ability_paladin_empoweredsealsrighteous.jpg',
  },
  SWEEPING_VERDICT_TALENT: {
    id: 1246488,
    granted: false,
    requiresTalentEntry: [102474],
    type: 'talent',
    iconID: 613955,
    passive: true,
    hidden: 'always',
    name: 'Sweeping Verdict',
    icon: 'spell_paladin_lightshammer.jpg',
  },
  DIVINE_EXACTION_TALENT: {
    id: 1260429,
    granted: false,
    requiresTalentEntry: [136003],
    type: 'talent',
    iconID: 6035315,
    passive: true,
    hidden: 'always',
    name: 'Divine Exaction',
    icon: 'inv_ability_paladin_divinetoll.jpg',
  },
  LIGHTS_JUDICATOR_TALENT: {
    id: 1261525,
    granted: false,
    requiresTalentEntry: [136004],
    type: 'talent',
    iconID: 236256,
    passive: true,
    hidden: 'always',
    name: "Light's Judicator",
    icon: 'ability_paladin_judgementofthepure.jpg',
  },
  SEAL_OF_THE_TEMPLAR_TALENT: {
    id: 1263252,
    granted: false,
    requiresTalentEntry: [136184],
    type: 'talent',
    iconID: 461860,
    passive: true,
    hidden: 'always',
    name: 'Seal of the Templar',
    icon: 'spell_paladin_templarsverdict.jpg',
  },
  FEAR_NO_EVIL_TALENT: {
    id: 1265541,
    granted: false,
    requiresTalentEntry: [136485],
    type: 'talent',
    iconID: 1581158,
    passive: true,
    hidden: 'always',
    name: 'Fear No Evil',
    icon: 'inv_bracer_plate_raidpaladin_r_01mythic.jpg',
  },
  BROUGHT_TO_LIGHT_TALENT: {
    id: 1265549,
    granted: false,
    requiresTalentEntry: [136486],
    type: 'talent',
    iconID: 535593,
    passive: true,
    hidden: 'always',
    name: 'Brought to Light',
    icon: 'paladin_holy.jpg',
  },
  GLORY_OF_THE_VANGUARD_TALENT_1: {
    id: 1267203,
    granted: false,
    requiresTalentEntry: [137022],
    type: 'talent',
    iconID: 7636559,
    passive: true,
    hidden: 'always',
    name: 'Glory of the Vanguard',
    icon: 'inv12_apextalent_paladin_gloryofthevanguard.jpg',
  },
  GLORY_OF_THE_VANGUARD_TALENT_2: {
    id: 1267211,
    granted: false,
    requiresTalentEntry: [137021],
    type: 'talent',
    iconID: 7636559,
    passive: true,
    hidden: 'always',
    name: 'Glory of the Vanguard',
    icon: 'inv12_apextalent_paladin_gloryofthevanguard.jpg',
  },
  GLORY_OF_THE_VANGUARD_TALENT_3: {
    id: 1267215,
    granted: false,
    requiresTalentEntry: [137020],
    type: 'talent',
    iconID: 7636559,
    passive: true,
    hidden: 'always',
    name: 'Glory of the Vanguard',
    icon: 'inv12_apextalent_paladin_gloryofthevanguard.jpg',
  },
  MASTERWORK_TALENT: {
    id: 1271387,
    granted: false,
    requiresTalentEntry: [136000],
    type: 'talent',
    iconID: 4374708,
    passive: true,
    hidden: 'always',
    name: 'Masterwork',
    icon: 'inv_mace_1h_blacksmithing_b_01_black.jpg',
  },
  REFLECTION_OF_RADIANCE_TALENT: {
    id: 1271466,
    granted: false,
    requiresTalentEntry: [117887],
    type: 'talent',
    iconID: 1379180,
    passive: true,
    hidden: 'always',
    name: 'Reflection of Radiance',
    icon: 'inv_enchanting_70_pet_torch.jpg',
  },
  RESOUNDING_STRIKE_TALENT: {
    id: 1271553,
    granted: false,
    requiresTalentEntry: [136002],
    type: 'talent',
    iconID: 6012000,
    passive: true,
    hidden: 'always',
    name: 'Resounding Strike',
    icon: 'inv_11_0_arathordungeon_bell_color1.jpg',
  },
  IMBUED_SHIELD_TALENT: {
    id: 1276945,
    granted: false,
    requiresTalentEntry: [102463],
    type: 'talent',
    iconID: 1394888,
    passive: true,
    hidden: 'always',
    name: 'Imbued Shield',
    icon: 'inv_artifact_bulwarkoforder.jpg',
  },
  ADJUDICATION_TALENT: {
    id: 1277005,
    granted: false,
    requiresTalentEntry: [136732],
    type: 'talent',
    iconID: 1006574,
    passive: true,
    hidden: 'always',
    name: 'Adjudication',
    icon: 'inv_mace_2h_draenorraid_d_03.jpg',
  },
  INSTRUMENT_OF_THE_DIVINE_TALENT: {
    id: 1277162,
    granted: false,
    requiresTalentEntry: [102454],
    type: 'talent',
    iconID: 458225,
    passive: true,
    hidden: 'always',
    name: 'Instrument of the Divine',
    icon: 'ability_priest_archangel.jpg',
  },
} as const satisfies Record<string, RetailSpell & { icon: string }>;
export default SPELLS;
