const enchants = {
  ENCHANT_WEAPON_ASCENDED_VIGOR: {
    id: 172365,
    name: 'Enchant Weapon - Ascended Vigor',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6227,
  },
  ENCHANT_WEAPON_CELESTIAL_GUIDANCE: {
    id: 172366,
    name: 'Enchant Weapon - Celestial Guidance',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6229,
  },
  ENCHANT_WEAPON_ETERNAL_GRACE: {
    id: 172367,
    name: 'Enchant Weapon - Eternal Grace',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6226,
  },
  ENCHANT_WEAPON_LIGHTLESS_FORCE: {
    id: 172370,
    name: 'Enchant Weapon - Lightless Force',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6223,
  },
  ENCHANT_WEAPON_SINFUL_REVELATION: {
    id: 172368,
    name: 'Enchant Weapon - Sinful Revelation',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6228,
  },
  ENCHANT_WEAPON_OPTICAL_TARGET_EMBIGGENER: {
    id: 172920,
    name: 'Optical Target Embiggener',
    icon: 'inv_engineering_90_scope_blue',
    effectId: 6196,
  },
  ENCHANT_WEAPON_INFRA_GREEN_REFLEX_SIGHT: {
    id: 172921,
    name: 'Infra-green Reflex Sight',
    icon: 'inv_engineering_90_scope_green',
    effectId: 6195,
  },
  ENCHANT_CLOAK_FORTIFIED_AVOIDANCE: {
    id: 172411,
    name: 'Enchant Cloak - Fortified Avoidance',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6203,
  },
  ENCHANT_CLOAK_FORTIFIED_LEECH: {
    id: 172412,
    name: 'Enchant Cloak - Fortified Leech',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6204,
  },
  ENCHANT_CLOAK_FORTIFIED_SPEED: {
    id: 172410,
    name: 'Enchant Cloak - Fortified Speed',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6202,
  },
  ENCHANT_CLOAK_SOUL_VITALITY: {
    id: 177660,
    name: 'Enchant Cloak - Soul Vitality',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6208,
  },
  ENCHANT_CHEST_SACRED_STATS: {
    id: 177716,
    name: 'Enchant Chest - Sacred Stats',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6216,
  },
  ENCHANT_CHEST_ETERNAL_STATS: {
    id: 177962,
    name: 'Enchant Chest - Eternal Stats',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6230,
  },
  ENCHANT_CHEST_ETERNAL_BOUNDS: {
    id: 177715,
    name: 'Enchant Chest - Eternal Bounds',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6217,
  },
  ENCHANT_CHEST_ETERNAL_INSIGHT: {
    id: 183738,
    name: 'Enchant Chest - Eternal Insight',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6265,
  },
  ENCHANT_CHEST_ETERNAL_BULWARK: {
    id: 172418,
    name: 'Enchant Chest - Eternal Bulwark',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6213,
  },
  ENCHANT_CHEST_ETERNAL_SKIRMISH: {
    id: 177659,
    name: 'Enchant Chest - Eternal Skirmish',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6214,
  },
  ENCHANT_BRACERS_ILLUMINATED_SOUL: {
    id: 172414,
    name: 'Enchant Bracers - Illuminated Soul',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6219,
  },
  ENCHANT_BRACERS_ETERNAL_INTELLECT: {
    id: 172415,
    name: 'Enchant Bracers - Eternal Intellect',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6220,
  },
  ENCHANT_BRACERS_SHADED_HEARTHING: {
    id: 172416,
    name: 'Enchant Bracers - Shaded Hearthing',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6222,
  },
  ENCHANT_GLOVES_STRENGTH_OF_SOUL: {
    id: 172407,
    name: 'Enchant Gloves - Strength of Soul',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6209,
  },
  ENCHANT_GLOVES_ETERNAL_STRENGTH: {
    id: 172408,
    name: 'Enchant Gloves - Eternal Strength',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6210,
  },
  ENCHANT_GLOVES_SHADOWLANDS_GATHERING: {
    id: 172406,
    name: 'Enchant Gloves - Shadowlands Gathering',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6205,
  },
  ENCHANT_BOOTS_AGILE_SOULWALKER: {
    id: 172413,
    name: 'Enchant Boots - Agile Soulwalker',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6212,
  },
  ENCHANT_BOOTS_ETERNAL_AGILITY: {
    id: 172419,
    name: 'Enchant Boots - Eternal Agility',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6211,
  },
  ENCHANT_BOOTS_SOUL_TREADS: {
    id: 177661,
    name: 'Enchant Boots - Soul Treads',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6207,
  },
  ENCHANT_RING_BARGAIN_OF_CRITICAL_STRIKE: {
    id: 172357,
    name: 'Enchant Ring - Bargain of Critical Strike',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6163,
  },
  ENCHANT_RING_BARGAIN_OF_HASTE: {
    id: 172358,
    name: 'Enchant Ring - Bargain of Haste',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6165,
  },
  ENCHANT_RING_BARGAIN_OF_MASTERY: {
    id: 172359,
    name: 'Enchant Ring - Bargain of Master',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6167,
  },
  ENCHANT_RING_BARGAIN_OF_VERSATILITY: {
    id: 172360,
    name: 'Enchant Ring - Bargain of Versatility',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6169,
  },
  ENCHANT_RING_TENET_OF_CRITICAL_STRIKE: {
    id: 172361,
    name: 'Enchant Ring - Tenet of Critical Strike',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6164,
  },
  ENCHANT_RING_TENET_OF_HASTE: {
    id: 172362,
    name: 'Enchant Ring - Tenet of Haste',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6166,
  },
  ENCHANT_RING_TENET_OF_MASTERY: {
    id: 172363,
    name: 'Enchant Ring - Tenet of Mastery',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6168,
  },
  ENCHANT_RING_TENET_OF_VERSATILITY: {
    id: 172364,
    name: 'Enchant Ring - Tenet of Versatility',
    icon: 'inv_misc_enchantedscroll',
    effectId: 6170,
  },

  //Weapon Oils & Stones
  SHADOWCORE_OIL: {
    id: 171285,
    name: 'Shadowcore Oil',
    icon: 'inv_misc_potionseta',
    effectId: 6188,
  },
  EMBALMERS_OIL: {
    id: 171286,
    name: 'Embalmer\'s Oil',
    icon: 'inv_misc_potionsetb',
    effectId: 6190,
  },
  SHADED_SHARPENING_STONE: {
    id: 171437,
    name: 'Shaded Sharpening Stone',
    icon: 'inv_blacksmithing_greatersharpeningstone',
    effectId: 6200,
  },
  SHADED_WEIGHTSTONE: {
    id: 171439,
    name: 'Shaded Weightstone',
    icon: 'inv_blacksmithing_greaterweightstone',
    effectId: 6201,
  },
} as const;

export default enchants;
