enum STATISTIC_CATEGORY {
  GENERAL = 'GENERAL',
  TALENTS = 'TALENTS',
  COVENANTS = 'COVENANT',
  ITEMS = 'ITEMS',
  THEORYCRAFT = 'THEORYCRAFT',
  PANELS = 'PANELS',
}

export default STATISTIC_CATEGORY;
