enum STATISTIC_CATEGORY {
  GENERAL = 'GENERAL',
  TALENTS = 'TALENTS',
  COVENANTS = 'COVENANTS',
  AZERITE_POWERS = 'AZERITE_POWERS',
  ITEMS = 'ITEMS',
  PANELS = 'PANELS',
}

export default STATISTIC_CATEGORY;
