import SPELLS from 'common/SPELLS';

export const ABILITIES_AFFECTED_BY_HEALING_INCREASES = [
  // Spells
  SPELLS.EFFUSE.id,
  SPELLS.ENVELOPING_MISTS.id,
  SPELLS.ESSENCE_FONT.id,
  SPELLS.ESSENCE_FONT_BUFF.id,
  SPELLS.RENEWING_MIST.id,
  SPELLS.RENEWING_MIST_HEAL.id,
  SPELLS.VIVIFY.id,
  SPELLS.SOOTHING_MIST.id,
  SPELLS.GUSTS_OF_MISTS.id,

  // Cooldowns
  SPELLS.LIFE_COCOON.id,
  SPELLS.REVIVAL.id,

  // Artifact and Traits
  SPELLS.SHEILUNS_GIFT.id,
  SPELLS.CELESTIAL_BREATH.id,
  SPELLS.MISTS_OF_SHEILUN.id,
  SPELLS.WHISPERS_OF_SHAOHAO.id,
  SPELLS.BLESSINGS_OF_YULON.id,

  // Talents
  SPELLS.CHI_BURST_TALENT.id,
  SPELLS.CHI_BURST_HEAL.id,
  SPELLS.CHI_WAVE_TALENT.id,
  SPELLS.ZEN_PULSE_TALENT.id,
  SPELLS.REFRESHING_JADE_WIND_TALENT.id,
  SPELLS.REFRESHING_JADE_WIND_HEAL.id,
  SPELLS.CRANE_HEAL.id, // Chi-Ji Heal

  // Misc
  SPELLS.LEECH.id,
  SPELLS.MARK_OF_THE_ANCIENT_PRIESTESS.id,

];
