import SPELLS from 'common/SPELLS';

export const FIRESTARTER_THRESHOLD = .90;
export const SEARING_TOUCH_THRESHOLD = .30;
export const PROC_BUFFER = 200;
export const CAST_BUFFER = 250;
export const COMBUSTION_BUFFER = 3000;
export const KINDLING_REDUCTION_MS = 1000;
export const RUNE_OF_POWER_DELAY = 100;
export const PYROCLASM_DAMAGE_MODIFIER = 225;
export const SEARING_TOUCH_DAMAGE_MODIFIER = 1.50;

export const HOT_STREAK_CONTRIBUTORS = [
  SPELLS.FIREBALL,
  SPELLS.PYROBLAST,
  SPELLS.FIRE_BLAST,
  SPELLS.SCORCH,
  SPELLS.PHOENIX_FLAMES_TALENT,
];

export const COMBUST_REDUCTION_SPELLS = [
  SPELLS.FIREBALL,
  SPELLS.PYROBLAST,
  SPELLS.FIRE_BLAST,
];
