import SPELLS from 'common/SPELLS';

export const SMOLDERING =
  {PROC_CHANCE : 0.001,
    PROC_DURATION : 10000};

export const ELEMENTAL_BLAST_IDS = [
  SPELLS.ELEMENTAL_BLAST_CRIT.id,
  SPELLS.ELEMENTAL_BLAST_MASTERY.id,
  SPELLS.ELEMENTAL_BLAST_HASTE.id,
];

export const ECHOES = {
  PROC_DURATION : 6000,
  LAG_TOLERANCE : 150,
  TRESHOLD_PERCENTAGE : 0.3,
};

export const CRIT_MULTIPLIER = 2.5;
