import SPELLS from 'common/SPELLS';

export const ELEMENTAL_BLAST_SPELLS = [
  SPELLS.ELEMENTAL_BLAST_CRIT,
  SPELLS.ELEMENTAL_BLAST_MASTERY,
  SPELLS.ELEMENTAL_BLAST_HASTE,
];

export const CRIT_MULTIPLIER = 2.5;
