import SPELLS from 'common/SPELLS';

export const SMOLDERING =
  {PROC_CHANCE : 0.001,
    PROC_DURATION : 10000};

export const ELEMENTAL_BLAST_IDS = [
  SPELLS.ELEMENTAL_BLAST_CRIT.id,
  SPELLS.ELEMENTAL_BLAST_MASTERY.id,
  SPELLS.ELEMENTAL_BLAST_HASTE.id,
];
