import SPELLS from 'common/SPELLS/shaman';

export const STORMSTRIKE_CAST_SPELLS = [SPELLS.STORMSTRIKE_CAST, SPELLS.WINDSTRIKE_CAST];

export const STORMSTRIKE_CAST_SPELLS_IDS = [SPELLS.STORMSTRIKE_CAST.id, SPELLS.WINDSTRIKE_CAST.id];

export const STORMSTRIKE_DAMAGE_SPELLS = [
  SPELLS.STORMSTRIKE_DAMAGE,
  SPELLS.STORMSTRIKE_DAMAGE_OFFHAND,
  SPELLS.WINDSTRIKE_DAMAGE,
  SPELLS.WINDSTRIKE_DAMAGE_OFFHAND,
];

export const STORMSTRIKE_COEFFICIENT = 1.074; // 107.4%

export const ESSENTIAL_EXTRACTION_EFFECT_BY_RANK = [
  0,
  -25,
  -26,
  -27,
  -28,
  -29,
  -30,
  -31,
  -33,
  -34,
  -35,
  -36,
  -37,
  -38,
  -39,
  -40,
];
