import SPELLS from 'common/SPELLS/shaman';

export const STORMSTRIKE_CAST_SPELLS = [
  SPELLS.STORMSTRIKE_CAST,
  SPELLS.WINDSTRIKE_CAST,
];

export const STORMSTRIKE_DAMAGE_SPELLS = [
  SPELLS.STORMSTRIKE_DAMAGE,
  SPELLS.STORMSTRIKE_DAMAGE_OFFHAND,
  SPELLS.WINDSTRIKE_DAMAGE,
  SPELLS.WINDSTRIKE_DAMAGE_OFFHAND,
];

export const STORMSTRIKE_COEFFICIENT = 1.074; // 107.4%
