import type { RetailSpell } from 'wow-dbc';
const SPELLS = {
  MYSTIC_TOUCH_PASSIVE: {
    id: 8647,
    type: 'baseline',
    iconID: 615342,
    passive: true,
    name: 'Mystic Touch',
    icon: 'ability_monk_sparring.jpg',
  },
  TIGER_PALM: {
    id: 100780,
    type: 'baseline',
    iconID: 606551,
    passive: false,
    name: 'Tiger Palm',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'ability_monk_tigerpalm.jpg',
  },
  BLACKOUT_KICK_BASELINE: {
    id: 100784,
    type: 'baseline',
    iconID: 574575,
    passive: false,
    name: 'Blackout Kick',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 3000,
      hasted: false,
      modifiers: [
        {
          duration: -1000,
          hasted: false,
          requiredSpells: [387230],
        },
      ],
    },
    icon: 'ability_monk_roundhousekick.jpg',
  },
  BLACKOUT_KICK: {
    id: 205523,
    type: 'learned',
    overrides: 100784,
    taughtBy: 322120,
    iconID: 574575,
    passive: false,
    name: 'Blackout Kick',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    charges: {
      max: 1,
    },
    cooldown: {
      duration: 4000,
      hasted: false,
    },
    icon: 'ability_monk_roundhousekick.jpg',
  },
  SPINNING_CRANE_KICK_BASELINE: {
    id: 101546,
    type: 'baseline',
    iconID: 606543,
    passive: false,
    name: 'Spinning Crane Kick',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    channel: {
      duration: 1500,
      hasted: true,
      buffIsLogged: false,
      triggeredSpells: [
        {
          spell: 107270,
          period: 500,
          hasted: true,
        },
      ],
    },
    icon: 'ability_monk_cranekick_new.jpg',
  },
  SPINNING_CRANE_KICK: {
    id: 322729,
    type: 'baseline',
    overrides: 101546,
    iconID: 606543,
    passive: false,
    hidden: 'unless-learned',
    name: 'Spinning Crane Kick',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    channel: {
      duration: 1500,
      hasted: true,
      buffIsLogged: false,
      triggeredSpells: [
        {
          spell: 107270,
          period: 500,
          hasted: true,
        },
      ],
    },
    icon: 'ability_monk_cranekick_new.jpg',
  },
  SPINNING_CRANE_KICK_HIDDEN: {
    id: 107270,
    type: 'baseline',
    iconID: 606543,
    passive: false,
    hidden: 'always',
    name: 'Spinning Crane Kick',
    icon: 'ability_monk_cranekick_new.jpg',
  },
  DND_MONK_ENERGY_DRIVER_HIDDEN: {
    id: 107500,
    type: 'baseline',
    iconID: 236180,
    passive: true,
    hidden: 'always',
    name: '<DND> Monk Energy Driver',
    icon: 'ability_hunter_huntervswild.jpg',
  },
  ROLL: {
    id: 109132,
    type: 'baseline',
    iconID: 574574,
    passive: false,
    name: 'Roll',
    charges: {
      max: 2,
    },
    cooldown: {
      duration: 20000,
      hasted: false,
      modifiers: [
        {
          duration: -2000,
          requiredSpells: [1272844],
        },
      ],
    },
    icon: 'ability_monk_roll.jpg',
  },
  STAGGER_TALENT: {
    id: 115069,
    granted: true,
    requiresTalentEntry: [136086],
    type: 'talent',
    iconID: 611419,
    passive: true,
    name: 'Stagger',
    icon: 'monk_stance_drunkenox.jpg',
  },
  PARALYSIS_TALENT: {
    id: 115078,
    granted: true,
    requiresTalentEntry: [124932],
    type: 'talent',
    iconID: 629534,
    passive: false,
    name: 'Paralysis',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 45000,
      hasted: false,
      modifiers: [
        {
          duration: -15000,
          hasted: false,
          requiredSpells: [344359],
        },
      ],
    },
    icon: 'ability_monk_paralysis.jpg',
  },
  SOOTHING_MIST_TALENT: {
    id: 115175,
    granted: false,
    requiresTalentEntry: [124933],
    type: 'talent',
    iconID: 606550,
    passive: false,
    name: 'Soothing Mist',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    channel: {
      duration: 8000,
      hasted: true,
      buffIsLogged: true,
      triggeredSpells: [],
    },
    icon: 'ability_monk_soothingmists.jpg',
  },
  RESUSCITATE: {
    id: 115178,
    type: 'baseline',
    iconID: 132132,
    passive: false,
    name: 'Resuscitate',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 10000,
    },
    icon: 'ability_druid_lunarguidance.jpg',
  },
  BREATH_OF_FIRE_TALENT: {
    id: 115181,
    granted: false,
    requiresTalentEntry: [124843],
    type: 'talent',
    iconID: 615339,
    passive: false,
    name: 'Breath of Fire',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 15000,
      hasted: false,
    },
    icon: 'ability_monk_breathoffire.jpg',
  },
  FORTIFYING_BREW: {
    id: 115203,
    type: 'learned',
    taughtBy: 322960,
    iconID: 615341,
    passive: false,
    name: 'Fortifying Brew',
    cooldown: {
      duration: 360000,
      hasted: false,
    },
    icon: 'ability_monk_fortifyingale_new.jpg',
  },
  SUMMON_BLACK_OX_STATUE_TALENT: {
    id: 115315,
    granted: false,
    requiresTalentEntry: [124967],
    type: 'talent',
    iconID: 627607,
    passive: false,
    name: 'Summon Black Ox Statue',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 10000,
      hasted: false,
    },
    icon: 'monk_ability_summonoxstatue.jpg',
  },
  BLACK_OX_BREW_TALENT: {
    id: 115399,
    granted: false,
    requiresTalentEntry: [124991],
    type: 'talent',
    iconID: 629483,
    castableWhileCasting: true,
    passive: false,
    name: 'Black Ox Brew',
    cooldown: {
      duration: 120000,
      hasted: false,
    },
    icon: 'ability_monk_chibrew.jpg',
  },
  PROVOKE: {
    id: 115546,
    type: 'baseline',
    iconID: 620830,
    passive: false,
    name: 'Provoke',
    cooldown: {
      duration: 8000,
      hasted: false,
    },
    icon: 'ability_monk_provoke.jpg',
  },
  DISABLE_TALENT: {
    id: 116095,
    granted: false,
    requiresTalentEntry: [124939],
    type: 'talent',
    iconID: 132316,
    passive: false,
    name: 'Disable',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    icon: 'ability_shockwave.jpg',
  },
  VIVIFY: {
    id: 116670,
    type: 'baseline',
    iconID: 1360980,
    passive: false,
    name: 'Vivify',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 1500,
    },
    icon: 'ability_monk_vivify.jpg',
  },
  SPEAR_HAND_STRIKE_TALENT: {
    id: 116705,
    granted: false,
    requiresTalentEntry: [124943],
    type: 'talent',
    iconID: 608940,
    passive: false,
    name: 'Spear Hand Strike',
    cooldown: {
      duration: 15000,
      hasted: false,
    },
    icon: 'ability_monk_spearhand.jpg',
  },
  PARRY_HIDDEN: {
    id: 116812,
    type: 'baseline',
    iconID: 132269,
    passive: true,
    hidden: 'always',
    name: 'Parry',
    icon: 'ability_parry.jpg',
  },
  TIGERS_LUST_TALENT: {
    id: 116841,
    granted: false,
    requiresTalentEntry: [124937],
    type: 'talent',
    iconID: 651727,
    passive: false,
    name: "Tiger's Lust",
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    icon: 'ability_monk_tigerslust.jpg',
  },
  RUSHING_JADE_WIND_TALENT: {
    id: 116847,
    granted: false,
    requiresTalentEntry: [125007],
    type: 'talent',
    iconID: 606549,
    passive: false,
    name: 'Rushing Jade Wind',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 6000,
      hasted: true,
    },
    icon: 'ability_monk_rushingjadewind.jpg',
  },
  FISTS_OF_FURY_HIDDEN: {
    id: 117418,
    type: 'baseline',
    iconID: 627606,
    passive: false,
    hidden: 'always',
    name: 'Fists of Fury',
    icon: 'monk_ability_fistoffury.jpg',
  },
  MASTERY_ELUSIVE_BRAWLER_PASSIVE: {
    id: 117906,
    type: 'baseline',
    iconID: 611417,
    passive: true,
    name: 'Mastery: Elusive Brawler',
    icon: 'ability_monk_guard.jpg',
  },
  CRACKLING_JADE_LIGHTNING: {
    id: 117952,
    type: 'baseline',
    iconID: 606542,
    passive: false,
    name: 'Crackling Jade Lightning',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 0,
      hasted: false,
      modifiers: [
        {
          duration: 60000,
          hasted: false,
          requiredSpells: [1262334],
        },
      ],
    },
    channel: {
      duration: 4000,
      hasted: true,
      buffIsLogged: true,
      triggeredSpells: [],
    },
    icon: 'ability_monk_cracklingjadelightning.jpg',
  },
  CRACKLING_JADE_LIGHTNING_HIDDEN: {
    id: 117959,
    type: 'baseline',
    iconID: 132269,
    passive: true,
    hidden: 'always',
    name: 'Crackling Jade Lightning',
    icon: 'ability_parry.jpg',
  },
  LEG_SWEEP: {
    id: 119381,
    type: 'baseline',
    iconID: 642414,
    passive: false,
    name: 'Leg Sweep',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
      modifiers: [
        {
          duration: -10000,
          hasted: false,
          requiredSpells: [344359],
        },
      ],
    },
    icon: 'ability_monk_legsweep.jpg',
  },
  PURIFYING_BREW_TALENT: {
    id: 119582,
    granted: false,
    requiresTalentEntry: [124838],
    type: 'talent',
    iconID: 133701,
    passive: false,
    name: 'Purifying Brew',
    charges: {
      max: 2,
    },
    cooldown: {
      duration: 20000,
      hasted: true,
      modifiers: [
        {
          duration: -4000,
          requiredSpells: [325093],
        },
      ],
    },
    icon: 'inv_misc_beer_06.jpg',
  },
  RENEWING_MIST_HIDDEN: {
    id: 119611,
    type: 'baseline',
    iconID: 627487,
    passive: false,
    hidden: 'always',
    name: 'Renewing Mist',
    icon: 'ability_monk_renewingmists.jpg',
  },
  ENERGY_USAGE_HIDDEN: {
    id: 119650,
    type: 'baseline',
    iconID: 135724,
    passive: false,
    hidden: 'always',
    name: 'Energy Usage',
    icon: 'mail_gmicon.jpg',
  },
  LEATHER_SPECIALIZATION_HIDDEN: {
    id: 120225,
    type: 'baseline',
    iconID: 132721,
    passive: true,
    hidden: 'always',
    name: 'Leather Specialization',
    icon: 'inv_chest_leather_06.jpg',
  },
  TOUCH_OF_DEATH_NOTIFICATION_DRIVER_HIDDEN: {
    id: 121128,
    type: 'baseline',
    iconID: 606552,
    passive: true,
    hidden: 'always',
    name: 'Touch of Death Notification Driver',
    icon: 'ability_monk_touchofdeath.jpg',
  },
  KEG_SMASH_TALENT: {
    id: 121253,
    granted: false,
    requiresTalentEntry: [124865],
    type: 'talent',
    iconID: 594274,
    passive: false,
    name: 'Keg Smash',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    charges: {
      max: 1,
      modifiers: [
        {
          max: 1,
          requiredSpells: [383707],
        },
      ],
    },
    cooldown: {
      duration: 8000,
      hasted: true,
    },
    icon: 'achievement_brewery_2.jpg',
  },
  FLYING_SERPENT_KICK_HIDDEN: {
    id: 123586,
    type: 'baseline',
    iconID: 463281,
    passive: false,
    hidden: 'always',
    name: 'Flying Serpent Kick',
    icon: 'priest_icon_chakra_green.jpg',
  },
  CHI_BURST_TALENT: {
    id: 123986,
    granted: false,
    requiresTalentEntry: [126501],
    type: 'talent',
    iconID: 135734,
    passive: false,
    name: 'Chi Burst',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
    castTime: {
      duration: 1000,
    },
    icon: 'spell_arcane_arcanetorrent.jpg',
  },
  DUAL_WIELD_HIDDEN: {
    id: 124146,
    type: 'baseline',
    iconID: 132147,
    passive: true,
    hidden: 'always',
    name: 'Dual Wield',
    icon: 'ability_dualwield.jpg',
  },
  TOUCH_OF_KARMA_HIDDEN: {
    id: 124280,
    type: 'baseline',
    iconID: 651728,
    passive: false,
    hidden: 'always',
    name: 'Touch of Karma',
    gcd: {
      duration: 1500,
      hasted: true,
    },
    icon: 'ability_monk_touchofkarma.jpg',
  },
  GIFT_OF_THE_OX_TALENT: {
    id: 124502,
    granted: false,
    requiresTalentEntry: [124845],
    type: 'talent',
    iconID: 236155,
    passive: true,
    name: 'Gift of the Ox',
    icon: 'ability_druid_giftoftheearthmother.jpg',
  },
  HEALING_SPHERE_HIDDEN: {
    id: 125355,
    type: 'baseline',
    iconID: 606546,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Healing Sphere',
    icon: 'ability_monk_healthsphere.jpg',
  },
  ZEN_FLIGHT: {
    id: 125883,
    type: 'baseline',
    iconID: 660248,
    passive: false,
    hidden: 'unless-learned',
    name: 'Zen Flight',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    icon: 'ability_monk_zenflight.jpg',
  },
  ZEN_PILGRIMAGE_ZEN_PILGRIMAGE: {
    id: 293866,
    grantedBy: 126892,
    type: 'temporary',
    iconID: 775462,
    passive: false,
    name: 'Zen Pilgrimage',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    castTime: {
      duration: 10000,
    },
    icon: 'spell_monk_zenpilgrimage.jpg',
  },
  ZEN_PILGRIMAGE: {
    id: 126892,
    type: 'baseline',
    iconID: 775462,
    passive: false,
    name: 'Zen Pilgrimage',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    castTime: {
      duration: 10000,
    },
    icon: 'spell_monk_zenpilgrimage.jpg',
  },
  ZEN_PILGRIMAGEDEATH_GATEMOONGLADE_STORAGE_AURA_I_HIDDEN: {
    id: 126893,
    type: 'baseline',
    iconID: 132181,
    passive: false,
    hidden: 'always',
    name: 'Zen Pilgrimage/Death Gate/Moonglade Storage Aura I',
    icon: 'ability_hunter_pathfinding.jpg',
  },
  ZEN_PILGRIMAGE_RETURN_HIDDEN: {
    id: 126895,
    type: 'baseline',
    iconID: 775462,
    passive: false,
    hidden: 'always',
    name: 'Zen Pilgrimage: Return',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    castTime: {
      duration: 10000,
    },
    icon: 'spell_monk_zenpilgrimage.jpg',
  },
  MONK_HIDDEN_1: {
    id: 130610,
    type: 'baseline',
    iconID: 572033,
    passive: true,
    hidden: 'always',
    name: 'Monk',
    icon: 'pandarenracial_bouncy.jpg',
  },
  MONK_HIDDEN_2: {
    id: 137022,
    type: 'baseline',
    iconID: 236216,
    passive: true,
    hidden: 'always',
    name: 'Monk',
    icon: 'ability_mage_firestarter.jpg',
  },
  MONK_HIDDEN_3: {
    id: 462088,
    type: 'baseline',
    iconID: 136243,
    passive: true,
    hidden: 'always',
    name: 'Monk',
    icon: 'trade_engineering.jpg',
  },
  CHI_BURST_HIDDEN: {
    id: 130654,
    type: 'baseline',
    iconID: 135734,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Burst',
    icon: 'spell_arcane_arcanetorrent.jpg',
  },
  CHI_WAVE_HIDDEN_1: {
    id: 132463,
    type: 'baseline',
    iconID: 606541,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Wave',
    icon: 'ability_monk_chiwave.jpg',
  },
  CHI_WAVE_HIDDEN_2: {
    id: 132467,
    type: 'baseline',
    iconID: 606541,
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Chi Wave',
    icon: 'ability_monk_chiwave.jpg',
  },
  INVOKE_NIUZAO_THE_BLACK_OX_TALENT: {
    id: 132578,
    granted: false,
    requiresTalentEntry: [124849],
    type: 'talent',
    iconID: 608951,
    passive: false,
    name: 'Invoke Niuzao, the Black Ox',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    cooldown: {
      duration: 120000,
      hasted: false,
      modifiers: [
        {
          duration: -25000,
          hasted: false,
          requiredSpells: [450989],
        },
      ],
    },
    icon: 'spell_monk_brewmaster_spec.jpg',
  },
  BREWMASTER_MONK_HIDDEN_1: {
    id: 137023,
    type: 'baseline',
    iconID: 236216,
    passive: true,
    hidden: 'always',
    name: 'Brewmaster Monk',
    icon: 'ability_mage_firestarter.jpg',
  },
  BREWMASTER_MONK_HIDDEN_2: {
    id: 462087,
    type: 'baseline',
    iconID: 136243,
    passive: true,
    hidden: 'always',
    name: 'Brewmaster Monk',
    icon: 'trade_engineering.jpg',
  },
  BREWMASTER_MONK_HIDDEN_3: {
    id: 1256978,
    type: 'baseline',
    iconID: 236216,
    passive: true,
    hidden: 'always',
    name: 'Brewmaster Monk',
    icon: 'ability_mage_firestarter.jpg',
  },
  BREWMASTER_MONK_HIDDEN_4: {
    id: 1258153,
    type: 'baseline',
    iconID: 236216,
    passive: true,
    hidden: 'always',
    name: 'Brewmaster Monk',
    icon: 'ability_mage_firestarter.jpg',
  },
  ROLL_SPEED_CONTROLS_HIDDEN: {
    id: 157361,
    type: 'baseline',
    iconID: 574574,
    passive: true,
    hidden: 'always',
    name: 'Roll Speed Controls',
    icon: 'ability_monk_roll.jpg',
  },
  CRITICAL_STRIKES_HIDDEN: {
    id: 157445,
    type: 'baseline',
    iconID: 458723,
    passive: true,
    hidden: 'always',
    name: 'Critical Strikes',
    icon: 'ability_rogue_combatexpertise.jpg',
  },
  STAT_NEGATION_AURA_AGILITY_TANK_HIDDEN: {
    id: 162700,
    type: 'baseline',
    iconID: 136243,
    passive: true,
    hidden: 'always',
    name: 'Stat Negation Aura - Agility Tank',
    icon: 'trade_engineering.jpg',
  },
  TOUCH_OF_FATALITY: {
    id: 169340,
    type: 'baseline',
    iconID: 606552,
    passive: false,
    hidden: 'unless-learned',
    name: 'Touch of Fatality',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    cooldown: {
      duration: 90000,
      hasted: false,
    },
    icon: 'ability_monk_touchofdeath.jpg',
  },
  SPECIAL_DELIVERY_TALENT: {
    id: 196730,
    granted: false,
    requiresTalentEntry: [125008],
    type: 'talent',
    iconID: 594274,
    passive: true,
    hidden: 'always',
    name: 'Special Delivery',
    icon: 'achievement_brewery_2.jpg',
  },
  BLACKOUT_COMBO_TALENT: {
    id: 196736,
    granted: false,
    requiresTalentEntry: [124996],
    type: 'talent',
    iconID: 574568,
    passive: true,
    hidden: 'always',
    name: 'Blackout Combo',
    icon: 'ability_monk_blackoutkick.jpg',
  },
  HIGH_TOLERANCE_TALENT: {
    id: 196737,
    granted: false,
    requiresTalentEntry: [124990],
    type: 'talent',
    iconID: 627605,
    passive: true,
    hidden: 'always',
    name: 'High Tolerance',
    icon: 'monk_ability_avertharm.jpg',
  },
  SHEILUNS_GIFT: {
    id: 205406,
    type: 'baseline',
    iconID: 1242282,
    passive: false,
    name: "Sheilun's Gift",
    gcd: {
      duration: 1500,
      hasted: true,
    },
    castTime: {
      duration: 2000,
    },
    icon: 'inv_staff_2h_artifactshaohao_d_01.jpg',
  },
  SOOTHING_MIST: {
    id: 209525,
    type: 'baseline',
    iconID: 606550,
    passive: false,
    hidden: 'unless-learned',
    name: 'Soothing Mist',
    gcd: {
      duration: 500,
      hasted: true,
    },
    cooldown: {
      duration: 1000,
      hasted: false,
    },
    channel: {
      duration: 20000,
      hasted: true,
      buffIsLogged: true,
      triggeredSpells: [],
    },
    icon: 'ability_monk_soothingmists.jpg',
  },
  CELESTIAL_FORTUNE_PASSIVE: {
    id: 216519,
    type: 'baseline',
    iconID: 656166,
    passive: true,
    name: 'Celestial Fortune',
    icon: 'inv_celestialserpentmount.jpg',
  },
  DETOX_TALENT: {
    id: 218164,
    granted: false,
    requiresTalentEntry: [124867],
    type: 'talent',
    iconID: 460692,
    passive: false,
    name: 'Detox',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    charges: {
      max: 1,
    },
    cooldown: {
      duration: 8000,
      hasted: false,
    },
    icon: 'ability_rogue_imrovedrecuperate.jpg',
  },
  IMPROVED_VIVIFY_HIDDEN: {
    id: 231602,
    type: 'baseline',
    iconID: 1360980,
    passive: true,
    hidden: 'always',
    name: 'Improved Vivify',
    icon: 'ability_monk_vivify.jpg',
  },
  BREWMASTERS_BALANCE_PASSIVE: {
    id: 245013,
    type: 'baseline',
    iconID: 574577,
    passive: true,
    name: "Brewmaster's Balance",
    icon: 'ability_monk_standingkick.jpg',
  },
  BOB_AND_WEAVE_TALENT: {
    id: 280515,
    granted: false,
    requiresTalentEntry: [124992],
    type: 'talent',
    iconID: 132096,
    passive: true,
    hidden: 'always',
    name: 'Bob and Weave',
    icon: 'ability_creature_cursed_04.jpg',
  },
  EXPEL_HARM: {
    id: 322101,
    type: 'baseline',
    iconID: 627486,
    passive: false,
    name: 'Expel Harm',
    gcd: {
      duration: 500,
      hasted: true,
    },
    cooldown: {
      duration: 5000,
      hasted: false,
    },
    icon: 'ability_monk_expelharm.jpg',
  },
  EXPEL_HARM_PASSIVE: {
    id: 322102,
    type: 'baseline',
    iconID: 627486,
    passive: true,
    name: 'Expel Harm',
    icon: 'ability_monk_expelharm.jpg',
  },
  TOUCH_OF_DEATH: {
    id: 322109,
    type: 'baseline',
    iconID: 606552,
    passive: false,
    name: 'Touch of Death',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 180000,
      hasted: false,
    },
    icon: 'ability_monk_touchofdeath.jpg',
  },
  SHUFFLE_TALENT: {
    id: 322120,
    granted: false,
    requiresTalentEntry: [124864],
    type: 'talent',
    iconID: 642416,
    passive: true,
    name: 'Shuffle',
    icon: 'ability_monk_shuffle.jpg',
  },
  CELESTIAL_BREW_TALENT: {
    id: 322507,
    granted: false,
    requiresTalentEntry: [124841],
    type: 'talent',
    iconID: 1360979,
    passive: false,
    name: 'Celestial Brew',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    charges: {
      max: 1,
      modifiers: [
        {
          max: 1,
          requiredSpells: [450892],
        },
      ],
    },
    cooldown: {
      duration: 45000,
      hasted: false,
      modifiers: [
        {
          duration: -9000,
          requiredSpells: [325093],
        },
      ],
    },
    icon: 'ability_monk_ironskinbrew.jpg',
  },
  SPINNING_CRANE_KICK_PASSIVE: {
    id: 322700,
    type: 'learned',
    taughtBy: 322120,
    iconID: 606543,
    passive: true,
    name: 'Spinning Crane Kick',
    icon: 'ability_monk_cranekick_new.jpg',
  },
  MIGHTY_STOMP_TALENT: {
    id: 322740,
    granted: false,
    requiresTalentEntry: [124847],
    type: 'talent',
    iconID: 634014,
    passive: true,
    hidden: 'always',
    name: 'Mighty Stomp',
    icon: 'inv_inscription_trinket_ox.jpg',
  },
  FORTIFYING_BREW_DETERMINATION_TALENT: {
    id: 322960,
    granted: false,
    requiresTalentEntry: [124842],
    type: 'talent',
    iconID: 615341,
    passive: true,
    hidden: 'always',
    name: 'Fortifying Brew: Determination',
    icon: 'ability_monk_fortifyingale_new.jpg',
  },
  LIGHT_BREWING_TALENT: {
    id: 325093,
    granted: false,
    requiresTalentEntry: [124858],
    type: 'talent',
    iconID: 623777,
    passive: true,
    hidden: 'always',
    name: 'Light Brewing',
    icon: 'spell_brew_wheat.jpg',
  },
  TOUCH_OF_DEATH_PASSIVE: {
    id: 325095,
    type: 'baseline',
    iconID: 606552,
    passive: true,
    name: 'Touch of Death',
    icon: 'ability_monk_touchofdeath.jpg',
  },
  EXPLODING_KEG_TALENT: {
    id: 325153,
    granted: false,
    requiresTalentEntry: [125001],
    type: 'talent',
    iconID: 7439206,
    passive: false,
    name: 'Exploding Keg',
    gcd: {
      duration: 1000,
      hasted: false,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
    icon: 'inv12_ability_monk_explodingkeg.jpg',
  },
  ANCIENT_ARTS_TALENT: {
    id: 344359,
    granted: false,
    requiresTalentEntry: [124983],
    type: 'talent',
    iconID: 574570,
    passive: true,
    hidden: 'always',
    name: 'Ancient Arts',
    icon: 'ability_monk_dpsstance.jpg',
  },
  WINDWALKER_MONK_TWO_HAND_ADJUSTMENT_HIDDEN: {
    id: 346104,
    type: 'baseline',
    iconID: 574570,
    passive: true,
    hidden: 'always',
    name: 'Windwalker Monk Two-Hand Adjustment',
    icon: 'ability_monk_dpsstance.jpg',
  },
  IMPROVED_BLACKOUT_KICK_TALENT: {
    id: 383695,
    granted: false,
    requiresTalentEntry: [124846],
    type: 'talent',
    iconID: 574575,
    passive: true,
    hidden: 'always',
    name: 'Improved Blackout Kick',
    icon: 'ability_monk_roundhousekick.jpg',
  },
  SALSALABIMS_STRENGTH_TALENT: {
    id: 383697,
    granted: false,
    requiresTalentEntry: [124988],
    type: 'talent',
    iconID: 236317,
    passive: true,
    hidden: 'always',
    name: "Sal'salabim's Strength",
    icon: 'ability_warrior_unrelentingassault.jpg',
  },
  SCALDING_BREW_TALENT: {
    id: 383698,
    granted: false,
    requiresTalentEntry: [124989],
    type: 'talent',
    iconID: 623960,
    passive: true,
    hidden: 'always',
    name: 'Scalding Brew',
    icon: 'spell_brew_bolt_dark.jpg',
  },
  GAI_PLINS_IMPERIAL_BREW_TALENT: {
    id: 383700,
    granted: false,
    requiresTalentEntry: [124859],
    type: 'talent',
    iconID: 133700,
    passive: true,
    hidden: 'always',
    name: "Gai Plin's Imperial Brew",
    icon: 'inv_misc_beer_05.jpg',
  },
  STORMSTOUTS_LAST_KEG_TALENT: {
    id: 383707,
    granted: false,
    requiresTalentEntry: [124999],
    type: 'talent',
    iconID: 594274,
    passive: true,
    hidden: 'always',
    name: "Stormstout's Last Keg",
    icon: 'achievement_brewery_2.jpg',
  },
  TRAINING_OF_NIUZAO_TALENT: {
    id: 383714,
    granted: false,
    requiresTalentEntry: [124857],
    type: 'talent',
    iconID: 611419,
    passive: true,
    hidden: 'always',
    name: 'Training of Niuzao',
    icon: 'monk_stance_drunkenox.jpg',
  },
  COUNTERSTRIKE_TALENT: {
    id: 383785,
    granted: false,
    requiresTalentEntry: [124854],
    type: 'talent',
    iconID: 574573,
    passive: true,
    hidden: 'always',
    name: 'Counterstrike',
    icon: 'ability_monk_palmstrike.jpg',
  },
  DRAGONFIRE_BREW_TALENT: {
    id: 383994,
    granted: false,
    requiresTalentEntry: [124987],
    type: 'talent',
    iconID: 135789,
    passive: true,
    hidden: 'always',
    name: 'Dragonfire Brew',
    icon: 'spell_fire_burnout.jpg',
  },
  ANVIL_AND_STAVE_TALENT: {
    id: 386937,
    granted: false,
    requiresTalentEntry: [124856],
    type: 'talent',
    iconID: 613396,
    passive: true,
    hidden: 'always',
    name: 'Anvil and Stave',
    icon: 'ability_monk_elusiveale.jpg',
  },
  CHARRED_PASSIONS_TALENT: {
    id: 386965,
    granted: false,
    requiresTalentEntry: [124986],
    type: 'talent',
    iconID: 1381297,
    passive: true,
    hidden: 'always',
    name: 'Charred Passions',
    icon: 'ability_monk_mightyoxkick.jpg',
  },
  ELUSIVE_FOOTWORK_TALENT: {
    id: 387046,
    granted: false,
    requiresTalentEntry: [136145],
    type: 'talent',
    iconID: 642416,
    passive: true,
    hidden: 'always',
    name: 'Elusive Footwork',
    icon: 'ability_monk_shuffle.jpg',
  },
  WALK_WITH_THE_OX_TALENT: {
    id: 387219,
    granted: false,
    requiresTalentEntry: [124848],
    type: 'talent',
    iconID: 615340,
    passive: true,
    hidden: 'always',
    name: 'Walk with the Ox',
    icon: 'ability_monk_chargingoxwave.jpg',
  },
  FLUIDITY_OF_MOTION_TALENT: {
    id: 387230,
    granted: false,
    requiresTalentEntry: [124852],
    type: 'talent',
    iconID: 574577,
    passive: true,
    hidden: 'always',
    name: 'Fluidity of Motion',
    icon: 'ability_monk_standingkick.jpg',
  },
  STRENGTH_OF_SPIRIT_TALENT: {
    id: 387276,
    granted: false,
    requiresTalentEntry: [124924],
    type: 'talent',
    iconID: 606546,
    passive: true,
    hidden: 'always',
    name: 'Strength of Spirit',
    icon: 'ability_monk_healthsphere.jpg',
  },
  STAGGERING_STRIKES_TALENT: {
    id: 387625,
    granted: false,
    requiresTalentEntry: [124839],
    type: 'talent',
    iconID: 1500803,
    passive: true,
    hidden: 'always',
    name: 'Staggering Strikes',
    icon: 'ability_monk_blackoutstrike.jpg',
  },
  SHADOWBOXING_TREADS_TALENT: {
    id: 387638,
    granted: false,
    requiresTalentEntry: [124853],
    type: 'talent',
    iconID: 574575,
    passive: true,
    hidden: 'always',
    name: 'Shadowboxing Treads',
    icon: 'ability_monk_roundhousekick.jpg',
  },
  QUICK_SIP_TALENT: {
    id: 388505,
    granted: false,
    requiresTalentEntry: [136148],
    type: 'talent',
    iconID: 645193,
    passive: true,
    hidden: 'always',
    name: 'Quick Sip',
    icon: 'achievement_faction_brewmaster.jpg',
  },
  CALMING_PRESENCE_TALENT: {
    id: 388664,
    granted: false,
    requiresTalentEntry: [124944],
    type: 'talent',
    iconID: 134333,
    passive: true,
    hidden: 'always',
    name: 'Calming Presence',
    icon: 'inv_misc_orb_01.jpg',
  },
  ELUSIVE_MISTS_TALENT: {
    id: 388681,
    granted: false,
    requiresTalentEntry: [124934],
    type: 'talent',
    iconID: 606550,
    passive: true,
    hidden: 'always',
    name: 'Elusive Mists',
    icon: 'ability_monk_soothingmists.jpg',
  },
  GRACE_OF_THE_CRANE_TALENT: {
    id: 388811,
    granted: false,
    requiresTalentEntry: [124936],
    type: 'talent',
    iconID: 608949,
    passive: true,
    hidden: 'always',
    name: 'Grace of the Crane',
    icon: 'monk_ability_cherrymanatea.jpg',
  },
  VIVACIOUS_VIVIFICATION_TALENT: {
    id: 388812,
    granted: false,
    requiresTalentEntry: [124935],
    type: 'talent',
    iconID: 1360980,
    passive: true,
    hidden: 'always',
    name: 'Vivacious Vivification',
    icon: 'ability_monk_vivify.jpg',
  },
  FACE_PALM_TALENT: {
    id: 389942,
    granted: false,
    requiresTalentEntry: [124855],
    type: 'talent',
    iconID: 606551,
    passive: true,
    hidden: 'always',
    name: 'Face Palm',
    icon: 'ability_monk_tigerpalm.jpg',
  },
  VIGOROUS_EXPULSION_TALENT: {
    id: 392900,
    granted: false,
    requiresTalentEntry: [124948],
    type: 'talent',
    iconID: 627486,
    passive: true,
    hidden: 'always',
    name: 'Vigorous Expulsion',
    icon: 'ability_monk_expelharm.jpg',
  },
  PROFOUND_REBUTTAL_TALENT: {
    id: 392910,
    granted: false,
    requiresTalentEntry: [124923],
    type: 'talent',
    iconID: 627486,
    passive: true,
    hidden: 'always',
    name: 'Profound Rebuttal',
    icon: 'ability_monk_expelharm.jpg',
  },
  TRANQUIL_SPIRIT_TALENT: {
    id: 393357,
    granted: false,
    requiresTalentEntry: [124860],
    type: 'talent',
    iconID: 1056569,
    passive: true,
    hidden: 'always',
    name: 'Tranquil Spirit',
    icon: 'ability_monk_chiswirl.jpg',
  },
  PRETENSE_OF_INSTABILITY_TALENT: {
    id: 393516,
    granted: false,
    requiresTalentEntry: [125006],
    type: 'talent',
    iconID: 516667,
    passive: true,
    hidden: 'always',
    name: 'Pretense of Instability',
    icon: 'inv_misc_archaeology_vrykuldrinkinghorn.jpg',
  },
  SPIRIT_OF_THE_OX_TALENT: {
    id: 400629,
    granted: false,
    requiresTalentEntry: [124863],
    type: 'talent',
    iconID: 897131,
    passive: true,
    name: 'Spirit of the Ox',
    icon: 'ability_titankeeper_cleansingorb.jpg',
  },
  DANCE_OF_THE_WIND_TALENT: {
    id: 414132,
    granted: false,
    requiresTalentEntry: [124979],
    type: 'talent',
    iconID: 4067369,
    passive: true,
    name: 'Dance of the Wind',
    icon: 'ability_monk_dematerialize.jpg',
  },
  PRESS_THE_ADVANTAGE_TALENT: {
    id: 418359,
    granted: false,
    requiresTalentEntry: [124997],
    overrides: 100780,
    type: 'talent',
    iconID: 2032605,
    passive: true,
    hidden: 'always',
    name: 'Press the Advantage',
    icon: 'inv__fistofthewhitetiger.jpg',
  },
  CRASHING_MOMENTUM_TALENT: {
    id: 450335,
    granted: false,
    requiresTalentEntry: [124940],
    type: 'talent',
    iconID: 574568,
    passive: true,
    name: 'Crashing Momentum',
    icon: 'ability_monk_blackoutkick.jpg',
  },
  CHI_WAVE_TALENT: {
    id: 450391,
    granted: false,
    requiresTalentEntry: [126502],
    type: 'talent',
    iconID: 606541,
    passive: true,
    name: 'Chi Wave',
    icon: 'ability_monk_chiwave.jpg',
  },
  PRESSURE_POINTS_TALENT: {
    id: 450432,
    granted: false,
    requiresTalentEntry: [124931],
    type: 'talent',
    iconID: 629533,
    passive: true,
    name: 'Pressure Points',
    icon: 'ability_monk_deadlyreach.jpg',
  },
  ASPECT_OF_HARMONY_TALENT: {
    id: 450508,
    granted: false,
    requiresTalentEntry: [125033],
    type: 'talent',
    iconID: 5927638,
    passive: true,
    name: 'Aspect of Harmony',
    icon: 'inv_ability_masterofharmonymonk_aspectofharmony.jpg',
  },
  WINDS_REACH_TALENT: {
    id: 450514,
    granted: false,
    requiresTalentEntry: [124938],
    type: 'talent',
    iconID: 660248,
    passive: true,
    name: "Wind's Reach",
    icon: 'ability_monk_zenflight.jpg',
  },
  BOUNDING_AGILITY_TALENT: {
    id: 450520,
    granted: false,
    requiresTalentEntry: [124955],
    type: 'talent',
    iconID: 574574,
    passive: true,
    name: 'Bounding Agility',
    icon: 'ability_monk_roll.jpg',
  },
  COALESCENCE_TALENT: {
    id: 450529,
    granted: false,
    requiresTalentEntry: [125039],
    type: 'talent',
    iconID: 1360977,
    passive: true,
    name: 'Coalescence',
    icon: 'ability_monk_effuse.jpg',
  },
  JADE_WALK_TALENT: {
    id: 450553,
    granted: false,
    requiresTalentEntry: [124954],
    type: 'talent',
    iconID: 348567,
    passive: true,
    name: 'Jade Walk',
    icon: 'spell_lifegivingspeed.jpg',
  },
  FLURRY_STRIKES_TALENT: {
    id: 450615,
    granted: false,
    requiresTalentEntry: [125069],
    type: 'talent',
    iconID: 5927648,
    passive: true,
    name: 'Flurry Strikes',
    icon: 'inv_ability_shadopanmonk_flurrystrikes.jpg',
  },
  ENERGY_TRANSFER_TALENT: {
    id: 450631,
    granted: false,
    requiresTalentEntry: [124942],
    type: 'talent',
    iconID: 627605,
    passive: true,
    hidden: 'always',
    name: 'Energy Transfer',
    icon: 'monk_ability_avertharm.jpg',
  },
  PURIFIED_SPIRIT_TALENT: {
    id: 450867,
    granted: false,
    requiresTalentEntry: [125035],
    type: 'talent',
    iconID: 620828,
    passive: true,
    name: 'Purified Spirit',
    icon: 'ability_monk_explodingjadeblossom.jpg',
  },
  HARMONIC_GAMBIT_TALENT: {
    id: 450870,
    granted: false,
    requiresTalentEntry: [125034],
    type: 'talent',
    iconID: 611422,
    passive: true,
    name: 'Harmonic Gambit',
    icon: 'passive_monk_teachingsofmonastery.jpg',
  },
  MANIFESTATION_TALENT: {
    id: 450875,
    granted: false,
    requiresTalentEntry: [125032],
    type: 'talent',
    iconID: 1629909,
    passive: true,
    name: 'Manifestation',
    icon: 'inv_shoulder_inv_leather_raidmonk_s_01.jpg',
  },
  BALANCED_STRATAGEM_TALENT: {
    id: 450889,
    granted: false,
    requiresTalentEntry: [125043],
    type: 'talent',
    iconID: 5094560,
    passive: true,
    name: 'Balanced Stratagem',
    icon: 'ability_monk_sphereharmonydiscord.jpg',
  },
  ENDLESS_DRAUGHT_TALENT: {
    id: 450892,
    granted: false,
    requiresTalentEntry: [125036],
    type: 'talent',
    iconID: 132812,
    passive: true,
    name: 'Endless Draught',
    icon: 'inv_drink_25_honeytea.jpg',
  },
  PATH_OF_RESURGENCE_TALENT: {
    id: 450912,
    granted: false,
    requiresTalentEntry: [125038],
    type: 'talent',
    iconID: 988196,
    passive: true,
    name: 'Path of Resurgence',
    icon: 'ability_monk_pathofmists.jpg',
  },
  WAY_OF_A_THOUSAND_STRIKES_TALENT: {
    id: 450965,
    granted: false,
    requiresTalentEntry: [125037],
    type: 'talent',
    iconID: 1381297,
    passive: true,
    name: 'Way of a Thousand Strikes',
    icon: 'ability_monk_mightyoxkick.jpg',
  },
  PRIDE_OF_PANDARIA_TALENT: {
    id: 450979,
    granted: false,
    requiresTalentEntry: [125068],
    type: 'talent',
    iconID: 839611,
    passive: true,
    name: 'Pride of Pandaria',
    icon: 'inv_staff_2h_pandarenmonk_c_01.jpg',
  },
  HIGH_IMPACT_TALENT: {
    id: 450982,
    granted: false,
    requiresTalentEntry: [125067],
    type: 'talent',
    iconID: 629484,
    passive: true,
    name: 'High Impact',
    icon: 'ability_monk_powerstrikes.jpg',
  },
  AGAINST_ALL_ODDS_TALENT: {
    id: 450986,
    granted: false,
    requiresTalentEntry: [125074],
    type: 'talent',
    iconID: 1713482,
    passive: true,
    name: 'Against All Odds',
    icon: 'achievement_legionpvp6tier1.jpg',
  },
  VETERANS_EYE_TALENT: {
    id: 450987,
    granted: false,
    requiresTalentEntry: [125070],
    type: 'talent',
    iconID: 620830,
    passive: true,
    name: "Veteran's Eye",
    icon: 'ability_monk_provoke.jpg',
  },
  ONE_VERSUS_MANY_TALENT: {
    id: 450988,
    granted: false,
    requiresTalentEntry: [125071],
    type: 'talent',
    iconID: 615340,
    passive: true,
    name: 'One Versus Many',
    icon: 'ability_monk_chargingoxwave.jpg',
  },
  EFFICIENT_TRAINING_TALENT: {
    id: 450989,
    granted: false,
    requiresTalentEntry: [125072],
    type: 'talent',
    iconID: 2065583,
    passive: true,
    name: 'Efficient Training',
    icon: 'inv_fistofthewhitetiger.jpg',
  },
  MARTIAL_PRECISION_TALENT: {
    id: 450990,
    granted: false,
    requiresTalentEntry: [125066],
    type: 'talent',
    iconID: 574572,
    passive: true,
    name: 'Martial Precision',
    icon: 'ability_monk_jab.jpg',
  },
  WHIRLING_STEEL_TALENT: {
    id: 450991,
    granted: false,
    requiresTalentEntry: [125065],
    type: 'talent',
    iconID: 132369,
    passive: true,
    name: 'Whirling Steel',
    icon: 'ability_whirlwind.jpg',
  },
  PREDICTIVE_TRAINING_TALENT: {
    id: 450992,
    granted: false,
    requiresTalentEntry: [125064],
    type: 'talent',
    iconID: 1381295,
    passive: true,
    name: 'Predictive Training',
    icon: 'ability_monk_domeofmist.jpg',
  },
  VIGILANT_WATCH_TALENT: {
    id: 450993,
    granted: false,
    requiresTalentEntry: [125063],
    type: 'talent',
    iconID: 132299,
    passive: true,
    name: 'Vigilant Watch',
    icon: 'ability_rogue_masterofsubtlety.jpg',
  },
  CLARITY_OF_PURPOSE_TALENT: {
    id: 451017,
    granted: false,
    requiresTalentEntry: [125040],
    type: 'talent',
    iconID: 897130,
    passive: true,
    name: 'Clarity of Purpose',
    icon: 'ability_titankeeper_cleanse.jpg',
  },
  OVERWHELMING_FORCE_TALENT: {
    id: 451024,
    granted: false,
    requiresTalentEntry: [125029],
    type: 'talent',
    iconID: 897137,
    passive: true,
    name: 'Overwhelming Force',
    icon: 'ability_titankeeper_piercingcorruption.jpg',
  },
  MANTRA_OF_TENACITY_TALENT: {
    id: 451029,
    granted: false,
    requiresTalentEntry: [125041],
    type: 'talent',
    iconID: 608950,
    passive: true,
    name: 'Mantra of Tenacity',
    icon: 'spell_monk_brewmastertraining.jpg',
  },
  MANTRA_OF_PURITY_TALENT: {
    id: 451036,
    granted: false,
    requiresTalentEntry: [125042],
    type: 'talent',
    iconID: 1381295,
    passive: true,
    name: 'Mantra of Purity',
    icon: 'ability_monk_domeofmist.jpg',
  },
  TIGERS_VIGOR_TALENT: {
    id: 451041,
    granted: false,
    requiresTalentEntry: [125031],
    type: 'talent',
    iconID: 611420,
    passive: true,
    name: "Tiger's Vigor",
    icon: 'monk_stance_whitetiger.jpg',
  },
  ROAR_FROM_THE_HEAVENS_TALENT: {
    id: 451043,
    granted: false,
    requiresTalentEntry: [125030],
    type: 'talent',
    iconID: 656166,
    passive: true,
    name: 'Roar from the Heavens',
    icon: 'inv_celestialserpentmount.jpg',
  },
  AUGUST_BLESSING_TALENT: {
    id: 454483,
    granted: false,
    requiresTalentEntry: [136147],
    type: 'talent',
    iconID: 656166,
    passive: true,
    name: 'August Blessing',
    icon: 'inv_celestialserpentmount.jpg',
  },
  ONE_WITH_THE_WIND_TALENT: {
    id: 454484,
    granted: false,
    requiresTalentEntry: [125611],
    type: 'talent',
    iconID: 1029595,
    passive: true,
    name: 'One With the Wind',
    icon: 'ability_skyreach_wind.jpg',
  },
  OX_STANCE_TALENT: {
    id: 455068,
    granted: false,
    requiresTalentEntry: [125004],
    type: 'talent',
    iconID: 620829,
    passive: true,
    name: 'Ox Stance',
    icon: 'ability_monk_leeroftheox.jpg',
  },
  ELIXIR_OF_DETERMINATION_TALENT: {
    id: 455139,
    granted: false,
    requiresTalentEntry: [124862],
    type: 'talent',
    iconID: 608949,
    passive: true,
    name: 'Elixir of Determination',
    icon: 'monk_ability_cherrymanatea.jpg',
  },
  SINGLE_BUTTON_ASSISTANT: {
    id: 1229376,
    type: 'baseline',
    iconID: 6718291,
    passive: false,
    name: 'Single-Button Assistant',
    castTime: {
      duration: 2000,
    },
    icon: 'ui_spellbook_onebutton.jpg',
  },
  CELESTIAL_INFUSION_TALENT: {
    id: 1241059,
    granted: false,
    requiresTalentEntry: [136146],
    type: 'talent',
    iconID: 613399,
    passive: false,
    name: 'Celestial Infusion',
    gcd: {
      duration: 1000,
      hasted: true,
    },
    charges: {
      max: 1,
      modifiers: [
        {
          max: 1,
          requiredSpells: [450892],
        },
      ],
    },
    cooldown: {
      duration: 45000,
      hasted: false,
      modifiers: [
        {
          duration: -9000,
          requiredSpells: [325093],
        },
      ],
    },
    icon: 'ability_monk_tigereyebrandy.jpg',
  },
  NIUZAOS_RESOLVE_TALENT: {
    id: 1241097,
    granted: false,
    requiresTalentEntry: [124861],
    type: 'talent',
    iconID: 5901829,
    passive: true,
    name: "Niuzao's Resolve",
    icon: 'inv_ability_monk_renewingmists_active.jpg',
  },
  ZEN_STATE_TALENT: {
    id: 1241136,
    granted: false,
    requiresTalentEntry: [124851],
    type: 'talent',
    iconID: 775462,
    passive: true,
    name: 'Zen State',
    icon: 'spell_monk_zenpilgrimage.jpg',
  },
  FAST_FEET_TALENT: {
    id: 1261543,
    granted: false,
    requiresTalentEntry: [136085],
    type: 'talent',
    iconID: 1381297,
    passive: true,
    hidden: 'always',
    name: 'Fast Feet',
    icon: 'ability_monk_mightyoxkick.jpg',
  },
  FUEL_ON_THE_FIRE_TALENT: {
    id: 1262017,
    granted: false,
    requiresTalentEntry: [125003],
    type: 'talent',
    iconID: 237588,
    passive: true,
    hidden: 'always',
    name: 'Fuel on the Fire',
    icon: 'spell_shaman_stormearthfire.jpg',
  },
  EMPTY_THE_CELLAR_TALENT: {
    id: 1262329,
    granted: false,
    requiresTalentEntry: [136150],
    type: 'talent',
    iconID: 252176,
    passive: true,
    hidden: 'always',
    name: 'Empty the Cellar',
    icon: 'ability_vehicle_liquidpyrite.jpg',
  },
  JADE_FLASH_TALENT: {
    id: 1262334,
    granted: false,
    requiresTalentEntry: [124844],
    type: 'talent',
    iconID: 1385915,
    passive: true,
    name: 'Jade Flash',
    icon: 'shaman_pvp_staticcling.jpg',
  },
  STAND_READY_TALENT: {
    id: 1262603,
    granted: false,
    requiresTalentEntry: [135956],
    type: 'talent',
    iconID: 615342,
    passive: true,
    hidden: 'always',
    name: 'Stand Ready',
    icon: 'ability_monk_sparring.jpg',
  },
  WEAPONS_OF_THE_WALL_TALENT: {
    id: 1262610,
    granted: false,
    requiresTalentEntry: [135957],
    type: 'talent',
    iconID: 1603009,
    passive: true,
    hidden: 'always',
    name: 'Weapons of the Wall',
    icon: 'misc_legionfall_monk.jpg',
  },
  SHADO_OVER_THE_BATTLEFIELD_TALENT: {
    id: 1262612,
    granted: false,
    requiresTalentEntry: [135955],
    type: 'talent',
    iconID: 132851,
    passive: true,
    hidden: 'always',
    name: 'Shado Over the Battlefield',
    icon: 'inv_elemental_primal_shadow.jpg',
  },
  AWAKENING_SPIRIT_TALENT: {
    id: 1262628,
    granted: false,
    requiresTalentEntry: [125000],
    type: 'talent',
    iconID: 897027,
    passive: true,
    hidden: 'always',
    name: 'Awakening Spirit',
    icon: 'achievement_boss_golden_lotus_council.jpg',
  },
  VITAL_FLAME_TALENT: {
    id: 1262659,
    granted: false,
    requiresTalentEntry: [136149],
    type: 'talent',
    iconID: 645204,
    passive: true,
    hidden: 'always',
    name: 'Vital Flame',
    icon: 'achievement_faction_shadopan.jpg',
  },
  KEG_VOLLEY_TALENT: {
    id: 1262764,
    granted: false,
    requiresTalentEntry: [125002],
    type: 'talent',
    iconID: 1266518,
    passive: true,
    hidden: 'always',
    name: 'Keg Volley',
    icon: 'inv_staff_2h_artifactmonkeyking_d_02.jpg',
  },
  HEART_OF_THE_OX_TALENT: {
    id: 1263245,
    granted: false,
    requiresTalentEntry: [136177],
    type: 'talent',
    iconID: 4572410,
    passive: true,
    hidden: 'always',
    name: 'Heart of the Ox',
    icon: 'inv_muskox_white.jpg',
  },
  SWIFT_AS_A_COURSING_RIVER_TALENT: {
    id: 1263346,
    granted: false,
    requiresTalentEntry: [124837],
    type: 'talent',
    iconID: 965900,
    passive: true,
    name: 'Swift as a Coursing River',
    icon: 'ability_rogue_sprint_blue.jpg',
  },
  CELESTIAL_FLAMES_TALENT: {
    id: 1263353,
    granted: false,
    requiresTalentEntry: [124850],
    type: 'talent',
    iconID: 463567,
    passive: true,
    hidden: 'always',
    name: 'Celestial Flames',
    icon: 'inv_misc_volatilefire.jpg',
  },
  BRING_ME_ANOTHER_TALENT_1: {
    id: 1265129,
    granted: false,
    requiresTalentEntry: [136235],
    type: 'talent',
    iconID: 5899327,
    passive: true,
    name: 'Bring Me Another',
    icon: 'inv_achievement_dungeon_cinderbrewmeadery.jpg',
  },
  BRING_ME_ANOTHER_TALENT_2: {
    id: 1265138,
    granted: false,
    requiresTalentEntry: [136234],
    type: 'talent',
    iconID: 5899327,
    passive: true,
    name: 'Bring Me Another',
    icon: 'inv_achievement_dungeon_cinderbrewmeadery.jpg',
  },
  BRING_ME_ANOTHER_TALENT_3: {
    id: 1265141,
    granted: false,
    requiresTalentEntry: [136233],
    type: 'talent',
    iconID: 5899327,
    passive: true,
    name: 'Bring Me Another',
    icon: 'inv_achievement_dungeon_cinderbrewmeadery.jpg',
  },
  SILENT_SANCTUARY_TALENT: {
    id: 1266719,
    granted: false,
    requiresTalentEntry: [136517],
    type: 'talent',
    iconID: 775462,
    passive: true,
    hidden: 'always',
    name: 'Silent Sanctuary',
    icon: 'spell_monk_zenpilgrimage.jpg',
  },
  REINVIGORATION_TALENT: {
    id: 1266740,
    granted: false,
    requiresTalentEntry: [136520],
    type: 'talent',
    iconID: 607848,
    passive: true,
    hidden: 'always',
    name: 'Reinvigoration',
    icon: 'ability_monk_quipunch.jpg',
  },
  HARMONIC_SURGE_TALENT: {
    id: 1270958,
    granted: false,
    requiresTalentEntry: [135952],
    type: 'talent',
    iconID: 1041235,
    passive: true,
    hidden: 'always',
    name: 'Harmonic Surge',
    icon: 'ability_socererking_forcenova.jpg',
  },
  POTENTIAL_ENERGY_TALENT: {
    id: 1271048,
    granted: false,
    requiresTalentEntry: [135953],
    type: 'talent',
    iconID: 237551,
    passive: true,
    hidden: 'always',
    name: 'Potential Energy',
    icon: 'spell_magic_managain.jpg',
  },
  MEDITATIVE_FOCUS_TALENT: {
    id: 1271105,
    granted: false,
    requiresTalentEntry: [135954],
    type: 'talent',
    iconID: 134215,
    passive: true,
    hidden: 'always',
    name: 'Meditative Focus',
    icon: 'inv_misc_herb_mountainsilversage.jpg',
  },
  WISDOM_OF_THE_WALL_TALENT: {
    id: 1272821,
    granted: false,
    requiresTalentEntry: [125073],
    type: 'talent',
    iconID: 656542,
    passive: true,
    name: 'Wisdom of the Wall',
    icon: 'inv_legendary_sigilofwisdom.jpg',
  },
  COMBAT_STANCE_TALENT: {
    id: 1272844,
    granted: false,
    requiresTalentEntry: [125076],
    type: 'talent',
    iconID: 574574,
    passive: true,
    hidden: 'always',
    name: 'Combat Stance',
    icon: 'ability_monk_roll.jpg',
  },
  INITIATORS_EDGE_TALENT: {
    id: 1272849,
    granted: false,
    requiresTalentEntry: [125075],
    type: 'talent',
    iconID: 1362366,
    passive: true,
    hidden: 'always',
    name: "Initiator's Edge",
    icon: 'crest_monk.jpg',
  },
} as const satisfies Record<string, RetailSpell & { icon: string }>;
export default SPELLS;
