import SPELLS from 'common/SPELLS';
import { TALENTS_MONK } from 'common/TALENTS/monk';

export const CELESTIAL_CONDUIT_MAX_DURATION = 4000;
export const CELESTIAL_CONDUIT_INCREASE_PER_TARGET = 0.06;
export const CELESTIAL_CONDUIT_MAX_TARGETS = 5;
export const RESTORE_BALANCE_BOOST = 0.05;
export const MISTWEAVER_HEART_SPELLS = (hasRWK: boolean): number[] => [
  SPELLS.RENEWING_MIST_CAST.id,
  hasRWK
    ? TALENTS_MONK.RUSHING_WIND_KICK_MISTWEAVER_TALENT.id
    : TALENTS_MONK.RISING_SUN_KICK_TALENT.id,
  TALENTS_MONK.THUNDER_FOCUS_TEA_TALENT.id,
  TALENTS_MONK.LIFE_COCOON_TALENT.id,
];

export const WINDWALKER_HEART_SPELLS = [
  TALENTS_MONK.RISING_SUN_KICK_TALENT.id,
  TALENTS_MONK.FISTS_OF_FURY_TALENT.id,
  TALENTS_MONK.STRIKE_OF_THE_WINDLORD_TALENT.id,
  TALENTS_MONK.WHIRLING_DRAGON_PUNCH_TALENT.id,
];
