import { TALENTS_MONK } from 'common/TALENTS/monk';

export const CELESTIAL_CONDUIT_MAX_DURATION = 4000;
export const CELESTIAL_CONDUIT_INCREASE_PER_TARGET = 0.06;
export const CELESTIAL_CONDUIT_MAX_TARGETS = 5;
export const MISTWEAVER_HEART_SPELLS = [
  TALENTS_MONK.RENEWING_MIST_TALENT.id,
  TALENTS_MONK.RISING_SUN_KICK_TALENT.id,
  TALENTS_MONK.THUNDER_FOCUS_TEA_TALENT.id,
  TALENTS_MONK.LIFE_COCOON_TALENT.id,
];

export const WINDWALKER_HEART_SPELLS = [
  TALENTS_MONK.RISING_SUN_KICK_TALENT.id,
  TALENTS_MONK.FISTS_OF_FURY_TALENT.id,
  TALENTS_MONK.STRIKE_OF_THE_WINDLORD_TALENT.id,
  TALENTS_MONK.WHIRLING_DRAGON_PUNCH_TALENT.id,
];
