// Generated file, changes will eventually be overwritten!
import { createTalentList } from './types';

const talents = createTalentList({
  ABOMINATION_LIMB_TALENT: {
    id: 383269,
    name: 'Abomination Limb',
    icon: 'ability_maldraxxus_deathknight',
    maxRanks: 1,
    entryIds: [96177],
  },
  ABSOLUTE_ZERO_TALENT: {
    id: 377047,
    name: 'Absolute Zero',
    icon: 'spell_fire_blueflamering',
    maxRanks: 1,
    entryIds: [96223],
  },
  ACCLIMATION_TALENT: {
    id: 373926,
    name: 'Acclimation',
    icon: 'spell_deathknight_iceboundfortitude',
    maxRanks: 1,
    entryIds: [96175],
  },
  ALL_WILL_SERVE_TALENT: {
    id: 194916,
    name: 'All Will Serve',
    icon: 'ability_fiegndead',
    maxRanks: 1,
    entryIds: [96317],
  },
  ANTI_MAGIC_BARRIER_TALENT: {
    id: 205727,
    name: 'Anti-Magic Barrier',
    icon: 'spell_shadow_antimagicshell',
    maxRanks: 1,
    entryIds: [96174],
  },
  ANTI_MAGIC_SHELL_TALENT: {
    id: 48707,
    name: 'Anti-Magic Shell',
    icon: 'spell_shadow_antimagicshell',
    maxRanks: 1,
    entryIds: [96199],
  },
  ANTI_MAGIC_ZONE_TALENT: {
    id: 51052,
    name: 'Anti-Magic Zone',
    icon: 'spell_deathknight_antimagiczone',
    maxRanks: 1,
    entryIds: [96194],
  },
  APOCALYPSE_TALENT: {
    id: 275699,
    name: 'Apocalypse',
    icon: 'artifactability_unholydeathknight_deathsembrace',
    maxRanks: 1,
    entryIds: [96322],
  },
  ARMY_OF_THE_DAMNED_TALENT: {
    id: 276837,
    name: 'Army of the Damned',
    icon: 'artifactability_unholydeathknight_deathsembrace',
    maxRanks: 1,
    entryIds: [96287],
  },
  ARMY_OF_THE_DEAD_TALENT: {
    id: 42650,
    name: 'Army of the Dead',
    icon: 'spell_deathknight_armyofthedead',
    maxRanks: 1,
    entryIds: [96333],
    runesCost: 1,
  },
  ASPHYXIATE_TALENT: {
    id: 221562,
    name: 'Asphyxiate',
    icon: 'ability_deathknight_asphixiate',
    maxRanks: 1,
    entryIds: [96193],
  },
  ASSIMILATION_TALENT: {
    id: 374383,
    name: 'Assimilation',
    icon: 'spell_deathknight_antimagiczone',
    maxRanks: 1,
    entryIds: [96176],
  },
  AVALANCHE_TALENT: {
    id: 207142,
    name: 'Avalanche',
    icon: 'spell_frost_icestorm',
    maxRanks: 1,
    entryIds: [96235],
  },
  BITING_COLD_TALENT: {
    id: 377056,
    name: 'Biting Cold',
    icon: 'ability_deathknight_remorselesswinters2',
    maxRanks: 1,
    entryIds: [96164],
  },
  BLINDING_SLEET_TALENT: {
    id: 207167,
    name: 'Blinding Sleet',
    icon: 'spell_frost_chillingblast',
    maxRanks: 1,
    entryIds: [96172],
  },
  BLOODDRINKER_TALENT: {
    id: 206931,
    name: 'Blooddrinker',
    icon: 'ability_animusdraw',
    maxRanks: 1,
    entryIds: [96276],
    runesCost: 1,
  },
  BLOODSHOT_TALENT: {
    id: 391398,
    name: 'Bloodshot',
    icon: 'ability_warlock_baneofhavoc',
    maxRanks: 1,
    entryIds: [96256],
  },
  BLOODWORMS_TALENT: {
    id: 195679,
    name: 'Bloodworms',
    icon: 'spell_shadow_soulleech',
    maxRanks: 1,
    entryIds: [96309],
  },
  BLOOD_BOIL_TALENT: {
    id: 50842,
    name: 'Blood Boil',
    icon: 'spell_deathknight_bloodboil',
    maxRanks: 1,
    entryIds: [96305],
  },
  BLOOD_DRAW_TALENT: {
    id: 374598,
    name: 'Blood Draw',
    icon: 'inv_artifact_bloodoftheassassinated',
    maxRanks: 2,
    entryIds: [96208],
  },
  BLOOD_FEAST_TALENT: {
    id: 391386,
    name: 'Blood Feast',
    icon: 'spell_deathknight_vendetta',
    maxRanks: 1,
    entryIds: [96167],
  },
  BLOOD_SCENT_TALENT: {
    id: 374030,
    name: 'Blood Scent',
    icon: 'spell_chargepositive',
    maxRanks: 1,
    entryIds: [96195],
  },
  BLOOD_TAP_TALENT: {
    id: 221699,
    name: 'Blood Tap',
    icon: 'spell_deathknight_bloodtap',
    maxRanks: 1,
    entryIds: [96274],
  },
  BONEGRINDER_TALENT: {
    id: 377098,
    name: 'Bonegrinder',
    icon: 'ability_deathknight_bonegrinder',
    maxRanks: 2,
    entryIds: [96253],
  },
  BONESTORM_TALENT: {
    id: 194844,
    name: 'Bonestorm',
    icon: 'achievement_boss_lordmarrowgar',
    maxRanks: 1,
    entryIds: [96258],
    runicPowerCost: 10,
  },
  BREATH_OF_SINDRAGOSA_TALENT: {
    id: 152279,
    name: 'Breath of Sindragosa',
    icon: 'spell_deathknight_breathofsindragosa',
    maxRanks: 1,
    entryIds: [96222],
    runicPowerCost: 0,
  },
  BRITTLE_TALENT: {
    id: 374504,
    name: 'Brittle',
    icon: 'ability_bosskilrogg_deaththroes',
    maxRanks: 1,
    entryIds: [96190],
  },
  BURSTING_SORES_TALENT: {
    id: 207264,
    name: 'Bursting Sores',
    icon: 'ability_druid_infectedwound',
    maxRanks: 1,
    entryIds: [96299],
  },
  CHAINS_OF_ICE_TALENT: {
    id: 45524,
    name: 'Chains of Ice',
    icon: 'spell_frost_chainsofice',
    maxRanks: 1,
    entryIds: [96210],
    runesCost: 1,
  },
  CHILL_STREAK_TALENT: {
    id: 305392,
    name: 'Chill Streak',
    icon: 'spell_frost_piercing_chill',
    maxRanks: 1,
    entryIds: [96228],
    runesCost: 1,
  },
  CLAWING_SHADOWS_TALENT: {
    id: 207311,
    name: 'Clawing Shadows',
    icon: 'warlock_curse_shadow',
    maxRanks: 1,
    entryIds: [96320],
    runesCost: 1,
  },
  CLEAVING_STRIKES_TALENT: {
    id: 316916,
    name: 'Cleaving Strikes',
    icon: 'spell_shadow_deathanddecay',
    maxRanks: 1,
    entryIds: [96202],
  },
  CLENCHING_GRASP_TALENT: {
    id: 389679,
    name: 'Clenching Grasp',
    icon: 'ability_deathknight_icygrip',
    maxRanks: 1,
    entryIds: [96191],
  },
  COAGULOPATHY_TALENT: {
    id: 391477,
    name: 'Coagulopathy',
    icon: 'ability_skeer_bloodletting',
    maxRanks: 1,
    entryIds: [96166],
  },
  COIL_OF_DEVASTATION_TALENT: {
    id: 390270,
    name: 'Coil of Devastation',
    icon: 'ability_malkorok_blightofyshaarj_green',
    maxRanks: 1,
    entryIds: [96290],
  },
  COLDTHIRST_TALENT: {
    id: 378848,
    name: 'Coldthirst',
    icon: 'spell_deathknight_mindfreeze',
    maxRanks: 1,
    entryIds: [96173],
  },
  COLD_BLOODED_RAGE_TALENT: {
    id: 377083,
    name: 'Cold-Blooded Rage',
    icon: 'inv_helm_plate_raiddeathknightmythic_q_01',
    maxRanks: 2,
    entryIds: [96254],
  },
  COLD_HEART_TALENT: {
    id: 281208,
    name: 'Cold Heart',
    icon: 'spell_frost_frozencore',
    maxRanks: 1,
    entryIds: [96163],
  },
  COMMANDER_OF_THE_DEAD_TALENT: {
    id: 390259,
    name: 'Commander of the Dead',
    icon: 'spell_shadow_fumble',
    maxRanks: 1,
    entryIds: [96283],
  },
  CONSUMPTION_TALENT: {
    id: 274156,
    name: 'Consumption',
    icon: 'inv_axe_2h_artifactmaw_d_01',
    maxRanks: 1,
    entryIds: [96275],
  },
  CONTROL_UNDEAD_TALENT: {
    id: 111673,
    name: 'Control Undead',
    icon: 'inv_misc_bone_skull_01',
    maxRanks: 1,
    entryIds: [96188],
    runesCost: 1,
  },
  CRIMSON_SCOURGE_TALENT: {
    id: 81136,
    name: 'Crimson Scourge',
    icon: 'ability_warrior_bloodnova',
    maxRanks: 1,
    entryIds: [96306],
  },
  DANCING_RUNE_WEAPON_TALENT: {
    id: 49028,
    name: 'Dancing Rune Weapon',
    icon: 'inv_sword_07',
    maxRanks: 1,
    entryIds: [96269],
  },
  DARK_TRANSFORMATION_TALENT: {
    id: 63560,
    name: 'Dark Transformation',
    icon: 'achievement_boss_festergutrotface',
    maxRanks: 1,
    entryIds: [96324],
  },
  DEATHS_CARESS_TALENT: {
    id: 195292,
    name: "Death's Caress",
    icon: 'ability_deathknight_deathscaress',
    maxRanks: 1,
    entryIds: [96279],
    runesCost: 1,
  },
  DEATHS_ECHO_TALENT: {
    id: 356367,
    name: "Death's Echo",
    icon: 'inv_fabric_ebonweave',
    maxRanks: 1,
    entryIds: [96184],
  },
  DEATHS_REACH_TALENT: {
    id: 276079,
    name: "Death's Reach",
    icon: 'spell_deathknight_strangulate',
    maxRanks: 1,
    entryIds: [96186],
  },
  DEATH_PACT_TALENT: {
    id: 48743,
    name: 'Death Pact',
    icon: 'spell_shadow_deathpact',
    maxRanks: 1,
    entryIds: [96206],
  },
  DEATH_ROT_TALENT: {
    id: 377537,
    name: 'Death Rot',
    icon: 'ability_creature_cursed_03',
    maxRanks: 1,
    entryIds: [96292],
  },
  DEATH_STRIKE_TALENT: {
    id: 49998,
    name: 'Death Strike',
    icon: 'spell_deathknight_butcher2',
    maxRanks: 1,
    entryIds: [96200],
    runicPowerCost: 45,
  },
  DEFILE_TALENT: {
    id: 152280,
    name: 'Defile',
    icon: 'spell_deathknight_defile',
    maxRanks: 1,
    entryIds: [96315],
    runesCost: 1,
  },
  EBON_FEVER_TALENT: {
    id: 207269,
    name: 'Ebon Fever',
    icon: 'spell_shadow_creepingplague',
    maxRanks: 1,
    entryIds: [96298],
  },
  EMPOWER_RUNE_WEAPON_FROST_TALENT: {
    id: 47568,
    name: 'Empower Rune Weapon',
    icon: 'inv_sword_62',
    maxRanks: 1,
    entryIds: [96229],
  },
  EMPOWER_RUNE_WEAPON_SHARED_TALENT: {
    id: 47568,
    name: 'Empower Rune Weapon',
    icon: 'inv_sword_62',
    maxRanks: 1,
    entryIds: [96178],
  },
  ENDURING_CHILL_TALENT: {
    id: 377376,
    name: 'Enduring Chill',
    icon: 'spell_frost_piercing_chill',
    maxRanks: 1,
    entryIds: [96226],
  },
  ENDURING_STRENGTH_TALENT: {
    id: 377190,
    name: 'Enduring Strength',
    icon: 'spell_shadow_soulleech_2',
    maxRanks: 2,
    entryIds: [96230],
  },
  ENFEEBLE_TALENT: {
    id: 392566,
    name: 'Enfeeble',
    icon: 'ability_creature_poison_01',
    maxRanks: 1,
    entryIds: [96189],
  },
  EPIDEMIC_TALENT: {
    id: 207317,
    name: 'Epidemic',
    icon: 'spell_nature_nullifydisease',
    maxRanks: 1,
    entryIds: [96295],
    runicPowerCost: 30,
  },
  ETERNAL_AGONY_TALENT: {
    id: 390268,
    name: 'Eternal Agony',
    icon: 'spell_necro_deathsdoor',
    maxRanks: 1,
    entryIds: [96332],
  },
  EVERFROST_TALENT: {
    id: 376938,
    name: 'Everfrost',
    icon: 'ability_mage_deepfreeze',
    maxRanks: 1,
    entryIds: [96237],
  },
  EVERLASTING_BOND_TALENT: {
    id: 377668,
    name: 'Everlasting Bond',
    icon: 'inv_sword_07',
    maxRanks: 1,
    entryIds: [96261],
  },
  FEASTING_STRIKES_TALENT: {
    id: 390161,
    name: 'Feasting Strikes',
    icon: 'spell_nature_rune',
    maxRanks: 1,
    entryIds: [96330],
  },
  FESTERING_STRIKE_TALENT: {
    id: 85948,
    name: 'Festering Strike',
    icon: 'spell_deathknight_festering_strike',
    maxRanks: 1,
    entryIds: [96326],
    runesCost: 2,
  },
  FESTERMIGHT_TALENT: {
    id: 377590,
    name: 'Festermight',
    icon: 'ability_deathknight_festermight',
    maxRanks: 2,
    entryIds: [96286],
  },
  FOUL_BULWARK_TALENT: {
    id: 206974,
    name: 'Foul Bulwark',
    icon: 'inv_armor_shield_naxxramas_d_02',
    maxRanks: 1,
    entryIds: [96302],
  },
  FRIGID_EXECUTIONER_TALENT: {
    id: 377073,
    name: 'Frigid Executioner',
    icon: 'spell_shadow_focusedpower',
    maxRanks: 1,
    entryIds: [96251],
  },
  FROSTREAPER_TALENT: {
    id: 317214,
    name: 'Frostreaper',
    icon: 'spell_ice_rune',
    maxRanks: 1,
    entryIds: [96218],
  },
  FROSTSCYTHE_TALENT: {
    id: 207230,
    name: 'Frostscythe',
    icon: 'inv_misc_2h_farmscythe_a_01',
    maxRanks: 1,
    entryIds: [96225],
    runesCost: 1,
  },
  FROSTWHELPS_AID_TALENT: {
    id: 377226,
    name: "Frostwhelp's Aid",
    icon: 'inv_pet_dkwhelplingfrost',
    maxRanks: 2,
    entryIds: [96236],
  },
  FROSTWYRMS_FURY_TALENT: {
    id: 279302,
    name: "Frostwyrm's Fury",
    icon: 'achievement_boss_sindragosa',
    maxRanks: 1,
    entryIds: [96224],
  },
  FROST_STRIKE_TALENT: {
    id: 49143,
    name: 'Frost Strike',
    icon: 'spell_deathknight_empowerruneblade2',
    maxRanks: 1,
    entryIds: [96245],
    runicPowerCost: 25,
  },
  GATHERING_STORM_TALENT: {
    id: 194912,
    name: 'Gathering Storm',
    icon: 'spell_frost_ice_shards',
    maxRanks: 1,
    entryIds: [96239],
  },
  GHOULISH_FRENZY_TALENT: {
    id: 377587,
    name: 'Ghoulish Frenzy',
    icon: 'ability_warlock_baneofhavoc',
    maxRanks: 2,
    entryIds: [96288],
  },
  GLACIAL_ADVANCE_TALENT: {
    id: 194913,
    name: 'Glacial Advance',
    icon: 'ability_hunter_glacialtrap',
    maxRanks: 1,
    entryIds: [96221],
    runicPowerCost: 30,
  },
  GLOOM_WARD_TALENT: {
    id: 391571,
    name: 'Gloom Ward',
    icon: 'ability_rogue_envelopingshadows',
    maxRanks: 1,
    entryIds: [96180],
  },
  GOREFIENDS_GRASP_TALENT: {
    id: 108199,
    name: "Gorefiend's Grasp",
    icon: 'ability_deathknight_aoedeathgrip',
    maxRanks: 1,
    entryIds: [96267],
  },
  GRIP_OF_THE_DEAD_TALENT: {
    id: 273952,
    name: 'Grip of the Dead',
    icon: 'ability_creature_disease_05',
    maxRanks: 1,
    entryIds: [96185],
  },
  HARBINGER_OF_DOOM_TALENT: {
    id: 276023,
    name: 'Harbinger of Doom',
    icon: 'spell_shadow_painspike',
    maxRanks: 1,
    entryIds: [96310],
  },
  HEARTBREAKER_TALENT: {
    id: 221536,
    name: 'Heartbreaker',
    icon: 'spell_deathknight_deathstrike',
    maxRanks: 2,
    entryIds: [96266],
  },
  HEARTREND_TALENT: {
    id: 377655,
    name: 'Heartrend',
    icon: 'inv_weapon_shortblade_40',
    maxRanks: 1,
    entryIds: [96262],
  },
  HEART_STRIKE_TALENT: {
    id: 206930,
    name: 'Heart Strike',
    icon: 'inv_weapon_shortblade_40',
    maxRanks: 1,
    entryIds: [96304],
    runesCost: 1,
  },
  HEMOSTASIS_TALENT: {
    id: 273946,
    name: 'Hemostasis',
    icon: 'ability_deathwing_bloodcorruption_earth',
    maxRanks: 1,
    entryIds: [96268],
  },
  HORN_OF_WINTER_TALENT: {
    id: 57330,
    name: 'Horn of Winter',
    icon: 'inv_misc_horn_02',
    maxRanks: 1,
    entryIds: [96240],
  },
  HOWLING_BLAST_TALENT: {
    id: 49184,
    name: 'Howling Blast',
    icon: 'spell_frost_arcticwinds',
    maxRanks: 1,
    entryIds: [96244],
    runesCost: 1,
  },
  ICEBOUND_FORTITUDE_TALENT: {
    id: 48792,
    name: 'Icebound Fortitude',
    icon: 'spell_deathknight_iceboundfortitude',
    maxRanks: 1,
    entryIds: [96213],
  },
  ICEBREAKER_TALENT: {
    id: 392950,
    name: 'Icebreaker',
    icon: 'ability_mage_icewall',
    maxRanks: 2,
    entryIds: [96161],
  },
  ICECAP_TALENT: {
    id: 207126,
    name: 'Icecap',
    icon: 'inv_misc_herb_icecap',
    maxRanks: 1,
    entryIds: [96162],
  },
  ICY_TALONS_TALENT: {
    id: 194878,
    name: 'Icy Talons',
    icon: 'spell_deathknight_icytalons',
    maxRanks: 2,
    entryIds: [96179],
  },
  IMPROVED_BONE_SHIELD_TALENT: {
    id: 374715,
    name: 'Improved Bone Shield',
    icon: 'ability_deathknight_marrowrend',
    maxRanks: 1,
    entryIds: [96170],
  },
  IMPROVED_DEATH_COIL_TALENT: {
    id: 377580,
    name: 'Improved Death Coil',
    icon: 'spell_shadow_deathcoil',
    maxRanks: 2,
    entryIds: [96321],
  },
  IMPROVED_DEATH_STRIKE_TALENT: {
    id: 374277,
    name: 'Improved Death Strike',
    icon: 'spell_deathknight_butcher2',
    maxRanks: 1,
    entryIds: [96196],
  },
  IMPROVED_FESTERING_STRIKE_TALENT: {
    id: 316867,
    name: 'Improved Festering Strike',
    icon: 'spell_deathknight_festering_strike',
    maxRanks: 2,
    entryIds: [96329],
  },
  IMPROVED_FROST_STRIKE_TALENT: {
    id: 316803,
    name: 'Improved Frost Strike',
    icon: 'spell_deathknight_empowerruneblade2',
    maxRanks: 2,
    entryIds: [96233],
  },
  IMPROVED_HEART_STRIKE_TALENT: {
    id: 374717,
    name: 'Improved Heart Strike',
    icon: 'inv_weapon_shortblade_40',
    maxRanks: 2,
    entryIds: [96257],
  },
  IMPROVED_OBLITERATE_TALENT: {
    id: 317198,
    name: 'Improved Obliterate',
    icon: 'spell_deathknight_classicon',
    maxRanks: 1,
    entryIds: [96249],
  },
  IMPROVED_RIME_TALENT: {
    id: 316838,
    name: 'Improved Rime',
    icon: 'spell_frost_freezingbreath',
    maxRanks: 1,
    entryIds: [96241],
  },
  IMPROVED_VAMPIRIC_BLOOD_TALENT: {
    id: 317133,
    name: 'Improved Vampiric Blood',
    icon: 'spell_shadow_lifedrain',
    maxRanks: 2,
    entryIds: [96272],
  },
  INEXORABLE_ASSAULT_TALENT: {
    id: 253593,
    name: 'Inexorable Assault',
    icon: 'achievement_dungeon_icecrown_frostmourne',
    maxRanks: 1,
    entryIds: [96165],
  },
  INFECTED_CLAWS_TALENT: {
    id: 207272,
    name: 'Infected Claws',
    icon: 'spell_deathknight_thrash_ghoul',
    maxRanks: 1,
    entryIds: [96318],
  },
  INSATIABLE_BLADE_TALENT: {
    id: 377637,
    name: 'Insatiable Blade',
    icon: '70_inscription_vantus_rune_nightmare',
    maxRanks: 1,
    entryIds: [96260],
  },
  INSIDIOUS_CHILL_TALENT: {
    id: 391566,
    name: 'Insidious Chill',
    icon: 'ability_racial_wardoftheloafrost',
    maxRanks: 1,
    entryIds: [96217],
  },
  INVIGORATING_FREEZE_TALENT: {
    id: 377092,
    name: 'Invigorating Freeze',
    icon: 'spell_deathknight_frostfever',
    maxRanks: 2,
    entryIds: [96238],
  },
  IRON_HEART_TALENT: {
    id: 391395,
    name: 'Iron Heart',
    icon: 'inv_ragnaros_heart',
    maxRanks: 1,
    entryIds: [96307],
  },
  KILLING_MACHINE_TALENT: {
    id: 51128,
    name: 'Killing Machine',
    icon: 'inv_sword_122',
    maxRanks: 1,
    entryIds: [96247],
  },
  LEECHING_STRIKE_TALENT: {
    id: 377629,
    name: 'Leeching Strike',
    icon: 'ability_deathwing_bloodcorruption_death',
    maxRanks: 1,
    entryIds: [96301],
  },
  MAGUS_OF_THE_DEAD_TALENT: {
    id: 390196,
    name: 'Magus of the Dead',
    icon: 'ability_maldraxxus_mage',
    maxRanks: 1,
    entryIds: [96282],
  },
  MARCH_OF_DARKNESS_TALENT: {
    id: 391546,
    name: 'March of Darkness',
    icon: 'ability_argus_deathfog',
    maxRanks: 1,
    entryIds: [96198],
  },
  MARK_OF_BLOOD_TALENT: {
    id: 206940,
    name: 'Mark of Blood',
    icon: 'ability_hunter_rapidkilling',
    maxRanks: 1,
    entryIds: [96271],
  },
  MARROWREND_TALENT: {
    id: 195182,
    name: 'Marrowrend',
    icon: 'ability_deathknight_marrowrend',
    maxRanks: 1,
    entryIds: [96303],
    runesCost: 2,
  },
  MERCILESS_STRIKES_TALENT: {
    id: 373923,
    name: 'Merciless Strikes',
    icon: 'spell_chargepositive',
    maxRanks: 1,
    entryIds: [96214],
  },
  MIGHT_OF_THASSARIAN_TALENT: {
    id: 374111,
    name: 'Might of Thassarian',
    icon: 'spell_chargepositive',
    maxRanks: 1,
    entryIds: [96205],
  },
  MIGHT_OF_THE_FROZEN_WASTES_TALENT: {
    id: 81333,
    name: 'Might of the Frozen Wastes',
    icon: 'inv_sword_120',
    maxRanks: 1,
    entryIds: [96219],
  },
  MIND_FREEZE_TALENT: {
    id: 47528,
    name: 'Mind Freeze',
    icon: 'spell_deathknight_mindfreeze',
    maxRanks: 1,
    entryIds: [96211],
    runicPowerCost: 0,
  },
  MORBIDITY_TALENT: {
    id: 377592,
    name: 'Morbidity',
    icon: 'spell_necro_deathlyecho',
    maxRanks: 2,
    entryIds: [96334],
  },
  MURDEROUS_EFFICIENCY_TALENT: {
    id: 207061,
    name: 'Murderous Efficiency',
    icon: 'spell_frost_frostarmor',
    maxRanks: 1,
    entryIds: [96252],
  },
  OBLITERATE_TALENT: {
    id: 49020,
    name: 'Obliterate',
    icon: 'spell_deathknight_classicon',
    maxRanks: 1,
    entryIds: [96246],
    runesCost: 2,
  },
  OBLITERATION_TALENT: {
    id: 281238,
    name: 'Obliteration',
    icon: 'inv_axe_114',
    maxRanks: 1,
    entryIds: [96220],
  },
  OSSUARY_TALENT: {
    id: 219786,
    name: 'Ossuary',
    icon: 'ability_deathknight_brittlebones',
    maxRanks: 1,
    entryIds: [96277],
  },
  OUTBREAK_TALENT: {
    id: 77575,
    name: 'Outbreak',
    icon: 'spell_deathvortex',
    maxRanks: 1,
    entryIds: [96328],
    runesCost: 1,
  },
  PERMAFROST_TALENT: {
    id: 207200,
    name: 'Permafrost',
    icon: 'achievement_zone_frostfire',
    maxRanks: 1,
    entryIds: [96212],
  },
  PERSEVERANCE_OF_THE_EBON_BLADE_TALENT: {
    id: 374747,
    name: 'Perseverance of the Ebon Blade',
    icon: 'ability_deathknight_sanguinfortitude',
    maxRanks: 2,
    entryIds: [96255],
  },
  PESTILENCE_TALENT: {
    id: 277234,
    name: 'Pestilence',
    icon: 'spell_deathknight_necroticplague',
    maxRanks: 1,
    entryIds: [96291],
  },
  PESTILENT_PUSTULES_TALENT: {
    id: 194917,
    name: 'Pestilent Pustules',
    icon: 'ability_creature_disease_03',
    maxRanks: 1,
    entryIds: [96294],
  },
  PIERCING_CHILL_TALENT: {
    id: 377351,
    name: 'Piercing Chill',
    icon: 'spell_frost_piercing_chill',
    maxRanks: 1,
    entryIds: [96227],
  },
  PILLAR_OF_FROST_TALENT: {
    id: 51271,
    name: 'Pillar of Frost',
    icon: 'ability_deathknight_pillaroffrost',
    maxRanks: 1,
    entryIds: [96234],
  },
  PLAGUEBRINGER_TALENT: {
    id: 390175,
    name: 'Plaguebringer',
    icon: 'spell_deathknight_plaguestrike',
    maxRanks: 1,
    entryIds: [96319],
  },
  PROLIFERATING_CHILL_TALENT: {
    id: 373930,
    name: 'Proliferating Chill',
    icon: 'spell_frost_chainsofice',
    maxRanks: 1,
    entryIds: [96215],
  },
  PURGATORY_TALENT: {
    id: 114556,
    name: 'Purgatory',
    icon: 'inv_misc_shadowegg',
    maxRanks: 1,
    entryIds: [96264],
  },
  RAGE_OF_THE_FROZEN_CHAMPION_TALENT: {
    id: 377076,
    name: 'Rage of the Frozen Champion',
    icon: 'spell_mage_frostbomb',
    maxRanks: 1,
    entryIds: [96250],
  },
  RAISE_DEAD_SHARED_TALENT: {
    id: 46585,
    name: 'Raise Dead',
    icon: 'inv_pet_ghoul',
    maxRanks: 1,
    entryIds: [96201],
  },
  RAISE_DEAD_UNHOLY_TALENT: {
    id: 46584,
    name: 'Raise Dead',
    icon: 'inv_pet_ghoul',
    maxRanks: 1,
    entryIds: [96325],
  },
  RAPID_DECOMPOSITION_TALENT: {
    id: 194662,
    name: 'Rapid Decomposition',
    icon: 'ability_deathknight_deathsiphon2',
    maxRanks: 1,
    entryIds: [96273],
  },
  REAPING_TALENT: {
    id: 377514,
    name: 'Reaping',
    icon: 'ability_deathwing_bloodcorruption_death',
    maxRanks: 1,
    entryIds: [96312],
  },
  RED_THIRST_TALENT: {
    id: 205723,
    name: 'Red Thirst',
    icon: 'spell_deathknight_bloodpresence',
    maxRanks: 2,
    entryIds: [96263],
  },
  REINFORCED_BONES_TALENT: {
    id: 374737,
    name: 'Reinforced Bones',
    icon: 'ability_deathknight_boneshield',
    maxRanks: 1,
    entryIds: [96300],
  },
  RELISH_IN_BLOOD_TALENT: {
    id: 317610,
    name: 'Relish in Blood',
    icon: 'ability_deathknight_roilingblood',
    maxRanks: 1,
    entryIds: [96280],
  },
  REMORSELESS_WINTER_TALENT: {
    id: 196770,
    name: 'Remorseless Winter',
    icon: 'ability_deathknight_remorselesswinters2',
    maxRanks: 1,
    entryIds: [96242],
    runesCost: 1,
  },
  REPLENISHING_WOUNDS_TALENT: {
    id: 377585,
    name: 'Replenishing Wounds',
    icon: 'spell_yorsahj_bloodboil_purpleoil',
    maxRanks: 1,
    entryIds: [96297],
  },
  RIME_TALENT: {
    id: 59057,
    name: 'Rime',
    icon: 'spell_frost_freezingbreath',
    maxRanks: 1,
    entryIds: [96243],
  },
  ROTTEN_TOUCH_TALENT: {
    id: 390275,
    name: 'Rotten Touch',
    icon: 'ability_deathwing_grasping_tendrilsgreen',
    maxRanks: 1,
    entryIds: [96313],
  },
  RUNE_MASTERY_TALENT: {
    id: 374574,
    name: 'Rune Mastery',
    icon: 'ability_deathknight_hungeringruneblade',
    maxRanks: 2,
    entryIds: [96209],
  },
  RUNE_TAP_TALENT: {
    id: 194679,
    name: 'Rune Tap',
    icon: 'spell_deathknight_runetap',
    maxRanks: 1,
    entryIds: [96278],
    runesCost: 1,
  },
  RUNIC_ATTENUATION_TALENT: {
    id: 207104,
    name: 'Runic Attenuation',
    icon: 'boss_odunrunes_blue',
    maxRanks: 1,
    entryIds: [96216],
  },
  RUNIC_COMMAND_TALENT: {
    id: 376251,
    name: 'Runic Command',
    icon: 'ability_deathknight_remorselesswinters',
    maxRanks: 2,
    entryIds: [96232],
  },
  RUNIC_MASTERY_TALENT: {
    id: 390166,
    name: 'Runic Mastery',
    icon: 'ability_deathknight_remorselesswinters',
    maxRanks: 2,
    entryIds: [96323],
  },
  RUPTURED_VISCERA_TALENT: {
    id: 390236,
    name: 'Ruptured Viscera',
    icon: 'artifactability_unholydeathknight_flagellation',
    maxRanks: 1,
    entryIds: [96281],
  },
  SACRIFICIAL_PACT_TALENT: {
    id: 327574,
    name: 'Sacrificial Pact',
    icon: 'spell_shadow_corpseexplode',
    maxRanks: 1,
    entryIds: [96203],
    runicPowerCost: 20,
  },
  SANGUINE_GROUND_TALENT: {
    id: 391458,
    name: 'Sanguine Ground',
    icon: 'inv_artifact_corruptedbloodofzakajz',
    maxRanks: 1,
    entryIds: [96169],
  },
  SCOURGE_STRIKE_TALENT: {
    id: 55090,
    name: 'Scourge Strike',
    icon: 'spell_deathknight_scourgestrike',
    maxRanks: 1,
    entryIds: [96327],
    runesCost: 1,
  },
  SHATTERING_BLADE_TALENT: {
    id: 207057,
    name: 'Shattering Blade',
    icon: 'inv_7af_deathknight_frostmournefragment',
    maxRanks: 1,
    entryIds: [96231],
  },
  SHATTERING_BONE_TALENT: {
    id: 377640,
    name: 'Shattering Bone',
    icon: 'ability_deathknight_shatteringbone',
    maxRanks: 2,
    entryIds: [96259],
  },
  SOUL_REAPER_TALENT: {
    id: 343294,
    name: 'Soul Reaper',
    icon: 'ability_deathknight_soulreaper',
    maxRanks: 1,
    entryIds: [96181],
    runesCost: 1,
  },
  SUDDEN_DOOM_TALENT: {
    id: 49530,
    name: 'Sudden Doom',
    icon: 'spell_shadow_painspike',
    maxRanks: 1,
    entryIds: [96314],
  },
  SUMMON_GARGOYLE_TALENT: {
    id: 49206,
    name: 'Summon Gargoyle',
    icon: 'ability_deathknight_summongargoyle',
    maxRanks: 1,
    entryIds: [96311],
  },
  SUPERSTRAIN_TALENT: {
    id: 390283,
    name: 'Superstrain',
    icon: 'spell_deathknight_explode_ghoul',
    maxRanks: 1,
    entryIds: [96289],
  },
  SUPPRESSION_TALENT: {
    id: 374049,
    name: 'Suppression',
    icon: 'spell_chargepositive',
    maxRanks: 1,
    entryIds: [96204],
  },
  TIGHTENING_GRASP_TALENT: {
    id: 206970,
    name: 'Tightening Grasp',
    icon: 'ability_deathknight_aoedeathgrip',
    maxRanks: 1,
    entryIds: [96265],
  },
  TOMBSTONE_TALENT: {
    id: 219809,
    name: 'Tombstone',
    icon: 'ability_fiegndead',
    maxRanks: 1,
    entryIds: [96270],
  },
  UMBILICUS_ETERNUS_TALENT: {
    id: 391517,
    name: 'Umbilicus Eternus',
    icon: 'artifactability_blooddeathknight_umbilicuseternus',
    maxRanks: 1,
    entryIds: [96168],
  },
  UNHOLY_ASSAULT_TALENT: {
    id: 207289,
    name: 'Unholy Assault',
    icon: 'spell_shadow_unholyfrenzy',
    maxRanks: 1,
    entryIds: [96285],
  },
  UNHOLY_AURA_TALENT: {
    id: 377440,
    name: 'Unholy Aura',
    icon: 'ability_deathknight_decomposingaura',
    maxRanks: 2,
    entryIds: [96284],
  },
  UNHOLY_BLIGHT_TALENT: {
    id: 115989,
    name: 'Unholy Blight',
    icon: 'spell_shadow_contagion',
    maxRanks: 1,
    entryIds: [96296],
    runesCost: 1,
  },
  UNHOLY_BOND_TALENT: {
    id: 374261,
    name: 'Unholy Bond',
    icon: 'inv_sword_1h_felfireraid_d_01',
    maxRanks: 2,
    entryIds: [96183],
  },
  UNHOLY_COMMAND_TALENT: {
    id: 316941,
    name: 'Unholy Command',
    icon: 'ability_rogue_deadlymomentum',
    maxRanks: 2,
    entryIds: [96331],
  },
  UNHOLY_ENDURANCE_TALENT: {
    id: 389682,
    name: 'Unholy Endurance',
    icon: 'spell_deathknight_subversion',
    maxRanks: 1,
    entryIds: [96192],
  },
  UNHOLY_GROUND_TALENT: {
    id: 374265,
    name: 'Unholy Ground',
    icon: 'ability_deathknight_desecratedground',
    maxRanks: 1,
    entryIds: [96187],
  },
  UNHOLY_PACT_TALENT: {
    id: 319230,
    name: 'Unholy Pact',
    icon: 'spell_shadow_deathsembrace',
    maxRanks: 1,
    entryIds: [96316],
  },
  UNLEASHED_FRENZY_TALENT: {
    id: 376905,
    name: 'Unleashed Frenzy',
    icon: 'spell_deathknight_icetouch',
    maxRanks: 1,
    entryIds: [96248],
  },
  VAMPIRIC_BLOOD_TALENT: {
    id: 55233,
    name: 'Vampiric Blood',
    icon: 'spell_shadow_lifedrain',
    maxRanks: 1,
    entryIds: [96308],
  },
  VETERAN_OF_THE_THIRD_WAR_TALENT: {
    id: 48263,
    name: 'Veteran of the Third War',
    icon: 'spell_misc_warsongfocus',
    maxRanks: 2,
    entryIds: [96197],
  },
  VILE_CONTAGION_TALENT: {
    id: 390279,
    name: 'Vile Contagion',
    icon: 'spell_shadow_plaguecloud',
    maxRanks: 1,
    entryIds: [96293],
    runicPowerCost: 30,
  },
  VORACIOUS_TALENT: {
    id: 273953,
    name: 'Voracious',
    icon: 'ability_ironmaidens_whirlofblood',
    maxRanks: 1,
    entryIds: [96171],
  },
  WILL_OF_THE_NECROPOLIS_TALENT: {
    id: 206967,
    name: 'Will of the Necropolis',
    icon: 'achievement_boss_kelthuzad_01',
    maxRanks: 2,
    entryIds: [96182],
  },
  WRAITH_WALK_TALENT: {
    id: 212552,
    name: 'Wraith Walk',
    icon: 'inv_helm_plate_raiddeathknight_p_01',
    maxRanks: 1,
    entryIds: [96207],
  },
});

export default talents;
export { talents as TALENTS_DEATH_KNIGHT };
