// Generated file, changes will eventually be overwritten!
import { createTalentList } from './types';

const talents = createTalentList({
  //Shared
  CHAINS_OF_ICE_TALENT: {
    id: 45524,
    name: 'Chains of Ice',
    icon: 'spell_frost_chainsofice',
    maxRanks: 1,
    runesCost: 1,
  },
  DEATH_STRIKE_TALENT: {
    id: 49998,
    name: 'Death Strike',
    icon: 'spell_deathknight_butcher2',
    maxRanks: 1,
    runicPowerCost: 45,
  },
  RAISE_DEAD_TALENT: { id: 46585, name: 'Raise Dead', icon: 'inv_pet_ghoul', maxRanks: 1 },
  MIND_FREEZE_TALENT: {
    id: 47528,
    name: 'Mind Freeze',
    icon: 'spell_deathknight_mindfreeze',
    maxRanks: 1,
    runicPowerCost: 0,
  },
  ANTI_MAGIC_SHELL_TALENT: {
    id: 48707,
    name: 'Anti-Magic Shell',
    icon: 'spell_shadow_antimagicshell',
    maxRanks: 1,
  },
  CLEAVING_STRIKES_TALENT: {
    id: 316916,
    name: 'Cleaving Strikes',
    icon: 'spell_shadow_deathanddecay',
    maxRanks: 1,
  },
  BLINDING_SLEET_TALENT: {
    id: 207167,
    name: 'Blinding Sleet',
    icon: 'spell_frost_chillingblast',
    maxRanks: 1,
  },
  ANTICIPATION_TALENT: {
    id: 378848,
    name: 'Anticipation',
    icon: 'spell_deathknight_mindfreeze',
    maxRanks: 1,
  },
  PERMAFROST_TALENT: {
    id: 207200,
    name: 'Permafrost',
    icon: 'achievement_zone_frostfire',
    maxRanks: 1,
  },
  DEATH_PACT_TALENT: { id: 48743, name: 'Death Pact', icon: 'spell_shadow_deathpact', maxRanks: 1 },
  ANTI_MAGIC_BARRIER_TALENT: {
    id: 205727,
    name: 'Anti-Magic Barrier',
    icon: 'spell_shadow_antimagicshell',
    maxRanks: 1,
  },
  DEATHS_ADVANCE_TALENT: {
    id: 48265,
    name: "Death's Advance",
    icon: 'spell_shadow_demonicempathy',
    maxRanks: 1,
  },
  SACRIFICIAL_PACT_TALENT: {
    id: 327574,
    name: 'Sacrificial Pact',
    icon: 'spell_shadow_corpseexplode',
    maxRanks: 1,
    runicPowerCost: 20,
  },
  CONTROL_UNDEAD_TALENT: {
    id: 111673,
    name: 'Control Undead',
    icon: 'inv_misc_bone_skull_01',
    maxRanks: 1,
    runesCost: 1,
  },
  ICEBOUND_FORTITUDE_TALENT: {
    id: 48792,
    name: 'Icebound Fortitude',
    icon: 'spell_deathknight_iceboundfortitude',
    maxRanks: 1,
  },
  BLOOD_SCENT_TALENT: {
    id: 374030,
    name: 'Blood Scent',
    icon: 'spell_chargepositive',
    maxRanks: 1,
  },
  VETERAN_OF_THE_THIRD_WAR_TALENT: {
    id: 48263,
    name: 'Veteran of the Third War',
    icon: 'spell_misc_warsongfocus',
    maxRanks: 2,
  },
  SUPPRESSION_TALENT: {
    id: 374049,
    name: 'Suppression',
    icon: 'spell_chargepositive',
    maxRanks: 1,
  },
  BRITTLE_TALENT: {
    id: 374504,
    name: 'Brittle',
    icon: 'spell_deathknight_explode_ghoul',
    maxRanks: 1,
  },
  MERCILESS_STRIKES_TALENT: {
    id: 373923,
    name: 'Merciless Strikes',
    icon: 'spell_chargepositive',
    maxRanks: 1,
  },
  ANTI_MAGIC_ZONE_TALENT: {
    id: 51052,
    name: 'Anti-Magic Zone',
    icon: 'spell_deathknight_antimagiczone',
    maxRanks: 1,
  },
  MIGHT_OF_THASSARIAN_TALENT: {
    id: 374111,
    name: 'Might of Thassarian',
    icon: 'spell_chargepositive',
    maxRanks: 1,
  },
  PROLIFERATING_CHILL_TALENT: {
    id: 373930,
    name: 'Proliferating Chill',
    icon: 'spell_frost_chainsofice',
    maxRanks: 1,
  },
  ACCLIMATION_TALENT: {
    id: 373926,
    name: 'Acclimation',
    icon: 'spell_deathknight_iceboundfortitude',
    maxRanks: 1,
  },
  ASPHYXIATE_TALENT: {
    id: 221562,
    name: 'Asphyxiate',
    icon: 'ability_deathknight_asphixiate',
    maxRanks: 1,
  },
  WRAITH_WALK_TALENT: {
    id: 212552,
    name: 'Wraith Walk',
    icon: 'inv_helm_plate_raiddeathknight_p_01',
    maxRanks: 1,
  },
  GRIP_OF_THE_DEAD_TALENT: {
    id: 273952,
    name: 'Grip of the Dead',
    icon: 'ability_creature_disease_05',
    maxRanks: 1,
  },
  DEATHS_REACH_TALENT: {
    id: 276079,
    name: "Death's Reach",
    icon: 'spell_deathknight_strangulate',
    maxRanks: 1,
  },
  LICHBORNE_TALENT: { id: 49039, name: 'Lichborne', icon: 'spell_shadow_raisedead', maxRanks: 1 },
  RUNIC_CORRUPTION_TALENT: {
    id: 51462,
    name: 'Runic Corruption',
    icon: 'spell_shadow_rune',
    maxRanks: 1,
  },
  RUNIC_EMPOWERMENT_TALENT: {
    id: 81229,
    name: 'Runic Empowerment',
    icon: 'inv_misc_rune_10',
    maxRanks: 1,
  },
  ASSIMILATION_TALENT: {
    id: 374383,
    name: 'Assimilation',
    icon: 'spell_deathknight_antimagiczone',
    maxRanks: 1,
  },
  UNHOLY_GROUND_TALENT: {
    id: 374265,
    name: 'Unholy Ground',
    icon: 'ability_deathknight_desecratedground',
    maxRanks: 1,
  },
  RUNIC_ATTENUATION_TALENT: {
    id: 207104,
    name: 'Runic Attenuation',
    icon: 'boss_odunrunes_blue',
    maxRanks: 1,
  },
  HORN_OF_WINTER_TALENT: {
    id: 57330,
    name: 'Horn of Winter',
    icon: 'inv_misc_horn_02',
    maxRanks: 1,
  },
  WILL_OF_THE_NECROPOLIS_TALENT: {
    id: 206967,
    name: 'Will of the Necropolis',
    icon: 'achievement_boss_kelthuzad_01',
    maxRanks: 1,
  },
  DEATHS_ECHO_TALENT: {
    id: 356367,
    name: "Death's Echo",
    icon: 'inv_fabric_ebonweave',
    maxRanks: 1,
  },
  ICY_TALONS_TALENT: {
    id: 194878,
    name: 'Icy Talons',
    icon: 'spell_deathknight_icytalons',
    maxRanks: 3,
  },
  IMPROVED_DEATH_STRIKE_TALENT: {
    id: 374277,
    name: 'Improved Death Strike',
    icon: 'spell_deathknight_butcher2',
    maxRanks: 3,
  },
  UNHOLY_BOND_TALENT: {
    id: 374261,
    name: 'Unholy Bond',
    icon: 'inv_sword_1h_felfireraid_d_01',
    maxRanks: 3,
  },
  EMPOWER_RUNE_WEAPON_TALENT: {
    id: 47568,
    name: 'Empower Rune Weapon',
    icon: 'inv_sword_62',
    maxRanks: 1,
  },
  RUNE_MASTERY_TALENT: {
    id: 374574,
    name: 'Rune Mastery',
    icon: 'ability_deathknight_hungeringruneblade',
    maxRanks: 1,
  },
  ABOMINATION_LIMB_TALENT: {
    id: 383269,
    name: 'Abomination Limb',
    icon: 'ability_maldraxxus_deathknight',
    maxRanks: 1,
  },
  BLOOD_DRAW_TALENT: {
    id: 374598,
    name: 'Blood Draw',
    icon: 'inv_artifact_bloodoftheassassinated',
    maxRanks: 1,
  },
  SOUL_REAPER_TALENT: {
    id: 343294,
    name: 'Soul Reaper',
    icon: 'ability_deathknight_soulreaper',
    maxRanks: 1,
    runesCost: 1,
  },

  //Blood
  HEART_STRIKE_BLOOD_TALENT: {
    id: 206930,
    name: 'Heart Strike',
    icon: 'inv_weapon_shortblade_40',
    maxRanks: 1,
    runesCost: 1,
  },
  MARROWREND_BLOOD_TALENT: {
    id: 195182,
    name: 'Marrowrend',
    icon: 'ability_deathknight_marrowrend',
    maxRanks: 1,
    runesCost: 2,
  },
  BLOOD_BOIL_BLOOD_TALENT: {
    id: 316634,
    name: 'Blood Boil',
    icon: 'spell_deathknight_bloodboil',
    maxRanks: 1,
  },
  FOUL_BULWARK_BLOOD_TALENT: {
    id: 206974,
    name: 'Foul Bulwark',
    icon: 'inv_armor_shield_naxxramas_d_02',
    maxRanks: 1,
  },
  CRIMSON_SCOURGE_BLOOD_TALENT: {
    id: 81136,
    name: 'Crimson Scourge',
    icon: 'ability_warrior_bloodnova',
    maxRanks: 1,
  },
  IMPROVED_BONESHIELD_BLOOD_TALENT: {
    id: 374715,
    name: 'Improved Boneshield',
    icon: 'ability_deathknight_marrowrend',
    maxRanks: 2,
  },
  IMPROVED_HEART_STRIKE_BLOOD_TALENT: {
    id: 374717,
    name: 'Improved Heart Strike',
    icon: 'inv_weapon_shortblade_40',
    maxRanks: 3,
  },
  BLOOD_FORTIFICATION_BLOOD_TALENT: {
    id: 374721,
    name: 'Blood Fortification',
    icon: 'inv_tikiman2_bloodtroll',
    maxRanks: 3,
  },
  RUNE_TAP_BLOOD_TALENT: {
    id: 194679,
    name: 'Rune Tap',
    icon: 'spell_deathknight_runetap',
    maxRanks: 1,
    runesCost: 1,
  },
  BLOOD_TAP_BLOOD_TALENT: {
    id: 221699,
    name: 'Blood Tap',
    icon: 'spell_deathknight_bloodtap',
    maxRanks: 1,
  },
  REINFORCED_BONES_BLOOD_TALENT: {
    id: 374737,
    name: 'Reinforced Bones',
    icon: 'ability_deathknight_boneshield',
    maxRanks: 1,
  },
  LEECHING_STRIKE_BLOOD_TALENT: {
    id: 377629,
    name: 'Leeching Strike',
    icon: 'inv_weapon_shortblade_40',
    maxRanks: 1,
  },
  VAMPIRIC_BLOOD_BLOOD_TALENT: {
    id: 55233,
    name: 'Vampiric Blood',
    icon: 'spell_shadow_lifedrain',
    maxRanks: 1,
  },
  HASTY_BARGAIN_BLOOD_TALENT: {
    id: 374747,
    name: 'Hasty Bargain',
    icon: 'ability_warrior_bloodnova',
    maxRanks: 2,
  },
  DEATHS_CARESS_BLOOD_TALENT: {
    id: 195292,
    name: "Death's Caress",
    icon: 'ability_deathknight_deathscaress',
    maxRanks: 1,
    runesCost: 1,
  },
  CONSUMPTION_BLOOD_TALENT: {
    id: 274156,
    name: 'Consumption',
    icon: 'inv_axe_2h_artifactmaw_d_01',
    maxRanks: 1,
  },
  BLOODDRINKER_BLOOD_TALENT: {
    id: 206931,
    name: 'Blooddrinker',
    icon: 'ability_animusdraw',
    maxRanks: 1,
    runesCost: 1,
  },
  TOMBSTONE_BLOOD_TALENT: { id: 219809, name: 'Tombstone', icon: 'ability_fiegndead', maxRanks: 1 },
  MARK_OF_BLOOD_BLOOD_TALENT: {
    id: 206940,
    name: 'Mark of Blood',
    icon: 'ability_hunter_rapidkilling',
    maxRanks: 1,
  },
  BLOODWORMS_BLOOD_TALENT: {
    id: 195679,
    name: 'Bloodworms',
    icon: 'spell_shadow_soulleech',
    maxRanks: 1,
  },
  VORACIOUS_BLOOD_TALENT: {
    id: 273953,
    name: 'Voracious',
    icon: 'ability_ironmaidens_whirlofblood',
    maxRanks: 1,
  },
  RELISH_IN_BLOOD_BLOOD_TALENT: {
    id: 317610,
    name: 'Relish in Blood',
    icon: 'ability_deathknight_roilingblood',
    maxRanks: 1,
  },
  OSSUARY_BLOOD_TALENT: {
    id: 219786,
    name: 'Ossuary',
    icon: 'ability_deathknight_brittlebones',
    maxRanks: 1,
  },
  IMPROVED_VAMPIRIC_BLOOD_BLOOD_TALENT: {
    id: 317133,
    name: 'Improved Vampiric Blood',
    icon: 'spell_shadow_lifedrain',
    maxRanks: 2,
  },
  HEMOSTASIS_BLOOD_TALENT: {
    id: 273946,
    name: 'Hemostasis',
    icon: 'ability_deathwing_bloodcorruption_earth',
    maxRanks: 2,
  },
  HEARTBREAKER_BLOOD_TALENT: {
    id: 221536,
    name: 'Heartbreaker',
    icon: 'spell_deathknight_deathstrike',
    maxRanks: 2,
  },
  RAPID_DECOMPOSITION_BLOOD_TALENT: {
    id: 194662,
    name: 'Rapid Decomposition',
    icon: 'ability_deathknight_deathsiphon2',
    maxRanks: 1,
  },
  DANCING_RUNE_WEAPON_BLOOD_TALENT: {
    id: 49028,
    name: 'Dancing Rune Weapon',
    icon: 'inv_sword_07',
    maxRanks: 1,
  },
  GOREFIENDS_GRASP_BLOOD_TALENT: {
    id: 108199,
    name: "Gorefiend's Grasp",
    icon: 'ability_deathknight_aoedeathgrip',
    maxRanks: 1,
  },
  SHATTERING_BONE_BLOOD_TALENT: {
    id: 377640,
    name: 'Shattering Bone',
    icon: 'ability_deathknight_boneshield',
    maxRanks: 2,
  },
  HEARTREND_BLOOD_TALENT: {
    id: 377655,
    name: 'Heartrend',
    icon: 'inv_weapon_shortblade_40',
    maxRanks: 2,
  },
  INSATIABLE_BLADE_BLOOD_TALENT: {
    id: 377637,
    name: 'Insatiable Blade',
    icon: '70_inscription_vantus_rune_nightmare',
    maxRanks: 1,
  },
  TIGHTENING_GRASP_BLOOD_TALENT: {
    id: 206970,
    name: 'Tightening Grasp',
    icon: 'ability_deathknight_aoedeathgrip',
    maxRanks: 2,
  },
  RED_THIRST_BLOOD_TALENT: {
    id: 205723,
    name: 'Red Thirst',
    icon: 'spell_deathknight_bloodpresence',
    maxRanks: 2,
  },
  BONESTORM_BLOOD_TALENT: {
    id: 194844,
    name: 'Bonestorm',
    icon: 'achievement_boss_lordmarrowgar',
    maxRanks: 1,
    runicPowerCost: 10,
  },
  EVERLASTING_BOND_BLOOD_TALENT: {
    id: 377668,
    name: 'Everlasting Bond',
    icon: 'inv_sword_07',
    maxRanks: 1,
  },
  PURGATORY_BLOOD_TALENT: {
    id: 114556,
    name: 'Purgatory',
    icon: 'inv_misc_shadowegg',
    maxRanks: 1,
  },

  //Unholy
  FESTERING_STRIKE_UNHOLY_TALENT: {
    id: 316867,
    name: 'Festering Strike',
    icon: 'spell_deathknight_festering_strike',
    maxRanks: 3,
  },
  SCOURGE_STRIKE_UNHOLY_TALENT: {
    id: 317234,
    name: 'Scourge Strike',
    icon: 'spell_deathknight_scourgestrike',
    maxRanks: 2,
  },
  RAISE_DEAD_UNHOLY_TALENT: { id: 46584, name: 'Raise Dead', icon: 'inv_pet_ghoul', maxRanks: 1 },
  SUDDEN_DOOM_UNHOLY_TALENT: {
    id: 49530,
    name: 'Sudden Doom',
    icon: 'spell_shadow_painspike',
    maxRanks: 1,
  },
  OUTBREAK_UNHOLY_TALENT: {
    id: 77575,
    name: 'Outbreak',
    icon: 'spell_deathvortex',
    maxRanks: 1,
    runesCost: 1,
  },
  REPLENISHING_WOUNDS_UNHOLY_TALENT: {
    id: 377585,
    name: 'Replenishing Wounds',
    icon: 'spell_yorsahj_bloodboil_purpleoil',
    maxRanks: 1,
  },
  EPIDEMIC_UNHOLY_TALENT: {
    id: 207317,
    name: 'Epidemic',
    icon: 'spell_nature_nullifydisease',
    maxRanks: 1,
    runicPowerCost: 30,
  },
  HARBINGER_OF_DOOM_UNHOLY_TALENT: {
    id: 276023,
    name: 'Harbinger of Doom',
    icon: 'spell_shadow_painspike',
    maxRanks: 1,
  },
  DARK_TRANSFORMATION_UNHOLY_TALENT: {
    id: 63560,
    name: 'Dark Transformation',
    icon: 'achievement_boss_festergutrotface',
    maxRanks: 1,
  },
  DEADLY_COIL_UNHOLY_TALENT: {
    id: 377577,
    name: 'Deadly Coil',
    icon: 'spell_shadow_deathcoil',
    maxRanks: 2,
  },
  CLAWING_SHADOWS_UNHOLY_TALENT: {
    id: 207311,
    name: 'Clawing Shadows',
    icon: 'warlock_curse_shadow',
    maxRanks: 1,
    runesCost: 1,
  },
  PESTILENCE_UNHOLY_TALENT: {
    id: 277234,
    name: 'Pestilence',
    icon: 'spell_deathknight_necroticplague',
    maxRanks: 1,
  },
  DEFILE_UNHOLY_TALENT: {
    id: 152280,
    name: 'Defile',
    icon: 'spell_deathknight_defile',
    maxRanks: 1,
    runesCost: 1,
  },
  UNHOLY_PACT_UNHOLY_TALENT: {
    id: 319230,
    name: 'Unholy Pact',
    icon: 'spell_shadow_deathsembrace',
    maxRanks: 1,
  },
  EBON_FEVER_UNHOLY_TALENT: {
    id: 207269,
    name: 'Ebon Fever',
    icon: 'spell_shadow_creepingplague',
    maxRanks: 1,
  },
  BURSTING_SORES_UNHOLY_TALENT: {
    id: 207264,
    name: 'Bursting Sores',
    icon: 'ability_druid_infectedwound',
    maxRanks: 1,
  },
  INFECTED_CLAWS_UNHOLY_TALENT: {
    id: 207272,
    name: 'Infected Claws',
    icon: 'spell_deathknight_thrash_ghoul',
    maxRanks: 1,
  },
  ALL_WILL_SERVE_UNHOLY_TALENT: {
    id: 194916,
    name: 'All Will Serve',
    icon: 'ability_fiegndead',
    maxRanks: 1,
  },
  PESTILENT_PUSTULES_UNHOLY_TALENT: {
    id: 194917,
    name: 'Pestilent Pustules',
    icon: 'spell_yorsahj_bloodboil_purpleoil',
    maxRanks: 1,
  },
  UNHOLY_COMMAND_UNHOLY_TALENT: {
    id: 316941,
    name: 'Unholy Command',
    icon: 'spell_shadow_deathcoil',
    maxRanks: 2,
  },
  ARMY_OF_THE_DEAD_UNHOLY_TALENT: {
    id: 42650,
    name: 'Army of the Dead',
    icon: 'spell_deathknight_armyofthedead',
    maxRanks: 1,
    runesCost: 1,
  },
  IMPROVED_DEATH_COIL_UNHOLY_TALENT: {
    id: 377580,
    name: 'Improved Death Coil',
    icon: 'spell_shadow_deathcoil',
    maxRanks: 2,
  },
  REAPING_UNHOLY_TALENT: {
    id: 377514,
    name: 'Reaping',
    icon: 'ability_deathwing_bloodcorruption_death',
    maxRanks: 1,
  },
  DEATH_ROT_UNHOLY_TALENT: {
    id: 377537,
    name: 'Death Rot',
    icon: 'ability_creature_cursed_03',
    maxRanks: 1,
  },
  APOCALYPSE_UNHOLY_TALENT: {
    id: 275699,
    name: 'Apocalypse',
    icon: 'artifactability_unholydeathknight_deathsembrace',
    maxRanks: 1,
  },
  UNHOLY_BLIGHT_UNHOLY_TALENT: {
    id: 115989,
    name: 'Unholy Blight',
    icon: 'spell_shadow_contagion',
    maxRanks: 1,
    runesCost: 1,
  },
  FESTERMIGHT_UNHOLY_TALENT: {
    id: 377590,
    name: 'Festermight',
    icon: 'spell_yorsahj_bloodboil_purpleoil',
    maxRanks: 2,
  },
  GHOULISH_FRENZY_UNHOLY_TALENT: {
    id: 377587,
    name: 'Ghoulish Frenzy',
    icon: 'ability_warlock_baneofhavoc',
    maxRanks: 2,
  },
  MORBIDITY_UNHOLY_TALENT: {
    id: 377592,
    name: 'Morbidity',
    icon: 'spell_necro_deathlyecho',
    maxRanks: 2,
  },
  UNHOLY_AURA_UNHOLY_TALENT: {
    id: 377440,
    name: 'Unholy Aura',
    icon: 'ability_deathknight_decomposingaura',
    maxRanks: 2,
  },
  UNHOLY_ASSAULT_UNHOLY_TALENT: {
    id: 207289,
    name: 'Unholy Assault',
    icon: 'spell_shadow_unholyfrenzy',
    maxRanks: 1,
  },
  ARMY_OF_THE_DAMNED_UNHOLY_TALENT: {
    id: 276837,
    name: 'Army of the Damned',
    icon: 'artifactability_unholydeathknight_deathsembrace',
    maxRanks: 1,
  },
  SUMMON_GARGOYLE_UNHOLY_TALENT: {
    id: 49206,
    name: 'Summon Gargoyle',
    icon: 'ability_deathknight_summongargoyle',
    maxRanks: 1,
  },

  //Frost
  FROST_STRIKE_FROST_TALENT: {
    id: 49143,
    name: 'Frost Strike',
    icon: 'spell_deathknight_empowerruneblade2',
    maxRanks: 1,
    runicPowerCost: 25,
  },
  OBLITERATE_FROST_TALENT: {
    id: 49020,
    name: 'Obliterate',
    icon: 'spell_deathknight_classicon',
    maxRanks: 1,
    runesCost: 2,
  },
  HOWLING_BLAST_FROST_TALENT: {
    id: 49184,
    name: 'Howling Blast',
    icon: 'spell_frost_arcticwinds',
    maxRanks: 1,
    runesCost: 1,
  },
  KILLING_MACHINE_FROST_TALENT: {
    id: 51128,
    name: 'Killing Machine',
    icon: 'inv_sword_122',
    maxRanks: 1,
  },
  RIME_FROST_TALENT: { id: 59057, name: 'Rime', icon: 'spell_frost_freezingbreath', maxRanks: 1 },
  UNLEASHED_FRENZY_FROST_TALENT: {
    id: 376905,
    name: 'Unleashed Frenzy',
    icon: 'spell_deathknight_icetouch',
    maxRanks: 1,
  },
  RUNIC_COMMAND_FROST_TALENT: {
    id: 376251,
    name: 'Runic Command',
    icon: 'ability_deathknight_remorselesswinters',
    maxRanks: 2,
  },
  IMPROVED_FROST_STRIKE_FROST_TALENT: {
    id: 316803,
    name: 'Improved Frost Strike',
    icon: 'spell_deathknight_empowerruneblade2',
    maxRanks: 2,
  },
  REMORSELESS_WINTER_FROST_TALENT: {
    id: 196770,
    name: 'Remorseless Winter',
    icon: 'ability_deathknight_remorselesswinters2',
    maxRanks: 1,
    runesCost: 1,
  },
  IMPROVED_OBLITERATE_FROST_TALENT: {
    id: 317198,
    name: 'Improved Obliterate',
    icon: 'spell_deathknight_classicon',
    maxRanks: 2,
  },
  PILLAR_OF_FROST_FROST_TALENT: {
    id: 51271,
    name: 'Pillar of Frost',
    icon: 'ability_deathknight_pillaroffrost',
    maxRanks: 1,
  },
  IMPROVED_RIME_FROST_TALENT: {
    id: 316838,
    name: 'Improved Rime',
    icon: 'spell_frost_freezingbreath',
    maxRanks: 2,
  },
  RAGE_OF_THE_FROZEN_CHAMPION_FROST_TALENT: {
    id: 377076,
    name: 'Rage of the Frozen Champion',
    icon: 'spell_mage_frostbomb',
    maxRanks: 1,
  },
  FRIGID_EXECUTIONER_FROST_TALENT: {
    id: 377073,
    name: 'Frigid Executioner',
    icon: 'spell_shadow_focusedpower',
    maxRanks: 1,
  },
  IMPROVED_KILLING_MACHINE_FROST_TALENT: {
    id: 317214,
    name: 'Improved Killing Machine',
    icon: 'inv_sword_122',
    maxRanks: 1,
  },
  COLD_HEART_FROST_TALENT: {
    id: 281208,
    name: 'Cold Heart',
    icon: 'spell_frost_frozencore',
    maxRanks: 1,
  },
  INEXORABLE_ASSAULT_FROST_TALENT: {
    id: 253593,
    name: 'Inexorable Assault',
    icon: 'achievement_dungeon_icecrown_frostmourne',
    maxRanks: 1,
  },
  FROZEN_PULSE_FROST_TALENT: {
    id: 194909,
    name: 'Frozen Pulse',
    icon: 'inv_misc_permafrostshard',
    maxRanks: 1,
  },
  AVALANCHE_FROST_TALENT: {
    id: 207142,
    name: 'Avalanche',
    icon: 'spell_frost_icestorm',
    maxRanks: 1,
  },
  BITING_COLD_FROST_TALENT: {
    id: 377056,
    name: 'Biting Cold',
    icon: 'ability_deathknight_remorselesswinters2',
    maxRanks: 1,
  },
  CHILL_STREAK_FROST_TALENT: {
    id: 305392,
    name: 'Chill Streak',
    icon: 'spell_frost_piercing_chill',
    maxRanks: 1,
    runicPowerCost: 40,
  },
  MURDEROUS_EFFICIENCY_FROST_TALENT: {
    id: 207061,
    name: 'Murderous Efficiency',
    icon: 'spell_frost_frostarmor',
    maxRanks: 1,
  },
  MIGHT_OF_THE_FROZEN_WASTES_FROST_TALENT: {
    id: 343252,
    name: 'Might of the Frozen Wastes',
    icon: 'inv_sword_120',
    maxRanks: 1,
  },
  ENDURING_STRENGTH_FROST_TALENT: {
    id: 377190,
    name: 'Enduring Strength',
    icon: 'inv_sword_62',
    maxRanks: 2,
  },
  FROSTWHELPS_AID_FROST_TALENT: {
    id: 377226,
    name: "Frostwhelp's Aid",
    icon: 'inv_pet_dkwhelplingfrost',
    maxRanks: 2,
  },
  GATHERING_STORM_FROST_TALENT: {
    id: 194912,
    name: 'Gathering Storm',
    icon: 'spell_frost_ice_shards',
    maxRanks: 1,
  },
  ENDURING_CHILL_FROST_TALENT: {
    id: 377376,
    name: 'Enduring Chill',
    icon: 'spell_frost_piercing_chill',
    maxRanks: 1,
  },
  PIERCING_CHILL_FROST_TALENT: {
    id: 377351,
    name: 'Piercing Chill',
    icon: 'spell_frost_piercing_chill',
    maxRanks: 1,
  },
  GLACIAL_ADVANCE_FROST_TALENT: {
    id: 194913,
    name: 'Glacial Advance',
    icon: 'ability_hunter_glacialtrap',
    maxRanks: 1,
    runicPowerCost: 30,
  },
  BONEGRINDER_FROST_TALENT: {
    id: 377098,
    name: 'Bonegrinder',
    icon: 'spell_deathknight_classicon',
    maxRanks: 2,
  },
  EVERFROST_FROST_TALENT: {
    id: 376938,
    name: 'Everfrost',
    icon: 'ability_mage_deepfreeze',
    maxRanks: 2,
  },
  FROSTSCYTHE_FROST_TALENT: {
    id: 207230,
    name: 'Frostscythe',
    icon: 'inv_misc_2h_farmscythe_a_01',
    maxRanks: 1,
    runesCost: 1,
  },
  COLD_BLOODED_RAGE_FROST_TALENT: {
    id: 377083,
    name: 'Cold-Blooded Rage',
    icon: 'inv_sword_122',
    maxRanks: 2,
  },
  FROSTWYRMS_FURY_FROST_TALENT: {
    id: 279302,
    name: "Frostwyrm's Fury",
    icon: 'achievement_boss_sindragosa',
    maxRanks: 1,
  },
  INVIGORATING_FREEZE_FROST_TALENT: {
    id: 377092,
    name: 'Invigorating Freeze',
    icon: 'spell_deathknight_frostfever',
    maxRanks: 2,
  },
  ICECAP_FROST_TALENT: { id: 207126, name: 'Icecap', icon: 'inv_misc_herb_icecap', maxRanks: 1 },
  OBLITERATION_FROST_TALENT: { id: 281238, name: 'Obliteration', icon: 'inv_axe_114', maxRanks: 1 },
  ABSOLUTE_ZERO_FROST_TALENT: {
    id: 377047,
    name: 'Absolute Zero',
    icon: 'spell_frost_frostnova',
    maxRanks: 1,
  },
  BREATH_OF_SINDRAGOSA_FROST_TALENT: {
    id: 152279,
    name: 'Breath of Sindragosa',
    icon: 'spell_deathknight_breathofsindragosa',
    maxRanks: 1,
    runicPowerCost: 0,
  },
});

export default talents;
export { talents as TALENTS_DEATH_KNIGHT };
