// Generated file, changes will eventually be overwritten!
import { createTalentList } from './types';

const talents = createTalentList({
  //Shared
  VENGEFUL_RETREAT_TALENT: {
    id: 198793,
    name: 'Vengeful Retreat',
    icon: 'ability_demonhunter_vengefulretreat2',
    maxRanks: 1,
  },
  HOT_FEET_TALENT: {
    id: 320416,
    name: 'Hot Feet',
    icon: 'ability_demonhunter_felrush',
    maxRanks: 1,
  },
  SIGIL_OF_FLAME_TALENT: {
    id: 204596,
    name: 'Sigil of Flame',
    icon: 'ability_demonhunter_sigilofinquisition',
    maxRanks: 1,
  },
  UNRESTRAINED_FURY_TALENT: {
    id: 320770,
    name: 'Unrestrained Fury',
    icon: 'ability_warrior_improveddisciplines',
    maxRanks: 2,
  },
  IMPRISON_TALENT: {
    id: 217832,
    name: 'Imprison',
    icon: 'ability_demonhunter_imprison',
    maxRanks: 1,
  },
  SHATTERED_RESTORATION_TALENT: {
    id: 389824,
    name: 'Shattered Restoration',
    icon: 'ability_warlock_soulsiphon',
    maxRanks: 2,
  },
  VENGEFUL_RESTRAINT_TALENT: {
    id: 320635,
    name: 'Vengeful Restraint',
    icon: 'ability_demonhunter_vengefulretreat2',
    maxRanks: 1,
  },
  IMPROVED_DISRUPT_TALENT: {
    id: 320361,
    name: 'Improved Disrupt',
    icon: 'ability_demonhunter_consumemagic',
    maxRanks: 1,
  },
  BOUNCING_GLAIVES_TALENT: {
    id: 320386,
    name: 'Bouncing Glaives',
    icon: 'ability_demonhunter_throwglaive',
    maxRanks: 1,
  },
  CONSUME_MAGIC_TALENT: {
    id: 320313,
    name: 'Consume Magic',
    icon: 'spell_misc_zandalari_council_soulswap',
    maxRanks: 1,
  },
  FLAMES_OF_FURY_TALENT: {
    id: 389694,
    name: 'Flames of Fury',
    icon: 'ability_demonhunter_sigilofinquisition',
    maxRanks: 1,
  },
  PURSUIT_TALENT: {
    id: 320654,
    name: 'Pursuit',
    icon: 'ability_warlock_demonicpower',
    maxRanks: 1,
  },
  DISRUPTING_FURY_TALENT: {
    id: 183782,
    name: 'Disrupting Fury',
    icon: 'ability_demonhunter_consumemagic',
    maxRanks: 1,
  },
  AURA_OF_PAIN_TALENT: {
    id: 207347,
    name: 'Aura of Pain',
    icon: 'ability_demonhunter_immolation',
    maxRanks: 1,
  },
  FELBLADE_TALENT: {
    id: 232893,
    name: 'Felblade',
    icon: 'ability_demonhunter_felblade',
    maxRanks: 1,
  },
  CHARRED_WARBLADES_TALENT: {
    id: 213010,
    name: 'Charred Warblades',
    icon: 'spell_fire_incinerate',
    maxRanks: 1,
  },
  FELFIRE_HASTE_TALENT: {
    id: 389846,
    name: 'Felfire Haste',
    icon: 'inv_boots_cloth_35v4',
    maxRanks: 1,
  },
  MASTER_OF_THE_GLAIVE_TALENT: {
    id: 389763,
    name: 'Master of the Glaive',
    icon: 'inv_glaive_1h_demonhunter_a_01',
    maxRanks: 1,
  },
  RUSH_OF_CHAOS_TALENT: {
    id: 320421,
    name: 'Rush of Chaos',
    icon: 'ability_demonhunter_metamorphasisdps',
    maxRanks: 1,
  },
  CONCENTRATED_SIGILS_TALENT: {
    id: 207666,
    name: 'Concentrated Sigils',
    icon: 'ability_bossfelorcs_necromancer_red',
    maxRanks: 1,
  },
  PRECISE_SIGILS_TALENT: {
    id: 389799,
    name: 'Precise Sigils',
    icon: 'ability_bossfelorcs_necromancer_orange',
    maxRanks: 1,
  },
  LOST_IN_DARKNESS_TALENT: {
    id: 389849,
    name: 'Lost in Darkness',
    icon: 'inv_pet_inquisitoreye',
    maxRanks: 1,
  },
  ILLIDARI_KNOWLEDGE_TALENT: {
    id: 389696,
    name: 'Illidari Knowledge',
    icon: 'spell_mage_overpowered',
    maxRanks: 2,
  },
  SOUL_RENDING_TALENT: {
    id: 204909,
    name: 'Soul Rending',
    icon: 'ability_demonhunter_soulcleave2',
    maxRanks: 2,
  },
  INFERNAL_ARMOR_TALENT: {
    id: 320331,
    name: 'Infernal Armor',
    icon: 'ability_demonhunter_immolation',
    maxRanks: 2,
  },
  WILL_OF_THE_ILLIDARI_TALENT: {
    id: 389695,
    name: 'Will of the Illidari',
    icon: 'ability_demonhunter_spectank',
    maxRanks: 2,
  },
  CHAOS_NOVA_TALENT: {
    id: 179057,
    name: 'Chaos Nova',
    icon: 'spell_fire_felfirenova',
    maxRanks: 1,
    furyCost: 30,
  },
  DEMONIC_TALENT: { id: 213410, name: 'Demonic', icon: 'spell_shadow_demonform', maxRanks: 1 },
  DEMONIC_ORIGINS_TALENT: {
    id: 235893,
    name: 'Demonic Origins',
    icon: 'artifactability_havocdemonhunter_anguishofthedeceiver',
    maxRanks: 1,
  },
  SIGIL_OF_SILENCE_TALENT: {
    id: 202137,
    name: 'Sigil of Silence',
    icon: 'ability_demonhunter_sigilofsilence',
    maxRanks: 1,
  },
  INTERNAL_STRUGGLE_TALENT: {
    id: 393822,
    name: 'Internal Struggle',
    icon: 'ability_warlock_demonicpower',
    maxRanks: 1,
  },
  CHAOS_FRAGMENTS_TALENT: {
    id: 320412,
    name: 'Chaos Fragments',
    icon: 'spell_fire_felfirenova',
    maxRanks: 1,
  },
  UNLEASHED_POWER_TALENT: {
    id: 206477,
    name: 'Unleashed Power',
    icon: 'ability_demonhunter_chaosnova',
    maxRanks: 1,
  },
  DARKNESS_TALENT: {
    id: 196718,
    name: 'Darkness',
    icon: 'ability_demonhunter_darkness',
    maxRanks: 1,
  },
  SIGIL_OF_MISERY_TALENT: {
    id: 207684,
    name: 'Sigil of Misery',
    icon: 'ability_demonhunter_sigilofmisery',
    maxRanks: 1,
  },
  DEMON_MUZZLE_NYI_TALENT: {
    id: 388111,
    name: 'Demon Muzzle [NYI]',
    icon: 'spell_fire_fireballgreen',
    maxRanks: 1,
  },
  ALDRACHI_DESIGN_TALENT: {
    id: 391409,
    name: 'Aldrachi Design',
    icon: 'inv_glaive_1h_artifactaldrochi_d_01dual',
    maxRanks: 1,
  },
  ERRATIC_FELHEART_TALENT: {
    id: 391397,
    name: 'Erratic Felheart',
    icon: 'inv_archaeology_70_crystallineeyeofundravius',
    maxRanks: 2,
  },
  LONG_NIGHT_TALENT: {
    id: 389781,
    name: 'Long Night',
    icon: 'spell_fire_twilightimmolation',
    maxRanks: 1,
  },
  PITCH_BLACK_TALENT: {
    id: 389783,
    name: 'Pitch Black',
    icon: 'sha_spell_warlock_demonsoul',
    maxRanks: 1,
  },
  THE_HUNT_TALENT: {
    id: 370965,
    name: 'The Hunt',
    icon: 'ability_ardenweald_demonhunter',
    maxRanks: 1,
  },
  IMPROVED_SIGIL_OF_MISERY_TALENT: {
    id: 320418,
    name: 'Improved Sigil of Misery',
    icon: 'ability_demonhunter_sigilofmisery',
    maxRanks: 1,
  },
  MISERY_IN_DEFEAT_TALENT: {
    id: 388110,
    name: 'Misery in Defeat',
    icon: 'ability_demonhunter_sigilofmisery',
    maxRanks: 1,
  },
  EXTENDED_SIGILS_TALENT: {
    id: 389697,
    name: 'Extended Sigils',
    icon: 'ability_demonhunter_sigilofinquisition',
    maxRanks: 2,
  },
  COLLECTIVE_ANGUISH_TALENT: {
    id: 390152,
    name: 'Collective Anguish',
    icon: 'artifactability_havocdemonhunter_anguishofthedeceiver',
    maxRanks: 1,
  },
  UNNATURAL_MALICE_TALENT: {
    id: 389811,
    name: 'Unnatural Malice',
    icon: 'spell_animaardenweald_missile',
    maxRanks: 1,
  },
  FAE_EMPOWERED_ELIXIR_TALENT: {
    id: 389819,
    name: 'Fae Empowered Elixir',
    icon: 'ability_demonhunter_demonictrample',
    maxRanks: 1,
  },
  QUICKENED_SIGILS_TALENT: {
    id: 209281,
    name: 'Quickened Sigils',
    icon: 'ability_demonhunter_concentratedsigils',
    maxRanks: 1,
  },
  FODDER_TO_THE_FLAME_TALENT: {
    id: 391429,
    name: 'Fodder to the Flame',
    icon: 'ability_maldraxxus_demonhunter',
    maxRanks: 1,
  },
  ELYSIAN_DECREE_TALENT: {
    id: 390163,
    name: 'Elysian Decree',
    icon: 'ability_bastion_demonhunter',
    maxRanks: 1,
  },

  //Vengeance
  FEL_DEVASTATION_TALENT: {
    id: 212084,
    name: 'Fel Devastation',
    icon: 'ability_demonhunter_feldevastation',
    maxRanks: 1,
    furyCost: 50,
  },
  FRAILTY_TALENT: {
    id: 389958,
    name: 'Frailty',
    icon: 'inv_icon_shadowcouncilorb_purple',
    maxRanks: 1,
  },
  FIERY_BRAND_TALENT: {
    id: 204021,
    name: 'Fiery Brand',
    icon: 'ability_demonhunter_fierybrand',
    maxRanks: 1,
  },
  PERFECTLY_BALANCED_GLAIVE_TALENT: {
    id: 320387,
    name: 'Perfectly Balanced Glaive',
    icon: 'ability_demonhunter_throwglaive',
    maxRanks: 1,
  },
  DEFLECTING_SPIKES_TALENT: {
    id: 321028,
    name: 'Deflecting Spikes',
    icon: 'ability_demonhunter_demonspikes',
    maxRanks: 1,
  },
  ABYSSAL_HASTE_TALENT: {
    id: 389724,
    name: 'Abyssal Haste',
    icon: 'spell_warlock_summonabyssal',
    maxRanks: 1,
  },
  SHEAR_FURY_TALENT: {
    id: 389997,
    name: 'Shear Fury',
    icon: 'ability_demonhunter_hatefulstrike',
    maxRanks: 1,
  },
  FRACTURE_TALENT: {
    id: 263642,
    name: 'Fracture',
    icon: 'ability_creature_felsunder',
    maxRanks: 1,
  },
  CALCIFIED_SPIKES_TALENT: {
    id: 389720,
    name: 'Calcified Spikes',
    icon: 'ability_demonhunter_demonspikes',
    maxRanks: 1,
  },
  ROARING_FIRE_TALENT: {
    id: 391178,
    name: 'Roaring Fire',
    icon: 'spell_fire_felflamering',
    maxRanks: 1,
  },
  RETALIATION_TALENT: {
    id: 389729,
    name: 'Retaliation',
    icon: 'ability_demonhunter_demonspikes2',
    maxRanks: 1,
  },
  FEL_FLAME_FORTIFICATION_TALENT: {
    id: 389705,
    name: 'Fel Flame Fortification',
    icon: 'spell_fire_felfire',
    maxRanks: 1,
  },
  SPIRIT_BOMB_TALENT: {
    id: 247454,
    name: 'Spirit Bomb',
    icon: 'inv_icon_shadowcouncilorb_purple',
    maxRanks: 1,
    furyCost: 45,
  },
  FEAST_OF_SOULS_TALENT: {
    id: 207697,
    name: 'Feast of Souls',
    icon: 'spell_shadow_soulleech',
    maxRanks: 1,
  },
  AGONIZING_FLAMES_TALENT: {
    id: 207548,
    name: 'Agonizing Flames',
    icon: 'achievment_raid_houroftwilight',
    maxRanks: 2,
  },
  EXTENDED_SPIKES_TALENT: {
    id: 389721,
    name: 'Extended Spikes',
    icon: 'ability_demonhunter_demonspikes',
    maxRanks: 2,
  },
  BURNING_BLOOD_TALENT: {
    id: 390213,
    name: 'Burning Blood',
    icon: 'ability_demonhunter_immolation',
    maxRanks: 2,
  },
  SOUL_BARRIER_TALENT: { id: 263648, name: 'Soul Barrier', icon: 'inv_soulbarrier', maxRanks: 1 },
  BULK_EXTRACTION_TALENT: {
    id: 320341,
    name: 'Bulk Extraction',
    icon: 'spell_shadow_shadesofdarkness',
    maxRanks: 1,
  },
  SIGIL_OF_CHAINS_TALENT: {
    id: 202138,
    name: 'Sigil of Chains',
    icon: 'ability_demonhunter_sigilofchains',
    maxRanks: 1,
  },
  VOID_REAVER_TALENT: {
    id: 268175,
    name: 'Void Reaver',
    icon: 'spell_shadow_demonicempathy',
    maxRanks: 1,
  },
  FALLOUT_TALENT: { id: 227174, name: 'Fallout', icon: 'spell_volatilefiregreen', maxRanks: 1 },
  RUINOUS_BULWARK_TALENT: {
    id: 326853,
    name: 'Ruinous Bulwark',
    icon: 'ability_demonhunter_feldevastation',
    maxRanks: 1,
  },
  VOLATILE_FLAMEBLOOD_TALENT: {
    id: 390808,
    name: 'Volatile Flameblood',
    icon: 'ability_demonhunter_immolation',
    maxRanks: 1,
  },
  REVEL_IN_PAIN_TALENT: {
    id: 343014,
    name: 'Revel in Pain',
    icon: 'ability_bossfelmagnaron_handempowered',
    maxRanks: 1,
  },
  SOUL_FURNACE_TALENT: {
    id: 391165,
    name: 'Soul Furnace',
    icon: 'ability_demonhunter_soulcleave4',
    maxRanks: 1,
  },
  PAINBRINGER_TALENT: {
    id: 207387,
    name: 'Painbringer',
    icon: 'artifactability_vengeancedemonhunter_painbringer',
    maxRanks: 2,
  },
  DARKGLARE_BOON_TALENT: {
    id: 389708,
    name: 'Darkglare Boon',
    icon: 'inv_jewelry_necklace_53',
    maxRanks: 2,
  },
  FIERY_DEMISE_TALENT: {
    id: 389220,
    name: 'Fiery Demise',
    icon: 'ability_demonhunter_fierybrand',
    maxRanks: 2,
  },
  CHAINS_OF_ANGER_TALENT: {
    id: 389715,
    name: 'Chains of Anger',
    icon: 'ability_demonhunter_sigilofchains',
    maxRanks: 1,
  },
  FOCUSED_CLEAVE_TALENT: {
    id: 343207,
    name: 'Focused Cleave',
    icon: 'ability_demonhunter_soulcleave',
    maxRanks: 1,
  },
  SOULMONGER_TALENT: {
    id: 389711,
    name: 'Soulmonger',
    icon: 'ability_demonhunter_shatteredsouls',
    maxRanks: 1,
  },
  STOKE_THE_FLAMES_TALENT: {
    id: 393827,
    name: 'Stoke the Flames',
    icon: 'ability_demonhunter_feldevastation',
    maxRanks: 1,
  },
  BURNING_ALIVE_TALENT: {
    id: 207739,
    name: 'Burning Alive',
    icon: 'spell_fire_elementaldevastation',
    maxRanks: 1,
  },
  CYCLE_OF_BINDING_TALENT: {
    id: 389718,
    name: 'Cycle of Binding',
    icon: 'ability_demonhunter_sigilofinquisition',
    maxRanks: 1,
  },
  VULNERABILITY_TALENT: {
    id: 389976,
    name: 'Vulnerability',
    icon: 'inv_icon_shadowcouncilorb_purple',
    maxRanks: 2,
  },
  FEED_THE_DEMON_TALENT: {
    id: 218612,
    name: 'Feed the Demon',
    icon: 'spell_warlock_demonicempowerment',
    maxRanks: 2,
  },
  CHARRED_FLESH_TALENT: {
    id: 336639,
    name: 'Charred Flesh',
    icon: 'ability_warlock_backdraft',
    maxRanks: 2,
  },
  THE_WEAK_WILLED_TALENT: {
    id: 389985,
    name: 'The Weak-Willed',
    icon: 'inv_icon_shadowcouncilorb_purple',
    maxRanks: 1,
  },
  SOUL_CARVER_TALENT: {
    id: 207407,
    name: 'Soul Carver',
    icon: 'inv_glaive_1h_artifactaldrochi_d_01',
    maxRanks: 1,
  },
  LAST_RESORT_TALENT: {
    id: 209258,
    name: 'Last Resort',
    icon: 'inv_glaive_1h_artifactaldorchi_d_06',
    maxRanks: 1,
  },
  DOWN_IN_FLAMES_TALENT: {
    id: 389732,
    name: 'Down in Flames',
    icon: 'ability_demonhunter_fierybrand',
    maxRanks: 1,
  },

  //Havoc
  EYE_BEAM_TALENT: {
    id: 198013,
    name: 'Eye Beam',
    icon: 'ability_demonhunter_eyebeam',
    maxRanks: 1,
    furyCost: 30,
  },
  IMPROVED_CHAOS_STRIKE_TALENT: {
    id: 343206,
    name: 'Improved Chaos Strike',
    icon: 'ability_demonhunter_chaosstrike',
    maxRanks: 1,
  },
  INSATIABLE_HUNGER_TALENT: {
    id: 258876,
    name: 'Insatiable Hunger',
    icon: 'ability_rogue_hungerforblood',
    maxRanks: 1,
  },
  DEMON_BLADES_TALENT: {
    id: 203555,
    name: 'Demon Blades',
    icon: 'inv_weapon_shortblade_92',
    maxRanks: 1,
  },
  FELFIRE_HEART_TALENT: {
    id: 388109,
    name: 'Felfire Heart',
    icon: 'ability_demonhunter_immolation',
    maxRanks: 1,
  },
  DEMONIC_APPETITE_TALENT: {
    id: 206478,
    name: 'Demonic Appetite',
    icon: 'ability_creature_poison_01_purple',
    maxRanks: 1,
  },
  IMPROVED_FEL_RUSH_TALENT: {
    id: 343017,
    name: 'Improved Fel Rush',
    icon: 'ability_demonhunter_felrush',
    maxRanks: 1,
  },
  FIRST_BLOOD_TALENT: {
    id: 206416,
    name: 'First Blood',
    icon: 'ability_deathwing_bloodcorruption_death',
    maxRanks: 1,
  },
  FURIOUS_THROWS_TALENT: {
    id: 393029,
    name: 'Furious Throws',
    icon: 'ability_demonhunter_throwglaive',
    maxRanks: 1,
  },
  BURNING_HATRED_TALENT: {
    id: 320374,
    name: 'Burning Hatred',
    icon: 'ability_demonhunter_immolation',
    maxRanks: 1,
  },
  CRITICAL_CHAOS_TALENT: {
    id: 320413,
    name: 'Critical Chaos',
    icon: 'ability_demonhunter_chaosstrike',
    maxRanks: 2,
  },
  MORTAL_DANCE_TALENT: {
    id: 328725,
    name: 'Mortal Dance',
    icon: 'ability_demonhunter_vengefulretreat',
    maxRanks: 1,
  },
  DANCING_WITH_FATE_TALENT: {
    id: 389978,
    name: 'Dancing with Fate',
    icon: 'inv_polearm_1h_felfireraid_d_02',
    maxRanks: 2,
  },
  INITIATIVE_TALENT: {
    id: 388108,
    name: 'Initiative',
    icon: 'ability_rogue_surpriseattack',
    maxRanks: 1,
  },
  DESPERATE_INSTINCTS_TALENT: {
    id: 205411,
    name: 'Desperate Instincts',
    icon: 'spell_shadow_manafeed',
    maxRanks: 1,
  },
  NETHERWALK_TALENT: {
    id: 196555,
    name: 'Netherwalk',
    icon: 'spell_warlock_demonsoul',
    maxRanks: 1,
  },
  CHAOTIC_TRANSFORMATION_TALENT: {
    id: 388112,
    name: 'Chaotic Transformation',
    icon: 'ability_demonhunter_glide',
    maxRanks: 1,
  },
  FEL_ERUPTION_TALENT: {
    id: 211881,
    name: 'Fel Eruption',
    icon: 'ability_bossfellord_felspike',
    maxRanks: 1,
    furyCost: 10,
  },
  TRAIL_OF_RUIN_TALENT: {
    id: 258881,
    name: 'Trail of Ruin',
    icon: 'ability_demonhunter_bladedance',
    maxRanks: 1,
  },
  UNBOUND_CHAOS_TALENT: {
    id: 347461,
    name: 'Unbound Chaos',
    icon: 'artifactability_vengeancedemonhunter_painbringer',
    maxRanks: 2,
  },
  BLIND_FURY_TALENT: {
    id: 203550,
    name: 'Blind Fury',
    icon: 'ability_bosskilrogg_deadeye',
    maxRanks: 2,
  },
  LOOKS_CAN_KILL_TALENT: {
    id: 320415,
    name: 'Looks Can Kill',
    icon: 'ability_demonhunter_eyebeam',
    maxRanks: 1,
  },
  SERRATED_GLAIVE_TALENT: {
    id: 390154,
    name: 'Serrated Glaive',
    icon: 'inv_glaive_1h_artifactaldrochi_d_03dual',
    maxRanks: 2,
  },
  GROWING_INFERNO_TALENT: {
    id: 390158,
    name: 'Growing Inferno',
    icon: 'spell_fel_incinerate',
    maxRanks: 2,
  },
  TACTICAL_RETREAT_TALENT: {
    id: 389688,
    name: 'Tactical Retreat',
    icon: 'ability_demonhunter_vengefulretreat2',
    maxRanks: 1,
  },
  ISOLATED_PREY_TALENT: {
    id: 388113,
    name: 'Isolated Prey',
    icon: 'spell_shadow_shadesofdarkness',
    maxRanks: 1,
  },
  FURIOUS_GAZE_TALENT: {
    id: 343311,
    name: 'Furious Gaze',
    icon: 'ability_demonhunter_eyebeam',
    maxRanks: 1,
  },
  RELENTLESS_ONSLAUGHT_TALENT: {
    id: 389977,
    name: 'Relentless Onslaught',
    icon: 'ability_demonhunter_soulcleave2',
    maxRanks: 1,
  },
  BURNING_WOUND_TALENT: {
    id: 391189,
    name: 'Burning Wound',
    icon: 'spell_fire_felhellfire',
    maxRanks: 1,
  },
  MOMENTUM_TALENT: {
    id: 206476,
    name: 'Momentum',
    icon: 'ability_foundryraid_demolition',
    maxRanks: 1,
  },
  CHAOS_THEORY_TALENT: {
    id: 389687,
    name: 'Chaos Theory',
    icon: 'inv_glaive_1h_artifactaldrochi_d_03dual',
    maxRanks: 1,
  },
  RESTLESS_HUNTER_TALENT: {
    id: 390142,
    name: 'Restless Hunter',
    icon: 'ability_demonhunter_doublejump',
    maxRanks: 1,
  },
  INNER_DEMON_TALENT: {
    id: 389693,
    name: 'Inner Demon',
    icon: 'ability_demonhunter_glide',
    maxRanks: 1,
  },
  MOARG_BIONICS_TALENT: {
    id: 391275,
    name: "Mo'arg Bionics",
    icon: 'ability_demonhunter_throwglaive',
    maxRanks: 1,
  },
  RAGEFIRE_TALENT: { id: 388107, name: 'Ragefire', icon: 'spell_fire_fireballgreen', maxRanks: 1 },
  KNOW_YOUR_ENEMY_TALENT: {
    id: 388118,
    name: 'Know Your Enemy',
    icon: 'ability_demonhunter_eyeofleotheras',
    maxRanks: 2,
  },
  GLAIVE_TEMPEST_TALENT: {
    id: 342817,
    name: 'Glaive Tempest',
    icon: 'inv_glaive_1h_artifactazgalor_d_06dual',
    maxRanks: 1,
    furyCost: 30,
  },
  FEL_BARRAGE_TALENT: { id: 258925, name: 'Fel Barrage', icon: 'inv_felbarrage', maxRanks: 1 },
  CYCLE_OF_HATRED_TALENT: {
    id: 258887,
    name: 'Cycle of Hatred',
    icon: 'ability_ironmaidens_whirlofblood',
    maxRanks: 2,
  },
  SOULREND_TALENT: {
    id: 388106,
    name: 'Soulrend',
    icon: 'ability_demonhunter_bloodlet',
    maxRanks: 2,
  },
  ESSENCE_BREAK_TALENT: {
    id: 258860,
    name: 'Essence Break',
    icon: 'spell_shadow_ritualofsacrifice',
    maxRanks: 1,
  },
  SHATTERED_DESTINY_TALENT: {
    id: 388116,
    name: 'Shattered Destiny',
    icon: 'achievement_boss_triumvirate_darknaaru',
    maxRanks: 1,
  },
  ANY_MEANS_NECESSARY_TALENT: {
    id: 388114,
    name: 'Any Means Necessary',
    icon: 'ability_warlock_demonicpower',
    maxRanks: 1,
  },
});

export default talents;
export { talents as TALENTS_DEMON_HUNTER };
