// Generated file, changes will eventually be overwritten!
import { createTalentList } from './types';

const talents = createTalentList({
  //Shared
  RAKE_TALENT: {
    id: 1822,
    name: 'Rake',
    icon: 'ability_druid_disembowel',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  FRENZIED_REGENERATION_TALENT: {
    id: 22842,
    name: 'Frenzied Regeneration',
    icon: 'ability_bullrush',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  REJUVENATION_TALENT: {
    id: 774,
    name: 'Rejuvenation',
    icon: 'spell_nature_rejuvenation',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  STARFIRE_TALENT: {
    id: 194153,
    name: 'Starfire',
    icon: 'spell_arcane_starfire',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  THRASH_TALENT: {
    id: 106832,
    name: 'Thrash',
    icon: 'spell_druid_thrash',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  IMPROVED_BARKSKIN_TALENT: {
    id: 327993,
    name: 'Improved Barkskin',
    icon: 'spell_nature_stoneclawtotem',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  SWIFTMEND_TALENT: {
    id: 18562,
    name: 'Swiftmend',
    icon: 'inv_relics_idolofrejuvenation',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  STARSURGE_TALENT: {
    id: 197626,
    name: 'Starsurge',
    icon: 'spell_arcane_arcane03',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  RIP_TALENT: {
    id: 1079,
    name: 'Rip',
    icon: 'ability_ghoulfrenzy',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  SWIPE_TALENT: {
    id: 213764,
    name: 'Swipe',
    icon: 'inv_misc_monsterclaw_03',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  IMPROVED_FRENZIED_REGENERATION_NNF_TALENT: {
    id: 301768,
    name: 'Improved Frenzied Regeneration (NNF)',
    icon: 'ability_bullrush',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  REMOVE_CORRUPTION_TALENT: {
    id: 2782,
    name: 'Remove Corruption',
    icon: 'spell_holy_removecurse',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  MOONKIN_FORM_TALENT: {
    id: 24858,
    name: 'Moonkin Form',
    icon: 'spell_nature_forceofnature',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  MAIM_TALENT: {
    id: 22570,
    name: 'Maim',
    icon: 'ability_druid_mangle.tga',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  KILLER_INSTINCT_TALENT: {
    id: 108299,
    name: 'Killer Instinct',
    icon: 'ability_druid_predatoryinstincts',
    maxRanks: 3,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  IRONFUR_TALENT: {
    id: 192081,
    name: 'Ironfur',
    icon: 'ability_druid_ironfur',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  NURTURING_INSTINCT_TALENT: {
    id: 33873,
    name: 'Nurturing Instinct',
    icon: 'ability_druid_healinginstincts',
    maxRanks: 3,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  HIBERNATE_TALENT: {
    id: 2637,
    name: 'Hibernate',
    icon: 'spell_nature_sleep',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  FELINE_SWIFTNESS_TALENT: {
    id: 131768,
    name: 'Feline Swiftness',
    icon: 'spell_druid_tirelesspursuit',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  SKULL_BASH_TALENT: {
    id: 106839,
    name: 'Skull Bash',
    icon: 'inv_bone_skull_04',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  THICK_HIDE_TALENT: {
    id: 16931,
    name: 'Thick Hide',
    icon: 'inv_misc_pelt_bear_03',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  TIGER_DASH_TALENT: {
    id: 252216,
    name: 'Tiger Dash',
    icon: 'ability_druid_dash_orange',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
  },
  WILD_CHARGE_TALENT: {
    id: 102401,
    name: 'Wild Charge',
    icon: 'spell_druid_wildcharge',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
  },
  NEW_RESTO_PASSIVE_NNF_TALENT: {
    id: 377796,
    name: 'New Resto Passive (NNF)',
    icon: 'ability_druid_naturalperfection',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  CYCLONE_TALENT: {
    id: 33786,
    name: 'Cyclone',
    icon: 'spell_nature_earthbind',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  ASTRAL_INFLUENCE_TALENT: {
    id: 197524,
    name: 'Astral Influence',
    icon: 'ability_skyreach_lens_flare',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  TIRELESS_PURSUIT_TALENT: {
    id: 377801,
    name: 'Tireless Pursuit',
    icon: 'spell_druid_tirelesspursuit',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  SOOTHE_TALENT: {
    id: 2908,
    name: 'Soothe',
    icon: 'ability_hunter_beastsoothe',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  SUNFIRE_NO_AOE_TALENT: {
    id: 93402,
    name: 'Sunfire (no AOE)',
    icon: 'ability_mage_firestarter',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  TYPHOON_TALENT: {
    id: 132469,
    name: 'Typhoon',
    icon: 'ability_druid_typhoon',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  PRIMAL_FURY_TALENT: {
    id: 159286,
    name: 'Primal Fury',
    icon: 'ability_racial_cannibalize',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  URSOCS_ENDURANCE_NNF_TALENT: {
    id: 280013,
    name: "Ursoc's Endurance (NNF)",
    icon: 'spell_nature_stoneclawtotem',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'tiered',
  },
  STAMPEDING_ROAR_TALENT: {
    id: 288826,
    name: 'Stampeding Roar',
    icon: 'spell_druid_stamedingroar',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  WILD_GROWTH_TALENT: {
    id: 48438,
    name: 'Wild Growth',
    icon: 'ability_druid_flourish',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  IMPROVED_SUNFIRE_TALENT: {
    id: 231050,
    name: 'Improved Sunfire',
    icon: 'ability_mage_firestarter',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  MIGHTY_BASH_TALENT: {
    id: 5211,
    name: 'Mighty Bash',
    icon: 'ability_druid_bash',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  INCAPACITATING_ROAR_TALENT: {
    id: 99,
    name: 'Incapacitating Roar',
    icon: 'ability_druid_demoralizingroar',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  URSINE_VIGOR_TALENT: {
    id: 377842,
    name: 'Ursine Vigor',
    icon: 'ability_druid_markofursol',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  LYCARAS_TEACHINGS_TALENT: {
    id: 378988,
    name: "Lycara's Teachings",
    icon: 'inv_trinket_ardenweald_02_green',
    maxRanks: 3,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  IMPROVED_REJUVENATION_TALENT: {
    id: 231040,
    name: 'Improved Rejuvenation',
    icon: 'spell_nature_rejuvenation',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  URSOLS_VORTEX_TALENT: {
    id: 102793,
    name: "Ursol's Vortex",
    icon: 'spell_druid_ursolsvortex',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  MASS_ENTANGLEMENT_TALENT: {
    id: 102359,
    name: 'Mass Entanglement',
    icon: 'spell_druid_massentanglement',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  WELL_HONED_INSTINCTS_TALENT: {
    id: 377847,
    name: 'Well-Honed Instincts',
    icon: 'ability_druid_tigersroar',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  RENEWAL_TALENT: {
    id: 108238,
    name: 'Renewal',
    icon: 'spell_nature_natureblessing',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  INNERVATE_TALENT: {
    id: 29166,
    name: 'Innervate',
    icon: 'spell_nature_lightning',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  FUROR_TALENT: {
    id: 378986,
    name: 'Furor',
    icon: 'spell_holy_blessingofstamina',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  HEART_OF_THE_WILD_TALENT: {
    id: 319454,
    name: 'Heart of the Wild',
    icon: 'spell_holy_blessingofagility',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  NATURES_VIGIL_TALENT: {
    id: 124974,
    name: "Nature's Vigil",
    icon: 'achievement_zone_feralas',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },

  //Guardian
  MAUL_GUARDIAN_TALENT: {
    id: 6807,
    name: 'Maul',
    icon: 'ability_druid_maul',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  GORE_GUARDIAN_TALENT: {
    id: 210706,
    name: 'Gore',
    icon: 'spell_druid_bearhug',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  SURVIVAL_INSTINCTS_GUARDIAN_TALENT: {
    id: 328767,
    name: 'Survival Instincts',
    icon: 'ability_druid_tigersroar',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  BRAMBLES_GUARDIAN_TALENT: {
    id: 203953,
    name: 'Brambles',
    icon: 'inv_misc_thornnecklace',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  BRISTLING_FUR_GUARDIAN_TALENT: {
    id: 155835,
    name: 'Bristling Fur',
    icon: 'spell_druid_bristlingfur',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  URSINE_ADEPT_GUARDIAN_TALENT: {
    id: 300346,
    name: 'Ursine Adept',
    icon: 'talentspec_druid_feral_bear',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  MANGLE_GUARDIAN_TALENT: {
    id: 231064,
    name: 'Mangle',
    icon: 'ability_druid_mangle2',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  INNATE_RESOLVE_GUARDIAN_TALENT: {
    id: 377811,
    name: 'Innate Resolve',
    icon: 'spell_nature_healingway',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  INFECTED_WOUNDS_GUARDIAN_TALENT: {
    id: 345208,
    name: 'Infected Wounds',
    icon: 'ability_druid_infectedwound',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  BERSERK_RAVAGE_GUARDIAN_TALENT: {
    id: 343240,
    name: 'Berserk: Ravage',
    icon: 'ability_druid_berserk',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  URSOCS_ENDURANCE_GUARDIAN_TALENT: {
    id: 200399,
    name: "Ursoc's Endurance",
    icon: 'ability_hunter_pet_bear',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'tiered',
  },
  GORY_FUR_GUARDIAN_TALENT: {
    id: 200854,
    name: 'Gory Fur',
    icon: 'artifactability_guardiandruid_goryfur',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  PAWSITIVE_OUTLOOK_GUARDIAN_TALENT: {
    id: 238121,
    name: 'Pawsitive Outlook',
    icon: 'spell_druid_thrash',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  TOOTH_AND_CLAW_GUARDIAN_TALENT: {
    id: 135288,
    name: 'Tooth and Claw',
    icon: 'inv_misc_monsterfang_01',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  LAYERED_MANE_GUARDIAN_TALENT: {
    id: 384721,
    name: 'Layered Mane',
    icon: 'ability_druid_ironfur',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  SCINTILLATING_MOONLIGHT_GUARDIAN_TALENT: {
    id: 238049,
    name: 'Scintillating Moonlight',
    icon: 'spell_nature_starfall',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  EARTHWARDEN_GUARDIAN_TALENT: {
    id: 203974,
    name: 'Earthwarden',
    icon: 'spell_shaman_blessingofeternals',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  VICIOUS_CYCLE_GUARDIAN_TALENT: {
    id: 371999,
    name: 'Vicious Cycle',
    icon: 'spell_druid_bearhug',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  VULNERABLE_FLESH_GUARDIAN_TALENT: {
    id: 372618,
    name: 'Vulnerable Flesh',
    icon: 'ability_druid_primalagression',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  FRONT_OF_THE_PACK_GUARDIAN_TALENT: {
    id: 377835,
    name: 'Front of the Pack',
    icon: 'spell_druid_stampedingroar_cat',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  REINFORCED_FUR_GUARDIAN_TALENT: {
    id: 200395,
    name: 'Reinforced Fur',
    icon: 'spell_druid_malfurionstenacity',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  GALACTIC_GUARDIAN_GUARDIAN_TALENT: {
    id: 203964,
    name: 'Galactic Guardian',
    icon: 'spell_frost_iceclaw',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  TWIN_MOONFIRE_GUARDIAN_TALENT: {
    id: 372567,
    name: 'Twin Moonfire',
    icon: 'spell_nature_starfall',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  BERSERK_UNCHECKED_AGGRESSION_GUARDIAN_TALENT: {
    id: 377623,
    name: 'Berserk: Unchecked Aggression',
    icon: 'ability_druid_berserk',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  FURY_OF_NATURE_GUARDIAN_TALENT: {
    id: 370695,
    name: 'Fury of Nature',
    icon: 'spell_nature_moonglow',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  BERSERK_PERSISTENCE_GUARDIAN_TALENT: {
    id: 377779,
    name: 'Berserk: Persistence',
    icon: 'ability_druid_berserk',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  REINVIGORATION_GUARDIAN_TALENT: {
    id: 372945,
    name: 'Reinvigoration',
    icon: 'ability_druid_overgrowth',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  CIRCLE_OF_LIFE_AND_DEATH_GUARDIAN_TALENT: {
    id: 338657,
    name: 'Circle of Life and Death',
    icon: 'ability_druid_cyclone',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  ELUNES_FAVORED_GUARDIAN_TALENT: {
    id: 370586,
    name: "Elune's Favored",
    icon: 'spell_holy_elunesgrace',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  SURVIVAL_OF_THE_FITTEST_GUARDIAN_TALENT: {
    id: 203965,
    name: 'Survival of the Fittest',
    icon: 'ability_druid_enrage',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  DREAM_OF_CENARIUS_GUARDIAN_TALENT: {
    id: 372119,
    name: 'Dream of Cenarius',
    icon: 'ability_druid_dreamstate',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  URSOCS_FURY_GUARDIAN_TALENT: {
    id: 377210,
    name: "Ursoc's Fury",
    icon: 'achievement_emeraldnightmare_ursoc',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  PULVERIZE_GUARDIAN_TALENT: {
    id: 80313,
    name: 'Pulverize',
    icon: 'spell_druid_malfurionstenacity',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  CONVOKE_THE_SPIRITS_GUARDIAN_TALENT: {
    id: 337433,
    name: 'Convoke the Spirits',
    icon: 'ability_ardenweald_druid',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  INCARNATION_GUARDIAN_OF_URSOC_GUARDIAN_TALENT: {
    id: 102558,
    name: 'Incarnation: Guardian of Ursoc',
    icon: 'spell_druid_incarnation',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  SOUL_OF_THE_FOREST_GUARDIAN_TALENT: {
    id: 158477,
    name: 'Soul of the Forest',
    icon: 'ability_druid_manatree',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  BLOOD_FRENZY_GUARDIAN_TALENT: {
    id: 203962,
    name: 'Blood Frenzy',
    icon: 'ability_druid_primaltenacity',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  GUARDIAN_OF_ELUNE_GUARDIAN_TALENT: {
    id: 155578,
    name: 'Guardian of Elune',
    icon: 'spell_druid_guardianofelune',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  AFTER_THE_WILDFIRE_GUARDIAN_TALENT: {
    id: 371905,
    name: 'After the Wildfire',
    icon: 'spell_nature_naturetouchgrow',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  UNTAMED_SAVAGERY_GUARDIAN_TALENT: {
    id: 372943,
    name: 'Untamed Savagery',
    icon: 'spell_druid_bloodythrash',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  REND_AND_TEAR_GUARDIAN_TALENT: {
    id: 204053,
    name: 'Rend and Tear',
    icon: 'ability_druid_swipe',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  RAGE_OF_THE_SLEEPER_GUARDIAN_TALENT: {
    id: 200851,
    name: 'Rage of the Sleeper',
    icon: 'inv_hand_1h_artifactursoc_d_01',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },

  //Balance
  ECLIPSE_BALANCE_TALENT: {
    id: 79577,
    name: 'Eclipse',
    icon: 'ability_druid_eclipseorange',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  IMPROVED_ECLIPSE_BALANCE_TALENT: {
    id: 328021,
    name: 'Improved Eclipse',
    icon: 'ability_druid_eclipseorange',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  MOONFIRESUNFIRE__S_BALANCE_TALENT: {
    id: 328023,
    name: 'Moonfire/Sunfire + 3/6s',
    icon: 'spell_nature_starfall',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  FORCE_OF_NATURE_BALANCE_TALENT: {
    id: 205636,
    name: 'Force of Nature',
    icon: 'ability_druid_forceofnature',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  NATURES_BALANCE_BALANCE_TALENT: {
    id: 202430,
    name: "Nature's Balance",
    icon: 'ability_druid_balanceofpower',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  WARRIOR_OF_ELUNE_BALANCE_TALENT: {
    id: 202425,
    name: 'Warrior of Elune',
    icon: 'spell_holy_elunesgrace',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  STARFALL_BALANCE_TALENT: {
    id: 327541,
    name: 'Starfall',
    icon: 'ability_druid_starfall',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  MOONKIN_FORM_BALANCE_TALENT: {
    id: 231042,
    name: 'Moonkin Form',
    icon: 'spell_nature_forceofnature',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  CELESTIAL_ALIGNMENT_SL_VERSION_NO_INITIAL_DAMAGE_BALANCE_TALENT: {
    id: 194223,
    name: 'Celestial Alignment [SL version, No initial damage]',
    icon: 'spell_nature_natureguardian',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  IMPROVED_STARSURGE_BALANCE_TALENT: {
    id: 328022,
    name: 'Improved Starsurge',
    icon: 'spell_arcane_arcane03',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  SOLAR_BEAM_BALANCE_TALENT: {
    id: 78675,
    name: 'Solar Beam',
    icon: 'ability_vehicle_sonicshockwave',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  SHOOTING_STARS_BALANCE_TALENT: {
    id: 202342,
    name: 'Shooting Stars',
    icon: 'spell_priest_divinestar_shadow2',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  POWER_OF_GOLDRINN_BALANCE_TALENT: {
    id: 202996,
    name: 'Power of Goldrinn',
    icon: 'inv_mount_spectralwolf',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  STARLORD_BALANCE_TALENT: {
    id: 202345,
    name: 'Starlord',
    icon: 'spell_shaman_measuredinsight',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  STELLAR_DRIFT_BALANCE_TALENT: {
    id: 202354,
    name: 'Stellar Drift',
    icon: 'ability_druid_starfall',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  STELLAR_INSPIRATION_BALANCE_TALENT: {
    id: 383194,
    name: 'Stellar Inspiration',
    icon: 'ability_skyreach_lens_flare',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  LIGHT_OF_THE_SUN_BALANCE_TALENT: {
    id: 202918,
    name: 'Light of the Sun',
    icon: 'ability_vehicle_sonicshockwave',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  UMBRAL_INTENSITY_BALANCE_TALENT: {
    id: 383195,
    name: 'Umbral Intensity',
    icon: 'ability_druid_eclipse',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  PRECISE_ALIGNMENT_BALANCE_TALENT: {
    id: 340706,
    name: 'Precise Alignment',
    icon: 'spell_nature_natureguardian',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  BLESSING_OF_ANSHE_BALANCE_TALENT: {
    id: 202739,
    name: "Blessing of An'she",
    icon: 'spell_priest_divinestar_holy',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  BLESSING_OF_ELUNE_BALANCE_TALENT: {
    id: 202737,
    name: 'Blessing of Elune',
    icon: 'achievement_worldevent_lunar',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  SOUL_OF_THE_FOREST_BALANCE_TALENT: {
    id: 114107,
    name: 'Soul of the Forest',
    icon: 'ability_druid_manatree',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  FURY_OF_THE_SKIES_BALANCE_TALENT: {
    id: 340708,
    name: 'Fury of the Skies (1/2%)',
    icon: 'spell_druid_equinox',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  STELLAR_FLARE_BALANCE_TALENT: {
    id: 202347,
    name: 'Stellar Flare',
    icon: 'ability_druid_stellarflare',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  TWIN_MOONS_BALANCE_TALENT: {
    id: 279620,
    name: 'Twin Moons',
    icon: 'spell_nature_starfall',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  SOLSTICE_BALANCE_TALENT: {
    id: 343647,
    name: 'Solstice',
    icon: 'artifactability_balancedruid_moonandstars',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  TIMEWORN_DREAMBINDER_NNF_BALANCE_TALENT: {
    id: 339949,
    name: 'Timeworn Dreambinder [NNF]',
    icon: 'ability_creature_cursed_04',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  ONETHS_CLEAR_VISION_NNF_BALANCE_TALENT: {
    id: 338661,
    name: "Oneth's Clear Vision [NNF]",
    icon: 'spell_arcane_invocation',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  UMBRAL_INFUSION_NNF_BALANCE_TALENT: {
    id: 383196,
    name: 'Umbral Infusion [NNF]',
    icon: 'spell_animaardenweald_groundstate',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  CONVOKE_THE_SPIRITS_BALANCE_TALENT: {
    id: 323764,
    name: 'Convoke the Spirits',
    icon: 'ability_ardenweald_druid',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  INCARNATION_CHOSEN_OF_ELUNE_BALANCE_TALENT: {
    id: 102560,
    name: 'Incarnation: Chosen of Elune',
    icon: 'spell_druid_incarnation',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  CIRCLE_OF_LIFE_AND_DEATH_BALANCE_TALENT: {
    id: 338657,
    name: 'Circle of Life and Death',
    icon: 'ability_druid_cyclone',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  PRIMORDIAL_ARCANIC_PULSAR_BALANCE_TALENT: {
    id: 338668,
    name: 'Primordial Arcanic Pulsar',
    icon: 'spell_arcane_arcane03',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  FURY_OF_ELUNE_BALANCE_TALENT: {
    id: 202770,
    name: 'Fury of Elune',
    icon: 'ability_druid_dreamstate',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  NEW_MOON_BALANCE_TALENT: {
    id: 274281,
    name: 'New Moon',
    icon: 'artifactability_balancedruid_newmoon',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  BALANCE_OF_ALL_THINGS_BALANCE_TALENT: {
    id: 339942,
    name: 'Balance of All Things',
    icon: 'ability_druid_balanceofpower',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  ADAPTIVE_SWARM_BALANCE_TALENT: {
    id: 325727,
    name: 'Adaptive Swarm',
    icon: 'ability_maldraxxus_druid',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  ORBIT_BREAKER_BALANCE_TALENT: {
    id: 383197,
    name: 'Orbit Breaker',
    icon: 'artifactability_balancedruid_moonandstars',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },

  //Feral
  TIGERS_FURY_FERAL_TALENT: {
    id: 5217,
    name: "Tiger's Fury",
    icon: 'ability_mount_jungletiger',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  MAX_ENERGY_FERAL_TALENT: {
    id: 383352,
    name: '[Max Energy]',
    icon: 'spell_chargepositive',
    maxRanks: 3,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  OMEN_OF_CLARITY_FERAL_TALENT: {
    id: 16864,
    name: 'Omen of Clarity',
    icon: 'spell_nature_crystalball',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  IMPROVED_TIGERS_FURY_FERAL_TALENT: {
    id: 231055,
    name: "Improved Tiger's Fury",
    icon: 'ability_mount_jungletiger',
    maxRanks: 3,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  IMPROVED_SHRED_FERAL_TALENT: {
    id: 343232,
    name: 'Improved Shred',
    icon: 'spell_shadow_vampiricaura',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  SCENT_OF_BLOOD_FERAL_TALENT: {
    id: 285564,
    name: 'Scent of Blood',
    icon: 'spell_druid_thrash',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  SABERTOOTH_FERAL_TALENT: {
    id: 202031,
    name: 'Sabertooth',
    icon: 'inv_misc_monsterfang_01',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  PREDATOR_FERAL_TALENT: {
    id: 202021,
    name: 'Predator',
    icon: 'ability_hunter_catlikereflexes',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  RAKE_STEALTH_BONUS_ALSO_SHRED_FERAL_TALENT: {
    id: 231052,
    name: 'Rake Stealth bonus (also Shred)',
    icon: 'ability_druid_prowl',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  SHRED_BLEED_BONUS_ALSO_SWIPE_FERAL_TALENT: {
    id: 231063,
    name: 'Shred Bleed bonus (also Swipe)',
    icon: 'inv_misc_monsterclaw_03',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  SUDDEN_AMBUSH_FERAL_TALENT: {
    id: 340694,
    name: 'Sudden Ambush',
    icon: 'ability_hunter_catlikereflexes',
    maxRanks: 3,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  BERSERK_RELENTLESSNESS_FERAL_TALENT: {
    id: 343223,
    name: 'Berserk: Relentlessness',
    icon: 'ability_druid_berserk',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  TASTE_FOR_BLOOD_FERAL_TALENT: {
    id: 340682,
    name: 'Taste for Blood',
    icon: 'ability_druid_ferociousbite',
    maxRanks: 3,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  LUNAR_INSPIRATION_FERAL_TALENT: {
    id: 155580,
    name: 'Lunar Inspiration',
    icon: 'spell_druid_lunarinspiration',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  PRIMAL_WRATH_FERAL_TALENT: {
    id: 285381,
    name: 'Primal Wrath',
    icon: 'artifactability_feraldruid_ashamanesbite',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  MOMENT_OF_CLARITY_FERAL_TALENT: {
    id: 236068,
    name: 'Moment of Clarity',
    icon: 'spell_druid_momentofclarity',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  BRUTAL_SLASH_FERAL_TALENT: {
    id: 202028,
    name: 'Brutal Slash',
    icon: 'ability_druid_ravage',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  SAVAGE_ROAR_FERAL_TALENT: {
    id: 52610,
    name: 'Savage Roar',
    icon: 'ability_druid_skinteeth',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  PREDATORY_SWIFTNESS_FERAL_TALENT: {
    id: 16974,
    name: 'Predatory Swiftness',
    icon: 'ability_hunter_pet_cat',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  INFECTED_WOUNDS_FERAL_TALENT: {
    id: 48484,
    name: 'Infected Wounds',
    icon: 'ability_druid_infectedwound',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  SURVIVAL_INSTINCTS_FERAL_TALENT: {
    id: 61336,
    name: 'Survival Instincts',
    icon: 'ability_druid_tigersroar',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  BERSERK_JUNGLE_STALKER_FERAL_TALENT: {
    id: 384671,
    name: 'Berserk: Jungle Stalker',
    icon: 'ability_druid_berserk',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  CARNIVOROUS_INSTINCT_FERAL_TALENT: {
    id: 340705,
    name: 'Carnivorous Instinct',
    icon: 'ability_mount_jungletiger',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  EYE_OF_FEARFUL_SYMMETRY_FERAL_TALENT: {
    id: 339141,
    name: 'Eye of Fearful Symmetry',
    icon: 'ability_druid_healinginstincts',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  CAT_EYE_CURIO_NO_MAX_E_FERAL_TALENT: {
    id: 339144,
    name: 'Cat-Eye Curio (no max E)',
    icon: 'inv_jewelcrafting_gem_30',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  BERSERK_FRENZY_FERAL_TALENT: {
    id: 384668,
    name: 'Berserk: Frenzy',
    icon: 'ability_druid_berserk',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  BLOODTALONS_FERAL_TALENT: {
    id: 319439,
    name: 'Bloodtalons',
    icon: 'spell_druid_bloodythrash',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  FERAL_FRENZY_FERAL_TALENT: {
    id: 274837,
    name: 'Feral Frenzy',
    icon: 'ability_druid_rake',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  ADAPTIVE_SWARM_FERAL_TALENT: {
    id: 325727,
    name: 'Adaptive Swarm',
    icon: 'ability_maldraxxus_druid',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  CONVOKE_THE_SPIRITS_FERAL_TALENT: {
    id: 323764,
    name: 'Convoke the Spirits',
    icon: 'ability_ardenweald_druid',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  INCARNATION_AVATAR_OF_ASHAMANE_FERAL_TALENT: {
    id: 102543,
    name: 'Incarnation: Avatar of Ashamane',
    icon: 'spell_druid_incarnation',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  SOUL_OF_THE_FOREST_FERAL_TALENT: {
    id: 158476,
    name: 'Soul of the Forest',
    icon: 'ability_druid_manatree',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  APEX_PREDATORS_CRAVING_FERAL_TALENT: {
    id: 339139,
    name: "Apex Predator's Craving",
    icon: 'ability_druid_primaltenacity',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  DRAUGHT_OF_DEEP_FOCUS_FERAL_TALENT: {
    id: 338658,
    name: 'Draught of Deep Focus',
    icon: 'trade_alchemy_dpotion_d12',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  UNBRIDLED_SWARM_FERAL_TALENT: {
    id: 354123,
    name: 'Unbridled Swarm',
    icon: 'ability_maldraxxus_druid',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  CIRCLE_OF_LIFE_AND_DEATH_FERAL_TALENT: {
    id: 338657,
    name: 'Circle of Life and Death',
    icon: 'ability_druid_cyclone',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },

  //Restoration
  LIFEBLOOM_RESTORATION_TALENT: {
    id: 33763,
    name: 'Lifebloom',
    icon: 'inv_misc_herb_felblossom',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  EFFLORESCENCE_RESTORATION_TALENT: {
    id: 145205,
    name: 'Efflorescence',
    icon: 'inv_misc_herb_talandrasrose',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  NATURES_SWIFTNESS_RESTORATION_TALENT: {
    id: 132158,
    name: "Nature's Swiftness",
    icon: 'spell_nature_ravenform',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  OMEN_OF_CLARITY_RESTORATION_TALENT: {
    id: 113043,
    name: 'Omen of Clarity',
    icon: 'spell_nature_crystalball',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  READY_FOR_ANYTHING_RESTORATION_TALENT: {
    id: 382550,
    name: 'Ready For Anything',
    icon: 'spell_nature_ravenform',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  IRONBARK_RESTORATION_TALENT: {
    id: 102342,
    name: 'Ironbark',
    icon: 'spell_druid_ironbark',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  IMPROVED_WILD_GROWTH_RESTORATION_TALENT: {
    id: 328025,
    name: 'Improved Wild Growth',
    icon: 'ability_druid_flourish',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  IMPROVED_REGROWTH_RESTORATION_TALENT: {
    id: 231032,
    name: 'Improved Regrowth',
    icon: 'spell_nature_resistnature',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  IMPROVED_IRONBARK_RESTORATION_TALENT: {
    id: 382552,
    name: 'Improved Ironbark',
    icon: 'spell_druid_ironbark',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  UNSTOPPABLE_GROWTH_RESTORATION_TALENT: {
    id: 340549,
    name: 'Unstoppable Growth',
    icon: 'ability_druid_flourish',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  TRANQUILITY_RESTORATION_TALENT: {
    id: 740,
    name: 'Tranquility',
    icon: 'spell_nature_tranquility',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  YSERAS_GIFT_RESTORATION_TALENT: {
    id: 145108,
    name: "Ysera's Gift",
    icon: 'inv_misc_head_dragon_green',
    maxRanks: 3,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  NOURISH_RESTORATION_TALENT: {
    id: 50464,
    name: 'Nourish',
    icon: 'ability_druid_nourish',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  SOUL_OF_THE_FOREST_RESTORATION_TALENT: {
    id: 158478,
    name: 'Soul of the Forest',
    icon: 'ability_druid_manatree',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  INNER_PEACE_RESTORATION_TALENT: {
    id: 197073,
    name: 'Inner Peace',
    icon: 'ability_druid_dreamstate',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  CULTIVATION_RESTORATION_TALENT: {
    id: 200390,
    name: 'Cultivation',
    icon: 'spell_nature_healingtouch',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  DEEP_ROOTS_RESTORATION_TALENT: {
    id: 383191,
    name: 'Deep Roots',
    icon: 'inv_misc_herb_liferoot_stem',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  ABUNDANCE_RESTORATION_TALENT: {
    id: 207383,
    name: 'Abundance',
    icon: 'ability_druid_empoweredrejuvination',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  CENARION_WARD_RESTORATION_TALENT: {
    id: 102351,
    name: 'Cenarion Ward',
    icon: 'ability_druid_naturalperfection',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
  },
  STONEBARK_RESTORATION_TALENT: {
    id: 197061,
    name: 'Stonebark',
    icon: 'spell_druid_ironbark',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  OVERGROWTH_RESTORATION_TALENT: {
    id: 203651,
    name: 'Overgrowth',
    icon: 'ability_druid_overgrowth',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  SPRING_BLOSSOMS_RESTORATION_TALENT: {
    id: 207385,
    name: 'Spring Blossoms',
    icon: 'inv_misc_trailofflowers',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  RAMPANT_GROWTH_RESTORATION_TALENT: {
    id: 278515,
    name: 'Rampant Growth',
    icon: 'spell_nature_resistnature',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  AUTUMN_LEAVES_NO_EXTENSION_RESTORATION_TALENT: {
    id: 274432,
    name: 'Autumn Leaves [no extension]',
    icon: 'spell_nature_rejuvenation',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  GROVE_TENDING_RESTORATION_TALENT: {
    id: 279778,
    name: 'Grove Tending',
    icon: 'inv_relics_idolofrejuvenation',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  MEMORY_OF_THE_MOTHER_TREE_RESTORATION_TALENT: {
    id: 339064,
    name: 'Memory of the Mother Tree',
    icon: 'spell_druid_rampantgrowth',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  GERMINATION_RESTORATION_TALENT: {
    id: 155675,
    name: 'Germination',
    icon: 'spell_druid_germination',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  ADAPTIVE_SWARM_RESTORATION_TALENT: {
    id: 325727,
    name: 'Adaptive Swarm',
    icon: 'ability_maldraxxus_druid',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  CONVOKE_THE_SPIRITS_RESTORATION_TALENT: {
    id: 323764,
    name: 'Convoke the Spirits',
    icon: 'ability_ardenweald_druid',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  INCARNATION_TREE_OF_LIFE_RESTORATION_TALENT: {
    id: 33891,
    name: 'Incarnation: Tree of Life',
    icon: 'ability_druid_improvedtreeform',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  IMPROVED_INNERVATE_RESTORATION_TALENT: {
    id: 326228,
    name: 'Improved Innervate',
    icon: 'spell_nature_lightning',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  CIRCLE_OF_LIFE_AND_DEATH_RESTORATION_TALENT: {
    id: 338657,
    name: 'Circle of Life and Death',
    icon: 'ability_druid_cyclone',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  THE_DARK_TITANS_LESSON_RESTORATION_TALENT: {
    id: 338831,
    name: "The Dark Titan's Lesson",
    icon: 'spell_druid_germination_rejuvenation',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  PHOTOSYNTHESIS_RESTORATION_TALENT: {
    id: 274902,
    name: 'Photosynthesis',
    icon: 'spell_lifegivingseed',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  UNBRIDLED_SWARM_RESTORATION_TALENT: {
    id: 354123,
    name: 'Unbridled Swarm',
    icon: 'ability_maldraxxus_druid',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  EPHEMERAL_INCARNATION_RESTORATION_TALENT: {
    id: 363495,
    name: 'Ephemeral Incarnation',
    icon: 'spell_progenitor_orb2',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  VERDANT_INFUSION_RESTORATION_TALENT: {
    id: 338829,
    name: 'Verdant Infusion',
    icon: 'inv_relics_totemoflife',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  FLOURISH_RESTORATION_TALENT: {
    id: 197721,
    name: 'Flourish',
    icon: 'spell_druid_wildburst',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  VISION_OF_UNENDING_GROWTH_RESTORATION_TALENT: {
    id: 338832,
    name: 'Vision of Unending Growth',
    icon: 'achievement_dungeon_everbloom',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
});

export default talents;
export { talents as TALENTS_DRUID };
