// Generated file, changes will eventually be overwritten!
import { createTalentList } from './types';

const talents = createTalentList({
  LANDSLIDE_TALENT: {
    id: 358385,
    name: 'Landslide',
    icon: 'ability_earthen_pillar',
    maxRanks: 1,
    entryIds: [87708],
    manaCost: 7000,
  },
  OBSIDIAN_SCALES_TALENT: {
    id: 363916,
    name: 'Obsidian Scales',
    icon: 'inv_artifact_dragonscales',
    maxRanks: 1,
    entryIds: [87702],
  },
  EXPUNGE_TALENT: {
    id: 365585,
    name: 'Expunge',
    icon: 'ability_evoker_fontofmagic_green',
    maxRanks: 1,
    entryIds: [87716],
    manaCost: 3250,
  },
  NATURAL_CONVERGENCE_TALENT: {
    id: 369913,
    name: 'Natural Convergence',
    icon: 'spell_frost_frostblast',
    maxRanks: 1,
    entryIds: [87709],
  },
  PERMEATING_CHILL_TALENT: {
    id: 370897,
    name: 'Permeating Chill',
    icon: 'spell_frost_coldhearted',
    maxRanks: 1,
    entryIds: [87703],
  },
  VERDANT_EMBRACE_TALENT: {
    id: 360995,
    name: 'Verdant Embrace',
    icon: 'ability_evoker_rescue',
    maxRanks: 1,
    entryIds: [87715],
    manaCost: 7500,
  },
  FORGER_OF_MOUNTAINS_TALENT: {
    id: 375528,
    name: 'Forger of Mountains',
    icon: 'ability_earthen_pillar',
    maxRanks: 1,
    entryIds: [87584],
  },
  INNATE_MAGIC_TALENT: {
    id: 375520,
    name: 'Innate Magic',
    icon: 'ability_evoker_innatemagic4',
    maxRanks: 2,
    entryIds: [87710],
  },
  OBSIDIAN_BULWARK_TALENT: {
    id: 375406,
    name: 'Obsidian Bulwark',
    icon: 'inv_shield_1h_revenantfire_d_01',
    maxRanks: 1,
    entryIds: [87701],
  },
  ENKINDLED_TALENT: {
    id: 375554,
    name: 'Enkindled',
    icon: 'ability_evoker_livingflame',
    maxRanks: 2,
    entryIds: [87704],
  },
  SCARLET_ADAPTATION_TALENT: {
    id: 372469,
    name: 'Scarlet Adaptation',
    icon: 'inv_bijou_red',
    maxRanks: 1,
    entryIds: [87714],
  },
  QUELL_TALENT: {
    id: 351338,
    name: 'Quell',
    icon: 'ability_evoker_quell',
    maxRanks: 1,
    entryIds: [87692],
  },
  RECALL_TALENT: {
    id: 371806,
    name: 'Recall',
    icon: 'ability_evoker_recall',
    maxRanks: 1,
    entryIds: [87711],
  },
  HEAVY_WINGBEATS_TALENT: {
    id: 368838,
    name: 'Heavy Wingbeats',
    icon: 'ability_racial_wingbuffet',
    maxRanks: 1,
    entryIds: [87586],
  },
  CLOBBERING_SWEEP_TALENT: {
    id: 375443,
    name: 'Clobbering Sweep',
    icon: 'ability_racial_tailswipe',
    maxRanks: 1,
    entryIds: [87585],
  },
  TAILWIND_TALENT: {
    id: 375556,
    name: 'Tailwind',
    icon: 'ability_skyreach_wind',
    maxRanks: 1,
    entryIds: [87705],
  },
  CAUTERIZING_FLAME_TALENT: {
    id: 374251,
    name: 'Cauterizing Flame',
    icon: 'ability_evoker_fontofmagic_red',
    maxRanks: 1,
    entryIds: [87700],
    manaCost: 3250,
  },
  ROAR_OF_EXHILARATION_TALENT: {
    id: 375507,
    name: 'Roar of Exhilaration',
    icon: 'ability_hunter_mastertactitian',
    maxRanks: 1,
    entryIds: [87691],
  },
  INSTINCTIVE_ARCANA_TALENT: {
    id: 376164,
    name: 'Instinctive Arcana',
    icon: 'spell_arcane_studentofmagic',
    maxRanks: 2,
    entryIds: [87693],
  },
  TIP_THE_SCALES_TALENT: {
    id: 370553,
    name: 'Tip the Scales',
    icon: 'ability_evoker_tipthescales',
    maxRanks: 1,
    entryIds: [87713],
  },
  ATTUNED_TO_THE_DREAM_TALENT: {
    id: 376930,
    name: 'Attuned to the Dream',
    icon: 'ability_rogue_imrovedrecuperate',
    maxRanks: 2,
    entryIds: [87699],
  },
  SLEEP_WALK_TALENT: {
    id: 360806,
    name: 'Sleep Walk',
    icon: 'ability_xavius_dreamsimulacrum',
    maxRanks: 1,
    entryIds: [87587],
    manaCost: 6000,
  },
  DRACONIC_LEGACY_TALENT: {
    id: 376166,
    name: 'Draconic Legacy',
    icon: 'inv_helm_mail_dracthyrquest_b_02',
    maxRanks: 2,
    entryIds: [87712],
  },
  INHERENT_RESISTANCE_TALENT: {
    id: 375544,
    name: 'Inherent Resistance',
    icon: 'inv_misc_rubysanctum1',
    maxRanks: 2,
    entryIds: [87697],
  },
  EXTENDED_FLIGHT_TALENT: {
    id: 375517,
    name: 'Extended Flight',
    icon: 'ability_evoker_hover',
    maxRanks: 2,
    entryIds: [87706],
  },
  BOUNTIFUL_BLOOM_TALENT: {
    id: 370886,
    name: 'Bountiful Bloom',
    icon: 'ability_evoker_emeraldblossom',
    maxRanks: 1,
    entryIds: [87588],
  },
  ANCIENT_FLAME_TALENT: {
    id: 369990,
    name: 'Ancient Flame',
    icon: 'inv_elemental_mote_fire01',
    maxRanks: 1,
    entryIds: [87698],
  },
  BLAST_FURNACE_TALENT: {
    id: 375510,
    name: 'Blast Furnace',
    icon: 'ability_evoker_firebreath',
    maxRanks: 2,
    entryIds: [87694],
  },
  EXUBERANCE_TALENT: {
    id: 375542,
    name: 'Exuberance',
    icon: 'ability_evoker_hover2',
    maxRanks: 1,
    entryIds: [87589],
  },
  SOURCE_OF_MAGIC_TALENT: {
    id: 369459,
    name: 'Source of Magic',
    icon: 'ability_evoker_blue_01',
    maxRanks: 1,
    entryIds: [87696],
  },
  WALLOPING_BLOW_TALENT: {
    id: 387341,
    name: 'Walloping Blow',
    icon: 'inv_misc_monsterscales_06',
    maxRanks: 1,
    entryIds: [87684],
  },
  PANACEA_TALENT: {
    id: 387761,
    name: 'Panacea',
    icon: 'ability_druid_protectionofthegrove',
    maxRanks: 1,
    entryIds: [87707],
  },
  UNRAVEL_TALENT: {
    id: 368432,
    name: 'Unravel',
    icon: 'ability_evoker_unravel',
    maxRanks: 1,
    entryIds: [87690],
    manaCost: 2500,
  },
  PROTRACTED_TALONS_TALENT: {
    id: 369909,
    name: 'Protracted Talons',
    icon: 'ability_evoker_azurestrike',
    maxRanks: 1,
    entryIds: [87688],
  },
  OPPRESSING_ROAR_TALENT: {
    id: 372048,
    name: 'Oppressing Roar',
    icon: 'ability_evoker_oppressingroar',
    maxRanks: 1,
    entryIds: [87695],
  },
  REGENERATIVE_MAGIC_TALENT: {
    id: 387787,
    name: 'Regenerative Magic',
    icon: 'spell_frost_manarecharge',
    maxRanks: 1,
    entryIds: [87677],
  },
  RESCUE_TALENT: {
    id: 370665,
    name: 'Rescue',
    icon: 'ability_evoker_flywithme',
    maxRanks: 1,
    entryIds: [87685],
  },
  LUSH_GROWTH_TALENT: {
    id: 375561,
    name: 'Lush Growth',
    icon: 'inv_staff_2h_bloodelf_c_01',
    maxRanks: 2,
    entryIds: [87678],
  },
  RENEWING_BLAZE_TALENT: {
    id: 374348,
    name: 'Renewing Blaze',
    icon: 'ability_evoker_masterylifebinder_red',
    maxRanks: 1,
    entryIds: [87679],
  },
  LEAPING_FLAMES_TALENT: {
    id: 369939,
    name: 'Leaping Flames',
    icon: 'spell_fire_flare',
    maxRanks: 1,
    entryIds: [87689],
  },
  OVERAWE_TALENT: {
    id: 374346,
    name: 'Overawe',
    icon: 'ability_evoker_oppressingroar2',
    maxRanks: 1,
    entryIds: [87687],
  },
  AERIAL_MASTERY_TALENT: {
    id: 365933,
    name: 'Aerial Mastery',
    icon: 'ability_evoker_aerialmastery',
    maxRanks: 1,
    entryIds: [87686],
  },
  TWIN_GUARDIAN_TALENT: {
    id: 370888,
    name: 'Twin Guardian',
    icon: 'ability_skyreach_shielded',
    maxRanks: 1,
    entryIds: [87683],
  },
  FOCI_OF_LIFE_TALENT: {
    id: 375574,
    name: 'Foci of Life',
    icon: 'spell_fire_incinerate',
    maxRanks: 1,
    entryIds: [87681],
  },
  FIRE_WITHIN_TALENT: {
    id: 375577,
    name: 'Fire Within',
    icon: 'item_sparkofragnoros',
    maxRanks: 1,
    entryIds: [87680],
  },
  TERROR_OF_THE_SKIES_TALENT: {
    id: 371032,
    name: 'Terror of the Skies',
    icon: 'ability_evoker_terroroftheskies',
    maxRanks: 1,
    entryIds: [87675],
  },
  TIME_SPIRAL_TALENT: {
    id: 374968,
    name: 'Time Spiral',
    icon: 'ability_evoker_timespiral',
    maxRanks: 1,
    entryIds: [87676],
  },
  ZEPHYR_TALENT: {
    id: 374227,
    name: 'Zephyr',
    icon: 'ability_evoker_hoverblack',
    maxRanks: 1,
    entryIds: [87682],
  },
  PYRE_TALENT: {
    id: 357211,
    name: 'Pyre',
    icon: 'ability_evoker_pyre',
    maxRanks: 1,
    entryIds: [87669],
    essenceCost: 3,
  },
  RUBY_ESSENCE_BURST_TALENT: {
    id: 376872,
    name: 'Ruby Essence Burst',
    icon: 'ability_evoker_essenceburst4',
    maxRanks: 1,
    entryIds: [87670],
  },
  AZURE_ESSENCE_BURST_TALENT: {
    id: 375721,
    name: 'Azure Essence Burst',
    icon: 'ability_evoker_essenceburst2',
    maxRanks: 1,
    entryIds: [87668],
  },
  DENSE_ENERGY_TALENT: {
    id: 370962,
    name: 'Dense Energy',
    icon: 'ability_evoker_pyre',
    maxRanks: 1,
    entryIds: [87671],
  },
  IMPOSING_PRESENCE_TALENT: {
    id: 371016,
    name: 'Imposing Presence',
    icon: 'ability_evoker_quell',
    maxRanks: 1,
    entryIds: [87667],
  },
  INNER_RADIANCE_TALENT: {
    id: 386405,
    name: 'Inner Radiance',
    icon: 'spell_holy_spellwarding',
    maxRanks: 1,
    entryIds: [87666],
  },
  ETERNITY_SURGE_TALENT: {
    id: 359073,
    name: 'Eternity Surge',
    icon: 'ability_evoker_eternitysurge',
    maxRanks: 1,
    entryIds: [87647],
  },
  VOLATILITY_TALENT: {
    id: 369089,
    name: 'Volatility',
    icon: 'spell_fire_ragnaros_lavabolt',
    maxRanks: 2,
    entryIds: [87672],
  },
  POWER_NEXUS_TALENT: {
    id: 369908,
    name: 'Power Nexus',
    icon: 'ability_evoker_powernexus',
    maxRanks: 1,
    entryIds: [87590, 87598],
  },
  DRAGONRAGE_TALENT: {
    id: 375087,
    name: 'Dragonrage',
    icon: 'ability_evoker_dragonrage',
    maxRanks: 1,
    entryIds: [87665],
  },
  LAY_WASTE_TALENT: {
    id: 371034,
    name: 'Lay Waste',
    icon: 'ability_evoker_deepbreath',
    maxRanks: 2,
    entryIds: [87648],
  },
  ARCANE_INTENSITY_TALENT: {
    id: 375618,
    name: 'Arcane Intensity',
    icon: 'ability_evoker_disintegrate',
    maxRanks: 2,
    entryIds: [87646],
  },
  RUBY_EMBERS_TALENT: {
    id: 365937,
    name: 'Ruby Embers',
    icon: 'inv_tradeskillitem_lessersorcerersfire',
    maxRanks: 1,
    entryIds: [87674],
  },
  ENGULFING_BLAZE_TALENT: {
    id: 370837,
    name: 'Engulfing Blaze',
    icon: 'inv_inscription_pigment_ruby',
    maxRanks: 1,
    entryIds: [87673],
  },
  ANIMOSITY_TALENT: {
    id: 375797,
    name: 'Animosity',
    icon: 'spell_nature_shamanrage',
    maxRanks: 1,
    entryIds: [87664],
  },
  ESSENCE_ATTUNEMENT_TALENT: {
    id: 375722,
    name: 'Essence Attunement',
    icon: 'ability_evoker_essenceburststacks',
    maxRanks: 1,
    entryIds: [87649, 87631],
  },
  FIRESTORM_TALENT: {
    id: 368847,
    name: 'Firestorm',
    icon: 'ability_evoker_firestorm',
    maxRanks: 1,
    entryIds: [87659],
  },
  HEAT_WAVE_TALENT: {
    id: 375725,
    name: 'Heat Wave',
    icon: 'spell_fire_moltenblood',
    maxRanks: 2,
    entryIds: [87661],
  },
  TITANIC_WRATH_TALENT: {
    id: 386272,
    name: 'Titanic Wrath',
    icon: 'spell_fireresistancetotem_01',
    maxRanks: 2,
    entryIds: [87663],
  },
  HONED_AGGRESSION_TALENT: {
    id: 371038,
    name: 'Honed Aggression',
    icon: 'spell_fire_blueimmolation',
    maxRanks: 2,
    entryIds: [87650],
  },
  ETERNITYS_SPAN_TALENT: {
    id: 375757,
    name: "Eternity's Span",
    icon: 'spell_arcane_arcanetorrent',
    maxRanks: 1,
    entryIds: [87645],
  },
  EYE_OF_INFINITY_TALENT: {
    id: 369375,
    name: 'Eye of Infinity',
    icon: 'ability_socererking_arcanewrath',
    maxRanks: 1,
    entryIds: [87640],
  },
  CAUSALITY_TALENT: {
    id: 375777,
    name: 'Causality',
    icon: 'spell_azerite_essence_16',
    maxRanks: 1,
    entryIds: [87639],
  },
  CATALYZE_TALENT: {
    id: 386283,
    name: 'Catalyze',
    icon: 'spell_fire_masterofelements',
    maxRanks: 1,
    entryIds: [87660],
  },
  TYRANNY_TALENT: {
    id: 376888,
    name: 'Tyranny',
    icon: 'ability_evoker_dragonrage2',
    maxRanks: 1,
    entryIds: [87662],
  },
  CHARGED_BLAST_TALENT: {
    id: 370455,
    name: 'Charged Blast',
    icon: 'spell_arcane_arcanepotency',
    maxRanks: 1,
    entryIds: [87651],
  },
  SHATTERING_STAR_TALENT: {
    id: 370452,
    name: 'Shattering Star',
    icon: 'ability_evoker_chargedblast',
    maxRanks: 1,
    entryIds: [87641],
  },
  SNAPFIRE_TALENT: {
    id: 370783,
    name: 'Snapfire',
    icon: 'spell_shaman_improvedfirenova',
    maxRanks: 1,
    entryIds: [87658],
  },
  FONT_OF_MAGIC_TALENT: {
    id: 375783,
    name: 'Font of Magic',
    icon: 'ability_evoker_fontofmagic',
    maxRanks: 1,
    entryIds: [87656, 87596],
  },
  ONYX_LEGACY_TALENT: {
    id: 386348,
    name: 'Onyx Legacy',
    icon: 'inv_misc_head_dragon_black',
    maxRanks: 1,
    entryIds: [87654],
  },
  SPELLWEAVERS_DOMINANCE_TALENT: {
    id: 370845,
    name: "Spellweaver's Dominance",
    icon: 'spell_shaman_shockinglava',
    maxRanks: 1,
    entryIds: [87652],
  },
  FOCUSING_IRIS_TALENT: {
    id: 386336,
    name: 'Focusing Iris',
    icon: 'spell_mage_temporalshield',
    maxRanks: 1,
    entryIds: [87643],
  },
  ARCANE_VIGOR_TALENT: {
    id: 386342,
    name: 'Arcane Vigor',
    icon: 'spell_arcane_arcane01',
    maxRanks: 1,
    entryIds: [87642],
  },
  BURNOUT_TALENT: {
    id: 375801,
    name: 'Burnout',
    icon: 'spell_fire_soulburn',
    maxRanks: 2,
    entryIds: [87657],
  },
  IMMINENT_DESTRUCTION_TALENT: {
    id: 370781,
    name: 'Imminent Destruction',
    icon: 'spell_burningbladeshaman_blazing_radiance',
    maxRanks: 2,
    entryIds: [87655],
  },
  SCINTILLATION_TALENT: {
    id: 370821,
    name: 'Scintillation',
    icon: 'spell_arcane_arcane03',
    maxRanks: 2,
    entryIds: [87653],
  },
  POWER_SWELL_TALENT: {
    id: 370839,
    name: 'Power Swell',
    icon: 'ability_evoker_powernexus2',
    maxRanks: 2,
    entryIds: [87644],
  },
  FEED_THE_FLAMES_TALENT: {
    id: 369846,
    name: 'Feed the Flames',
    icon: 'mace_1h_blacksmithing_d_04_icon',
    maxRanks: 1,
    entryIds: [87637],
  },
  EVERBURNING_FLAME_TALENT: {
    id: 370819,
    name: 'Everburning Flame',
    icon: 'spell_fire_burnout',
    maxRanks: 1,
    entryIds: [87636],
  },
  HOARDED_POWER_TALENT: {
    id: 375796,
    name: 'Hoarded Power',
    icon: 'ability_evoker_innatemagic2',
    maxRanks: 1,
    entryIds: [87591],
  },
  IRIDESCENCE_TALENT: {
    id: 370867,
    name: 'Iridescence',
    icon: 'ability_evoker_powerswell',
    maxRanks: 1,
    entryIds: [87638],
  },
  ECHO_TALENT: {
    id: 364343,
    name: 'Echo',
    icon: 'ability_evoker_echo',
    maxRanks: 1,
    entryIds: [87628],
    essenceCost: 2,
  },
  DREAM_BREATH_TALENT: {
    id: 355936,
    name: 'Dream Breath',
    icon: 'ability_evoker_dreambreath',
    maxRanks: 1,
    entryIds: [87627],
    manaCost: 11250,
  },
  REVERSION_TALENT: {
    id: 366155,
    name: 'Reversion',
    icon: 'ability_evoker_reversion',
    maxRanks: 1,
    entryIds: [87629],
    manaCost: 6250,
  },
  TEMPORAL_COMPRESSION_TALENT: {
    id: 362874,
    name: 'Temporal Compression',
    icon: 'ability_evoker_rewind2',
    maxRanks: 1,
    entryIds: [87626],
  },
  ESSENCE_BURST_TALENT: {
    id: 369297,
    name: 'Essence Burst',
    icon: 'ability_evoker_essenceburst',
    maxRanks: 1,
    entryIds: [87630],
  },
  REWIND_TALENT: {
    id: 363534,
    name: 'Rewind',
    icon: 'ability_evoker_rewind',
    maxRanks: 1,
    entryIds: [87612],
    manaCost: 12500,
  },
  SPIRITBLOOM_TALENT: {
    id: 367226,
    name: 'Spiritbloom',
    icon: 'ability_evoker_spiritbloom2',
    maxRanks: 1,
    entryIds: [87625],
    manaCost: 9500,
  },
  TIME_DILATION_TALENT: {
    id: 357170,
    name: 'Time Dilation',
    icon: 'ability_evoker_timedilation',
    maxRanks: 1,
    entryIds: [87613],
    manaCost: 5000,
  },
  EMERALD_COMMUNION_TALENT: {
    id: 370960,
    name: 'Emerald Communion',
    icon: 'ability_evoker_green_01',
    maxRanks: 1,
    entryIds: [87594],
  },
  EMPATH_TALENT: {
    id: 376138,
    name: 'Empath',
    icon: 'ability_evoker_powernexus2',
    maxRanks: 1,
    entryIds: [87624],
  },
  SPIRITUAL_CLARITY_TALENT: {
    id: 376150,
    name: 'Spiritual Clarity',
    icon: 'ability_evoker_spiritbloom',
    maxRanks: 1,
    entryIds: [87623],
  },
  FLUTTERING_SEEDLINGS_TALENT: {
    id: 359793,
    name: 'Fluttering Seedlings',
    icon: 'inv_herbalism_70_yserallineseed',
    maxRanks: 2,
    entryIds: [87632],
  },
  LIFE_GIVERS_FLAME_TALENT: {
    id: 371426,
    name: "Life-Giver's Flame",
    icon: 'item_sparkofragnoros',
    maxRanks: 2,
    entryIds: [87616],
  },
  GOLDEN_HOUR_TALENT: {
    id: 378196,
    name: 'Golden Hour',
    icon: 'inv_belt_armor_waistoftime_d_01',
    maxRanks: 1,
    entryIds: [87614],
  },
  DELAY_HARM_TALENT: {
    id: 376207,
    name: 'Delay Harm',
    icon: 'ability_racial_magicalresistance',
    maxRanks: 1,
    entryIds: [87602],
  },
  JUST_IN_TIME_TALENT: {
    id: 376204,
    name: 'Just in Time',
    icon: 'inv_offhand_1h_artifactsilverhand_d_01',
    maxRanks: 1,
    entryIds: [87601],
  },
  TEMPORAL_ANOMALY_TALENT: {
    id: 373861,
    name: 'Temporal Anomaly',
    icon: 'ability_evoker_temporalanomaly',
    maxRanks: 1,
    entryIds: [87611],
    manaCost: 18750,
  },
  DREAMWALKER_TALENT: {
    id: 377082,
    name: 'Dreamwalker',
    icon: 'ability_hunter_onewithnature',
    maxRanks: 1,
    entryIds: [87593],
  },
  RUSH_OF_VITALITY_TALENT: {
    id: 377086,
    name: 'Rush of Vitality',
    icon: 'trade_enchanting_greatermysteriousessence',
    maxRanks: 1,
    entryIds: [87592],
  },
  EXHILARATING_BURST_TALENT: {
    id: 377100,
    name: 'Exhilarating Burst',
    icon: 'ability_evoker_essenceburst3',
    maxRanks: 2,
    entryIds: [87595],
  },
  FIELD_OF_DREAMS_TALENT: {
    id: 370062,
    name: 'Field of Dreams',
    icon: 'inv_misc_herb_chamlotus',
    maxRanks: 1,
    entryIds: [87633],
  },
  LIFEFORCE_MENDER_TALENT: {
    id: 376179,
    name: 'Lifeforce Mender',
    icon: 'ability_evoker_dragonrage2',
    maxRanks: 2,
    entryIds: [87617],
  },
  TIME_LORD_TALENT: {
    id: 372527,
    name: 'Time Lord',
    icon: 'ability_evoker_innatemagic4',
    maxRanks: 2,
    entryIds: [87615],
  },
  FLOW_STATE_TALENT: {
    id: 385696,
    name: 'Flow State',
    icon: 'ability_evoker_timespiral',
    maxRanks: 2,
    entryIds: [87610],
  },
  RESONATING_SPHERE_TALENT: {
    id: 376236,
    name: 'Resonating Sphere',
    icon: 'ability_evoker_bronze_01',
    maxRanks: 1,
    entryIds: [87609],
  },
  NOZDORMUS_TEACHINGS_TALENT: {
    id: 376237,
    name: "Nozdormu's Teachings",
    icon: 'inv_misc_head_dragon_bronze',
    maxRanks: 1,
    entryIds: [87608],
  },
  CALL_OF_YSERA_TALENT: {
    id: 373834,
    name: 'Call of Ysera',
    icon: '',
    maxRanks: 1,
    entryIds: [87618],
  },
  LIFEBIND_TALENT: {
    id: 373270,
    name: 'Lifebind',
    icon: 'ability_evoker_hoverred',
    maxRanks: 1,
    entryIds: [87634],
  },
  PUNCTUALITY_TALENT: {
    id: 371270,
    name: 'Punctuality',
    icon: 'inv_offhand_1h_ulduarraid_d_01',
    maxRanks: 1,
    entryIds: [87607],
  },
  SPARK_OF_INSIGHT_TALENT: {
    id: 377099,
    name: 'Spark of Insight',
    icon: 'ability_evoker_essenceburst5',
    maxRanks: 1,
    entryIds: [87635],
  },
  OUROBOROS_TALENT: {
    id: 381921,
    name: 'Ouroboros',
    icon: 'ability_evoker_innatemagic',
    maxRanks: 1,
    entryIds: [87600],
  },
  ERASURE_TALENT: {
    id: 376210,
    name: 'Erasure',
    icon: 'ability_bossmagistrix_timewarp2',
    maxRanks: 1,
    entryIds: [87620],
  },
  TEMPORAL_ARTIFICER_TALENT: {
    id: 381922,
    name: 'Temporal Artificer',
    icon: 'ability_evoker_rewind',
    maxRanks: 1,
    entryIds: [87619],
  },
  ENERGY_LOOP_TALENT: {
    id: 372233,
    name: 'Energy Loop',
    icon: 'inv_elemental_mote_mana',
    maxRanks: 1,
    entryIds: [87606],
  },
  TIME_OF_NEED_TALENT: {
    id: 368412,
    name: 'Time of Need',
    icon: 'ability_evoker_masterylifebinder_bronze',
    maxRanks: 1,
    entryIds: [87604],
  },
  RENEWING_BREATH_TALENT: {
    id: 371257,
    name: 'Renewing Breath',
    icon: 'ability_evoker_dreambreath',
    maxRanks: 2,
    entryIds: [87599],
  },
  GRACE_PERIOD_TALENT: {
    id: 376239,
    name: 'Grace Period',
    icon: 'ability_evoker_reversion_green',
    maxRanks: 2,
    entryIds: [87621],
  },
  TIMELESS_MAGIC_TALENT: {
    id: 376240,
    name: 'Timeless Magic',
    icon: 'inv_artifact_xp05',
    maxRanks: 2,
    entryIds: [87605],
  },
  DREAM_FLIGHT_TALENT: {
    id: 359816,
    name: 'Dream Flight',
    icon: 'ability_evoker_dreamflight',
    maxRanks: 1,
    entryIds: [87597],
    manaCost: 10000,
  },
  CYCLE_OF_LIFE_TALENT: {
    id: 371832,
    name: 'Cycle of Life',
    icon: 'spell_lifegivingseed',
    maxRanks: 1,
    entryIds: [87622],
  },
  STASIS_TALENT: {
    id: 370537,
    name: 'Stasis',
    icon: 'ability_evoker_stasis',
    maxRanks: 1,
    entryIds: [87603],
    manaCost: 10000,
  },
});

export default talents;
export { talents as TALENTS_EVOKER };
