// Generated file, changes will eventually be overwritten!
import { createTalentList } from './types';

const talents = createTalentList({
  ACCUMULATIVE_SHIELDING_TALENT: {
    id: 382800,
    name: 'Accumulative Shielding',
    icon: 'ability_mage_shattershield',
    maxRanks: 1,
    entryIds: [80149],
    definitionIds: [{ id: 85152, specId: 62 }],
  },
  ALEXSTRASZAS_FURY_TALENT: {
    id: 235870,
    name: "Alexstrasza's Fury",
    icon: 'spell_warrior_dragoncharge',
    maxRanks: 1,
    entryIds: [80288],
    definitionIds: [{ id: 85291, specId: 63 }],
  },
  ALTER_TIME_TALENT: {
    id: 342245,
    name: 'Alter Time',
    icon: 'spell_mage_altertime',
    maxRanks: 1,
    entryIds: [80174],
    definitionIds: [{ id: 85177, specId: 62 }],
    manaCost: 2500,
  },
  AMPLIFICATION_TALENT: {
    id: 236628,
    name: 'Amplification',
    icon: 'spell_arcane_invocation',
    maxRanks: 1,
    entryIds: [80294],
    definitionIds: [{ id: 85297, specId: 62 }],
  },
  ARCANE_BOMBARDMENT_TALENT: {
    id: 384581,
    name: 'Arcane Bombardment',
    icon: 'ability_socererking_arcanereplication',
    maxRanks: 1,
    entryIds: [80303],
    definitionIds: [{ id: 85306, specId: 62 }],
  },
  ARCANE_ECHO_TALENT: {
    id: 342231,
    name: 'Arcane Echo',
    icon: 'ability_socererking_arcanewrath',
    maxRanks: 1,
    entryIds: [80191],
    definitionIds: [{ id: 85194, specId: 62 }],
  },
  ARCANE_FAMILIAR_TALENT: {
    id: 205022,
    name: 'Arcane Familiar',
    icon: 'ability_socererking_arcanemines',
    maxRanks: 1,
    entryIds: [80207],
    definitionIds: [{ id: 85210, specId: 62 }],
  },
  ARCANE_HARMONY_TALENT: {
    id: 384452,
    name: 'Arcane Harmony',
    icon: 'ability_creature_cursed_04',
    maxRanks: 1,
    entryIds: [80195],
    definitionIds: [{ id: 85198, specId: 62 }],
  },
  ARCANE_MISSILES_TALENT: {
    id: 5143,
    name: 'Arcane Missiles',
    icon: 'spell_nature_starfall',
    maxRanks: 1,
    entryIds: [80307],
    definitionIds: [{ id: 85310, specId: 62 }],
    manaCost: 37500,
  },
  ARCANE_ORB_TALENT: {
    id: 153626,
    name: 'Arcane Orb',
    icon: 'spell_mage_arcaneorb',
    maxRanks: 1,
    entryIds: [80308],
    definitionIds: [{ id: 85311, specId: 62 }],
    manaCost: 2500,
  },
  ARCANE_SURGE_TALENT: {
    id: 365350,
    name: 'Arcane Surge',
    icon: 'ability_mage_arcanesurge',
    maxRanks: 1,
    entryIds: [80299],
    definitionIds: [{ id: 85302, specId: 62 }],
    manaCost: 1,
  },
  ARCANE_TEMPO_TALENT: {
    id: 383980,
    name: 'Arcane Tempo',
    icon: 'ability_socererking_arcaneacceleration',
    maxRanks: 1,
    entryIds: [80205],
    definitionIds: [{ id: 85208, specId: 62 }],
  },
  ARCANE_WARDING_TALENT: {
    id: 383092,
    name: 'Arcane Warding',
    icon: 'spell_arcane_arcaneresilience',
    maxRanks: 2,
    entryIds: [80173],
    definitionIds: [{ id: 85176, specId: 62 }],
  },
  ARCING_CLEAVE_TALENT: {
    id: 231564,
    name: 'Arcing Cleave',
    icon: 'ability_mage_arcanebarrage',
    maxRanks: 1,
    entryIds: [80201],
    definitionIds: [{ id: 85204, specId: 62 }],
  },
  BLAST_WAVE_TALENT: {
    id: 157981,
    name: 'Blast Wave',
    icon: 'spell_holy_excorcism_02',
    maxRanks: 1,
    entryIds: [80160],
    definitionIds: [{ id: 85163, specId: 62 }],
  },
  BLAZING_BARRIER_TALENT: {
    id: 235313,
    name: 'Blazing Barrier',
    icon: 'ability_mage_moltenarmor',
    maxRanks: 1,
    entryIds: [80178],
    definitionIds: [{ id: 85181, specId: 63 }],
    manaCost: 7500,
  },
  BONE_CHILLING_TALENT: {
    id: 205027,
    name: 'Bone Chilling',
    icon: 'ability_mage_chilledtothebone',
    maxRanks: 1,
    entryIds: [80230],
    definitionIds: [{ id: 85233, specId: 64 }],
  },
  BRAIN_FREEZE_TALENT: {
    id: 190447,
    name: 'Brain Freeze',
    icon: 'ability_mage_brainfreeze',
    maxRanks: 1,
    entryIds: [80244],
    definitionIds: [{ id: 85247, specId: 64 }],
  },
  CALL_OF_THE_SUN_KING_TALENT: {
    id: 343222,
    name: 'Call of the Sun King',
    icon: 'artifactability_firemage_phoenixbolt',
    maxRanks: 1,
    entryIds: [80278],
    definitionIds: [{ id: 85281, specId: 63 }],
  },
  CASCADING_POWER_TALENT: {
    id: 384276,
    name: 'Cascading Power',
    icon: 'inv_misc_gem_sapphire_02',
    maxRanks: 1,
    entryIds: [80193],
    definitionIds: [{ id: 85196, specId: 62 }],
  },
  CHAIN_REACTION_TALENT: {
    id: 278309,
    name: 'Chain Reaction',
    icon: 'spell_frost_frostblast',
    maxRanks: 1,
    entryIds: [80226],
    definitionIds: [{ id: 85229, specId: 64 }],
  },
  CHARGED_ORB_TALENT: {
    id: 384651,
    name: 'Charged Orb',
    icon: 'spell_mage_arcaneorb',
    maxRanks: 1,
    entryIds: [80310],
    definitionIds: [{ id: 85313, specId: 62 }],
  },
  CHRONO_SHIFT_TALENT: {
    id: 235711,
    name: 'Chrono Shift',
    icon: 'ability_monk_deadlyreach',
    maxRanks: 1,
    entryIds: [80202],
    definitionIds: [{ id: 85205, specId: 62 }],
  },
  COLDEST_SNAP_TALENT: {
    id: 417493,
    name: 'Coldest Snap',
    icon: 'spell_frost_wizardmark',
    maxRanks: 1,
    entryIds: [80218],
    definitionIds: [{ id: 85221, specId: 64 }],
  },
  COLD_FRONT_TALENT: {
    id: 382110,
    name: 'Cold Front',
    icon: 'ability_mage_coldasice',
    maxRanks: 1,
    entryIds: [80251],
    definitionIds: [{ id: 85254, specId: 64 }],
  },
  COMBUSTION_TALENT: {
    id: 190319,
    name: 'Combustion',
    icon: 'spell_fire_sealoffire',
    maxRanks: 1,
    entryIds: [80275],
    definitionIds: [{ id: 85278, specId: 63 }],
    manaCost: 25000,
  },
  COMET_STORM_TALENT: {
    id: 153595,
    name: 'Comet Storm',
    icon: 'spell_mage_cometstorm2',
    maxRanks: 1,
    entryIds: [80248],
    definitionIds: [{ id: 85251, specId: 64 }],
    manaCost: 2500,
  },
  CONCENTRATED_POWER_TALENT: {
    id: 414379,
    name: 'Concentrated Power',
    icon: 'spell_mage_overpowered',
    maxRanks: 1,
    entryIds: [80298],
    definitionIds: [{ id: 85301, specId: 62 }],
  },
  CONCENTRATION_TALENT: {
    id: 384374,
    name: 'Concentration',
    icon: 'ability_mage_potentspirit',
    maxRanks: 1,
    entryIds: [80194],
    definitionIds: [{ id: 85197, specId: 62 }],
  },
  CONFLAGRATION_TALENT: {
    id: 205023,
    name: 'Conflagration',
    icon: 'spell_shaman_firenova',
    maxRanks: 1,
    entryIds: [80262],
    definitionIds: [{ id: 85265, specId: 63 }],
  },
  CONJURE_MANA_GEM_TALENT: {
    id: 759,
    name: 'Conjure Mana Gem',
    icon: 'inv_misc_gem_sapphire_02',
    maxRanks: 1,
    entryIds: [80192],
    definitionIds: [{ id: 85195, specId: 62 }],
    manaCost: 45000,
  },
  CONTROLLED_DESTRUCTION_TALENT: {
    id: 383669,
    name: 'Controlled Destruction',
    icon: 'spell_fire_playingwithfire',
    maxRanks: 2,
    entryIds: [80272],
    definitionIds: [{ id: 85275, specId: 63 }],
  },
  CONVECTION_TALENT: {
    id: 416715,
    name: 'Convection',
    icon: 'spell_fire_lavaspawn',
    maxRanks: 1,
    entryIds: [80254],
    definitionIds: [{ id: 85257, specId: 63 }],
  },
  CRACKLING_ENERGY_TALENT: {
    id: 321752,
    name: 'Crackling Energy',
    icon: 'spell_nature_wispsplode',
    maxRanks: 2,
    entryIds: [80297],
    definitionIds: [{ id: 85300, specId: 62 }],
  },
  CRITICAL_MASS_TALENT: {
    id: 117216,
    name: 'Critical Mass',
    icon: 'spell_fire_volcano',
    maxRanks: 2,
    entryIds: [80287],
    definitionIds: [{ id: 85290, specId: 63 }],
  },
  CRYOPATHY_TALENT: {
    id: 417491,
    name: 'Cryopathy',
    icon: 'ability_hunter_pointofnoescape',
    maxRanks: 1,
    entryIds: [80215],
    definitionIds: [{ id: 85218, specId: 64 }],
  },
  CRYO_FREEZE_TALENT: {
    id: 382292,
    name: 'Cryo-Freeze',
    icon: 'spell_frost_icefloes',
    maxRanks: 2,
    entryIds: [80165],
    definitionIds: [{ id: 85168, specId: 62 }],
  },
  DEEP_IMPACT_TALENT: {
    id: 416719,
    name: 'Deep Impact',
    icon: 'spell_fire_moltenblood',
    maxRanks: 1,
    entryIds: [80252],
    definitionIds: [{ id: 85255, specId: 63 }],
  },
  DEEP_SHATTER_TALENT: {
    id: 378749,
    name: 'Deep Shatter',
    icon: 'inv_misc_frostemblem_01',
    maxRanks: 2,
    entryIds: [80222],
    definitionIds: [{ id: 85225, specId: 64 }],
  },
  DISPLACEMENT_TALENT: {
    id: 389713,
    name: 'Displacement',
    icon: 'ability_hunter_displacement',
    maxRanks: 1,
    entryIds: [80152],
    definitionIds: [{ id: 85155, specId: 62 }],
  },
  DIVERTED_ENERGY_TALENT: {
    id: 382270,
    name: 'Diverted Energy',
    icon: 'inv_soulbarrier',
    maxRanks: 2,
    entryIds: [80158],
    definitionIds: [{ id: 85161, specId: 62 }],
  },
  DRAGONS_BREATH_TALENT: {
    id: 31661,
    name: "Dragon's Breath",
    icon: 'inv_misc_head_dragon_01',
    maxRanks: 1,
    entryIds: [80147],
    definitionIds: [{ id: 85150, specId: 62 }],
    manaCost: 10000,
  },
  ENERGIZED_BARRIERS_TALENT: {
    id: 386828,
    name: 'Energized Barriers',
    icon: 'spell_mage_temporalshield',
    maxRanks: 1,
    entryIds: [80157],
    definitionIds: [{ id: 85160, specId: 62 }],
  },
  ENLIGHTENED_TALENT: {
    id: 321387,
    name: 'Enlightened',
    icon: 'ability_socererking_arcanefortification',
    maxRanks: 1,
    entryIds: [80204],
    definitionIds: [{ id: 85207, specId: 62 }],
  },
  EVERLASTING_FROST_TALENT: {
    id: 385167,
    name: 'Everlasting Frost',
    icon: 'spell_frost_chillingbolt',
    maxRanks: 1,
    entryIds: [102429],
    definitionIds: [{ id: 107434, specId: 64 }],
  },
  EVOCATION_TALENT: {
    id: 12051,
    name: 'Evocation',
    icon: 'spell_nature_purge',
    maxRanks: 1,
    entryIds: [80209],
    definitionIds: [{ id: 85212, specId: 62 }],
  },
  FEEL_THE_BURN_TALENT: {
    id: 383391,
    name: 'Feel the Burn',
    icon: 'spell_fire_fireball',
    maxRanks: 1,
    entryIds: [80261],
    definitionIds: [{ id: 85264, specId: 63 }],
  },
  FERVENT_FLICKERING_TALENT: {
    id: 387044,
    name: 'Fervent Flickering',
    icon: 'ability_warlock_burningembers',
    maxRanks: 1,
    entryIds: [80286],
    definitionIds: [{ id: 85289, specId: 63 }],
  },
  FEVERED_INCANTATION_TALENT: {
    id: 383810,
    name: 'Fevered Incantation',
    icon: 'inv_misc_enchantedpearld',
    maxRanks: 1,
    entryIds: [80277],
    definitionIds: [{ id: 85280, specId: 63 }],
  },
  FIERY_RUSH_TALENT: {
    id: 383634,
    name: 'Fiery Rush',
    icon: 'inv_summerfest_firespirit',
    maxRanks: 1,
    entryIds: [80271],
    definitionIds: [{ id: 85274, specId: 63 }],
  },
  FINGERS_OF_FROST_TALENT: {
    id: 112965,
    name: 'Fingers of Frost',
    icon: 'ability_mage_wintersgrasp',
    maxRanks: 1,
    entryIds: [80227],
    definitionIds: [{ id: 85230, specId: 64 }],
  },
  FIREFALL_TALENT: {
    id: 384033,
    name: 'Firefall',
    icon: 'ability_ironmaidens_rapidfire',
    maxRanks: 1,
    entryIds: [80264],
    definitionIds: [{ id: 85267, specId: 63 }],
  },
  FIREMIND_TALENT: {
    id: 383499,
    name: 'Firemind',
    icon: 'spell_burningsoul',
    maxRanks: 1,
    entryIds: [80276],
    definitionIds: [{ id: 85279, specId: 63 }],
  },
  FIRESTARTER_TALENT: {
    id: 205026,
    name: 'Firestarter',
    icon: 'spell_fire_fire',
    maxRanks: 1,
    entryIds: [80139],
    definitionIds: [{ id: 85142, specId: 63 }],
  },
  FIRE_BLAST_TALENT: {
    id: 108853,
    name: 'Fire Blast',
    icon: 'spell_fire_fireball',
    maxRanks: 1,
    entryIds: [80282],
    definitionIds: [{ id: 85285, specId: 63 }],
    manaCost: 2500,
  },
  FLAME_ACCELERANT_TALENT: {
    id: 203275,
    name: 'Flame Accelerant',
    icon: 'inv_ember',
    maxRanks: 2,
    entryIds: [80267],
    definitionIds: [{ id: 85270, specId: 63 }],
  },
  FLAME_ON_TALENT: {
    id: 205029,
    name: 'Flame On',
    icon: 'inv_helm_circlet_firelands_d_01',
    maxRanks: 2,
    entryIds: [80256],
    definitionIds: [{ id: 85259, specId: 63 }],
  },
  FLAME_PATCH_TALENT: {
    id: 205037,
    name: 'Flame Patch',
    icon: 'spell_mage_flameorb',
    maxRanks: 1,
    entryIds: [80259],
    definitionIds: [{ id: 85262, specId: 63 }],
  },
  FLASH_FREEZE_TALENT: {
    id: 379993,
    name: 'Flash Freeze',
    icon: 'spell_hunter_icetrap',
    maxRanks: 1,
    entryIds: [80231],
    definitionIds: [{ id: 85234, specId: 64 }],
  },
  FLOW_OF_TIME_TALENT: {
    id: 382268,
    name: 'Flow of Time',
    icon: 'spell_arcane_blink',
    maxRanks: 2,
    entryIds: [80153],
    definitionIds: [{ id: 85156, specId: 62 }],
  },
  FLURRY_TALENT: {
    id: 44614,
    name: 'Flurry',
    icon: 'ability_warlock_burningembersblue',
    maxRanks: 1,
    entryIds: [80243],
    definitionIds: [{ id: 85246, specId: 64 }],
    manaCost: 2500,
  },
  FORESIGHT_TALENT: {
    id: 384861,
    name: 'Foresight',
    icon: 'spell_mage_presenceofmind',
    maxRanks: 1,
    entryIds: [80203],
    definitionIds: [{ id: 85206, specId: 62 }],
  },
  FRACTURED_FROST_TALENT: {
    id: 378448,
    name: 'Fractured Frost',
    icon: 'spell_fire_frostresistancetotem',
    maxRanks: 2,
    entryIds: [80250],
    definitionIds: [{ id: 85253, specId: 64 }],
  },
  FREEZING_COLD_TALENT: {
    id: 386763,
    name: 'Freezing Cold',
    icon: 'spell_frost_glacier',
    maxRanks: 1,
    entryIds: [80143],
    definitionIds: [{ id: 85146, specId: 62 }],
  },
  FREEZING_RAIN_TALENT: {
    id: 270233,
    name: 'Freezing Rain',
    icon: 'spell_frost_frozenorb',
    maxRanks: 1,
    entryIds: [80212],
    definitionIds: [{ id: 85215, specId: 64 }],
  },
  FREEZING_WINDS_TALENT: {
    id: 382103,
    name: 'Freezing Winds',
    icon: 'spell_fire_blueflamering',
    maxRanks: 1,
    entryIds: [80214],
    definitionIds: [{ id: 85217, specId: 64 }],
  },
  FRIGID_WINDS_TALENT: {
    id: 235224,
    name: 'Frigid Winds',
    icon: 'ability_mage_deepfreeze',
    maxRanks: 2,
    entryIds: [80188],
    definitionIds: [{ id: 85191, specId: 62 }],
  },
  FROM_THE_ASHES_TALENT: {
    id: 342344,
    name: 'From the Ashes',
    icon: 'inv_misc_phoenixegg',
    maxRanks: 1,
    entryIds: [80289],
    definitionIds: [{ id: 85292, specId: 63 }],
  },
  FROSTBITE_TALENT: {
    id: 378756,
    name: 'Frostbite',
    icon: 'spell_frost_frostarmor',
    maxRanks: 1,
    entryIds: [102428],
    definitionIds: [{ id: 107433, specId: 64 }],
  },
  FROZEN_ORB_TALENT: {
    id: 84714,
    name: 'Frozen Orb',
    icon: 'spell_frost_frozenorb',
    maxRanks: 1,
    entryIds: [80242],
    definitionIds: [{ id: 85245, specId: 64 }],
    manaCost: 2500,
  },
  FROZEN_TOUCH_TALENT: {
    id: 205030,
    name: 'Frozen Touch',
    icon: 'ability_mage_burstofcold',
    maxRanks: 1,
    entryIds: [80245],
    definitionIds: [{ id: 85248, specId: 64 }],
  },
  FUEL_THE_FIRE_TALENT: {
    id: 416094,
    name: 'Fuel the Fire',
    icon: 'ability_warlock_inferno',
    maxRanks: 1,
    entryIds: [80257],
    definitionIds: [{ id: 85260, specId: 63 }],
  },
  GLACIAL_ASSAULT_TALENT: {
    id: 378947,
    name: 'Glacial Assault',
    icon: 'inv_staff_15',
    maxRanks: 1,
    entryIds: [80249],
    definitionIds: [{ id: 85252, specId: 64 }],
  },
  GLACIAL_SPIKE_TALENT: {
    id: 199786,
    name: 'Glacial Spike',
    icon: 'ability_mage_glacialspike',
    maxRanks: 1,
    entryIds: [80220],
    definitionIds: [{ id: 85223, specId: 64 }],
    manaCost: 2500,
  },
  GREATER_INVISIBILITY_TALENT: {
    id: 110959,
    name: 'Greater Invisibility',
    icon: 'ability_mage_greaterinvisibility',
    maxRanks: 1,
    entryIds: [115877],
    definitionIds: [{ id: 120889, specId: 62 }],
  },
  HAILSTONES_TALENT: {
    id: 381244,
    name: 'Hailstones',
    icon: 'artifactability_frostmage_blackicicles',
    maxRanks: 2,
    entryIds: [80221],
    definitionIds: [{ id: 85224, specId: 64 }],
  },
  HARMONIC_ECHO_TALENT: {
    id: 384683,
    name: 'Harmonic Echo',
    icon: 'ability_bastion_mage',
    maxRanks: 1,
    entryIds: [80305],
    definitionIds: [{ id: 85308, specId: 62 }],
  },
  HYPERTHERMIA_TALENT: {
    id: 383860,
    name: 'Hyperthermia',
    icon: 'spell_fire_burnout',
    maxRanks: 1,
    entryIds: [116062],
    definitionIds: [{ id: 121074, specId: 63 }],
  },
  ICE_BARRIER_TALENT: {
    id: 11426,
    name: 'Ice Barrier',
    icon: 'spell_ice_lament',
    maxRanks: 1,
    entryIds: [80176],
    definitionIds: [{ id: 85179, specId: 64 }],
    manaCost: 7500,
  },
  ICE_BLOCK_TALENT: {
    id: 45438,
    name: 'Ice Block',
    icon: 'spell_frost_frost',
    maxRanks: 1,
    entryIds: [80181],
    definitionIds: [{ id: 85184, specId: 62 }],
  },
  ICE_CALLER_TALENT: {
    id: 236662,
    name: 'Ice Caller',
    icon: 'spell_frost_icestorm',
    maxRanks: 1,
    entryIds: [80233],
    definitionIds: [{ id: 85236, specId: 64 }],
  },
  ICE_COLD_TALENT: {
    id: 414659,
    name: 'Ice Cold',
    icon: 'spell_fire_bluefire',
    maxRanks: 1,
    entryIds: [80141],
    definitionIds: [{ id: 85144, specId: 62 }],
  },
  ICE_FLOES_TALENT: {
    id: 108839,
    name: 'Ice Floes',
    icon: 'spell_mage_iceflows',
    maxRanks: 1,
    entryIds: [80162],
    definitionIds: [{ id: 85165, specId: 62 }],
  },
  ICE_LANCE_TALENT: {
    id: 30455,
    name: 'Ice Lance',
    icon: 'spell_frost_frostblast',
    maxRanks: 1,
    entryIds: [80241],
    definitionIds: [{ id: 85244, specId: 64 }],
    manaCost: 2500,
  },
  ICE_NOVA_TALENT: {
    id: 157997,
    name: 'Ice Nova',
    icon: 'spell_mage_icenova',
    maxRanks: 1,
    entryIds: [80186],
    definitionIds: [{ id: 85189, specId: 62 }],
  },
  ICE_WARD_TALENT: {
    id: 205036,
    name: 'Ice Ward',
    icon: 'spell_frost_frostward',
    maxRanks: 1,
    entryIds: [80142],
    definitionIds: [{ id: 85145, specId: 62 }],
  },
  ICY_VEINS_TALENT: {
    id: 12472,
    name: 'Icy Veins',
    icon: 'spell_frost_coldhearted',
    maxRanks: 1,
    entryIds: [80235],
    definitionIds: [{ id: 85238, specId: 64 }],
  },
  ILLUMINATED_THOUGHTS_TALENT: {
    id: 384060,
    name: 'Illuminated Thoughts',
    icon: 'spell_arcane_focusedpower',
    maxRanks: 2,
    entryIds: [80292],
    definitionIds: [{ id: 85295, specId: 62 }],
  },
  IMPETUS_TALENT: {
    id: 383676,
    name: 'Impetus',
    icon: 'spell_arcane_arcanetorrent',
    maxRanks: 1,
    entryIds: [80291],
    definitionIds: [{ id: 85294, specId: 62 }],
  },
  IMPROVED_ARCANE_MISSILES_TALENT: {
    id: 383661,
    name: 'Improved Arcane Missiles',
    icon: 'spell_nature_starfall',
    maxRanks: 2,
    entryIds: [80309],
    definitionIds: [{ id: 85312, specId: 62 }],
  },
  IMPROVED_CLEARCASTING_TALENT: {
    id: 321420,
    name: 'Improved Clearcasting',
    icon: 'spell_shadow_manaburn',
    maxRanks: 1,
    entryIds: [80293],
    definitionIds: [{ id: 85296, specId: 62 }],
  },
  IMPROVED_COMBUSTION_TALENT: {
    id: 383967,
    name: 'Improved Combustion',
    icon: 'spell_fire_sealoffire',
    maxRanks: 1,
    entryIds: [80269],
    definitionIds: [{ id: 85272, specId: 63 }],
  },
  IMPROVED_FROST_NOVA_TALENT: {
    id: 343183,
    name: 'Improved Frost Nova',
    icon: 'spell_frost_frostnova',
    maxRanks: 1,
    entryIds: [80166],
    definitionIds: [{ id: 85169, specId: 62 }],
  },
  IMPROVED_PRISMATIC_BARRIER_TALENT: {
    id: 321745,
    name: 'Improved Prismatic Barrier',
    icon: 'spell_magearmor',
    maxRanks: 1,
    entryIds: [80301],
    definitionIds: [{ id: 85304, specId: 62 }],
  },
  IMPROVED_SCORCH_TALENT: {
    id: 383604,
    name: 'Improved Scorch',
    icon: 'ability_mage_fierypayback',
    maxRanks: 1,
    entryIds: [80279],
    definitionIds: [{ id: 85282, specId: 63 }],
  },
  INCANTATION_OF_SWIFTNESS_TALENT: {
    id: 382293,
    name: 'Incantation of Swiftness',
    icon: 'rogue_burstofspeed',
    maxRanks: 2,
    entryIds: [80170],
    definitionIds: [{ id: 85173, specId: 62 }],
  },
  INCANTERS_FLOW_TALENT: {
    id: 1463,
    name: "Incanter's Flow",
    icon: 'ability_mage_incantersabsorbtion',
    maxRanks: 1,
    entryIds: [80177],
    definitionIds: [{ id: 85180, specId: 62 }],
  },
  INCENDIARY_ERUPTIONS_TALENT: {
    id: 383665,
    name: 'Incendiary Eruptions',
    icon: 'spell_fire_moltenblood',
    maxRanks: 1,
    entryIds: [80255],
    definitionIds: [{ id: 85258, specId: 63 }],
  },
  INFLAME_TALENT: {
    id: 417467,
    name: 'Inflame',
    icon: 'spell_fire_ragnaros_lavabolt',
    maxRanks: 1,
    entryIds: [116101],
    definitionIds: [{ id: 121113, specId: 63 }],
  },
  INTENSIFYING_FLAME_TALENT: {
    id: 416714,
    name: 'Intensifying Flame',
    icon: 'spell_fire_incinerate',
    maxRanks: 1,
    entryIds: [80274],
    definitionIds: [{ id: 85277, specId: 63 }],
  },
  KINDLING_TALENT: {
    id: 155148,
    name: 'Kindling',
    icon: 'spell_mage_kindling',
    maxRanks: 1,
    entryIds: [80265],
    definitionIds: [{ id: 85268, specId: 63 }],
  },
  LIVING_BOMB_TALENT: {
    id: 44457,
    name: 'Living Bomb',
    icon: 'ability_mage_livingbomb',
    maxRanks: 1,
    entryIds: [80260],
    definitionIds: [{ id: 85263, specId: 63 }],
    manaCost: 3750,
  },
  LONELY_WINTER_TALENT: {
    id: 205024,
    name: 'Lonely Winter',
    icon: 'achievement_dungeon_frozenthrone',
    maxRanks: 1,
    entryIds: [80237],
    definitionIds: [{ id: 85240, specId: 64 }],
  },
  MANA_ADEPT_TALENT: {
    id: 321526,
    name: 'Mana Adept',
    icon: 'ability_mage_arcanebarrage',
    maxRanks: 1,
    entryIds: [80300],
    definitionIds: [{ id: 85303, specId: 62 }],
  },
  MASS_BARRIER_TALENT: {
    id: 414660,
    name: 'Mass Barrier',
    icon: 'ability_racial_magicalresistance',
    maxRanks: 1,
    entryIds: [80148],
    definitionIds: [{ id: 85151, specId: 62 }],
    manaCost: 30000,
  },
  MASS_INVISIBILITY_TALENT: {
    id: 414664,
    name: 'Mass Invisibility',
    icon: 'ability_mage_massinvisibility',
    maxRanks: 1,
    entryIds: [115878],
    definitionIds: [{ id: 120890, specId: 62 }],
    manaCost: 15000,
  },
  MASS_POLYMORPH_TALENT: {
    id: 383121,
    name: 'Mass Polymorph',
    icon: 'spell_nature_doublepolymorph1',
    maxRanks: 1,
    entryIds: [80164],
    definitionIds: [{ id: 85167, specId: 62 }],
    manaCost: 10000,
  },
  MASS_SLOW_TALENT: {
    id: 391102,
    name: 'Mass Slow',
    icon: 'inv_enchant_essencearcanelarge',
    maxRanks: 1,
    entryIds: [80167],
    definitionIds: [{ id: 85170, specId: 62 }],
  },
  MASTER_OF_FLAME_TALENT: {
    id: 384174,
    name: 'Master of Flame',
    icon: 'inv_trinket_firelands_02',
    maxRanks: 1,
    entryIds: [116061],
    definitionIds: [{ id: 121073, specId: 63 }],
  },
  MASTER_OF_TIME_TALENT: {
    id: 342249,
    name: 'Master of Time',
    icon: 'inv_belt_armor_waistoftime_d_01',
    maxRanks: 1,
    entryIds: [80159],
    definitionIds: [{ id: 85162, specId: 62 }],
  },
  METEOR_TALENT: {
    id: 153561,
    name: 'Meteor',
    icon: 'spell_mage_meteor',
    maxRanks: 1,
    entryIds: [80253],
    definitionIds: [{ id: 85256, specId: 63 }],
    manaCost: 2500,
  },
  MIRROR_IMAGE_TALENT: {
    id: 55342,
    name: 'Mirror Image',
    icon: 'spell_magic_lesserinvisibilty',
    maxRanks: 1,
    entryIds: [80183],
    definitionIds: [{ id: 85186, specId: 62 }],
    manaCost: 5000,
  },
  NETHER_PRECISION_TALENT: {
    id: 383782,
    name: 'Nether Precision',
    icon: 'spell_arcane_blast_nightborne',
    maxRanks: 1,
    entryIds: [80295],
    definitionIds: [{ id: 85298, specId: 62 }],
  },
  NETHER_TEMPEST_TALENT: {
    id: 114923,
    name: 'Nether Tempest',
    icon: 'spell_mage_nethertempest',
    maxRanks: 1,
    entryIds: [80198],
    definitionIds: [{ id: 85201, specId: 62 }],
    manaCost: 3750,
  },
  ORB_BARRAGE_TALENT: {
    id: 384858,
    name: 'Orb Barrage',
    icon: 'spell_mage_arcaneorb_nightborne',
    maxRanks: 1,
    entryIds: [80196],
    definitionIds: [{ id: 85199, specId: 62 }],
  },
  OVERFLOWING_ENERGY_TALENT: {
    id: 390218,
    name: 'Overflowing Energy',
    icon: 'spell_arcane_manatap',
    maxRanks: 1,
    entryIds: [80179],
    definitionIds: [{ id: 85182, specId: 62 }],
  },
  PERPETUAL_WINTER_TALENT: {
    id: 378198,
    name: 'Perpetual Winter',
    icon: 'spell_frost_arcticwinds',
    maxRanks: 1,
    entryIds: [80247],
    definitionIds: [{ id: 85250, specId: 64 }],
  },
  PHOENIX_FLAMES_TALENT: {
    id: 257541,
    name: 'Phoenix Flames',
    icon: 'artifactability_firemage_phoenixbolt',
    maxRanks: 1,
    entryIds: [80285],
    definitionIds: [{ id: 85288, specId: 63 }],
  },
  PHOENIX_REBORN_TALENT: {
    id: 383476,
    name: 'Phoenix Reborn',
    icon: 'inv_sword_1h_artifactfelomelorn_d_01',
    maxRanks: 1,
    entryIds: [80266],
    definitionIds: [{ id: 85269, specId: 63 }],
  },
  PIERCING_COLD_TALENT: {
    id: 378919,
    name: 'Piercing Cold',
    icon: 'spell_frost_frostbolt',
    maxRanks: 1,
    entryIds: [80229],
    definitionIds: [{ id: 85232, specId: 64 }],
  },
  PRESENCE_OF_MIND_TALENT: {
    id: 205025,
    name: 'Presence of Mind',
    icon: 'spell_nature_enchantarmor',
    maxRanks: 1,
    entryIds: [80208],
    definitionIds: [{ id: 85211, specId: 62 }],
  },
  PRISMATIC_BARRIER_TALENT: {
    id: 235450,
    name: 'Prismatic Barrier',
    icon: 'spell_magearmor',
    maxRanks: 1,
    entryIds: [80180],
    definitionIds: [{ id: 85183, specId: 62 }],
    manaCost: 7500,
  },
  PRODIGIOUS_SAVANT_TALENT: {
    id: 384612,
    name: 'Prodigious Savant',
    icon: 'ability_mage_studentofthemind',
    maxRanks: 2,
    entryIds: [80197],
    definitionIds: [{ id: 85200, specId: 62 }],
  },
  PYROBLAST_TALENT: {
    id: 11366,
    name: 'Pyroblast',
    icon: 'spell_fire_fireball02',
    maxRanks: 1,
    entryIds: [80283],
    definitionIds: [{ id: 85286, specId: 63 }],
    manaCost: 5000,
  },
  PYROMANIAC_TALENT: {
    id: 205020,
    name: 'Pyromaniac',
    icon: 'inv_misc_volatilefire',
    maxRanks: 1,
    entryIds: [116060],
    definitionIds: [{ id: 121072, specId: 63 }],
  },
  PYROTECHNICS_TALENT: {
    id: 157642,
    name: 'Pyrotechnics',
    icon: 'spell_fire_flamebolt',
    maxRanks: 1,
    entryIds: [80284],
    definitionIds: [{ id: 85287, specId: 63 }],
  },
  QUICK_WITTED_TALENT: {
    id: 382297,
    name: 'Quick Witted',
    icon: 'ability_priest_surgeofdarkness',
    maxRanks: 1,
    entryIds: [80161],
    definitionIds: [{ id: 85164, specId: 62 }],
  },
  RADIANT_SPARK_TALENT: {
    id: 376103,
    name: 'Radiant Spark',
    icon: 'ability_bastion_mage',
    maxRanks: 1,
    entryIds: [80304],
    definitionIds: [{ id: 85307, specId: 62 }],
    manaCost: 5000,
  },
  RAY_OF_FROST_TALENT: {
    id: 205021,
    name: 'Ray of Frost',
    icon: 'ability_mage_rayoffrost',
    maxRanks: 1,
    entryIds: [80216],
    definitionIds: [{ id: 85219, specId: 64 }],
    manaCost: 5000,
  },
  REABSORPTION_TALENT: {
    id: 382820,
    name: 'Reabsorption',
    icon: 'spell_arcane_studentofmagic',
    maxRanks: 1,
    entryIds: [80184],
    definitionIds: [{ id: 85187, specId: 62 }],
  },
  REDUPLICATION_TALENT: {
    id: 382569,
    name: 'Reduplication',
    icon: 'ability_mage_massinvisibility',
    maxRanks: 1,
    entryIds: [80185],
    definitionIds: [{ id: 85188, specId: 62 }],
  },
  REMOVE_CURSE_TALENT: {
    id: 475,
    name: 'Remove Curse',
    icon: 'spell_nature_removecurse',
    maxRanks: 1,
    entryIds: [80175],
    definitionIds: [{ id: 85178, specId: 62 }],
    manaCost: 3250,
  },
  RESONANCE_TALENT: {
    id: 205028,
    name: 'Resonance',
    icon: 'spell_arcane_arcane01',
    maxRanks: 1,
    entryIds: [80200],
    definitionIds: [{ id: 85203, specId: 62 }],
  },
  REVERBERATE_TALENT: {
    id: 281482,
    name: 'Reverberate',
    icon: 'spell_arcane_arcane04',
    maxRanks: 1,
    entryIds: [115762],
    definitionIds: [{ id: 120774, specId: 62 }],
  },
  RIGID_ICE_TALENT: {
    id: 382481,
    name: 'Rigid Ice',
    icon: 'spell_hunter_blackicetrap',
    maxRanks: 1,
    entryIds: [80168],
    definitionIds: [{ id: 85171, specId: 62 }],
  },
  RING_OF_FROST_TALENT: {
    id: 113724,
    name: 'Ring of Frost',
    icon: 'spell_frost_ring_of_frost',
    maxRanks: 1,
    entryIds: [80144],
    definitionIds: [{ id: 85147, specId: 62 }],
    manaCost: 20000,
  },
  RULE_OF_THREES_TALENT: {
    id: 264354,
    name: 'Rule of Threes',
    icon: 'spell_arcane_starfire',
    maxRanks: 1,
    entryIds: [80206],
    definitionIds: [{ id: 85209, specId: 62 }],
  },
  SCORCH_TALENT: {
    id: 2948,
    name: 'Scorch',
    icon: 'spell_fire_soulburn',
    maxRanks: 1,
    entryIds: [80281],
    definitionIds: [{ id: 85284, specId: 63 }],
    manaCost: 2500,
  },
  SEARING_TOUCH_TALENT: {
    id: 269644,
    name: 'Searing Touch',
    icon: 'ability_warlock_backdraft',
    maxRanks: 1,
    entryIds: [80280],
    definitionIds: [{ id: 85283, specId: 63 }],
  },
  SHATTER_TALENT: {
    id: 12982,
    name: 'Shatter',
    icon: 'spell_frost_frostshock',
    maxRanks: 1,
    entryIds: [80228],
    definitionIds: [{ id: 85231, specId: 64 }],
  },
  SHIFTING_POWER_TALENT: {
    id: 382440,
    name: 'Shifting Power',
    icon: 'ability_ardenweald_mage',
    maxRanks: 1,
    entryIds: [80171],
    definitionIds: [{ id: 85174, specId: 62 }],
    manaCost: 12500,
  },
  SHIMMER_TALENT: {
    id: 212653,
    name: 'Shimmer',
    icon: 'spell_arcane_massdispel',
    maxRanks: 1,
    entryIds: [80163],
    definitionIds: [{ id: 85166, specId: 62 }],
    manaCost: 5000,
  },
  SIPHON_STORM_TALENT: {
    id: 384187,
    name: 'Siphon Storm',
    icon: 'ability_monk_forcesphere_arcane',
    maxRanks: 1,
    entryIds: [80210],
    definitionIds: [{ id: 85213, specId: 62 }],
  },
  SLICK_ICE_TALENT: {
    id: 382144,
    name: 'Slick Ice',
    icon: 'inv_enchant_shardshadowfrostlarge',
    maxRanks: 1,
    entryIds: [80219],
    definitionIds: [{ id: 85222, specId: 64 }],
  },
  SLIPSTREAM_TALENT: {
    id: 236457,
    name: 'Slipstream',
    icon: 'spell_holy_mindsooth',
    maxRanks: 1,
    entryIds: [80296],
    definitionIds: [{ id: 85299, specId: 62 }],
  },
  SLOW_TALENT: {
    id: 31589,
    name: 'Slow',
    icon: 'spell_nature_slow',
    maxRanks: 1,
    entryIds: [80154],
    definitionIds: [{ id: 85157, specId: 62 }],
    manaCost: 2500,
  },
  SNOWSTORM_TALENT: {
    id: 381706,
    name: 'Snowstorm',
    icon: 'spell_fire_bluerainoffire',
    maxRanks: 2,
    entryIds: [80234],
    definitionIds: [{ id: 85237, specId: 64 }],
  },
  SPELLSTEAL_TALENT: {
    id: 30449,
    name: 'Spellsteal',
    icon: 'spell_arcane_arcane02',
    maxRanks: 1,
    entryIds: [80140],
    definitionIds: [{ id: 85143, specId: 62 }],
    manaCost: 52500,
  },
  SPLINTERING_COLD_TALENT: {
    id: 379049,
    name: 'Splintering Cold',
    icon: 'spell_fire_blueflamestrike',
    maxRanks: 2,
    entryIds: [80225],
    definitionIds: [{ id: 85228, specId: 64 }],
  },
  SPLINTERING_RAY_TALENT: {
    id: 418733,
    name: 'Splintering Ray',
    icon: 'spell_fire_blueflamestrike',
    maxRanks: 1,
    entryIds: [116133],
    definitionIds: [{ id: 121145, specId: 64 }],
  },
  SPLITTING_ICE_TALENT: {
    id: 56377,
    name: 'Splitting Ice',
    icon: 'spell_frost_ice_shards',
    maxRanks: 1,
    entryIds: [80224],
    definitionIds: [{ id: 85227, specId: 64 }],
  },
  SUBZERO_TALENT: {
    id: 380154,
    name: 'Subzero',
    icon: 'spell_ice_magicdamage',
    maxRanks: 2,
    entryIds: [80223],
    definitionIds: [{ id: 85226, specId: 64 }],
  },
  SUN_KINGS_BLESSING_TALENT: {
    id: 383886,
    name: "Sun King's Blessing",
    icon: 'ability_mage_firestarter',
    maxRanks: 1,
    entryIds: [80273],
    definitionIds: [{ id: 85276, specId: 63 }],
  },
  SUPERNOVA_TALENT: {
    id: 157980,
    name: 'Supernova',
    icon: 'spell_mage_supernova',
    maxRanks: 1,
    entryIds: [80290],
    definitionIds: [{ id: 85293, specId: 62 }],
  },
  SURGING_BLAZE_TALENT: {
    id: 343230,
    name: 'Surging Blaze',
    icon: 'spell_fire_selfdestruct',
    maxRanks: 1,
    entryIds: [80258],
    definitionIds: [{ id: 85261, specId: 63 }],
  },
  TEMPERED_FLAMES_TALENT: {
    id: 383659,
    name: 'Tempered Flames',
    icon: 'ability_mage_greaterpyroblast',
    maxRanks: 1,
    entryIds: [80268],
    definitionIds: [{ id: 85271, specId: 63 }],
  },
  TEMPEST_BARRIER_TALENT: {
    id: 382289,
    name: 'Tempest Barrier',
    icon: 'inv_shield_1h_artifactstormfist_d_04',
    maxRanks: 2,
    entryIds: [80169],
    definitionIds: [{ id: 85172, specId: 62 }],
  },
  TEMPORAL_VELOCITY_TALENT: {
    id: 382826,
    name: 'Temporal Velocity',
    icon: 'ability_socererking_arcaneacceleration',
    maxRanks: 2,
    entryIds: [80156],
    definitionIds: [{ id: 85159, specId: 62 }],
  },
  TEMPORAL_WARP_TALENT: {
    id: 386539,
    name: 'Temporal Warp',
    icon: 'ability_bossmagistrix_timewarp2',
    maxRanks: 1,
    entryIds: [80150],
    definitionIds: [{ id: 85153, specId: 62 }],
  },
  THERMAL_VOID_TALENT: {
    id: 155149,
    name: 'Thermal Void',
    icon: 'spell_mage_thermalvoid',
    maxRanks: 1,
    entryIds: [80217],
    definitionIds: [{ id: 85220, specId: 64 }],
  },
  TIME_ANOMALY_TALENT: {
    id: 383243,
    name: 'Time Anomaly',
    icon: 'ability_mage_timewarp',
    maxRanks: 1,
    entryIds: [80151],
    definitionIds: [{ id: 85154, specId: 62 }],
  },
  TIME_MANIPULATION_TALENT: {
    id: 387807,
    name: 'Time Manipulation',
    icon: 'spell_nature_timestop',
    maxRanks: 1,
    entryIds: [80189],
    definitionIds: [{ id: 85192, specId: 62 }],
  },
  TOME_OF_ANTONIDAS_TALENT: {
    id: 382490,
    name: 'Tome of Antonidas',
    icon: 'inv_misc_book_18',
    maxRanks: 1,
    entryIds: [80155],
    definitionIds: [{ id: 85158, specId: 62 }],
  },
  TOME_OF_RHONIN_TALENT: {
    id: 382493,
    name: 'Tome of Rhonin',
    icon: 'inv_misc_book_04',
    maxRanks: 1,
    entryIds: [80187],
    definitionIds: [{ id: 85190, specId: 62 }],
  },
  TOUCH_OF_THE_MAGI_TALENT: {
    id: 321507,
    name: 'Touch of the Magi',
    icon: 'ability_mage_netherwindpresence',
    maxRanks: 1,
    entryIds: [80302],
    definitionIds: [{ id: 85305, specId: 62 }],
    manaCost: 12500,
  },
  UNLEASHED_INFERNO_TALENT: {
    id: 416506,
    name: 'Unleashed Inferno',
    icon: 'spell_fire_felflamering_red',
    maxRanks: 1,
    entryIds: [116063],
    definitionIds: [{ id: 121075, specId: 63 }],
  },
  VOLATILE_DETONATION_TALENT: {
    id: 389627,
    name: 'Volatile Detonation',
    icon: 'spell_fire_burnout',
    maxRanks: 1,
    entryIds: [80145],
    definitionIds: [{ id: 85148, specId: 62 }],
  },
  WILDFIRE_TALENT: {
    id: 383489,
    name: 'Wildfire',
    icon: 'ability_warlock_inferno',
    maxRanks: 2,
    entryIds: [80270],
    definitionIds: [{ id: 85273, specId: 63 }],
  },
  WINTERS_BLESSING_TALENT: {
    id: 417489,
    name: "Winter's Blessing",
    icon: 'spell_frost_wisp',
    maxRanks: 1,
    entryIds: [80239],
    definitionIds: [{ id: 85242, specId: 64 }],
  },
  WINTERS_PROTECTION_TALENT: {
    id: 382424,
    name: "Winter's Protection",
    icon: 'spell_ice_rune',
    maxRanks: 2,
    entryIds: [80182],
    definitionIds: [{ id: 85185, specId: 62 }],
  },
  WINTERTIDE_TALENT: {
    id: 378406,
    name: 'Wintertide',
    icon: 'ability_deathknight_frozencenter',
    maxRanks: 2,
    entryIds: [80236],
    definitionIds: [{ id: 85239, specId: 64 }],
  },
});

export default talents;
export { talents as TALENTS_MAGE };
