// Generated file, changes will eventually be overwritten!
import { createTalentList } from './types';

const talents = createTalentList({
  ACCUMULATIVE_SHIELDING_TALENT: {
    id: 382800,
    name: 'Accumulative Shielding',
    icon: 'ability_mage_shattershield',
    maxRanks: 2,
    entryIds: [80149],
  },
  ALEXSTRASZAS_FURY_TALENT: {
    id: 235870,
    name: "Alexstrasza's Fury",
    icon: 'spell_warrior_dragoncharge',
    maxRanks: 1,
    entryIds: [80288],
  },
  ALTER_TIME_TALENT: {
    id: 342245,
    name: 'Alter Time',
    icon: 'spell_mage_altertime',
    maxRanks: 1,
    entryIds: [80174],
    manaCost: 2500,
  },
  AMPLIFICATION_TALENT: {
    id: 236628,
    name: 'Amplification',
    icon: 'spell_arcane_invocation',
    maxRanks: 1,
    entryIds: [80294],
  },
  ARCANE_BARRAGE_TALENT: {
    id: 44425,
    name: 'Arcane Barrage',
    icon: 'ability_mage_arcanebarrage',
    maxRanks: 1,
    entryIds: [80306],
  },
  ARCANE_BOMBARDMENT_TALENT: {
    id: 384581,
    name: 'Arcane Bombardment',
    icon: 'ability_socererking_arcanereplication',
    maxRanks: 1,
    entryIds: [80303],
  },
  ARCANE_ECHO_TALENT: {
    id: 342231,
    name: 'Arcane Echo',
    icon: 'ability_socererking_arcanewrath',
    maxRanks: 1,
    entryIds: [80191],
  },
  ARCANE_FAMILIAR_TALENT: {
    id: 205022,
    name: 'Arcane Familiar',
    icon: 'ability_socererking_arcanemines',
    maxRanks: 1,
    entryIds: [80207],
  },
  ARCANE_HARMONY_TALENT: {
    id: 384452,
    name: 'Arcane Harmony',
    icon: 'ability_creature_cursed_04',
    maxRanks: 1,
    entryIds: [80195],
  },
  ARCANE_MISSILES_TALENT: {
    id: 5143,
    name: 'Arcane Missiles',
    icon: 'spell_nature_starfall',
    maxRanks: 1,
    entryIds: [80307],
    manaCost: 37500,
  },
  ARCANE_ORB_TALENT: {
    id: 153626,
    name: 'Arcane Orb',
    icon: 'spell_mage_arcaneorb',
    maxRanks: 1,
    entryIds: [80308],
    manaCost: 2500,
  },
  ARCANE_POWER_TALENT: {
    id: 321739,
    name: 'Arcane Power',
    icon: 'spell_nature_lightning',
    maxRanks: 1,
    entryIds: [80190],
  },
  ARCANE_SURGE_TALENT: {
    id: 365350,
    name: 'Arcane Surge',
    icon: 'ability_mage_arcanesurge',
    maxRanks: 1,
    entryIds: [80299],
    manaCost: 1,
  },
  ARCANE_TEMPO_TALENT: {
    id: 383980,
    name: 'Arcane Tempo',
    icon: 'ability_socererking_arcaneacceleration',
    maxRanks: 1,
    entryIds: [80205],
  },
  ARCANE_WARDING_TALENT: {
    id: 383092,
    name: 'Arcane Warding',
    icon: 'spell_arcane_arcaneresilience',
    maxRanks: 2,
    entryIds: [80173],
  },
  ARCING_CLEAVE_TALENT: {
    id: 231564,
    name: 'Arcing Cleave',
    icon: 'ability_mage_arcanebarrage',
    maxRanks: 1,
    entryIds: [80201],
  },
  BLAST_WAVE_TALENT: {
    id: 157981,
    name: 'Blast Wave',
    icon: 'spell_holy_excorcism_02',
    maxRanks: 1,
    entryIds: [80160],
  },
  BLAZING_BARRIER_TALENT: {
    id: 235313,
    name: 'Blazing Barrier',
    icon: 'ability_mage_moltenarmor',
    maxRanks: 1,
    entryIds: [80178],
    manaCost: 7500,
  },
  BLIZZARD_TALENT: {
    id: 190356,
    name: 'Blizzard',
    icon: 'spell_frost_icestorm',
    maxRanks: 1,
    entryIds: [80240],
    manaCost: 6250,
  },
  BONE_CHILLING_TALENT: {
    id: 205027,
    name: 'Bone Chilling',
    icon: 'ability_mage_chilledtothebone',
    maxRanks: 1,
    entryIds: [80230],
  },
  BRAIN_FREEZE_TALENT: {
    id: 190447,
    name: 'Brain Freeze',
    icon: 'ability_mage_brainfreeze',
    maxRanks: 1,
    entryIds: [80244],
  },
  CALL_OF_THE_SUN_KING_TALENT: {
    id: 343222,
    name: 'Call of the Sun King',
    icon: 'artifactability_firemage_phoenixbolt',
    maxRanks: 1,
    entryIds: [80278],
  },
  CASCADING_POWER_TALENT: {
    id: 384276,
    name: 'Cascading Power',
    icon: 'inv_misc_gem_sapphire_02',
    maxRanks: 1,
    entryIds: [80193],
  },
  CAUTERIZE_TALENT: {
    id: 86949,
    name: 'Cauterize',
    icon: 'spell_fire_rune',
    maxRanks: 1,
    entryIds: [80274],
  },
  CHAIN_REACTION_TALENT: {
    id: 278309,
    name: 'Chain Reaction',
    icon: 'spell_frost_frostblast',
    maxRanks: 1,
    entryIds: [80218],
  },
  CHARGED_ORB_TALENT: {
    id: 384651,
    name: 'Charged Orb',
    icon: 'spell_mage_arcaneorb',
    maxRanks: 1,
    entryIds: [80310],
  },
  CHRONO_SHIFT_TALENT: {
    id: 235711,
    name: 'Chrono Shift',
    icon: 'ability_monk_deadlyreach',
    maxRanks: 1,
    entryIds: [80202],
  },
  CLEARCASTING_TALENT: {
    id: 79684,
    name: 'Clearcasting',
    icon: 'spell_shadow_manaburn',
    maxRanks: 1,
    entryIds: [80298],
    manaCost: 2500,
  },
  COLD_FRONT_TALENT: {
    id: 382110,
    name: 'Cold Front',
    icon: 'ability_mage_coldasice',
    maxRanks: 1,
    entryIds: [80251],
  },
  COLD_SNAP_TALENT: {
    id: 235219,
    name: 'Cold Snap',
    icon: 'spell_frost_wizardmark',
    maxRanks: 1,
    entryIds: [80239],
  },
  COMBUSTION_TALENT: {
    id: 190319,
    name: 'Combustion',
    icon: 'spell_fire_sealoffire',
    maxRanks: 1,
    entryIds: [80275],
    manaCost: 25000,
  },
  COMET_STORM_TALENT: {
    id: 153595,
    name: 'Comet Storm',
    icon: 'spell_mage_cometstorm2',
    maxRanks: 1,
    entryIds: [80249],
    manaCost: 2500,
  },
  CONCENTRATION_TALENT: {
    id: 384374,
    name: 'Concentration',
    icon: 'ability_mage_potentspirit',
    maxRanks: 1,
    entryIds: [80194],
  },
  CONFLAGRATION_TALENT: {
    id: 205023,
    name: 'Conflagration',
    icon: 'spell_shaman_firenova',
    maxRanks: 1,
    entryIds: [80254],
  },
  CONJURE_MANA_GEM_TALENT: {
    id: 759,
    name: 'Conjure Mana Gem',
    icon: 'inv_misc_gem_sapphire_02',
    maxRanks: 1,
    entryIds: [80192],
    manaCost: 45000,
  },
  CONTROLLED_DESTRUCTION_TALENT: {
    id: 383669,
    name: 'Controlled Destruction',
    icon: 'spell_fire_playingwithfire',
    maxRanks: 2,
    entryIds: [80272],
  },
  CRACKLING_ENERGY_TALENT: {
    id: 321752,
    name: 'Crackling Energy',
    icon: 'spell_nature_wispsplode',
    maxRanks: 2,
    entryIds: [80297],
  },
  CRITICAL_MASS_TALENT: {
    id: 117216,
    name: 'Critical Mass',
    icon: 'spell_fire_volcano',
    maxRanks: 2,
    entryIds: [80287],
  },
  CRYO_FREEZE_TALENT: {
    id: 382292,
    name: 'Cryo-Freeze',
    icon: 'spell_frost_icefloes',
    maxRanks: 2,
    entryIds: [80165],
  },
  DEEP_SHATTER_TALENT: {
    id: 378749,
    name: 'Deep Shatter',
    icon: 'inv_misc_frostemblem_01',
    maxRanks: 2,
    entryIds: [80222],
  },
  DISPLACEMENT_TALENT: {
    id: 389713,
    name: 'Displacement',
    icon: 'ability_hunter_displacement',
    maxRanks: 1,
    entryIds: [80148],
  },
  DIVERTED_ENERGY_TALENT: {
    id: 382270,
    name: 'Diverted Energy',
    icon: 'inv_soulbarrier',
    maxRanks: 2,
    entryIds: [80158],
  },
  DRAGONS_BREATH_TALENT: {
    id: 31661,
    name: "Dragon's Breath",
    icon: 'inv_misc_head_dragon_01',
    maxRanks: 1,
    entryIds: [80147],
    manaCost: 10000,
  },
  EBONBOLT_TALENT: {
    id: 257537,
    name: 'Ebonbolt',
    icon: 'artifactability_frostmage_ebonbolt',
    maxRanks: 1,
    entryIds: [80245],
  },
  ENERGIZED_BARRIERS_TALENT: {
    id: 386828,
    name: 'Energized Barriers',
    icon: 'spell_mage_temporalshield',
    maxRanks: 1,
    entryIds: [80157],
  },
  ENLIGHTENED_TALENT: {
    id: 321387,
    name: 'Enlightened',
    icon: 'ability_socererking_arcanefortification',
    maxRanks: 1,
    entryIds: [80204],
  },
  EVERLASTING_FROST_TALENT: {
    id: 385167,
    name: 'Everlasting Frost',
    icon: 'spell_frost_chillingbolt',
    maxRanks: 1,
    entryIds: [102429],
  },
  EVOCATION_TALENT: {
    id: 12051,
    name: 'Evocation',
    icon: 'spell_nature_purge',
    maxRanks: 1,
    entryIds: [80209],
  },
  FEEL_THE_BURN_TALENT: {
    id: 383391,
    name: 'Feel the Burn',
    icon: 'spell_fire_fireball',
    maxRanks: 2,
    entryIds: [80261],
  },
  FERVENT_FLICKERING_TALENT: {
    id: 387044,
    name: 'Fervent Flickering',
    icon: 'ability_warlock_burningembers',
    maxRanks: 1,
    entryIds: [80284],
  },
  FEVERED_INCANTATION_TALENT: {
    id: 383810,
    name: 'Fevered Incantation',
    icon: 'inv_misc_enchantedpearld',
    maxRanks: 2,
    entryIds: [80253],
  },
  FIERY_RUSH_TALENT: {
    id: 383634,
    name: 'Fiery Rush',
    icon: 'inv_summerfest_firespirit',
    maxRanks: 1,
    entryIds: [80271],
  },
  FINGERS_OF_FROST_TALENT: {
    id: 112965,
    name: 'Fingers of Frost',
    icon: 'ability_mage_wintersgrasp',
    maxRanks: 1,
    entryIds: [80227],
  },
  FIREFALL_TALENT: {
    id: 384033,
    name: 'Firefall',
    icon: 'spell_mage_meteor',
    maxRanks: 1,
    entryIds: [80263],
  },
  FIREMIND_TALENT: {
    id: 383499,
    name: 'Firemind',
    icon: 'spell_burningsoul',
    maxRanks: 2,
    entryIds: [80276],
  },
  FIRESTARTER_TALENT: {
    id: 205026,
    name: 'Firestarter',
    icon: 'spell_fire_fire',
    maxRanks: 1,
    entryIds: [80139],
  },
  FIRE_BLAST_TALENT: {
    id: 108853,
    name: 'Fire Blast',
    icon: 'spell_fire_fireball',
    maxRanks: 1,
    entryIds: [80282],
    manaCost: 2500,
  },
  FLAMESTRIKE_TALENT: {
    id: 2120,
    name: 'Flamestrike',
    icon: 'spell_fire_selfdestruct',
    maxRanks: 1,
    entryIds: [80258],
    manaCost: 6250,
  },
  FLAME_ACCELERANT_TALENT: {
    id: 203275,
    name: 'Flame Accelerant',
    icon: 'inv_ember',
    maxRanks: 2,
    entryIds: [80267],
  },
  FLAME_ON_TALENT: {
    id: 205029,
    name: 'Flame On',
    icon: 'inv_helm_circlet_firelands_d_01',
    maxRanks: 2,
    entryIds: [80256],
  },
  FLAME_PATCH_TALENT: {
    id: 205037,
    name: 'Flame Patch',
    icon: 'spell_mage_flameorb',
    maxRanks: 1,
    entryIds: [80259],
  },
  FLASH_FREEZE_TALENT: {
    id: 379993,
    name: 'Flash Freeze',
    icon: 'spell_hunter_icetrap',
    maxRanks: 1,
    entryIds: [80231],
  },
  FLOW_OF_TIME_TALENT: {
    id: 382268,
    name: 'Flow of Time',
    icon: 'spell_arcane_blink',
    maxRanks: 2,
    entryIds: [80153],
  },
  FLURRY_TALENT: {
    id: 44614,
    name: 'Flurry',
    icon: 'ability_warlock_burningembersblue',
    maxRanks: 1,
    entryIds: [80243],
    manaCost: 2500,
  },
  FORESIGHT_TALENT: {
    id: 384861,
    name: 'Foresight',
    icon: 'spell_mage_presenceofmind',
    maxRanks: 1,
    entryIds: [80203],
  },
  FRACTURED_FROST_TALENT: {
    id: 378448,
    name: 'Fractured Frost',
    icon: 'spell_fire_frostresistancetotem',
    maxRanks: 2,
    entryIds: [80250],
  },
  FREEZING_COLD_TALENT: {
    id: 386763,
    name: 'Freezing Cold',
    icon: 'spell_frost_glacier',
    maxRanks: 1,
    entryIds: [80143],
  },
  FREEZING_RAIN_TALENT: {
    id: 270233,
    name: 'Freezing Rain',
    icon: 'spell_frost_frozenorb',
    maxRanks: 1,
    entryIds: [80212],
  },
  FREEZING_WINDS_TALENT: {
    id: 382103,
    name: 'Freezing Winds',
    icon: 'spell_fire_blueflamering',
    maxRanks: 1,
    entryIds: [80214],
  },
  FRIGID_WINDS_TALENT: {
    id: 235224,
    name: 'Frigid Winds',
    icon: 'ability_mage_deepfreeze',
    maxRanks: 2,
    entryIds: [80188],
  },
  FROM_THE_ASHES_TALENT: {
    id: 342344,
    name: 'From the Ashes',
    icon: 'inv_misc_phoenixegg',
    maxRanks: 1,
    entryIds: [80289],
  },
  FROSTBITE_TALENT: {
    id: 378756,
    name: 'Frostbite',
    icon: 'spell_frost_frostarmor',
    maxRanks: 1,
    entryIds: [102428],
  },
  FROZEN_ORB_TALENT: {
    id: 84714,
    name: 'Frozen Orb',
    icon: 'spell_frost_frozenorb',
    maxRanks: 1,
    entryIds: [80242],
    manaCost: 2500,
  },
  FROZEN_TOUCH_TALENT: {
    id: 205030,
    name: 'Frozen Touch',
    icon: 'ability_mage_burstofcold',
    maxRanks: 1,
    entryIds: [80246],
  },
  GLACIAL_ASSAULT_TALENT: {
    id: 378947,
    name: 'Glacial Assault',
    icon: 'inv_staff_15',
    maxRanks: 2,
    entryIds: [80248],
  },
  GLACIAL_SPIKE_TALENT: {
    id: 199786,
    name: 'Glacial Spike',
    icon: 'ability_mage_glacialspike',
    maxRanks: 1,
    entryIds: [80220],
    manaCost: 2500,
  },
  GREATER_INVISIBILITY_TALENT: {
    id: 110959,
    name: 'Greater Invisibility',
    icon: 'ability_mage_greaterinvisibility',
    maxRanks: 1,
    entryIds: [80152],
  },
  HAILSTONES_TALENT: {
    id: 381244,
    name: 'Hailstones',
    icon: 'artifactability_frostmage_blackicicles',
    maxRanks: 2,
    entryIds: [80221],
  },
  HARMONIC_ECHO_TALENT: {
    id: 384683,
    name: 'Harmonic Echo',
    icon: 'ability_bastion_mage',
    maxRanks: 1,
    entryIds: [80305],
  },
  HYPERTHERMIA_TALENT: {
    id: 383860,
    name: 'Hyperthermia',
    icon: 'spell_fire_burnout',
    maxRanks: 1,
    entryIds: [80252],
  },
  ICE_BARRIER_TALENT: {
    id: 11426,
    name: 'Ice Barrier',
    icon: 'spell_ice_lament',
    maxRanks: 1,
    entryIds: [80176],
    manaCost: 7500,
  },
  ICE_BLOCK_TALENT: {
    id: 45438,
    name: 'Ice Block',
    icon: 'spell_frost_frost',
    maxRanks: 1,
    entryIds: [80181],
  },
  ICE_CALLER_TALENT: {
    id: 236662,
    name: 'Ice Caller',
    icon: 'spell_frost_icestorm',
    maxRanks: 1,
    entryIds: [80233],
  },
  ICE_FLOES_TALENT: {
    id: 108839,
    name: 'Ice Floes',
    icon: 'spell_mage_iceflows',
    maxRanks: 1,
    entryIds: [80162],
  },
  ICE_LANCE_TALENT: {
    id: 30455,
    name: 'Ice Lance',
    icon: 'spell_frost_frostblast',
    maxRanks: 1,
    entryIds: [80241],
    manaCost: 2500,
  },
  ICE_NOVA_TALENT: {
    id: 157997,
    name: 'Ice Nova',
    icon: 'spell_mage_icenova',
    maxRanks: 1,
    entryIds: [80186],
  },
  ICE_WARD_TALENT: {
    id: 205036,
    name: 'Ice Ward',
    icon: 'spell_frost_frostward',
    maxRanks: 1,
    entryIds: [80142],
  },
  ICY_PROPULSION_TALENT: {
    id: 378433,
    name: 'Icy Propulsion',
    icon: 'spell_frost_wisp',
    maxRanks: 1,
    entryIds: [80217],
  },
  ICY_VEINS_TALENT: {
    id: 12472,
    name: 'Icy Veins',
    icon: 'spell_frost_coldhearted',
    maxRanks: 1,
    entryIds: [80235],
  },
  ILLUMINATED_THOUGHTS_TALENT: {
    id: 384060,
    name: 'Illuminated Thoughts',
    icon: 'spell_arcane_focusedpower',
    maxRanks: 2,
    entryIds: [80292],
  },
  IMPETUS_TALENT: {
    id: 383676,
    name: 'Impetus',
    icon: 'spell_arcane_arcanetorrent',
    maxRanks: 1,
    entryIds: [80291],
  },
  IMPROVED_ARCANE_MISSILES_TALENT: {
    id: 383661,
    name: 'Improved Arcane Missiles',
    icon: 'spell_nature_starfall',
    maxRanks: 2,
    entryIds: [80309],
  },
  IMPROVED_CLEARCASTING_TALENT: {
    id: 321420,
    name: 'Improved Clearcasting',
    icon: 'spell_shadow_manaburn',
    maxRanks: 1,
    entryIds: [80293],
  },
  IMPROVED_COMBUSTION_TALENT: {
    id: 383967,
    name: 'Improved Combustion',
    icon: 'spell_fire_sealoffire',
    maxRanks: 1,
    entryIds: [80269],
  },
  IMPROVED_FLAMESTRIKE_TALENT: {
    id: 343230,
    name: 'Improved Flamestrike',
    icon: 'spell_fire_selfdestruct',
    maxRanks: 1,
    entryIds: [80257],
  },
  IMPROVED_FROST_NOVA_TALENT: {
    id: 343183,
    name: 'Improved Frost Nova',
    icon: 'spell_frost_frostnova',
    maxRanks: 1,
    entryIds: [80166],
  },
  IMPROVED_PRISMATIC_BARRIER_TALENT: {
    id: 321745,
    name: 'Improved Prismatic Barrier',
    icon: 'spell_magearmor',
    maxRanks: 1,
    entryIds: [80301],
  },
  IMPROVED_SCORCH_TALENT: {
    id: 383604,
    name: 'Improved Scorch',
    icon: 'ability_mage_fierypayback',
    maxRanks: 2,
    entryIds: [80279],
  },
  INCANTATION_OF_SWIFTNESS_TALENT: {
    id: 382293,
    name: 'Incantation of Swiftness',
    icon: 'rogue_burstofspeed',
    maxRanks: 2,
    entryIds: [80170],
  },
  INCANTERS_FLOW_TALENT: {
    id: 1463,
    name: "Incanter's Flow",
    icon: 'ability_mage_incantersabsorbtion',
    maxRanks: 1,
    entryIds: [80172],
  },
  INCENDIARY_ERUPTIONS_TALENT: {
    id: 383665,
    name: 'Incendiary Eruptions',
    icon: 'spell_fire_moltenblood',
    maxRanks: 1,
    entryIds: [80255],
  },
  INVISIBILITY_TALENT: {
    id: 66,
    name: 'Invisibility',
    icon: 'ability_mage_invisibility',
    maxRanks: 1,
    entryIds: [80177],
    manaCost: 7500,
  },
  KINDLING_TALENT: {
    id: 155148,
    name: 'Kindling',
    icon: 'spell_mage_kindling',
    maxRanks: 1,
    entryIds: [80265],
  },
  LIVING_BOMB_TALENT: {
    id: 44457,
    name: 'Living Bomb',
    icon: 'ability_mage_livingbomb',
    maxRanks: 1,
    entryIds: [80260],
    manaCost: 3750,
  },
  LONELY_WINTER_TALENT: {
    id: 205024,
    name: 'Lonely Winter',
    icon: 'achievement_dungeon_frozenthrone',
    maxRanks: 1,
    entryIds: [80238],
  },
  MANA_ADEPT_TALENT: {
    id: 321526,
    name: 'Mana Adept',
    icon: 'ability_mage_arcanebarrage',
    maxRanks: 1,
    entryIds: [80300],
  },
  MASS_POLYMORPH_TALENT: {
    id: 383121,
    name: 'Mass Polymorph',
    icon: 'spell_nature_doublepolymorph1',
    maxRanks: 1,
    entryIds: [80164],
    manaCost: 10000,
  },
  MASS_SLOW_TALENT: {
    id: 391102,
    name: 'Mass Slow',
    icon: 'inv_enchant_essencearcanelarge',
    maxRanks: 1,
    entryIds: [80167],
  },
  MASTER_OF_FLAME_TALENT: {
    id: 384174,
    name: 'Master of Flame',
    icon: 'inv_trinket_firelands_02',
    maxRanks: 1,
    entryIds: [80262],
  },
  MASTER_OF_TIME_TALENT: {
    id: 342249,
    name: 'Master of Time',
    icon: 'inv_belt_armor_waistoftime_d_01',
    maxRanks: 1,
    entryIds: [80159],
  },
  METEOR_TALENT: {
    id: 153561,
    name: 'Meteor',
    icon: 'spell_mage_meteor',
    maxRanks: 1,
    entryIds: [80146],
    manaCost: 2500,
  },
  MIRROR_IMAGE_TALENT: {
    id: 55342,
    name: 'Mirror Image',
    icon: 'spell_magic_lesserinvisibilty',
    maxRanks: 1,
    entryIds: [80183],
    manaCost: 5000,
  },
  NETHER_PRECISION_TALENT: {
    id: 383782,
    name: 'Nether Precision',
    icon: 'spell_arcane_blast_nightborne',
    maxRanks: 1,
    entryIds: [80295],
  },
  NETHER_TEMPEST_TALENT: {
    id: 114923,
    name: 'Nether Tempest',
    icon: 'spell_mage_nethertempest',
    maxRanks: 1,
    entryIds: [80199],
    manaCost: 3750,
  },
  ORB_BARRAGE_TALENT: {
    id: 384858,
    name: 'Orb Barrage',
    icon: 'spell_mage_arcaneorb_nightborne',
    maxRanks: 1,
    entryIds: [80196],
  },
  OVERFLOWING_ENERGY_TALENT: {
    id: 390218,
    name: 'Overflowing Energy',
    icon: 'spell_arcane_manatap',
    maxRanks: 1,
    entryIds: [80179],
  },
  PERPETUAL_WINTER_TALENT: {
    id: 378198,
    name: 'Perpetual Winter',
    icon: 'spell_frost_arcticwinds',
    maxRanks: 1,
    entryIds: [80247],
  },
  PHOENIX_FLAMES_TALENT: {
    id: 257541,
    name: 'Phoenix Flames',
    icon: 'artifactability_firemage_phoenixbolt',
    maxRanks: 1,
    entryIds: [80285],
  },
  PHOENIX_REBORN_TALENT: {
    id: 383476,
    name: 'Phoenix Reborn',
    icon: 'inv_sword_1h_artifactfelomelorn_d_01',
    maxRanks: 1,
    entryIds: [80266],
  },
  PIERCING_COLD_TALENT: {
    id: 378919,
    name: 'Piercing Cold',
    icon: 'spell_frost_frostbolt',
    maxRanks: 1,
    entryIds: [80229],
  },
  PRESENCE_OF_MIND_TALENT: {
    id: 205025,
    name: 'Presence of Mind',
    icon: 'spell_nature_enchantarmor',
    maxRanks: 1,
    entryIds: [80208],
  },
  PRISMATIC_BARRIER_TALENT: {
    id: 235450,
    name: 'Prismatic Barrier',
    icon: 'spell_magearmor',
    maxRanks: 1,
    entryIds: [80180],
    manaCost: 7500,
  },
  PRODIGIOUS_SAVANT_TALENT: {
    id: 384612,
    name: 'Prodigious Savant',
    icon: 'ability_mage_studentofthemind',
    maxRanks: 2,
    entryIds: [80197],
  },
  PYROBLAST_TALENT: {
    id: 11366,
    name: 'Pyroblast',
    icon: 'spell_fire_fireball02',
    maxRanks: 1,
    entryIds: [80283],
    manaCost: 5000,
  },
  PYROCLASM_TALENT: {
    id: 269650,
    name: 'Pyroclasm',
    icon: 'spell_shaman_lavasurge',
    maxRanks: 1,
    entryIds: [80277],
  },
  PYROMANIAC_TALENT: {
    id: 205020,
    name: 'Pyromaniac',
    icon: 'inv_misc_volatilefire',
    maxRanks: 1,
    entryIds: [80264],
  },
  PYROTECHNICS_TALENT: {
    id: 157642,
    name: 'Pyrotechnics',
    icon: 'spell_fire_flamebolt',
    maxRanks: 1,
    entryIds: [80286],
  },
  QUICK_WITTED_TALENT: {
    id: 382297,
    name: 'Quick Witted',
    icon: 'ability_priest_surgeofdarkness',
    maxRanks: 1,
    entryIds: [80161],
  },
  RADIANT_SPARK_TALENT: {
    id: 376103,
    name: 'Radiant Spark',
    icon: 'ability_bastion_mage',
    maxRanks: 1,
    entryIds: [80304],
    manaCost: 5000,
  },
  RAY_OF_FROST_TALENT: {
    id: 205021,
    name: 'Ray of Frost',
    icon: 'ability_mage_rayoffrost',
    maxRanks: 1,
    entryIds: [80226],
    manaCost: 5000,
  },
  REABSORPTION_TALENT: {
    id: 382820,
    name: 'Reabsorption',
    icon: 'spell_arcane_studentofmagic',
    maxRanks: 1,
    entryIds: [80184],
  },
  REDUPLICATION_TALENT: {
    id: 382569,
    name: 'Reduplication',
    icon: 'ability_mage_massinvisibility',
    maxRanks: 1,
    entryIds: [80185],
  },
  REMOVE_CURSE_TALENT: {
    id: 475,
    name: 'Remove Curse',
    icon: 'spell_nature_removecurse',
    maxRanks: 1,
    entryIds: [80175],
    manaCost: 3250,
  },
  RESONANCE_TALENT: {
    id: 205028,
    name: 'Resonance',
    icon: 'spell_arcane_arcane01',
    maxRanks: 1,
    entryIds: [80200],
  },
  REVERBERATE_TALENT: {
    id: 281482,
    name: 'Reverberate',
    icon: 'spell_arcane_arcane04',
    maxRanks: 1,
    entryIds: [80198],
  },
  RIGID_ICE_TALENT: {
    id: 382481,
    name: 'Rigid Ice',
    icon: 'spell_hunter_blackicetrap',
    maxRanks: 1,
    entryIds: [80168],
  },
  RING_OF_FROST_TALENT: {
    id: 113724,
    name: 'Ring of Frost',
    icon: 'spell_frost_ring_of_frost',
    maxRanks: 1,
    entryIds: [80144],
    manaCost: 20000,
  },
  RULE_OF_THREES_TALENT: {
    id: 264354,
    name: 'Rule of Threes',
    icon: 'spell_arcane_starfire',
    maxRanks: 1,
    entryIds: [80206],
  },
  RUNE_OF_POWER_TALENT: {
    id: 116011,
    name: 'Rune of Power',
    icon: 'spell_mage_runeofpower',
    maxRanks: 1,
    entryIds: [80171],
  },
  SCORCH_TALENT: {
    id: 2948,
    name: 'Scorch',
    icon: 'spell_fire_soulburn',
    maxRanks: 1,
    entryIds: [80281],
    manaCost: 2500,
  },
  SEARING_TOUCH_TALENT: {
    id: 269644,
    name: 'Searing Touch',
    icon: 'ability_warlock_backdraft',
    maxRanks: 1,
    entryIds: [80280],
  },
  SHATTER_TALENT: {
    id: 12982,
    name: 'Shatter',
    icon: 'spell_frost_frostshock',
    maxRanks: 1,
    entryIds: [80228],
  },
  SHIFTING_POWER_TALENT: {
    id: 382440,
    name: 'Shifting Power',
    icon: 'ability_ardenweald_mage',
    maxRanks: 1,
    entryIds: [80141],
    manaCost: 12500,
  },
  SHIMMER_TALENT: {
    id: 212653,
    name: 'Shimmer',
    icon: 'spell_arcane_massdispel',
    maxRanks: 1,
    entryIds: [80163],
    manaCost: 5000,
  },
  SIPHON_STORM_TALENT: {
    id: 384187,
    name: 'Siphon Storm',
    icon: 'ability_monk_forcesphere_arcane',
    maxRanks: 1,
    entryIds: [80210],
  },
  SLICK_ICE_TALENT: {
    id: 382144,
    name: 'Slick Ice',
    icon: 'inv_enchant_shardshadowfrostlarge',
    maxRanks: 1,
    entryIds: [80216],
  },
  SLIPSTREAM_TALENT: {
    id: 236457,
    name: 'Slipstream',
    icon: 'spell_holy_mindsooth',
    maxRanks: 1,
    entryIds: [80296],
  },
  SLOW_TALENT: {
    id: 31589,
    name: 'Slow',
    icon: 'spell_nature_slow',
    maxRanks: 1,
    entryIds: [80154],
    manaCost: 2500,
  },
  SNAP_FREEZE_TALENT: {
    id: 378901,
    name: 'Snap Freeze',
    icon: 'ability_mage_freeze',
    maxRanks: 1,
    entryIds: [80215],
  },
  SNOWSTORM_TALENT: {
    id: 381706,
    name: 'Snowstorm',
    icon: 'spell_fire_bluerainoffire',
    maxRanks: 2,
    entryIds: [80234],
  },
  SPELLSTEAL_TALENT: {
    id: 30449,
    name: 'Spellsteal',
    icon: 'spell_arcane_arcane02',
    maxRanks: 1,
    entryIds: [80140],
    manaCost: 52500,
  },
  SPLINTERING_COLD_TALENT: {
    id: 379049,
    name: 'Splintering Cold',
    icon: 'spell_fire_blueflamestrike',
    maxRanks: 2,
    entryIds: [80225],
  },
  SPLITTING_ICE_TALENT: {
    id: 56377,
    name: 'Splitting Ice',
    icon: 'spell_frost_ice_shards',
    maxRanks: 1,
    entryIds: [80224],
  },
  SUBZERO_TALENT: {
    id: 380154,
    name: 'Subzero',
    icon: 'spell_ice_magicdamage',
    maxRanks: 2,
    entryIds: [80223],
  },
  SUMMON_WATER_ELEMENTAL_TALENT: {
    id: 31687,
    name: 'Summon Water Elemental',
    icon: 'spell_frost_summonwaterelemental_2',
    maxRanks: 1,
    entryIds: [80237],
    manaCost: 7500,
  },
  SUN_KINGS_BLESSING_TALENT: {
    id: 383886,
    name: "Sun King's Blessing",
    icon: 'ability_mage_firestarter',
    maxRanks: 1,
    entryIds: [80273],
  },
  SUPERNOVA_TALENT: {
    id: 157980,
    name: 'Supernova',
    icon: 'spell_mage_supernova',
    maxRanks: 1,
    entryIds: [80290],
  },
  TEMPERED_FLAMES_TALENT: {
    id: 383659,
    name: 'Tempered Flames',
    icon: 'ability_mage_greaterpyroblast',
    maxRanks: 1,
    entryIds: [80268],
  },
  TEMPEST_BARRIER_TALENT: {
    id: 382289,
    name: 'Tempest Barrier',
    icon: 'inv_shield_1h_artifactstormfist_d_04',
    maxRanks: 2,
    entryIds: [80169],
  },
  TEMPORAL_VELOCITY_TALENT: {
    id: 382826,
    name: 'Temporal Velocity',
    icon: 'ability_socererking_arcaneacceleration',
    maxRanks: 2,
    entryIds: [80156],
  },
  TEMPORAL_WARP_TALENT: {
    id: 386539,
    name: 'Temporal Warp',
    icon: 'ability_bossmagistrix_timewarp2',
    maxRanks: 1,
    entryIds: [80150],
  },
  THERMAL_VOID_TALENT: {
    id: 155149,
    name: 'Thermal Void',
    icon: 'spell_mage_thermalvoid',
    maxRanks: 1,
    entryIds: [80219],
  },
  TIME_ANOMALY_TALENT: {
    id: 383243,
    name: 'Time Anomaly',
    icon: 'ability_mage_timewarp',
    maxRanks: 1,
    entryIds: [80151],
  },
  TIME_MANIPULATION_TALENT: {
    id: 387807,
    name: 'Time Manipulation',
    icon: 'spell_nature_timestop',
    maxRanks: 2,
    entryIds: [80189],
  },
  TOME_OF_ANTONIDAS_TALENT: {
    id: 382490,
    name: 'Tome of Antonidas',
    icon: 'inv_misc_book_18',
    maxRanks: 1,
    entryIds: [80155],
  },
  TOME_OF_RHONIN_TALENT: {
    id: 382493,
    name: 'Tome of Rhonin',
    icon: 'inv_misc_book_04',
    maxRanks: 1,
    entryIds: [80187],
  },
  TOUCH_OF_THE_MAGI_TALENT: {
    id: 321507,
    name: 'Touch of the Magi',
    icon: 'ability_mage_netherwindpresence',
    maxRanks: 1,
    entryIds: [80302],
    manaCost: 12500,
  },
  VOLATILE_DETONATION_TALENT: {
    id: 389627,
    name: 'Volatile Detonation',
    icon: 'spell_fire_burnout',
    maxRanks: 1,
    entryIds: [80145],
  },
  WILDFIRE_TALENT: {
    id: 383489,
    name: 'Wildfire',
    icon: 'ability_warlock_inferno',
    maxRanks: 2,
    entryIds: [80270],
  },
  WINTERS_PROTECTION_TALENT: {
    id: 382424,
    name: "Winter's Protection",
    icon: 'spell_ice_rune',
    maxRanks: 2,
    entryIds: [80182],
  },
  WINTERTIDE_TALENT: {
    id: 378406,
    name: 'Wintertide',
    icon: 'ability_deathknight_frozencenter',
    maxRanks: 2,
    entryIds: [80236],
  },
});

export default talents;
export { talents as TALENTS_MAGE };
