// Generated file, changes will eventually be overwritten!
import { createTalentList } from './types';

const talents = createTalentList({
  //Shared
  SOOTHING_MIST_TALENT: {
    id: 115175,
    name: 'Soothing Mist',
    icon: 'ability_monk_soothingmists',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
    manaCost: 0,
  },
  RISING_SUN_KICK_TALENT: {
    id: 107428,
    name: 'Rising Sun Kick',
    icon: 'ability_monk_risingsunkick',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
    chiCost: 2,
  },
  TIGERS_LUST_TALENT: {
    id: 116841,
    name: "Tiger's Lust",
    icon: 'ability_monk_tigerslust',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  ROLL_TALENT: {
    id: 109132,
    name: 'Roll',
    icon: 'ability_monk_roll',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  CALMING_PRESENCE_TALENT: {
    id: 388664,
    name: 'Calming Presence',
    icon: 'inv_misc_orb_01',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  PARALYSIS_TALENT: {
    id: 344359,
    name: 'Paralysis',
    icon: 'ability_monk_paralysis',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  TIGER_TAIL_SWEEP_TALENT: {
    id: 264348,
    name: 'Tiger Tail Sweep',
    icon: 'ability_monk_legsweep',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  HEAVY_AIR_TALENT: {
    id: 388671,
    name: 'Heavy Air',
    icon: 'spell_lightning_lightningbolt01',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  VIVIFY_TALENT: {
    id: 231602,
    name: 'Vivify',
    icon: 'ability_monk_vivify',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  DETOX_TALENT: {
    id: 218164,
    name: 'Detox',
    icon: 'ability_rogue_imrovedrecuperate',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
    energyCost: 20,
  },
  DISABLE_TALENT: {
    id: 116095,
    name: 'Disable',
    icon: 'ability_shockwave',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
    energyCost: 15,
  },
  GRACE_OF_THE_CRANE_TALENT: {
    id: 388811,
    name: 'Grace of the Crane',
    icon: 'monk_ability_cherrymanatea',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  VIVACIOUS_VIVIFICATION_TALENT: {
    id: 388812,
    name: 'Vivacious Vivification',
    icon: 'ability_monk_vivify',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  FEROCITY_OF_XUEN_TALENT: {
    id: 388674,
    name: 'Ferocity of Xuen',
    icon: 'ability_mount_pinktiger',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  ELUSIVE_MISTS_TALENT: {
    id: 115175,
    name: 'Elusive Mists',
    icon: 'ability_monk_soothingmists',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
    manaCost: 0,
  },
  TRANSCENDENCE_TALENT: {
    id: 101643,
    name: 'Transcendence',
    icon: 'monk_ability_transcendence',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  SPEAR_HAND_STRIKE_TALENT: {
    id: 116705,
    name: 'Spear Hand Strike',
    icon: 'ability_monk_spearhand',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  FORTIFYING_BREW_TALENT: {
    id: 322960,
    name: 'Fortifying Brew',
    icon: 'ability_monk_fortifyingale_new',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  CHI_BURST_TALENT: {
    id: 123986,
    name: 'Chi Burst',
    icon: 'spell_arcane_arcanetorrent',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
  },
  CHI_WAVE_TALENT: {
    id: 115098,
    name: 'Chi Wave',
    icon: 'ability_monk_chiwave',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
  },
  PROVOKE_TALENT: {
    id: 328670,
    name: 'Provoke',
    icon: 'ability_monk_provoke',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  RING_OF_PEACE_TALENT: {
    id: 116844,
    name: 'Ring of Peace',
    icon: 'spell_monk_ringofpeace',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  FAST_FEET_TALENT: {
    id: 388809,
    name: 'Fast Feet',
    icon: 'ability_monk_risingsunkick',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  CHI_TORPEDO_TALENT: {
    id: 115008,
    name: 'Chi Torpedo',
    icon: 'ability_monk_quitornado',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  CELERITY_TALENT: {
    id: 115173,
    name: 'Celerity',
    icon: 'ability_monk_quipunch',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  ROLL_OUT_TALENT: {
    id: 388810,
    name: 'Roll Out',
    icon: 'ability_monk_roll',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  DIFFUSE_MAGIC_TALENT: {
    id: 122783,
    name: 'Diffuse Magic',
    icon: 'spell_monk_diffusemagic',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  EYE_OF_THE_TIGER_TALENT: {
    id: 196607,
    name: 'Eye of the Tiger',
    icon: 'ability_druid_primalprecision',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  DAMPEN_HARM_TALENT: {
    id: 122278,
    name: 'Dampen Harm',
    icon: 'ability_monk_dampenharm',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  TOUCH_OF_DEATH_TALENT: {
    id: 322113,
    name: 'Touch of Death',
    icon: 'ability_monk_touchofdeath',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  EXPEL_HARM_TALENT: {
    id: 322101,
    name: 'Expel Harm',
    icon: 'ability_monk_expelharm',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
    energyCost: 15,
  },
  ESCAPE_FROM_REALITY_TALENT: {
    id: 343250,
    name: 'Escape from Reality',
    icon: 'monk_ability_transcendence',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  WINDWALKING_TALENT: {
    id: 157411,
    name: 'Windwalking',
    icon: 'monk_stance_whitetiger',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  FATAL_TOUCH_TALENT: {
    id: 337296,
    name: 'Fatal Touch',
    icon: 'ability_monk_touchofdeath',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  SUMMON_JADE_SERPENT_STATUE_TALENT: {
    id: 115313,
    name: 'Summon Jade Serpent Statue',
    icon: 'ability_monk_summonserpentstatue',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  SUMMON_BLACK_OX_STATUE_TALENT: {
    id: 115315,
    name: 'Summon Black Ox Statue',
    icon: 'monk_ability_summonoxstatue',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },

  //Mistweaver
  ENVELOPING_MIST_MISTWEAVER_TALENT: {
    id: 124682,
    name: 'Enveloping Mist',
    icon: 'spell_monk_envelopingmist',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
    manaCost: 2500,
  },
  ESSENCE_FONT_MISTWEAVER_TALENT: {
    id: 191837,
    name: 'Essence Font',
    icon: 'ability_monk_essencefont',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
    manaCost: 3500,
  },
  RENEWING_MIST_MISTWEAVER_TALENT: {
    id: 115151,
    name: 'Renewing Mist',
    icon: 'ability_monk_renewingmists',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
    manaCost: 500,
  },
  LIFE_COCOON_MISTWEAVER_TALENT: {
    id: 116849,
    name: 'Life Cocoon',
    icon: 'ability_monk_chicocoon',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
    manaCost: 1000,
  },
  THUNDER_FOCUS_TEA_MISTWEAVER_TALENT: {
    id: 116680,
    name: 'Thunder Focus Tea',
    icon: 'ability_monk_thunderfocustea',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  INVIGORATING_MISTS_MISTWEAVER_TALENT: {
    id: 274586,
    name: 'Invigorating Mists',
    icon: 'ability_monk_vivify',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  TEACHINGS_OF_THE_MONASTERY_MISTWEAVER_TALENT: {
    id: 116645,
    name: 'Teachings of the Monastery',
    icon: 'passive_monk_teachingsofmonastery',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  RESTORAL_MISTWEAVER_TALENT: {
    id: 388615,
    name: 'Restoral',
    icon: 'spell_monk_revival',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'choice',
    manaCost: 2000,
  },
  REVIVAL_MISTWEAVER_TALENT: {
    id: 115310,
    name: 'Revival',
    icon: 'spell_monk_revival',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'choice',
    manaCost: 2000,
  },
  HEALING_ELIXIR_MISTWEAVER_TALENT: {
    id: 122281,
    name: 'Healing Elixir',
    icon: 'ability_monk_jasmineforcetea',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  MASTERY_OF_MIST_MISTWEAVER_TALENT: {
    id: 281231,
    name: 'Mastery of Mist',
    icon: 'ability_monk_renewingmists',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  SPIRIT_OF_THE_CRANE_MISTWEAVER_TALENT: {
    id: 210802,
    name: 'Spirit of the Crane',
    icon: 'monk_stance_redcrane',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  MISTS_OF_LIFE_MISTWEAVER_TALENT: {
    id: 388548,
    name: 'Mists of Life',
    icon: 'ability_monk_chicocoon',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  UPLIFTED_SPIRITS_MISTWEAVER_TALENT: {
    id: 388551,
    name: 'Uplifted Spirits',
    icon: 'spell_monk_revival',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  ZEN_PULSE_MISTWEAVER_TALENT: {
    id: 124081,
    name: 'Zen Pulse',
    icon: 'ability_monk_forcesphere',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  MANA_TEA_MISTWEAVER_TALENT: {
    id: 197908,
    name: 'Mana Tea',
    icon: 'monk_ability_cherrymanatea',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  LIFECYCLES_MISTWEAVER_TALENT: {
    id: 197915,
    name: 'Lifecycles',
    icon: 'ability_monk_souldance',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  NOURISHING_CHI_MISTWEAVER_TALENT: {
    id: 387765,
    name: 'Nourishing Chi',
    icon: 'inv_misc_gem_pearl_06',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  OVERFLOWING_MISTS_MISTWEAVER_TALENT: {
    id: 388511,
    name: 'Overflowing Mists',
    icon: 'spell_monk_envelopingmist',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  INVOKE_CHI_JI_THE_RED_CRANE_MISTWEAVER_TALENT: {
    id: 325197,
    name: 'Invoke Chi-Ji, the Red Crane',
    icon: 'inv_pet_cranegod',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
    manaCost: 2500,
  },
  INVOKE_YULON_THE_JADE_SERPENT_MISTWEAVER_TALENT: {
    id: 322118,
    name: "Invoke Yu'lon, the Jade Serpent",
    icon: 'ability_monk_dragonkick',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
    manaCost: 2500,
  },
  ACCUMULATING_MIST_MISTWEAVER_TALENT: {
    id: 388564,
    name: 'Accumulating Mist',
    icon: 'ability_monk_zenmeditation',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  ZEN_REVERBERATION_MISTWEAVER_TALENT: {
    id: 388604,
    name: 'Zen Reverberation',
    icon: 'spell_monk_nimblebrew',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  SONG_OF_CHI_JI_MISTWEAVER_TALENT: {
    id: 198898,
    name: 'Song of Chi-Ji',
    icon: 'inv_chaos_orb',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  RAPID_DIFFUSION_NYI_MISTWEAVER_TALENT: {
    id: 388847,
    name: 'Rapid Diffusion [NYI]',
    icon: 'ability_monk_chiswirl',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  CALMING_COALESCENCE_MISTWEAVER_TALENT: {
    id: 388218,
    name: 'Calming Coalescence',
    icon: 'ability_monk_healthsphere',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  YULONS_WHISPER_MISTWEAVER_TALENT: {
    id: 388038,
    name: "Yu'lon's Whisper",
    icon: 'ability_monk_dragonkick',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  REFRESHING_JADE_WIND_MISTWEAVER_TALENT: {
    id: 196725,
    name: 'Refreshing Jade Wind',
    icon: 'ability_monk_rushingjadewind',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
    manaCost: 1500,
  },
  MIST_WRAP_MISTWEAVER_TALENT: {
    id: 197900,
    name: 'Mist Wrap',
    icon: 'ability_monk_pathofmists',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  ENVELOPING_BREATH_MISTWEAVER_TALENT: {
    id: 343655,
    name: 'Enveloping Breath',
    icon: 'ability_monk_dragonkick',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  DANCING_MISTS_MISTWEAVER_TALENT: {
    id: 388701,
    name: 'Dancing Mists',
    icon: 'ability_monk_souldance',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  FONT_OF_LIFE_MISTWEAVER_TALENT: {
    id: 337209,
    name: 'Font of Life',
    icon: 'ability_monk_essencefont',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  FAELINE_STOMP_MISTWEAVER_TALENT: {
    id: 388193,
    name: 'Faeline Stomp',
    icon: 'ability_ardenweald_monk',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
    manaCost: 2000,
  },
  CLOUDED_FOCUS_MISTWEAVER_TALENT: {
    id: 388047,
    name: 'Clouded Focus',
    icon: 'ability_monk_soothingmists',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  ANCIENT_TEACHINGS_OF_THE_MONASTERY_MISTWEAVER_TALENT: {
    id: 388023,
    name: 'Ancient Teachings of the Monastery',
    icon: 'passive_monk_teachingsofmonastery',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  GIFT_OF_THE_CELESTIALS_MISTWEAVER_TALENT: {
    id: 388212,
    name: 'Gift of the Celestials',
    icon: 'inv_pet_jadeserpentpet',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  JADE_BOND_MISTWEAVER_TALENT: {
    id: 388031,
    name: 'Jade Bond',
    icon: 'inv_inscription_deck_jadeserpent',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  UPWELLING_MISTWEAVER_TALENT: {
    id: 274963,
    name: 'Upwelling',
    icon: 'ability_monk_surgingmist',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  FOCUSED_THUNDER_MISTWEAVER_TALENT: {
    id: 197895,
    name: 'Focused Thunder',
    icon: 'spell_monk_nimblebrew',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  BONEDUST_BREW_MISTWEAVER_TALENT: {
    id: 386276,
    name: 'Bonedust Brew',
    icon: 'ability_maldraxxus_monk',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  ANCIENT_CONCORDANCE_NYI_MISTWEAVER_TALENT: {
    id: 388740,
    name: 'Ancient Concordance [NYI]',
    icon: 'spell_animaardenweald_beam',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  PEACEFUL_MENDING_MISTWEAVER_TALENT: {
    id: 388593,
    name: 'Peaceful Mending',
    icon: 'ability_monk_surgingmist',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  SECRET_INFUSION_MISTWEAVER_TALENT: {
    id: 388491,
    name: 'Secret Infusion',
    icon: 'ability_monk_thunderfocustea',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  MISTY_PEAKS_NYI_MISTWEAVER_TALENT: {
    id: 388682,
    name: 'Misty Peaks [NYI]',
    icon: 'ability_monk_renewingmists',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  RESPLENDENT_MIST_MISTWEAVER_TALENT: {
    id: 388020,
    name: 'Resplendent Mist',
    icon: 'spell_nature_abolishmagic',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  AWAKENED_FAELINE_NYI_MISTWEAVER_TALENT: {
    id: 388779,
    name: 'Awakened Faeline [NYI]',
    icon: 'ability_ardenweald_monk',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  TEA_OF_PLENTY_MISTWEAVER_TALENT: {
    id: 388517,
    name: 'Tea of Plenty',
    icon: 'inv_misc_pearlmilktea',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  RESTORATIVE_PROLIFERATION_MISTWEAVER_TALENT: {
    id: 388509,
    name: 'Restorative Proliferation',
    icon: 'ability_monk_souldance',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  UNISON_MISTWEAVER_TALENT: {
    id: 388477,
    name: 'Unison',
    icon: 'ability_creature_cursed_04',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  INVOKERS_DELIGHT_MISTWEAVER_TALENT: {
    id: 388661,
    name: "Invoker's Delight",
    icon: 'inv_inscription_80_warscroll_battleshout',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  RISING_MIST_MISTWEAVER_TALENT: {
    id: 274909,
    name: 'Rising Mist',
    icon: 'ability_monk_effuse',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  TEAR_OF_MORNING_MISTWEAVER_TALENT: {
    id: 387991,
    name: 'Tear of Morning',
    icon: 'ability_monk_uplift',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  ATTENUATION_MISTWEAVER_TALENT: {
    id: 386941,
    name: 'Attenuation',
    icon: 'spell_animamaldraxxus_nova',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  BOUNTIFUL_BREW_MISTWEAVER_TALENT: {
    id: 386949,
    name: 'Bountiful Brew',
    icon: 'ability_maldraxxus_monk',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },

  //Windwalker
  FISTS_OF_FURY_WINDWALKER_TALENT: {
    id: 113656,
    name: 'Fists of Fury',
    icon: 'monk_ability_fistoffury',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
    chiCost: 3,
  },
  TOUCH_OF_KARMA_WINDWALKER_TALENT: {
    id: 122470,
    name: 'Touch of Karma',
    icon: 'ability_monk_touchofkarma',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  ASCENSION_WINDWALKER_TALENT: {
    id: 115396,
    name: 'Ascension',
    icon: 'ability_monk_ascension',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  POWER_STRIKES_WINDWALKER_TALENT: {
    id: 121817,
    name: 'Power Strikes',
    icon: 'ability_monk_powerstrikes',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  FEATHERS_OF_A_HUNDRED_FLOCKS_WINDWALKER_TALENT: {
    id: 388846,
    name: 'Feathers of a Hundred Flocks',
    icon: 'ability_monk_forcesphere_pink',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  TOUCH_OF_THE_TIGER_WINDWALKER_TALENT: {
    id: 388856,
    name: 'Touch of the Tiger',
    icon: 'ability_monk_tigerpalm',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  FLYING_SERPENT_KICK_WINDWALKER_TALENT: {
    id: 101545,
    name: 'Flying Serpent Kick',
    icon: 'ability_monk_flyingdragonkick',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  FLASHING_FISTS_WINDWALKER_TALENT: {
    id: 388854,
    name: 'Flashing Fists',
    icon: 'monk_ability_fistoffury',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  OPEN_PALM_STRIKES_WINDWALKER_TALENT: {
    id: 279918,
    name: 'Open Palm Strikes',
    icon: 'monk_ability_fistoffury',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  MARK_OF_THE_CRANE_WINDWALKER_TALENT: {
    id: 228287,
    name: 'Mark of the Crane',
    icon: 'ability_monk_cranekick_new',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  GALE_BURST_WINDWALKER_TALENT: {
    id: 195399,
    name: 'Gale Burst',
    icon: 'ability_monk_palmstrike',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  GLORY_OF_THE_DAWN_WINDWALKER_TALENT: {
    id: 288634,
    name: 'Glory of the Dawn',
    icon: 'ability_monk_mightyoxkick',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  SHADOWBOXING_TREADS_WINDWALKER_TALENT: {
    id: 331512,
    name: 'Shadowboxing Treads',
    icon: 'ability_monk_roundhousekick',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  HIT_SCHEME_WINDWALKER_TALENT: {
    id: 383695,
    name: 'Hit Scheme',
    icon: 'ability_monk_roundhousekick',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  SERENITY_WINDWALKER_TALENT: {
    id: 152173,
    name: 'Serenity',
    icon: 'ability_monk_serenity',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
  },
  STORM_EARTH_AND_FIRE_WINDWALKER_TALENT: {
    id: 137639,
    name: 'Storm, Earth, and Fire',
    icon: 'spell_nature_giftofthewild',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
  },
  MERIDIAN_STRIKES_WINDWALKER_TALENT: {
    id: 278580,
    name: 'Meridian Strikes',
    icon: 'ability_monk_touchofdeath',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  JADE_IGNITION_WINDWALKER_TALENT: {
    id: 337483,
    name: 'Jade Ignition',
    icon: 'ability_monk_chiexplosion',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  DANCE_OF_CHI_JI_WINDWALKER_TALENT: {
    id: 325201,
    name: 'Dance of Chi-Ji',
    icon: 'ability_monk_cranekick_new',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  INNER_PEACE_WINDWALKER_TALENT: {
    id: 195243,
    name: 'Inner Peace',
    icon: 'ability_monk_jasmineforcetea',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  DRINKING_HORN_COVER_WINDWALKER_TALENT: {
    id: 209256,
    name: 'Drinking Horn Cover',
    icon: 'ability_warrior_unrelentingassault',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  SPIRITUAL_FOCUS_WINDWALKER_TALENT: {
    id: 280197,
    name: 'Spiritual Focus',
    icon: 'spell_nature_giftofthewild',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  STRIKE_OF_THE_WINDLORD_WINDWALKER_TALENT: {
    id: 205320,
    name: 'Strike of the Windlord',
    icon: 'inv_hand_1h_artifactskywall_d_01',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
    chiCost: 2,
  },
  RUSHING_JADE_WIND_WINDWALKER_TALENT: {
    id: 116847,
    name: 'Rushing Jade Wind',
    icon: 'ability_monk_rushingjadewind',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
    chiCost: 1,
  },
  HIDDEN_MASTERS_FORBIDDEN_TOUCH_WINDWALKER_TALENT: {
    id: 213112,
    name: "Hidden Master's Forbidden Touch",
    icon: 'ability_monk_touchofdeath',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  INVOKE_XUEN_THE_WHITE_TIGER_WINDWALKER_TALENT: {
    id: 123904,
    name: 'Invoke Xuen, the White Tiger',
    icon: 'ability_monk_summontigerstatue',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  TEACHINGS_OF_THE_MONASTERY_WINDWALKER_TALENT: {
    id: 116645,
    name: 'Teachings of the Monastery',
    icon: 'passive_monk_teachingsofmonastery',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  THUNDERFIST_WINDWALKER_TALENT: {
    id: 238131,
    name: 'Thunderfist',
    icon: 'inv_hand_1h_artifactskywall_d_01',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  CRANE_VORTEX_WINDWALKER_TALENT: {
    id: 388848,
    name: 'Crane Vortex',
    icon: 'ability_monk_cranekick_new',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  XUENS_BOND_WINDWALKER_TALENT: {
    id: 336616,
    name: "Xuen's Bond",
    icon: 'ability_demonhunter_netherbond',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  FURY_OF_XUEN_WINDWALKER_TALENT: {
    id: 287055,
    name: 'Fury of Xuen',
    icon: 'ability_monk_prideofthetiger',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  EMPOWERED_TIGER_LIGHTNING_WINDWALKER_TALENT: {
    id: 335913,
    name: 'Empowered Tiger Lightning',
    icon: 'ability_monk_summontigerstatue',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  RISING_STAR_WINDWALKER_TALENT: {
    id: 388849,
    name: 'Rising Star',
    icon: 'ability_monk_risingsunkick',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  BONEDUST_BREW_WINDWALKER_TALENT: {
    id: 386276,
    name: 'Bonedust Brew',
    icon: 'ability_maldraxxus_monk',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  FATAL_FLYING_GUILLOTINE_WINDWALKER_TALENT: {
    id: 331679,
    name: 'Fatal Flying Guillotine',
    icon: 'ability_monk_touchofdeath',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  XUENS_BATTLEGEAR_WINDWALKER_TALENT: {
    id: 337481,
    name: "Xuen's Battlegear",
    icon: 'monk_stance_whitetiger',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  TRANSFER_THE_POWER_WINDWALKER_TALENT: {
    id: 195300,
    name: 'Transfer the Power',
    icon: 'monk_ability_fistoffury',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  WHIRLING_DRAGON_PUNCH_WINDWALKER_TALENT: {
    id: 152175,
    name: 'Whirling Dragon Punch',
    icon: 'ability_monk_hurricanestrike',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  FAELINE_STOMP_WINDWALKER_TALENT: {
    id: 388193,
    name: 'Faeline Stomp',
    icon: 'ability_ardenweald_monk',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
    manaCost: 2000,
  },
  CALCULATED_STRIKES_WINDWALKER_TALENT: {
    id: 336526,
    name: 'Calculated Strikes',
    icon: 'spell_magic_lesserinvisibilty',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  ATTENUATION_WINDWALKER_TALENT: {
    id: 386941,
    name: 'Attenuation',
    icon: 'spell_animamaldraxxus_nova',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  KEEFERS_SKYREACH_WINDWALKER_TALENT: {
    id: 337334,
    name: "Keefer's Skyreach",
    icon: 'inv__fistofthewhitetiger',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  INVOKERS_DELIGHT_WINDWALKER_TALENT: {
    id: 388661,
    name: "Invoker's Delight",
    icon: 'inv_inscription_80_warscroll_battleshout',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  WAY_OF_THE_FAE_WINDWALKER_TALENT: {
    id: 337303,
    name: 'Way of the Fae',
    icon: 'spell_animaardenweald_beam',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  LAST_EMPERORS_CAPACITOR_WINDWALKER_TALENT: {
    id: 337292,
    name: "Last Emperor's Capacitor",
    icon: 'ability_warrior_unrelentingassault',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },

  //Brewmaster
  KEG_SMASH_BREWMASTER_TALENT: {
    id: 121253,
    name: 'Keg Smash',
    icon: 'achievement_brewery_2',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
    energyCost: 40,
  },
  STAGGER_BREWMASTER_TALENT: {
    id: 115069,
    name: 'Stagger',
    icon: 'monk_stance_drunkenox',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  PURIFYING_BREW_BREWMASTER_TALENT: {
    id: 343743,
    name: 'Purifying Brew',
    icon: 'inv_misc_beer_06',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  SHUFFLE_BREWMASTER_TALENT: {
    id: 322120,
    name: 'Shuffle',
    icon: 'ability_monk_shuffle',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  HIT_SCHEME_BREWMASTER_TALENT: {
    id: 383695,
    name: 'Hit Scheme',
    icon: 'ability_monk_roundhousekick',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  GIFT_OF_THE_OX_BREWMASTER_TALENT: {
    id: 124502,
    name: 'Gift of the Ox',
    icon: 'ability_druid_giftoftheearthmother',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  HEALING_ELIXIR_BREWMASTER_TALENT: {
    id: 122281,
    name: 'Healing Elixir',
    icon: 'ability_monk_jasmineforcetea',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  QUICK_SIP_BREWMASTER_TALENT: {
    id: 383764,
    name: 'Quick Sip',
    icon: 'achievement_faction_brewmaster',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  SPECIAL_DELIVERY_BREWMASTER_TALENT: {
    id: 196730,
    name: 'Special Delivery',
    icon: 'achievement_brewery_2',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'choice',
  },
  RUSHING_JADE_WIND_BREWMASTER_TALENT: {
    id: 116847,
    name: 'Rushing Jade Wind',
    icon: 'ability_monk_rushingjadewind',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'choice',
    chiCost: 1,
  },
  CELESTIAL_FLAMES_BREWMASTER_TALENT: {
    id: 325177,
    name: 'Celestial Flames',
    icon: 'inv_misc_volatilefire',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  CELESTIAL_BREW_BREWMASTER_TALENT: {
    id: 322510,
    name: 'Celestial Brew',
    icon: 'ability_monk_ironskinbrew',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  STAGGERING_STRIKES_NYI_BREWMASTER_TALENT: {
    id: 387625,
    name: 'Staggering Strikes [NYI]',
    icon: 'ability_monk_blackoutstrike',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  GRACEFUL_EXIT_BREWMASTER_TALENT: {
    id: 387256,
    name: 'Graceful Exit',
    icon: 'ability_rogue_sprint_blue',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  ZEN_MEDITATION_BREWMASTER_TALENT: {
    id: 115176,
    name: 'Zen Meditation',
    icon: 'ability_monk_zenmeditation',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  CLASH_BREWMASTER_TALENT: {
    id: 324312,
    name: 'Clash',
    icon: 'ability_monk_clashingoxcharge',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  BREATH_OF_FIRE_BREWMASTER_TALENT: {
    id: 115181,
    name: 'Breath of Fire',
    icon: 'ability_monk_breathoffire',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  GAI_PLINS_IMPERIAL_BREW_BREWMASTER_TALENT: {
    id: 383700,
    name: "Gai Plin's Imperial Brew",
    icon: 'inv_misc_beer_05',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  STRENGTH_OF_SPIRIT_BREWMASTER_TALENT: {
    id: 387276,
    name: 'Strength of Spirit',
    icon: 'ability_monk_healthsphere',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  FUNDAMENTAL_OBSERVATION_BREWMASTER_TALENT: {
    id: 387035,
    name: 'Fundamental Observation',
    icon: 'ability_monk_zenmeditation',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  FACE_PALM_BREWMASTER_TALENT: {
    id: 213116,
    name: 'Face Palm',
    icon: 'ability_monk_tigerpalm',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  SALSALABIMS_STRENGTH_BREWMASTER_TALENT: {
    id: 383697,
    name: "Sal'salabim's Strength",
    icon: 'ability_warrior_unrelentingassault',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  SCALDING_BREW_BREWMASTER_TALENT: {
    id: 383698,
    name: 'Scalding Brew',
    icon: 'spell_brew_bolt_dark',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  FORTIFYING_BREW_BREWMASTER_TALENT: {
    id: 322960,
    name: 'Fortifying Brew',
    icon: 'ability_monk_fortifyingale_new',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  BOB_AND_WEAVE_BREWMASTER_TALENT: {
    id: 280515,
    name: 'Bob and Weave',
    icon: 'ability_creature_cursed_04',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
  },
  BLACK_OX_BREW_BREWMASTER_TALENT: {
    id: 115399,
    name: 'Black Ox Brew',
    icon: 'ability_monk_chibrew',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
  },
  INVOKE_NIUZAO_THE_BLACK_OX_BREWMASTER_TALENT: {
    id: 322740,
    name: 'Invoke Niuzao, the Black Ox',
    icon: 'spell_monk_brewmaster_spec',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  TRAINING_OF_NIUZAO_BREWMASTER_TALENT: {
    id: 383714,
    name: 'Training of Niuzao',
    icon: 'monk_stance_drunkenox',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  LIGHT_BREWING_BREWMASTER_TALENT: {
    id: 325093,
    name: 'Light Brewing',
    icon: 'spell_brew_wheat',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  FLUIDITY_OF_MOTION_BREWMASTER_TALENT: {
    id: 387230,
    name: 'Fluidity of Motion',
    icon: 'ability_monk_standingkick',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  SHADOWBOXING_TREADS_BREWMASTER_TALENT: {
    id: 387638,
    name: 'Shadowboxing Treads',
    icon: 'ability_monk_roundhousekick',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  CHARRED_PASSIONS_BREWMASTER_TALENT: {
    id: 386965,
    name: 'Charred Passions',
    icon: 'ability_monk_mightyoxkick',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  DRAGONFIRE_BREW_BREWMASTER_TALENT: {
    id: 383994,
    name: 'Dragonfire Brew',
    icon: 'spell_fire_burnout',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  HIGH_TOLERANCE_BREWMASTER_TALENT: {
    id: 196737,
    name: 'High Tolerance',
    icon: 'monk_ability_avertharm',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  WALK_WITH_THE_OX_BREWMASTER_TALENT: {
    id: 387219,
    name: 'Walk with the Ox',
    icon: 'monk_stance_drunkenox',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  ELUSIVE_FOOTWORK_BREWMASTER_TALENT: {
    id: 387046,
    name: 'Elusive Footwork',
    icon: 'ability_monk_shuffle',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  ANVIL__STAVE_BREWMASTER_TALENT: {
    id: 386937,
    name: 'Anvil & Stave',
    icon: 'ability_monk_elusiveale',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  COUNTERSTRIKE_BREWMASTER_TALENT: {
    id: 383785,
    name: 'Counterstrike',
    icon: 'ability_monk_palmstrike',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  BONEDUST_BREW_BREWMASTER_TALENT: {
    id: 386276,
    name: 'Bonedust Brew',
    icon: 'ability_maldraxxus_monk',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  EXPLODING_KEG_BREWMASTER_TALENT: {
    id: 325153,
    name: 'Exploding Keg',
    icon: 'archaeology_5_0_emptykegofbrewfatherxinwoyin',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  BLACKOUT_COMBO_BREWMASTER_TALENT: {
    id: 196736,
    name: 'Blackout Combo',
    icon: 'ability_monk_blackoutkick',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  WEAPONS_OF_ORDER_BREWMASTER_TALENT: {
    id: 387185,
    name: 'Weapons of Order',
    icon: 'ability_bastion_monk',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  ATTENUATION_BREWMASTER_TALENT: {
    id: 386941,
    name: 'Attenuation',
    icon: 'spell_animamaldraxxus_nova',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  BOUNTIFUL_BREW_BREWMASTER_TALENT: {
    id: 386949,
    name: 'Bountiful Brew',
    icon: 'ability_maldraxxus_monk',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  STORMSTOUTS_LAST_KEG_BREWMASTER_TALENT: {
    id: 383707,
    name: "Stormstout's Last Keg",
    icon: 'achievement_brewery_2',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  EFFUSIVE_ANIMA_ACCELERATOR_BREWMASTER_TALENT: {
    id: 352188,
    name: 'Effusive Anima Accelerator',
    icon: 'inv_offhand_1h_bastion_d_01',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  CALL_TO_ARMS_BREWMASTER_TALENT: {
    id: 356684,
    name: 'Call to Arms',
    icon: 'ability_bastion_monk',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
});

export default talents;
export { talents as TALENTS_MONK };
