// Generated file, changes will eventually be overwritten!
import { createTalentList } from './types';

const talents = createTalentList({
  ACCUMULATING_MIST_TALENT: {
    id: 388564,
    name: 'Accumulating Mist',
    icon: 'ability_monk_zenmeditation',
    maxRanks: 1,
    entryIds: [101364],
  },
  ANCIENT_CONCORDANCE_TALENT: {
    id: 388740,
    name: 'Ancient Concordance',
    icon: 'spell_animaardenweald_beam',
    maxRanks: 2,
    entryIds: [101371],
  },
  ANCIENT_TEACHINGS_TALENT: {
    id: 388023,
    name: 'Ancient Teachings',
    icon: 'inv_misc_book_07',
    maxRanks: 1,
    entryIds: [101408],
  },
  ANVIL__STAVE_TALENT: {
    id: 386937,
    name: 'Anvil & Stave',
    icon: 'ability_monk_elusiveale',
    maxRanks: 2,
    entryIds: [101446],
  },
  ASCENSION_TALENT: {
    id: 115396,
    name: 'Ascension',
    icon: 'ability_monk_ascension',
    maxRanks: 1,
    entryIds: [101422],
  },
  ATTENUATION_TALENT: {
    id: 386941,
    name: 'Attenuation',
    icon: 'spell_animamaldraxxus_nova',
    maxRanks: 1,
    entryIds: [101550, 101484],
  },
  AWAKENED_FAELINE_TALENT: {
    id: 388779,
    name: 'Awakened Faeline',
    icon: 'spell_animaardenweald_buff',
    maxRanks: 1,
    entryIds: [101383],
  },
  BLACKOUT_COMBO_TALENT: {
    id: 196736,
    name: 'Blackout Combo',
    icon: 'ability_monk_blackoutkick',
    maxRanks: 1,
    entryIds: [101411],
  },
  BLACK_OX_BREW_TALENT: {
    id: 115399,
    name: 'Black Ox Brew',
    icon: 'ability_monk_chibrew',
    maxRanks: 1,
    entryIds: [101450],
  },
  BOB_AND_WEAVE_TALENT: {
    id: 280515,
    name: 'Bob and Weave',
    icon: 'ability_creature_cursed_04',
    maxRanks: 1,
    entryIds: [101449],
  },
  BONEDUST_BREW_TALENT: {
    id: 386276,
    name: 'Bonedust Brew',
    icon: 'ability_maldraxxus_monk',
    maxRanks: 1,
    entryIds: [101552, 101485],
  },
  BOUNCE_BACK_TALENT: {
    id: 389577,
    name: 'Bounce Back',
    icon: 'ability_butcher_heavyhanded',
    maxRanks: 2,
    entryIds: [101536],
  },
  BOUNTIFUL_BREW_TALENT: {
    id: 386949,
    name: 'Bountiful Brew',
    icon: 'spell_animamaldraxxus_wave',
    maxRanks: 1,
    entryIds: [101551],
  },
  BREATH_OF_FIRE_TALENT: {
    id: 115181,
    name: 'Breath of Fire',
    icon: 'ability_monk_breathoffire',
    maxRanks: 1,
    entryIds: [101464],
  },
  BURST_OF_LIFE_TALENT: {
    id: 399226,
    name: 'Burst of Life',
    icon: 'ability_monk_counteractmagic',
    maxRanks: 1,
    entryIds: [114297],
  },
  CALL_TO_ARMS_TALENT: {
    id: 397251,
    name: 'Call to Arms',
    icon: 'ability_bastion_monk',
    maxRanks: 1,
    entryIds: [101538],
  },
  CALMING_COALESCENCE_TALENT: {
    id: 388218,
    name: 'Calming Coalescence',
    icon: 'ability_monk_healthsphere',
    maxRanks: 1,
    entryIds: [101389],
  },
  CALMING_PRESENCE_TALENT: {
    id: 388664,
    name: 'Calming Presence',
    icon: 'inv_misc_orb_01',
    maxRanks: 1,
    entryIds: [101511],
  },
  CELERITY_TALENT: {
    id: 115173,
    name: 'Celerity',
    icon: 'ability_monk_quipunch',
    maxRanks: 1,
    entryIds: [101503],
  },
  CELESTIAL_BREW_TALENT: {
    id: 322507,
    name: 'Celestial Brew',
    icon: 'ability_monk_ironskinbrew',
    maxRanks: 1,
    entryIds: [101463],
  },
  CELESTIAL_FLAMES_TALENT: {
    id: 325177,
    name: 'Celestial Flames',
    icon: 'inv_misc_volatilefire',
    maxRanks: 1,
    entryIds: [101460],
  },
  CHARRED_PASSIONS_TALENT: {
    id: 386965,
    name: 'Charred Passions',
    icon: 'ability_monk_mightyoxkick',
    maxRanks: 1,
    entryIds: [101465],
  },
  CHI_BURST_TALENT: {
    id: 123986,
    name: 'Chi Burst',
    icon: 'spell_arcane_arcanetorrent',
    maxRanks: 1,
    entryIds: [101527],
  },
  CHI_SURGE_TALENT: {
    id: 393400,
    name: 'Chi Surge',
    icon: 'ability_monk_chiexplosion',
    maxRanks: 1,
    entryIds: [101537],
  },
  CHI_TORPEDO_TALENT: {
    id: 115008,
    name: 'Chi Torpedo',
    icon: 'ability_monk_quitornado',
    maxRanks: 1,
    entryIds: [101502],
  },
  CHI_WAVE_TALENT: {
    id: 115098,
    name: 'Chi Wave',
    icon: 'ability_monk_chiwave',
    maxRanks: 1,
    entryIds: [101528],
  },
  CLASH_TALENT: {
    id: 324312,
    name: 'Clash',
    icon: 'ability_monk_clashingoxcharge',
    maxRanks: 1,
    entryIds: [101440],
  },
  CLOSE_TO_HEART_TALENT: {
    id: 389574,
    name: 'Close to Heart',
    icon: 'inv_offhand_1h_pvppandarias2_c_01',
    maxRanks: 2,
    entryIds: [101525],
  },
  CLOUDED_FOCUS_TALENT: {
    id: 388047,
    name: 'Clouded Focus',
    icon: 'ability_monk_soothingmists',
    maxRanks: 1,
    entryIds: [101407],
  },
  COUNTERSTRIKE_TALENT: {
    id: 383785,
    name: 'Counterstrike',
    icon: 'ability_monk_palmstrike',
    maxRanks: 1,
    entryIds: [101441],
  },
  CRANE_VORTEX_TALENT: {
    id: 388848,
    name: 'Crane Vortex',
    icon: 'ability_monk_cranekick_new',
    maxRanks: 2,
    entryIds: [101483],
  },
  DAMPEN_HARM_TALENT: {
    id: 122278,
    name: 'Dampen Harm',
    icon: 'ability_monk_dampenharm',
    maxRanks: 1,
    entryIds: [101522],
  },
  DANCE_OF_CHI_JI_TALENT: {
    id: 325201,
    name: 'Dance of Chi-Ji',
    icon: 'ability_monk_cranekick_new',
    maxRanks: 1,
    entryIds: [101437],
  },
  DANCING_MISTS_TALENT: {
    id: 388701,
    name: 'Dancing Mists',
    icon: 'ability_monk_serenity',
    maxRanks: 2,
    entryIds: [101393],
  },
  DETOX_TALENT: {
    id: 218164,
    name: 'Detox',
    icon: 'ability_rogue_imrovedrecuperate',
    maxRanks: 1,
    entryIds: [102626, 101416],
    energyCost: 20,
  },
  DIFFUSE_MAGIC_TALENT: {
    id: 122783,
    name: 'Diffuse Magic',
    icon: 'spell_monk_diffusemagic',
    maxRanks: 1,
    entryIds: [101515],
  },
  DISABLE_TALENT: {
    id: 116095,
    name: 'Disable',
    icon: 'ability_shockwave',
    maxRanks: 1,
    entryIds: [101495],
    energyCost: 15,
  },
  DRAGONFIRE_BREW_TALENT: {
    id: 383994,
    name: 'Dragonfire Brew',
    icon: 'spell_fire_burnout',
    maxRanks: 1,
    entryIds: [101466],
  },
  DRINKING_HORN_COVER_TALENT: {
    id: 391370,
    name: 'Drinking Horn Cover',
    icon: 'ability_warrior_unrelentingassault',
    maxRanks: 1,
    entryIds: [101430],
  },
  DUST_IN_THE_WIND_TALENT: {
    id: 394093,
    name: 'Dust in the Wind',
    icon: 'inv_misc_powder_tin',
    maxRanks: 1,
    entryIds: [101486],
  },
  ECHOING_REVERBERATION_TALENT: {
    id: 388604,
    name: 'Echoing Reverberation',
    icon: 'ability_monk_legacyoftheemperor',
    maxRanks: 1,
    entryIds: [101365],
  },
  ELUSIVE_FOOTWORK_TALENT: {
    id: 387046,
    name: 'Elusive Footwork',
    icon: 'ability_monk_shuffle',
    maxRanks: 2,
    entryIds: [101412],
  },
  ELUSIVE_MISTS_TALENT: {
    id: 388681,
    name: 'Elusive Mists',
    icon: 'ability_monk_soothingmists',
    maxRanks: 2,
    entryIds: [101413],
  },
  EMPOWERED_TIGER_LIGHTNING_TALENT: {
    id: 323999,
    name: 'Empowered Tiger Lightning',
    icon: 'ability_monk_summontigerstatue',
    maxRanks: 1,
    entryIds: [101475],
  },
  CELESTIAL_HARMONY_TALENT: {
    id: 343655,
    name: 'Enveloping Breath',
    icon: 'ability_monk_jadeserpentbreath',
    maxRanks: 1,
    entryIds: [101388],
  },
  ENVELOPING_MIST_TALENT: {
    id: 124682,
    name: 'Enveloping Mist',
    icon: 'spell_monk_envelopingmist',
    maxRanks: 1,
    entryIds: [101370],
    manaCost: 12000,
  },
  ESCAPE_FROM_REALITY_TALENT: {
    id: 394110,
    name: 'Escape from Reality',
    icon: 'monk_ability_transcendence',
    maxRanks: 2,
    entryIds: [101534],
  },
  ESSENCE_FONT_TALENT: {
    id: 191837,
    name: 'Essence Font',
    icon: 'ability_monk_essencefont',
    maxRanks: 1,
    entryIds: [101406],
    manaCost: 18000,
  },
  EXPEDITIOUS_FORTIFICATION_TALENT: {
    id: 388813,
    name: 'Expeditious Fortification',
    icon: 'ability_monk_fortifyingale_new',
    maxRanks: 1,
    entryIds: [101497],
  },
  EXPLODING_KEG_TALENT: {
    id: 325153,
    name: 'Exploding Keg',
    icon: 'archaeology_5_0_emptykegofbrewfatherxinwoyin',
    maxRanks: 1,
    entryIds: [101542],
  },
  EYE_OF_THE_TIGER_TALENT: {
    id: 196607,
    name: 'Eye of the Tiger',
    icon: 'ability_druid_primalprecision',
    maxRanks: 1,
    entryIds: [101518],
  },
  FACE_PALM_TALENT: {
    id: 389942,
    name: 'Face Palm',
    icon: 'ability_monk_tigerpalm',
    maxRanks: 1,
    entryIds: [101442],
  },
  FAELINE_HARMONY_TALENT: {
    id: 391412,
    name: 'Faeline Harmony',
    icon: 'ability_ardenweald_monk',
    maxRanks: 1,
    entryIds: [101487],
  },
  FAELINE_STOMP_TALENT: {
    id: 388193,
    name: 'Faeline Stomp',
    icon: 'ability_ardenweald_monk',
    maxRanks: 1,
    entryIds: [101359, 101488],
    manaCost: 10000,
  },
  FAST_FEET_TALENT: {
    id: 388809,
    name: 'Fast Feet',
    icon: 'ability_monk_risingsunkick',
    maxRanks: 2,
    entryIds: [101523],
  },
  FATAL_FLYING_GUILLOTINE_TALENT: {
    id: 394923,
    name: 'Fatal Flying Guillotine',
    icon: 'ability_monk_touchofdeath',
    maxRanks: 1,
    entryIds: [101482],
  },
  FATAL_TOUCH_TALENT: {
    id: 394123,
    name: 'Fatal Touch',
    icon: 'ability_monk_touchofdeath',
    maxRanks: 2,
    entryIds: [101521],
  },
  FEROCITY_OF_XUEN_TALENT: {
    id: 388674,
    name: 'Ferocity of Xuen',
    icon: 'ability_mount_pinktiger',
    maxRanks: 2,
    entryIds: [101524],
  },
  FISTS_OF_FURY_TALENT: {
    id: 113656,
    name: 'Fists of Fury',
    icon: 'monk_ability_fistoffury',
    maxRanks: 1,
    entryIds: [101423],
    chiCost: 3,
  },
  FLASHING_FISTS_TALENT: {
    id: 388854,
    name: 'Flashing Fists',
    icon: 'inv_weapon_hand_08',
    maxRanks: 2,
    entryIds: [101425],
  },
  FLUIDITY_OF_MOTION_TALENT: {
    id: 387230,
    name: 'Fluidity of Motion',
    icon: 'ability_monk_standingkick',
    maxRanks: 1,
    entryIds: [101443],
  },
  FLYING_SERPENT_KICK_TALENT: {
    id: 101545,
    name: 'Flying Serpent Kick',
    icon: 'ability_monk_flyingdragonkick',
    maxRanks: 1,
    entryIds: [101432],
  },
  FOCUSED_THUNDER_TALENT: {
    id: 197895,
    name: 'Focused Thunder',
    icon: 'spell_monk_nimblebrew',
    maxRanks: 1,
    entryIds: [101401],
  },
  FONT_OF_LIFE_TALENT: {
    id: 337209,
    name: 'Font of Life',
    icon: 'spell_shaman_tidalwaves',
    maxRanks: 1,
    entryIds: [101386],
  },
  FORBIDDEN_TECHNIQUE_TALENT: {
    id: 393098,
    name: 'Forbidden Technique',
    icon: 'ability_monk_touchofdeath',
    maxRanks: 1,
    entryIds: [101418],
  },
  FORTIFYING_BREW_DETERMINATION_TALENT: {
    id: 322960,
    name: 'Fortifying Brew: Determination',
    icon: 'ability_monk_fortifyingale_new',
    maxRanks: 1,
    entryIds: [101470],
  },
  FORTIFYING_BREW_TALENT: {
    id: 115203,
    name: 'Fortifying Brew',
    icon: 'ability_monk_fortifyingale_new',
    maxRanks: 1,
    entryIds: [101496],
  },
  FUNDAMENTAL_OBSERVATION_TALENT: {
    id: 387035,
    name: 'Fundamental Observation',
    icon: 'ability_monk_zenmeditation',
    maxRanks: 1,
    entryIds: [101439],
  },
  FURY_OF_XUEN_TALENT: {
    id: 396166,
    name: 'Fury of Xuen',
    icon: 'ability_monk_prideofthetiger',
    maxRanks: 1,
    entryIds: [101472],
  },
  GAI_PLINS_IMPERIAL_BREW_TALENT: {
    id: 383700,
    name: "Gai Plin's Imperial Brew",
    icon: 'inv_misc_beer_06',
    maxRanks: 1,
    entryIds: [101545],
  },
  GENEROUS_POUR_TALENT: {
    id: 389575,
    name: 'Generous Pour',
    icon: 'inv_misc_food_legion_goocaramel_bottle',
    maxRanks: 2,
    entryIds: [101500],
  },
  GIFT_OF_THE_CELESTIALS_TALENT: {
    id: 388212,
    name: 'Gift of the Celestials',
    icon: 'inv_pet_jadeserpentpet',
    maxRanks: 1,
    entryIds: [101381],
  },
  GIFT_OF_THE_OX_TALENT: {
    id: 124502,
    name: 'Gift of the Ox',
    icon: 'ability_druid_giftoftheearthmother',
    maxRanks: 1,
    entryIds: [101452],
  },
  GLORY_OF_THE_DAWN_TALENT: {
    id: 392958,
    name: 'Glory of the Dawn',
    icon: 'ability_monk_mightyoxkick',
    maxRanks: 1,
    entryIds: [101493],
  },
  GRACEFUL_EXIT_TALENT: {
    id: 387256,
    name: 'Graceful Exit',
    icon: 'ability_rogue_sprint_blue',
    maxRanks: 1,
    entryIds: [101457],
  },
  GRACE_OF_THE_CRANE_TALENT: {
    id: 388811,
    name: 'Grace of the Crane',
    icon: 'monk_ability_cherrymanatea',
    maxRanks: 2,
    entryIds: [101529],
  },
  HARDENED_SOLES_TALENT: {
    id: 391383,
    name: 'Hardened Soles',
    icon: 'ability_monk_roundhousekick',
    maxRanks: 2,
    entryIds: [101421],
  },
  HASTY_PROVOCATION_TALENT: {
    id: 328670,
    name: 'Hasty Provocation',
    icon: 'ability_monk_provoke',
    maxRanks: 1,
    entryIds: [101514],
  },
  HEALING_ELIXIR_TALENT: {
    id: 122281,
    name: 'Healing Elixir',
    icon: 'ability_monk_jasmineforcetea',
    maxRanks: 1,
    entryIds: [101374, 101458],
  },
  HIGH_TOLERANCE_TALENT: {
    id: 196737,
    name: 'High Tolerance',
    icon: 'monk_ability_avertharm',
    maxRanks: 2,
    entryIds: [101469],
  },
  HIT_COMBO_TALENT: {
    id: 196740,
    name: 'Hit Combo',
    icon: 'ability_monk_palmstrike',
    maxRanks: 1,
    entryIds: [101492],
  },
  HIT_SCHEME_TALENT: {
    id: 383695,
    name: 'Hit Scheme',
    icon: 'ability_monk_roundhousekick',
    maxRanks: 1,
    entryIds: [101461],
  },
  IMPROVED_CELESTIAL_BREW_TALENT: {
    id: 322510,
    name: 'Improved Celestial Brew',
    icon: 'ability_monk_ironskinbrew',
    maxRanks: 1,
    entryIds: [101462],
  },
  IMPROVED_DETOX_TALENT: {
    id: 388874,
    name: 'Improved Detox',
    icon: 'ability_rogue_imrovedrecuperate',
    maxRanks: 1,
    entryIds: [102627],
  },
  IMPROVED_INVOKE_NIUZAO_THE_BLACK_OX_TALENT: {
    id: 322740,
    name: 'Improved Invoke Niuzao, the Black Ox',
    icon: 'spell_monk_brewmaster_spec',
    maxRanks: 1,
    entryIds: [101540],
  },
  IMPROVED_PARALYSIS_TALENT: {
    id: 344359,
    name: 'Improved Paralysis',
    icon: 'ability_monk_paralysis',
    maxRanks: 1,
    entryIds: [101505],
  },
  IMPROVED_PURIFYING_BREW_TALENT: {
    id: 343743,
    name: 'Improved Purifying Brew',
    icon: 'inv_misc_beer_06',
    maxRanks: 1,
    entryIds: [101471],
  },
  IMPROVED_ROLL_TALENT: {
    id: 328669,
    name: 'Improved Roll',
    icon: 'ability_monk_roll',
    maxRanks: 1,
    entryIds: [101531],
  },
  IMPROVED_TOUCH_OF_DEATH_TALENT: {
    id: 322113,
    name: 'Improved Touch of Death',
    icon: 'ability_monk_touchofdeath',
    maxRanks: 1,
    entryIds: [101501],
  },
  IMPROVED_VIVIFY_TALENT: {
    id: 231602,
    name: 'Improved Vivify',
    icon: 'ability_monk_vivify',
    maxRanks: 2,
    entryIds: [101510],
  },
  INNER_PEACE_TALENT: {
    id: 397768,
    name: 'Inner Peace',
    icon: 'ability_monk_jasmineforcetea',
    maxRanks: 1,
    entryIds: [101438],
  },
  INVIGORATING_MISTS_TALENT: {
    id: 274586,
    name: 'Invigorating Mists',
    icon: 'ability_monk_vivify',
    maxRanks: 1,
    entryIds: [101358],
  },
  INVOKERS_DELIGHT_TALENT: {
    id: 388661,
    name: "Invoker's Delight",
    icon: 'inv_inscription_80_warscroll_battleshout',
    maxRanks: 1,
    entryIds: [101373, 101477],
  },
  INVOKE_CHI_JI_THE_RED_CRANE_TALENT: {
    id: 325197,
    name: 'Invoke Chi-Ji, the Red Crane',
    icon: 'inv_pet_cranegod',
    maxRanks: 1,
    entryIds: [101396],
    manaCost: 12500,
  },
  INVOKE_NIUZAO_THE_BLACK_OX_TALENT: {
    id: 132578,
    name: 'Invoke Niuzao, the Black Ox',
    icon: 'spell_monk_brewmaster_spec',
    maxRanks: 1,
    entryIds: [101544],
  },
  INVOKE_XUEN_THE_WHITE_TIGER_TALENT: {
    id: 123904,
    name: 'Invoke Xuen, the White Tiger',
    icon: 'ability_monk_summontigerstatue',
    maxRanks: 1,
    entryIds: [101473],
  },
  INVOKE_YULON_THE_JADE_SERPENT_TALENT: {
    id: 322118,
    name: "Invoke Yu'lon, the Jade Serpent",
    icon: 'ability_monk_dragonkick',
    maxRanks: 1,
    entryIds: [101397],
    manaCost: 12500,
  },
  IRONSHELL_BREW_TALENT: {
    id: 388814,
    name: 'Ironshell Brew',
    icon: 'ability_monk_fortifyingale_new',
    maxRanks: 1,
    entryIds: [101498],
  },
  JADE_BOND_TALENT: {
    id: 388031,
    name: 'Jade Bond',
    icon: 'inv_inscription_deck_jadeserpent',
    maxRanks: 1,
    entryIds: [101382],
  },
  JADE_IGNITION_TALENT: {
    id: 392979,
    name: 'Jade Ignition',
    icon: 'ability_monk_chiexplosion',
    maxRanks: 1,
    entryIds: [101417],
  },
  KEG_SMASH_TALENT: {
    id: 121253,
    name: 'Keg Smash',
    icon: 'achievement_brewery_2',
    maxRanks: 1,
    entryIds: [101451],
    energyCost: 40,
  },
  LAST_EMPERORS_CAPACITOR_TALENT: {
    id: 392989,
    name: "Last Emperor's Capacitor",
    icon: 'ability_warrior_unrelentingassault',
    maxRanks: 1,
    entryIds: [101480],
  },
  LIFECYCLES_TALENT: {
    id: 197915,
    name: 'Lifecycles',
    icon: 'ability_monk_souldance',
    maxRanks: 1,
    entryIds: [101380],
  },
  LIFE_COCOON_TALENT: {
    id: 116849,
    name: 'Life Cocoon',
    icon: 'ability_monk_chicocoon',
    maxRanks: 1,
    entryIds: [101390],
    manaCost: 6000,
  },
  LIGHT_BREWING_TALENT: {
    id: 325093,
    name: 'Light Brewing',
    icon: 'spell_brew_wheat',
    maxRanks: 1,
    entryIds: [101448],
  },
  MANA_TEA_TALENT: {
    id: 197908,
    name: 'Mana Tea',
    icon: 'monk_ability_cherrymanatea',
    maxRanks: 1,
    entryIds: [101379],
  },
  MARK_OF_THE_CRANE_TALENT: {
    id: 220357,
    name: 'Mark of the Crane',
    icon: 'ability_monk_cranekick_new',
    maxRanks: 1,
    entryIds: [101434],
  },
  MASTERY_OF_MIST_TALENT: {
    id: 281231,
    name: 'Mastery of Mist',
    icon: 'spell_nature_wispsplodegreen',
    maxRanks: 1,
    entryIds: [101395],
  },
  MENDING_PROLIFERATION_TALENT: {
    id: 388509,
    name: 'Mending Proliferation',
    icon: 'inv_shoulder_inv_leather_raidmonk_s_01',
    maxRanks: 1,
    entryIds: [101375],
  },
  MERIDIAN_STRIKES_TALENT: {
    id: 391330,
    name: 'Meridian Strikes',
    icon: 'ability_monk_touchofdeath',
    maxRanks: 1,
    entryIds: [101431],
  },
  MISTS_OF_LIFE_TALENT: {
    id: 388548,
    name: 'Mists of Life',
    icon: 'inv_shoulder__inv_leather_raidmonkmythic_s_01',
    maxRanks: 1,
    entryIds: [101369],
  },
  MISTY_PEAKS_TALENT: {
    id: 388682,
    name: 'Misty Peaks',
    icon: 'achievement_zone_stormpeaks_10',
    maxRanks: 2,
    entryIds: [101402],
  },
  MIST_WRAP_TALENT: {
    id: 197900,
    name: 'Mist Wrap',
    icon: 'ability_monk_pathofmists',
    maxRanks: 1,
    entryIds: [101363],
  },
  NOURISHING_CHI_TALENT: {
    id: 387765,
    name: 'Nourishing Chi',
    icon: 'inv_misc_gem_pearl_06',
    maxRanks: 1,
    entryIds: [101409],
  },
  OPEN_PALM_STRIKES_TALENT: {
    id: 392970,
    name: 'Open Palm Strikes',
    icon: 'monk_ability_fistoffury',
    maxRanks: 1,
    entryIds: [101494],
  },
  OVERFLOWING_MISTS_TALENT: {
    id: 388511,
    name: 'Overflowing Mists',
    icon: 'inv_legion_faction_dreamweavers',
    maxRanks: 2,
    entryIds: [101387],
  },
  PARALYSIS_TALENT: {
    id: 115078,
    name: 'Paralysis',
    icon: 'ability_monk_paralysis',
    maxRanks: 1,
    entryIds: [101506],
    energyCost: 20,
  },
  PEACEFUL_MENDING_TALENT: {
    id: 388593,
    name: 'Peaceful Mending',
    icon: 'pandarenracial_innerpeace',
    maxRanks: 2,
    entryIds: [101399],
  },
  POWER_STRIKES_TALENT: {
    id: 121817,
    name: 'Power Strikes',
    icon: 'ability_monk_powerstrikes',
    maxRanks: 1,
    entryIds: [101424],
  },
  PRETENSE_OF_INSTABILITY_TALENT: {
    id: 393516,
    name: 'Pretense of Instability',
    icon: 'inv_misc_archaeology_vrykuldrinkinghorn',
    maxRanks: 1,
    entryIds: [101445],
  },
  PROFOUND_REBUTTAL_TALENT: {
    id: 392910,
    name: 'Profound Rebuttal',
    icon: 'ability_monk_expelharm',
    maxRanks: 1,
    entryIds: [101526],
  },
  PURIFYING_BREW_TALENT: {
    id: 119582,
    name: 'Purifying Brew',
    icon: 'inv_misc_beer_06',
    maxRanks: 1,
    entryIds: [101453],
  },
  QUICK_SIP_TALENT: {
    id: 388505,
    name: 'Quick Sip',
    icon: 'achievement_faction_brewmaster',
    maxRanks: 1,
    entryIds: [101456],
  },
  RAPID_DIFFUSION_TALENT: {
    id: 388847,
    name: 'Rapid Diffusion',
    icon: 'ability_monk_chiswirl',
    maxRanks: 2,
    entryIds: [101385],
  },
  REFRESHING_JADE_WIND_TALENT: {
    id: 196725,
    name: 'Refreshing Jade Wind',
    icon: 'ability_monk_rushingjadewind',
    maxRanks: 1,
    entryIds: [101362],
    manaCost: 12500,
  },
  RENEWING_MIST_TALENT: {
    id: 115151,
    name: 'Renewing Mist',
    icon: 'ability_monk_renewingmists',
    maxRanks: 1,
    entryIds: [101394],
    manaCost: 4500,
  },
  RESONANT_FISTS_TALENT: {
    id: 389578,
    name: 'Resonant Fists',
    icon: 'inv_weapon_hand_16',
    maxRanks: 2,
    entryIds: [101520],
  },
  RESPLENDENT_MIST_TALENT: {
    id: 388020,
    name: 'Resplendent Mist',
    icon: 'spell_nature_abolishmagic',
    maxRanks: 2,
    entryIds: [101391],
  },
  RESTORAL_TALENT: {
    id: 388615,
    name: 'Restoral',
    icon: 'ability_monk_tigerstyle',
    maxRanks: 1,
    entryIds: [101377],
    manaCost: 10935,
  },
  REVIVAL_TALENT: {
    id: 115310,
    name: 'Revival',
    icon: 'spell_monk_revival',
    maxRanks: 1,
    entryIds: [101378],
    manaCost: 10935,
  },
  RING_OF_PEACE_TALENT: {
    id: 116844,
    name: 'Ring of Peace',
    icon: 'spell_monk_ringofpeace',
    maxRanks: 1,
    entryIds: [101516],
  },
  RISING_MIST_TALENT: {
    id: 274909,
    name: 'Rising Mist',
    icon: 'ability_monk_effuse',
    maxRanks: 1,
    entryIds: [101356],
  },
  RISING_STAR_TALENT: {
    id: 388849,
    name: 'Rising Star',
    icon: 'ability_monk_risingsunkick',
    maxRanks: 2,
    entryIds: [101489],
  },
  RISING_SUN_KICK_TALENT: {
    id: 107428,
    name: 'Rising Sun Kick',
    icon: 'ability_monk_risingsunkick',
    maxRanks: 1,
    entryIds: [101508],
    chiCost: 2,
  },
  RUSHING_JADE_WIND_TALENT: {
    id: 116847,
    name: 'Rushing Jade Wind',
    icon: 'ability_monk_rushingjadewind',
    maxRanks: 1,
    entryIds: [101549, 101436],
    chiCost: 1,
  },
  SALSALABIMS_STRENGTH_TALENT: {
    id: 383697,
    name: "Sal'salabim's Strength",
    icon: 'ability_warrior_unrelentingassault',
    maxRanks: 1,
    entryIds: [101467],
  },
  SAVE_THEM_ALL_TALENT: {
    id: 389579,
    name: 'Save Them All',
    icon: 'inv_weapon_hand_22',
    maxRanks: 2,
    entryIds: [101533],
  },
  SCALDING_BREW_TALENT: {
    id: 383698,
    name: 'Scalding Brew',
    icon: 'spell_brew_bolt_dark',
    maxRanks: 1,
    entryIds: [101468],
  },
  SECRET_INFUSION_TALENT: {
    id: 388491,
    name: 'Secret Infusion',
    icon: 'ability_monk_chibrew',
    maxRanks: 2,
    entryIds: [101372],
  },
  SERENITY_TALENT: {
    id: 152173,
    name: 'Serenity',
    icon: 'ability_monk_serenity',
    maxRanks: 1,
    entryIds: [101428],
  },
  SHADOWBOXING_TREADS_BREWMASTER_TALENT: {
    id: 387638,
    name: 'Shadowboxing Treads',
    icon: 'ability_monk_roundhousekick',
    maxRanks: 1,
    entryIds: [101444],
  },
  SHADOWBOXING_TREADS_WINDWALKER_TALENT: {
    id: 392982,
    name: 'Shadowboxing Treads',
    icon: 'ability_monk_roundhousekick',
    maxRanks: 1,
    entryIds: [101435],
  },
  SHAOHAOS_LESSONS_TALENT: {
    id: 400089,
    name: "Shaohao's Lessons",
    icon: 'ability_monk_dematerialize',
    maxRanks: 1,
    entryIds: [101404],
  },
  SHEILUNS_GIFT_TALENT: {
    id: 399491,
    name: "Sheilun's Gift",
    icon: 'inv_staff_2h_artifactshaohao_d_01',
    maxRanks: 1,
    entryIds: [101392],
    manaCost: 6250,
  },
  LEGACY_OF_WISDOM_TALENT: {
    id: 404408,
    name: 'Legacy of Wisdom',
    icon: 'misc_legionfall_monk',
    maxRanks: 1,
    entryIds: [114821],
  },
  SHUFFLE_TALENT: {
    id: 322120,
    name: 'Shuffle',
    icon: 'ability_monk_shuffle',
    maxRanks: 1,
    entryIds: [101455],
  },
  SKYREACH_TALENT: {
    id: 392991,
    name: 'Skyreach',
    icon: 'inv__fistofthewhitetiger',
    maxRanks: 1,
    entryIds: [114822],
  },
  SKYTOUCH_TALENT: {
    id: 405044,
    name: 'Skytouch',
    icon: 'inv__fistofthewhitetiger',
    maxRanks: 1,
    entryIds: [101479],
  },
  SONG_OF_CHI_JI_TALENT: {
    id: 198898,
    name: 'Song of Chi-Ji',
    icon: 'inv_chaos_orb',
    maxRanks: 1,
    entryIds: [101360],
  },
  SOOTHING_MIST_TALENT: {
    id: 115175,
    name: 'Soothing Mist',
    icon: 'ability_monk_soothingmists',
    maxRanks: 1,
    entryIds: [101509],
    manaCost: 0,
  },
  SPEAR_HAND_STRIKE_TALENT: {
    id: 116705,
    name: 'Spear Hand Strike',
    icon: 'ability_monk_spearhand',
    maxRanks: 1,
    entryIds: [101504],
  },
  SPECIAL_DELIVERY_TALENT: {
    id: 196730,
    name: 'Special Delivery',
    icon: 'achievement_brewery_2',
    maxRanks: 1,
    entryIds: [101548],
  },
  SPIRITUAL_FOCUS_TALENT: {
    id: 280197,
    name: 'Spiritual Focus',
    icon: 'spell_nature_giftofthewild',
    maxRanks: 1,
    entryIds: [101427],
  },
  SPIRIT_OF_THE_CRANE_TALENT: {
    id: 210802,
    name: 'Spirit of the Crane',
    icon: 'monk_stance_redcrane',
    maxRanks: 1,
    entryIds: [101361],
  },
  SPIRIT_OF_THE_OX_TALENT: {
    id: 400629,
    name: 'Spirit of the Ox',
    icon: 'ability_titankeeper_cleansingorb',
    maxRanks: 1,
    entryIds: [114729],
  },
  STAGGERING_STRIKES_TALENT: {
    id: 387625,
    name: 'Staggering Strikes',
    icon: 'ability_monk_blackoutstrike',
    maxRanks: 1,
    entryIds: [101459],
  },
  STORMSTOUTS_LAST_KEG_TALENT: {
    id: 383707,
    name: "Stormstout's Last Keg",
    icon: 'achievement_brewery_2',
    maxRanks: 1,
    entryIds: [101541],
  },
  STORM_EARTH_AND_FIRE_TALENT: {
    id: 137639,
    name: 'Storm, Earth, and Fire',
    icon: 'spell_nature_giftofthewild',
    maxRanks: 1,
    entryIds: [101429],
  },
  STRENGTH_OF_SPIRIT_TALENT: {
    id: 387276,
    name: 'Strength of Spirit',
    icon: 'ability_monk_healthsphere',
    maxRanks: 1,
    entryIds: [101499],
  },
  STRIKE_OF_THE_WINDLORD_TALENT: {
    id: 392983,
    name: 'Strike of the Windlord',
    icon: 'inv_hand_1h_artifactskywall_d_01',
    maxRanks: 1,
    entryIds: [101491],
    chiCost: 2,
  },
  SUMMON_BLACK_OX_STATUE_TALENT: {
    id: 115315,
    name: 'Summon Black Ox Statue',
    icon: 'monk_ability_summonoxstatue',
    maxRanks: 1,
    entryIds: [101535],
  },
  SUMMON_JADE_SERPENT_STATUE_TALENT: {
    id: 115313,
    name: 'Summon Jade Serpent Statue',
    icon: 'ability_monk_summonserpentstatue',
    maxRanks: 1,
    entryIds: [101532],
  },
  SUMMON_WHITE_TIGER_STATUE_TALENT: {
    id: 388686,
    name: 'Summon White Tiger Statue',
    icon: 'ability_monk_summonwhitetigerstatue',
    maxRanks: 1,
    entryIds: [101519],
  },
  TEACHINGS_OF_THE_MONASTERY_TALENT: {
    id: 116645,
    name: 'Teachings of the Monastery',
    icon: 'passive_monk_teachingsofmonastery',
    maxRanks: 1,
    entryIds: [101403, 101426],
  },
  TEAR_OF_MORNING_TALENT: {
    id: 387991,
    name: 'Tear of Morning',
    icon: 'ability_monk_uplift',
    maxRanks: 1,
    entryIds: [101357],
  },
  TEA_OF_PLENTY_TALENT: {
    id: 388517,
    name: 'Tea of Plenty',
    icon: 'inv_misc_pearlmilktea',
    maxRanks: 1,
    entryIds: [101366],
  },
  TEA_OF_SERENITY_TALENT: {
    id: 393460,
    name: 'Tea of Serenity',
    icon: 'inv_misc_food_vendor_roastedbarlytea',
    maxRanks: 1,
    entryIds: [101367],
  },
  THUNDERFIST_TALENT: {
    id: 392985,
    name: 'Thunderfist',
    icon: 'inv_hand_1h_artifactskywall_d_01',
    maxRanks: 1,
    entryIds: [101490],
  },
  THUNDER_FOCUS_TEA_TALENT: {
    id: 116680,
    name: 'Thunder Focus Tea',
    icon: 'ability_monk_thunderfocustea',
    maxRanks: 1,
    entryIds: [101410],
  },
  TIGERS_LUST_TALENT: {
    id: 116841,
    name: "Tiger's Lust",
    icon: 'ability_monk_tigerslust',
    maxRanks: 1,
    entryIds: [101507],
  },
  TIGER_TAIL_SWEEP_TALENT: {
    id: 264348,
    name: 'Tiger Tail Sweep',
    icon: 'ability_monk_legsweep',
    maxRanks: 2,
    entryIds: [101414],
  },
  TOUCH_OF_KARMA_TALENT: {
    id: 122470,
    name: 'Touch of Karma',
    icon: 'ability_monk_touchofkarma',
    maxRanks: 1,
    entryIds: [101420],
  },
  TOUCH_OF_THE_TIGER_TALENT: {
    id: 388856,
    name: 'Touch of the Tiger',
    icon: 'ability_monk_tigerpalm',
    maxRanks: 2,
    entryIds: [101433],
  },
  TRAINING_OF_NIUZAO_TALENT: {
    id: 383714,
    name: 'Training of Niuzao',
    icon: 'monk_stance_drunkenox',
    maxRanks: 1,
    entryIds: [101447],
  },
  TRANQUIL_SPIRIT_TALENT: {
    id: 393357,
    name: 'Tranquil Spirit',
    icon: 'ability_monk_chiswirl',
    maxRanks: 1,
    entryIds: [101546],
  },
  TRANSCENDENCE_TALENT: {
    id: 101643,
    name: 'Transcendence',
    icon: 'monk_ability_transcendence',
    maxRanks: 1,
    entryIds: [101512],
  },
  TRANSFER_THE_POWER_TALENT: {
    id: 195300,
    name: 'Transfer the Power',
    icon: 'ability_thunderking_kickshell',
    maxRanks: 1,
    entryIds: [101476],
  },
  UNISON_TALENT: {
    id: 388477,
    name: 'Unison',
    icon: 'ability_creature_cursed_04',
    maxRanks: 1,
    entryIds: [101376],
  },
  UPLIFTED_SPIRITS_TALENT: {
    id: 388551,
    name: 'Uplifted Spirits',
    icon: 'monk_stance_wiseserpent',
    maxRanks: 1,
    entryIds: [101398],
  },
  UPWELLING_TALENT: {
    id: 274963,
    name: 'Upwelling',
    icon: 'ability_monk_surgingmist',
    maxRanks: 1,
    entryIds: [101400],
  },
  VEIL_OF_PRIDE_TALENT: {
    id: 400053,
    name: 'Veil of Pride',
    icon: 'ability_monk_vivify',
    maxRanks: 1,
    entryIds: [101405],
  },
  VIGOROUS_EXPULSION_TALENT: {
    id: 392900,
    name: 'Vigorous Expulsion',
    icon: 'ability_monk_expelharm',
    maxRanks: 1,
    entryIds: [101530],
  },
  VIVACIOUS_VIVIFICATION_TALENT: {
    id: 388812,
    name: 'Vivacious Vivification',
    icon: 'ability_monk_vivify',
    maxRanks: 1,
    entryIds: [101513],
  },
  WALK_WITH_THE_OX_TALENT: {
    id: 387219,
    name: 'Walk with the Ox',
    icon: 'monk_stance_drunkenox',
    maxRanks: 2,
    entryIds: [101543],
  },
  WAY_OF_THE_FAE_TALENT: {
    id: 392994,
    name: 'Way of the Fae',
    icon: 'spell_animaardenweald_beam',
    maxRanks: 1,
    entryIds: [101415],
  },
  WEAPONS_OF_ORDER_TALENT: {
    id: 387184,
    name: 'Weapons of Order',
    icon: 'ability_bastion_monk',
    maxRanks: 1,
    entryIds: [101539],
    manaCost: 12500,
  },
  WHIRLING_DRAGON_PUNCH_TALENT: {
    id: 152175,
    name: 'Whirling Dragon Punch',
    icon: 'ability_monk_hurricanestrike',
    maxRanks: 1,
    entryIds: [101474],
  },
  WIDENING_WHIRL_TALENT: {
    id: 388846,
    name: 'Widening Whirl',
    icon: 'ability_monk_forcesphere_pink',
    maxRanks: 1,
    entryIds: [101419],
  },
  WINDWALKING_TALENT: {
    id: 157411,
    name: 'Windwalking',
    icon: 'monk_stance_whitetiger',
    maxRanks: 2,
    entryIds: [101517],
  },
  XUENS_BATTLEGEAR_TALENT: {
    id: 392993,
    name: "Xuen's Battlegear",
    icon: 'monk_stance_whitetiger',
    maxRanks: 1,
    entryIds: [101478],
  },
  XUENS_BOND_TALENT: {
    id: 392986,
    name: "Xuen's Bond",
    icon: 'ability_demonhunter_netherbond',
    maxRanks: 1,
    entryIds: [101481],
  },
  YULONS_WHISPER_TALENT: {
    id: 388038,
    name: "Yu'lon's Whisper",
    icon: 'ability_monk_chiexplosion',
    maxRanks: 1,
    entryIds: [101384],
  },
  ZEN_MEDITATION_TALENT: {
    id: 115176,
    name: 'Zen Meditation',
    icon: 'ability_monk_zenmeditation',
    maxRanks: 1,
    entryIds: [101547],
  },
  ZEN_PULSE_TALENT: {
    id: 124081,
    name: 'Zen Pulse',
    icon: 'ability_monk_forcesphere',
    maxRanks: 1,
    entryIds: [101368],
    manaCost: 2500,
  },
});

export default talents;
export { talents as TALENTS_MONK };
