// Generated file, changes will eventually be overwritten!
import { createTalentList } from './types';

const talents = createTalentList({
  LAY_ON_HANDS_TALENT: {
    id: 633,
    name: 'Lay on Hands',
    icon: 'spell_holy_layonhands',
    maxRanks: 1,
    entryIds: [102583],
  },
  BLESSING_OF_FREEDOM_TALENT: {
    id: 1044,
    name: 'Blessing of Freedom',
    icon: 'spell_holy_sealofvalor',
    maxRanks: 1,
    entryIds: [102587],
    manaCost: 3500,
  },
  HAMMER_OF_WRATH_TALENT: {
    id: 24275,
    name: 'Hammer of Wrath',
    icon: 'spell_paladin_hammerofwrath',
    maxRanks: 1,
    entryIds: [102479],
  },
  AURAS_OF_THE_RESOLUTE_TALENT: {
    id: 385633,
    name: 'Auras of the Resolute',
    icon: 'spell_holy_devotionaura',
    maxRanks: 1,
    entryIds: [102586],
  },
  AURAS_OF_SWIFT_VENGEANCE_TALENT: {
    id: 385639,
    name: 'Auras of Swift Vengeance',
    icon: 'spell_holy_crusade',
    maxRanks: 1,
    entryIds: [102588],
  },
  REPENTANCE_TALENT: {
    id: 20066,
    name: 'Repentance',
    icon: 'spell_holy_prayerofhealing',
    maxRanks: 1,
    entryIds: [102585],
    manaCost: 3000,
  },
  BLINDING_LIGHT_TALENT: {
    id: 115750,
    name: 'Blinding Light',
    icon: 'ability_paladin_blindinglight',
    maxRanks: 1,
    entryIds: [102584],
    manaCost: 3000,
  },
  DIVINE_STEED_TALENT: {
    id: 190784,
    name: 'Divine Steed',
    icon: 'ability_paladin_divinesteed',
    maxRanks: 1,
    entryIds: [102625],
  },
  FIST_OF_JUSTICE_TALENT: {
    id: 234299,
    name: 'Fist of Justice',
    icon: 'spell_holy_fistofjustice',
    maxRanks: 2,
    entryIds: [102589],
  },
  CLEANSE_TOXINS_TALENT: {
    id: 213644,
    name: 'Cleanse Toxins',
    icon: 'spell_holy_renew',
    maxRanks: 1,
    entryIds: [102476],
    manaCost: 3250,
  },
  CAVALIER_TALENT: {
    id: 230332,
    name: 'Cavalier',
    icon: 'ability_paladin_divinesteed',
    maxRanks: 1,
    entryIds: [102592],
  },
  SEASONED_WARHORSE_TALENT: {
    id: 376996,
    name: 'Seasoned Warhorse',
    icon: 'spell_nature_swiftness',
    maxRanks: 1,
    entryIds: [102624],
  },
  SEAL_OF_THE_TEMPLAR_TALENT: {
    id: 377016,
    name: 'Seal of the Templar',
    icon: 'ability_paladin_artofwar',
    maxRanks: 1,
    entryIds: [102623],
  },
  GREATER_JUDGMENT_SHARED_TALENT: {
    id: 231663,
    name: 'Greater Judgment',
    icon: 'spell_holy_righteousfury',
    maxRanks: 1,
    entryIds: [102590],
  },
  GREATER_JUDGMENT_HOLY_TALENT: {
    id: 231644,
    name: 'Greater Judgment',
    icon: 'spell_holy_righteousfury',
    maxRanks: 1,
    entryIds: [114292],
  },
  HOLY_AEGIS_TALENT: {
    id: 385515,
    name: 'Holy Aegis',
    icon: 'ability_paladin_touchedbylight',
    maxRanks: 2,
    entryIds: [102597],
  },
  AVENGING_WRATH_TALENT: {
    id: 31884,
    name: 'Avenging Wrath',
    icon: 'spell_holy_avenginewrath',
    maxRanks: 1,
    entryIds: [102593],
  },
  TURN_EVIL_TALENT: {
    id: 10326,
    name: 'Turn Evil',
    icon: 'ability_paladin_turnevil',
    maxRanks: 1,
    entryIds: [102622],
    manaCost: 5250,
  },
  REBUKE_TALENT: {
    id: 96231,
    name: 'Rebuke',
    icon: 'spell_holy_rebuke',
    maxRanks: 1,
    entryIds: [102591],
  },
  GOLDEN_PATH_TALENT: {
    id: 377128,
    name: 'Golden Path',
    icon: 'ability_priest_cascade',
    maxRanks: 1,
    entryIds: [102598],
  },
  JUDGMENT_OF_LIGHT_TALENT: {
    id: 183778,
    name: 'Judgment of Light',
    icon: 'spell_holy_divineprovidence',
    maxRanks: 1,
    entryIds: [102596],
  },
  BLESSING_OF_SACRIFICE_TALENT: {
    id: 6940,
    name: 'Blessing of Sacrifice',
    icon: 'spell_holy_sealofsacrifice',
    maxRanks: 1,
    entryIds: [102602],
    manaCost: 3500,
  },
  BLESSING_OF_PROTECTION_TALENT: {
    id: 1022,
    name: 'Blessing of Protection',
    icon: 'spell_holy_sealofprotection',
    maxRanks: 1,
    entryIds: [102604],
    manaCost: 7500,
  },
  SEAL_OF_REPRISAL_TALENT: {
    id: 377053,
    name: 'Seal of Reprisal',
    icon: 'spell_holy_sealoffury',
    maxRanks: 2,
    entryIds: [102621],
  },
  SEAL_OF_MERCY_TALENT: {
    id: 384897,
    name: 'Seal of Mercy',
    icon: 'spell_holy_greaterblessingofsalvation',
    maxRanks: 2,
    entryIds: [102599],
  },
  AFTERIMAGE_TALENT: {
    id: 385414,
    name: 'Afterimage',
    icon: 'spell_holy_aspiration',
    maxRanks: 1,
    entryIds: [102601],
  },
  SACRIFICE_OF_THE_JUST_TALENT: {
    id: 384820,
    name: 'Sacrifice of the Just',
    icon: 'spell_holy_sealofsacrifice',
    maxRanks: 1,
    entryIds: [102595],
  },
  RECOMPENSE_TALENT: {
    id: 384914,
    name: 'Recompense',
    icon: 'ability_racial_foregedinflames',
    maxRanks: 1,
    entryIds: [102594],
  },
  UNBREAKABLE_SPIRIT_TALENT: {
    id: 114154,
    name: 'Unbreakable Spirit',
    icon: 'spell_holy_holyguidance',
    maxRanks: 1,
    entryIds: [102603],
  },
  IMPROVED_BLESSING_OF_PROTECTION_TALENT: {
    id: 384909,
    name: 'Improved Blessing of Protection',
    icon: 'spell_holy_sealofprotection',
    maxRanks: 1,
    entryIds: [102606],
  },
  INCANDESCENCE_TALENT: {
    id: 385464,
    name: 'Incandescence',
    icon: 'inv_summerfest_firespirit',
    maxRanks: 1,
    entryIds: [102620],
  },
  TOUCH_OF_LIGHT_TALENT: {
    id: 385349,
    name: 'Touch of Light',
    icon: 'achievment_raid_houroftwilight',
    maxRanks: 1,
    entryIds: [102619],
  },
  SEAL_OF_CLARITY_TALENT: {
    id: 384815,
    name: 'Seal of Clarity',
    icon: 'spell_priest_power_word',
    maxRanks: 2,
    entryIds: [102600],
  },
  ASPIRATION_OF_DIVINITY_TALENT: {
    id: 385416,
    name: 'Aspiration of Divinity',
    icon: 'spell_holy_fanaticism',
    maxRanks: 2,
    entryIds: [102613],
  },
  DIVINE_PURPOSE_TALENT: {
    id: 223817,
    name: 'Divine Purpose',
    icon: 'spell_holy_divinepurpose',
    maxRanks: 1,
    entryIds: [102608],
  },
  HOLY_AVENGER_TALENT: {
    id: 105809,
    name: 'Holy Avenger',
    icon: 'ability_paladin_holyavenger',
    maxRanks: 1,
    entryIds: [102607],
  },
  OBDURACY_TALENT: {
    id: 385427,
    name: 'Obduracy',
    icon: 'ability_paladin_speedoflight',
    maxRanks: 1,
    entryIds: [102618],
  },
  HALLOWED_GROUND_TALENT: {
    id: 377043,
    name: 'Hallowed Ground',
    icon: 'ability_paladin_empoweredsealsrighteous',
    maxRanks: 1,
    entryIds: [102478],
  },
  OF_DUSK_AND_DAWN_TALENT: {
    id: 385125,
    name: 'Of Dusk and Dawn',
    icon: 'spell_paladin_lightofdawn',
    maxRanks: 1,
    entryIds: [102615],
  },
  SEAL_OF_MIGHT_TALENT: {
    id: 385450,
    name: 'Seal of Might',
    icon: 'spell_holy_sealofwrath',
    maxRanks: 2,
    entryIds: [102612],
  },
  SEAL_OF_ALACRITY_TALENT: {
    id: 385425,
    name: 'Seal of Alacrity',
    icon: 'spell_holy_sealofvengeance',
    maxRanks: 2,
    entryIds: [102609],
  },
  SEAL_OF_THE_CRUSADER_TALENT: {
    id: 385728,
    name: 'Seal of the Crusader',
    icon: 'spell_holy_holysmite',
    maxRanks: 2,
    entryIds: [102617],
  },
  SEAL_OF_ORDER_TALENT: {
    id: 385129,
    name: 'Seal of Order',
    icon: 'spell_holy_sealofwisdom',
    maxRanks: 1,
    entryIds: [102614],
  },
  SANCTIFIED_WRATH_TALENT: {
    id: 31884,
    name: 'Sanctified Wrath',
    icon: 'ability_paladin_judgementsofthejust',
    maxRanks: 1,
    entryIds: [102611],
  },
  SERAPHIM_TALENT: {
    id: 152262,
    name: 'Seraphim',
    icon: 'ability_paladin_seraphim',
    maxRanks: 1,
    entryIds: [102610],
    holyPowerCost: 3,
  },
  ZEALOTS_PARAGON_TALENT: {
    id: 391142,
    name: "Zealot's Paragon",
    icon: 'ability_paladin_conviction',
    maxRanks: 1,
    entryIds: [102616],
  },
  IMPROVED_CLEANSE_TALENT: {
    id: 393024,
    name: 'Improved Cleanse',
    icon: 'spell_holy_purify',
    maxRanks: 1,
    entryIds: [102477],
  },
  AVENGERS_SHIELD_TALENT: {
    id: 31935,
    name: "Avenger's Shield",
    icon: 'spell_holy_avengersshield',
    maxRanks: 1,
    entryIds: [102471],
  },
  HAMMER_OF_THE_RIGHTEOUS_TALENT: {
    id: 53595,
    name: 'Hammer of the Righteous',
    icon: 'ability_paladin_hammeroftherighteous',
    maxRanks: 1,
    entryIds: [102431],
  },
  BLESSED_HAMMER_TALENT: {
    id: 204019,
    name: 'Blessed Hammer',
    icon: 'paladin_retribution',
    maxRanks: 1,
    entryIds: [102430],
  },
  INNER_LIGHT_TALENT: {
    id: 386568,
    name: 'Inner Light',
    icon: 'ability_paladin_shieldofvengeance',
    maxRanks: 1,
    entryIds: [102463],
  },
  REDOUBT_TALENT: {
    id: 280373,
    name: 'Redoubt',
    icon: 'ability_warrior_shieldguard',
    maxRanks: 1,
    entryIds: [102462],
  },
  HOLY_SHIELD_TALENT: {
    id: 152261,
    name: 'Holy Shield',
    icon: 'inv_shield_1h_hyrja_d_01',
    maxRanks: 1,
    entryIds: [102455],
  },
  GRAND_CRUSADER_TALENT: {
    id: 85043,
    name: 'Grand Crusader',
    icon: 'inv_helmet_74',
    maxRanks: 1,
    entryIds: [102453],
  },
  SHINING_LIGHT_TALENT: {
    id: 321136,
    name: 'Shining Light',
    icon: 'ability_paladin_toweroflight',
    maxRanks: 1,
    entryIds: [102467],
  },
  CONSECRATED_GROUND_TALENT: {
    id: 204054,
    name: 'Consecrated Ground',
    icon: 'ability_paladin_righteousvengeance',
    maxRanks: 1,
    entryIds: [102459, 102508],
  },
  IMPROVED_LAY_ON_HANDS_TALENT: {
    id: 393027,
    name: 'Improved Lay on Hands',
    icon: 'spell_holy_layonhands',
    maxRanks: 1,
    entryIds: [102458],
  },
  INSPIRING_VANGUARD_TALENT: {
    id: 393022,
    name: 'Inspiring Vanguard',
    icon: 'inv_helmet_74',
    maxRanks: 1,
    entryIds: [102439],
  },
  ARDENT_DEFENDER_TALENT: {
    id: 31850,
    name: 'Ardent Defender',
    icon: 'spell_holy_ardentdefender',
    maxRanks: 1,
    entryIds: [102445],
  },
  BARRICADE_OF_FAITH_TALENT: {
    id: 385726,
    name: 'Barricade of Faith',
    icon: 'ability_paladin_barrieroffaith',
    maxRanks: 1,
    entryIds: [102470],
  },
  CONSECRATION_IN_FLAME_TALENT: {
    id: 379022,
    name: 'Consecration in Flame',
    icon: 'spell_fire_sealoffire',
    maxRanks: 1,
    entryIds: [102432],
  },
  IMPROVED_HOLY_SHIELD_TALENT: {
    id: 393030,
    name: 'Improved Holy Shield',
    icon: 'inv_shield_1h_hyrja_d_01',
    maxRanks: 1,
    entryIds: [102452],
  },
  SANCTUARY_TALENT: {
    id: 379021,
    name: 'Sanctuary',
    icon: 'spell_holy_innerfire',
    maxRanks: 1,
    entryIds: [102451],
  },
  BULWARK_OF_ORDER_TALENT: {
    id: 209389,
    name: 'Bulwark of Order',
    icon: 'spell_holy_pureofheart',
    maxRanks: 2,
    entryIds: [102468],
  },
  IMPROVED_ARDENT_DEFENDER_TALENT: {
    id: 393114,
    name: 'Improved Ardent Defender',
    icon: 'spell_holy_ardentdefender',
    maxRanks: 1,
    entryIds: [111887],
  },
  BLESSING_OF_SPELLWARDING_TALENT: {
    id: 204018,
    name: 'Blessing of Spellwarding',
    icon: 'spell_holy_blessingofprotection',
    maxRanks: 1,
    entryIds: [111886],
    manaCost: 7500,
  },
  LIGHT_OF_THE_TITANS_TALENT: {
    id: 378405,
    name: 'Light of the Titans',
    icon: 'spell_paladin_lightofdawn',
    maxRanks: 2,
    entryIds: [102472],
  },
  STRENGTH_IN_ADVERSITY_TALENT: {
    id: 393071,
    name: 'Strength in Adversity',
    icon: 'spell_holy_weaponmastery',
    maxRanks: 1,
    entryIds: [102461],
  },
  CRUSADERS_RESOLVE_TALENT: {
    id: 380188,
    name: "Crusader's Resolve",
    icon: 'ability_priest_angelicbulwark',
    maxRanks: 1,
    entryIds: [102460],
  },
  TYRS_ENFORCER_TALENT: {
    id: 378285,
    name: "Tyr's Enforcer",
    icon: 'spell_holy_persecution',
    maxRanks: 2,
    entryIds: [102437],
  },
  RELENTLESS_INQUISITOR_TALENT: {
    id: 383388,
    name: 'Relentless Inquisitor',
    icon: 'spell_holy_mindvision',
    maxRanks: 1,
    entryIds: [102475, 102514, 102575],
  },
  AVENGING_WRATH_MIGHT_TALENT: {
    id: 31884,
    name: 'Avenging Wrath: Might',
    icon: 'spell_holy_avenginewrath',
    maxRanks: 1,
    entryIds: [102448, 102497, 102569],
  },
  SENTINEL_TALENT: {
    id: 389539,
    name: 'Sentinel',
    icon: 'spell_holy_holynova',
    maxRanks: 1,
    entryIds: [102447],
  },
  HAND_OF_THE_PROTECTOR_TALENT: {
    id: 315924,
    name: 'Hand of the Protector',
    icon: 'ability_paladin_blessedhands',
    maxRanks: 1,
    entryIds: [102438],
  },
  STRENGTH_OF_CONVICTION_TALENT: {
    id: 379008,
    name: 'Strength of Conviction',
    icon: 'spell_holy_eyeforaneye',
    maxRanks: 2,
    entryIds: [102450],
  },
  RESOLUTE_DEFENDER_TALENT: {
    id: 385422,
    name: 'Resolute Defender',
    icon: 'ability_crown_of_the_heavens_icon',
    maxRanks: 1,
    entryIds: [102433],
  },
  BASTION_OF_LIGHT_TALENT: {
    id: 378974,
    name: 'Bastion of Light',
    icon: 'paladin_protection',
    maxRanks: 1,
    entryIds: [102454],
  },
  GUARDIAN_OF_ANCIENT_KINGS_TALENT: {
    id: 86659,
    name: 'Guardian of Ancient Kings',
    icon: 'spell_holy_heroism',
    maxRanks: 1,
    entryIds: [102456],
  },
  CRUSADERS_JUDGMENT_TALENT: {
    id: 204023,
    name: "Crusader's Judgment",
    icon: 'ability_paladin_enlightenedjudgements',
    maxRanks: 1,
    entryIds: [102436],
  },
  UTHERS_COUNSEL_TALENT: {
    id: 378425,
    name: "Uther's Counsel",
    icon: 'spell_holy_greaterblessingofsalvation',
    maxRanks: 1,
    entryIds: [102469],
  },
  FOCUSED_ENMITY_TALENT: {
    id: 378845,
    name: 'Focused Enmity',
    icon: 'ability_priest_flashoflight',
    maxRanks: 1,
    entryIds: [102435],
  },
  SOARING_SHIELD_TALENT: {
    id: 378457,
    name: 'Soaring Shield',
    icon: 'spell_burningbladeshaman_lavaslash',
    maxRanks: 1,
    entryIds: [102434],
  },
  GIFT_OF_THE_GOLDEN_VALKYR_TALENT: {
    id: 378279,
    name: "Gift of the Golden Val'kyr",
    icon: 'inv_valkiergoldpet',
    maxRanks: 2,
    entryIds: [102449],
  },
  EYE_OF_TYR_TALENT: {
    id: 387174,
    name: 'Eye of Tyr',
    icon: 'inv_shield_1h_artifactnorgannon_d_01',
    maxRanks: 1,
    entryIds: [102466],
  },
  RIGHTEOUS_PROTECTOR_TALENT: {
    id: 204074,
    name: 'Righteous Protector',
    icon: 'ability_paladin_shieldofthetemplar',
    maxRanks: 2,
    entryIds: [102440],
  },
  FAITH_IN_THE_LIGHT_TALENT: {
    id: 379043,
    name: 'Faith in the Light',
    icon: 'spell_holy_redemption',
    maxRanks: 2,
    entryIds: [102444],
  },
  FERREN_MARCUSS_FERVOR_TALENT: {
    id: 378762,
    name: "Ferren Marcus's Fervor",
    icon: 'spell_holy_sealofwrath',
    maxRanks: 2,
    entryIds: [102446],
  },
  FAITHS_ARMOR_TALENT: {
    id: 379017,
    name: "Faith's Armor",
    icon: 'ability_paladin_shieldofvengeance',
    maxRanks: 1,
    entryIds: [102464],
  },
  FINAL_STAND_TALENT: {
    id: 204077,
    name: 'Final Stand',
    icon: 'spell_holy_crusade',
    maxRanks: 1,
    entryIds: [102473],
  },
  DIVINE_TOLL_TALENT: {
    id: 375576,
    name: 'Divine Toll',
    icon: 'ability_bastion_paladin',
    maxRanks: 1,
    entryIds: [102465, 102513, 102563],
    manaCost: 7500,
  },
  MOMENT_OF_GLORY_TALENT: {
    id: 327193,
    name: 'Moment of Glory',
    icon: 'spell_holy_aspiration',
    maxRanks: 1,
    entryIds: [102474],
  },
  BULWARK_OF_RIGHTEOUS_FURY_TALENT: {
    id: 386653,
    name: 'Bulwark of Righteous Fury',
    icon: 'spell_holy_sealofrighteousness',
    maxRanks: 1,
    entryIds: [102457],
  },
  DIVINE_RESONANCE_PROTECTION_TALENT: {
    id: 386738,
    name: 'Divine Resonance',
    icon: 'ability_mount_goatmountwhite',
    maxRanks: 1,
    entryIds: [102443],
  },
  DIVINE_RESONANCE_RETRIBUTION_TALENT: {
    id: 384027,
    name: 'Divine Resonance',
    icon: 'ability_mount_goatmountwhite',
    maxRanks: 1,
    entryIds: [102512],
  },
  DIVINE_RESONANCE_HOLY_TALENT: {
    id: 387893,
    name: 'Divine Resonance',
    icon: 'ability_mount_goatmountwhite',
    maxRanks: 1,
    entryIds: [102582],
  },
  QUICKENED_INVOCATIONS_TALENT: {
    id: 379391,
    name: 'Quickened Invocations',
    icon: 'spell_holy_pureofheart',
    maxRanks: 1,
    entryIds: [102442],
  },
  BLADE_OF_JUSTICE_TALENT: {
    id: 184575,
    name: 'Blade of Justice',
    icon: 'ability_paladin_bladeofjustice',
    maxRanks: 1,
    entryIds: [102498],
  },
  DIVINE_STORM_TALENT: {
    id: 53385,
    name: 'Divine Storm',
    icon: 'ability_paladin_divinestorm',
    maxRanks: 1,
    entryIds: [102501],
    holyPowerCost: 3,
  },
  ART_OF_WAR_TALENT: {
    id: 267344,
    name: 'Art of War',
    icon: 'ability_paladin_artofwar',
    maxRanks: 1,
    entryIds: [102523],
  },
  IMPROVED_JUDGMENT_TALENT: {
    id: 383228,
    name: 'Improved Judgment',
    icon: 'ability_paladin_judgementofthepure',
    maxRanks: 1,
    entryIds: [102502],
  },
  IMPROVED_CRUSADER_STRIKE_TALENT: {
    id: 383254,
    name: 'Improved Crusader Strike',
    icon: 'spell_holy_crusaderstrike',
    maxRanks: 1,
    entryIds: [102500],
  },
  HOLY_CRUSADER_TALENT: {
    id: 386967,
    name: 'Holy Crusader',
    icon: 'spell_holy_power',
    maxRanks: 1,
    entryIds: [102499],
  },
  HOLY_BLADE_TALENT: {
    id: 383342,
    name: 'Holy Blade',
    icon: 'ability_paladin_lightoftheprotector',
    maxRanks: 1,
    entryIds: [102522],
  },
  BLADE_OF_CONDEMNATION_TALENT: {
    id: 383263,
    name: 'Blade of Condemnation',
    icon: 'ability_skyreach_spinning_blade',
    maxRanks: 1,
    entryIds: [102482],
  },
  EMPYREAN_POWER_TALENT: {
    id: 326732,
    name: 'Empyrean Power',
    icon: 'ability_paladin_sheathoflight',
    maxRanks: 1,
    entryIds: [102504],
  },
  SHIELD_OF_VENGEANCE_TALENT: {
    id: 184662,
    name: 'Shield of Vengeance',
    icon: 'ability_paladin_shieldofthetemplar',
    maxRanks: 1,
    entryIds: [102521],
  },
  DIVINE_PROTECTION_TALENT: {
    id: 498,
    name: 'Divine Protection',
    icon: 'spell_holy_divineprotection',
    maxRanks: 1,
    entryIds: [102520, 102549],
    manaCost: 1750,
  },
  BLADE_OF_WRATH_TALENT: {
    id: 231832,
    name: 'Blade of Wrath',
    icon: 'ability_paladin_bladeofjustice',
    maxRanks: 1,
    entryIds: [102491],
  },
  HIGHLORDS_JUDGMENT_TALENT: {
    id: 383271,
    name: "Highlord's Judgment",
    icon: 'spell_holy_righteousfury',
    maxRanks: 2,
    entryIds: [102505],
  },
  RIGHTEOUS_VERDICT_TALENT: {
    id: 267610,
    name: 'Righteous Verdict',
    icon: 'spell_paladin_templarsverdict',
    maxRanks: 1,
    entryIds: [102503],
  },
  SANCTIFY_TALENT: {
    id: 382536,
    name: 'Sanctify',
    icon: 'achievement_zone_firelands',
    maxRanks: 1,
    entryIds: [102519],
  },
  WAKE_OF_ASHES_TALENT: {
    id: 255937,
    name: 'Wake of Ashes',
    icon: 'inv_sword_2h_artifactashbringerfire_d_03',
    maxRanks: 1,
    entryIds: [102495],
  },
  CONSECRATED_BLADE_TALENT: {
    id: 382275,
    name: 'Consecrated Blade',
    icon: 'ability_mage_firestarter',
    maxRanks: 1,
    entryIds: [102531],
  },
  SEAL_OF_WRATH_TALENT: {
    id: 386901,
    name: 'Seal of Wrath',
    icon: 'ability_paladin_empoweredsealstruth',
    maxRanks: 1,
    entryIds: [102490],
  },
  EXPURGATION_TALENT: {
    id: 383344,
    name: 'Expurgation',
    icon: 'ability_paladin_bladeofjusticeblue',
    maxRanks: 1,
    entryIds: [102489],
  },
  BOUNDLESS_JUDGMENT_TALENT: {
    id: 383876,
    name: 'Boundless Judgment',
    icon: 'ability_paladin_judgementofthewise',
    maxRanks: 1,
    entryIds: [102506],
  },
  SANCTIFICATION_TALENT: {
    id: 382430,
    name: 'Sanctification',
    icon: 'spell_holy_surgeoflight',
    maxRanks: 1,
    entryIds: [102518],
  },
  INNER_GRACE_TALENT: {
    id: 383334,
    name: 'Inner Grace',
    icon: 'ability_paladin_toweroflight',
    maxRanks: 1,
    entryIds: [102517],
  },
  ASHES_TO_DUST_TALENT: {
    id: 383300,
    name: 'Ashes to Dust',
    icon: 'inv_sword_2h_artifactashbringerpurified_d_02',
    maxRanks: 1,
    entryIds: [102494],
  },
  RADIANT_DECREE_TALENT: {
    id: 384052,
    name: 'Radiant Decree',
    icon: 'inv_sword_2h_artifactashbringerfire_d_02',
    maxRanks: 1,
    entryIds: [102493],
  },
  CRUSADE_TALENT: {
    id: 231895,
    name: 'Crusade',
    icon: 'ability_paladin_sanctifiedwrath',
    maxRanks: 1,
    entryIds: [102496],
  },
  TRUTHS_WAKE_TALENT: {
    id: 383350,
    name: "Truth's Wake",
    icon: 'inv_mace_104',
    maxRanks: 1,
    entryIds: [102492],
  },
  ZEAL_TALENT: {
    id: 269569,
    name: 'Zeal',
    icon: 'spell_holy_sealofblood',
    maxRanks: 1,
    entryIds: [102530],
  },
  FIRES_OF_JUSTICE_TALENT: {
    id: 203316,
    name: 'Fires of Justice',
    icon: 'spell_holy_crusaderstrike',
    maxRanks: 1,
    entryIds: [102529],
  },
  SEALED_VERDICT_TALENT: {
    id: 387640,
    name: 'Sealed Verdict',
    icon: 'ability_paladin_swiftretribution',
    maxRanks: 2,
    entryIds: [102488],
  },
  SANCTIFIED_GROUND_TALENT: {
    id: 387479,
    name: 'Sanctified Ground',
    icon: 'warrior_talent_icon_skirmisher',
    maxRanks: 1,
    entryIds: [102507],
  },
  EXORCISM_TALENT: {
    id: 383185,
    name: 'Exorcism',
    icon: 'spell_holy_excorcism_02',
    maxRanks: 1,
    entryIds: [102516],
  },
  HAND_OF_HINDRANCE_TALENT: {
    id: 183218,
    name: 'Hand of Hindrance',
    icon: 'ability_paladin_handofhindrance',
    maxRanks: 1,
    entryIds: [102515],
    manaCost: 5000,
  },
  SELFLESS_HEALER_TALENT: {
    id: 85804,
    name: 'Selfless Healer',
    icon: 'ability_paladin_gaurdedbythelight',
    maxRanks: 1,
    entryIds: [102528],
  },
  HEALING_HANDS_TALENT: {
    id: 326734,
    name: 'Healing Hands',
    icon: 'ability_paladin_infusionoflight',
    maxRanks: 1,
    entryIds: [102527],
  },
  TEMPEST_OF_THE_LIGHTBRINGER_TALENT: {
    id: 383396,
    name: 'Tempest of the Lightbringer',
    icon: 'ability_malkorok_blightofyshaarj_yellow',
    maxRanks: 1,
    entryIds: [102481],
  },
  JUSTICARS_VENGEANCE_TALENT: {
    id: 215661,
    name: "Justicar's Vengeance",
    icon: 'spell_holy_retributionaura',
    maxRanks: 1,
    entryIds: [102487],
    holyPowerCost: 3,
  },
  EYE_FOR_AN_EYE_TALENT: {
    id: 205191,
    name: 'Eye for an Eye',
    icon: 'spell_holy_weaponmastery',
    maxRanks: 1,
    entryIds: [102486],
  },
  ASHES_TO_ASHES_TALENT: {
    id: 383276,
    name: 'Ashes to Ashes',
    icon: 'inv_artifact_ashes_to_ashes',
    maxRanks: 2,
    entryIds: [102526],
  },
  TEMPLARS_VINDICATION_TALENT: {
    id: 383274,
    name: "Templar's Vindication",
    icon: 'ability_priest_evangelism',
    maxRanks: 2,
    entryIds: [102485],
  },
  EXECUTION_SENTENCE_TALENT: {
    id: 343527,
    name: 'Execution Sentence',
    icon: 'spell_paladin_executionsentence',
    maxRanks: 1,
    entryIds: [102511],
    holyPowerCost: 3,
  },
  EMPYREAN_LEGACY_TALENT: {
    id: 387170,
    name: 'Empyrean Legacy',
    icon: 'item_holyspark',
    maxRanks: 1,
    entryIds: [102480, 102576],
  },
  VIRTUOUS_COMMAND_TALENT: {
    id: 383304,
    name: 'Virtuous Command',
    icon: 'spell_holy_sealofvengeance',
    maxRanks: 2,
    entryIds: [102525],
  },
  FINAL_VERDICT_TALENT: {
    id: 383328,
    name: 'Final Verdict',
    icon: 'spell_paladin_templarsverdict',
    maxRanks: 1,
    entryIds: [102484],
    holyPowerCost: 3,
  },
  EXECUTIONERS_WILL_TALENT: {
    id: 384162,
    name: "Executioner's Will",
    icon: 'inv_helm_plate_raidpaladinmythic_q_01',
    maxRanks: 1,
    entryIds: [102510],
  },
  EXECUTIONERS_WRATH_TALENT: {
    id: 387196,
    name: "Executioner's Wrath",
    icon: 'inv_glove_plate_raidpaladinmythic_q_01',
    maxRanks: 1,
    entryIds: [102509],
  },
  FINAL_RECKONING_TALENT: {
    id: 343721,
    name: 'Final Reckoning',
    icon: 'spell_holy_blessedresillience',
    maxRanks: 1,
    entryIds: [102524],
  },
  VANGUARDS_MOMENTUM_TALENT: {
    id: 383314,
    name: "Vanguard's Momentum",
    icon: 'ability_paladin_speedoflight',
    maxRanks: 2,
    entryIds: [102483],
  },
  HOLY_SHOCK_TALENT: {
    id: 20473,
    name: 'Holy Shock',
    icon: 'spell_holy_searinglight',
    maxRanks: 1,
    entryIds: [102534],
    manaCost: 8000,
  },
  HOLY_LIGHT_TALENT: {
    id: 82326,
    name: 'Holy Light',
    icon: 'spell_holy_surgeoflight',
    maxRanks: 1,
    entryIds: [102550],
    manaCost: 8000,
  },
  LIGHT_OF_DAWN_TALENT: {
    id: 85222,
    name: 'Light of Dawn',
    icon: 'spell_paladin_lightofdawn',
    maxRanks: 1,
    entryIds: [102545],
    holyPowerCost: 3,
  },
  ILLUMINATION_TALENT: {
    id: 387993,
    name: 'Illumination',
    icon: 'spell_paladin_clarityofpurpose',
    maxRanks: 1,
    entryIds: [102555],
  },
  DIVINE_INSIGHT_TALENT: {
    id: 392914,
    name: 'Divine Insight',
    icon: 'spell_holy_pureofheart',
    maxRanks: 1,
    entryIds: [102554],
  },
  UNENDING_LIGHT_TALENT: {
    id: 387998,
    name: 'Unending Light',
    icon: 'spell_holy_holybolt',
    maxRanks: 1,
    entryIds: [102544],
  },
  BESTOW_FAITH_TALENT: {
    id: 223306,
    name: 'Bestow Faith',
    icon: 'ability_paladin_blessedmending',
    maxRanks: 1,
    entryIds: [102543],
    manaCost: 3000,
  },
  MOMENT_OF_COMPASSION_TALENT: {
    id: 387786,
    name: 'Moment of Compassion',
    icon: 'spell_holy_flashheal',
    maxRanks: 1,
    entryIds: [102553],
  },
  RESPLENDENT_LIGHT_TALENT: {
    id: 392902,
    name: 'Resplendent Light',
    icon: 'ability_priest_voidshift',
    maxRanks: 1,
    entryIds: [102552],
  },
  TIRIONS_DEVOTION_TALENT: {
    id: 392928,
    name: "Tirion's Devotion",
    icon: 'spell_holy_holyguidance',
    maxRanks: 1,
    entryIds: [102556],
  },
  AURA_MASTERY_TALENT: {
    id: 31821,
    name: 'Aura Mastery',
    icon: 'spell_holy_auramastery',
    maxRanks: 1,
    entryIds: [102548],
  },
  EMPYREAL_WARD_TALENT: {
    id: 387791,
    name: 'Empyreal Ward',
    icon: 'spell_holy_layonhands',
    maxRanks: 1,
    entryIds: [102558],
  },
  RULE_OF_LAW_TALENT: {
    id: 214202,
    name: 'Rule of Law',
    icon: 'ability_paladin_longarmofthelaw',
    maxRanks: 1,
    entryIds: [102541],
  },
  DIVINE_FAVOR_TALENT: {
    id: 210294,
    name: 'Divine Favor',
    icon: 'spell_holy_heal',
    maxRanks: 1,
    entryIds: [102551],
  },
  SHINING_SAVIOR_TALENT: {
    id: 388005,
    name: 'Shining Savior',
    icon: 'ability_paladin_sacredcleansing',
    maxRanks: 1,
    entryIds: [102559],
  },
  UNWAVERING_SPIRIT_TALENT: {
    id: 392911,
    name: 'Unwavering Spirit',
    icon: 'spell_holy_fanaticism',
    maxRanks: 1,
    entryIds: [102547],
  },
  PROTECTION_OF_TYR_TALENT: {
    id: 200430,
    name: 'Protection of Tyr',
    icon: 'spell_holy_auramastery',
    maxRanks: 1,
    entryIds: [102546],
  },
  IMBUED_INFUSIONS_TALENT: {
    id: 392961,
    name: 'Imbued Infusions',
    icon: 'ability_priest_flashoflight',
    maxRanks: 1,
    entryIds: [102536],
  },
  LIGHTS_HAMMER_TALENT: {
    id: 114158,
    name: "Light's Hammer",
    icon: 'spell_paladin_lightshammer',
    maxRanks: 1,
    entryIds: [102561],
    manaCost: 9000,
  },
  HOLY_PRISM_TALENT: {
    id: 114165,
    name: 'Holy Prism',
    icon: 'spell_paladin_holyprism',
    maxRanks: 1,
    entryIds: [102560],
    manaCost: 6500,
  },
  SAVED_BY_THE_LIGHT_TALENT: {
    id: 157047,
    name: 'Saved by the Light',
    icon: 'ability_paladin_savedbythelight',
    maxRanks: 1,
    entryIds: [102542],
  },
  RADIANT_ONSLAUGHT_TALENT: {
    id: 231667,
    name: 'Radiant Onslaught',
    icon: 'spell_holy_crusaderstrike',
    maxRanks: 1,
    entryIds: [102557],
  },
  TOWER_OF_RADIANCE_TALENT: {
    id: 231642,
    name: 'Tower of Radiance',
    icon: 'ability_paladin_beaconoflight',
    maxRanks: 1,
    entryIds: [102571],
  },
  ECHOING_BLESSINGS_TALENT: {
    id: 387801,
    name: 'Echoing Blessings',
    icon: 'achievement_dungeon_heroic_gloryoftheraider',
    maxRanks: 1,
    entryIds: [102535],
  },
  LIGHT_OF_THE_MARTYR_TALENT: {
    id: 183998,
    name: 'Light of the Martyr',
    icon: 'ability_paladin_lightofthemartyr',
    maxRanks: 1,
    entryIds: [102540],
    manaCost: 4500,
  },
  DIVINE_REVELATIONS_TALENT: {
    id: 387808,
    name: 'Divine Revelations',
    icon: 'ability_paladin_infusionoflight',
    maxRanks: 1,
    entryIds: [102562],
  },
  COMMANDING_LIGHT_TALENT: {
    id: 387781,
    name: 'Commanding Light',
    icon: 'ability_paladin_beaconoflight',
    maxRanks: 2,
    entryIds: [102564],
  },
  SECOND_SUNRISE_TALENT: {
    id: 200482,
    name: 'Second Sunrise',
    icon: 'spell_holy_lightsgrace',
    maxRanks: 2,
    entryIds: [102567],
  },
  DIVINE_GLIMPSE_TALENT: {
    id: 387805,
    name: 'Divine Glimpse',
    icon: 'spell_holy_healingaura',
    maxRanks: 2,
    entryIds: [102570],
  },
  UNTEMPERED_DEDICATION_TALENT: {
    id: 387814,
    name: 'Untempered Dedication',
    icon: 'achievement_admiral_of_the_light',
    maxRanks: 1,
    entryIds: [102539],
  },
  BEACON_OF_FAITH_TALENT: {
    id: 156910,
    name: 'Beacon of Faith',
    icon: 'ability_paladin_beaconsoflight',
    maxRanks: 1,
    entryIds: [102533],
    manaCost: 1563,
  },
  BEACON_OF_VIRTUE_TALENT: {
    id: 200025,
    name: 'Beacon of Virtue',
    icon: 'ability_paladin_beaconofinsight',
    maxRanks: 1,
    entryIds: [102532],
    manaCost: 5000,
  },
  VENERATION_TALENT: {
    id: 392938,
    name: 'Veneration',
    icon: 'ability_crown_of_the_heavens_icon',
    maxRanks: 1,
    entryIds: [102565],
  },
  BREAKING_DAWN_TALENT: {
    id: 387879,
    name: 'Breaking Dawn',
    icon: 'spell_holy_rune',
    maxRanks: 1,
    entryIds: [102566],
  },
  AVENGING_CRUSADER_TALENT: {
    id: 216331,
    name: 'Avenging Crusader',
    icon: 'ability_paladin_veneration',
    maxRanks: 1,
    entryIds: [102568],
    manaCost: 25000,
  },
  POWER_OF_THE_SILVER_HAND_TALENT: {
    id: 200474,
    name: 'Power of the Silver Hand',
    icon: 'ability_paladin_blessedhands',
    maxRanks: 1,
    entryIds: [102574],
  },
  BARRIER_OF_FAITH_TALENT: {
    id: 148039,
    name: 'Barrier of Faith',
    icon: 'ability_paladin_barrieroffaith',
    maxRanks: 1,
    entryIds: [102537],
    manaCost: 8000,
  },
  MARAADS_DYING_BREATH_TALENT: {
    id: 388018,
    name: "Maraad's Dying Breath",
    icon: 'paladin_icon_speedoflight',
    maxRanks: 1,
    entryIds: [102538],
  },
  CRUSADERS_MIGHT_TALENT: {
    id: 196926,
    name: "Crusader's Might",
    icon: 'ability_paladin_swiftretribution',
    maxRanks: 2,
    entryIds: [102580],
  },
  AWAKENING_TALENT: {
    id: 248033,
    name: 'Awakening',
    icon: 'inv_helm_plate_raidpaladin_n_01',
    maxRanks: 2,
    entryIds: [102578],
  },
  TYRS_DELIVERANCE_TALENT: {
    id: 200652,
    name: "Tyr's Deliverance",
    icon: 'inv_mace_2h_artifactsilverhand_d_01',
    maxRanks: 1,
    entryIds: [102573],
    manaCost: 6000,
  },
  GLIMMER_OF_LIGHT_TALENT: {
    id: 325966,
    name: 'Glimmer of Light',
    icon: 'ability_paladin_toweroflight',
    maxRanks: 1,
    entryIds: [102581],
  },
  BLESSING_OF_SUMMER_TALENT: {
    id: 388007,
    name: 'Blessing of Summer',
    icon: 'ability_ardenweald_paladin_summer',
    maxRanks: 1,
    entryIds: [102579],
    manaCost: 2500,
  },
  INFLORESCENCE_OF_THE_SUNWELL_TALENT: {
    id: 392907,
    name: 'Inflorescence of the Sunwell',
    icon: 'spell_lfieblood',
    maxRanks: 1,
    entryIds: [102577],
  },
  BOUNDLESS_SALVATION_TALENT: {
    id: 392951,
    name: 'Boundless Salvation',
    icon: 'ability_paladin_selflesshealer',
    maxRanks: 1,
    entryIds: [102572],
  },
});

export default talents;
export { talents as TALENTS_PALADIN };
