// Generated file, changes will eventually be overwritten!
import { createTalentList } from './types';

const talents = createTalentList({
  SHIV_TALENT: {
    id: 5938,
    name: 'Shiv',
    icon: 'inv_throwingknife_04',
    maxRanks: 1,
    entryIds: [112630],
    energyCost: 20,
  },
  BLIND_TALENT: {
    id: 2094,
    name: 'Blind',
    icon: 'spell_shadow_mindsteal',
    maxRanks: 1,
    entryIds: [112572],
  },
  SAP_TALENT: {
    id: 6770,
    name: 'Sap',
    icon: 'ability_sap',
    maxRanks: 1,
    entryIds: [112573],
    energyCost: 35,
  },
  EVASION_TALENT: {
    id: 5277,
    name: 'Evasion',
    icon: 'spell_shadow_shadowward',
    maxRanks: 1,
    entryIds: [112657],
  },
  ELUSIVENESS_TALENT: {
    id: 79008,
    name: 'Elusiveness',
    icon: 'ability_rogue_turnthetables',
    maxRanks: 1,
    entryIds: [112632],
  },
  CLOAK_OF_SHADOWS_TALENT: {
    id: 31224,
    name: 'Cloak of Shadows',
    icon: 'spell_shadow_nethercloak',
    maxRanks: 1,
    entryIds: [112585],
  },
  MASTER_POISONER_TALENT: {
    id: 378436,
    name: 'Master Poisoner',
    icon: 'ability_creature_poison_06',
    maxRanks: 1,
    entryIds: [112521],
  },
  NUMBING_POISON_TALENT: {
    id: 5761,
    name: 'Numbing Poison',
    icon: 'spell_nature_nullifydisease',
    maxRanks: 1,
    entryIds: [112656],
  },
  ATROPHIC_POISON_TALENT: {
    id: 381637,
    name: 'Atrophic Poison',
    icon: 'ability_rogue_nervesofsteel',
    maxRanks: 1,
    entryIds: [112655],
  },
  NIMBLE_FINGERS_TALENT: {
    id: 378427,
    name: 'Nimble Fingers',
    icon: 'ability_rogue_crimsonvial',
    maxRanks: 1,
    entryIds: [112635],
  },
  GOUGE_TALENT: {
    id: 1776,
    name: 'Gouge',
    icon: 'ability_gouge',
    maxRanks: 1,
    entryIds: [112631],
    energyCost: 25,
  },
  BLACKJACK_TALENT: {
    id: 379005,
    name: 'Blackjack',
    icon: 'ability_sap',
    maxRanks: 1,
    entryIds: [112584],
  },
  TRICKS_OF_THE_TRADE_TALENT: {
    id: 57934,
    name: 'Tricks of the Trade',
    icon: 'ability_rogue_tricksofthetrade',
    maxRanks: 1,
    entryIds: [112574],
  },
  SHADOWRUNNER_TALENT: {
    id: 378807,
    name: 'Shadowrunner',
    icon: 'ability_stealth',
    maxRanks: 1,
    entryIds: [112575],
  },
  IMPROVED_WOUND_POISON_TALENT: {
    id: 319066,
    name: 'Improved Wound Poison',
    icon: 'inv_misc_herb_16',
    maxRanks: 1,
    entryIds: [112522],
  },
  FLEET_FOOTED_TALENT: {
    id: 378813,
    name: 'Fleet Footed',
    icon: 'ability_rogue_quickrecovery',
    maxRanks: 1,
    entryIds: [112654],
  },
  IRON_STOMACH_TALENT: {
    id: 193546,
    name: 'Iron Stomach',
    icon: 'inv_misc_organ_11',
    maxRanks: 1,
    entryIds: [112634],
  },
  IMPROVED_SPRINT_TALENT: {
    id: 231691,
    name: 'Improved Sprint',
    icon: 'ability_rogue_sprint',
    maxRanks: 1,
    entryIds: [112636],
  },
  PREY_ON_THE_WEAK_TALENT: {
    id: 131511,
    name: 'Prey on the Weak',
    icon: 'ability_rogue_preyontheweak',
    maxRanks: 1,
    entryIds: [112647],
  },
  SHADOWSTEP_SHARED_TALENT: {
    id: 36554,
    name: 'Shadowstep',
    icon: 'ability_rogue_shadowstep',
    maxRanks: 1,
    entryIds: [112583],
  },
  SHADOWSTEP_SPEC_TALENT: {
    id: 36554,
    name: 'Shadowstep',
    icon: 'ability_rogue_shadowstep',
    maxRanks: 1,
    entryIds: [112675, 112617],
  },
  SUBTERFUGE_TALENT: {
    id: 108208,
    name: 'Subterfuge',
    icon: 'rogue_subterfuge',
    maxRanks: 1,
    entryIds: [112576],
  },
  VIRULENT_POISONS_TALENT: {
    id: 381543,
    name: 'Virulent Poisons',
    icon: 'ability_creature_poison_06',
    maxRanks: 1,
    entryIds: [112653],
  },
  DEADENED_NERVES_TALENT: {
    id: 231719,
    name: 'Deadened Nerves',
    icon: 'ability_rogue_nervesofsteel',
    maxRanks: 1,
    entryIds: [112633],
  },
  UNBREAKABLE_STRIDE_TALENT: {
    id: 400804,
    name: 'Unbreakable Stride',
    icon: 'ability_rogue_trip',
    maxRanks: 1,
    entryIds: [112638],
  },
  RUSHED_SETUP_TALENT: {
    id: 378803,
    name: 'Rushed Setup',
    icon: 'ability_skyreach_piercing_rush',
    maxRanks: 1,
    entryIds: [112646],
  },
  TIGHT_SPENDER_TALENT: {
    id: 381621,
    name: 'Tight Spender',
    icon: 'inv_misc_coin_03',
    maxRanks: 1,
    entryIds: [112582],
  },
  DEADLY_PRECISION_TALENT: {
    id: 381542,
    name: 'Deadly Precision',
    icon: 'ability_rogue_deadenednerves',
    maxRanks: 2,
    entryIds: [112652],
  },
  THIEFS_VERSATILITY_TALENT: {
    id: 381619,
    name: "Thief's Versatility",
    icon: 'ability_rogue_versatility',
    maxRanks: 2,
    entryIds: [112645],
  },
  NIGHTSTALKER_TALENT: {
    id: 14062,
    name: 'Nightstalker',
    icon: 'ability_stealth',
    maxRanks: 2,
    entryIds: [112581],
  },
  VIGOR_TALENT: {
    id: 14983,
    name: 'Vigor',
    icon: 'ability_rogue_vigor',
    maxRanks: 1,
    entryIds: [112651],
  },
  ACROBATIC_STRIKES_TALENT: {
    id: 196924,
    name: 'Acrobatic Strikes',
    icon: 'spell_warrior_wildstrike',
    maxRanks: 1,
    entryIds: [112644],
  },
  IMPROVED_AMBUSH_TALENT: {
    id: 381620,
    name: 'Improved Ambush',
    icon: 'ability_rogue_ambush',
    maxRanks: 1,
    entryIds: [112580],
  },
  LEECHING_POISON_TALENT: {
    id: 280716,
    name: 'Leeching Poison',
    icon: 'rogue_leeching_poison',
    maxRanks: 1,
    entryIds: [112650],
  },
  LETHALITY_TALENT: {
    id: 382238,
    name: 'Lethality',
    icon: 'ability_criticalstrike',
    maxRanks: 2,
    entryIds: [112640],
  },
  RECUPERATOR_TALENT: {
    id: 378996,
    name: 'Recuperator',
    icon: 'inv_gizmo_runichealthinjector',
    maxRanks: 1,
    entryIds: [112526],
  },
  ALACRITY_TALENT: {
    id: 193539,
    name: 'Alacrity',
    icon: 'ability_paladin_speedoflight',
    maxRanks: 2,
    entryIds: [112643],
  },
  SOOTHING_DARKNESS_TALENT: {
    id: 393970,
    name: 'Soothing Darkness',
    icon: 'spell_shadow_twilight',
    maxRanks: 1,
    entryIds: [112579],
  },
  SEAL_FATE_TALENT: {
    id: 14190,
    name: 'Seal Fate',
    icon: 'ability_rogue_stayofexecution',
    maxRanks: 2,
    entryIds: [112649],
  },
  COLD_BLOOD_TALENT: {
    id: 382245,
    name: 'Cold Blood',
    icon: 'spell_ice_lament',
    maxRanks: 1,
    entryIds: [112639],
  },
  ECHOING_REPRIMAND_TALENT: {
    id: 385616,
    name: 'Echoing Reprimand',
    icon: 'ability_bastion_rogue',
    maxRanks: 1,
    entryIds: [112525],
    energyCost: 10,
  },
  DEEPER_STRATAGEM_TALENT: {
    id: 193531,
    name: 'Deeper Stratagem',
    icon: 'archaeology_5_0_changkiboard',
    maxRanks: 1,
    entryIds: [112642],
  },
  MARKED_FOR_DEATH_TALENT: {
    id: 137619,
    name: 'Marked for Death',
    icon: 'achievement_bg_killingblow_berserker',
    maxRanks: 1,
    entryIds: [112641],
  },
  FIND_WEAKNESS_TALENT: {
    id: 91023,
    name: 'Find Weakness',
    icon: 'ability_rogue_findweakness',
    maxRanks: 2,
    entryIds: [112578],
  },
  THISTLE_TEA_TALENT: {
    id: 381623,
    name: 'Thistle Tea',
    icon: 'inv_drink_milk_05',
    maxRanks: 1,
    entryIds: [112648],
  },
  RESOUNDING_CLARITY_TALENT: {
    id: 381622,
    name: 'Resounding Clarity',
    icon: 'ability_bastion_rogue',
    maxRanks: 1,
    entryIds: [112524],
  },
  REVERBERATION_TALENT: {
    id: 394332,
    name: 'Reverberation',
    icon: 'spell_animabastion_buff',
    maxRanks: 1,
    entryIds: [112523],
  },
  SHADOW_DANCE_TALENT: {
    id: 185313,
    name: 'Shadow Dance',
    icon: 'ability_rogue_shadowdance',
    maxRanks: 1,
    entryIds: [112577],
  },
  DEADLY_POISON_TALENT: {
    id: 2823,
    name: 'Deadly Poison',
    icon: 'ability_rogue_dualweild',
    maxRanks: 1,
    entryIds: [112676],
  },
  IMPROVED_SHIV_TALENT: {
    id: 319032,
    name: 'Improved Shiv',
    icon: 'inv_throwingknife_04',
    maxRanks: 1,
    entryIds: [112513],
  },
  VENOMOUS_WOUNDS_TALENT: {
    id: 79134,
    name: 'Venomous Wounds',
    icon: 'ability_rogue_venomouswounds',
    maxRanks: 1,
    entryIds: [112520],
  },
  CUT_TO_THE_CHASE_TALENT: {
    id: 51667,
    name: 'Cut to the Chase',
    icon: 'ability_rogue_cuttothechase',
    maxRanks: 1,
    entryIds: [112514],
  },
  ELABORATE_PLANNING_TALENT: {
    id: 193640,
    name: 'Elaborate Planning',
    icon: 'inv_misc_map08',
    maxRanks: 2,
    entryIds: [112512],
  },
  IMPROVED_POISONS_TALENT: {
    id: 381624,
    name: 'Improved Poisons',
    icon: 'ability_poisons',
    maxRanks: 2,
    entryIds: [112519],
  },
  BLOODY_MESS_TALENT: {
    id: 381626,
    name: 'Bloody Mess',
    icon: 'ability_rogue_rupture',
    maxRanks: 2,
    entryIds: [112510],
  },
  INTERNAL_BLEEDING_TALENT: {
    id: 381627,
    name: 'Internal Bleeding',
    icon: 'ability_rogue_bloodsplatter',
    maxRanks: 1,
    entryIds: [112674],
  },
  THROWN_PRECISION_TALENT: {
    id: 381629,
    name: 'Thrown Precision',
    icon: 'ability_hunter_cobrashot',
    maxRanks: 1,
    entryIds: [112515],
  },
  LIGHTWEIGHT_SHIV_TALENT: {
    id: 394983,
    name: 'Lightweight Shiv',
    icon: 'inv_throwingknife_04',
    maxRanks: 1,
    entryIds: [112518],
  },
  FATAL_CONCOCTION_TALENT: {
    id: 392384,
    name: 'Fatal Concoction',
    icon: 'ability_creature_poison_06',
    maxRanks: 1,
    entryIds: [112511],
  },
  IMPROVED_GARROTE_TALENT: {
    id: 381632,
    name: 'Improved Garrote',
    icon: 'ability_rogue_garrote',
    maxRanks: 1,
    entryIds: [112673],
  },
  INTENT_TO_KILL_TALENT: {
    id: 381630,
    name: 'Intent to Kill',
    icon: 'ability_rogue_bloodyeye',
    maxRanks: 1,
    entryIds: [112504],
  },
  CRIMSON_TEMPEST_TALENT: {
    id: 121411,
    name: 'Crimson Tempest',
    icon: 'inv_knife_1h_cataclysm_c_05',
    maxRanks: 1,
    entryIds: [112517],
    energyCost: 30,
  },
  VENOM_RUSH_TALENT: {
    id: 152152,
    name: 'Venom Rush',
    icon: 'rogue_venomzest',
    maxRanks: 1,
    entryIds: [112666],
  },
  DEATHMARK_TALENT: {
    id: 360194,
    name: 'Deathmark',
    icon: 'ability_rogue_deathmark',
    maxRanks: 1,
    entryIds: [112662],
  },
  MASTER_ASSASSIN_TALENT: {
    id: 255989,
    name: 'Master Assassin',
    icon: 'ability_criticalstrike',
    maxRanks: 1,
    entryIds: [112508],
  },
  EXSANGUINATE_TALENT: {
    id: 200806,
    name: 'Exsanguinate',
    icon: 'ability_deathwing_bloodcorruption_earth',
    maxRanks: 1,
    entryIds: [112672],
    energyCost: 25,
  },
  FLYING_DAGGERS_TALENT: {
    id: 381631,
    name: 'Flying Daggers',
    icon: 'ability_rogue_fanofknives',
    maxRanks: 1,
    entryIds: [112516],
  },
  VICIOUS_VENOMS_TALENT: {
    id: 381634,
    name: 'Vicious Venoms',
    icon: 'ability_rogue_deadlybrew',
    maxRanks: 2,
    entryIds: [112665],
  },
  LETHAL_DOSE_TALENT: {
    id: 381640,
    name: 'Lethal Dose',
    icon: 'ability_rogue_deviouspoisons',
    maxRanks: 2,
    entryIds: [112509],
  },
  IRON_WIRE_TALENT: {
    id: 196861,
    name: 'Iron Wire',
    icon: 'inv_jewelcrafting_delicatecopperwire',
    maxRanks: 1,
    entryIds: [112671],
  },
  SYSTEMIC_FAILURE_TALENT: {
    id: 381652,
    name: 'Systemic Failure',
    icon: 'ability_skeer_bloodletting',
    maxRanks: 1,
    entryIds: [112664],
  },
  AMPLIFYING_POISON_TALENT: {
    id: 381664,
    name: 'Amplifying Poison',
    icon: 'inv_misc_herb_fellotus',
    maxRanks: 1,
    entryIds: [112505],
  },
  TWIST_THE_KNIFE_TALENT: {
    id: 381669,
    name: 'Twist the Knife',
    icon: 'ability_rogue_bladetwisting',
    maxRanks: 1,
    entryIds: [112661],
  },
  DOOMBLADE_TALENT: {
    id: 381673,
    name: 'Doomblade',
    icon: 'ability_deathwing_bloodcorruption_earth',
    maxRanks: 1,
    entryIds: [112670],
  },
  BLINDSIDE_TALENT: {
    id: 328085,
    name: 'Blindside',
    icon: 'ability_rogue_focusedattacks',
    maxRanks: 1,
    entryIds: [112679],
  },
  TINY_TOXIC_BLADE_TALENT: {
    id: 381800,
    name: 'Tiny Toxic Blade',
    icon: 'ability_rogue_poisonedknife',
    maxRanks: 1,
    entryIds: [112663],
  },
  POISON_BOMB_TALENT: {
    id: 255544,
    name: 'Poison Bomb',
    icon: 'rogue_paralytic_poison',
    maxRanks: 2,
    entryIds: [112660],
  },
  SHROUDED_SUFFOCATION_TALENT: {
    id: 385478,
    name: 'Shrouded Suffocation',
    icon: 'ability_rogue_garrote',
    maxRanks: 1,
    entryIds: [112669],
  },
  SEPSIS_TALENT: {
    id: 385408,
    name: 'Sepsis',
    icon: 'ability_ardenweald_rogue',
    maxRanks: 1,
    entryIds: [112507, 112565, 112592],
    energyCost: 25,
  },
  SERRATED_BONE_SPIKE_TALENT: {
    id: 385424,
    name: 'Serrated Bone Spike',
    icon: 'ability_maldraxxus_rogue',
    maxRanks: 1,
    entryIds: [112506],
    energyCost: 15,
  },
  ZOLDYCK_RECIPE_TALENT: {
    id: 381798,
    name: 'Zoldyck Recipe',
    icon: 'archaeology_5_0_thunderkinginsignia',
    maxRanks: 3,
    entryIds: [112678],
  },
  DASHING_SCOUNDREL_TALENT: {
    id: 381797,
    name: 'Dashing Scoundrel',
    icon: 'ability_rogue_venomouswounds',
    maxRanks: 2,
    entryIds: [112659],
  },
  SCENT_OF_BLOOD_TALENT: {
    id: 381799,
    name: 'Scent of Blood',
    icon: 'ability_rogue_rupture',
    maxRanks: 3,
    entryIds: [112668],
  },
  ARTERIAL_PRECISION_TALENT: {
    id: 400783,
    name: 'Arterial Precision',
    icon: 'ability_rogue_surpriseattack',
    maxRanks: 1,
    entryIds: [112677],
  },
  DRAGON_TEMPERED_BLADES_TALENT: {
    id: 381801,
    name: 'Dragon-Tempered Blades',
    icon: 'spell_fire_flameblades',
    maxRanks: 1,
    entryIds: [112658],
  },
  KINGSBANE_TALENT: {
    id: 385627,
    name: 'Kingsbane',
    icon: 'inv_knife_1h_artifactgarona_d_01',
    maxRanks: 1,
    entryIds: [114736],
    energyCost: 35,
  },
  INDISCRIMINATE_CARNAGE_TALENT: {
    id: 381802,
    name: 'Indiscriminate Carnage',
    icon: 'ability_rogue_indiscriminatecarnage',
    maxRanks: 1,
    entryIds: [112667],
  },
  OPPORTUNITY_TALENT: {
    id: 279876,
    name: 'Opportunity',
    icon: 'spell_shadow_ritualofsacrifice',
    maxRanks: 1,
    entryIds: [112571],
  },
  BLADE_FLURRY_TALENT: {
    id: 13877,
    name: 'Blade Flurry',
    icon: 'ability_warrior_punishingblow',
    maxRanks: 1,
    entryIds: [112561],
    energyCost: 15,
  },
  GRAPPLING_HOOK_TALENT: {
    id: 195457,
    name: 'Grappling Hook',
    icon: 'ability_rogue_grapplinghook',
    maxRanks: 1,
    entryIds: [112570],
  },
  WEAPONMASTER_OUTLAW_TALENT: {
    id: 200733,
    name: 'Weaponmaster',
    icon: 'ability_ironmaidens_bladerush',
    maxRanks: 1,
    entryIds: [112533],
  },
  WEAPONMASTER_SUBTLETY_TALENT: {
    id: 193537,
    name: 'Weaponmaster',
    icon: 'ability_ironmaidens_bladerush',
    maxRanks: 1,
    entryIds: [112628],
  },
  COMBAT_POTENCY_TALENT: {
    id: 61329,
    name: 'Combat Potency',
    icon: 'inv_weapon_shortblade_38',
    maxRanks: 1,
    entryIds: [112532],
  },
  AMBIDEXTERITY_TALENT: {
    id: 381822,
    name: 'Ambidexterity',
    icon: 'inv_glove_cloth_oribosdungeon_c_01',
    maxRanks: 1,
    entryIds: [112546],
  },
  HIT_AND_RUN_TALENT: {
    id: 196922,
    name: 'Hit and Run',
    icon: 'ability_rogue_fleetfooted',
    maxRanks: 1,
    entryIds: [112560],
  },
  RETRACTABLE_HOOK_TALENT: {
    id: 256188,
    name: 'Retractable Hook',
    icon: 'ability_rogue_grapplinghook',
    maxRanks: 1,
    entryIds: [112569],
  },
  COMBAT_STAMINA_TALENT: {
    id: 381877,
    name: 'Combat Stamina',
    icon: 'ability_rogue_imrovedrecuperate',
    maxRanks: 1,
    entryIds: [112534],
  },
  ADRENALINE_RUSH_TALENT: {
    id: 13750,
    name: 'Adrenaline Rush',
    icon: 'spell_shadow_shadowworddominate',
    maxRanks: 1,
    entryIds: [112545],
  },
  RIPOSTE_TALENT: {
    id: 344363,
    name: 'Riposte',
    icon: 'ability_warrior_challange',
    maxRanks: 1,
    entryIds: [112547],
  },
  DEFT_MANEUVERS_TALENT: {
    id: 381878,
    name: 'Deft Maneuvers',
    icon: 'spell_warrior_wildstrike',
    maxRanks: 1,
    entryIds: [112559],
  },
  BLINDING_POWDER_TALENT: {
    id: 256165,
    name: 'Blinding Powder',
    icon: 'inv_misc_ammo_gunpowder_06',
    maxRanks: 1,
    entryIds: [112529],
  },
  RUTHLESSNESS_TALENT: {
    id: 14161,
    name: 'Ruthlessness',
    icon: 'ability_druid_disembowel',
    maxRanks: 1,
    entryIds: [112568],
  },
  SWIFT_SLASHER_TALENT: {
    id: 381988,
    name: 'Swift Slasher',
    icon: 'ability_rogue_slicedice',
    maxRanks: 1,
    entryIds: [112535],
  },
  RESTLESS_BLADES_TALENT: {
    id: 79096,
    name: 'Restless Blades',
    icon: 'ability_rogue_restlessblades',
    maxRanks: 1,
    entryIds: [112544],
  },
  FATAL_FLOURISH_TALENT: {
    id: 35551,
    name: 'Fatal Flourish',
    icon: 'ability_rogue_unfairadvantage',
    maxRanks: 1,
    entryIds: [112548],
  },
  IMPROVED_BETWEEN_THE_EYES_TALENT: {
    id: 235484,
    name: 'Improved Between the Eyes',
    icon: 'inv_weapon_rifle_01',
    maxRanks: 1,
    entryIds: [112558],
  },
  DIRTY_TRICKS_TALENT: {
    id: 108216,
    name: 'Dirty Tricks',
    icon: 'ability_rogue_dirtydeeds',
    maxRanks: 1,
    entryIds: [112531],
  },
  HEAVY_HITTER_TALENT: {
    id: 381885,
    name: 'Heavy Hitter',
    icon: 'spell_shadow_ritualofsacrifice',
    maxRanks: 1,
    entryIds: [112528],
  },
  DEVIOUS_STRATAGEM_TALENT: {
    id: 394321,
    name: 'Devious Stratagem',
    icon: 'archaeology_5_0_changkiboard',
    maxRanks: 1,
    entryIds: [112567],
  },
  ROLL_THE_BONES_TALENT: {
    id: 315508,
    name: 'Roll the Bones',
    icon: 'ability_rogue_rollthebones',
    maxRanks: 1,
    entryIds: [112543],
    energyCost: 25,
  },
  QUICK_DRAW_TALENT: {
    id: 196938,
    name: 'Quick Draw',
    icon: 'inv_weapon_rifle_40',
    maxRanks: 1,
    entryIds: [112549],
  },
  ACE_UP_YOUR_SLEEVE_TALENT: {
    id: 381828,
    name: 'Ace Up Your Sleeve',
    icon: 'inv_weapon_rifle_01',
    maxRanks: 1,
    entryIds: [112557],
  },
  AUDACITY_TALENT: {
    id: 381845,
    name: 'Audacity',
    icon: 'ability_rogue_ambush',
    maxRanks: 1,
    entryIds: [112527],
  },
  LOADED_DICE_TALENT: {
    id: 256170,
    name: 'Loaded Dice',
    icon: 'ability_rogue_rollthebones',
    maxRanks: 1,
    entryIds: [112542],
  },
  FLOAT_LIKE_A_BUTTERFLY_TALENT: {
    id: 354897,
    name: 'Float Like a Butterfly',
    icon: 'inv_pet_butterfly_orange',
    maxRanks: 1,
    entryIds: [112536],
  },
  SLEIGHT_OF_HAND_TALENT: {
    id: 381839,
    name: 'Sleight of Hand',
    icon: 'inv_misc_dice_02',
    maxRanks: 1,
    entryIds: [112537],
  },
  DANCING_STEEL_TALENT: {
    id: 272026,
    name: 'Dancing Steel',
    icon: 'ability_warrior_punishingblow',
    maxRanks: 1,
    entryIds: [112556],
  },
  TRIPLE_THREAT_TALENT: {
    id: 381894,
    name: 'Triple Threat',
    icon: 'ability_dualwield',
    maxRanks: 2,
    entryIds: [112566],
  },
  COUNT_THE_ODDS_TALENT: {
    id: 381982,
    name: 'Count the Odds',
    icon: 'inv_misc_dice_01',
    maxRanks: 2,
    entryIds: [112541],
  },
  IMPROVED_MAIN_GAUCHE_TALENT: {
    id: 382746,
    name: 'Improved Main Gauche',
    icon: 'inv_weapon_shortblade_15',
    maxRanks: 2,
    entryIds: [112555],
  },
  GHOSTLY_STRIKE_TALENT: {
    id: 196937,
    name: 'Ghostly Strike',
    icon: 'ability_creature_cursed_02',
    maxRanks: 1,
    entryIds: [112564],
    energyCost: 30,
  },
  BLADE_RUSH_TALENT: {
    id: 271877,
    name: 'Blade Rush',
    icon: 'ability_arakkoa_spinning_blade',
    maxRanks: 1,
    entryIds: [112530],
  },
  IMPROVED_ADRENALINE_RUSH_TALENT: {
    id: 395422,
    name: 'Improved Adrenaline Rush',
    icon: 'spell_shadow_shadowworddominate',
    maxRanks: 1,
    entryIds: [112540],
  },
  KILLING_SPREE_TALENT: {
    id: 51690,
    name: 'Killing Spree',
    icon: 'ability_rogue_murderspree',
    maxRanks: 1,
    entryIds: [112551],
  },
  DREADBLADES_TALENT: {
    id: 343142,
    name: 'Dreadblades',
    icon: 'inv_sword_1h_artifactskywall_d_01dual',
    maxRanks: 1,
    entryIds: [112550],
    energyCost: 40,
  },
  PRECISE_CUTS_TALENT: {
    id: 381985,
    name: 'Precise Cuts',
    icon: 'ability_warrior_punishingblow',
    maxRanks: 1,
    entryIds: [112554],
  },
  TAKE_EM_BY_SURPRISE_TALENT: {
    id: 382742,
    name: "Take 'em by Surprise",
    icon: 'ability_rogue_masterofsubtlety',
    maxRanks: 2,
    entryIds: [112563],
  },
  SUMMARILY_DISPATCHED_TALENT: {
    id: 381990,
    name: 'Summarily Dispatched',
    icon: 'ability_rogue_waylay',
    maxRanks: 2,
    entryIds: [112539],
  },
  FAN_THE_HAMMER_TALENT: {
    id: 381846,
    name: 'Fan the Hammer',
    icon: 'ability_rogue_pistolshot',
    maxRanks: 2,
    entryIds: [112553],
  },
  HIDDEN_OPPORTUNITY_TALENT: {
    id: 383281,
    name: 'Hidden Opportunity',
    icon: 'ability_rogue_ambush',
    maxRanks: 1,
    entryIds: [112562],
  },
  KEEP_IT_ROLLING_TALENT: {
    id: 381989,
    name: 'Keep It Rolling',
    icon: 'ability_rogue_keepitrolling',
    maxRanks: 1,
    entryIds: [112538],
  },
  GREENSKINS_WICKERS_TALENT: {
    id: 386823,
    name: "Greenskin's Wickers",
    icon: 'ability_creature_cursed_04',
    maxRanks: 1,
    entryIds: [112552],
  },
  IMPROVED_BACKSTAB_TALENT: {
    id: 319949,
    name: 'Improved Backstab',
    icon: 'ability_backstab',
    maxRanks: 1,
    entryIds: [112629],
  },
  IMPROVED_SHURIKEN_STORM_TALENT: {
    id: 319951,
    name: 'Improved Shuriken Storm',
    icon: 'ability_rogue_shuriken_storm',
    maxRanks: 1,
    entryIds: [112598],
  },
  SHADOW_FOCUS_TALENT: {
    id: 108209,
    name: 'Shadow Focus',
    icon: 'rogue_shadowfocus',
    maxRanks: 1,
    entryIds: [112615],
  },
  QUICK_DECISIONS_TALENT: {
    id: 382503,
    name: 'Quick Decisions',
    icon: 'inv_misc_hook_01',
    maxRanks: 1,
    entryIds: [112616],
  },
  RELENTLESS_STRIKES_TALENT: {
    id: 58423,
    name: 'Relentless Strikes',
    icon: 'ability_warrior_decisivestrike',
    maxRanks: 1,
    entryIds: [112597],
  },
  BLACK_POWDER_TALENT: {
    id: 319175,
    name: 'Black Powder',
    icon: 'spell_priest_divinestar_shadow',
    maxRanks: 1,
    entryIds: [112600],
    energyCost: 35,
  },
  SHOT_IN_THE_DARK_TALENT: {
    id: 257505,
    name: 'Shot in the Dark',
    icon: 'ability_cheapshot',
    maxRanks: 1,
    entryIds: [112586],
  },
  PREMEDITATION_TALENT: {
    id: 343160,
    name: 'Premeditation',
    icon: 'spell_shadow_possession',
    maxRanks: 1,
    entryIds: [112627],
  },
  SHADOW_BLADES_TALENT: {
    id: 121471,
    name: 'Shadow Blades',
    icon: 'inv_knife_1h_grimbatolraid_d_03',
    maxRanks: 1,
    entryIds: [112614],
  },
  SILENT_STORM_TALENT: {
    id: 385722,
    name: 'Silent Storm',
    icon: 'ability_rogue_shuriken_storm',
    maxRanks: 1,
    entryIds: [112602],
  },
  NIGHT_TERRORS_TALENT: {
    id: 277953,
    name: 'Night Terrors',
    icon: 'spell_shadow_shadesofdarkness',
    maxRanks: 1,
    entryIds: [112599],
  },
  GLOOMBLADE_TALENT: {
    id: 200758,
    name: 'Gloomblade',
    icon: 'ability_ironmaidens_convulsiveshadows',
    maxRanks: 1,
    entryIds: [112587],
    energyCost: 35,
  },
  IMPROVED_SHADOW_TECHNIQUES_TALENT: {
    id: 394023,
    name: 'Improved Shadow Techniques',
    icon: 'ability_rogue_masterofsubtlety',
    maxRanks: 1,
    entryIds: [112626],
  },
  STILETTO_STACCATO_TALENT: {
    id: 382509,
    name: 'Stiletto Staccato',
    icon: 'ability_rogue_shadowyduel',
    maxRanks: 1,
    entryIds: [112613],
  },
  VEILTOUCHED_TALENT: {
    id: 382017,
    name: 'Veiltouched',
    icon: 'spell_arcane_prismaticcloak',
    maxRanks: 1,
    entryIds: [112601],
  },
  SECRET_TECHNIQUE_TALENT: {
    id: 280719,
    name: 'Secret Technique',
    icon: 'ability_rogue_sinistercalling',
    maxRanks: 1,
    entryIds: [112603],
    energyCost: 30,
  },
  SWIFT_DEATH_TALENT: {
    id: 394309,
    name: 'Swift Death',
    icon: 'spell_shadow_rune',
    maxRanks: 1,
    entryIds: [112589],
  },
  THE_FIRST_DANCE_TALENT: {
    id: 382505,
    name: 'The First Dance',
    icon: 'ability_rogue_shadowdance',
    maxRanks: 1,
    entryIds: [112625],
  },
  MASTER_OF_SHADOWS_TALENT: {
    id: 196976,
    name: 'Master of Shadows',
    icon: 'spell_shadow_charm',
    maxRanks: 1,
    entryIds: [112624],
  },
  DEEPENING_SHADOWS_TALENT: {
    id: 185314,
    name: 'Deepening Shadows',
    icon: 'spell_shadow_twilight',
    maxRanks: 1,
    entryIds: [112612],
  },
  REPLICATING_SHADOWS_TALENT: {
    id: 382506,
    name: 'Replicating Shadows',
    icon: 'spell_deathknight_strangulate',
    maxRanks: 1,
    entryIds: [112605],
  },
  SHROUDED_IN_DARKNESS_TALENT: {
    id: 382507,
    name: 'Shrouded in Darkness',
    icon: 'ability_rogue_envelopingshadows',
    maxRanks: 1,
    entryIds: [112588],
  },
  PLANNED_EXECUTION_TALENT: {
    id: 382508,
    name: 'Planned Execution',
    icon: 'ability_creature_cursed_02',
    maxRanks: 2,
    entryIds: [112591],
  },
  IMPROVED_SHADOW_DANCE_TALENT: {
    id: 393972,
    name: 'Improved Shadow Dance',
    icon: 'ability_rogue_shadowdance',
    maxRanks: 2,
    entryIds: [112623],
  },
  SHADOWED_FINISHERS_TALENT: {
    id: 382511,
    name: 'Shadowed Finishers',
    icon: 'ability_rogue_eviscerate',
    maxRanks: 2,
    entryIds: [112611],
  },
  SHURIKEN_TORNADO_TALENT: {
    id: 277925,
    name: 'Shuriken Tornado',
    icon: 'ability_rogue_throwingspecialization',
    maxRanks: 1,
    entryIds: [112604],
    energyCost: 60,
  },
  INEVITABILITY_TALENT: {
    id: 382512,
    name: 'Inevitability',
    icon: 'spell_shadow_rune',
    maxRanks: 1,
    entryIds: [112596],
  },
  WITHOUT_A_TRACE_TALENT: {
    id: 382513,
    name: 'Without a Trace',
    icon: 'ability_vanish',
    maxRanks: 1,
    entryIds: [112590],
  },
  CLOAKED_IN_SHADOWS_TALENT: {
    id: 382515,
    name: 'Cloaked in Shadows',
    icon: 'inv_helm_cloth_shadowmoonclan_b_01',
    maxRanks: 1,
    entryIds: [112622],
  },
  FADE_TO_NOTHING_TALENT: {
    id: 382514,
    name: 'Fade to Nothing',
    icon: 'ability_warlock_everlastingaffliction',
    maxRanks: 1,
    entryIds: [112621],
  },
  SECRET_STRATAGEM_TALENT: {
    id: 394320,
    name: 'Secret Stratagem',
    icon: 'archaeology_5_0_changkiboard',
    maxRanks: 1,
    entryIds: [112610],
  },
  PERFORATED_VEINS_TALENT: {
    id: 382518,
    name: 'Perforated Veins',
    icon: 'ability_warrior_bloodfrenzy',
    maxRanks: 2,
    entryIds: [112595],
  },
  DARK_SHADOW_TALENT: {
    id: 245687,
    name: 'Dark Shadow',
    icon: 'spell_warlock_demonsoul',
    maxRanks: 2,
    entryIds: [112620],
  },
  DEEPER_DAGGERS_TALENT: {
    id: 382517,
    name: 'Deeper Daggers',
    icon: 'inv_weapon_shortblade_15',
    maxRanks: 2,
    entryIds: [112609],
  },
  FLAGELLATION_TALENT: {
    id: 384631,
    name: 'Flagellation',
    icon: 'ability_revendreth_rogue',
    maxRanks: 1,
    entryIds: [112606],
  },
  INVIGORATING_SHADOWDUST_TALENT: {
    id: 382523,
    name: 'Invigorating Shadowdust',
    icon: 'ability_vanish',
    maxRanks: 2,
    entryIds: [112594],
  },
  LINGERING_SHADOW_TALENT: {
    id: 382524,
    name: 'Lingering Shadow',
    icon: 'spell_fire_twilightnova',
    maxRanks: 2,
    entryIds: [112619],
  },
  FINALITY_TALENT: {
    id: 382525,
    name: 'Finality',
    icon: 'ability_rogue_eviscerate',
    maxRanks: 2,
    entryIds: [112608],
  },
  THE_ROTTEN_TALENT: {
    id: 382015,
    name: 'The Rotten',
    icon: 'spell_shadow_nightofthedead',
    maxRanks: 1,
    entryIds: [112593],
  },
  DANSE_MACABRE_TALENT: {
    id: 382528,
    name: 'Danse Macabre',
    icon: 'ability_deathwing_bloodcorruption_death',
    maxRanks: 1,
    entryIds: [112618],
  },
  DARK_BREW_TALENT: {
    id: 382504,
    name: 'Dark Brew',
    icon: 'spell_nature_slowpoison',
    maxRanks: 1,
    entryIds: [112607],
  },
});

export default talents;
export { talents as TALENTS_ROGUE };
