// Generated file, changes will eventually be overwritten!
import { createTalentList } from './types';

const talents = createTalentList({
  //Shared
  CHAIN_HEAL_TALENT: {
    id: 1064,
    name: 'Chain Heal',
    icon: 'spell_nature_healingwavegreater',
    maxRanks: 1,
    talentId: 101951,
    __ignoreDuplication: true,
    manaCost: 15000,
  },
  LAVA_BURST_TALENT: {
    id: 51505,
    name: 'Lava Burst',
    icon: 'spell_shaman_lavaburst',
    maxRanks: 1,
    talentId: 101950,
    __ignoreDuplication: true,
    manaCost: 1250,
  },
  ASTRAL_SHIFT_TALENT: {
    id: 108271,
    name: 'Astral Shift',
    icon: 'ability_shaman_astralshift',
    maxRanks: 1,
    talentId: 101945,
    __ignoreDuplication: true,
  },
  CHAIN_LIGHTNING_TALENT: {
    id: 188443,
    name: 'Chain Lightning',
    icon: 'spell_nature_chainlightning',
    maxRanks: 1,
    talentId: 101949,
    __ignoreDuplication: true,
    manaCost: 500,
  },
  EARTH_ELEMENTAL_TALENT: {
    id: 198103,
    name: 'Earth Elemental',
    icon: 'spell_nature_earthelemental_totem',
    maxRanks: 1,
    talentId: 101952,
    __ignoreDuplication: true,
  },
  WIND_SHEAR_TALENT: {
    id: 57994,
    name: 'Wind Shear',
    icon: 'spell_nature_cyclone',
    maxRanks: 1,
    talentId: 101957,
    __ignoreDuplication: true,
  },
  PLANES_TRAVELER_TALENT: {
    id: 381647,
    name: 'Planes Traveler',
    icon: 'spell_shaman_astralshift',
    maxRanks: 1,
    talentId: 101944,
    __ignoreDuplication: true,
  },
  ASTRAL_BULWARK_TALENT: {
    id: 377933,
    name: 'Astral Bulwark',
    icon: 'spell_shaman_ancestralawakening',
    maxRanks: 1,
    talentId: 101943,
    __ignoreDuplication: true,
  },
  SPIRIT_WOLF_TALENT: {
    id: 260878,
    name: 'Spirit Wolf',
    icon: 'spell_hunter_lonewolf',
    maxRanks: 1,
    talentId: 101963,
    __ignoreDuplication: true,
  },
  THUNDEROUS_PAWS_TALENT: {
    id: 378075,
    name: 'Thunderous Paws',
    icon: 'ability_hunter_longevity',
    maxRanks: 1,
    talentId: 101962,
    __ignoreDuplication: true,
  },
  FROST_SHOCK_TALENT: {
    id: 196840,
    name: 'Frost Shock',
    icon: 'spell_frost_frostshock',
    maxRanks: 1,
    talentId: 101965,
    __ignoreDuplication: true,
    manaCost: 500,
  },
  MAELSTROM_WEAPON_TALENT: {
    id: 187880,
    name: 'Maelstrom Weapon',
    icon: 'spell_shaman_maelstromweapon',
    maxRanks: 1,
    talentId: 101948,
    __ignoreDuplication: true,
  },
  EARTH_SHIELD_TALENT: {
    id: 974,
    name: 'Earth Shield',
    icon: 'spell_nature_skinofearth',
    maxRanks: 1,
    talentId: 102004,
    __ignoreDuplication: true,
    manaCost: 5000,
  },
  FIRE_AND_ICE_TALENT: {
    id: 382886,
    name: 'Fire and Ice',
    icon: 'spell_firefrost_orb',
    maxRanks: 1,
    talentId: 101956,
    __ignoreDuplication: true,
  },
  CAPACITOR_TOTEM_TALENT: {
    id: 192058,
    name: 'Capacitor Totem',
    icon: 'spell_nature_brilliance',
    maxRanks: 1,
    talentId: 101961,
    __ignoreDuplication: true,
    manaCost: 5000,
  },
  CLEANSE_SPIRIT_TALENT: {
    id: 51886,
    name: 'Cleanse Spirit',
    icon: 'ability_shaman_cleansespirit',
    maxRanks: 1,
    talentId: 101966,
    __ignoreDuplication: true,
    manaCost: 3250,
  },
  FOCUSED_INSIGHT_TALENT: {
    id: 381666,
    name: 'Focused Insight',
    icon: 'spell_shaman_measuredinsight',
    maxRanks: 2,
    talentId: 101946,
    __ignoreDuplication: true,
  },
  ELEMENTAL_ORBIT_TALENT: {
    id: 383010,
    name: 'Elemental Orbit',
    icon: 'ability_mage_shattershield',
    maxRanks: 1,
    talentId: 102003,
    __ignoreDuplication: true,
  },
  SPIRITWALKERS_GRACE_TALENT: {
    id: 79206,
    name: "Spiritwalker's Grace",
    icon: 'spell_shaman_spiritwalkersgrace',
    maxRanks: 1,
    talentId: 101955,
    __ignoreDuplication: true,
    manaCost: 7050,
  },
  ANCESTRAL_DEFENSE_TALENT: {
    id: 382947,
    name: 'Ancestral Defense',
    icon: 'ability_earthen_pillar',
    maxRanks: 1,
    talentId: 101977,
    __ignoreDuplication: true,
  },
  TREMOR_TOTEM_TALENT: {
    id: 8143,
    name: 'Tremor Totem',
    icon: 'spell_nature_tremortotem',
    maxRanks: 1,
    talentId: 101958,
    __ignoreDuplication: true,
    manaCost: 1150,
  },
  STATIC_CHARGE_TALENT: {
    id: 265046,
    name: 'Static Charge',
    icon: 'spell_nature_brilliance',
    maxRanks: 1,
    talentId: 101960,
    __ignoreDuplication: true,
  },
  GUARDIANS_CUDGEL_TALENT: {
    id: 381819,
    name: "Guardian's Cudgel",
    icon: 'inv_mace_2h_draenorcrafted_d_01_b_alliance',
    maxRanks: 1,
    talentId: 101959,
    __ignoreDuplication: true,
  },
  PURGE_TALENT: {
    id: 370,
    name: 'Purge',
    icon: 'spell_nature_purge',
    maxRanks: 1,
    talentId: 101968,
    __ignoreDuplication: true,
    manaCost: 5000,
  },
  GREATER_PURGE_TALENT: {
    id: 378773,
    name: 'Greater Purge',
    icon: 'spell_shaman_focusedstrikes',
    maxRanks: 1,
    talentId: 101967,
    __ignoreDuplication: true,
    manaCost: 10000,
  },
  FLURRY_TALENT: {
    id: 382888,
    name: 'Flurry',
    icon: 'ability_ghoulfrenzy',
    maxRanks: 1,
    talentId: 101947,
    __ignoreDuplication: true,
  },
  GRACEFUL_SPIRIT_TALENT: {
    id: 192088,
    name: 'Graceful Spirit',
    icon: 'spell_shaman_spectraltransformation',
    maxRanks: 1,
    talentId: 101954,
    __ignoreDuplication: true,
  },
  SPIRITWALKERS_AEGIS_TALENT: {
    id: 378077,
    name: "Spiritwalker's Aegis",
    icon: 'ability_racial_forceshield',
    maxRanks: 1,
    talentId: 101953,
    __ignoreDuplication: true,
  },
  WIND_RUSH_TOTEM_TALENT: {
    id: 192077,
    name: 'Wind Rush Totem',
    icon: 'ability_shaman_windwalktotem',
    maxRanks: 1,
    talentId: 101976,
    __ignoreDuplication: true,
  },
  EARTHGRAB_TOTEM_TALENT: {
    id: 51485,
    name: 'Earthgrab Totem',
    icon: 'spell_nature_stranglevines',
    maxRanks: 1,
    talentId: 101975,
    __ignoreDuplication: true,
    manaCost: 1250,
  },
  HEX_TALENT: {
    id: 51514,
    name: 'Hex',
    icon: 'spell_shaman_hex',
    maxRanks: 1,
    talentId: 101972,
    __ignoreDuplication: true,
  },
  NATURES_FURY_TALENT: {
    id: 381655,
    name: "Nature's Fury",
    icon: 'spell_nature_spiritarmor',
    maxRanks: 2,
    talentId: 101980,
    __ignoreDuplication: true,
  },
  TOTEMIC_SURGE_TALENT: {
    id: 381867,
    name: 'Totemic Surge',
    icon: 'spell_nature_agitatingtotem',
    maxRanks: 2,
    talentId: 102002,
    __ignoreDuplication: true,
  },
  ELEMENTAL_WARDING_TALENT: {
    id: 381650,
    name: 'Elemental Warding',
    icon: 'inv_10_elementalcombinedfoozles_primordial',
    maxRanks: 2,
    talentId: 101978,
    __ignoreDuplication: true,
  },
  NATURES_GUARDIAN_TALENT: {
    id: 30884,
    name: "Nature's Guardian",
    icon: 'spell_nature_natureguardian',
    maxRanks: 2,
    talentId: 101974,
    __ignoreDuplication: true,
  },
  VOODOO_MASTERY_TALENT: {
    id: 204268,
    name: 'Voodoo Mastery',
    icon: 'spell_shaman_hex',
    maxRanks: 1,
    talentId: 101971,
    __ignoreDuplication: true,
  },
  ENFEEBLEMENT_TALENT: {
    id: 378079,
    name: 'Enfeeblement',
    icon: 'inv_frog2_teal',
    maxRanks: 1,
    talentId: 101970,
    __ignoreDuplication: true,
  },
  WINDS_OF_ALAKIR_TALENT: {
    id: 382215,
    name: "Winds of Al'Akir",
    icon: 'ability_druid_galewinds',
    maxRanks: 2,
    talentId: 101981,
    __ignoreDuplication: true,
  },
  BRIMMING_WITH_LIFE_TALENT: {
    id: 381689,
    name: 'Brimming with Life',
    icon: 'inv_jewelry_talisman_06',
    maxRanks: 1,
    talentId: 101979,
    __ignoreDuplication: true,
  },
  HEALING_STREAM_TOTEM_TALENT: {
    id: 5394,
    name: 'Healing Stream Totem',
    icon: 'inv_spear_04',
    maxRanks: 1,
    talentId: 101900,
    __ignoreDuplication: true,
    manaCost: 4500,
  },
  IMPROVED_LIGHTNING_BOLT_TALENT: {
    id: 381674,
    name: 'Improved Lightning Bolt',
    icon: 'spell_nature_lightning',
    maxRanks: 2,
    talentId: 101996,
    __ignoreDuplication: true,
  },
  TOTEMIC_PROJECTION_TALENT: {
    id: 108287,
    name: 'Totemic Projection',
    icon: 'ability_shaman_totemrelocation',
    maxRanks: 1,
    talentId: 101973,
    __ignoreDuplication: true,
  },
  SPIRIT_WALK_TALENT: {
    id: 58875,
    name: 'Spirit Walk',
    icon: 'ability_tracking',
    maxRanks: 1,
    talentId: 101983,
    __ignoreDuplication: true,
  },
  GUST_OF_WIND_TALENT: {
    id: 192063,
    name: 'Gust of Wind',
    icon: 'ability_skyreach_four_wind',
    maxRanks: 1,
    talentId: 101982,
    __ignoreDuplication: true,
  },
  SWIRLING_CURRENTS_TALENT: {
    id: 378094,
    name: 'Swirling Currents',
    icon: 'spell_holy_serendipity',
    maxRanks: 2,
    talentId: 101999,
    __ignoreDuplication: true,
  },
  NATURES_SWIFTNESS_TALENT: {
    id: 378081,
    name: "Nature's Swiftness",
    icon: 'spell_nature_ravenform',
    maxRanks: 1,
    talentId: 101997,
    __ignoreDuplication: true,
  },
  THUNDERSTORM_TALENT: {
    id: 51490,
    name: 'Thunderstorm',
    icon: 'spell_shaman_thunderstorm',
    maxRanks: 1,
    talentId: 101995,
    __ignoreDuplication: true,
  },
  TOTEMIC_FOCUS_TALENT: {
    id: 382201,
    name: 'Totemic Focus',
    icon: 'inv_relics_totemofrebirth',
    maxRanks: 2,
    talentId: 101990,
    __ignoreDuplication: true,
  },
  SURGING_SHIELDS_TALENT: {
    id: 382033,
    name: 'Surging Shields',
    icon: 'spell_nature_lightningshield',
    maxRanks: 2,
    talentId: 101988,
    __ignoreDuplication: true,
  },
  GO_WITH_THE_FLOW_TALENT: {
    id: 381678,
    name: 'Go with the Flow',
    icon: 'ability_racial_runningwild',
    maxRanks: 2,
    talentId: 101984,
    __ignoreDuplication: true,
  },
  MANA_SPRING_TOTEM_TALENT: {
    id: 381930,
    name: 'Mana Spring Totem',
    icon: 'spell_nature_manaregentotem',
    maxRanks: 1,
    talentId: 102001,
    __ignoreDuplication: true,
    manaCost: 750,
  },
  THUNDERSHOCK_TALENT: {
    id: 378779,
    name: 'Thundershock',
    icon: 'ability_thunderking_thunderstruck',
    maxRanks: 1,
    talentId: 101994,
    __ignoreDuplication: true,
  },
  LIGHTNING_LASSO_TALENT: {
    id: 305483,
    name: 'Lightning Lasso',
    icon: 'shaman_pvp_lightninglasso',
    maxRanks: 1,
    talentId: 101993,
    __ignoreDuplication: true,
  },
  POISON_CLEANSING_TOTEM_TALENT: {
    id: 383013,
    name: 'Poison Cleansing Totem',
    icon: 'spell_nature_poisoncleansingtotem',
    maxRanks: 1,
    talentId: 101989,
    __ignoreDuplication: true,
    manaCost: 1250,
  },
  TOTEMIC_RECALL_TALENT: {
    id: 108285,
    name: 'Totemic Recall',
    icon: 'ability_shaman_multitotemactivation',
    maxRanks: 1,
    talentId: 101987,
    __ignoreDuplication: true,
  },
  ANCESTRAL_GUIDANCE_TALENT: {
    id: 108281,
    name: 'Ancestral Guidance',
    icon: 'ability_shaman_ancestralguidance',
    maxRanks: 1,
    talentId: 102000,
    __ignoreDuplication: true,
  },
  STONESKIN_TOTEM_TALENT: {
    id: 383017,
    name: 'Stoneskin Totem',
    icon: 'ability_shaman_stoneskintotem',
    maxRanks: 1,
    talentId: 101992,
    __ignoreDuplication: true,
    manaCost: 750,
  },
  TRANQUIL_AIR_TOTEM_TALENT: {
    id: 383019,
    name: 'Tranquil Air Totem',
    icon: 'ability_shaman_tranquilmindtotem',
    maxRanks: 1,
    talentId: 101991,
    __ignoreDuplication: true,
    manaCost: 750,
  },
  CALL_OF_THE_ELEMENTS_TALENT: {
    id: 383011,
    name: 'Call of the Elements',
    icon: 'ability_shaman_multitotemactivation',
    maxRanks: 1,
    talentId: 101986,
    __ignoreDuplication: true,
  },
  CREATION_CORE_TALENT: {
    id: 383012,
    name: 'Creation Core',
    icon: 'inv_artifact_xp03',
    maxRanks: 1,
    talentId: 101985,
    __ignoreDuplication: true,
  },
  IMPROVED_PURIFY_SPIRIT_TALENT: {
    id: 383016,
    name: 'Improved Purify Spirit',
    icon: 'ability_shaman_cleansespirit',
    maxRanks: 1,
    talentId: 101964,
    __ignoreDuplication: true,
  },
  ANCESTRAL_WOLF_AFFINITY_TALENT: {
    id: 382197,
    name: 'Ancestral Wolf Affinity',
    icon: 'spell_beastmaster_wolf',
    maxRanks: 1,
    talentId: 101851,
    __ignoreDuplication: true,
  },
  ELEMENTAL_BLAST_TALENT: {
    id: 117014,
    name: 'Elemental Blast',
    icon: 'shaman_talent_elementalblast',
    maxRanks: 1,
    talentId: 101866,
    __ignoreDuplication: true,
    manaCost: 1375,
  },
  PRIMORDIAL_WAVE_TALENT: {
    id: 375982,
    name: 'Primordial Wave',
    icon: 'ability_maldraxxus_shaman',
    maxRanks: 1,
    talentId: 101891,
    __ignoreDuplication: true,
    manaCost: 1500,
  },
  DEEPLY_ROOTED_ELEMENTS_TALENT: {
    id: 378270,
    name: 'Deeply Rooted Elements',
    icon: 'inv_misc_herb_liferoot_stem',
    maxRanks: 1,
    talentId: 101878,
    __ignoreDuplication: true,
  },
  SPLINTERED_ELEMENTS_TALENT: {
    id: 382042,
    name: 'Splintered Elements',
    icon: 'spell_nature_elementalprecision_1',
    maxRanks: 1,
    talentId: 101844,
    __ignoreDuplication: true,
  },
  CALL_OF_THUNDER_TALENT: {
    id: 378241,
    name: 'Call of Thunder',
    icon: 'ability_thunderking_balllightning',
    maxRanks: 1,
    talentId: 101858,
    __ignoreDuplication: true,
  },
  REFRESHING_WATERS_SHARED_TALENT: {
    id: 378211,
    name: 'Refreshing Waters',
    icon: 'ability_shaman_fortifyingwaters',
    maxRanks: 1,
    talentId: 101848,
    __ignoreDuplication: true,
  },
  MASTER_OF_THE_ELEMENTS_TALENT: {
    id: 16166,
    name: 'Master of the Elements',
    icon: 'spell_nature_elementalabsorption',
    maxRanks: 2,
    talentId: 101879,
    __ignoreDuplication: true,
  },
  LAVA_SURGE_TALENT: {
    id: 77756,
    name: 'Lava Surge',
    icon: 'spell_shaman_lavasurge',
    maxRanks: 1,
    talentId: 101846,
    __ignoreDuplication: true,
  },
  ECHO_OF_THE_ELEMENTS_TALENT: {
    id: 333919,
    name: 'Echo of the Elements',
    icon: 'ability_shaman_echooftheelements',
    maxRanks: 1,
    talentId: 101872,
    __ignoreDuplication: true,
  },

  //Enhancement
  STORMSTRIKE_TALENT: {
    id: 17364,
    name: 'Stormstrike',
    icon: 'ability_shaman_stormstrike',
    maxRanks: 1,
    talentId: 101804,
    __ignoreDuplication: true,
    manaCost: 1000,
  },
  WINDFURY_WEAPON_TALENT: {
    id: 33757,
    name: 'Windfury Weapon',
    icon: 'spell_shaman_unleashweapon_wind',
    maxRanks: 1,
    talentId: 101823,
    __ignoreDuplication: true,
  },
  LAVA_LASH_TALENT: {
    id: 60103,
    name: 'Lava Lash',
    icon: 'ability_shaman_lavalash',
    maxRanks: 1,
    talentId: 101805,
    __ignoreDuplication: true,
    manaCost: 0,
  },
  FORCEFUL_WINDS_TALENT: {
    id: 262647,
    name: 'Forceful Winds',
    icon: 'spell_shaman_unleashweapon_wind',
    maxRanks: 1,
    talentId: 101834,
    __ignoreDuplication: true,
  },
  IMPROVED_MAELSTROM_WEAPON_TALENT: {
    id: 383303,
    name: 'Improved Maelstrom Weapon',
    icon: 'spell_shaman_maelstromweapon',
    maxRanks: 2,
    talentId: 101822,
    __ignoreDuplication: true,
  },
  MOLTEN_ASSAULT_TALENT: {
    id: 334033,
    name: 'Molten Assault',
    icon: 'spell_shaman_improvelavalash',
    maxRanks: 2,
    talentId: 101806,
    __ignoreDuplication: true,
  },
  UNRULY_WINDS_TALENT: {
    id: 390288,
    name: 'Unruly Winds',
    icon: 'ability_skyreach_wind_wall',
    maxRanks: 1,
    talentId: 101833,
    __ignoreDuplication: true,
  },
  FERAL_LUNGE_TALENT: {
    id: 196884,
    name: 'Feral Lunge',
    icon: 'spell_beastmaster_wolf',
    maxRanks: 1,
    talentId: 101810,
    __ignoreDuplication: true,
  },
  RAGING_MAELSTROM_TALENT: {
    id: 384143,
    name: 'Raging Maelstrom',
    icon: 'spell_shaman_stormearthfire',
    maxRanks: 1,
    talentId: 101802,
    __ignoreDuplication: true,
  },
  ICE_STRIKE_TALENT: {
    id: 342240,
    name: 'Ice Strike',
    icon: 'spell_frost_frostbolt',
    maxRanks: 1,
    talentId: 101821,
    __ignoreDuplication: true,
    manaCost: 1650,
  },
  HAILSTORM_TALENT: {
    id: 334195,
    name: 'Hailstorm',
    icon: 'spell_frost_icestorm',
    maxRanks: 1,
    talentId: 101808,
    __ignoreDuplication: true,
  },
  FIRE_NOVA_TALENT: {
    id: 333974,
    name: 'Fire Nova',
    icon: 'spell_shaman_improvedfirenova',
    maxRanks: 1,
    talentId: 101807,
    __ignoreDuplication: true,
    manaCost: 500,
  },
  DOOM_WINDS_TALENT: {
    id: 384352,
    name: 'Doom Winds',
    icon: 'ability_ironmaidens_swirlingvortex',
    maxRanks: 1,
    talentId: 101824,
    __ignoreDuplication: true,
  },
  SUNDERING_TALENT: {
    id: 197214,
    name: 'Sundering',
    icon: 'ability_rhyolith_lavapool',
    maxRanks: 1,
    talentId: 101841,
    __ignoreDuplication: true,
    manaCost: 3000,
  },
  OVERFLOWING_MAELSTROM_TALENT: {
    id: 384149,
    name: 'Overflowing Maelstrom',
    icon: 'spell_shaman_maelstromweapon',
    maxRanks: 1,
    talentId: 101801,
    __ignoreDuplication: true,
  },
  WINDFURY_TOTEM_TALENT: {
    id: 8512,
    name: 'Windfury Totem',
    icon: 'spell_nature_windfury',
    maxRanks: 1,
    talentId: 101803,
    __ignoreDuplication: true,
    manaCost: 750,
  },
  SWIRLING_MAELSTROM_TALENT: {
    id: 384359,
    name: 'Swirling Maelstrom',
    icon: 'spell_shadow_soulleech_2',
    maxRanks: 1,
    talentId: 101820,
    __ignoreDuplication: true,
  },
  HOT_HAND_TALENT: {
    id: 201900,
    name: 'Hot Hand',
    icon: 'spell_fire_playingwithfire',
    maxRanks: 2,
    talentId: 101809,
    __ignoreDuplication: true,
  },
  STORMS_WRATH_TALENT: {
    id: 392352,
    name: "Storm's Wrath",
    icon: 'spell_nature_stormreach',
    maxRanks: 1,
    talentId: 101832,
    __ignoreDuplication: true,
  },
  REFRESHING_WATERS_ENHANCEMENT_TALENT: {
    id: 393905,
    name: 'Refreshing Waters',
    icon: 'ability_shaman_fortifyingwaters',
    maxRanks: 1,
    talentId: 101800,
    __ignoreDuplication: true,
  },
  CRASH_LIGHTNING_TALENT: {
    id: 187874,
    name: 'Crash Lightning',
    icon: 'spell_shaman_crashlightning',
    maxRanks: 1,
    talentId: 101840,
    __ignoreDuplication: true,
    manaCost: 500,
  },
  STORMFLURRY_TALENT: {
    id: 344357,
    name: 'Stormflurry',
    icon: 'ability_shaman_stormstrike',
    maxRanks: 1,
    talentId: 101819,
    __ignoreDuplication: true,
  },
  ASHEN_CATALYST_TALENT: {
    id: 390370,
    name: 'Ashen Catalyst',
    icon: 'spell_shaman_stormearthfire',
    maxRanks: 1,
    talentId: 101811,
    __ignoreDuplication: true,
  },
  STORMBLAST_TALENT: {
    id: 319930,
    name: 'Stormblast',
    icon: 'spell_nature_stormreach',
    maxRanks: 1,
    talentId: 101825,
    __ignoreDuplication: true,
  },
  ELEMENTAL_WEAPONS_TALENT: {
    id: 384355,
    name: 'Elemental Weapons',
    icon: 'inv_mace_2h_draenorraid_d_03',
    maxRanks: 2,
    talentId: 101826,
    __ignoreDuplication: true,
  },
  CONVERGING_STORMS_TALENT: {
    id: 384363,
    name: 'Converging Storms',
    icon: 'warrior_talent_icon_stormbolt',
    maxRanks: 1,
    talentId: 101839,
    __ignoreDuplication: true,
  },
  CRASHING_STORMS_TALENT: {
    id: 334308,
    name: 'Crashing Storms',
    icon: 'spell_nature_chainlightning',
    maxRanks: 1,
    talentId: 101818,
    __ignoreDuplication: true,
  },
  LASHING_FLAMES_TALENT: {
    id: 334046,
    name: 'Lashing Flames',
    icon: 'spell_shaman_improvelavalash',
    maxRanks: 1,
    talentId: 101812,
    __ignoreDuplication: true,
  },
  FERAL_SPIRIT_TALENT: {
    id: 51533,
    name: 'Feral Spirit',
    icon: 'spell_shaman_feralspirit',
    maxRanks: 1,
    talentId: 101838,
    __ignoreDuplication: true,
  },
  ASCENDANCE_ENHANCEMENT_TALENT: {
    id: 114051,
    name: 'Ascendance',
    icon: 'spell_fire_elementaldevastation',
    maxRanks: 1,
    talentId: 114291,
    __ignoreDuplication: true,
  },
  PRIMAL_MAELSTROM_TALENT: {
    id: 384405,
    name: 'Primal Maelstrom',
    icon: 'shaman_talent_unleashedfury',
    maxRanks: 2,
    talentId: 101829,
    __ignoreDuplication: true,
  },
  ELEMENTAL_ASSAULT_TALENT: {
    id: 210853,
    name: 'Elemental Assault',
    icon: 'spell_shaman_improvedstormstrike',
    maxRanks: 2,
    talentId: 101827,
    __ignoreDuplication: true,
  },
  WITCH_DOCTORS_ANCESTRY_TALENT: {
    id: 384447,
    name: "Witch Doctor's Ancestry",
    icon: 'inv_misc_bone_09',
    maxRanks: 2,
    talentId: 101837,
    __ignoreDuplication: true,
  },
  LEGACY_OF_THE_FROST_WITCH_TALENT: {
    id: 384450,
    name: 'Legacy of the Frost Witch',
    icon: 'ability_thunderking_thunderstruck',
    maxRanks: 2,
    talentId: 101815,
    __ignoreDuplication: true,
  },
  STATIC_ACCUMULATION_TALENT: {
    id: 384411,
    name: 'Static Accumulation',
    icon: 'spell_nature_callstorm',
    maxRanks: 2,
    talentId: 101814,
    __ignoreDuplication: true,
  },
  ELEMENTAL_SPIRITS_TALENT: {
    id: 262624,
    name: 'Elemental Spirits',
    icon: 'spell_shaman_feralspirit',
    maxRanks: 1,
    talentId: 101836,
    __ignoreDuplication: true,
  },
  ALPHA_WOLF_TALENT: {
    id: 198434,
    name: 'Alpha Wolf',
    icon: 'spell_beastmaster_wolf',
    maxRanks: 1,
    talentId: 101835,
    __ignoreDuplication: true,
  },
  THORIMS_INVOCATION_TALENT: {
    id: 384444,
    name: "Thorim's Invocation",
    icon: 'spell_shaman_ancestralawakening',
    maxRanks: 1,
    talentId: 101813,
    __ignoreDuplication: true,
  },

  //Restoration
  RIPTIDE_TALENT: {
    id: 61295,
    name: 'Riptide',
    icon: 'spell_nature_riptide',
    maxRanks: 1,
    talentId: 101905,
    __ignoreDuplication: true,
    manaCost: 4000,
  },
  DELUGE_TALENT: {
    id: 200076,
    name: 'Deluge',
    icon: 'ability_shawaterelemental_reform',
    maxRanks: 2,
    talentId: 101906,
    __ignoreDuplication: true,
  },
  HEALING_WAVE_TALENT: {
    id: 77472,
    name: 'Healing Wave',
    icon: 'spell_nature_healingwavelesser',
    maxRanks: 1,
    talentId: 101904,
    __ignoreDuplication: true,
    manaCost: 7500,
  },
  HEALING_RAIN_TALENT: {
    id: 73920,
    name: 'Healing Rain',
    icon: 'spell_nature_giftofthewaterspirit',
    maxRanks: 1,
    talentId: 101923,
    __ignoreDuplication: true,
    manaCost: 10800,
  },
  STORMKEEPER_RESTORATION_TALENT: {
    id: 383009,
    name: 'Stormkeeper',
    icon: 'ability_thunderking_lightningwhip',
    maxRanks: 1,
    talentId: 101907,
    __ignoreDuplication: true,
  },
  WATER_SHIELD_TALENT: {
    id: 52127,
    name: 'Water Shield',
    icon: 'ability_shaman_watershield',
    maxRanks: 1,
    talentId: 101903,
    __ignoreDuplication: true,
  },
  TIDAL_WAVES_TALENT: {
    id: 51564,
    name: 'Tidal Waves',
    icon: 'spell_shaman_tidalwaves',
    maxRanks: 1,
    talentId: 101899,
    __ignoreDuplication: true,
  },
  OVERFLOWING_SHORES_TALENT: {
    id: 383222,
    name: 'Overflowing Shores',
    icon: 'spell_nature_giftofthewaterspirit',
    maxRanks: 1,
    talentId: 101922,
    __ignoreDuplication: true,
  },
  ACID_RAIN_TALENT: {
    id: 378443,
    name: 'Acid Rain',
    icon: 'spell_nature_acid_01',
    maxRanks: 1,
    talentId: 101921,
    __ignoreDuplication: true,
  },
  ANCESTRAL_VIGOR_TALENT: {
    id: 207401,
    name: 'Ancestral Vigor',
    icon: 'spell_shaman_blessingoftheeternals',
    maxRanks: 2,
    talentId: 101909,
    __ignoreDuplication: true,
  },
  RESURGENCE_TALENT: {
    id: 16196,
    name: 'Resurgence',
    icon: 'ability_shaman_watershield',
    maxRanks: 1,
    talentId: 101902,
    __ignoreDuplication: true,
  },
  FLASH_FLOOD_TALENT: {
    id: 280614,
    name: 'Flash Flood',
    icon: 'spell_frost_summonwaterelemental',
    maxRanks: 2,
    talentId: 101898,
    __ignoreDuplication: true,
  },
  WATER_TOTEM_MASTERY_TALENT: {
    id: 382030,
    name: 'Water Totem Mastery',
    icon: 'ability_shaman_totemcooldownrefund',
    maxRanks: 1,
    talentId: 101895,
    __ignoreDuplication: true,
  },
  ANCESTRAL_REACH_TALENT: {
    id: 382732,
    name: 'Ancestral Reach',
    icon: 'spell_nature_healingwavegreater',
    maxRanks: 1,
    talentId: 101911,
    __ignoreDuplication: true,
  },
  FLOW_OF_THE_TIDES_TALENT: {
    id: 382039,
    name: 'Flow of the Tides',
    icon: 'spell_frost_manarecharge',
    maxRanks: 1,
    talentId: 101910,
    __ignoreDuplication: true,
  },
  SPIRIT_LINK_TOTEM_TALENT: {
    id: 98008,
    name: 'Spirit Link Totem',
    icon: 'spell_shaman_spiritlink',
    maxRanks: 1,
    talentId: 101913,
    __ignoreDuplication: true,
    manaCost: 5500,
  },
  LIVING_STREAM_TALENT: {
    id: 382482,
    name: 'Living Stream',
    icon: 'spell_nature_natureresistancetotem',
    maxRanks: 1,
    talentId: 101934,
    __ignoreDuplication: true,
  },
  CLOUDBURST_TOTEM_TALENT: {
    id: 157153,
    name: 'Cloudburst Totem',
    icon: 'ability_shaman_condensationtotem',
    maxRanks: 1,
    talentId: 101933,
    __ignoreDuplication: true,
    manaCost: 4300,
  },
  WAVESPEAKERS_BLESSING_TALENT: {
    id: 381946,
    name: "Wavespeaker's Blessing",
    icon: 'inv_alchemist_81_spiritedalchemiststone',
    maxRanks: 1,
    talentId: 101920,
    __ignoreDuplication: true,
  },
  HEALING_TIDE_TOTEM_TALENT: {
    id: 108280,
    name: 'Healing Tide Totem',
    icon: 'ability_shaman_healingtide',
    maxRanks: 1,
    talentId: 101912,
    __ignoreDuplication: true,
    manaCost: 2800,
  },
  MANA_TIDE_TOTEM_TALENT: {
    id: 16191,
    name: 'Mana Tide Totem',
    icon: 'ability_shaman_manatidetotem',
    maxRanks: 1,
    talentId: 101929,
    __ignoreDuplication: true,
  },
  TORRENT_TALENT: {
    id: 200072,
    name: 'Torrent',
    icon: 'spell_nature_riptide',
    maxRanks: 2,
    talentId: 101932,
    __ignoreDuplication: true,
  },
  UNDULATION_TALENT: {
    id: 200071,
    name: 'Undulation',
    icon: 'spell_nature_healingway',
    maxRanks: 1,
    talentId: 101919,
    __ignoreDuplication: true,
  },
  UNLEASH_LIFE_TALENT: {
    id: 73685,
    name: 'Unleash Life',
    icon: 'spell_shaman_unleashweapon_life',
    maxRanks: 1,
    talentId: 101918,
    __ignoreDuplication: true,
    manaCost: 2000,
  },
  EARTHEN_WALL_TOTEM_TALENT: {
    id: 198838,
    name: 'Earthen Wall Totem',
    icon: 'spell_nature_stoneskintotem',
    maxRanks: 1,
    talentId: 101931,
    __ignoreDuplication: true,
    manaCost: 5500,
  },
  ANCESTRAL_PROTECTION_TOTEM_TALENT: {
    id: 207399,
    name: 'Ancestral Protection Totem',
    icon: 'spell_nature_reincarnation',
    maxRanks: 1,
    talentId: 101930,
    __ignoreDuplication: true,
    manaCost: 5500,
  },
  EARTHLIVING_WEAPON_TALENT: {
    id: 382021,
    name: 'Earthliving Weapon',
    icon: 'spell_shaman_giftearthmother',
    maxRanks: 1,
    talentId: 101935,
    __ignoreDuplication: true,
  },
  ANCESTRAL_AWAKENING_TALENT: {
    id: 382309,
    name: 'Ancestral Awakening',
    icon: 'spell_shaman_ancestralawakening',
    maxRanks: 2,
    talentId: 101927,
    __ignoreDuplication: true,
  },
  EARTHEN_HARMONY_TALENT: {
    id: 382020,
    name: 'Earthen Harmony',
    icon: 'spell_shaman_improvedearthshield',
    maxRanks: 2,
    talentId: 101941,
    __ignoreDuplication: true,
  },
  UNDERCURRENT_TALENT: {
    id: 382194,
    name: 'Undercurrent',
    icon: 'spell_fire_bluehellfire',
    maxRanks: 2,
    talentId: 101939,
    __ignoreDuplication: true,
  },
  IMPROVED_PRIMORDIAL_WAVE_TALENT: {
    id: 382191,
    name: 'Improved Primordial Wave',
    icon: 'ability_maldraxxus_shaman',
    maxRanks: 2,
    talentId: 101916,
    __ignoreDuplication: true,
  },
  DOWNPOUR_TALENT: {
    id: 207778,
    name: 'Downpour',
    icon: 'ability_mage_waterjet',
    maxRanks: 1,
    talentId: 101842,
    __ignoreDuplication: true,
    manaCost: 7500,
  },
  NATURES_FOCUS_TALENT: {
    id: 382019,
    name: "Nature's Focus",
    icon: 'spell_shaman_blessingofeternals',
    maxRanks: 1,
    talentId: 101924,
    __ignoreDuplication: true,
  },
  EVER_RISING_TIDE_TALENT: {
    id: 382029,
    name: 'Ever-Rising Tide',
    icon: 'inv_elemental_primal_water',
    maxRanks: 1,
    talentId: 101940,
    __ignoreDuplication: true,
  },
  IMPROVED_EARTHLIVING_WEAPON_TALENT: {
    id: 382315,
    name: 'Improved Earthliving Weapon',
    icon: 'spell_shaman_giftearthmother',
    maxRanks: 2,
    talentId: 101936,
    __ignoreDuplication: true,
  },
  CONTINUOUS_WAVES_TALENT: {
    id: 382046,
    name: 'Continuous Waves',
    icon: 'spell_animabastion_wave',
    maxRanks: 1,
    talentId: 101915,
    __ignoreDuplication: true,
  },
  TUMBLING_WAVES_TALENT: {
    id: 382040,
    name: 'Tumbling Waves',
    icon: 'spell_animamaldraxxus_wave',
    maxRanks: 1,
    talentId: 101914,
    __ignoreDuplication: true,
  },
  PRIMAL_TIDE_CORE_TALENT: {
    id: 382045,
    name: 'Primal Tide Core',
    icon: 'ability_shaman_repulsiontotem',
    maxRanks: 1,
    talentId: 101926,
    __ignoreDuplication: true,
  },
  HIGH_TIDE_TALENT: {
    id: 157154,
    name: 'High Tide',
    icon: 'spell_shaman_hightide',
    maxRanks: 1,
    talentId: 101925,
    __ignoreDuplication: true,
    manaCost: 500,
  },
  ASCENDANCE_RESTORATION_TALENT: {
    id: 114052,
    name: 'Ascendance',
    icon: 'spell_fire_elementaldevastation',
    maxRanks: 1,
    talentId: 101942,
    __ignoreDuplication: true,
  },
  WELLSPRING_TALENT: {
    id: 197995,
    name: 'Wellspring',
    icon: 'ability_shawaterelemental_split',
    maxRanks: 1,
    talentId: 101937,
    __ignoreDuplication: true,
    manaCost: 10000,
  },

  //Elemental
  EARTH_SHOCK_TALENT: {
    id: 8042,
    name: 'Earth Shock',
    icon: 'spell_nature_earthshock',
    maxRanks: 1,
    talentId: 101854,
    __ignoreDuplication: true,
    maelstromCost: 60,
  },
  EARTHQUAKE_TALENT: {
    id: 61882,
    name: 'Earthquake',
    icon: 'spell_shaman_earthquake',
    maxRanks: 1,
    talentId: 101855,
    __ignoreDuplication: true,
    maelstromCost: 60,
  },
  ELEMENTAL_FURY_TALENT: {
    id: 60188,
    name: 'Elemental Fury',
    icon: 'spell_fire_volcano',
    maxRanks: 1,
    talentId: 101853,
    __ignoreDuplication: true,
  },
  FIRE_ELEMENTAL_TALENT: {
    id: 198067,
    name: 'Fire Elemental',
    icon: 'spell_fire_elemental_totem',
    maxRanks: 1,
    talentId: 101850,
    __ignoreDuplication: true,
    manaCost: 2500,
  },
  STORM_ELEMENTAL_TALENT: {
    id: 192249,
    name: 'Storm Elemental',
    icon: 'inv_stormelemental',
    maxRanks: 1,
    talentId: 101849,
    __ignoreDuplication: true,
  },
  TUMULTUOUS_FISSURES_TALENT: {
    id: 381743,
    name: 'Tumultuous Fissures',
    icon: 'ability_rogue_fleetfooted',
    maxRanks: 1,
    talentId: 101857,
    __ignoreDuplication: true,
  },
  INUNDATE_TALENT: {
    id: 378776,
    name: 'Inundate',
    icon: 'ability_shawaterelemental_swirl',
    maxRanks: 1,
    talentId: 101856,
    __ignoreDuplication: true,
  },
  PRIMORDIAL_FURY_TALENT: {
    id: 378193,
    name: 'Primordial Fury',
    icon: 'inv_10_elementalshardfoozles_primordial',
    maxRanks: 1,
    talentId: 101852,
    __ignoreDuplication: true,
  },
  PRIMORDIAL_BOND_TALENT: {
    id: 381764,
    name: 'Primordial Bond',
    icon: 'inv_elemental_primal_earth',
    maxRanks: 1,
    talentId: 101847,
    __ignoreDuplication: true,
  },
  FLOW_OF_POWER_TALENT: {
    id: 385923,
    name: 'Flow of Power',
    icon: 'spell_shaman_shockinglava',
    maxRanks: 1,
    talentId: 101871,
    __ignoreDuplication: true,
  },
  UNRELENTING_CALAMITY_TALENT: {
    id: 382685,
    name: 'Unrelenting Calamity',
    icon: 'ability_vehicle_electrocharge',
    maxRanks: 1,
    talentId: 101859,
    __ignoreDuplication: true,
  },
  ICEFURY_TALENT: {
    id: 210714,
    name: 'Icefury',
    icon: 'spell_frost_iceshard',
    maxRanks: 1,
    talentId: 101870,
    __ignoreDuplication: true,
    manaCost: 1500,
  },
  SWELLING_MAELSTROM_TALENT: {
    id: 381707,
    name: 'Swelling Maelstrom',
    icon: 'spell_shaman_maelstromweapon',
    maxRanks: 1,
    talentId: 101893,
    __ignoreDuplication: true,
  },
  CALL_OF_FIRE_TALENT: {
    id: 378255,
    name: 'Call of Fire',
    icon: 'spell_fire_ragnaros_molteninferno',
    maxRanks: 1,
    talentId: 101888,
    __ignoreDuplication: true,
  },
  STORMKEEPER_ELEMENTAL_TALENT: {
    id: 191634,
    name: 'Stormkeeper',
    icon: 'ability_thunderking_lightningwhip',
    maxRanks: 1,
    talentId: 101863,
    __ignoreDuplication: true,
  },
  FLUX_MELTING_TALENT: {
    id: 381776,
    name: 'Flux Melting',
    icon: 'spell_frostfire_orb',
    maxRanks: 1,
    talentId: 101869,
    __ignoreDuplication: true,
  },
  ELECTRIFIED_SHOCKS_TALENT: {
    id: 382086,
    name: 'Electrified Shocks',
    icon: 'inv_offhand_1h_artifactdoomhammer_d_02',
    maxRanks: 1,
    talentId: 101868,
    __ignoreDuplication: true,
  },
  AFTERSHOCK_TALENT: {
    id: 273221,
    name: 'Aftershock',
    icon: 'spell_nature_stormreach',
    maxRanks: 1,
    talentId: 101874,
    __ignoreDuplication: true,
  },
  SURGE_OF_POWER_TALENT: {
    id: 262303,
    name: 'Surge of Power',
    icon: 'spell_nature_shamanrage',
    maxRanks: 1,
    talentId: 101873,
    __ignoreDuplication: true,
  },
  FLAMES_OF_THE_CAULDRON_TALENT: {
    id: 378266,
    name: 'Flames of the Cauldron',
    icon: 'inv_misc_cauldron_fire',
    maxRanks: 1,
    talentId: 101887,
    __ignoreDuplication: true,
  },
  FLASH_OF_LIGHTNING_TALENT: {
    id: 381936,
    name: 'Flash of Lightning',
    icon: 'spell_lightning_lightningbolt01',
    maxRanks: 1,
    talentId: 101861,
    __ignoreDuplication: true,
  },
  EYE_OF_THE_STORM_TALENT: {
    id: 381708,
    name: 'Eye of the Storm',
    icon: 'spell_shadow_soulleech_2',
    maxRanks: 2,
    talentId: 101867,
    __ignoreDuplication: true,
  },
  POWER_OF_THE_MAELSTROM_TALENT: {
    id: 191861,
    name: 'Power of the Maelstrom',
    icon: 'spell_fire_masterofelements',
    maxRanks: 2,
    talentId: 101892,
    __ignoreDuplication: true,
  },
  IMPROVED_FLAMETONGUE_WEAPON_TALENT: {
    id: 382027,
    name: 'Improved Flametongue Weapon',
    icon: 'spell_fire_flametounge',
    maxRanks: 1,
    talentId: 101886,
    __ignoreDuplication: true,
  },
  ASCENDANCE_ELEMENTAL_TALENT: {
    id: 114050,
    name: 'Ascendance',
    icon: 'spell_fire_elementaldevastation',
    maxRanks: 1,
    talentId: 101877,
    __ignoreDuplication: true,
  },
  PRIMAL_ELEMENTALIST_TALENT: {
    id: 117013,
    name: 'Primal Elementalist',
    icon: 'shaman_talent_primalelementalist',
    maxRanks: 1,
    talentId: 101885,
    __ignoreDuplication: true,
  },
  LIQUID_MAGMA_TOTEM_TALENT: {
    id: 192222,
    name: 'Liquid Magma Totem',
    icon: 'spell_shaman_spewlava',
    maxRanks: 1,
    talentId: 101884,
    __ignoreDuplication: true,
    manaCost: 1750,
  },
  ECHOES_OF_GREAT_SUNDERING_TALENT: {
    id: 384087,
    name: 'Echoes of Great Sundering',
    icon: 'spell_shaman_earthquake',
    maxRanks: 2,
    talentId: 101862,
    __ignoreDuplication: true,
  },
  ELEMENTAL_EQUILIBRIUM_TALENT: {
    id: 378271,
    name: 'Elemental Equilibrium',
    icon: 'ability_shaman_ascendance',
    maxRanks: 2,
    talentId: 101865,
    __ignoreDuplication: true,
  },
  ROLLING_MAGMA_TALENT: {
    id: 386443,
    name: 'Rolling Magma',
    icon: 'ability_rhyolith_volcano',
    maxRanks: 2,
    talentId: 101843,
    __ignoreDuplication: true,
  },
  ECHO_CHAMBER_TALENT: {
    id: 382032,
    name: 'Echo Chamber',
    icon: 'spell_nature_lightningoverload',
    maxRanks: 2,
    talentId: 101890,
    __ignoreDuplication: true,
  },
  OATH_OF_THE_FAR_SEER_TALENT: {
    id: 381785,
    name: 'Oath of the Far Seer',
    icon: 'spell_shaman_elementaloath',
    maxRanks: 2,
    talentId: 101876,
    __ignoreDuplication: true,
  },
  MAGMA_CHAMBER_TALENT: {
    id: 381932,
    name: 'Magma Chamber',
    icon: 'ability_rhyolith_magmaflow_whole',
    maxRanks: 2,
    talentId: 101883,
    __ignoreDuplication: true,
  },
  SEARING_FLAMES_TALENT: {
    id: 381782,
    name: 'Searing Flames',
    icon: 'inv_offhand_1h_artifactdoomhammer_d_01',
    maxRanks: 2,
    talentId: 101880,
    __ignoreDuplication: true,
  },
  LIGHTNING_ROD_TALENT: {
    id: 210689,
    name: 'Lightning Rod',
    icon: 'inv_rod_enchantedcobalt',
    maxRanks: 1,
    talentId: 101864,
    __ignoreDuplication: true,
  },
  PRIMORDIAL_SURGE_TALENT: {
    id: 386474,
    name: 'Primordial Surge',
    icon: 'ability_rhyolith_magmaflow_wave',
    maxRanks: 1,
    talentId: 101845,
    __ignoreDuplication: true,
  },
  MOUNTAINS_WILL_FALL_TALENT: {
    id: 381726,
    name: 'Mountains Will Fall',
    icon: 'inv_elementalearth2',
    maxRanks: 1,
    talentId: 101889,
    __ignoreDuplication: true,
  },
  FURTHER_BEYOND_TALENT: {
    id: 381787,
    name: 'Further Beyond',
    icon: 'spell_holy_spiritualguidence',
    maxRanks: 1,
    talentId: 101875,
    __ignoreDuplication: true,
  },
  WINDSPEAKERS_LAVA_RESURGENCE_TALENT: {
    id: 378268,
    name: "Windspeaker's Lava Resurgence",
    icon: 'ability_rhyolith_lavapool',
    maxRanks: 1,
    talentId: 101882,
    __ignoreDuplication: true,
  },
  SKYBREAKERS_FIERY_DEMISE_TALENT: {
    id: 378310,
    name: "Skybreaker's Fiery Demise",
    icon: 'spell_fire_elemental_totem',
    maxRanks: 1,
    talentId: 101881,
    __ignoreDuplication: true,
  },
});

export default talents;
export { talents as TALENTS_SHAMAN };
