// Generated file, changes will eventually be overwritten!
import { createTalentList } from './types';

const talents = createTalentList({
  //Shared
  CHAIN_HEAL_TALENT: {
    id: 1064,
    name: 'Chain Heal',
    icon: 'spell_nature_healingwavegreater',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  LAVA_BURST_TALENT: {
    id: 51505,
    name: 'Lava Burst',
    icon: 'spell_shaman_lavaburst',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  ASTRAL_SHIFT_TALENT: {
    id: 108271,
    name: 'Astral Shift',
    icon: 'ability_shaman_astralshift',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  CHAIN_LIGHTNING_TALENT: {
    id: 188443,
    name: 'Chain Lightning',
    icon: 'spell_nature_chainlightning',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  EARTH_ELEMENTAL_TALENT: {
    id: 198103,
    name: 'Earth Elemental',
    icon: 'spell_nature_earthelemental_totem',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  WIND_SHEAR_TALENT: {
    id: 57994,
    name: 'Wind Shear',
    icon: 'spell_nature_cyclone',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  ASTRAL_BULWARK_TALENT: {
    id: 377933,
    name: 'Astral Bulwark',
    icon: 'spell_shaman_ancestralawakening',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  PLANES_TRAVELER_TALENT: {
    id: 381647,
    name: 'Planes Traveler',
    icon: 'spell_shaman_astralshift',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  THUNDEROUS_PAWS_TALENT: {
    id: 378075,
    name: 'Thunderous Paws',
    icon: 'ability_hunter_longevity',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  SPIRIT_WOLF_TALENT: {
    id: 260878,
    name: 'Spirit Wolf',
    icon: 'spell_hunter_lonewolf',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  FROST_SHOCK_TALENT: {
    id: 196840,
    name: 'Frost Shock',
    icon: 'spell_frost_frostshock',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  MAELSTROM_WEAPON_TALENT: {
    id: 187880,
    name: 'Maelstrom Weapon',
    icon: 'spell_shaman_maelstromweapon',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  EARTH_SHIELD_TALENT: {
    id: 974,
    name: 'Earth Shield',
    icon: 'spell_nature_skinofearth',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  FIRE_AND_ICE_TALENT: {
    id: 382886,
    name: 'Fire and Ice',
    icon: 'spell_firefrost_orb',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  CAPACITOR_TOTEM_TALENT: {
    id: 192058,
    name: 'Capacitor Totem',
    icon: 'spell_nature_brilliance',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  CLEANSE_SPIRIT_TALENT: {
    id: 51886,
    name: 'Cleanse Spirit',
    icon: 'ability_shaman_cleansespirit',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  FOCUSED_INSIGHT_TALENT: {
    id: 381666,
    name: 'Focused Insight',
    icon: 'spell_shaman_measuredinsight',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  ELEMENTAL_ORBIT_TALENT: {
    id: 383010,
    name: 'Elemental Orbit',
    icon: 'ability_mage_shattershield',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  SPIRITWALKERS_GRACE_TALENT: {
    id: 79206,
    name: "Spiritwalker's Grace",
    icon: 'spell_shaman_spiritwalkersgrace',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  ANCESTRAL_DEFENSE_TALENT: {
    id: 382947,
    name: 'Ancestral Defense',
    icon: 'ability_earthen_pillar',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  TREMOR_TOTEM_TALENT: {
    id: 8143,
    name: 'Tremor Totem',
    icon: 'spell_nature_tremortotem',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  GUARDIANS_CUDGEL_TALENT: {
    id: 381819,
    name: "Guardian's Cudgel",
    icon: 'inv_mace_2h_draenorcrafted_d_01_b_alliance',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  STATIC_CHARGE_TALENT: {
    id: 265046,
    name: 'Static Charge',
    icon: 'spell_nature_brilliance',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  HEX_TALENT: {
    id: 51514,
    name: 'Hex',
    icon: 'spell_shaman_hex',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  FLURRY_TALENT: {
    id: 382888,
    name: 'Flurry',
    icon: 'ability_ghoulfrenzy',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  SPIRITWALKERS_AEGIS_TALENT: {
    id: 378077,
    name: "Spiritwalker's Aegis",
    icon: 'ability_racial_forceshield',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  GRACEFUL_SPIRIT_TALENT: {
    id: 192088,
    name: 'Graceful Spirit',
    icon: 'spell_shaman_spectraltransformation',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  EARTHGRAB_TOTEM_TALENT: {
    id: 51485,
    name: 'Earthgrab Totem',
    icon: 'spell_nature_stranglevines',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
  },
  WIND_RUSH_TOTEM_TALENT: {
    id: 192077,
    name: 'Wind Rush Totem',
    icon: 'ability_shaman_windwalktotem',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
  },
  GREATER_PURGE_TALENT: {
    id: 378773,
    name: 'Greater Purge',
    icon: 'spell_shaman_focusedstrikes',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
  },
  PURGE_TALENT: {
    id: 370,
    name: 'Purge',
    icon: 'spell_nature_purge',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
  },
  ENFEEBLEMENT_TALENT: {
    id: 378079,
    name: 'Enfeeblement',
    icon: 'inv_frog2_teal',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  VOODOO_MASTERY_TALENT: {
    id: 204268,
    name: 'Voodoo Mastery',
    icon: 'spell_shaman_hex',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  NATURES_FURY_TALENT: {
    id: 381655,
    name: "Nature's Fury",
    icon: 'spell_nature_spiritarmor',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  TOTEMIC_SURGE_TALENT: {
    id: 381867,
    name: 'Totemic Surge',
    icon: 'spell_nature_agitatingtotem',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  ELEMENTAL_WARDING_TALENT: {
    id: 381650,
    name: 'Elemental Warding',
    icon: 'inv_10_elementalcombinedfoozles_primordial',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  NATURES_GUARDIAN_TALENT: {
    id: 30884,
    name: "Nature's Guardian",
    icon: 'spell_nature_natureguardian',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  WINDS_OF_ALAKIR_TALENT: {
    id: 382215,
    name: "Winds of Al'Akir",
    icon: 'ability_druid_galewinds',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  BRIMMING_WITH_LIFE_TALENT: {
    id: 381689,
    name: 'Brimming with Life',
    icon: 'inv_jewelry_talisman_06',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  HEALING_STREAM_TOTEM_TALENT: {
    id: 5394,
    name: 'Healing Stream Totem',
    icon: 'inv_spear_04',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  IMPROVED_LIGHTNING_BOLT_TALENT: {
    id: 381674,
    name: 'Improved Lightning Bolt',
    icon: 'spell_nature_lightning',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  TOTEMIC_PROJECTION_TALENT: {
    id: 108287,
    name: 'Totemic Projection',
    icon: 'ability_shaman_totemrelocation',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  GUST_OF_WIND_TALENT: {
    id: 192063,
    name: 'Gust of Wind',
    icon: 'ability_skyreach_four_wind',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
  },
  SPIRIT_WALK_TALENT: {
    id: 58875,
    name: 'Spirit Walk',
    icon: 'ability_tracking',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
  },
  SWIRLING_CURRENTS_TALENT: {
    id: 378094,
    name: 'Swirling Currents',
    icon: 'spell_holy_serendipity',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  NATURES_SWIFTNESS_TALENT: {
    id: 378081,
    name: "Nature's Swiftness",
    icon: 'spell_nature_ravenform',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  THUNDERSTORM_TALENT: {
    id: 51490,
    name: 'Thunderstorm',
    icon: 'spell_shaman_thunderstorm',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  TOTEMIC_FOCUS_TALENT: {
    id: 382201,
    name: 'Totemic Focus',
    icon: 'inv_relics_totemofrebirth',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  SURGING_SHIELDS_TALENT: {
    id: 382033,
    name: 'Surging Shields',
    icon: 'spell_nature_lightningshield',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  GO_WITH_THE_FLOW_TALENT: {
    id: 381678,
    name: 'Go With The Flow',
    icon: 'ability_racial_runningwild',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  MANA_SPRING_TOTEM_TALENT: {
    id: 381930,
    name: 'Mana Spring Totem',
    icon: 'spell_nature_manaregentotem',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  LIGHTNING_LASSO_TALENT: {
    id: 305483,
    name: 'Lightning Lasso',
    icon: 'shaman_pvp_lightninglasso',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  THUNDERSHOCK_TALENT: {
    id: 378779,
    name: 'Thundershock',
    icon: 'ability_thunderking_thunderstruck',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  POISON_CLEANSING_TOTEM_TALENT: {
    id: 383013,
    name: 'Poison Cleansing Totem',
    icon: 'spell_nature_poisoncleansingtotem',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  CALL_OF_THE_ELEMENTS_TALENT: {
    id: 108285,
    name: 'Call of the Elements',
    icon: 'ability_shaman_multitotemactivation',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  ANCESTRAL_GUIDANCE_TALENT: {
    id: 108281,
    name: 'Ancestral Guidance',
    icon: 'ability_shaman_ancestralguidance',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  TRANQUIL_AIR_TOTEM_TALENT: {
    id: 383019,
    name: 'Tranquil Air Totem',
    icon: 'ability_shaman_tranquilmindtotem',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  STONESKIN_TOTEM_TALENT: {
    id: 383017,
    name: 'Stoneskin Totem',
    icon: 'ability_shaman_stoneskintotem',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  CREATION_CORE_TALENT: {
    id: 383012,
    name: 'Creation Core',
    icon: 'inv_artifact_xp03',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  IMPROVED_CALL_OF_THE_ELEMENTS_TALENT: {
    id: 383011,
    name: 'Improved Call of the Elements',
    icon: 'ability_shaman_multitotemactivation',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },

  //Elemental
  EARTH_SHOCK_ELEMENTAL_TALENT: {
    id: 8042,
    name: 'Earth Shock',
    icon: 'spell_nature_earthshock',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  EARTHQUAKE_ELEMENTAL_TALENT: {
    id: 61882,
    name: 'Earthquake',
    icon: 'spell_shaman_earthquake',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  ELEMENTAL_FURY_ELEMENTAL_TALENT: {
    id: 60188,
    name: 'Elemental Fury',
    icon: 'spell_fire_volcano',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  STORM_ELEMENTAL_ELEMENTAL_TALENT: {
    id: 192249,
    name: 'Storm Elemental',
    icon: 'inv_stormelemental',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'choice',
  },
  FIRE_ELEMENTAL_ELEMENTAL_TALENT: {
    id: 198067,
    name: 'Fire Elemental',
    icon: 'spell_fire_elemental_totem',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'choice',
  },
  INUNDATE_ELEMENTAL_TALENT: {
    id: 378776,
    name: 'Inundate',
    icon: 'ability_shawaterelemental_swirl',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  TUMULTUOUS_FISSURES_ELEMENTAL_TALENT: {
    id: 381743,
    name: 'Tumultuous Fissures',
    icon: 'ability_rogue_fleetfooted',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  ANCESTRAL_WOLF_AFFINITY_ELEMENTAL_TALENT: {
    id: 382197,
    name: 'Ancestral Wolf Affinity',
    icon: 'spell_beastmaster_wolf',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  PRIMORDIAL_FURY_ELEMENTAL_TALENT: {
    id: 378193,
    name: 'Primordial Fury',
    icon: 'inv_10_elementalshardfoozles_primordial',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  PRIMORDIAL_BOND_ELEMENTAL_TALENT: {
    id: 381764,
    name: 'Primordial Bond',
    icon: 'inv_elemental_primal_earth',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  REFRESHING_WATERS_ELEMENTAL_TALENT: {
    id: 378211,
    name: 'Refreshing Waters',
    icon: 'ability_shaman_fortifyingwaters',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  CALL_OF_THUNDER_ELEMENTAL_TALENT: {
    id: 378241,
    name: 'Call of Thunder',
    icon: 'ability_thunderking_balllightning',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  MASTER_OF_THE_ELEMENTS_ELEMENTAL_TALENT: {
    id: 16166,
    name: 'Master of the Elements',
    icon: 'spell_nature_elementalabsorption',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  LAVA_SURGE_ELEMENTAL_TALENT: {
    id: 77756,
    name: 'Lava Surge',
    icon: 'spell_shaman_lavasurge',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  UNRELENTING_CALAMITY_ELEMENTAL_TALENT: {
    id: 382685,
    name: 'Unrelenting Calamity',
    icon: 'ability_vehicle_electrocharge',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  ICEFURY_ELEMENTAL_TALENT: {
    id: 210714,
    name: 'Icefury',
    icon: 'spell_frost_iceshard',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  SWELLING_MAELSTROM_ELEMENTAL_TALENT: {
    id: 381707,
    name: 'Swelling Maelstrom',
    icon: 'spell_shaman_maelstromweapon',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  ECHO_OF_THE_ELEMENTS_ELEMENTAL_TALENT: {
    id: 333919,
    name: 'Echo of the Elements',
    icon: 'ability_shaman_echooftheelements',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  CALL_OF_FIRE_ELEMENTAL_TALENT: {
    id: 378255,
    name: 'Call of Fire',
    icon: 'spell_fire_ragnaros_molteninferno',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  STORMKEEPER_ELEMENTAL_TALENT: {
    id: 191634,
    name: 'Stormkeeper',
    icon: 'ability_thunderking_lightningwhip',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  ELECTRIFIED_SHOCKS_ELEMENTAL_TALENT: {
    id: 382086,
    name: 'Electrified Shocks',
    icon: 'inv_offhand_1h_artifactdoomhammer_d_02',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  FLUX_MELTING_ELEMENTAL_TALENT: {
    id: 381776,
    name: 'Flux Melting',
    icon: 'spell_frostfire_orb',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  SURGE_OF_POWER_ELEMENTAL_TALENT: {
    id: 262303,
    name: 'Surge of Power',
    icon: 'spell_nature_shamanrage',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  AFTERSHOCK_ELEMENTAL_TALENT: {
    id: 273221,
    name: 'Aftershock',
    icon: 'spell_nature_stormreach',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  FLAMES_OF_THE_FIRELORD_ELEMENTAL_TALENT: {
    id: 381784,
    name: 'Flames of the Firelord',
    icon: 'inv_misc_petragnaros',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  FLAMES_OF_THE_CAULDRON_ELEMENTAL_TALENT: {
    id: 378266,
    name: 'Flames of the Cauldron',
    icon: 'inv_misc_cauldron_fire',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  FLASH_OF_LIGHTNING_ELEMENTAL_TALENT: {
    id: 381936,
    name: 'Flash of Lightning',
    icon: 'spell_lightning_lightningbolt01',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  SHAKE_THE_FOUNDATIONS_ELEMENTAL_TALENT: {
    id: 385513,
    name: 'Shake the Foundations',
    icon: 'spell_nature_unrelentingstorm',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  EYE_OF_THE_STORM_ELEMENTAL_TALENT: {
    id: 381708,
    name: 'Eye of the Storm',
    icon: 'spell_shadow_soulleech_2',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  POWER_OF_THE_MAELSTROM_ELEMENTAL_TALENT: {
    id: 191861,
    name: 'Power of the Maelstrom',
    icon: 'spell_fire_masterofelements',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  IMPROVED_FLAMETONGUE_WEAPON_ELEMENTAL_TALENT: {
    id: 382027,
    name: 'Improved Flametongue Weapon',
    icon: 'spell_fire_flametounge',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  ELEMENTAL_BLAST_ELEMENTAL_TALENT: {
    id: 117014,
    name: 'Elemental Blast',
    icon: 'shaman_talent_elementalblast',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  PRIMORDIAL_WAVE_ELEMENTAL_TALENT: {
    id: 375982,
    name: 'Primordial Wave',
    icon: 'ability_maldraxxus_shaman',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  ASCENDANCE_ELEMENTAL_TALENT: {
    id: 114050,
    name: 'Ascendance',
    icon: 'spell_fire_elementaldevastation',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  DEEPLY_ROOTED_ELEMENTS_ELEMENTAL_TALENT: {
    id: 378270,
    name: 'Deeply Rooted Elements',
    icon: 'inv_misc_herb_liferoot_stem',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  LIQUID_MAGMA_TOTEM_ELEMENTAL_TALENT: {
    id: 192222,
    name: 'Liquid Magma Totem',
    icon: 'spell_shaman_spewlava',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  PRIMAL_ELEMENTALIST_ELEMENTAL_TALENT: {
    id: 117013,
    name: 'Primal Elementalist',
    icon: 'shaman_talent_primalelementalist',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  ECHOES_OF_GREAT_SUNDERING_ELEMENTAL_TALENT: {
    id: 384087,
    name: 'Echoes of Great Sundering',
    icon: 'spell_shaman_earthquake',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  ELEMENTAL_EQUILIBRIUM_ELEMENTAL_TALENT: {
    id: 378271,
    name: 'Elemental Equilibrium',
    icon: 'ability_shaman_ascendance',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  TUMBLING_WAVES_ELEMENTAL_TALENT: {
    id: 382040,
    name: 'Tumbling Waves',
    icon: 'spell_animamaldraxxus_wave',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  ECHO_CHAMBER_ELEMENTAL_TALENT: {
    id: 382032,
    name: 'Echo Chamber',
    icon: 'spell_nature_lightningoverload',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  OATH_OF_THE_FAR_SEER_ELEMENTAL_TALENT: {
    id: 381785,
    name: 'Oath of the Far Seer',
    icon: 'spell_shaman_elementaloath',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  SEARING_FLAMES_ELEMENTAL_TALENT: {
    id: 381782,
    name: 'Searing Flames',
    icon: 'inv_offhand_1h_artifactdoomhammer_d_01',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  MAGMA_CHAMBER_ELEMENTAL_TALENT: {
    id: 381932,
    name: 'Magma Chamber',
    icon: 'ability_rhyolith_magmaflow_whole',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  LIGHTNING_ROD_ELEMENTAL_TALENT: {
    id: 210689,
    name: 'Lightning Rod',
    icon: 'inv_rod_enchantedcobalt',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  SPLINTERED_ELEMENTS_ELEMENTAL_TALENT: {
    id: 382042,
    name: 'Splintered Elements',
    icon: 'spell_nature_elementalprecision_1',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  MOUNTAINS_WILL_FALL_ELEMENTAL_TALENT: {
    id: 381726,
    name: 'Mountains Will Fall',
    icon: 'inv_elementalearth2',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  FURTHER_BEYOND_ELEMENTAL_TALENT: {
    id: 381787,
    name: 'Further Beyond',
    icon: 'spell_holy_spiritualguidence',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  SKYBREAKERS_FIERY_DEMISE_ELEMENTAL_TALENT: {
    id: 378310,
    name: "Skybreaker's Fiery Demise",
    icon: 'spell_fire_elemental_totem',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  WINDSPEAKERS_LAVA_RESURGENCE_ELEMENTAL_TALENT: {
    id: 378268,
    name: "Windspeaker's Lava Resurgence",
    icon: 'ability_rhyolith_lavapool',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },

  //Enhancement
  STORMSTRIKE_ENHANCEMENT_TALENT: {
    id: 17364,
    name: 'Stormstrike',
    icon: 'ability_shaman_stormstrike',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  WINDFURY_WEAPON_ENHANCEMENT_TALENT: {
    id: 33757,
    name: 'Windfury Weapon',
    icon: 'spell_shaman_unleashweapon_wind',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  LAVA_LASH_ENHANCEMENT_TALENT: {
    id: 334033,
    name: 'Lava Lash',
    icon: 'spell_shaman_improvelavalash',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  FORCEFUL_WINDS_ENHANCEMENT_TALENT: {
    id: 262647,
    name: 'Forceful Winds',
    icon: 'spell_shaman_unleashweapon_wind',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  IMPROVED_MAELSTROM_WEAPON_ENHANCEMENT_TALENT: {
    id: 383303,
    name: 'Improved Maelstrom Weapon',
    icon: 'spell_shaman_maelstromweapon',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  UNRULY_WINDS_ENHANCEMENT_TALENT: {
    id: 338318,
    name: 'Unruly Winds',
    icon: 'ability_skyreach_wind_wall',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  RAGING_MAELSTROM_ENHANCEMENT_TALENT: {
    id: 384143,
    name: 'Raging Maelstrom',
    icon: 'spell_shaman_stormearthfire',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  FERAL_LUNGE_ENHANCEMENT_TALENT: {
    id: 196884,
    name: 'Feral Lunge',
    icon: 'spell_beastmaster_wolf',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  PRIMAL_LAVA_ACTUATORS_ENHANCEMENT_TALENT: {
    id: 335895,
    name: 'Primal Lava Actuators',
    icon: 'spell_shaman_stormearthfire',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  PRIMAL_PRIMER_ENHANCEMENT_TALENT: {
    id: 272992,
    name: 'Primal Primer',
    icon: 'ability_shaman_lavalash',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  DOOM_WINDS_ENHANCEMENT_TALENT: {
    id: 384352,
    name: 'Doom Winds',
    icon: 'ability_ironmaidens_swirlingvortex',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  SUNDERING_ENHANCEMENT_TALENT: {
    id: 197214,
    name: 'Sundering',
    icon: 'ability_rhyolith_lavapool',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  OVERFLOWING_MAELSTROM_ENHANCEMENT_TALENT: {
    id: 384149,
    name: 'Overflowing Maelstrom',
    icon: 'spell_shaman_maelstromweapon',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  FOCUSED_MAELSTROM_ENHANCEMENT_TALENT: {
    id: 384146,
    name: 'Focused Maelstrom',
    icon: 'spell_shaman_spectraltransformation',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  WINDFURY_TOTEM_ENHANCEMENT_TALENT: {
    id: 8512,
    name: 'Windfury Totem',
    icon: 'spell_nature_windfury',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  FIRE_NOVA_ENHANCEMENT_TALENT: {
    id: 333974,
    name: 'Fire Nova',
    icon: 'spell_shaman_improvedfirenova',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
  },
  HAILSTORM_ENHANCEMENT_TALENT: {
    id: 334195,
    name: 'Hailstorm',
    icon: 'spell_frost_icestorm',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  ELEMENTAL_WEAPONS_ENHANCEMENT_TALENT: {
    id: 384355,
    name: 'Elemental Weapons',
    icon: 'spell_nature_elementalprecision_1',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  STORMBRINGER_ENHANCEMENT_TALENT: {
    id: 201845,
    name: 'Stormbringer',
    icon: 'spell_nature_stormreach',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  ANCESTRAL_WOLF_AFFINITY_ENHANCEMENT_TALENT: {
    id: 382197,
    name: 'Ancestral Wolf Affinity',
    icon: 'spell_beastmaster_wolf',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  REFRESHING_WATERS_ENHANCEMENT_TALENT: {
    id: 337974,
    name: 'Refreshing Waters',
    icon: 'ability_shaman_fortifyingwaters',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  CRASH_LIGHTNING_ENHANCEMENT_TALENT: {
    id: 187874,
    name: 'Crash Lightning',
    icon: 'spell_shaman_crashlightning',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  STORMFLURRY_ENHANCEMENT_TALENT: {
    id: 344357,
    name: 'Stormflurry',
    icon: 'ability_shaman_stormstrike',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  ICE_STRIKE_ENHANCEMENT_TALENT: {
    id: 342240,
    name: 'Ice Strike',
    icon: 'spell_frost_frostbolt',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  ELEMENTAL_BLAST_ENHANCEMENT_TALENT: {
    id: 117014,
    name: 'Elemental Blast',
    icon: 'shaman_talent_elementalblast',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  IMPROVD_STORMBRINGER_ENHANCEMENT_TALENT: {
    id: 319930,
    name: 'Improvd Stormbringer',
    icon: 'spell_nature_stormreach',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  GATHERING_STORMS_ENHANCEMENT_TALENT: {
    id: 384363,
    name: 'Gathering Storms',
    icon: 'warrior_talent_icon_stormbolt',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  CHAIN_LIGHTNING_ENHANCEMENT_TALENT: {
    id: 334308,
    name: 'Chain Lightning',
    icon: 'spell_nature_chainlightning',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  HOT_HAND_ENHANCEMENT_TALENT: {
    id: 201900,
    name: 'Hot Hand',
    icon: 'spell_fire_playingwithfire',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  SWIRLING_MAELSTROM_ENHANCEMENT_TALENT: {
    id: 384359,
    name: 'Swirling Maelstrom',
    icon: 'spell_shadow_soulleech_2',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  PRIMORDIAL_WAVE_ENHANCEMENT_TALENT: {
    id: 375982,
    name: 'Primordial Wave',
    icon: 'ability_maldraxxus_shaman',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  FERAL_SPIRIT_ENHANCEMENT_TALENT: {
    id: 51533,
    name: 'Feral Spirit',
    icon: 'spell_shaman_feralspirit',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  ASCENDANCE_ENHANCEMENT_TALENT: {
    id: 114051,
    name: 'Ascendance',
    icon: 'spell_fire_elementaldevastation',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  PRIMAL_MAELSTROM_ENHANCEMENT_TALENT: {
    id: 384405,
    name: 'Primal Maelstrom',
    icon: 'shaman_talent_unleashedfury',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  ELEMENTAL_ASSAULT_ENHANCEMENT_TALENT: {
    id: 210853,
    name: 'Elemental Assault',
    icon: 'spell_shaman_improvedstormstrike',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  WITCH_DOCTORS_WOLF_BONES_ENHANCEMENT_TALENT: {
    id: 384447,
    name: "Witch Doctor's Wolf Bones",
    icon: 'inv_misc_bone_09',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  LEGACY_OF_THE_FROST_WITCH_ENHANCEMENT_TALENT: {
    id: 384450,
    name: 'Legacy of the Frost Witch',
    icon: 'ability_thunderking_thunderstruck',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  STATIC_ACCUMULATION_ENHANCEMENT_TALENT: {
    id: 384411,
    name: 'Static Accumulation',
    icon: 'spell_nature_callstorm',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  SPLINTERED_ELEMENTS_ENHANCEMENT_TALENT: {
    id: 382042,
    name: 'Splintered Elements',
    icon: 'spell_nature_elementalprecision_1',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  ALPHA_WOLF_ENHANCEMENT_TALENT: {
    id: 198434,
    name: 'Alpha Wolf',
    icon: 'spell_beastmaster_wolf',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  ELEMENTAL_SPIRITS_ENHANCEMENT_TALENT: {
    id: 262624,
    name: 'Elemental Spirits',
    icon: 'spell_shaman_feralspirit',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  THORIMS_INVOCATION_ENHANCEMENT_TALENT: {
    id: 384444,
    name: "Thorim's Invocation",
    icon: 'spell_shaman_ancestralawakening',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },

  //Restoration
  RIPTIDE_RESTORATION_TALENT: {
    id: 61295,
    name: 'Riptide',
    icon: 'spell_nature_riptide',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  HEALING_RAIN_RESTORATION_TALENT: {
    id: 73920,
    name: 'Healing Rain',
    icon: 'spell_nature_giftofthewaterspirit',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  HEALING_WAVE_RESTORATION_TALENT: {
    id: 77472,
    name: 'Healing Wave',
    icon: 'spell_nature_healingwavelesser',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  HEALING_STREAM_TOTEM_RESTORATION_TALENT: {
    id: 5394,
    name: 'Healing Stream Totem',
    icon: 'inv_spear_04',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  DELUGE_RESTORATION_TALENT: {
    id: 200076,
    name: 'Deluge',
    icon: 'ability_shawaterelemental_reform',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  WATER_SHIELD_RESTORATION_TALENT: {
    id: 52127,
    name: 'Water Shield',
    icon: 'ability_shaman_watershield',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  TIDAL_WAVES_RESTORATION_TALENT: {
    id: 51564,
    name: 'Tidal Waves',
    icon: 'spell_shaman_tidalwaves',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  ACID_RAIN_RESTORATION_TALENT: {
    id: 378443,
    name: 'Acid Rain',
    icon: 'spell_nature_acid_01',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  CALL_OF_THUNDER_RESTORATION_TALENT: {
    id: 378241,
    name: 'Call of Thunder',
    icon: 'ability_thunderking_balllightning',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  OVERFLOWING_SHORES_RESTORATION_TALENT: {
    id: 383222,
    name: 'Overflowing Shores',
    icon: 'spell_nature_giftofthewaterspirit',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  LAVA_SURGE_RESTORATION_TALENT: {
    id: 77756,
    name: 'Lava Surge',
    icon: 'spell_shaman_lavasurge',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  FLASH_FLOOD_RESTORATION_TALENT: {
    id: 280614,
    name: 'Flash Flood',
    icon: 'spell_frost_summonwaterelemental',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  WATER_TOTEM_MASTERY_RESTORATION_TALENT: {
    id: 382030,
    name: 'Water Totem Mastery',
    icon: 'ability_shaman_totemcooldownrefund',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  ANCESTRAL_WOLF_AFFINITY_RESTORATION_TALENT: {
    id: 382197,
    name: 'Ancestral Wolf Affinity',
    icon: 'spell_beastmaster_wolf',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  STORMKEEPER_RESTORATION_TALENT: {
    id: 383009,
    name: 'Stormkeeper',
    icon: 'ability_thunderking_lightningwhip',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
  },
  WAVESPEAKERS_BLESSING_RESTORATION_TALENT: {
    id: 381946,
    name: "Wavespeaker's Blessing",
    icon: 'inv_alchemist_81_spiritedalchemiststone',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  SPIRIT_LINK_TOTEM_RESTORATION_TALENT: {
    id: 98008,
    name: 'Spirit Link Totem',
    icon: 'spell_shaman_spiritlink',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  MASTER_OF_THE_ELEMENTS_RESTORATION_TALENT: {
    id: 16166,
    name: 'Master of the Elements',
    icon: 'spell_nature_elementalabsorption',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  REFRESHING_WATERS_RESTORATION_TALENT: {
    id: 378211,
    name: 'Refreshing Waters',
    icon: 'ability_shaman_fortifyingwaters',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  CLOUDBURST_TOTEM_RESTORATION_TALENT: {
    id: 157153,
    name: 'Cloudburst Totem',
    icon: 'ability_shaman_condensationtotem',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
  },
  LIVING_STREAM_RESTORATION_TALENT: {
    id: 382482,
    name: 'Living Stream',
    icon: 'spell_nature_natureresistancetotem',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  ANCESTRAL_VIGOR_RESTORATION_TALENT: {
    id: 207401,
    name: 'Ancestral Vigor',
    icon: 'spell_shaman_blessingoftheeternals',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  HEALING_TIDE_TOTEM_RESTORATION_TALENT: {
    id: 108280,
    name: 'Healing Tide Totem',
    icon: 'ability_shaman_healingtide',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  RESURGENCE_RESTORATION_TALENT: {
    id: 16196,
    name: 'Resurgence',
    icon: 'ability_shaman_watershield',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  MANA_TIDE_TOTEM_RESTORATION_TALENT: {
    id: 16191,
    name: 'Mana Tide Totem',
    icon: 'spell_frost_summonwaterelemental',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  TORRENT_RESTORATION_TALENT: {
    id: 200072,
    name: 'Torrent',
    icon: 'spell_nature_riptide',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  FLOW_OF_THE_TIDES_RESTORATION_TALENT: {
    id: 382039,
    name: 'Flow of the Tides',
    icon: 'spell_frost_manarecharge',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  ANCESTRAL_REACH_RESTORATION_TALENT: {
    id: 382732,
    name: 'Ancestral Reach',
    icon: 'spell_nature_healingwavegreater',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  UNLEASH_LIFE_RESTORATION_TALENT: {
    id: 73685,
    name: 'Unleash Life',
    icon: 'spell_shaman_unleashweapon_life',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
  },
  UNDULATION_RESTORATION_TALENT: {
    id: 200071,
    name: 'Undulation',
    icon: 'spell_nature_healingway',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  ECHO_OF_THE_ELEMENTS_RESTORATION_TALENT: {
    id: 333919,
    name: 'Echo of the Elements',
    icon: 'ability_shaman_echooftheelements',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  ANCESTRAL_PROTECTION_TOTEM_RESTORATION_TALENT: {
    id: 207399,
    name: 'Ancestral Protection Totem',
    icon: 'spell_nature_reincarnation',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
  },
  EARTHEN_WALL_TOTEM_RESTORATION_TALENT: {
    id: 198838,
    name: 'Earthen Wall Totem',
    icon: 'spell_nature_stoneskintotem',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
  },
  EARTHLIVING_WEAPON_RESTORATION_TALENT: {
    id: 382021,
    name: 'Earthliving Weapon',
    icon: 'spell_shaman_giftearthmother',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  PRIMORDIAL_WAVE_RESTORATION_TALENT: {
    id: 375982,
    name: 'Primordial Wave',
    icon: 'ability_maldraxxus_shaman',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  ANCESTRAL_AWAKENING_RESTORATION_TALENT: {
    id: 382309,
    name: 'Ancestral Awakening',
    icon: 'spell_shaman_ancestralawakening',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  EARTHEN_HARMONY_RESTORATION_TALENT: {
    id: 382020,
    name: 'Earthen Harmony',
    icon: 'spell_shaman_improvedearthshield',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  UNDERCURRENT_RESTORATION_TALENT: {
    id: 382194,
    name: 'Undercurrent',
    icon: 'spell_fire_bluehellfire',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  IMPROVED_PRIMORDIAL_WAVE_RESTORATION_TALENT: {
    id: 382191,
    name: 'Improved Primordial Wave',
    icon: 'ability_maldraxxus_shaman',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  DOWNPOUR_RESTORATION_TALENT: {
    id: 207778,
    name: 'Downpour',
    icon: 'ability_mage_waterjet',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  NATURES_FOCUS_RESTORATION_TALENT: {
    id: 382019,
    name: "Nature's Focus",
    icon: 'spell_shaman_blessingofeternals',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  EVER_RISING_TIDE_RESTORATION_TALENT: {
    id: 382029,
    name: 'Ever-Rising Tide',
    icon: 'inv_elemental_primal_water',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  EARTHWARDEN_RESTORATION_TALENT: {
    id: 382315,
    name: 'Earthwarden',
    icon: 'spell_shaman_giftearthmother',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  TUMBLING_WAVES_RESTORATION_TALENT: {
    id: 382040,
    name: 'Tumbling Waves',
    icon: 'spell_animamaldraxxus_wave',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  CONTINUOUS_WAVES_RESTORATION_TALENT: {
    id: 382046,
    name: 'Continuous Waves',
    icon: 'spell_animabastion_wave',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  HIGH_TIDE_RESTORATION_TALENT: {
    id: 157154,
    name: 'High Tide',
    icon: 'spell_shaman_hightide',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  PRIMAL_TIDE_CORE_RESTORATION_TALENT: {
    id: 382045,
    name: 'Primal Tide Core',
    icon: 'ability_shaman_repulsiontotem',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  ASCENDANCE_RESTORATION_TALENT: {
    id: 114052,
    name: 'Ascendance',
    icon: 'spell_fire_elementaldevastation',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  WELLSPRING_RESTORATION_TALENT: {
    id: 197995,
    name: 'Wellspring',
    icon: 'ability_shawaterelemental_split',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'choice',
  },
  DEEPLY_ROOTED_ELEMENTS_RESTORATION_TALENT: {
    id: 378270,
    name: 'Deeply Rooted Elements',
    icon: 'inv_misc_herb_liferoot_stem',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
});

export default talents;
export { talents as TALENTS_SHAMAN };
