// Generated file, changes will be overwritten!

export default {
  // Shared
  SHOCKWAVE_TALENT: { id: 46968, name: "Shockwave", icon: "ability_warrior_shockwave" },
  STORM_BOLT_TALENT: { id: 107570, name: "Storm Bolt", icon: "warrior_talent_icon_stormbolt" },
  DOUBLE_TIME_TALENT: { id: 103827, name: "Double Time", icon: "inv_misc_horn_04" },
  OUTBURST_TALENT: { id: 206320, name: "Outburst", icon: "spell_nature_ancestralguardian" },
  AVATAR_TALENT: { id: 107574, name: "Avatar", icon: "warrior_talent_icon_avatar" },
  SECOND_WIND_TALENT: { id: 29838, name: "Second Wind", icon: "ability_hunter_harass" },
  BOUNDING_STRIDE_TALENT: { id: 202163, name: "Bounding Stride", icon: "ability_heroicleap" },
  ANGER_MANAGEMENT_TALENT: { id: 152278, name: "Anger Management", icon: "warrior_talent_icon_angermanagement" },
  // Arms
  DAUNTLESS_TALENT: { id: 202297, name: "Dauntless", icon: "ability_warrior_unrelentingassault" },
  OVERPOWER_TALENT: { id: 7384, name: "Overpower", icon: "ability_meleedamage" },
  SWEEPING_STRIKES_TALENT: { id: 202161, name: "Sweeping Strikes", icon: "ability_rogue_slicedice" },
  TRAUMA_TALENT: { id: 215538, name: "Trauma", icon: "ability_warrior_trauma" },
  REND_TALENT: { id: 772, name: "Rend", icon: "ability_gouge", rageCost: 30 },
  DEFENSIVE_STANCE_TALENT: { id: 197690, name: "Defensive Stance", icon: "ability_warrior_defensivestance" },
  FERVOR_OF_BATTLE_TALENT: { id: 202316, name: "Fervor of Battle", icon: "ability_rogue_waylay" },
  MORTAL_COMBO_TALENT: { id: 202593, name: "Mortal Combo", icon: "ability_warrior_savageblow" },
  TITANIC_MIGHT_TALENT: { id: 202612, name: "Titanic Might", icon: "ability_warrior_colossussmash" },
  DEADLY_CALM_TALENT: { id: 227266, name: "Deadly Calm", icon: "achievement_boss_kingymiron" },
  IN_FOR_THE_KILL_TALENT: { id: 248621, name: "In For The Kill", icon: "ability_blackhand_marked4death" },
  FOCUSED_RAGE_TALENT: { id: 207982, name: "Focused Rage", icon: "ability_warrior_focusedrage", rageCost: 20 },
  OPPORTUNITY_STRIKES_TALENT: { id: 203179, name: "Opportunity Strikes", icon: "ability_backstab" },
  RAVAGER_TALENT_ARMS: { id: 152277, name: "Ravager", icon: "warrior_talent_icon_ravager" },
  // Protection
  WARBRINGER_TALENT: { id: 103828, name: "Warbringer", icon: "ability_warrior_warbringer" },
  IMPENDING_VICTORY_TALENT: { id: 202168, name: "Impending Victory", icon: "spell_impending_victory", rageCost: 10 },
  INSPIRING_PRESENCE_TALENT: { id: 205484, name: "Inspiring Presence", icon: "ability_toughness" },
  SAFEGUARD_TALENT: { id: 223657, name: "Safeguard", icon: "ability_warrior_safeguard" },
  RENEWED_FURY_TALENT: { id: 202288, name: "Renewed Fury", icon: "ability_warrior_intensifyrage" },
  BEST_SERVED_COLD_TALENT: { id: 202560, name: "Best Served Cold", icon: "ability_warrior_revenge" },
  WARLORDS_CHALLENGE_TALENT: { id: 223662, name: "Warlord's Challenge", icon: "ability_racial_bloodrage" },
  CRACKLING_THUNDER_TALENT: { id: 203201, name: "Crackling Thunder", icon: "ability_thunderking_overcharge" },
  DEVASTATOR_TALENT: { id: 236279, name: "Devastator", icon: "inv_sword_11" },
  NEVER_SURRENDER_TALENT: { id: 202561, name: "Never Surrender", icon: "ability_butcher_gushingwounds" },
  INDOMITABLE_TALENT: { id: 202095, name: "Indomitable", icon: "ability_warrior_intensifyrage" },
  VENGEANCE_TALENT: { id: 202572, name: "Vengeance", icon: "ability_warrior_unrelentingassault" },
  INTO_THE_FRAY_TALENT: { id: 202603, name: "Into the Fray", icon: "ability_warrior_bloodfrenzy" },
  BOOMING_VOICE_TALENT: { id: 202743, name: "Booming Voice", icon: "ability_warrior_battleshout" },
  HEAVY_REPERCUSSIONS_TALENT: { id: 203177, name: "Heavy Repercussions", icon: "inv_shield_32" },
  RAVAGER_TALENT_PROTECTION: { id: 228920, name: "Ravager", icon: "warrior_talent_icon_ravager" },
  // Fury
  WAR_MACHINE_TALENT: { id: 215556, name: "War Machine", icon: "ability_hunter_rapidkilling" },
  ENDLESS_RAGE_TALENT: { id: 202296, name: "Endless Rage", icon: "ability_warrior_endlessrage" },
  FRESH_MEAT_TALENT: { id: 215568, name: "Fresh Meat", icon: "ability_deathwing_bloodcorruption_death" },
  WRECKING_BALL_TALENT: { id: 215569, name: "Wrecking Ball", icon: "ability_butcher_whirl" },
  FURIOUS_CHARGE_TALENT: { id: 202224, name: "Furious Charge", icon: "spell_warrior_barbarian" },
  WARPAINT_TALENT: { id: 208154, name: "Warpaint", icon: "ability_rogue_preparation" },
  MASSACRE_TALENT: { id: 206315, name: "Massacre", icon: "inv_sword_48" },
  FROTHING_BERSERKER_TALENT: { id: 215571, name: "Frothing Berserker", icon: "warrior_talent_icon_furyintheblood" },
  CARNAGE_TALENT: { id: 202922, name: "Carnage", icon: "ability_warrior_rampage" },
  BLOODBATH_TALENT: { id: 12292, name: "Bloodbath", icon: "ability_warrior_bloodbath" },
  FRENZY_TALENT: { id: 206313, name: "Frenzy", icon: "inv_axe_2h_orcwarrior_c_01" },
  INNER_RAGE_TALENT: { id: 215573, name: "Inner Rage", icon: "ability_warrior_innerrage" },
  BLADESTORM_TALENT: { id: 46924, name: "Bladestorm", icon: "ability_warrior_bladestorm" },
  RECKLESS_ABANDON_TALENT: { id: 202751, name: "Reckless Abandon", icon: "ability_warrior_battleshout" },
  DRAGON_ROAR_TALENT: { id: 118000, name: "Dragon Roar", icon: "ability_warrior_dragonroar" },
};
