// Generated file, changes will eventually be overwritten!
import { createTalentList } from './types';

const talents = createTalentList({
  //Shared
  FEL_DOMINATION_TALENT: {
    id: 333889,
    name: 'Fel Domination',
    icon: 'spell_shadow_felmending',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  CURSES_OF_ENFEEBLEMENT_TALENT: {
    id: 386105,
    name: 'Curses of Enfeeblement',
    icon: 'ability_creature_cursed_02',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  BURNING_RUSH_TALENT: {
    id: 111400,
    name: 'Burning Rush',
    icon: 'ability_deathwing_sealarmorbreachtga',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  QUICK_FIENDS_TALENT: {
    id: 386113,
    name: 'Quick Fiends',
    icon: 'spell_shadow_impphaseshift',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  DEMON_SKIN_TALENT: {
    id: 219272,
    name: 'Demon Skin',
    icon: 'spell_shadow_ragingscream',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  FEL_ARMOR_TALENT: {
    id: 386124,
    name: 'Fel Armor',
    icon: 'spell_shadow_felarmour',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  IMP_STEP_TALENT: {
    id: 386110,
    name: 'Imp Step',
    icon: 'inv_misc_moosehoof_fel',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  SPELL_LOCK_TALENT: {
    id: 19647,
    name: 'Spell Lock',
    icon: 'spell_shadow_mindrot',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  ACCRUED_VITALITY_TALENT: {
    id: 386613,
    name: 'Accrued Vitality',
    icon: 'spell_shadow_lifedrain',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  MORTAL_COIL_TALENT: {
    id: 6789,
    name: 'Mortal Coil',
    icon: 'ability_warlock_mortalcoil',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'choice',
    manaCost: 1000,
  },
  HOWL_OF_TERROR_TALENT: {
    id: 5484,
    name: 'Howl of Terror',
    icon: 'ability_warlock_howlofterror',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'choice',
  },
  AMPLIFY_CURSE_TALENT: {
    id: 328774,
    name: 'Amplify Curse',
    icon: 'spell_shadow_contagion',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
  },
  DEMONIC_EMBRACE_TALENT: {
    id: 288843,
    name: 'Demonic Embrace',
    icon: 'spell_shadow_metamorphosis',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  DEMONIC_INSPIRATION_TALENT: {
    id: 386858,
    name: 'Demonic Inspiration',
    icon: 'ability_warlock_demonicpower',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  DEMONIC_CIRCLE_TALENT: {
    id: 48018,
    name: 'Demonic Circle',
    icon: 'spell_shadow_demoniccirclesummon',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
    manaCost: 1000,
  },
  WRATHFUL_MINION_TALENT: {
    id: 386864,
    name: 'Wrathful Minion',
    icon: 'spell_fel_incinerate',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  DEMONIC_FORTITUDE_TALENT: {
    id: 386617,
    name: 'Demonic Fortitude',
    icon: 'spell_warlock_summonimpoutland',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  BANISH_TALENT: {
    id: 710,
    name: 'Banish',
    icon: 'spell_shadow_cripple',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
    manaCost: 500,
  },
  FOUL_MOUTH_TALENT: {
    id: 387972,
    name: 'Foul Mouth',
    icon: 'spell_shadow_carrionswarm',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  DESPERATE_POWER_TALENT: {
    id: 386619,
    name: 'Desperate Power',
    icon: 'spell_shadow_lifedrain02',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  SWEET_SOULS_TALENT: {
    id: 386620,
    name: 'Sweet Souls',
    icon: 'spell_shadow_soulleech',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  LIFEBLOOD_TALENT: {
    id: 386646,
    name: 'Lifeblood',
    icon: 'warlock__healthstone',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  DEMONIC_GATEWAY_TALENT: {
    id: 111771,
    name: 'Demonic Gateway',
    icon: 'spell_warlock_demonicportal_green',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
    manaCost: 10000,
  },
  NIGHTMARE_TALENT: {
    id: 386648,
    name: 'Nightmare',
    icon: 'spell_shadow_possession',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  GREATER_BANISH_TALENT: {
    id: 386651,
    name: 'Greater Banish',
    icon: 'spell_shadow_cripple',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  DARK_PACT_TALENT: {
    id: 108416,
    name: 'Dark Pact',
    icon: 'spell_shadow_deathpact',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  DEMONIC_DURABILITY_TALENT: {
    id: 386659,
    name: 'Demonic Durability',
    icon: 'ability_warlock_improveddemonictactics',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  STRENGTH_OF_WILL_TALENT: {
    id: 317138,
    name: 'Strength of Will',
    icon: 'spell_shadow_demonictactics',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  SHADOWFURY_TALENT: {
    id: 30283,
    name: 'Shadowfury',
    icon: 'ability_warlock_shadowfurytga',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
    manaCost: 500,
  },
  FREQUENT_DONOR_TALENT: {
    id: 386686,
    name: 'Frequent Donor',
    icon: 'ability_ironmaidens_bloodritual',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  ICHOR_OF_DEVILS_TALENT: {
    id: 386664,
    name: 'Ichor of Devils',
    icon: 'spell_yorsahj_bloodboil_greenoil',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  CLAW_OF_ENDERETH_TALENT: {
    id: 386689,
    name: 'Claw of Endereth',
    icon: 'inv_flaming_splinter',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  GRIMOIRE_OF_SYNERGY_TALENT: {
    id: 171975,
    name: 'Grimoire of Synergy',
    icon: 'warlock_grimoireofsacrifice',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  SHADOWFLAME_TALENT: {
    id: 384069,
    name: 'Shadowflame',
    icon: 'ability_warlock_shadowflame',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  DARKFURY_TALENT: {
    id: 264874,
    name: 'Darkfury',
    icon: 'ability_warlock_shadowfurytga',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  TEACHINGS_OF_THE_BLACK_HARVEST_TALENT: {
    id: 385881,
    name: 'Teachings of the Black Harvest',
    icon: 'inv_misc_codexofxerrath_nochains',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  SOUL_LINK_TALENT: {
    id: 108415,
    name: 'Soul Link',
    icon: 'ability_warlock_soullink',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  SOULBURN_TALENT: {
    id: 385899,
    name: 'Soulburn',
    icon: 'spell_warlock_soulburn',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
    soulshardsCost: 1,
  },
  PACT_OF_THE_IMP_MOTHER_TALENT: {
    id: 387001,
    name: 'Pact of the Imp Mother',
    icon: 'inv_archaeology_70_impgenerator',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  SOUL_CONDUIT_TALENT: {
    id: 215941,
    name: 'Soul Conduit',
    icon: 'spell_shadow_soulleech_2',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  PACT_OF_THE_ANNIHILAN_TALENT: {
    id: 387042,
    name: 'Pact of the Annihilan',
    icon: 'inv_misc_magtheridonshead',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  INQUISITORS_GAZE_NYI_TALENT: {
    id: 386344,
    name: "Inquisitor's Gaze [NYI]",
    icon: 'inv_pet_inquisitoreye',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  PACT_OF_THE_EREDAR_TALENT: {
    id: 387061,
    name: 'Pact of the Eredar',
    icon: 'achievement_boss_argus_femaleeredar',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  SUMMON_JAILER_NYI_TALENT: {
    id: 386244,
    name: 'Summon Jailer [NYI]',
    icon: 'spell_fel_elementaldevastation',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
  DECIMATING_BOLT_TALENT: {
    id: 386696,
    name: 'Decimating Bolt',
    icon: 'ability_maldraxxus_warlock',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
    manaCost: 2000,
  },
  DIMENSIONAL_RIFT_TALENT: {
    id: 387976,
    name: 'Dimensional Rift',
    icon: 'spell_warlock_demonicportal_purple',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },

  //Destruction
  CHAOS_BOLT_DESTRUCTION_TALENT: {
    id: 116858,
    name: 'Chaos Bolt',
    icon: 'ability_warlock_chaosbolt',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
    soulshardsCost: 2,
  },
  CONFLAGRATE_DESTRUCTION_TALENT: {
    id: 17962,
    name: 'Conflagrate',
    icon: 'spell_fire_fireball',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
    manaCost: 500,
  },
  HAVOC_DESTRUCTION_TALENT: {
    id: 80240,
    name: 'Havoc',
    icon: 'ability_warlock_baneofhavoc',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'choice',
    manaCost: 1000,
  },
  MAYHEM_NYI_DESTRUCTION_TALENT: {
    id: 387506,
    name: 'Mayhem [NYI]',
    icon: 'spell_warlock_demonbolt',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  RAIN_OF_FIRE_DESTRUCTION_TALENT: {
    id: 5740,
    name: 'Rain of Fire',
    icon: 'spell_shadow_rainoffire',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
    soulshardsCost: 3,
  },
  BACKDRAFT_DESTRUCTION_TALENT: {
    id: 196406,
    name: 'Backdraft',
    icon: 'ability_warlock_backdraft',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  INTERNAL_COMBUSTION_DESTRUCTION_TALENT: {
    id: 266134,
    name: 'Internal Combustion',
    icon: 'ability_mage_livingbomb',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  REVERSE_ENTROPY_DESTRUCTION_TALENT: {
    id: 205148,
    name: 'Reverse Entropy',
    icon: 'spell_fire_playingwithfiregreen',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  PYROGENICS_DESTRUCTION_TALENT: {
    id: 387095,
    name: 'Pyrogenics',
    icon: 'inv_jewelry_ring_65',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  IMPROVED_CONFLAGRATE_DESTRUCTION_TALENT: {
    id: 231793,
    name: 'Improved Conflagrate',
    icon: 'spell_fire_fireball',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  ROARING_BLAZE_DESTRUCTION_TALENT: {
    id: 205184,
    name: 'Roaring Blaze',
    icon: 'ability_warlock_inferno',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  COMBUSTING_ENGINE_DESTRUCTION_TALENT: {
    id: 339896,
    name: 'Combusting Engine',
    icon: 'ability_rhyolith_immolation',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  SOUL_FIRE_DESTRUCTION_TALENT: {
    id: 6353,
    name: 'Soul Fire',
    icon: 'spell_fire_firebolt',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
    manaCost: 1000,
  },
  CRY_HAVOC_DESTRUCTION_TALENT: {
    id: 387522,
    name: 'Cry Havoc',
    icon: 'inv_offhand_1h_artifactskulloferedar_d_05',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  PANDEMONIUM_DESTRUCTION_TALENT: {
    id: 387509,
    name: 'Pandemonium',
    icon: 'ability_ironmaidens_whirlofblood',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  IMPROVED_IMMOLATE_DESTRUCTION_TALENT: {
    id: 387093,
    name: 'Improved Immolate',
    icon: 'spell_fire_immolation',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  CATACLYSM_DESTRUCTION_TALENT: {
    id: 152108,
    name: 'Cataclysm',
    icon: 'achievement_zone_cataclysm',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'choice',
    manaCost: 500,
  },
  INFERNO_DESTRUCTION_TALENT: {
    id: 270545,
    name: 'Inferno',
    icon: 'spell_shadow_rainoffire',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'choice',
  },
  CHANNEL_DEMONFIRE_DESTRUCTION_TALENT: {
    id: 196447,
    name: 'Channel Demonfire',
    icon: 'spell_fire_ragnaros_lavaboltgreen',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
    manaCost: 500,
  },
  SHADOWBURN_DESTRUCTION_TALENT: {
    id: 17877,
    name: 'Shadowburn',
    icon: 'spell_shadow_scourgebuild',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
    soulshardsCost: 1,
  },
  DECIMATION_DESTRUCTION_TALENT: {
    id: 387176,
    name: 'Decimation',
    icon: 'spell_fire_firebolt',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  ROLLING_HAVOC_DESTRUCTION_TALENT: {
    id: 387569,
    name: 'Rolling Havoc',
    icon: 'warlock_pvp_banehavoc',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  FIRE_AND_BRIMSTONE_DESTRUCTION_TALENT: {
    id: 196408,
    name: 'Fire and Brimstone',
    icon: 'ability_warlock_fireandbrimstone',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  CHAOS_SHARDS_DESTRUCTION_TALENT: {
    id: 387390,
    name: 'Chaos Shards',
    icon: 'inv_misc_gem_amethyst_02',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  RAGING_DEMONFIRE_DESTRUCTION_TALENT: {
    id: 387166,
    name: 'Raging Demonfire',
    icon: 'spell_fire_ragnaros_lavaboltgreen',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  CONFLAGRATION_OF_CHAOS_DESTRUCTION_TALENT: {
    id: 387108,
    name: 'Conflagration of Chaos',
    icon: 'spell_shadow_scourgebuild',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  BACKLASH_DESTRUCTION_TALENT: {
    id: 387384,
    name: 'Backlash',
    icon: 'spell_fire_playingwithfire',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  FLASHPOINT_DESTRUCTION_TALENT: {
    id: 387259,
    name: 'Flashpoint',
    icon: 'ability_evoker_firebreath',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  RUIN_DESTRUCTION_TALENT: {
    id: 387103,
    name: 'Ruin',
    icon: 'spell_fire_fire',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  ERADICATION_DESTRUCTION_TALENT: {
    id: 196412,
    name: 'Eradication',
    icon: 'ability_warlock_eradication',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  ASHEN_REMAINS_DESTRUCTION_TALENT: {
    id: 387252,
    name: 'Ashen Remains',
    icon: 'inv_enchanting_dust',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  GRIMOIRE_OF_SACRIFICE_DESTRUCTION_TALENT: {
    id: 108503,
    name: 'Grimoire of Sacrifice',
    icon: 'warlock_grimoireofsacrifice',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  SUMMON_INFERNAL_DESTRUCTION_TALENT: {
    id: 1122,
    name: 'Summon Infernal',
    icon: 'spell_shadow_summoninfernal',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
    manaCost: 1000,
  },
  EMBERS_OF_THE_DIABOLIC_DESTRUCTION_TALENT: {
    id: 387173,
    name: 'Embers of the Diabolic',
    icon: 'inv_shoulder_robe_raidmage_j_01',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  RITUAL_OF_RUIN_DESTRUCTION_TALENT: {
    id: 387156,
    name: 'Ritual of Ruin',
    icon: 'spell_fire_twilightrainoffire',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  CRASHING_CHAOS_DESTRUCTION_TALENT: {
    id: 387355,
    name: 'Crashing Chaos',
    icon: 'inv_infernalmount',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  INFERNAL_BRAND_DESTRUCTION_TALENT: {
    id: 387475,
    name: 'Infernal Brand',
    icon: 'warlock_pvp_burninglegion',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  POWER_OVERWHELMING_DESTRUCTION_TALENT: {
    id: 387279,
    name: 'Power Overwhelming',
    icon: 'ability_warlock_improvedsoulleech',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  MADNESS_OF_THE_AZJAQIR_DESTRUCTION_TALENT: {
    id: 387400,
    name: "Madness of the Azj'Aqir",
    icon: 'inv_eyeofnzothpet',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  MASTER_RITUALIST_DESTRUCTION_TALENT: {
    id: 387165,
    name: 'Master Ritualist',
    icon: 'spell_warlock_focusshadow',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  BURN_TO_ASHES_DESTRUCTION_TALENT: {
    id: 387153,
    name: 'Burn to Ashes',
    icon: 'ability_racial_foregedinflames',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  WILFREDS_SIGIL_OF_SUPERIOR_SUMMONING_DESTRUCTION_TALENT: {
    id: 387084,
    name: "Wilfred's Sigil of Superior Summoning",
    icon: 'spell_warlock_demonicportal_purple',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  RAIN_OF_CHAOS_DESTRUCTION_TALENT: {
    id: 266086,
    name: 'Rain of Chaos',
    icon: 'spell_fire_felrainoffire',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  CHAOS_INCARNATE_DESTRUCTION_TALENT: {
    id: 387275,
    name: 'Chaos Incarnate',
    icon: 'spell_fire_felflamering',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  AVATAR_OF_DESTRUCTION_DESTRUCTION_TALENT: {
    id: 387159,
    name: 'Avatar of Destruction',
    icon: 'inv_infernalmountblue',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },

  //Affliction
  MALEFIC_RAPTURE_AFFLICTION_TALENT: {
    id: 324536,
    name: 'Malefic Rapture',
    icon: 'ability_warlock_everlastingaffliction',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
    soulshardsCost: 1,
  },
  UNSTABLE_AFFLICTION_AFFLICTION_TALENT: {
    id: 316099,
    name: 'Unstable Affliction',
    icon: 'spell_shadow_unstableaffliction_3',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
    manaCost: 500,
  },
  SEED_OF_CORRUPTION_AFFLICTION_TALENT: {
    id: 27243,
    name: 'Seed of Corruption',
    icon: 'spell_shadow_seedofdestruction',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
    soulshardsCost: 1,
  },
  NIGHTFALL_AFFLICTION_TALENT: {
    id: 108558,
    name: 'Nightfall',
    icon: 'spell_shadow_twilight',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  XAVIAN_TEACHINGS_AFFLICTION_TALENT: {
    id: 317031,
    name: 'Xavian Teachings',
    icon: 'spell_shadow_abominationexplosion',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  SOW_THE_SEEDS_AFFLICTION_TALENT: {
    id: 196226,
    name: 'Sow the Seeds',
    icon: 'spell_shadow_seedofdestruction',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  INEVITABLE_DEMISE_AFFLICTION_TALENT: {
    id: 334319,
    name: 'Inevitable Demise',
    icon: 'spell_warlock_harvestoflife',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  PANDEMIC_INVOCATION_AFFLICTION_TALENT: {
    id: 386759,
    name: 'Pandemic Invocation',
    icon: 'spell_shadow_unsummonbuilding',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  WRITHE_IN_AGONY_AFFLICTION_TALENT: {
    id: 196102,
    name: 'Writhe in Agony',
    icon: 'spell_shadow_curseofsargeras',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  AGONIZING_CORRUPTION_AFFLICTION_TALENT: {
    id: 386922,
    name: 'Agonizing Corruption',
    icon: 'spell_warlock_darkregeneration',
    maxRanks: 2,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  DRAIN_SOUL_AFFLICTION_TALENT: {
    id: 198590,
    name: 'Drain Soul',
    icon: 'spell_shadow_haunting',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
    manaCost: 0,
  },
  ABSOLUTE_CORRUPTION_AFFLICTION_TALENT: {
    id: 196103,
    name: 'Absolute Corruption',
    icon: 'ability_bossmannoroth_empoweredmannorothsgaze',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
  },
  SIPHON_LIFE_AFFLICTION_TALENT: {
    id: 63106,
    name: 'Siphon Life',
    icon: 'spell_shadow_requiem',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'choice',
    manaCost: 500,
  },
  VILE_TAINT_AFFLICTION_TALENT: {
    id: 278350,
    name: 'Vile Taint',
    icon: 'sha_spell_shadow_shadesofdarkness_nightborne',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
    soulshardsCost: 1,
  },
  PHANTOM_SINGULARITY_AFFLICTION_TALENT: {
    id: 205179,
    name: 'Phantom Singularity',
    icon: 'inv_enchant_voidsphere',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'choice',
    manaCost: 500,
  },
  SOUL_TAP_AFFLICTION_TALENT: {
    id: 387073,
    name: 'Soul Tap',
    icon: 'spell_shadow_burningspirit',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  SHADOW_EMBRACE_AFFLICTION_TALENT: {
    id: 32388,
    name: 'Shadow Embrace',
    icon: 'spell_shadow_shadowembrace',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  GRIMOIRE_OF_SACRIFICE_AFFLICTION_TALENT: {
    id: 108503,
    name: 'Grimoire of Sacrifice',
    icon: 'warlock_grimoireofsacrifice',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  SOUL_FLAME_AFFLICTION_TALENT: {
    id: 199471,
    name: 'Soul Flame',
    icon: 'achievement_firelands_raid_ragnaros',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  SOUL_SWAP_AFFLICTION_TALENT: {
    id: 386951,
    name: 'Soul Swap',
    icon: 'ability_warlock_soulswap',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
    soulshardsCost: 1,
  },
  HARVESTER_OF_SOULS_AFFLICTION_TALENT: {
    id: 201424,
    name: 'Harvester of Souls',
    icon: 'warlock_spelldrain',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  WITHERING_BOLT_AFFLICTION_TALENT: {
    id: 386976,
    name: 'Withering Bolt',
    icon: 'spell_shadow_shadowbolt',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  SACROLASHS_DARK_STRIKE_AFFLICTION_TALENT: {
    id: 386986,
    name: "Sacrolash's Dark Strike",
    icon: 'spell_nzinsanity_fearofdeath',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  DEATHBOLT_AFFLICTION_TALENT: {
    id: 264106,
    name: 'Deathbolt',
    icon: 'spell_fire_twilightflamebolt',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
    soulshardsCost: 3,
  },
  SOUL_ROT_AFFLICTION_TALENT: {
    id: 386997,
    name: 'Soul Rot',
    icon: 'ability_ardenweald_warlock',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
    manaCost: 0,
  },
  HAUNT_AFFLICTION_TALENT: {
    id: 48181,
    name: 'Haunt',
    icon: 'ability_warlock_haunt',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
    manaCost: 1000,
  },
  SUMMON_DARKGLARE_AFFLICTION_TALENT: {
    id: 205180,
    name: 'Summon Darkglare',
    icon: 'inv_beholderwarlock',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
    manaCost: 1000,
  },
  DEATH_DEALER_AFFLICTION_TALENT: {
    id: 387223,
    name: 'Death Dealer',
    icon: 'spell_shadow_fingerofdeath',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  MALEFIC_WRATH_AFFLICTION_TALENT: {
    id: 387013,
    name: 'Malefic Wrath',
    icon: 'spell_shadow_soulleech_3',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  DECAYING_SOUL_SATCHEL_AFFLICTION_TALENT: {
    id: 387016,
    name: 'Decaying Soul Satchel',
    icon: 'spell_misc_zandalari_council_soulswap',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  DELIBERATE_MALICE_AFFLICTION_TALENT: {
    id: 387056,
    name: 'Deliberate Malice',
    icon: 'spell_priest_shadow_mend',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  SEIZED_VITALITY_AFFLICTION_TALENT: {
    id: 387250,
    name: 'Seized Vitality',
    icon: 'spell_shadow_skull',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  WRATH_OF_CONSUMPTION_AFFLICTION_TALENT: {
    id: 387065,
    name: 'Wrath of Consumption',
    icon: 'spell_nature_drowsy',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  ANTORAN_PLATING_AFFLICTION_TALENT: {
    id: 387273,
    name: 'Antoran Plating',
    icon: 'inv_antorus_grey',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  PACT_OF_THE_NATHREZIM_AFFLICTION_TALENT: {
    id: 387289,
    name: 'Pact of the Nathrezim',
    icon: 'achievement_thenighthold_tichondrius',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  CREEPING_DEATH_AFFLICTION_TALENT: {
    id: 264000,
    name: 'Creeping Death',
    icon: 'ability_creature_cursed_03',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  CALAMITOUS_CRESCENDO_AFFLICTION_TALENT: {
    id: 387075,
    name: 'Calamitous Crescendo',
    icon: 'spell_warlock_soulburn',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  HAUNTED_SOUL_AFFLICTION_TALENT: {
    id: 387301,
    name: 'Haunted Soul',
    icon: 'spell_warlock_soulburn_haunt',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  WILFREDS_SIGIL_OF_SUPERIOR_SUMMONING_AFFLICTION_TALENT: {
    id: 337020,
    name: "Wilfred's Sigil of Superior Summoning",
    icon: 'spell_warlock_demonicportal_purple',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },

  //Demonology
  CALL_DREADSTALKERS_DEMONOLOGY_TALENT: {
    id: 104316,
    name: 'Call Dreadstalkers',
    icon: 'spell_warlock_calldreadstalkers',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
    soulshardsCost: 2,
  },
  DEMONBOLT_DEMONOLOGY_TALENT: {
    id: 264178,
    name: 'Demonbolt',
    icon: 'inv__demonbolt',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
    manaCost: 1000,
  },
  DREADLASH_DEMONOLOGY_TALENT: {
    id: 264078,
    name: 'Dreadlash',
    icon: 'spell_shadow_summonvoidwalker',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  FEL_COMMANDO_DEMONOLOGY_TALENT: {
    id: 386174,
    name: 'Fel Commando',
    icon: 'spell_warlock_summonwrathguard',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  SHADOWS_BITE_DEMONOLOGY_TALENT: {
    id: 387322,
    name: "Shadow's Bite",
    icon: 'spell_shadow_painspike',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  SOUL_STRIKE_DEMONOLOGY_TALENT: {
    id: 264057,
    name: 'Soul Strike',
    icon: 'inv_polearm_2h_fellord_04',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'choice',
  },
  SUMMON_VILEFIEND_DEMONOLOGY_TALENT: {
    id: 264119,
    name: 'Summon Vilefiend',
    icon: 'inv_argusfelstalkermount',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'choice',
    soulshardsCost: 1,
  },
  DEMONIC_STRENGTH_DEMONOLOGY_TALENT: {
    id: 267171,
    name: 'Demonic Strength',
    icon: 'ability_warlock_demonicempowerment',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'choice',
  },
  BILESCOURGE_BOMBERS_DEMONOLOGY_TALENT: {
    id: 267211,
    name: 'Bilescourge Bombers',
    icon: 'ability_hunter_pet_bat',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'choice',
    soulshardsCost: 2,
  },
  FROM_THE_SHADOWS_DEMONOLOGY_TALENT: {
    id: 267170,
    name: 'From the Shadows',
    icon: 'spell_warlock_calldreadstalkers',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  IMPLOSION_DEMONOLOGY_TALENT: {
    id: 196277,
    name: 'Implosion',
    icon: 'inv_implosion',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'active',
    talentType: 'single',
    manaCost: 1000,
  },
  BORNE_OF_BLOOD_DEMONOLOGY_TALENT: {
    id: 386185,
    name: 'Borne of Blood',
    icon: 'ability_warlock_improveddemonictactics',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  CARNIVOROUS_STALKERS_DEMONOLOGY_TALENT: {
    id: 386194,
    name: 'Carnivorous Stalkers',
    icon: 'warlock_pvp_callfelhunter',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  FEL_AND_STEEL_DEMONOLOGY_TALENT: {
    id: 386200,
    name: 'Fel and Steel',
    icon: 'ability_creature_poison_01',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  FEL_MIGHT_DEMONOLOGY_TALENT: {
    id: 387338,
    name: 'Fel Might',
    icon: 'ability_bossfelmagnaron_hand',
    maxRanks: 1,
    reqPoints: 0,
    spellType: 'passive',
    talentType: 'single',
  },
  POWER_SIPHON_DEMONOLOGY_TALENT: {
    id: 264130,
    name: 'Power Siphon',
    icon: 'ability_warlock_backdraft',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
  },
  INNER_DEMONS_DEMONOLOGY_TALENT: {
    id: 267216,
    name: 'Inner Demons',
    icon: 'ability_warlock_eradication',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  DEMONIC_CALLING_DEMONOLOGY_TALENT: {
    id: 205145,
    name: 'Demonic Calling',
    icon: 'ability_warlock_impoweredimp',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  GRIMOIRE_FELGUARD_DEMONOLOGY_TALENT: {
    id: 111898,
    name: 'Grimoire: Felguard',
    icon: 'spell_shadow_summonfelguard',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
    soulshardsCost: 1,
  },
  BLOODBOUND_IMPS_DEMONOLOGY_TALENT: {
    id: 387349,
    name: 'Bloodbound Imps',
    icon: 'inv_misc_skullfel_06',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  GRIM_INQUISITORS_DREAD_CALLING_DEMONOLOGY_TALENT: {
    id: 387391,
    name: "Grim Inquisitor's Dread Calling",
    icon: 'spell_warlock_calldreadstalkers',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  DOOM_DEMONOLOGY_TALENT: {
    id: 603,
    name: 'Doom',
    icon: 'spell_shadow_auraofdarkness',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'active',
    talentType: 'single',
    manaCost: 500,
  },
  DEMONIC_METEOR_DEMONOLOGY_TALENT: {
    id: 387396,
    name: 'Demonic Meteor',
    icon: 'ability_warlock_handofguldan',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  FEL_SUNDER_DEMONOLOGY_TALENT: {
    id: 387399,
    name: 'Fel Sunder',
    icon: 'ability_creature_felsunder',
    maxRanks: 1,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  BALESPIDERS_BURNING_CORE_DEMONOLOGY_TALENT: {
    id: 387432,
    name: "Balespider's Burning Core",
    icon: 'inv_trinket_firelands_02',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  IMP_GANG_BOSS_DEMONOLOGY_TALENT: {
    id: 387445,
    name: 'Imp Gang Boss',
    icon: 'ability_warlock_empoweredimp',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  KAZAAKS_FINAL_CURSE_DEMONOLOGY_TALENT: {
    id: 387483,
    name: "Kazaak's Final Curse",
    icon: 'inv_feldreadravenmount',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  RIPPED_THROUGH_THE_PORTAL_DEMONOLOGY_TALENT: {
    id: 387485,
    name: 'Ripped through the Portal',
    icon: 'spell_shadow_summonfelhunter',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  HOUNDMASTERS_GAMBIT_DEMONOLOGY_TALENT: {
    id: 387488,
    name: "Houndmaster's Gambit",
    icon: 'achievement_boss_hellfire_fellord',
    maxRanks: 2,
    reqPoints: 8,
    spellType: 'passive',
    talentType: 'single',
  },
  NETHER_PORTAL_DEMONOLOGY_TALENT: {
    id: 267217,
    name: 'Nether Portal',
    icon: 'inv_netherportal',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
    soulshardsCost: 1,
  },
  SUMMON_DEMONIC_TYRANT_DEMONOLOGY_TALENT: {
    id: 265187,
    name: 'Summon Demonic Tyrant',
    icon: 'inv_summondemonictyrant',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
    manaCost: 1000,
  },
  ANTORAN_ARMAMENTS_DEMONOLOGY_TALENT: {
    id: 387494,
    name: 'Antoran Armaments',
    icon: 'inv_axe_1h_felfireraid_d_01',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  NERZHULS_VOLITION_DEMONOLOGY_TALENT: {
    id: 387526,
    name: "Ner'zhul's Volition",
    icon: 'achievement_dungeon_shadowmoonhideout',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  SACRIFICED_SOULS_DEMONOLOGY_TALENT: {
    id: 267214,
    name: 'Sacrificed Souls',
    icon: 'ability_creature_disease_05',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  SOULBOUND_TYRANT_DEMONOLOGY_TALENT: {
    id: 334585,
    name: 'Soulbound Tyrant',
    icon: 'inv_summondemonictyrant',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  FORCES_OF_THE_HORNED_NIGHTMARE_DEMONOLOGY_TALENT: {
    id: 387541,
    name: 'Forces of the Horned Nightmare',
    icon: 'ability_warlock_handofguldan',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  COMMAND_AURA_DEMONOLOGY_TALENT: {
    id: 387549,
    name: 'Command Aura',
    icon: 'ability_bossdarkvindicator_auraofcontempt',
    maxRanks: 2,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  GULDANS_AMBITION_DEMONOLOGY_TALENT: {
    id: 387578,
    name: "Gul'dan's Ambition",
    icon: 'achievement_dungeon_outland_dungeonmaster',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  THE_EXPENDABLES_DEMONOLOGY_TALENT: {
    id: 387600,
    name: 'The Expendables',
    icon: 'ability_warlock_impoweredimp',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  WILFREDS_SIGIL_OF_SUPERIOR_SUMMONING_DEMONOLOGY_TALENT: {
    id: 337020,
    name: "Wilfred's Sigil of Superior Summoning",
    icon: 'spell_warlock_demonicportal_purple',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  DEMONIC_CONSUMPTION_DEMONOLOGY_TALENT: {
    id: 267215,
    name: 'Demonic Consumption',
    icon: 'spell_warlock_soulburn',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'choice',
  },
  STOLEN_POWER_DEMONOLOGY_TALENT: {
    id: 387602,
    name: 'Stolen Power',
    icon: 'ability_bossfelmagnaron_waveempowered',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'passive',
    talentType: 'single',
  },
  HOLD_THIS_FOR_ME_NYI_DEMONOLOGY_TALENT: {
    id: 386833,
    name: 'Hold This For Me [NYI]',
    icon: 'inv_axe_2h_felfireraid_d_01',
    maxRanks: 1,
    reqPoints: 20,
    spellType: 'active',
    talentType: 'single',
  },
});

export default talents;
export { talents as TALENTS_WARLOCK };
