// Generated file, changes will eventually be overwritten!
import { createTalentList } from './types';

const talents = createTalentList({
  BERSERKER_STANCE_TALENT: {
    id: 386196,
    name: 'Berserker Stance',
    icon: 'ability_racial_avatar',
    maxRanks: 1,
    entryIds: [112182],
  },
  DEFENSIVE_STANCE_TALENT: {
    id: 386208,
    name: 'Defensive Stance',
    icon: 'ability_warrior_defensivestance',
    maxRanks: 1,
    entryIds: [114644, 112187, 114643],
  },
  BERSERKER_RAGE_TALENT: {
    id: 18499,
    name: 'Berserker Rage',
    icon: 'spell_nature_ancestralguardian',
    maxRanks: 1,
    entryIds: [112239],
  },
  IMPENDING_VICTORY_TALENT: {
    id: 202168,
    name: 'Impending Victory',
    icon: 'spell_impending_victory',
    maxRanks: 1,
    entryIds: [112183],
    rageCost: 10,
  },
  WAR_MACHINE_FURY_TALENT: {
    id: 346002,
    name: 'War Machine',
    icon: 'ability_hunter_rapidkilling',
    maxRanks: 1,
    entryIds: [112254],
  },
  WAR_MACHINE_PROTECTION_TALENT: {
    id: 316733,
    name: 'War Machine',
    icon: 'ability_hunter_rapidkilling',
    maxRanks: 1,
    entryIds: [112207],
  },
  WAR_MACHINE_ARMS_TALENT: {
    id: 262231,
    name: 'War Machine',
    icon: 'ability_hunter_rapidkilling',
    maxRanks: 1,
    entryIds: [112185],
  },
  INTERVENE_TALENT: {
    id: 3411,
    name: 'Intervene',
    icon: 'ability_warrior_victoryrush',
    maxRanks: 1,
    entryIds: [112186],
  },
  RALLYING_CRY_TALENT: {
    id: 97462,
    name: 'Rallying Cry',
    icon: 'ability_warrior_rallyingcry',
    maxRanks: 1,
    entryIds: [112188],
  },
  BERSERKER_SHOUT_TALENT: {
    id: 384100,
    name: 'Berserker Shout',
    icon: 'spell_nature_ancestralguardian',
    maxRanks: 1,
    entryIds: [112211],
  },
  PIERCING_HOWL_TALENT: {
    id: 12323,
    name: 'Piercing Howl',
    icon: 'spell_shadow_deathscream',
    maxRanks: 1,
    entryIds: [112210],
  },
  FAST_FOOTWORK_TALENT: {
    id: 382260,
    name: 'Fast Footwork',
    icon: 'ability_hunter_posthaste',
    maxRanks: 1,
    entryIds: [112238],
  },
  SPELL_REFLECTION_TALENT: {
    id: 23920,
    name: 'Spell Reflection',
    icon: 'ability_warrior_shieldreflection',
    maxRanks: 1,
    entryIds: [112253],
  },
  LEECHING_STRIKES_TALENT: {
    id: 382258,
    name: 'Leeching Strikes',
    icon: 'inv_artifact_bloodoftheassassinated',
    maxRanks: 1,
    entryIds: [112206],
  },
  INSPIRING_PRESENCE_TALENT: {
    id: 382310,
    name: 'Inspiring Presence',
    icon: 'ability_toughness',
    maxRanks: 1,
    entryIds: [112190],
  },
  SECOND_WIND_TALENT: {
    id: 29838,
    name: 'Second Wind',
    icon: 'ability_hunter_harass',
    maxRanks: 1,
    entryIds: [112189],
  },
  FROTHING_BERSERKER_FURY_TALENT: {
    id: 215571,
    name: 'Frothing Berserker',
    icon: 'warrior_talent_icon_furyintheblood',
    maxRanks: 1,
    entryIds: [112213],
  },
  FROTHING_BERSERKER_PROTECTION_TALENT: {
    id: 392790,
    name: 'Frothing Berserker',
    icon: 'warrior_talent_icon_furyintheblood',
    maxRanks: 1,
    entryIds: [112237],
  },
  FROTHING_BERSERKER_ARMS_TALENT: {
    id: 392792,
    name: 'Frothing Berserker',
    icon: 'warrior_talent_icon_furyintheblood',
    maxRanks: 1,
    entryIds: [112216],
  },
  HEROIC_LEAP_TALENT: {
    id: 6544,
    name: 'Heroic Leap',
    icon: 'ability_heroicleap',
    maxRanks: 1,
    entryIds: [112208],
  },
  INTIMIDATING_SHOUT_TALENT: {
    id: 5246,
    name: 'Intimidating Shout',
    icon: 'ability_golemthunderclap',
    maxRanks: 1,
    entryIds: [112252],
  },
  THUNDER_CLAP_SHARED_TALENT: {
    id: 396719,
    name: 'Thunder Clap',
    icon: 'spell_nature_thunderclap',
    maxRanks: 1,
    entryIds: [114295, 114296],
    rageCost: 30,
  },
  THUNDER_CLAP_PROTECTION_TALENT: {
    id: 6343,
    name: 'Thunder Clap',
    icon: 'spell_nature_thunderclap',
    maxRanks: 1,
    entryIds: [112205],
  },
  FURIOUS_BLOWS_TALENT: {
    id: 390354,
    name: 'Furious Blows',
    icon: 'ability_ghoulfrenzy',
    maxRanks: 1,
    entryIds: [112197],
  },
  WRECKING_THROW_TALENT: {
    id: 384110,
    name: 'Wrecking Throw',
    icon: 'warrior_talent_icon_mastercleaver',
    maxRanks: 1,
    entryIds: [112215],
  },
  SHATTERING_THROW_TALENT: {
    id: 64382,
    name: 'Shattering Throw',
    icon: 'ability_warrior_shatteringthrow',
    maxRanks: 1,
    entryIds: [112214],
  },
  CRUSHING_FORCE_SHARED_TALENT: {
    id: 382764,
    name: 'Crushing Force',
    icon: 'spell_shadow_unholystrength',
    maxRanks: 2,
    entryIds: [112212, 112209],
  },
  CRUSHING_FORCE_PROTECTION_TALENT: {
    id: 390642,
    name: 'Crushing Force',
    icon: 'spell_shadow_unholystrength',
    maxRanks: 2,
    entryIds: [112236],
  },
  PAIN_AND_GAIN_TALENT: {
    id: 382549,
    name: 'Pain and Gain',
    icon: 'spell_holy_painsupression',
    maxRanks: 1,
    entryIds: [112217],
  },
  CACOPHONOUS_ROAR_TALENT: {
    id: 382954,
    name: 'Cacophonous Roar',
    icon: 'ability_fomor_boss_shout',
    maxRanks: 1,
    entryIds: [112251],
  },
  MENACE_TALENT: {
    id: 275338,
    name: 'Menace',
    icon: 'ability_golemthunderclap',
    maxRanks: 1,
    entryIds: [112250],
  },
  STORM_BOLT_TALENT: {
    id: 107570,
    name: 'Storm Bolt',
    icon: 'warrior_talent_icon_stormbolt',
    maxRanks: 1,
    entryIds: [112198],
  },
  OVERWHELMING_RAGE_TALENT: {
    id: 382767,
    name: 'Overwhelming Rage',
    icon: 'racial_orc_berserkerstrength',
    maxRanks: 2,
    entryIds: [112245],
  },
  SIDEARM_TALENT: {
    id: 384404,
    name: 'Sidearm',
    icon: 'inv_throwingaxe_06',
    maxRanks: 1,
    entryIds: [112196, 112194, 112192],
  },
  CONCUSSIVE_BLOWS_TALENT: {
    id: 383115,
    name: 'Concussive Blows',
    icon: 'ability_warrior_intervene',
    maxRanks: 1,
    entryIds: [112195, 112193, 112191],
  },
  REINFORCED_PLATES_TALENT: {
    id: 382939,
    name: 'Reinforced Plates',
    icon: 'inv_chest_plate04',
    maxRanks: 1,
    entryIds: [112235],
  },
  BOUNDING_STRIDE_TALENT: {
    id: 202163,
    name: 'Bounding Stride',
    icon: 'ability_heroicleap',
    maxRanks: 1,
    entryIds: [112219],
  },
  BLOOD_AND_THUNDER_TALENT: {
    id: 384277,
    name: 'Blood and Thunder',
    icon: 'warrior_talent_icon_bloodandthunder',
    maxRanks: 1,
    entryIds: [112204],
  },
  CRACKLING_THUNDER_TALENT: {
    id: 203201,
    name: 'Crackling Thunder',
    icon: 'ability_thunderking_overcharge',
    maxRanks: 1,
    entryIds: [112203],
  },
  BARBARIC_TRAINING_FURY_TALENT: {
    id: 390674,
    name: 'Barbaric Training',
    icon: 'ability_garrosh_whirling_corruption',
    maxRanks: 1,
    entryIds: [114294],
  },
  BARBARIC_TRAINING_PROTECTION_TALENT: {
    id: 390675,
    name: 'Barbaric Training',
    icon: 'ability_garrosh_whirling_corruption',
    maxRanks: 1,
    entryIds: [112244],
  },
  BARBARIC_TRAINING_ARMS_TALENT: {
    id: 383082,
    name: 'Barbaric Training',
    icon: 'ability_garrosh_whirling_corruption',
    maxRanks: 1,
    entryIds: [114293],
  },
  HONED_REFLEXES_FURY_TALENT: {
    id: 391270,
    name: 'Honed Reflexes',
    icon: 'spell_holy_borrowedtime',
    maxRanks: 1,
    entryIds: [112234],
  },
  HONED_REFLEXES_PROTECTION_TALENT: {
    id: 391271,
    name: 'Honed Reflexes',
    icon: 'spell_holy_borrowedtime',
    maxRanks: 1,
    entryIds: [112225],
  },
  HONED_REFLEXES_ARMS_TALENT: {
    id: 382461,
    name: 'Honed Reflexes',
    icon: 'spell_holy_borrowedtime',
    maxRanks: 1,
    entryIds: [112218],
  },
  BITTER_IMMUNITY_TALENT: {
    id: 383762,
    name: 'Bitter Immunity',
    icon: 'spell_nature_shamanrage',
    maxRanks: 1,
    entryIds: [112220],
  },
  DOUBLE_TIME_TALENT: {
    id: 103827,
    name: 'Double Time',
    icon: 'inv_misc_horn_04',
    maxRanks: 1,
    entryIds: [112249],
  },
  TITANIC_THROW_TALENT: {
    id: 384090,
    name: 'Titanic Throw',
    icon: 'inv_axe_66',
    maxRanks: 1,
    entryIds: [112202],
  },
  SEISMIC_REVERBERATION_TALENT: {
    id: 382956,
    name: 'Seismic Reverberation',
    icon: 'ability_warrior_bloodnova',
    maxRanks: 1,
    entryIds: [112201],
  },
  ARMORED_TO_THE_TEETH_SHARED_TALENT: {
    id: 384124,
    name: 'Armored to the Teeth',
    icon: 'inv_shoulder_22',
    maxRanks: 2,
    entryIds: [112108, 112233],
  },
  ARMORED_TO_THE_TEETH_PROTECTION_TALENT: {
    id: 394855,
    name: 'Armored to the Teeth',
    icon: 'inv_shoulder_22',
    maxRanks: 2,
    entryIds: [112109],
  },
  WILD_STRIKES_TALENT: {
    id: 382946,
    name: 'Wild Strikes',
    icon: 'ability_rogue_sprint',
    maxRanks: 2,
    entryIds: [112224],
  },
  DUAL_WIELD_SPECIALIZATION_TALENT: {
    id: 382900,
    name: 'Dual Wield Specialization',
    icon: 'ability_dualwield',
    maxRanks: 1,
    entryIds: [112240],
  },
  CRUEL_STRIKES_TALENT: {
    id: 392777,
    name: 'Cruel Strikes',
    icon: 'ability_criticalstrike',
    maxRanks: 2,
    entryIds: [112248],
  },
  ENDURANCE_TRAINING_FURY_TALENT: {
    id: 391997,
    name: 'Endurance Training',
    icon: 'spell_nature_unyeildingstamina',
    maxRanks: 1,
    entryIds: [112243],
  },
  ENDURANCE_TRAINING_SHARED_TALENT: {
    id: 382940,
    name: 'Endurance Training',
    icon: 'spell_nature_unyeildingstamina',
    maxRanks: 1,
    entryIds: [112200, 112199],
  },
  AVATAR_SHARED_TALENT: {
    id: 107574,
    name: 'Avatar',
    icon: 'warrior_talent_icon_avatar',
    maxRanks: 1,
    entryIds: [114770, 112232],
  },
  AVATAR_PROTECTION_TALENT: {
    id: 401150,
    name: 'Avatar',
    icon: 'warrior_talent_icon_avatar',
    maxRanks: 1,
    entryIds: [114769],
  },
  THUNDEROUS_ROAR_TALENT: {
    id: 384318,
    name: 'Thunderous Roar',
    icon: 'ability_warrior_dragonroar',
    maxRanks: 1,
    entryIds: [112223],
  },
  SPEAR_OF_BASTION_TALENT: {
    id: 376079,
    name: 'Spear of Bastion',
    icon: 'ability_bastion_warrior',
    maxRanks: 1,
    entryIds: [112247],
  },
  SHOCKWAVE_TALENT: {
    id: 46968,
    name: 'Shockwave',
    icon: 'ability_warrior_shockwave',
    maxRanks: 1,
    entryIds: [112242],
  },
  BERSERKERS_TORMENT_TALENT: {
    id: 390123,
    name: "Berserker's Torment",
    icon: 'ability_warrior_innerrage',
    maxRanks: 1,
    entryIds: [112227],
  },
  TITANS_TORMENT_TALENT: {
    id: 390135,
    name: "Titan's Torment",
    icon: '70_inscription_vantus_rune_odyn',
    maxRanks: 1,
    entryIds: [112226],
  },
  UPROAR_TALENT: {
    id: 391572,
    name: 'Uproar',
    icon: 'inv_misc_head_dragon_01',
    maxRanks: 1,
    entryIds: [112221],
  },
  THUNDEROUS_WORDS_TALENT: {
    id: 384969,
    name: 'Thunderous Words',
    icon: 'spell_nature_earthquake',
    maxRanks: 1,
    entryIds: [112222],
  },
  PIERCING_VERDICT_TALENT: {
    id: 382948,
    name: 'Piercing Verdict',
    icon: 'spell_animabastion_missile',
    maxRanks: 1,
    entryIds: [112246],
  },
  ELYSIAN_MIGHT_TALENT: {
    id: 386285,
    name: 'Elysian Might',
    icon: 'ability_bastion_warrior',
    maxRanks: 1,
    entryIds: [112180],
  },
  RUMBLING_EARTH_TALENT: {
    id: 275339,
    name: 'Rumbling Earth',
    icon: 'spell_shaman_earthquake',
    maxRanks: 1,
    entryIds: [112241],
  },
  SONIC_BOOM_TALENT: {
    id: 390725,
    name: 'Sonic Boom',
    icon: 'spell_nature_unrelentingstorm',
    maxRanks: 1,
    entryIds: [112178],
  },
  BATTLE_STANCE_TALENT: {
    id: 386164,
    name: 'Battle Stance',
    icon: 'ability_warrior_offensivestance',
    maxRanks: 1,
    entryIds: [112112, 112184],
  },
  ONE_HANDED_WEAPON_SPECIALIZATION_TALENT: {
    id: 382895,
    name: 'One-Handed Weapon Specialization',
    icon: 'inv_sword_20',
    maxRanks: 1,
    entryIds: [112181],
  },
  IMMOVABLE_OBJECT_TALENT: {
    id: 394307,
    name: 'Immovable Object',
    icon: 'spell_frost_chillingarmor',
    maxRanks: 1,
    entryIds: [112231],
  },
  UNSTOPPABLE_FORCE_TALENT: {
    id: 275336,
    name: 'Unstoppable Force',
    icon: 'warrior_talent_icon_thunderstruck',
    maxRanks: 1,
    entryIds: [112230],
  },
  TWO_HANDED_WEAPON_SPECIALIZATION_TALENT: {
    id: 382896,
    name: 'Two-Handed Weapon Specialization',
    icon: 'inv_axe_09',
    maxRanks: 1,
    entryIds: [112179],
  },
  BLADEMASTERS_TORMENT_TALENT: {
    id: 390138,
    name: "Blademaster's Torment",
    icon: 'spell_nature_mirrorimage',
    maxRanks: 1,
    entryIds: [112229],
  },
  WARLORDS_TORMENT_TALENT: {
    id: 390140,
    name: "Warlord's Torment",
    icon: 'warrior_talent_icon_innerrage',
    maxRanks: 1,
    entryIds: [112228],
  },
  BLOODTHIRST_TALENT: {
    id: 23881,
    name: 'Bloodthirst',
    icon: 'spell_nature_bloodlust',
    maxRanks: 1,
    entryIds: [112261],
  },
  RAGING_BLOW_TALENT: {
    id: 85288,
    name: 'Raging Blow',
    icon: 'warrior_wild_strike',
    maxRanks: 1,
    entryIds: [112265],
  },
  IMPROVED_ENRAGE_TALENT: {
    id: 383848,
    name: 'Improved Enrage',
    icon: 'spell_shadow_unholyfrenzy',
    maxRanks: 1,
    entryIds: [112267],
  },
  ENRAGED_REGENERATION_TALENT: {
    id: 184364,
    name: 'Enraged Regeneration',
    icon: 'ability_warrior_focusedrage',
    maxRanks: 1,
    entryIds: [112264],
  },
  IMPROVED_EXECUTE_FURY_TALENT: {
    id: 316402,
    name: 'Improved Execute',
    icon: 'inv_sword_48',
    maxRanks: 1,
    entryIds: [112301],
  },
  IMPROVED_EXECUTE_ARMS_TALENT: {
    id: 316405,
    name: 'Improved Execute',
    icon: 'inv_sword_48',
    maxRanks: 1,
    entryIds: [112125],
  },
  IMPROVED_BLOODTHIRST_TALENT: {
    id: 383852,
    name: 'Improved Bloodthirst',
    icon: 'spell_nature_bloodlust',
    maxRanks: 1,
    entryIds: [112266],
  },
  FRESH_MEAT_TALENT: {
    id: 215568,
    name: 'Fresh Meat',
    icon: 'ability_deathwing_bloodcorruption_death',
    maxRanks: 1,
    entryIds: [112268],
  },
  WARPAINT_TALENT: {
    id: 208154,
    name: 'Warpaint',
    icon: 'ability_rogue_preparation',
    maxRanks: 1,
    entryIds: [112263],
  },
  INVIGORATING_FURY_TALENT: {
    id: 383468,
    name: 'Invigorating Fury',
    icon: 'spell_misc_emotionangry',
    maxRanks: 1,
    entryIds: [112262],
  },
  SUDDEN_DEATH_FURY_TALENT: {
    id: 280721,
    name: 'Sudden Death',
    icon: 'ability_warrior_improveddisciplines',
    maxRanks: 1,
    entryIds: [112300],
  },
  SUDDEN_DEATH_SPEC_TALENT: {
    id: 29725,
    name: 'Sudden Death',
    icon: 'ability_warrior_improveddisciplines',
    maxRanks: 1,
    entryIds: [112111, 112126],
  },
  IMPROVED_RAGING_BLOW_TALENT: {
    id: 383854,
    name: 'Improved Raging Blow',
    icon: 'warrior_wild_strike',
    maxRanks: 1,
    entryIds: [112259],
  },
  FOCUS_IN_CHAOS_TALENT: {
    id: 383486,
    name: 'Focus in Chaos',
    icon: 'ability_hunter_mastermarksman',
    maxRanks: 1,
    entryIds: [112272],
  },
  RAMPAGE_TALENT: {
    id: 184367,
    name: 'Rampage',
    icon: 'ability_warrior_rampage',
    maxRanks: 1,
    entryIds: [112277],
    rageCost: 80,
  },
  CRUELTY_TALENT: {
    id: 392931,
    name: 'Cruelty',
    icon: 'spell_nature_focusedmind',
    maxRanks: 1,
    entryIds: [112299],
  },
  SINGLE_MINDED_FURY_TALENT: {
    id: 81099,
    name: 'Single-Minded Fury',
    icon: 'warrior_talent_icon_singlemindedfury',
    maxRanks: 1,
    entryIds: [112269],
  },
  COLD_STEEL_HOT_BLOOD_TALENT: {
    id: 383959,
    name: 'Cold Steel, Hot Blood',
    icon: 'ability_rogue_hungerforblood',
    maxRanks: 1,
    entryIds: [112271],
  },
  VICIOUS_CONTEMPT_TALENT: {
    id: 383885,
    name: 'Vicious Contempt',
    icon: 'ability_ironmaidens_sorkasprey',
    maxRanks: 2,
    entryIds: [112273],
  },
  FRENZY_TALENT: {
    id: 335077,
    name: 'Frenzy',
    icon: 'ability_rogue_bloodyeye',
    maxRanks: 1,
    entryIds: [112275],
  },
  HACK_AND_SLASH_TALENT: {
    id: 383877,
    name: 'Hack and Slash',
    icon: 'ability_rogue_rollthebones02',
    maxRanks: 1,
    entryIds: [112276],
  },
  SLAUGHTERING_STRIKES_TALENT: {
    id: 388004,
    name: 'Slaughtering Strikes',
    icon: 'inv_axe_2h_orcwarrior_c_01',
    maxRanks: 1,
    entryIds: [112280],
  },
  ASHEN_JUGGERNAUT_TALENT: {
    id: 392536,
    name: 'Ashen Juggernaut',
    icon: 'warrior_talent_icon_skirmisher',
    maxRanks: 1,
    entryIds: [112278],
  },
  IMPROVED_WHIRLWIND_TALENT: {
    id: 12950,
    name: 'Improved Whirlwind',
    icon: 'ability_whirlwind',
    maxRanks: 1,
    entryIds: [112298],
  },
  WRATH_AND_FURY_TALENT: {
    id: 392936,
    name: 'Wrath and Fury',
    icon: 'inv_sword_2h_artifactarathor_d_03',
    maxRanks: 1,
    entryIds: [112255],
  },
  FRENZIED_FLURRY_TALENT: {
    id: 383605,
    name: 'Frenzied Flurry',
    icon: 'ability_ghoulfrenzy',
    maxRanks: 1,
    entryIds: [112293],
  },
  BLOODBORNE_FURY_TALENT: {
    id: 385703,
    name: 'Bloodborne',
    icon: 'inv_artifact_bloodoftheassassinated',
    maxRanks: 1,
    entryIds: [112270],
  },
  BLOODBORNE_PROTECTION_TALENT: {
    id: 385704,
    name: 'Bloodborne',
    icon: 'inv_artifact_bloodoftheassassinated',
    maxRanks: 2,
    entryIds: [112321],
  },
  BLOODBORNE_ARMS_TALENT: {
    id: 383287,
    name: 'Bloodborne',
    icon: 'inv_artifact_bloodoftheassassinated',
    maxRanks: 2,
    entryIds: [112135],
  },
  BLOODCRAZE_TALENT: {
    id: 393950,
    name: 'Bloodcraze',
    icon: 'ability_creature_cursed_02',
    maxRanks: 1,
    entryIds: [112274],
  },
  RECKLESSNESS_TALENT: {
    id: 1719,
    name: 'Recklessness',
    icon: 'warrior_talent_icon_innerrage',
    maxRanks: 1,
    entryIds: [112281],
  },
  MASSACRE_FURY_TALENT: {
    id: 206315,
    name: 'Massacre',
    icon: 'inv_sword_48',
    maxRanks: 1,
    entryIds: [112279],
  },
  MASSACRE_SPEC_TALENT: {
    id: 281001,
    name: 'Massacre',
    icon: 'inv_sword_48',
    maxRanks: 1,
    entryIds: [112168, 112145],
  },
  MEAT_CLEAVER_TALENT: {
    id: 280392,
    name: 'Meat Cleaver',
    icon: 'ability_whirlwind',
    maxRanks: 1,
    entryIds: [112260],
  },
  RAGING_ARMAMENTS_TALENT: {
    id: 388049,
    name: 'Raging Armaments',
    icon: 'achievement_arena_2v2_5',
    maxRanks: 1,
    entryIds: [112297],
  },
  DEFT_EXPERIENCE_FURY_TALENT: {
    id: 383295,
    name: 'Deft Experience',
    icon: 'inv_misc_book_07',
    maxRanks: 2,
    entryIds: [112292],
  },
  DEFT_EXPERIENCE_ARMS_TALENT: {
    id: 389308,
    name: 'Deft Experience',
    icon: 'inv_misc_book_07',
    maxRanks: 2,
    entryIds: [112309],
  },
  SWIFT_STRIKES_TALENT: {
    id: 383459,
    name: 'Swift Strikes',
    icon: 'ability_rogue_sprint',
    maxRanks: 2,
    entryIds: [112286],
  },
  CRITICAL_THINKING_FURY_TALENT: {
    id: 383297,
    name: 'Critical Thinking',
    icon: 'ability_criticalstrike',
    maxRanks: 2,
    entryIds: [112296],
  },
  CRITICAL_THINKING_ARMS_TALENT: {
    id: 389306,
    name: 'Critical Thinking',
    icon: 'ability_criticalstrike',
    maxRanks: 2,
    entryIds: [112317],
  },
  STORM_OF_SWORDS_FURY_TALENT: {
    id: 388903,
    name: 'Storm of Swords',
    icon: 'ability_skyreach_fourblades',
    maxRanks: 1,
    entryIds: [112291],
  },
  STORM_OF_SWORDS_ARMS_TALENT: {
    id: 385512,
    name: 'Storm of Swords',
    icon: 'ability_skyreach_fourblades',
    maxRanks: 1,
    entryIds: [112119],
  },
  ODYNS_FURY_TALENT: {
    id: 385059,
    name: "Odyn's Fury",
    icon: 'inv_sword_1h_artifactvigfus_d_01',
    maxRanks: 1,
    entryIds: [112289],
  },
  ANGER_MANAGEMENT_TALENT: {
    id: 152278,
    name: 'Anger Management',
    icon: 'warrior_talent_icon_angermanagement',
    maxRanks: 1,
    entryIds: [112285, 112166, 112143],
  },
  RECKLESS_ABANDON_TALENT: {
    id: 396749,
    name: 'Reckless Abandon',
    icon: 'spell_fire_incinerate',
    maxRanks: 1,
    entryIds: [112284],
  },
  ONSLAUGHT_TALENT: {
    id: 315720,
    name: 'Onslaught',
    icon: 'ability_warrior_trauma',
    maxRanks: 1,
    entryIds: [112295],
  },
  RAVAGER_TALENT: {
    id: 228920,
    name: 'Ravager',
    icon: 'warrior_talent_icon_ravager',
    maxRanks: 1,
    entryIds: [112256, 112304],
  },
  ANNIHILATOR_TALENT: {
    id: 383916,
    name: 'Annihilator',
    icon: 'ability_warrior_annihilator',
    maxRanks: 1,
    entryIds: [112290],
  },
  DANCING_BLADES_TALENT: {
    id: 391683,
    name: 'Dancing Blades',
    icon: 'inv_sword_1h_artifactvigfus_d_01dual',
    maxRanks: 1,
    entryIds: [112288],
  },
  TITANIC_RAGE_TALENT: {
    id: 394329,
    name: 'Titanic Rage',
    icon: 'inv_sword_1h_artifactvigfus_d_02',
    maxRanks: 1,
    entryIds: [112287],
  },
  UNBRIDLED_FEROCITY_TALENT: {
    id: 389603,
    name: 'Unbridled Ferocity',
    icon: 'ability_warrior_endlessrage',
    maxRanks: 1,
    entryIds: [112283],
  },
  DEPTHS_OF_INSANITY_TALENT: {
    id: 383922,
    name: 'Depths of Insanity',
    icon: 'racial_troll_berserk',
    maxRanks: 1,
    entryIds: [112282],
  },
  TENDERIZE_TALENT: {
    id: 388933,
    name: 'Tenderize',
    icon: 'inv_mace_1h_blacksmithing_b_01_black',
    maxRanks: 1,
    entryIds: [112294],
  },
  STORM_OF_STEEL_TALENT: {
    id: 382953,
    name: 'Storm of Steel',
    icon: 'ability_creature_cursed_04',
    maxRanks: 1,
    entryIds: [112258, 112303],
  },
  HURRICANE_TALENT: {
    id: 390563,
    name: 'Hurricane',
    icon: 'ability_skyreach_wind',
    maxRanks: 1,
    entryIds: [112257, 112312],
  },
  IGNORE_PAIN_TALENT: {
    id: 190456,
    name: 'Ignore Pain',
    icon: 'ability_warrior_renewedvigor',
    maxRanks: 1,
    entryIds: [112149, 114738],
    rageCost: 40,
  },
  REVENGE_TALENT: {
    id: 6572,
    name: 'Revenge',
    icon: 'ability_warrior_revenge',
    maxRanks: 1,
    entryIds: [112152],
    rageCost: 20,
  },
  DEMORALIZING_SHOUT_TALENT: {
    id: 1160,
    name: 'Demoralizing Shout',
    icon: 'ability_warrior_warcry',
    maxRanks: 1,
    entryIds: [112159],
  },
  DEVASTATOR_TALENT: {
    id: 236279,
    name: 'Devastator',
    icon: 'inv_sword_11',
    maxRanks: 1,
    entryIds: [112153],
  },
  LAST_STAND_TALENT: {
    id: 12975,
    name: 'Last Stand',
    icon: 'spell_holy_ashestoashes',
    maxRanks: 1,
    entryIds: [112151],
  },
  IMPROVED_HEROIC_THROW_TALENT: {
    id: 386034,
    name: 'Improved Heroic Throw',
    icon: 'inv_axe_66',
    maxRanks: 1,
    entryIds: [112160],
  },
  BEST_SERVED_COLD_TALENT: {
    id: 202560,
    name: 'Best Served Cold',
    icon: 'ability_warrior_revenge',
    maxRanks: 1,
    entryIds: [112158],
  },
  STRATEGIST_TALENT: {
    id: 384041,
    name: 'Strategist',
    icon: 'inv_shield_05',
    maxRanks: 1,
    entryIds: [112157],
  },
  BRACE_FOR_IMPACT_TALENT: {
    id: 386030,
    name: 'Brace For Impact',
    icon: 'ability_warrior_shieldguard',
    maxRanks: 1,
    entryIds: [112150],
  },
  UNNERVING_FOCUS_TALENT: {
    id: 384042,
    name: 'Unnerving Focus',
    icon: 'rogue_shadowfocus',
    maxRanks: 1,
    entryIds: [112327],
  },
  CHALLENGING_SHOUT_TALENT: {
    id: 1161,
    name: 'Challenging Shout',
    icon: 'ability_bullrush',
    maxRanks: 1,
    entryIds: [112163],
  },
  INSTIGATE_TALENT: {
    id: 394311,
    name: 'Instigate',
    icon: 'ability_rogue_dismantle',
    maxRanks: 1,
    entryIds: [112155],
  },
  REND_PROTECTION_TALENT: {
    id: 394062,
    name: 'Rend',
    icon: 'ability_gouge',
    maxRanks: 1,
    entryIds: [112156],
    rageCost: 30,
  },
  REND_ARMS_TALENT: {
    id: 772,
    name: 'Rend',
    icon: 'ability_gouge',
    maxRanks: 1,
    entryIds: [112136],
    rageCost: 30,
  },
  BLOODSURGE_TALENT: {
    id: 384361,
    name: 'Bloodsurge',
    icon: 'ability_warrior_bloodsurge',
    maxRanks: 1,
    entryIds: [112154, 112129],
  },
  FUELED_BY_VIOLENCE_TALENT: {
    id: 383103,
    name: 'Fueled by Violence',
    icon: 'ability_demonhunter_bloodlet',
    maxRanks: 1,
    entryIds: [112326, 112127],
  },
  BRUTAL_VITALITY_TALENT: {
    id: 384036,
    name: 'Brutal Vitality',
    icon: 'ability_warrior_renewedvigor',
    maxRanks: 1,
    entryIds: [112325],
  },
  DISRUPTING_SHOUT_TALENT: {
    id: 386071,
    name: 'Disrupting Shout',
    icon: 'ability_bullrush',
    maxRanks: 1,
    entryIds: [112161],
  },
  SHOW_OF_FORCE_TALENT: {
    id: 385843,
    name: 'Show of Force',
    icon: 'ability_rogue_reinforcedleather',
    maxRanks: 1,
    entryIds: [112177],
  },
  THUNDERLORD_TALENT: {
    id: 385840,
    name: 'Thunderlord',
    icon: 'ability_vehicle_electrocharge',
    maxRanks: 1,
    entryIds: [112162],
  },
  SHIELD_WALL_TALENT: {
    id: 871,
    name: 'Shield Wall',
    icon: 'ability_warrior_shieldwall',
    maxRanks: 1,
    entryIds: [112167],
  },
  BOLSTER_TALENT: {
    id: 280001,
    name: 'Bolster',
    icon: 'shield_draenorcrafted_d_02_c_alliance',
    maxRanks: 1,
    entryIds: [112115],
  },
  TOUGH_AS_NAILS_TALENT: {
    id: 385888,
    name: 'Tough as Nails',
    icon: 'inv_titanium_shield_spike',
    maxRanks: 1,
    entryIds: [112324],
  },
  SPELL_BLOCK_TALENT: {
    id: 392966,
    name: 'Spell Block',
    icon: 'ability_warrior_shieldbreak',
    maxRanks: 1,
    entryIds: [112110],
  },
  HEAVY_REPERCUSSIONS_TALENT: {
    id: 203177,
    name: 'Heavy Repercussions',
    icon: 'inv_shield_32',
    maxRanks: 1,
    entryIds: [112176],
  },
  INTO_THE_FRAY_TALENT: {
    id: 202603,
    name: 'Into the Fray',
    icon: 'ability_warrior_bloodfrenzy',
    maxRanks: 1,
    entryIds: [112175],
  },
  ENDURING_DEFENSES_TALENT: {
    id: 386027,
    name: 'Enduring Defenses',
    icon: 'ability_defend',
    maxRanks: 1,
    entryIds: [112169],
  },
  DEFENDERS_AEGIS_TALENT: {
    id: 397103,
    name: "Defender's Aegis",
    icon: 'ability_warrior_stalwartprotector',
    maxRanks: 1,
    entryIds: [112165],
  },
  IMPENETRABLE_WALL_TALENT: {
    id: 384072,
    name: 'Impenetrable Wall',
    icon: 'ability_warrior_shieldguard',
    maxRanks: 1,
    entryIds: [112164],
  },
  PUNISH_TALENT: {
    id: 275334,
    name: 'Punish',
    icon: 'ability_deathknight_sanguinfortitude',
    maxRanks: 1,
    entryIds: [112323],
  },
  JUGGERNAUT_PROTECTION_TALENT: {
    id: 393967,
    name: 'Juggernaut',
    icon: 'warrior_talent_icon_skirmisher',
    maxRanks: 1,
    entryIds: [112322],
  },
  JUGGERNAUT_ARMS_TALENT: {
    id: 383292,
    name: 'Juggernaut',
    icon: 'warrior_talent_icon_skirmisher',
    maxRanks: 1,
    entryIds: [112319],
  },
  FOCUSED_VIGOR_TALENT: {
    id: 384067,
    name: 'Focused Vigor',
    icon: 'spell_nature_strength',
    maxRanks: 1,
    entryIds: [112174],
  },
  SHIELD_SPECIALIZATION_TALENT: {
    id: 386011,
    name: 'Shield Specialization',
    icon: 'inv_shield_76',
    maxRanks: 2,
    entryIds: [112171],
  },
  ENDURING_ALACRITY_TALENT: {
    id: 384063,
    name: 'Enduring Alacrity',
    icon: 'spell_nature_unyeildingstamina',
    maxRanks: 1,
    entryIds: [112305],
  },
  SHIELD_CHARGE_TALENT: {
    id: 385952,
    name: 'Shield Charge',
    icon: 'ability_warrior_shieldcharge',
    maxRanks: 1,
    entryIds: [112173],
  },
  BOOMING_VOICE_TALENT: {
    id: 202743,
    name: 'Booming Voice',
    icon: 'ability_warrior_commandingshout',
    maxRanks: 1,
    entryIds: [112170],
  },
  INDOMITABLE_TALENT: {
    id: 202095,
    name: 'Indomitable',
    icon: 'ability_warrior_intensifyrage',
    maxRanks: 1,
    entryIds: [112306],
  },
  VIOLENT_OUTBURST_TALENT: {
    id: 386477,
    name: 'Violent Outburst',
    icon: 'ability_warrior_furiousresolve',
    maxRanks: 1,
    entryIds: [112116],
  },
  BATTERING_RAM_TALENT: {
    id: 394312,
    name: 'Battering Ram',
    icon: 'ability_warrior_bullrush',
    maxRanks: 1,
    entryIds: [112113],
  },
  CHAMPIONS_BULWARK_TALENT: {
    id: 386328,
    name: "Champion's Bulwark",
    icon: 'ability_warrior_shieldmastery',
    maxRanks: 1,
    entryIds: [112172],
  },
  BATTLE_SCARRED_VETERAN_TALENT: {
    id: 386394,
    name: 'Battle-Scarred Veteran',
    icon: 'ability_warrior_endlessrage',
    maxRanks: 1,
    entryIds: [112307],
  },
  DANCE_OF_DEATH_PROTECTION_TALENT: {
    id: 393965,
    name: 'Dance of Death',
    icon: 'ability_butcher_whirl',
    maxRanks: 1,
    entryIds: [112302],
  },
  DANCE_OF_DEATH_ARMS_TALENT: {
    id: 390713,
    name: 'Dance of Death',
    icon: 'ability_butcher_whirl',
    maxRanks: 1,
    entryIds: [114639],
  },
  MORTAL_STRIKE_TALENT: {
    id: 12294,
    name: 'Mortal Strike',
    icon: 'ability_warrior_savageblow',
    maxRanks: 1,
    entryIds: [112122],
    rageCost: 30,
  },
  OVERPOWER_TALENT: {
    id: 7384,
    name: 'Overpower',
    icon: 'ability_meleedamage',
    maxRanks: 1,
    entryIds: [112123],
  },
  MARTIAL_PROWESS_TALENT: {
    id: 316440,
    name: 'Martial Prowess',
    icon: 'ability_warrior_weaponmastery',
    maxRanks: 1,
    entryIds: [112130],
  },
  DIE_BY_THE_SWORD_TALENT: {
    id: 118038,
    name: 'Die by the Sword',
    icon: 'ability_warrior_challange',
    maxRanks: 1,
    entryIds: [112128],
  },
  IMPROVED_OVERPOWER_TALENT: {
    id: 385571,
    name: 'Improved Overpower',
    icon: 'ability_meleedamage',
    maxRanks: 1,
    entryIds: [112131],
  },
  STORM_WALL_TALENT: {
    id: 388807,
    name: 'Storm Wall',
    icon: 'spell_sandstorm',
    maxRanks: 1,
    entryIds: [112121],
  },
  FERVOR_OF_BATTLE_TALENT: {
    id: 202316,
    name: 'Fervor of Battle',
    icon: 'ability_rogue_waylay',
    maxRanks: 1,
    entryIds: [112124],
  },
  TACTICIAN_TALENT: {
    id: 184783,
    name: 'Tactician',
    icon: 'ability_warrior_unrelentingassault',
    maxRanks: 1,
    entryIds: [112134],
  },
  COLOSSUS_SMASH_TALENT: {
    id: 167105,
    name: 'Colossus Smash',
    icon: 'ability_warrior_colossussmash',
    maxRanks: 1,
    entryIds: [112144],
  },
  IMPALE_TALENT: {
    id: 383430,
    name: 'Impale',
    icon: 'ability_searingarrow',
    maxRanks: 1,
    entryIds: [112146],
  },
  SKULLSPLITTER_TALENT: {
    id: 260643,
    name: 'Skullsplitter',
    icon: 'inv_skullsplitter',
    maxRanks: 1,
    entryIds: [112133],
  },
  IMPROVED_SLAM_TALENT: {
    id: 400205,
    name: 'Improved Slam',
    icon: 'ability_warrior_decisivestrike',
    maxRanks: 1,
    entryIds: [114733],
  },
  SPITEFUL_SERENITY_TALENT: {
    id: 400314,
    name: 'Spiteful Serenity',
    icon: 'inv_helmet_08',
    maxRanks: 1,
    entryIds: [114642],
  },
  EXHILARATING_BLOWS_TALENT: {
    id: 383219,
    name: 'Exhilarating Blows',
    icon: 'warrior_talent_icon_igniteweapon',
    maxRanks: 1,
    entryIds: [112138],
  },
  IMPROVED_SWEEPING_STRIKES_TALENT: {
    id: 383155,
    name: 'Improved Sweeping Strikes',
    icon: 'ability_rogue_slicedice',
    maxRanks: 1,
    entryIds: [114641],
  },
  STRENGTH_OF_ARMS_TALENT: {
    id: 400803,
    name: 'Strength of Arms',
    icon: 'inv_gauntlets_26',
    maxRanks: 1,
    entryIds: [114739],
  },
  CLEAVE_TALENT: {
    id: 845,
    name: 'Cleave',
    icon: 'ability_warrior_cleave',
    maxRanks: 1,
    entryIds: [112147],
    rageCost: 20,
  },
  TIDE_OF_BLOOD_TALENT: {
    id: 386357,
    name: 'Tide of Blood',
    icon: 'spell_shadow_bloodboil',
    maxRanks: 1,
    entryIds: [112132],
  },
  DREADNAUGHT_TALENT: {
    id: 262150,
    name: 'Dreadnaught',
    icon: 'inv_sword_05',
    maxRanks: 1,
    entryIds: [112137],
  },
  IN_FOR_THE_KILL_TALENT: {
    id: 248621,
    name: 'In For The Kill',
    icon: 'ability_blackhand_marked4death',
    maxRanks: 1,
    entryIds: [112142],
  },
  TEST_OF_MIGHT_TALENT: {
    id: 385008,
    name: 'Test of Might',
    icon: 'ability_warrior_strengthofarms',
    maxRanks: 1,
    entryIds: [112141],
  },
  BLUNT_INSTRUMENTS_TALENT: {
    id: 383442,
    name: 'Blunt Instruments',
    icon: 'inv_mace_01',
    maxRanks: 1,
    entryIds: [112140],
  },
  WARBREAKER_TALENT: {
    id: 262161,
    name: 'Warbreaker',
    icon: 'inv_warbreaker',
    maxRanks: 1,
    entryIds: [112139],
  },
  COLLATERAL_DAMAGE_TALENT: {
    id: 334779,
    name: 'Collateral Damage',
    icon: 'ability_warrior_incite',
    maxRanks: 1,
    entryIds: [112118],
  },
  REAPING_SWINGS_TALENT: {
    id: 383293,
    name: 'Reaping Swings',
    icon: 'ability_rogue_cuttothechase',
    maxRanks: 1,
    entryIds: [112148],
  },
  VALOR_IN_VICTORY_TALENT: {
    id: 383338,
    name: 'Valor in Victory',
    icon: 'spell_holy_summonchampion',
    maxRanks: 1,
    entryIds: [112315],
  },
  BATTLELORD_TALENT: {
    id: 386630,
    name: 'Battlelord',
    icon: 'ability_pvp_hardiness',
    maxRanks: 1,
    entryIds: [114740],
  },
  BLOODLETTING_TALENT: {
    id: 383154,
    name: 'Bloodletting',
    icon: 'ability_skeer_bloodletting',
    maxRanks: 1,
    entryIds: [112310],
  },
  BLADESTORM_TALENT: {
    id: 227847,
    name: 'Bladestorm',
    icon: 'ability_warrior_bladestorm',
    maxRanks: 1,
    entryIds: [112314],
  },
  SHARPENED_BLADES_TALENT: {
    id: 383341,
    name: 'Sharpened Blades',
    icon: 'inv_sword_27',
    maxRanks: 1,
    entryIds: [112320],
  },
  FATALITY_TALENT: {
    id: 383703,
    name: 'Fatality',
    icon: 'achievement_bg_killingblow_berserker',
    maxRanks: 1,
    entryIds: [112311],
  },
  UNHINGED_TALENT: {
    id: 386628,
    name: 'Unhinged',
    icon: 'ability_warrior_savageblow',
    maxRanks: 1,
    entryIds: [112313],
  },
  MERCILESS_BONEGRINDER_TALENT: {
    id: 383317,
    name: 'Merciless Bonegrinder',
    icon: 'ability_ironmaidens_whirlofblood',
    maxRanks: 1,
    entryIds: [112117],
  },
  EXECUTIONERS_PRECISION_TALENT: {
    id: 386634,
    name: "Executioner's Precision",
    icon: 'inv_sword_48',
    maxRanks: 1,
    entryIds: [112318],
  },
});

export default talents;
export { talents as TALENTS_WARRIOR };
