import React from 'react';

import { Mamtooth, Zerotorescue, Putro, joshinator, Gebuz, ackwell, emallson, blazyb, Dambroda, Nalhan, Satyric, niseko } from 'CONTRIBUTORS';
import ItemLink from 'common/ItemLink';
import ITEMS from 'common/ITEMS';
import SPELLS from 'common/SPELLS';
import SpellLink from 'common/SpellLink';
import Contributor from 'interface/contributor/Button';

export default [
  {
    date: new Date('2018-10-21'),
    changes: <> Added <SpellLink id={SPELLS.BLIGHTBORNE_INFUSION.id} /> module.</>,
    contributors: [niseko],
    clIndex: 'Core20181021.1',
  },
  {
    date: new Date('2018-10-17'),
    changes: <>Fixed mana usage for innervate in cooldown tabs for healers.</>,
    contributors: [blazyb],
    clIndex: 'Core20181017.1',
  },
  {
    date: new Date('2018-10-06'),
    changes: <>Corrected Azerite Scaling for traits with split stat scaling (e.g. <SpellLink id={SPELLS.GEMHIDE.id} />).</>,
    contributors: [emallson],
    clIndex: 'Core20181006.2',
  },
  {
    date: new Date('2018-10-06'),
    changes: <React.Fragment> Added a damage reduction module for dwarf racial <SpellLink id={SPELLS.STONEFORM.id} /> </React.Fragment>,
    contributors: [Satyric],
    clIndex: 'Core20181006.1',
  },
  {
    date: new Date('2018-10-02'),
    changes: 'Added a BFA-ready food and flasker checker to the well prepared checklist, with a lot of help from ArthurEnglebert',
    contributors: [Putro],
    clIndex: 'Core20181002.1',
  },
  {
    date: new Date('2018-09-30'),
    changes: 'Removed the suggestions for Healing Potions and Healthstones, and added their status to the death recap panel. The "you died" suggestions will now refer to this for more information.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180930.3',
  },
  {
    date: new Date('2018-09-30'),
    changes: 'The "you had mana left" suggestion will no longer show up on wipes.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180930.2',
  },
  {
    date: new Date('2018-09-30'),
    changes: 'The "you died" suggestion will no longer show up when you died within 15 seconds of a wipe.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180930.1',
  },
  {
    date: new Date('2018-09-29'),
    changes: 'Added a "spec currently not supported" page, since the about panel appeared to be insufficient.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180929.2',
  },
  {
    date: new Date('2018-09-29'),
    changes: 'Completely reworked the way reports are loaded to be much more maintainable. There were also some minor performance imprpvements.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180929.1',
  },
  {
    date: new Date('2018-09-25'),
    changes: <> Added <SpellLink id={SPELLS.BLESSED_PORTENTS.id} /> module.</>,
    contributors: [Nalhan],
    clIndex: 'Core20180925.1',
  },
  {
    date: new Date('2018-09-24'),
    changes: <> Added <SpellLink id={SPELLS.CONCENTRATED_MENDING.id} /> module. </>,
    contributors: [Nalhan],
    clIndex: 'Core20180924.2',
  },
  {
    date: new Date('2018-09-24'),
    changes: <>Added <SpellLink id={SPELLS.HEED_MY_CALL.id} /> module.</>,
    contributors: [Dambroda],
    clIndex: 'Core20180924.1',
  },
  {
    date: new Date('2018-09-22'),
    changes: <>Added <SpellLink id={SPELLS.GUTRIPPER.id} /> module.</>,
    contributors: [Dambroda],
    clIndex: 'Core20180922.1',
  },
  {
    date: new Date('2018-09-19'),
    changes: <>Added <SpellLink id={SPELLS.OVERWHELMING_POWER.id} /> and <SpellLink id={SPELLS.BLOOD_RITE.id} /> modules.</>,
    contributors: [joshinator],
    clIndex: 'Core20180919.1',
  },
  {
    date: new Date('2018-09-16'),
    changes: 'Added the players azerite traits to the character pane.',
    contributors: [joshinator],
    clIndex: 'Core20180916.2',
  },
  {
    date: new Date('2018-09-17'),
    changes: 'Added Azerite trait Laser Matrix.',
    contributors: [blazyb],
    clIndex: 'Core20180917.4',
  },
  {
    date: new Date('2018-09-17'),
    changes: <>Adds <ItemLink id={ITEMS.GALECALLERS_BOON.id} /> and <ItemLink id={ITEMS.HARLANS_LOADED_DICE.id} /> modules.</>,
    contributors: [Putro],
    clIndex: 'Core20180917.3',
  },
  {
    date: new Date('2018-09-17'),
    changes: <>Added a <SpellLink id={SPELLS.ELEMENTAL_WHIRL.id} /> module.</>,
    contributors: [Putro],
    clIndex: 'Core20180917.2',
  },
  {
    date: new Date('2018-09-17'),
    changes: <>Added a <ItemLink id={ITEMS.DARKMOON_DECK_FATHOMS.id} /> module.</>,
    contributors: [Putro],
    clIndex: 'Core20180917.1',
  },
  {
    date: new Date('2018-09-16'),
    changes: <>Added a <SpellLink id={SPELLS.METICULOUS_SCHEMING.id} />-module.</>,
    contributors: [joshinator],
    clIndex: 'Core20180916.1',
  },
  {
    date: new Date('2018-09-12'),
    changes: 'Added support for item Seabreeze',
    contributors: [blazyb],
    clIndex: 'Core20180912.1',
  },
  {
    date: new Date('2018-09-10'),
    changes: 'Added the engineering weapon enchants to the EnchantChecker and mark them as valid weapon enchants.',
    contributors: [Putro],
    clIndex: 'Core20180910.1',
  },
  {
    date: new Date('2018-08-08'),
    changes: 'Moved the detail tab selection to the left side.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180808.1',
  },
  {
    date: new Date('2018-08-06'),
    changes: 'If a module has a bug that causes an error it will now automatically be disabled instead of crashing.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180806.1',
  },
  {
    date: new Date('2018-08-05'),
    changes: 'Linking a hunter pet doesn\'t crash the analyzer url builder anymore.',
    contributors: [Mamtooth],
    clIndex: 'Core20180805.2',
  },
  {
    date: new Date('2018-08-05'),
    changes: <>Added a <SpellLink id={SPELLS.MIGHT_OF_THE_MOUNTAIN.id} /> racial contribution module. Thanks to @Iyob for the suggestion.</>,
    contributors: [Zerotorescue],
    clIndex: 'Core20180805.1',
  },
  {
    date: new Date('2018-08-04'),
    changes: 'Account for the 1% Critical Strike racial from Blood Elfs.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180804.1',
  },
  {
    date: new Date('2018-08-03'),
    changes: <>Added an <SpellLink id={SPELLS.ARCANE_TORRENT_MANA1.id} /> module that works for all Blood Elfs.</>,
    contributors: [Zerotorescue],
    clIndex: 'Core20180803.1',
  },
  {
    date: new Date('2018-06-24'),
    changes: 'Added tracking of potion cooldowns and split Healthstone into Healthstone and health pots.',
    contributors: [Gebuz],
    clIndex: 'Core20180624.4',
  },
  {
    date: new Date('2018-07-26'),
    changes: <>Updated our GlobalCooldown module to automatically ignore certain casts if we've marked them as not being actual casts. BM Hunter casting two spells (one for buff, one for damage) per <SpellLink id={SPELLS.BARBED_SHOT.id} /> is an example.</>,
    contributors: [Putro],
    clIndex: 'Core20180726.1',
  },
  {
    date: new Date('2018-07-24'),
    changes: 'Added character information fetching from Battle.net (when possible) to gain race information and character thumbnails. The character thumbnail will now be used in the versus-header as per the original design.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180724.1',
  },
  {
    date: new Date('2018-07-21'),
    changes: 'Added a raid health tab to healer roles.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180721.1',
  },
  {
    date: new Date('2018-07-19'),
    changes: <>Fixed Darkmoon Deck: Promises squished mana values.</>,
    contributors: [Zerotorescue],
    clIndex: 'Core20180719.2',
  },
  {
    date: new Date('2018-07-19'),
    changes: <>Fixed a crash when wearing <ItemLink id={ITEMS.DRAPE_OF_SHAME.id} />.</>,
    contributors: [Zerotorescue],
    clIndex: 'Core20180719.1',
  },
  {
    date: new Date('2018-07-15'),
    changes: 'Added a link to the Legion analyzer in the links under the report bar.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180715.1',
  },
  {
    date: new Date('2018-07-11'),
    changes: <>Added support for the <SpellLink id={SPELLS.GEMHIDE.id} /> trait.</>,
    contributors: [emallson],
    clIndex: 'Core20180711.2',
  },
  {
    date: new Date('2018-07-11'),
    changes: <>Parsing time is about 35% quicker! Thanks to <Contributor {...ackwell} /> for showing <a href="https://github.com/WoWAnalyzer/WoWAnalyzer/issues/1799">the idea</a> worked out in <a href="https://github.com/xivanalysis/xivanalysis">xivanalysis</a>.</>,
    contributors: [Zerotorescue],
    clIndex: 'Core20180711.1',
  },
  {
    date: new Date('2018-07-07'),
    changes: 'Implemented a system for localization. We\'ll need to manually add support for localization everywhere before things can be translated, this will take some time.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180707.1',
  },
  {
    date: new Date('2018-07-06'),
    changes: 'Changed tooltips to be static except for large bars in the timeline.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180706.2',
  },
  {
    date: new Date('2018-07-06'),
    changes: 'When switching fights in the results page, the selected tab will now be remembered.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180706.1',
  },
  {
    date: new Date('2018-07-05'),
    changes: 'Added a toggle to the results page to adjust statistics for fight downtime. This is an experimental feature.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180705.1',
  },
  {
    date: new Date('2018-06-28'),
    changes: 'Allow Warcaftlogs- & BattleNet-character-links in the report selecter.',
    contributors: [joshinator],
    clIndex: 'Core20180628.1',
  },
  {
    date: new Date('2018-06-24'),
    changes: <>Changed the <SpellLink id={SPELLS.HEALTHSTONE.id} /> suggestion to always be of minor importance.</>,
    contributors: [Zerotorescue],
    clIndex: 'Core20180624.3',
  },
  {
    date: new Date('2018-06-24'),
    changes: 'Added an "About WoWAnalyzer" panel to the home page and updated the announcement.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180624.2',
  },
  {
    date: new Date('2018-06-24'),
    changes: 'The report history panel will be hidden where there are no entries.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180624.1',
  },
  {
    date: new Date('2018-06-23'),
    changes: 'Revamped all spells with static GCDs or base GCDs different from the class default.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180623.1',
  },
  {
    date: new Date('2018-06-22'),
    changes: 'Added WoWAnalyzer Premium. See the announcement for more information.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180622.2',
  },
  {
    date: new Date('2018-06-22'),
    changes: 'Added "ads" to help fund further development. The "ads" will at some point in the future turn into real ads from an ad platform.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180622.1',
  },
  {
    date: new Date('2018-06-12'),
    changes: 'Updated character selection to default to HPS or DPS as metric, depending on characters last active spec.',
    contributors: [joshinator],
    clIndex: 'Core20180612.1',
  },
  {
    date: new Date('2018-06-08'),
    changes: 'Added Healthstone/Health pots to abilities and the death recap.',
    contributors: [Gebuz],
    clIndex: 'Core20180608.1',
  },
  {
    date: new Date('2018-06-06'),
    changes: 'Fixed the character selection realm dropdown in Mozilla Firefox.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180606.1',
  },
  {
    date: new Date('2018-06-02'),
    changes: 'Improved error handling so the app will no longer permanently stay stuck in a loading state when something unexpected happens.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180602.2',
  },
  {
    date: new Date('2018-06-02'),
    changes: 'Fixed an issue where the character search realm matching was case-sensitive.',
    contributors: [Zerotorescue],
    clIndex: 'Core20180602.1',
  },
  {
    date: new Date('2018-06-01'),
    changes: <>Removed all changelog entries before June 2018, and updated spec contributors to match. If you're interested in older changelogs, visit <a href="https://legion.wowanalyzer.com/">https://legion.wowanalyzer.com/</a>.</>,
    contributors: [Zerotorescue],
    clIndex: 'Core20180601.1',
  },
];
