import { change, date } from 'common/changelog';
import ITEMS from 'common/ITEMS';
import SPELLS from 'common/SPELLS';
import CLASSIC_SPELLS from 'common/SPELLS/classic';
import { Arlie, Ceric, emallson, Gazh, jazminite, KYZ, nullDozzer, oneunreadmail, Putro, Rzial, Seriousnes, Sharrq, Sref, swirl, Taevis, Topple, Trevor, Vetyst, Vollmer, Yellot, } from 'CONTRIBUTORS';
import { ItemLink } from 'interface';
import SpellLink from 'interface/SpellLink';

// prettier-ignore
export default [
  change(date(2025, 11, 26), 'Update to React 19.', [Topple, emallson]),
  change(date(2025, 11, 26), 'Add bosses for Midnight S1.', Topple),
  change(date(2025, 11, 9), 'Redesign fight analysis header.', emallson),
  change(date(2025, 11,  4), 'Generate talents for 12.0.0.64124.', Topple),
  change(date(2025, 10,  28), 'Add MID1 tier set ids.', Vollmer),
  change(date(2025, 10,  14), 'Update CastEfficiencyBar to accept a spell object.', Sharrq),
  change(date(2025, 10,  22), 'Add and Update Guide Components for CastSummary, CastDetail, CastSequence, StatisticCard, and BuffUptimeBar.', Sharrq),
  change(date(2025, 10,  14), 'Replace Babel with oxc and swc.', Topple),
  change(date(2025, 10, 1), <>Fix crash in Protectors of the Endless analysis if the Foundation timeline is shown. Also fix a zoom bug on the phase header.</>, emallson),
  change(date(2025, 9, 25), <>Add <SpellLink spell={SPELLS.PHASE_BLINK.id} /> to the ignored spells.</>, Arlie),
  change(date(2025, 9, 14), 'MoP update for Classic Engineering Item, Spell, and Enchant IDs', jazminite),
  change(date(2025, 9, 12), 'Add background images and timeline abilities for Terrace of Endless Spring', emallson),
  change(date(2025, 9, 5), 'Add page to show analysis errors across all supported specs.', emallson),
  change(date(2025, 8, 25), 'Add option to disable movement warnings on timeline tab.', Topple),
  change(date(2025, 8, 14), <>Updated <ItemLink id={ITEMS.SAD_SOCKET_ADDING_DEVICE.id} /> to <ItemLink id={ITEMS.TECHNOMANCERS_GIFT.id} /> for Head, Belt, and Bracer socket addition</>, Ceric),
  change(date(2025, 8, 11), 'Start hiding Hero Specialization talent node on character page.', Topple),
  change(date(2025, 8, 10), 'Update to patch 11.2', KYZ),
  change(date(2025, 8, 9), 'Fix handling of sockets in D.I.S.C. belt.', emallson),
  change(date(2025, 8, 9), 'Remove Corruption helm enchants from recommendations in 11.2', emallson),
  change(date(2025, 7, 29), 'Add timeline abilities for Mogu\'shan Vaults bosses', emallson),
  change(date(2025, 7, 29), 'Add consumable data for MoP', emallson),
  change(date(2025, 7, 21), 'Add Classic MoP T14 raid zones, headshots, and placeholder image', jazminite),
  change(date(2025, 7, 21), 'Update Death Knight spells for MoP Classic', jazminite),
  change(date(2025, 7, 8), 'Add timeline buff filter', Seriousnes),
  change(date(2025, 6, 8),<>Add <SpellLink spell={SPELLS.LIGHTS_JUDGMENT.id} /> to Lightforged Draenei's racial spellbook.</>, Vetyst),
  change(date(2025, 6, 8),<>Add <SpellLink spell={SPELLS.LIGHTS_JUDGMENT.id} /> to Lightforged Draenei's racial spellbook.</>, Vetyst),
  change(date(2025, 6, 8),<>Fix validateDomNesting warning for Gem Preperation checklist.</>, Vetyst),
  change(date(2025, 6, 8),<>Updated visual appearance of gained stats for <ItemLink id={ITEMS.SUNSET_SPELLTHREAD_R3.id} />, <ItemLink id={ITEMS.WEAVERCLOTH_SPELLTHREAD_R3.id} />, and <ItemLink id={ITEMS.DAYBREAK_SPELLTHREAD_R3.id} /> enchants on the character info tab.</>, Vetyst),
  change(date(2025, 6, 8),<>Move <SpellLink spell={SPELLS.GLIDE_DRACTHYR.id} /> from Evoker's spellbook to Dracthyr's racial spellbook.</>, Vetyst),
  change(date(2025, 6, 5),<>Replaced deprecated package `react-minimalist-portal` used to create tooltips.</>, Vetyst),
  change(date(2025, 6, 4),<>Add Horrific Vision enchants suggestions.</>, Vetyst),
  change(date(2025, 6, 3),<>Mark <ItemLink id={ITEMS.COUNCILS_GUILE_R3.id} />, <ItemLink id={ITEMS.OATHSWORNS_TENACITY_R3.id} />, <ItemLink id={ITEMS.STONEBOUND_ARTISTRY_R3.id} />, and <ItemLink id={ITEMS.STORMRIDERS_FURY_R3.id} /> as max rank enchants</>, Vollmer),
  change(date(2025, 5, 30), 'Add WCL user sign-in & private logs support', Vollmer),
  change(date(2025, 5, 23), 'Regenerate talents for 11.1.5', Vollmer),
  change(date(2025, 5, 17), <>Minimal setup for Mists of Pandaria.</>, emallson),
  change(date(2025, 5, 16), <>Fix number of critical hits not being calculated.</>, swirl),
  change(date(2025, 5, 2), 'All Gems now show on Character Doll', Ceric),
  change(date(2025, 4, 27), 'Recommended Gems now show to the User if setup', Ceric),
  change(date(2025, 4, 25), 'Fix Azjol-Nerub special case for Armory Link', Ceric),
  change(date(2025, 4, 24), 'Streamlined Recommended Gems for Gem Checker', Ceric),
  change(date(2025, 4, 22), 'Added Gems to Preparation Section with general recommendations.', [emallson,Ceric]),
  change(date(2025, 4, 17), 'Add patch 11.1.5.', Vollmer),
  change(date(2025, 4, 12), 'Changed Momentum talent to Exergy for Havoc', oneunreadmail),
  change(date(2025, 3, 29), 'Update ESLint to v9.', Topple),
  change(date(2025, 3, 29), 'Update internal dependencies', emallson),
  change(date(2025, 3, 28), 'Expanded new Foundation downtime section to caster and healer specs.', emallson),
  change(date(2025, 3, 28), <>Add Empower ability handling for Cast Efficiency & Cancelled Casts modules</>, Vollmer),
  change(date(2025, 3, 28), <>Fixed internal ordering of event listener handling</>, Seriousnes),
  change(date(2025, 3, 10), 'Added ability data for Mug\'Zee and Gallywix to the Foundation downtime section', emallson),
  change(date(2025, 3, 8), 'Add missing patch 11.1.0 details.', Topple),
  change(date(2025, 2, 26), <>Revised Foundation downtime section for melee specs.</>, emallson),
  change(date(2025, 2, 18), 'Add Classic Cata Dragon Soul raid zone, headshots, and placeholder image', jazminite),
  change(date(2025, 2, 13), 'Add The War Within Season 2 set IDs.', Putro),
  change(date(2025, 2, 12), 'Fix display issues in dungeon pull selection', emallson),
  change(date(2025, 2, 8), <>Fixed display error in mana usage chart.</>, emallson),
  change(date(2025, 1, 25), <>Added internal support for new <SpellLink spell={SPELLS.SPELL_REFLECTION} /> events</>, emallson),
  change(date(2025, 1, 16), <>Added <ItemLink id={ITEMS.CIRRAL_CONCOCTORY.id}/></>, KYZ),
  change(date(2024, 12, 23), 'Update Classic Guild image for Reports page', jazminite),
  change(date(2024, 12, 21), <>Added <ItemLink id={ITEMS.MERELDARS_TOLL.id}/></>, KYZ),
  change(date(2024, 12, 11), 'Added support for new style of WCL URLs.', emallson),
  change(date(2024, 11, 13), <>Updated common hunter spells and talents with script</>, Yellot),
  change(date(2024, 11, 10), <>Added <ItemLink id={ITEMS.SKARDYNS_GRACE.id}/></>, Yellot),
  change(date(2024, 11, 9),  <>Added <ItemLink id={ITEMS.MAD_QUEENS_MANDATE.id}/> and <ItemLink id={ITEMS.OVINAXS_MERCURIAL_EGG.id}/></>, Yellot),
  change(date(2024, 10, 28), `Updated annotation list rendering for the annotation debugger`, Rzial),
  change(date(2024, 10, 14), `Fixed some technical issues with rendering of lists`, nullDozzer),
  change(date(2024, 10, 12), `Fixed an issue with the effective healing/damage patch causing the per-second damage and healing graphs to be incorrect and causing some by-ability healing and damage numbers to be too low`, Sref),
  change(date(2024, 10, 12), <>Prevent requesting spell data for unknown spell ids.</>, emallson),
  change(date(2024, 10, 7), <>Add the ability of <ItemLink id={ITEMS.TREACHEROUS_TRANSMITTER.id}/> to the spellbook when equipped.</>, Vetyst),
  change(date(2024, 10, 7), <>Updating item level scaling data</>, Seriousnes),
  change(date(2024, 10, 5), 'Fix viewing the character tab for certain regions.', Vetyst),
  change(date(2024, 10, 4), `Fixed many places where absorbed damage and healing was not counted as 'effective'`, Sref),
  change(date(2024, 10, 4), 'Added Earthen food buffs to consumable check.', emallson),
  change(date(2024, 10, 4), <>Added simple statistics for <ItemLink id={ITEMS.SPYMASTERS_WEB.id}/>.</>, Vetyst),
  change(date(2024, 10, 3), 'Fixed rendering of the Header on the character log browser.', Vetyst),
  change(date(2024, 9, 30), 'Add Classic Cata Firelands raid zone, headshots, and placeholder image', jazminite),
  change(date(2024, 9, 30), 'Enchant checker now detects Spellthreads', Sref),
  change(date(2024, 9, 26), "Add support for Warlock Hero Talents", Gazh),
  change(date(2024, 9, 25), 'Fix an error produced on the premium login tab.', Vetyst),
  change(date(2024, 9, 25), 'Show statistic for Tauren crit damage racial. Add all active racials to spellbook, correctly tracking cooldowns.', nullDozzer),
  change(date(2024, 9, 24), 'Update character profile to show gem icons and enchant effects.', Vetyst),
  change(date(2024, 9, 23), 'Fix temporary weapon enchants for all shaman specs', Seriousnes),
  change(date(2024, 9, 23), 'Fix a bug in table filtering. Notably: this fixes a bug with Brewmaster Purifying Brew active tanking time stats.', emallson),
  change(date(2024, 9, 21), 'Update all checks for enchants and consumables for The War Within. Also show more information when suggesting to improve enchants.', nullDozzer),
  change(date(2024, 9, 21), 'Fix another crash in Holy Paladin Divine Purpose.', emallson),
  change(date(2024, 9, 20), 'Ensured that LazyLoadStatisticBox is only requesting the results once.', Arlie),
  change(date(2024, 9, 17), 'Updated Class Guide links for Wowhead to point to correct link.', Taevis),
  change(date(2024, 9, 16), 'Updated spellAvailable APL function to properly adjust validation behaviour based on inverse options, and turn it into an options object rather than a straight boolean', Putro),
  change(date(2024, 9, 15), 'Adding TWW weapon enchants, removing DF-specific items (e.g. Fyralath, Call To Dominance, Voice of the Silent Star, etc)', Seriousnes),
  change(date(2024, 9, 12), 'Fixed crash when analyzing reports where 0 procs of certain effects ocurred.', emallson),
  change(date(2024, 9, 12), 'Add support for Earthen characters.', Topple),
  change(date(2024, 9, 11), 'Update Death Knight spells for Classic Cataclysm', jazminite),
  change(date(2024, 9, 10), 'Change behavior of getLowestPerf when no perfs are provided', Trevor),
  change(date(2024, 9, 9), 'Fix character search showing UNKNOWN instead of THE WAR WITHIN.', Topple),
  change(date(2024, 9, 8), "Add Nerub'ar Palace bosses and season 1 M+ dungeons.", Topple),
  change(date(2024, 9, 6), "Add missing supportID property to DamageEvent interface", Vollmer),
  change(date(2024, 9, 5), 'Update Rogue spells for Classic Cataclysm', jazminite),
  change(date(2024, 9, 4), 'Updates to Active Time calculation to avoid cases where overcount could occur.', Sref),
  change(date(2024, 9, 3), "Fixed a bug where the Death Recap wouldn't detect some defensive buffs", Sref),
  change(date(2024, 9, 3), 'Remove AbilitiesMissing module.', Topple),
  change(date(2024, 8, 30), 'Update Classic Spells, Potions, and Trinkets for Cata Disc Priest.', jazminite),
  change(date(2024, 8, 28), "Update rating to percentage conversions for stats for The War Within.", Putro),
  change(date(2024, 8, 26), <>Add <SpellLink spell={CLASSIC_SPELLS.FLEXWEAVE_UNDERLAY} /> support to Cataclysm Classic specs.</>, jazminite),
  change(date(2024, 8, 25), 'Remove Redux reducer that stored the entire report under analysis.', Topple),
  change(date(2024, 8, 22), 'Update Druid spells for Classic Cataclysm', jazminite),
  change(date(2024, 8, 13), 'Add patch 11.0.2.', Topple),
  change(date(2024, 8, 10), <>Implement buffAndNextCastChannelSpec for channeling normalizer</>, Vollmer),
  change(date(2024, 8, 9), <>Fix the haste bonus of <SpellLink spell={SPELLS.BERSERKING.id} /> in Classic Cataclysm.</>, emallson),
];
