import SPELLS from 'common/SPELLS';
import { TALENTS_EVOKER } from 'common/TALENTS';

export const BASE_ESSENCE_REGEN = 0.2;

export const INNATE_MAGIC_REGEN = 0.05;

export const BASE_MAX_ESSENCE = 5;

export const DEV_ESSENCE_CASTS = [SPELLS.DISINTEGRATE, TALENTS_EVOKER.PYRE_TALENT];

export const PRES_ESSENCE_CASTS = [
  SPELLS.DISINTEGRATE,
  SPELLS.EMERALD_BLOSSOM_CAST,
  TALENTS_EVOKER.ECHO_TALENT,
];
