const SPELLS = {
  ATTACK: {
    id: 88163,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: false,
    hidden: 'always',
    name: 'Attack',
  },
  HEROIC_STRIKE: {
    id: 78,
    type: 'baseline',
    label: [25, 16],
    classMask: [64, 0, 0, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Heroic Strike',
    cooldown: {
      duration: 1500,
      hasted: false,
    },
  },
  CLEAVE: {
    id: 845,
    type: 'baseline',
    label: [25, 16],
    classMask: [4194304, 0, 0, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Cleave',
    cooldown: {
      duration: 1500,
      hasted: false,
    },
  },
  EXECUTE: {
    id: 5308,
    type: 'baseline',
    label: [25, 16],
    classMask: [536870912, 0, 0, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Execute',
    gcd: {
      duration: 1500,
      hasted: false,
    },
  },
  VICTORY_RUSH_1: {
    id: 34428,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 256, 0, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Victory Rush',
    gcd: {
      duration: 1500,
      hasted: false,
    },
  },
  VICTORY_RUSH_2: {
    id: 118779,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 0, 131072, 0],
    effects: [],
    passive: false,
    hidden: 'unless-learned',
    name: 'Victory Rush',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
  },
  THUNDER_CLAP_1: {
    id: 6343,
    type: 'baseline',
    label: [25, 16],
    classMask: [128, 0, 0, 0],
    effects: [
      {
        sourceSpellId: 115799,
        aura: 109,
        basePoints: 100,
        misc0: 1,
        misc1: 0,
        pointModifiers: {},
        triggeredSpell: 115798,
      },
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 12712,
        aura: 107,
        basePoints: -100,
        misc0: 14,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 84615,
        aura: 109,
        basePoints: 100,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
        triggeredSpell: 115767,
      },
      {
        sourceSpellId: 84615,
        aura: 108,
        basePoints: 50,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Thunder Clap',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    cooldown: {
      duration: 6000,
      hasted: false,
    },
  },
  THUNDER_CLAP_2: {
    id: 115799,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    hidden: 'always',
    name: 'Thunder Clap',
  },
  CHARGE: {
    id: 100,
    type: 'baseline',
    label: [25, 16],
    classMask: [1, 0, 0, 1073741824],
    effects: [
      {
        sourceSpellId: 137049,
        aura: 332,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 103826,
        aura: 107,
        basePoints: -8000,
        misc0: 11,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 103827,
        aura: 411,
        basePoints: 2,
        misc0: 1219,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 103827,
        aura: 107,
        basePoints: -19000,
        misc0: 11,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Charge',
    charges: {
      max: 0,
      modifiers: [
        {
          max: 2,
          requiredSpells: [103827],
        },
      ],
    },
    cooldown: {
      duration: 20000,
      hasted: false,
    },
  },
  HEROIC_LEAP_1: {
    id: 6544,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 536870912, 0, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Heroic Leap',
    cooldown: {
      duration: 45000,
      hasted: false,
    },
  },
  HEROIC_LEAP_2: {
    id: 52174,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 536870912, 0, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    hidden: 'always',
    name: 'Heroic Leap',
  },
  SUNDER_ARMOR: {
    id: 7386,
    type: 'baseline',
    label: [25, 16],
    classMask: [16384, 0, 0, 0],
    effects: [
      {
        sourceSpellId: 76838,
        aura: 4,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Sunder Armor',
    gcd: {
      duration: 1500,
      hasted: false,
    },
  },
  TAUNT: {
    id: 355,
    type: 'baseline',
    label: [25, 16],
    classMask: [32768, 0, 0, 0],
    effects: [
      {
        sourceSpellId: 76838,
        aura: 4,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 46924,
        aura: 263,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 114030,
        aura: 108,
        basePoints: -100,
        misc0: 11,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Taunt',
    cooldown: {
      duration: 8000,
      hasted: false,
    },
  },
  BATTLE_STANCE: {
    id: 2457,
    type: 'baseline',
    label: [25, 16],
    classMask: [8388608, 8388608, 0, 0],
    effects: [],
    passive: false,
    name: 'Battle Stance',
    cooldown: {
      duration: 1500,
      hasted: false,
    },
  },
  DEFENSIVE_STANCE: {
    id: 71,
    type: 'baseline',
    label: [25, 16],
    classMask: [8388608, 0, 0, 0],
    effects: [],
    passive: false,
    name: 'Defensive Stance',
    cooldown: {
      duration: 1500,
      hasted: false,
    },
  },
  BATTLE_SHOUT: {
    id: 6673,
    type: 'baseline',
    label: [25, 16],
    classMask: [65536, 0, 0, 0],
    effects: [
      {
        sourceSpellId: 76838,
        aura: 4,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 46924,
        aura: 263,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Battle Shout',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
  },
  HEROIC_THROW: {
    id: 57755,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 1, 0, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Heroic Throw',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
  },
  HAMSTRING: {
    id: 1715,
    type: 'baseline',
    label: [25, 16],
    classMask: [2, 0, 0, 0],
    effects: [],
    passive: false,
    name: 'Hamstring',
    cooldown: {
      duration: 1000,
      hasted: false,
    },
  },
  BERSERKER_STANCE: {
    id: 2458,
    type: 'baseline',
    label: [25, 16],
    classMask: [8388608, 0, 0, 0],
    effects: [],
    passive: false,
    name: 'Berserker Stance',
    cooldown: {
      duration: 1500,
      hasted: false,
    },
  },
  DISARM: {
    id: 676,
    type: 'baseline',
    label: [25, 16],
    classMask: [512, 0, 0, 0],
    effects: [],
    passive: false,
    name: 'Disarm',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
  },
  PUMMEL: {
    id: 6552,
    type: 'baseline',
    label: [25, 16],
    classMask: [8, 0, 0, 0],
    effects: [],
    passive: false,
    name: 'Pummel',
    cooldown: {
      duration: 15000,
      hasted: false,
    },
  },
  SHIELD_WALL: {
    id: 871,
    type: 'baseline',
    label: [25, 16],
    classMask: [8192, 0, 0, 0],
    effects: [
      {
        sourceSpellId: 29725,
        aura: 0,
        basePoints: 7,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 76838,
        aura: 4,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Shield Wall',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
  },
  BERSERKER_RAGE: {
    id: 18499,
    type: 'baseline',
    label: [25, 16],
    classMask: [268435456, 67108864, 0, 0],
    effects: [
      {
        sourceSpellId: 76838,
        aura: 4,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 46924,
        aura: 263,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Berserker Rage',
    cooldown: {
      duration: 30000,
      hasted: false,
    },
  },
  SPELL_REFLECTION: {
    id: 23920,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 2, 0, 0],
    effects: [],
    passive: false,
    name: 'Spell Reflection',
    cooldown: {
      duration: 25000,
      hasted: false,
    },
  },
  COMMANDING_SHOUT: {
    id: 469,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 128, 0, 0],
    effects: [
      {
        sourceSpellId: 46924,
        aura: 263,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Commanding Shout',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
  },
  SHATTERING_THROW_HOTFIX_PASSIVE: {
    id: 1249459,
    grantedBy: 137047,
    type: 'temporary',
    label: [25, 16],
    classMask: [0, 4194304, 0, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 137047,
        aura: 332,
        basePoints: 1249459,
        misc0: 0,
        misc1: 0,
        pointModifiers: [],
      },
    ],
    passive: false,
    name: 'Shattering Throw',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    cooldown: {
      duration: 300000,
      hasted: false,
    },
  },
  SHATTERING_THROW: {
    id: 64382,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 4194304, 0, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 137047,
        aura: 332,
        basePoints: 1249459,
        misc0: 0,
        misc1: 0,
        pointModifiers: [],
      },
    ],
    passive: false,
    name: 'Shattering Throw',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    cooldown: {
      duration: 300000,
      hasted: false,
    },
    castTime: {
      duration: 1500,
    },
  },
  INTERVENE: {
    id: 3411,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 65536, 0, 0],
    effects: [],
    passive: false,
    name: 'Intervene',
    cooldown: {
      duration: 30000,
      hasted: false,
    },
  },
  ENRAGE: {
    id: 13046,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    name: 'Enrage',
  },
  INTIMIDATING_SHOUT: {
    id: 5246,
    type: 'baseline',
    label: [25, 16],
    classMask: [262144, 0, 0, 0],
    effects: [
      {
        sourceSpellId: 46924,
        aura: 263,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Intimidating Shout',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    cooldown: {
      duration: 90000,
      hasted: false,
    },
  },
  SYMBIOSIS: {
    id: 110506,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 0, 128, 0],
    effects: [],
    passive: false,
    name: 'Symbiosis',
  },
  RALLYING_CRY: {
    id: 97462,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 0, 16, 0],
    effects: [
      {
        sourceSpellId: 46924,
        aura: 263,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Rallying Cry',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
  },
  MOCKING_BANNER: {
    id: 114192,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 0, 0, 16],
    effects: [],
    passive: false,
    name: 'Mocking Banner',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
  },
  DEMORALIZING_BANNER: {
    id: 114203,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 0, 0, 8],
    effects: [],
    passive: false,
    name: 'Demoralizing Banner',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
  },
  SKULL_BANNER: {
    id: 114207,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 0, 0, 4],
    effects: [],
    passive: false,
    name: 'Skull Banner',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
  },
  PARRY: {
    id: 3127,
    type: 'baseline',
    label: [25, 16],
    effects: [],
    passive: true,
    name: 'Parry',
  },
  DEEP_WOUNDS_1: {
    id: 115768,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    name: 'Deep Wounds',
  },
  DEEP_WOUNDS_2: {
    id: 115767,
    type: 'baseline',
    label: [25, 16],
    classMask: [32, 16, 0, 0],
    effects: [
      {
        sourceSpellId: 76838,
        aura: 4,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    hidden: 'always',
    name: 'Deep Wounds',
  },
  BLADESTORM_1: {
    id: 50622,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 16384, 0, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Bladestorm',
  },
  BLADESTORM_2: {
    id: 46924,
    type: 'mists-talent',
    row: 3,
    column: 1,
    label: [25, 16],
    classMask: [0, 16384, 0, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    hidden: 'unless-learned',
    name: 'Bladestorm',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
  },
  BLADESTORM_OFF_HAND: {
    id: 95738,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 16384, 0, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Bladestorm Off-Hand',
  },
  THROW: {
    id: 122475,
    type: 'baseline',
    label: [25, 16],
    classMask: [1, 0, 0, 0],
    effects: [
      {
        sourceSpellId: 103826,
        aura: 107,
        basePoints: -8000,
        misc0: 11,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 103827,
        aura: 107,
        basePoints: -19000,
        misc0: 11,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Throw',
    castTime: {
      duration: 500,
    },
  },
  BLOCK: {
    id: 123829,
    type: 'baseline',
    label: [25, 16],
    effects: [],
    passive: true,
    hidden: 'always',
    name: 'Block',
  },
  RECKLESSNESS: {
    id: 1719,
    type: 'baseline',
    label: [25, 16],
    classMask: [16, 0, 0, 0],
    effects: [
      {
        sourceSpellId: 29725,
        aura: 0,
        basePoints: 7,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Recklessness',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
  },
  RAGING_BLOW_OFF_HAND: {
    id: 85384,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 67117056, 0, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 137047,
        aura: 108,
        basePoints: 20,
        misc0: 0,
        misc1: 0,
        pointModifiers: [],
      },
    ],
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Raging Blow Off-Hand',
  },
  WHIRLWIND_OFF_HAND: {
    id: 44949,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 4, 0, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 12712,
        aura: 107,
        basePoints: -100,
        misc0: 14,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Whirlwind Off-Hand',
  },
  SWEEPING_STRIKES_1: {
    id: 12723,
    type: 'baseline',
    classMask: [0, 0, 16384, 0],
    effects: [],
    passive: false,
    hidden: 'always',
    name: 'Sweeping Strikes',
  },
  SWEEPING_STRIKES_2: {
    id: 26654,
    type: 'baseline',
    classMask: [0, 0, 16384, 0],
    effects: [],
    passive: false,
    hidden: 'always',
    name: 'Sweeping Strikes',
  },
  SWEEPING_STRIKES_3: {
    id: 12328,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 1048576, 0, 0],
    effects: [
      {
        sourceSpellId: 137049,
        aura: 107,
        basePoints: -25,
        misc0: 3,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Sweeping Strikes',
    cooldown: {
      duration: 10000,
      hasted: false,
    },
  },
  RAGING_BLOW: {
    id: 96103,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 67117056, 0, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 137047,
        aura: 108,
        basePoints: 20,
        misc0: 0,
        misc1: 0,
        pointModifiers: [],
      },
    ],
    castableWhileCasting: true,
    passive: false,
    hidden: 'always',
    name: 'Raging Blow',
  },
  PUMMEL_SHIELD_VISUAL_OVERRIDE_DND: {
    id: 128217,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    hidden: 'always',
    name: 'Pummel (shield visual override) (DND)',
  },
  OPPORTUNITY_STRIKE: {
    id: 76858,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 0, 262144, 0],
    effects: [],
    passive: false,
    hidden: 'always',
    name: 'Opportunity Strike',
  },
  BLOODBATH_1: {
    id: 113344,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 0, 1024, 0],
    effects: [],
    passive: false,
    hidden: 'always',
    name: 'Bloodbath',
    gcd: {
      duration: 1500,
      hasted: false,
    },
  },
  BLOODBATH_2: {
    id: 12292,
    type: 'mists-talent',
    row: 5,
    column: 2,
    label: [25, 16],
    classMask: [0, 0, 1024, 0],
    effects: [],
    passive: false,
    hidden: 'unless-learned',
    name: 'Bloodbath',
    cooldown: {
      duration: 60000,
      hasted: false,
    },
  },
  BLOODTHIRST_HEAL: {
    id: 117313,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 0, 65536, 0],
    effects: [],
    passive: false,
    hidden: 'unless-learned',
    name: 'Bloodthirst Heal',
  },
  IMPENDING_VICTORY_1: {
    id: 118340,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 0, 131072, 0],
    effects: [],
    passive: false,
    hidden: 'unless-learned',
    name: 'Impending Victory',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
  },
  IMPENDING_VICTORY_2: {
    id: 103840,
    overrides: 34428,
    type: 'mists-talent',
    row: 1,
    column: 3,
    label: [25, 16],
    classMask: [0, 256, 256, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    hidden: 'unless-learned',
    name: 'Impending Victory',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
  },
  HOTFIX_PASSIVE_1: {
    id: 137047,
    type: 'baseline',
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    hidden: 'always',
    name: 'Hotfix Passive',
  },
  HOTFIX_PASSIVE_2: {
    id: 137049,
    type: 'baseline',
    label: [36],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    hidden: 'always',
    name: 'Hotfix Passive',
  },
  MORTAL_STRIKE: {
    id: 12294,
    type: 'baseline',
    label: [25, 16],
    classMask: [33554432, 0, 0, 0],
    effects: [
      {
        sourceSpellId: 115768,
        aura: 4,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 137049,
        aura: 107,
        basePoints: 40,
        misc0: 23,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Mortal Strike',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    cooldown: {
      duration: 6000,
      hasted: false,
    },
  },
  SEASONED_SOLDIER: {
    id: 12712,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    name: 'Seasoned Soldier',
  },
  SLAM: {
    id: 1464,
    type: 'baseline',
    label: [25, 16],
    classMask: [2097152, 0, 0, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 86346,
        aura: 271,
        basePoints: 10,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Slam',
    gcd: {
      duration: 1500,
      hasted: false,
    },
  },
  OVERPOWER: {
    id: 7384,
    type: 'baseline',
    label: [25, 16],
    classMask: [4, 0, 0, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 137049,
        aura: 107,
        basePoints: 20,
        misc0: 3,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Overpower',
    gcd: {
      duration: 1000,
      hasted: false,
    },
  },
  BLOOD_AND_THUNDER: {
    id: 84615,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    name: 'Blood and Thunder',
  },
  SUDDEN_DEATH: {
    id: 29725,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    name: 'Sudden Death',
  },
  PLATE_SPECIALIZATION: {
    id: 86101,
    type: 'baseline',
    effects: [],
    passive: true,
    name: 'Plate Specialization',
  },
  COLOSSUS_SMASH: {
    id: 86346,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 1073741824, 0, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Colossus Smash',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    cooldown: {
      duration: 20000,
      hasted: false,
    },
  },
  WHIRLWIND: {
    id: 1680,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 4, 0, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 12712,
        aura: 107,
        basePoints: -100,
        misc0: 14,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Whirlwind',
    gcd: {
      duration: 1500,
      hasted: false,
    },
  },
  DIE_BY_THE_SWORD: {
    id: 118038,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 0, 0, 2],
    effects: [],
    passive: false,
    name: 'Die by the Sword',
    cooldown: {
      duration: 120000,
      hasted: false,
    },
  },
  OVERPOWER_DRIVER_DND: {
    id: 119938,
    type: 'baseline',
    label: [25, 16],
    effects: [],
    passive: true,
    hidden: 'always',
    name: 'Overpower Driver (DND)',
  },
  MASTERY_STRIKES_OF_OPPORTUNITY: {
    id: 76838,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    name: 'Mastery: Strikes of Opportunity',
  },
  TASTE_FOR_BLOOD: {
    id: 56636,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    name: 'Taste for Blood',
  },
  UNBRIDLED_WRATH: {
    id: 143268,
    type: 'baseline',
    label: [25, 16],
    classMask: [0, 0, 8388608, 0],
    effects: [],
    passive: true,
    hidden: 'unless-learned',
    name: 'Unbridled Wrath',
  },
  SECOND_WIND_1: {
    id: 29838,
    type: 'mists-talent',
    row: 1,
    column: 2,
    label: [25, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    hidden: 'unless-learned',
    name: 'Second Wind',
  },
  SECOND_WIND_2: {
    id: 16491,
    type: 'learned',
    taughtBy: 29838,
    label: [25, 16],
    classMask: [0, 134217728, 8, 0],
    effects: [],
    castableWhileCasting: true,
    passive: true,
    hidden: 'always',
    name: 'Second Wind',
  },
  SHOCKWAVE: {
    id: 46968,
    type: 'mists-talent',
    row: 3,
    column: 2,
    label: [25, 16],
    classMask: [0, 32768, 0, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    hidden: 'unless-learned',
    name: 'Shockwave',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    cooldown: {
      duration: 40000,
      hasted: false,
    },
  },
  UNKNOWN_HOTFIX_PASSIVE: {
    id: 0,
    grantedBy: 137049,
    type: 'temporary',
    effects: [],
    passive: false,
    name: 'Unknown',
  },
  UNKNOWN_1: {
    id: 102052,
    type: 'mists-talent',
    row: 5,
    column: 4,
  },
  UNKNOWN_2: {
    id: 102052,
    type: 'mists-talent',
    row: 0,
    column: 4,
  },
  UNKNOWN_3: {
    id: 102052,
    type: 'mists-talent',
    row: 1,
    column: 4,
  },
  UNKNOWN_4: {
    id: 102052,
    type: 'mists-talent',
    row: 2,
    column: 4,
  },
  UNKNOWN_5: {
    id: 102052,
    type: 'mists-talent',
    row: 3,
    column: 4,
  },
  MASS_SPELL_REFLECTION: {
    id: 114028,
    type: 'mists-talent',
    row: 4,
    column: 1,
    label: [25, 16],
    classMask: [0, 0, 32768, 0],
    effects: [],
    passive: false,
    name: 'Mass Spell Reflection',
    cooldown: {
      duration: 60000,
      hasted: false,
    },
  },
  SAFEGUARD: {
    id: 114029,
    overrides: 3411,
    type: 'mists-talent',
    row: 4,
    column: 2,
    label: [25, 16],
    classMask: [0, 65536, 0, 0],
    effects: [],
    passive: false,
    hidden: 'unless-learned',
    name: 'Safeguard',
    cooldown: {
      duration: 30000,
      hasted: false,
    },
  },
  STAGGERING_SHOUT: {
    id: 107566,
    type: 'mists-talent',
    row: 2,
    column: 1,
    label: [25, 16],
    classMask: [0, 0, 2048, 0],
    effects: [
      {
        sourceSpellId: 46924,
        aura: 263,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    hidden: 'unless-learned',
    name: 'Staggering Shout',
    cooldown: {
      duration: 40000,
      hasted: false,
    },
  },
  PIERCING_HOWL: {
    id: 12323,
    type: 'mists-talent',
    row: 2,
    column: 2,
    label: [25, 16],
    classMask: [0, 32, 0, 0],
    effects: [
      {
        sourceSpellId: 46924,
        aura: 263,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    hidden: 'unless-learned',
    name: 'Piercing Howl',
    gcd: {
      duration: 1500,
      hasted: false,
    },
  },
  DISRUPTING_SHOUT: {
    id: 102060,
    type: 'mists-talent',
    row: 2,
    column: 3,
    label: [25, 16],
    classMask: [0, 0, 64, 0],
    effects: [
      {
        sourceSpellId: 46924,
        aura: 263,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    hidden: 'unless-learned',
    name: 'Disrupting Shout',
    cooldown: {
      duration: 40000,
      hasted: false,
    },
  },
  WARBRINGER: {
    id: 103828,
    type: 'mists-talent',
    row: 0,
    column: 3,
    label: [25, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    hidden: 'unless-learned',
    name: 'Warbringer',
  },
  JUGGERNAUT: {
    id: 103826,
    type: 'mists-talent',
    row: 0,
    column: 1,
    label: [25, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    hidden: 'unless-learned',
    name: 'Juggernaut',
  },
  DOUBLE_TIME: {
    id: 103827,
    type: 'mists-talent',
    row: 0,
    column: 2,
    label: [25, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: true,
    hidden: 'unless-learned',
    name: 'Double Time',
  },
  ENRAGED_REGENERATION: {
    id: 55694,
    type: 'mists-talent',
    row: 1,
    column: 1,
    label: [25, 16],
    classMask: [0, 134348800, 0, 0],
    effects: [
      {
        sourceSpellId: 46924,
        aura: 263,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    hidden: 'unless-learned',
    name: 'Enraged Regeneration',
    cooldown: {
      duration: 60000,
      hasted: false,
    },
  },
  DRAGON_ROAR: {
    id: 118000,
    type: 'mists-talent',
    row: 3,
    column: 3,
    label: [25, 16],
    classMask: [0, 0, 8192, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
      {
        sourceSpellId: 46924,
        aura: 263,
        basePoints: 0,
        misc0: 0,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    name: 'Dragon Roar',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    cooldown: {
      duration: 60000,
      hasted: false,
    },
  },
  DUMMY_50_TALENT: {
    id: 102052,
    type: 'mists-talent',
    row: 4,
    column: 4,
    effects: [],
    passive: false,
    name: 'Dummy 5.0 Talent',
  },
  AVATAR: {
    id: 107574,
    type: 'mists-talent',
    row: 5,
    column: 1,
    label: [25, 16],
    classMask: [1048576, 0, 0, 0],
    effects: [],
    passive: false,
    hidden: 'unless-learned',
    name: 'Avatar',
    cooldown: {
      duration: 180000,
      hasted: false,
    },
  },
  STORM_BOLT: {
    id: 107570,
    type: 'mists-talent',
    row: 5,
    column: 3,
    label: [25, 16],
    classMask: [0, 0, 4096, 0],
    effects: [
      {
        sourceSpellId: 1719,
        aura: 107,
        basePoints: 30,
        misc0: 7,
        misc1: 0,
        pointModifiers: {},
      },
    ],
    passive: false,
    hidden: 'unless-learned',
    name: 'Storm Bolt',
    gcd: {
      duration: 1500,
      hasted: false,
    },
    cooldown: {
      duration: 30000,
      hasted: false,
    },
  },
  VIGILANCE: {
    id: 114030,
    type: 'mists-talent',
    row: 4,
    column: 3,
    label: [25, 16],
    classMask: [0, 0, 0, 0],
    effects: [],
    passive: false,
    hidden: 'unless-learned',
    name: 'Vigilance',
    cooldown: {
      duration: 120000,
      hasted: false,
    },
  },
} as const;
export default SPELLS;
