import SPELLS from 'common/SPELLS';
import Spell from 'common/SPELLS/Spell';
import Combatant from 'parser/core/Combatant';
import { TALENTS_DRUID } from 'common/TALENTS';

export const REJUVENATION_BUFFS: Spell[] = [SPELLS.REJUVENATION, SPELLS.REJUVENATION_GERMINATION];

/** Given count of Druid HoTs on target, gets the multiplier against mastery val to apply */
export function masteryHotCountToMult(hotsOn: number): number {
  if (hotsOn > 10) {
    return 3.65;
  }
  return MASTERY_HOT_COUNT_TO_MULT_TABLE[hotsOn];
}
const MASTERY_HOT_COUNT_TO_MULT_TABLE = [
  0,
  1,
  1.7,
  2.3,
  2.8,
  3.2,
  3.5,
  3.7,
  3.8,
  3.85,
  3.65, // loses value here, probably a bug
];

/** Additional mastery stacks granted by Harmonius Blooming talent */
export const HARMONIUS_BLOOMING_EXTRA_STACKS = 2;

/** This is also the list of spell IDs that are boosted by Druid's mastery */
export const ABILITIES_AFFECTED_BY_HEALING_INCREASES: number[] = [
  SPELLS.REJUVENATION.id,
  SPELLS.REJUVENATION_GERMINATION.id,
  SPELLS.REGROWTH.id,
  SPELLS.WILD_GROWTH.id,
  SPELLS.CULTIVATION.id,
  SPELLS.FRENZIED_REGENERATION.id,
  SPELLS.LIFEBLOOM_HOT_HEAL.id,
  SPELLS.LIFEBLOOM_BLOOM_HEAL.id,
  SPELLS.SWIFTMEND.id,
  SPELLS.TRANQUILITY_HEAL.id,
  SPELLS.EFFLORESCENCE_HEAL.id,
  SPELLS.GROVE_TENDING.id,
  SPELLS.VERDANCY.id,
  SPELLS.GROVE_GUARDIANS_SWIFTMEND.id,
  SPELLS.GROVE_GUARDIANS_NOURISH.id,
  SPELLS.GROVE_GUARDIANS_WILD_GROWTH.id,
  SPELLS.THRIVING_VEGETATION.id,
  SPELLS.SYMBIOTIC_BLOOMS_WILDSTALKER.id,
  SPELLS.BURSTING_GROWTH_HEAL.id,
  SPELLS.DREAM_BLOOM.id,
  SPELLS.FLOWER_WALK.id,
  SPELLS.EMBRACE_OF_THE_DREAM.id,
  SPELLS.DRYAD_REGROWTH.id,
  SPELLS.DRYAD_TRANQUILITY.id,
  SPELLS.DRYAD_SPIRIT_OF_THE_THICKET_HEAL.id,
];

export const ABILITIES_AFFECTED_BY_HEALING_INCREASES_SPELL_OBJECTS =
  ABILITIES_AFFECTED_BY_HEALING_INCREASES.map((id) => SPELLS[id]);

/** IDs of heals that get 100% increased benefit from mastery */
export const DOUBLE_MASTERY_BENEFIT_IDS: number[] = [SPELLS.GROVE_GUARDIANS_NOURISH.id];

/** IDs of all buffs that give a mastery stack */
export const MASTERY_STACK_BUFF_IDS: number[] = [
  SPELLS.REJUVENATION.id,
  SPELLS.REJUVENATION_GERMINATION.id,
  SPELLS.REGROWTH.id,
  SPELLS.WILD_GROWTH.id,
  SPELLS.CULTIVATION.id,
  SPELLS.SPRING_BLOSSOMS.id,
  SPELLS.CENARION_WARD_HEAL.id,
  SPELLS.FRENZIED_REGENERATION.id,
  SPELLS.LIFEBLOOM_BUFF.id,
  SPELLS.SYMBIOTIC_BLOOMS_WILDSTALKER.id,
];

/** Heal id -> aura id when they differ. Lifebloom ticks are 33763, the buff is 1227806. */
export const HEAL_TO_HOT_BUFF_ID: Record<number, number> = {
  [SPELLS.LIFEBLOOM_HOT_HEAL.id]: SPELLS.LIFEBLOOM_BUFF.id,
};

export function hotBuffIdForHeal(healId: number): number {
  return HEAL_TO_HOT_BUFF_ID[healId] ?? healId;
}

// Flourish tracks auras, so Lifebloom is the buff id (1227806).
export const FLOURISH_EXTENDED_HOTS = [
  SPELLS.REJUVENATION,
  SPELLS.REJUVENATION_GERMINATION,
  SPELLS.REGROWTH,
  SPELLS.WILD_GROWTH,
  SPELLS.LIFEBLOOM_BUFF,
];

// Liveliness listens to heal events, so Lifebloom is the tick id (33763).
export const LIVELINESS_INCREASED_RATE = [
  SPELLS.REJUVENATION,
  SPELLS.REJUVENATION_GERMINATION,
  SPELLS.REGROWTH,
  SPELLS.WILD_GROWTH,
  SPELLS.LIFEBLOOM_HOT_HEAL,
  SPELLS.EFFLORESCENCE_HEAL,
  SPELLS.SYMBIOTIC_BLOOMS_WILDSTALKER,
];

// Genesis listens to heal events, so Lifebloom is the tick id (33763). No Efflo on Genesis.
export const GENESIS_BUFFED_HOTS = [
  SPELLS.REJUVENATION,
  SPELLS.REJUVENATION_GERMINATION,
  SPELLS.REGROWTH,
  SPELLS.WILD_GROWTH,
  SPELLS.LIFEBLOOM_HOT_HEAL,
  SPELLS.SYMBIOTIC_BLOOMS_WILDSTALKER,
];

// DoTs that get accelerated by Liveliness for restoration druid.
export const LIVELINESS_INCREASED_DAMAGE_RATE = [
  SPELLS.MOONFIRE_DEBUFF,
  SPELLS.SUNFIRE,
  SPELLS.RAKE_BLEED,
  SPELLS.RIP,
  SPELLS.FERAL_FRENZY_DEBUFF,
  SPELLS.BLOODSEEKER_VINES,
];

// Druid Cooldown cast IDs (reduced by Dreamstate)
export const DRUID_COOLDOWN_IDS: number[] = [
  SPELLS.WILD_GROWTH.id,
  SPELLS.SWIFTMEND.id,
  TALENTS_DRUID.GROVE_GUARDIANS_TALENT.id,
  TALENTS_DRUID.CONVOKE_THE_SPIRITS_TALENT.id,
  TALENTS_DRUID.INCARNATION_TREE_OF_LIFE_TALENT.id,
  TALENTS_DRUID.FLOURISH_TALENT.id,
  TALENTS_DRUID.INNERVATE_TALENT.id,
  TALENTS_DRUID.NATURES_SWIFTNESS_TALENT.id,
  TALENTS_DRUID.IRONBARK_TALENT.id,
  SPELLS.BARKSKIN.id,
];
